In [20]:
import os
import torch
import pandas as pd

from prepData import DataSetup, build_data_from_setup
from discriminate import CenterLoss, ConvBranch, ModulationClassifierReduced, train_classifier, run_experiment, run_experiment_suite
from evaluate import evaluate_classifier

In [21]:
DATA_ROOT = os.path.expanduser("~/adamArchives/Adam/varMax/PADataset/data")
CACHE_ROOT = os.path.expanduser("~/adamArchives/Adam/varMax/PADataset/_feature_cache_nvme/len16384/norm/ota__ota_core_high_run01__high_run01")
device = "cuda" if torch.cuda.is_available() else "cpu"
print("device:", device)

device: cuda

In [22]:
ota_core_experiment_list = []
for unk in ["PA2", "PA3", "PA4", "PA8"]:
    ota_core_experiment_list.append({
        "run_name": f"ota_core_ref_ent005_unk{unk}_c16384_seed0",
        "task": "pa",
        "split_mode": "open_pa",
        "unknown_pas": [unk],

        "normalize": True,
        "cache_len": 16384,
        "cache_root": CACHE_ROOT,     # <-- key: points at cacheBuild output
        "force_rebuild_cache": False, # <-- reuse caches

        "batch_size": 16,
        "seed": 0,

        "source_type": "ota",
        "source_name": "ota_core_high_run01",
        "dataset_tag": "ota_core_high_run01",
        "noise_tag": "high_run01",

        # IMPORTANT: no manifest_path, no source_glob, no protocols restriction
        # (so discovery includes wifi+bluetooth+zigbee once bank files exist)

        "open_val_frac": 0.15,
        "build_balanced_val_open": True,
        "manifold_balance_seed": 0,
        "require_true_val_open": True,
        "allow_val_open_fallback": False,

        "confidence_temperature": 1.0,
        "lr": 2e-4,
        "weight_decay": 0.0,
        "lambda_center": 0.1,
        "label_smoothing": 0.1,
        "entropy_loss_weight": 0.05,
        "mlp_dropout": 0.3,

        "scheduler_name": "cosine",
        "scheduler_min_lr": 1e-7,
        "early_stopping_mode": "open_conf",
        "model_selection_metric": "val_macro_f1",
        "open_conf_selection_metric": "dqn_proxy_expanded5",
        "epochs": 60,
        "early_stopping_patience": 10,

        "save_root": "results_pa_ota_core",
    })

In [23]:
results_df = run_experiment_suite(
    experiment_list=ota_core_experiment_list,
    data_root=DATA_ROOT,
    leaderboard_path="ota_core_ent005_allfolds_leaderboard.csv",
)

================================================================================
Running experiment 1/4
{
  "run_name": "ota_core_ref_ent005_unkPA2_c16384_seed0",
  "task": "pa",
  "split_mode": "open_pa",
  "unknown_pas": [
    "PA2"
  ],
  "normalize": true,
  "cache_len": 16384,
  "cache_root": "/home/atrott/adamArchives/Adam/varMax/PADataset/_feature_cache_nvme/len16384/norm/ota__ota_core_high_run01__high_run01",
  "force_rebuild_cache": false,
  "batch_size": 16,
  "seed": 0,
  "source_type": "ota",
  "source_name": "ota_core_high_run01",
  "dataset_tag": "ota_core_high_run01",
  "noise_tag": "high_run01",
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "lr": 0.0002,
  "weight_decay": 0.0,
  "lambda_center": 0.1,
  "label_smoothing": 0.1,
  "entropy_loss_weight": 0.05,
  "mlp_dropout": 0.3,
  "scheduler_name": "cosine",
  "scheduler_min_lr": 1e-07,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_expanded5",
  "epochs": 60,
  "early_stopping_patience": 10,
  "save_root": "results_pa_ota_core"
}
================================================================================

KeyboardInterrupt:

In [4]:
ota_core_experiment_list = []

for unk in ["PA2", "PA3", "PA4", "PA8"]:
    ota_core_experiment_list.append({
        "run_name": f"ota_core_ref_ent005_unk{unk}_c16384_seed0",
        "task": "pa",
        "split_mode": "open_pa",
        "unknown_pas": [unk],

        "normalize": True,
        "cache_len": 16384,
        "batch_size": 16,
        "seed": 0,

        "source_type": "ota",
        "source_name": "ota_core_high_run01",
        "dataset_tag": "ota_core_high_run01",
        "noise_tag": "high_run01",
        "cache_namespace": "ota_core_high_run01",

        "open_val_frac": 0.15,i dont habe
        "build_balanced_val_open": True,
        "manifold_balance_seed": 0,
        "require_true_val_open": True,
        "allow_val_open_fallback": False,
        "confidence_temperature": 1.0,

        "lr": 2e-4,
        "weight_decay": 0.0,
        "lambda_center": 0.1,
        "label_smoothing": 0.1,
        "entropy_loss_weight": 0.05,
        "mlp_dropout": 0.3,
        "class_weight_mode": None,
        "grad_clip_norm": None,
        "scheduler_name": "cosine",
        "scheduler_factor": 0.5,
        "scheduler_patience": 5,
        "scheduler_min_lr": 1e-7,

        "early_stopping_mode": "open_conf",
        "model_selection_metric": "val_macro_f1",
        "open_conf_selection_metric": "dqn_proxy_expanded5",

        "epochs": 60,
        "early_stopping_patience": 10,

        "save_root": "results_pa_ota_core",
    })

In [5]:
experiment_list = [
    {
        "run_name": "ota_btzb_ref_ent005_unkPA2_c16384_seed0",
        "task": "pa",
        "split_mode": "open_pa",
        "unknown_pas": ["PA2"],
        "normalize": True,
        "cache_len": 16384,
        "batch_size": 16,
        "seed": 0,
        "source_type": "ota",
        "source_name": "ota_core_high_run01",
        "dataset_tag": "ota_core_high_run01",
        "noise_tag": "high_run01",
        "cache_namespace": "ota_core_high_run01",
        "source_glob": "zigbee/ota/ota_core_high_run01/*.mat",
        "protocols": ["bluetooth", "zigbee"],
        "open_val_frac": 0.15,
        "build_balanced_val_open": True,
        "manifold_balance_seed": 0,
        "require_true_val_open": True,
        "allow_val_open_fallback": False,
        "confidence_temperature": 1.0,
        "lr": 5e-4,
        "weight_decay": 0.0,
        "lambda_center": 0.1,
        "label_smoothing": 0.1,
        "entropy_loss_weight": 0.05,
        "mlp_dropout": 0.3,
        "class_weight_mode": None,
        "grad_clip_norm": None,
        "scheduler_name": "cosine",
        "scheduler_factor": 0.5,
        "scheduler_patience": 5,
        "scheduler_min_lr": 1e-7,
        "early_stopping_mode": "open_conf",
        "model_selection_metric": "val_macro_f1",
        "open_conf_selection_metric": "dqn_proxy_expanded5",
        "epochs": 40,
        "early_stopping_patience": 8,
        "save_root": "results_pa_ota_btzb",
    },
    {
        "run_name": "ota_btzb_ref_ent005_unkPA3_c16384_seed0",
        "task": "pa",
        "split_mode": "open_pa",
        "unknown_pas": ["PA3"],
        "normalize": True,
        "cache_len": 16384,
        "batch_size": 16,
        "seed": 0,
        "source_type": "ota",
        "source_name": "ota_core_high_run01",
        "dataset_tag": "ota_core_high_run01",
        "noise_tag": "high_run01",
        "cache_namespace": "ota_core_high_run01",
        "source_glob": "zigbee/ota/ota_core_high_run01/*.mat",
        "protocols": ["bluetooth", "zigbee"],
        "open_val_frac": 0.15,
        "build_balanced_val_open": True,
        "manifold_balance_seed": 0,
        "require_true_val_open": True,
        "allow_val_open_fallback": False,
        "confidence_temperature": 1.0,
        "lr": 5e-4,
        "weight_decay": 0.0,
        "lambda_center": 0.1,
        "label_smoothing": 0.1,
        "entropy_loss_weight": 0.05,
        "mlp_dropout": 0.3,
        "class_weight_mode": None,
        "grad_clip_norm": None,
        "scheduler_name": "cosine",
        "scheduler_factor": 0.5,
        "scheduler_patience": 5,
        "scheduler_min_lr": 1e-7,
        "early_stopping_mode": "open_conf",
        "model_selection_metric": "val_macro_f1",
        "open_conf_selection_metric": "dqn_proxy_expanded5",
        "epochs": 40,
        "early_stopping_patience": 8,
        "save_root": "results_pa_ota_btzb",
    },
    {
        "run_name": "ota_btzb_ref_ent005_unkPA4_c16384_seed0",
        "task": "pa",
        "split_mode": "open_pa",
        "unknown_pas": ["PA4"],
        "normalize": True,
        "cache_len": 16384,
        "batch_size": 16,
        "seed": 0,
        "source_type": "ota",
        "source_name": "ota_core_high_run01",
        "dataset_tag": "ota_core_high_run01",
        "noise_tag": "high_run01",
        "cache_namespace": "ota_core_high_run01",
        "source_glob": "zigbee/ota/ota_core_high_run01/*.mat",
        "protocols": ["bluetooth", "zigbee"],
        "open_val_frac": 0.15,
        "build_balanced_val_open": True,
        "manifold_balance_seed": 0,
        "require_true_val_open": True,
        "allow_val_open_fallback": False,
        "confidence_temperature": 1.0,
        "lr": 5e-4,
        "weight_decay": 0.0,
        "lambda_center": 0.1,
        "label_smoothing": 0.1,
        "entropy_loss_weight": 0.05,
        "mlp_dropout": 0.3,
        "class_weight_mode": None,
        "grad_clip_norm": None,
        "scheduler_name": "cosine",
        "scheduler_factor": 0.5,
        "scheduler_patience": 5,
        "scheduler_min_lr": 1e-7,
        "early_stopping_mode": "open_conf",
        "model_selection_metric": "val_macro_f1",
        "open_conf_selection_metric": "dqn_proxy_expanded5",
        "epochs": 40,
        "early_stopping_patience": 8,
        "save_root": "results_pa_ota_btzb",
    },
]

In [6]:
results_df_remaining = run_experiment_suite(
    experiment_list=experiment_list,
    data_root=DATA_ROOT,
    leaderboard_path="ota_btzb_ent005_remaining_leaderboard.csv",
)

results_df_remaining

================================================================================
Running experiment 1/3
{
  "run_name": "ota_btzb_ref_ent005_unkPA2_c16384_seed0",
  "task": "pa",
  "split_mode": "open_pa",
  "unknown_pas": [
    "PA2"
  ],
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "source_type": "ota",
  "source_name": "ota_core_high_run01",
  "dataset_tag": "ota_core_high_run01",
  "noise_tag": "high_run01",
  "cache_namespace": "ota_core_high_run01",
  "source_glob": "zigbee/ota/ota_core_high_run01/*.mat",
  "protocols": [
    "bluetooth",
    "zigbee"
  ],
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "lr": 0.0005,
  "weight_decay": 0.0,
  "lambda_center": 0.1,
  "label_smoothing": 0.1,
  "entropy_loss_weight": 0.05,
  "mlp_dropout": 0.3,
  "class_weight_mode": null,
  "grad_clip_norm": null,
  "scheduler_name": "cosine",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_expanded5",
  "epochs": 40,
  "early_stopping_patience": 8,
  "save_root": "results_pa_ota_btzb"
}
================================================================================

FileNotFoundError: No raw source files found with pattern: /home/atrott/Adam/varMax/PADataset/data/zigbee/ota/ota_core_high_run01/*.mat

In [9]:
experiment_list = []

for unk in ["PA2", "PA3", "PA4", "PA8"]:
    experiment_list.append({
    "run_name": f"ota_btzb_ref_ent005_unk{unk}_c16384_seed0",
    "task": "pa",
    "split_mode": "open_pa",
    "unknown_pas": [unk],
    
    "normalize": True,
    "cache_len": 16384,
    "batch_size": 16,
    "seed": 0,
    
    "source_type": "ota",
    "source_name": "ota_core_high_run01",
    "dataset_tag": "ota_core_high_run01",
    "noise_tag": "high_run01",
    "cache_namespace": "ota_core_high_run01",
    "source_glob": "zigbee/ota/ota_core_high_run01/*.mat",
    "protocols": ["bluetooth", "zigbee"],
    
    "open_val_frac": 0.15,
    "build_balanced_val_open": True,
    "manifold_balance_seed": 0,
    "require_true_val_open": True,
    "allow_val_open_fallback": False,
    "confidence_temperature": 1.0,
    
    "lr": 5e-4,
    "weight_decay": 0.0,
    "lambda_center": 0.1,
    "label_smoothing": 0.1,
    "entropy_loss_weight": 0.05,
    "mlp_dropout": 0.3,
    "class_weight_mode": None,
    "grad_clip_norm": None,
    "scheduler_name": "cosine",
    "scheduler_factor": 0.5,
    "scheduler_patience": 5,
    "scheduler_min_lr": 1e-7,
    
    "early_stopping_mode": "open_conf",
    "model_selection_metric": "val_macro_f1",
    "open_conf_selection_metric": "dqn_proxy_expanded5",
    
    "epochs": 40,
    "early_stopping_patience": 8,
    
    "save_root": "results_pa_ota_btzb",
})

In [10]:
DATA_ROOT = "/home/atrott/adamArchives/Adam/varMax/PADataset/data"

results_df = run_experiment_suite(
    experiment_list=experiment_list,
    data_root=DATA_ROOT,
    leaderboard_path="ota_btzb_ent005_allfolds_leaderboard.csv",
)

================================================================================
Running experiment 1/4
{
  "run_name": "ota_btzb_ref_ent005_unkPA2_c16384_seed0",
  "task": "pa",
  "split_mode": "open_pa",
  "unknown_pas": [
    "PA2"
  ],
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "source_type": "ota",
  "source_name": "ota_core_high_run01",
  "dataset_tag": "ota_core_high_run01",
  "noise_tag": "high_run01",
  "cache_namespace": "ota_core_high_run01",
  "source_glob": "zigbee/ota/ota_core_high_run01/*.mat",
  "protocols": [
    "bluetooth",
    "zigbee"
  ],
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "lr": 0.0005,
  "weight_decay": 0.0,
  "lambda_center": 0.1,
  "label_smoothing": 0.1,
  "entropy_loss_weight": 0.05,
  "mlp_dropout": 0.3,
  "class_weight_mode": null,
  "grad_clip_norm": null,
  "scheduler_name": "cosine",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_expanded5",
  "epochs": 40,
  "early_stopping_patience": 8,
  "save_root": "results_pa_ota_btzb"
}
================================================================================

FileNotFoundError: No raw source files found with pattern: /home/atrott/adamArchives/Adam/varMax/PADataset/data/zigbee/ota/ota_core_high_run01/*.mat

In [12]:
from prepData import DataSetup, build_data_from_setup

DATA_ROOT = "/home/atrott/adamArchives/Adam/varMax/PADataset/data"

setup_ota_core_bt_zb = DataSetup(
    root=DATA_ROOT,
    task="pa",
    split_mode="open_pa",
    unknown_pas=("PA8",),   # placeholder; change per fold

    normalize=True,
    cache_len=16384,
    force_rebuild_cache=False,

    source_type="ota",
    source_name="ota_core_high_run01",
    dataset_tag="ota_core_high_run01",
    noise_tag="high_run01",
    cache_namespace="ota_core_high_run01",

    # THIS is what stops Wi-Fi from being built now
    source_glob="zigbee/ota/ota_core_high_run01/*.mat",

    # THIS is what makes the dataset use only BT+ZB
    protocols=("bluetooth", "zigbee"),

    build_balanced_val_open=True,
    manifold_balance_seed=0,
    seed=0,
)

In [ ]:
data_bt_zb = build_data_from_setup(
    setup_ota_core_bt_zb,
    batch_size=16,
    num_workers=0,
    pin_memory=True,
)

print(data_bt_zb["meta"])

In [13]:
ota_bt_zb_experiment = {
    "run_name": "ota_core_btzb_ref_ent005_unkPA8_c16384_seed0",
    "task": "pa",
    "split_mode": "open_pa",
    "unknown_pas": ["PA8"],

    "normalize": True,
    "cache_len": 16384,
    "batch_size": 16,
    "seed": 0,

    "source_type": "ota",
    "source_name": "ota_core_high_run01",
    "dataset_tag": "ota_core_high_run01",
    "noise_tag": "high_run01",
    "cache_namespace": "ota_core_high_run01",
    "source_glob": "zigbee/ota/ota_core_high_run01/*.mat",
    "protocols": ["bluetooth", "zigbee"],

    "open_val_frac": 0.15,
    "build_balanced_val_open": True,
    "manifold_balance_seed": 0,
    "require_true_val_open": True,
    "allow_val_open_fallback": False,
    "confidence_temperature": 1.0,

    "lr": 2e-4,
    "weight_decay": 0.0,
    "lambda_center": 0.1,
    "label_smoothing": 0.1,
    "entropy_loss_weight": 0.05,
    "mlp_dropout": 0.3,
    "class_weight_mode": None,
    "grad_clip_norm": None,
    "scheduler_name": "cosine",
    "scheduler_factor": 0.5,
    "scheduler_patience": 5,
    "scheduler_min_lr": 1e-7,

    "early_stopping_mode": "open_conf",
    "model_selection_metric": "val_macro_f1",
    "open_conf_selection_metric": "dqn_proxy_expanded5",

    "epochs": 60,
    "early_stopping_patience": 10,

    "save_root": "results_pa_ota_core_btzb",
}

In [14]:
btzb_lr2e4_pa8 = {
    "run_name": "ota_btzb_ref_lr2e4_unkPA8_c16384_seed0",
    "task": "pa",
    "split_mode": "open_pa",
    "unknown_pas": ["PA8"],

    "normalize": True,
    "cache_len": 16384,
    "batch_size": 16,
    "seed": 0,

    "source_type": "ota",
    "source_name": "ota_core_high_run01",
    "dataset_tag": "ota_core_high_run01",
    "noise_tag": "high_run01",
    "cache_namespace": "ota_core_high_run01",
    "source_glob": "zigbee/ota/ota_core_high_run01/*.mat",
    "protocols": ["bluetooth", "zigbee"],

    "open_val_frac": 0.15,
    "build_balanced_val_open": True,
    "manifold_balance_seed": 0,
    "require_true_val_open": True,
    "allow_val_open_fallback": False,
    "confidence_temperature": 1.0,

    "lr": 2e-4,
    "weight_decay": 0.0,
    "lambda_center": 0.1,
    "label_smoothing": 0.1,
    "entropy_loss_weight": 0.0,
    "mlp_dropout": 0.3,
    "class_weight_mode": None,
    "grad_clip_norm": None,
    "scheduler_name": "cosine",
    "scheduler_factor": 0.5,
    "scheduler_patience": 5,
    "scheduler_min_lr": 1e-7,

    "early_stopping_mode": "open_conf",
    "model_selection_metric": "val_macro_f1",
    "open_conf_selection_metric": "dqn_proxy_expanded5",

    "epochs": 40,
    "early_stopping_patience": 8,

    "save_root": "results_pa_ota_btzb",
}

In [19]:
ota_btzb_experiment_list = [
    btzb_ent005_pa8,
    btzb_lr2e4_pa8,
]

ota_btzb_results_df = run_experiment_suite(
    experiment_list=ota_btzb_experiment_list,
    data_root=DATA_ROOT,
    leaderboard_path="ota_btzb_leaderboard_pa8.csv",
)

================================================================================
Running experiment 1/2
{
  "run_name": "ota_btzb_ref_ent005_unkPA8_c16384_seed0",
  "task": "pa",
  "split_mode": "open_pa",
  "unknown_pas": [
    "PA8"
  ],
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "source_type": "ota",
  "source_name": "ota_core_high_run01",
  "dataset_tag": "ota_core_high_run01",
  "noise_tag": "high_run01",
  "cache_namespace": "ota_core_high_run01",
  "source_glob": "zigbee/ota/ota_core_high_run01/*.mat",
  "protocols": [
    "bluetooth",
    "zigbee"
  ],
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "lr": 0.0005,
  "weight_decay": 0.0,
  "lambda_center": 0.1,
  "label_smoothing": 0.1,
  "entropy_loss_weight": 0.05,
  "mlp_dropout": 0.3,
  "class_weight_mode": null,
  "grad_clip_norm": null,
  "scheduler_name": "cosine",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_expanded5",
  "epochs": 40,
  "early_stopping_patience": 8,
  "save_root": "results_pa_ota_btzb"
}
================================================================================

Epoch 001 | train_loss=0.4054 | ce=0.3258 | ent=0.3118 | center=0.6404 | val_loss=0.1478 | val_acc=0.9984 | val_macro_f1=0.9984 | val_dqn_proxy_softmax3=0.8929 | val_dqn_proxy_expanded5=0.9092

Epoch 002 | train_loss=0.3488 | ce=0.3044 | ent=0.2723 | center=0.3082 | val_loss=0.2087 | val_acc=0.9984 | val_macro_f1=0.9984 | val_dqn_proxy_softmax3=0.8932 | val_dqn_proxy_expanded5=0.8724

Epoch 003 | train_loss=0.3360 | ce=0.3006 | ent=0.2680 | center=0.2200 | val_loss=0.0793 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9747 | val_dqn_proxy_expanded5=0.9336

Epoch 004 | train_loss=0.3278 | ce=0.2976 | ent=0.2656 | center=0.1690 | val_loss=0.1354 | val_acc=0.9992 | val_macro_f1=0.9992 | val_dqn_proxy_softmax3=0.9047 | val_dqn_proxy_expanded5=0.8788

Epoch 005 | train_loss=0.3254 | ce=0.2983 | ent=0.2666 | center=0.1373 | val_loss=0.0994 | val_acc=0.9992 | val_macro_f1=0.9992 | val_dqn_proxy_softmax3=0.9474 | val_dqn_proxy_expanded5=0.9274

Epoch 006 | train_loss=0.3261 | ce=0.3004 | ent=0.2689 | center=0.1234 | val_loss=0.0796 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9542 | val_dqn_proxy_expanded5=0.9359

Epoch 007 | train_loss=0.3186 | ce=0.2962 | ent=0.2653 | center=0.0915 | val_loss=0.0642 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9665 | val_dqn_proxy_expanded5=0.9426

Epoch 008 | train_loss=0.3163 | ce=0.2956 | ent=0.2645 | center=0.0750 | val_loss=0.0799 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9977 | val_dqn_proxy_expanded5=0.9636

Epoch 009 | train_loss=0.3168 | ce=0.2969 | ent=0.2656 | center=0.0660 | val_loss=0.0643 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9795 | val_dqn_proxy_expanded5=0.9556

Epoch 010 | train_loss=0.3168 | ce=0.2976 | ent=0.2667 | center=0.0583 | val_loss=0.0605 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9133 | val_dqn_proxy_expanded5=0.8984

Epoch 011 | train_loss=0.3147 | ce=0.2966 | ent=0.2656 | center=0.0482 | val_loss=0.0679 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.8819 | val_dqn_proxy_expanded5=0.8650

Epoch 012 | train_loss=0.3120 | ce=0.2950 | ent=0.2641 | center=0.0381 | val_loss=0.0602 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.8852 | val_dqn_proxy_expanded5=0.8702

Epoch 013 | train_loss=0.3122 | ce=0.2957 | ent=0.2644 | center=0.0336 | val_loss=0.0750 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9365 | val_dqn_proxy_expanded5=0.9363

Epoch 014 | train_loss=0.3109 | ce=0.2949 | ent=0.2639 | center=0.0276 | val_loss=0.0716 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9586 | val_dqn_proxy_expanded5=0.9174

Epoch 015 | train_loss=0.3104 | ce=0.2948 | ent=0.2639 | center=0.0238 | val_loss=0.0621 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9201 | val_dqn_proxy_expanded5=0.8740

Epoch 016 | train_loss=0.3115 | ce=0.2961 | ent=0.2642 | center=0.0221 | val_loss=0.2892 | val_acc=0.8548 | val_macro_f1=0.8355 | val_dqn_proxy_softmax3=0.5665 | val_dqn_proxy_expanded5=0.6820
Early stopping at epoch 16 (best epoch: 8)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
0,ota_btzb_ref_ent005_unkPA8_c16384_seed0,results_pa_ota_btzb/12-01_05-01-26_ota_btzb_re...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_expanded5,40,0,ota,ota_core_high_run01,ota_core_high_run01,high_run01,"[best_model, final_model]"

================================================================================
Running experiment 2/2
{
  "run_name": "ota_btzb_ref_lr2e4_unkPA8_c16384_seed0",
  "task": "pa",
  "split_mode": "open_pa",
  "unknown_pas": [
    "PA8"
  ],
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "source_type": "ota",
  "source_name": "ota_core_high_run01",
  "dataset_tag": "ota_core_high_run01",
  "noise_tag": "high_run01",
  "cache_namespace": "ota_core_high_run01",
  "source_glob": "zigbee/ota/ota_core_high_run01/*.mat",
  "protocols": [
    "bluetooth",
    "zigbee"
  ],
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "lr": 0.0002,
  "weight_decay": 0.0,
  "lambda_center": 0.1,
  "label_smoothing": 0.1,
  "entropy_loss_weight": 0.0,
  "mlp_dropout": 0.3,
  "class_weight_mode": null,
  "grad_clip_norm": null,
  "scheduler_name": "cosine",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_expanded5",
  "epochs": 40,
  "early_stopping_patience": 8,
  "save_root": "results_pa_ota_btzb"
}
================================================================================

Epoch 001 | train_loss=0.4263 | ce=0.3441 | ent=0.0000 | center=0.8224 | val_loss=0.0713 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9257 | val_dqn_proxy_expanded5=0.9319

Epoch 002 | train_loss=0.3544 | ce=0.3035 | ent=0.0000 | center=0.5096 | val_loss=0.0660 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9695 | val_dqn_proxy_expanded5=0.9455

Epoch 003 | train_loss=0.3380 | ce=0.3006 | ent=0.0000 | center=0.3738 | val_loss=0.0847 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9694 | val_dqn_proxy_expanded5=0.9392

Epoch 004 | train_loss=0.3295 | ce=0.2988 | ent=0.0000 | center=0.3065 | val_loss=0.0772 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9575 | val_dqn_proxy_expanded5=0.9426

Epoch 005 | train_loss=0.3263 | ce=0.2993 | ent=0.0000 | center=0.2700 | val_loss=0.0778 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9898 | val_dqn_proxy_expanded5=0.9613

Epoch 006 | train_loss=0.3219 | ce=0.2980 | ent=0.0000 | center=0.2392 | val_loss=0.0736 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9481 | val_dqn_proxy_expanded5=0.9254

Epoch 007 | train_loss=0.3186 | ce=0.2972 | ent=0.0000 | center=0.2138 | val_loss=0.0631 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9847 | val_dqn_proxy_expanded5=0.9556

Epoch 008 | train_loss=0.3160 | ce=0.2966 | ent=0.0000 | center=0.1944 | val_loss=0.0737 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9978 | val_dqn_proxy_expanded5=0.9662

Epoch 009 | train_loss=0.3132 | ce=0.2957 | ent=0.0000 | center=0.1758 | val_loss=0.1131 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9914 | val_dqn_proxy_expanded5=0.9647

Epoch 010 | train_loss=0.3114 | ce=0.2953 | ent=0.0000 | center=0.1604 | val_loss=0.0749 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9437 | val_dqn_proxy_expanded5=0.9398

Epoch 011 | train_loss=0.3095 | ce=0.2949 | ent=0.0000 | center=0.1460 | val_loss=0.0728 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9668 | val_dqn_proxy_expanded5=0.9571

Epoch 012 | train_loss=0.3081 | ce=0.2946 | ent=0.0000 | center=0.1341 | val_loss=0.0769 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.8049 | val_dqn_proxy_expanded5=0.8683

Epoch 013 | train_loss=0.3068 | ce=0.2945 | ent=0.0000 | center=0.1229 | val_loss=0.0706 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9942 | val_dqn_proxy_expanded5=0.9717

Epoch 014 | train_loss=0.3062 | ce=0.2948 | ent=0.0000 | center=0.1140 | val_loss=0.0651 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9184 | val_dqn_proxy_expanded5=0.9249

Epoch 015 | train_loss=0.3047 | ce=0.2942 | ent=0.0000 | center=0.1048 | val_loss=0.0719 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9363 | val_dqn_proxy_expanded5=0.9398

Epoch 016 | train_loss=0.3051 | ce=0.2952 | ent=0.0000 | center=0.0982 | val_loss=0.0728 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.8232 | val_dqn_proxy_expanded5=0.8703

Epoch 017 | train_loss=0.3032 | ce=0.2942 | ent=0.0000 | center=0.0904 | val_loss=0.0755 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.7272 | val_dqn_proxy_expanded5=0.8201

Epoch 018 | train_loss=0.3024 | ce=0.2940 | ent=0.0000 | center=0.0840 | val_loss=0.0826 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.8585 | val_dqn_proxy_expanded5=0.8833

Epoch 019 | train_loss=0.3017 | ce=0.2939 | ent=0.0000 | center=0.0785 | val_loss=0.0805 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9107 | val_dqn_proxy_expanded5=0.9222

Epoch 020 | train_loss=0.3012 | ce=0.2939 | ent=0.0000 | center=0.0736 | val_loss=0.0679 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.8991 | val_dqn_proxy_expanded5=0.9196

Epoch 021 | train_loss=0.3007 | ce=0.2938 | ent=0.0000 | center=0.0688 | val_loss=0.0749 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.8559 | val_dqn_proxy_expanded5=0.8949
Early stopping at epoch 21 (best epoch: 13)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
1,ota_btzb_ref_lr2e4_unkPA8_c16384_seed0,results_pa_ota_btzb/12-07_05-01-26_ota_btzb_re...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_expanded5,40,0,ota,ota_core_high_run01,ota_core_high_run01,high_run01,"[best_model, epoch_20, final_model]"
0,ota_btzb_ref_ent005_unkPA8_c16384_seed0,results_pa_ota_btzb/12-01_05-01-26_ota_btzb_re...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_expanded5,40,0,ota,ota_core_high_run01,ota_core_high_run01,high_run01,"[best_model, final_model]"

In [2]:
DATA_ROOT = os.path.expanduser("~/Adam/varMax/PADataset/data")

setup = DataSetup(
    root=DATA_ROOT,
    task="pa",                # "pa" or "joint"
    split_mode="closed",      # "closed" or "open_pa"
    unknown_pas=(),           # e.g. ("PA8",) for open set
    normalize=True,
    cache_len=8192,
    force_rebuild_cache=False,
    train_frac=0.70,
    val_frac=0.15,
    seed=0,
)

In [3]:
def make_full_osr_backbone_experiment_list():
    experiment_list = []

    unknown_pas_list = ["PA2", "PA3", "PA4", "PA8"]
    cache_lengths = [4096, 8192, 16384, 32768]
    seeds = [0, 1, 2]

    for unknown_pa in unknown_pas_list:
        for cache_len in cache_lengths:
            for seed in seeds:
                batch_size = 16 if cache_len <= 16384 else 8

                experiment_list.append({
                    "run_name": f"osrbank_unk{unknown_pa}_c{cache_len}_bs{batch_size}_lr5e4_lc01_wd0_seed{seed}",
                    "task": "pa",
                    "split_mode": "open_pa",
                    "unknown_pas": (unknown_pa,),
                    "cache_len": cache_len,
                    "batch_size": batch_size,
                    "lr": 5e-4,
                    "weight_decay": 0.0,
                    "lambda_center": 0.1,
                    "epochs": 100,
                    "early_stopping_patience": None,
                    "seed": seed,
                    "save_root": "results_pa_osr_bank",
                })

    return experiment_list

In [18]:
experiment_list = [
    {
        "run_name": "template",
        "task": "pa",
        "split_mode": "closed",
        "cache_len": 16384,
        "batch_size": 16,
        "lr": 5e-4,
        "weight_decay": 0.0,
        "lambda_center": 0.1,
        "epochs": 40,
        "early_stopping_patience": 8,
        "seed": 1,
        "save_root": "template",
    }
]

In [17]:
results_df = run_experiment_suite(
    experiment_list=experiment_list,
    data_root=DATA_ROOT,
    leaderboard_path="experiment_leaderboard.csv",
)

NameError: name 'experiment_list' is not defined

In [4]:
DATA_ROOT = os.path.expanduser("~/Adam/varMax/PADataset/data")

def make_confmanifold_coarse_sweep_experiment_list():
    unknown_pas_list = ["PA2", "PA3", "PA4", "PA8"]

    base_cfgs = [
        {
            "tag": "baseline_knownonly",
            "lr": 5e-4,
            "weight_decay": 0.0,
            "lambda_center": 0.1,
            "label_smoothing": 0.10,
            "entropy_loss_weight": 0.00,
            "mlp_dropout": 0.30,
            "class_weight_mode": None,
            "grad_clip_norm": None,
            "scheduler_name": "cosine",
            "scheduler_factor": 0.5,
            "scheduler_patience": 5,
            "scheduler_min_lr": 1e-7,
            "early_stopping_mode": "known_only",
            "model_selection_metric": "val_macro_f1",
            "open_conf_selection_metric": "dqn_proxy_softmax3",
            "epochs": 200,
            "early_stopping_patience": 15,
        },
        {
            "tag": "baseline_openconf",
            "lr": 5e-4,
            "weight_decay": 0.0,
            "lambda_center": 0.1,
            "label_smoothing": 0.10,
            "entropy_loss_weight": 0.00,
            "mlp_dropout": 0.30,
            "class_weight_mode": None,
            "grad_clip_norm": None,
            "scheduler_name": "cosine",
            "scheduler_factor": 0.5,
            "scheduler_patience": 5,
            "scheduler_min_lr": 1e-7,
            "early_stopping_mode": "open_conf",
            "model_selection_metric": "val_macro_f1",
            "open_conf_selection_metric": "dqn_proxy_softmax3",
            "epochs": 200,
            "early_stopping_patience": 15,
        },
        {
            "tag": "paperish_mild",
            "lr": 1e-4,
            "weight_decay": 1e-4,
            "lambda_center": 0.1,
            "label_smoothing": 0.00,
            "entropy_loss_weight": 0.02,
            "mlp_dropout": 0.50,
            "class_weight_mode": None,
            "grad_clip_norm": 1.0,
            "scheduler_name": "plateau",
            "scheduler_factor": 0.5,
            "scheduler_patience": 5,
            "scheduler_min_lr": 1e-7,
            "early_stopping_mode": "open_conf",
            "model_selection_metric": "val_macro_f1",
            "open_conf_selection_metric": "dqn_proxy_softmax3",
            "epochs": 200,
            "early_stopping_patience": 15,
        },
        {
            "tag": "paperish_mid",
            "lr": 1e-4,
            "weight_decay": 1e-4,
            "lambda_center": 0.1,
            "label_smoothing": 0.00,
            "entropy_loss_weight": 0.05,
            "mlp_dropout": 0.50,
            "class_weight_mode": None,
            "grad_clip_norm": 1.0,
            "scheduler_name": "plateau",
            "scheduler_factor": 0.5,
            "scheduler_patience": 5,
            "scheduler_min_lr": 1e-7,
            "early_stopping_mode": "open_conf",
            "model_selection_metric": "val_macro_f1",
            "open_conf_selection_metric": "dqn_proxy_softmax3",
            "epochs": 200,
            "early_stopping_patience": 15,
        },
        {
            "tag": "paperish_strong",
            "lr": 1e-4,
            "weight_decay": 1e-4,
            "lambda_center": 0.1,
            "label_smoothing": 0.00,
            "entropy_loss_weight": 0.10,
            "mlp_dropout": 0.50,
            "class_weight_mode": None,
            "grad_clip_norm": 1.0,
            "scheduler_name": "plateau",
            "scheduler_factor": 0.5,
            "scheduler_patience": 5,
            "scheduler_min_lr": 1e-7,
            "early_stopping_mode": "open_conf",
            "model_selection_metric": "val_macro_f1",
            "open_conf_selection_metric": "dqn_proxy_softmax3",
            "epochs": 200,
            "early_stopping_patience": 15,
        },
        {
            "tag": "paperish_mid_nocenter",
            "lr": 1e-4,
            "weight_decay": 1e-4,
            "lambda_center": 0.0,
            "label_smoothing": 0.00,
            "entropy_loss_weight": 0.05,
            "mlp_dropout": 0.50,
            "class_weight_mode": None,
            "grad_clip_norm": 1.0,
            "scheduler_name": "plateau",
            "scheduler_factor": 0.5,
            "scheduler_patience": 5,
            "scheduler_min_lr": 1e-7,
            "early_stopping_mode": "open_conf",
            "model_selection_metric": "val_macro_f1",
            "open_conf_selection_metric": "dqn_proxy_softmax3",
            "epochs": 200,
            "early_stopping_patience": 15,
        },
        {
            "tag": "paperish_mid_lowdrop",
            "lr": 1e-4,
            "weight_decay": 1e-4,
            "lambda_center": 0.1,
            "label_smoothing": 0.00,
            "entropy_loss_weight": 0.05,
            "mlp_dropout": 0.30,
            "class_weight_mode": None,
            "grad_clip_norm": 1.0,
            "scheduler_name": "plateau",
            "scheduler_factor": 0.5,
            "scheduler_patience": 5,
            "scheduler_min_lr": 1e-7,
            "early_stopping_mode": "open_conf",
            "model_selection_metric": "val_macro_f1",
            "open_conf_selection_metric": "dqn_proxy_softmax3",
            "epochs": 200,
            "early_stopping_patience": 15,
        },
        {
            "tag": "paperish_mid_smooth",
            "lr": 1e-4,
            "weight_decay": 1e-4,
            "lambda_center": 0.1,
            "label_smoothing": 0.05,
            "entropy_loss_weight": 0.05,
            "mlp_dropout": 0.50,
            "class_weight_mode": None,
            "grad_clip_norm": 1.0,
            "scheduler_name": "plateau",
            "scheduler_factor": 0.5,
            "scheduler_patience": 5,
            "scheduler_min_lr": 1e-7,
            "early_stopping_mode": "open_conf",
            "model_selection_metric": "val_macro_f1",
            "open_conf_selection_metric": "dqn_proxy_softmax3",
            "epochs": 200,
            "early_stopping_patience": 15,
        },
    ]

    experiment_list = []

    for base in base_cfgs:
        for unknown_pa in unknown_pas_list:
            cfg = {
                "run_name": f"confman_{base['tag']}_unk{unknown_pa}_c16384_seed0",
                "task": "pa",
                "split_mode": "open_pa",
                "unknown_pas": (unknown_pa,),

                "normalize": True,
                "cache_len": 16384,
                "batch_size": 16,
                "seed": 0,

                # true open-val manifold controls
                "open_val_frac": 0.15,
                "build_balanced_val_open": True,
                "manifold_balance_seed": 0,
                "require_true_val_open": True,
                "allow_val_open_fallback": False,

                # confidence manifold evaluation
                "confidence_temperature": 1.0,

                # training levers
                "lr": base["lr"],
                "weight_decay": base["weight_decay"],
                "lambda_center": base["lambda_center"],
                "label_smoothing": base["label_smoothing"],
                "entropy_loss_weight": base["entropy_loss_weight"],
                "mlp_dropout": base["mlp_dropout"],
                "class_weight_mode": base["class_weight_mode"],
                "grad_clip_norm": base["grad_clip_norm"],

                # scheduler / stopping
                "scheduler_name": base["scheduler_name"],
                "scheduler_factor": base["scheduler_factor"],
                "scheduler_patience": base["scheduler_patience"],
                "scheduler_min_lr": base["scheduler_min_lr"],
                "early_stopping_mode": base["early_stopping_mode"],
                "model_selection_metric": base["model_selection_metric"],
                "open_conf_selection_metric": base["open_conf_selection_metric"],

                "epochs": base["epochs"],
                "early_stopping_patience": base["early_stopping_patience"],

                "save_root": "results_pa_confmanifold_coarse",
            }
            experiment_list.append(cfg)

    return experiment_list


experiment_list = make_confmanifold_coarse_sweep_experiment_list()

len(experiment_list), experiment_list[:2]

(32,
 [{'run_name': 'confman_baseline_knownonly_unkPA2_c16384_seed0',
   'task': 'pa',
   'split_mode': 'open_pa',
   'unknown_pas': ('PA2',),
   'normalize': True,
   'cache_len': 16384,
   'batch_size': 16,
   'seed': 0,
   'open_val_frac': 0.15,
   'build_balanced_val_open': True,
   'manifold_balance_seed': 0,
   'require_true_val_open': True,
   'allow_val_open_fallback': False,
   'confidence_temperature': 1.0,
   'lr': 0.0005,
   'weight_decay': 0.0,
   'lambda_center': 0.1,
   'label_smoothing': 0.1,
   'entropy_loss_weight': 0.0,
   'mlp_dropout': 0.3,
   'class_weight_mode': None,
   'grad_clip_norm': None,
   'scheduler_name': 'cosine',
   'scheduler_factor': 0.5,
   'scheduler_patience': 5,
   'scheduler_min_lr': 1e-07,
   'early_stopping_mode': 'known_only',
   'model_selection_metric': 'val_macro_f1',
   'open_conf_selection_metric': 'dqn_proxy_softmax3',
   'epochs': 200,
   'early_stopping_patience': 15,
   'save_root': 'results_pa_confmanifold_coarse'},
  {'run_name': 'confman_baseline_knownonly_unkPA3_c16384_seed0',
   'task': 'pa',
   'split_mode': 'open_pa',
   'unknown_pas': ('PA3',),
   'normalize': True,
   'cache_len': 16384,
   'batch_size': 16,
   'seed': 0,
   'open_val_frac': 0.15,
   'build_balanced_val_open': True,
   'manifold_balance_seed': 0,
   'require_true_val_open': True,
   'allow_val_open_fallback': False,
   'confidence_temperature': 1.0,
   'lr': 0.0005,
   'weight_decay': 0.0,
   'lambda_center': 0.1,
   'label_smoothing': 0.1,
   'entropy_loss_weight': 0.0,
   'mlp_dropout': 0.3,
   'class_weight_mode': None,
   'grad_clip_norm': None,
   'scheduler_name': 'cosine',
   'scheduler_factor': 0.5,
   'scheduler_patience': 5,
   'scheduler_min_lr': 1e-07,
   'early_stopping_mode': 'known_only',
   'model_selection_metric': 'val_macro_f1',
   'open_conf_selection_metric': 'dqn_proxy_softmax3',
   'epochs': 200,
   'early_stopping_patience': 15,
   'save_root': 'results_pa_confmanifold_coarse'}])

In [6]:
results_df = run_experiment_suite(
    experiment_list=experiment_list,
    data_root=DATA_ROOT,
    leaderboard_path="confmanifold_coarse_leaderboard.csv",
)

================================================================================
Running experiment 1/32
{
  "run_name": "confman_baseline_knownonly_unkPA2_c16384_seed0",
  "task": "pa",
  "split_mode": "open_pa",
  "unknown_pas": [
    "PA2"
  ],
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "lr": 0.0005,
  "weight_decay": 0.0,
  "lambda_center": 0.1,
  "label_smoothing": 0.1,
  "entropy_loss_weight": 0.0,
  "mlp_dropout": 0.3,
  "class_weight_mode": null,
  "grad_clip_norm": null,
  "scheduler_name": "cosine",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "early_stopping_mode": "known_only",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "epochs": 200,
  "early_stopping_patience": 15,
  "save_root": "results_pa_confmanifold_coarse"
}
================================================================================

Epoch 001 | train_loss=0.6519 | ce=0.5483 | ent=0.0000 | center=1.0359 | val_loss=0.2313 | val_acc=0.9481 | val_macro_f1=0.9484 | val_dqn_proxy_softmax3=0.6805 | val_dqn_proxy_expanded5=0.7075

Epoch 002 | train_loss=0.4764 | ce=0.3950 | ent=0.0000 | center=0.8138 | val_loss=0.1487 | val_acc=0.9778 | val_macro_f1=0.9779 | val_dqn_proxy_softmax3=0.6791 | val_dqn_proxy_expanded5=0.7216

Epoch 003 | train_loss=0.4276 | ce=0.3594 | ent=0.0000 | center=0.6817 | val_loss=0.1199 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7197 | val_dqn_proxy_expanded5=0.7242

Epoch 004 | train_loss=0.4109 | ce=0.3513 | ent=0.0000 | center=0.5958 | val_loss=0.1285 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8221 | val_dqn_proxy_expanded5=0.8279

Epoch 005 | train_loss=0.4101 | ce=0.3548 | ent=0.0000 | center=0.5522 | val_loss=0.1104 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8026 | val_dqn_proxy_expanded5=0.7795

Epoch 006 | train_loss=0.3866 | ce=0.3373 | ent=0.0000 | center=0.4926 | val_loss=0.1032 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8959 | val_dqn_proxy_expanded5=0.8573

Epoch 007 | train_loss=0.3743 | ce=0.3297 | ent=0.0000 | center=0.4462 | val_loss=0.0982 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8754 | val_dqn_proxy_expanded5=0.8845

Epoch 008 | train_loss=0.3601 | ce=0.3196 | ent=0.0000 | center=0.4058 | val_loss=0.0926 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8962 | val_dqn_proxy_expanded5=0.8487

Epoch 009 | train_loss=0.3566 | ce=0.3198 | ent=0.0000 | center=0.3680 | val_loss=0.1399 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7879 | val_dqn_proxy_expanded5=0.8248

Epoch 010 | train_loss=0.3732 | ce=0.3371 | ent=0.0000 | center=0.3607 | val_loss=0.0908 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8071 | val_dqn_proxy_expanded5=0.7952

Epoch 011 | train_loss=0.3710 | ce=0.3374 | ent=0.0000 | center=0.3366 | val_loss=0.0684 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7084 | val_dqn_proxy_expanded5=0.7422

Epoch 012 | train_loss=0.3609 | ce=0.3294 | ent=0.0000 | center=0.3155 | val_loss=0.0918 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6669 | val_dqn_proxy_expanded5=0.7578

Epoch 013 | train_loss=0.3523 | ce=0.3234 | ent=0.0000 | center=0.2884 | val_loss=0.0953 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6335 | val_dqn_proxy_expanded5=0.7367

Epoch 014 | train_loss=0.3404 | ce=0.3142 | ent=0.0000 | center=0.2625 | val_loss=0.0968 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6137 | val_dqn_proxy_expanded5=0.7341

Epoch 015 | train_loss=0.3420 | ce=0.3173 | ent=0.0000 | center=0.2478 | val_loss=0.1134 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8387 | val_dqn_proxy_expanded5=0.8549

Epoch 016 | train_loss=0.3381 | ce=0.3147 | ent=0.0000 | center=0.2341 | val_loss=0.0856 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7352 | val_dqn_proxy_expanded5=0.7815

Epoch 017 | train_loss=0.3346 | ce=0.3129 | ent=0.0000 | center=0.2167 | val_loss=0.0815 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9147 | val_dqn_proxy_expanded5=0.8514

Epoch 018 | train_loss=0.3374 | ce=0.3165 | ent=0.0000 | center=0.2088 | val_loss=0.0928 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8532 | val_dqn_proxy_expanded5=0.8252

Epoch 019 | train_loss=0.3321 | ce=0.3126 | ent=0.0000 | center=0.1951 | val_loss=0.0898 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8084 | val_dqn_proxy_expanded5=0.8229

Epoch 020 | train_loss=0.3335 | ce=0.3150 | ent=0.0000 | center=0.1857 | val_loss=0.1062 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6752 | val_dqn_proxy_expanded5=0.7801

Epoch 021 | train_loss=0.3297 | ce=0.3123 | ent=0.0000 | center=0.1736 | val_loss=0.1018 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7542 | val_dqn_proxy_expanded5=0.8054
Early stopping at epoch 21 (best epoch: 6)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
0,confman_baseline_knownonly_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-19_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"

================================================================================
Running experiment 2/32
{
  "run_name": "confman_baseline_knownonly_unkPA3_c16384_seed0",
  "task": "pa",
  "split_mode": "open_pa",
  "unknown_pas": [
    "PA3"
  ],
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "lr": 0.0005,
  "weight_decay": 0.0,
  "lambda_center": 0.1,
  "label_smoothing": 0.1,
  "entropy_loss_weight": 0.0,
  "mlp_dropout": 0.3,
  "class_weight_mode": null,
  "grad_clip_norm": null,
  "scheduler_name": "cosine",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "early_stopping_mode": "known_only",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "epochs": 200,
  "early_stopping_patience": 15,
  "save_root": "results_pa_confmanifold_coarse"
}
================================================================================

Epoch 001 | train_loss=0.7017 | ce=0.5956 | ent=0.0000 | center=1.0608 | val_loss=0.2537 | val_acc=0.9481 | val_macro_f1=0.9479 | val_dqn_proxy_softmax3=0.8259 | val_dqn_proxy_expanded5=0.8050

Epoch 002 | train_loss=0.5210 | ce=0.4347 | ent=0.0000 | center=0.8627 | val_loss=0.1305 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8742 | val_dqn_proxy_expanded5=0.8059

Epoch 003 | train_loss=0.5002 | ce=0.4246 | ent=0.0000 | center=0.7563 | val_loss=0.3692 | val_acc=0.8704 | val_macro_f1=0.8653 | val_dqn_proxy_softmax3=0.7918 | val_dqn_proxy_expanded5=0.7574

Epoch 004 | train_loss=0.4778 | ce=0.4093 | ent=0.0000 | center=0.6855 | val_loss=0.1640 | val_acc=0.9444 | val_macro_f1=0.9442 | val_dqn_proxy_softmax3=0.7143 | val_dqn_proxy_expanded5=0.7283

Epoch 005 | train_loss=0.4165 | ce=0.3566 | ent=0.0000 | center=0.5991 | val_loss=0.1910 | val_acc=0.9407 | val_macro_f1=0.9403 | val_dqn_proxy_softmax3=0.9446 | val_dqn_proxy_expanded5=0.9352

Epoch 006 | train_loss=0.4267 | ce=0.3726 | ent=0.0000 | center=0.5406 | val_loss=0.1494 | val_acc=0.9704 | val_macro_f1=0.9703 | val_dqn_proxy_softmax3=0.9030 | val_dqn_proxy_expanded5=0.8702

Epoch 007 | train_loss=0.4390 | ce=0.3874 | ent=0.0000 | center=0.5152 | val_loss=0.1073 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.8624 | val_dqn_proxy_expanded5=0.7971

Epoch 008 | train_loss=0.3963 | ce=0.3502 | ent=0.0000 | center=0.4608 | val_loss=0.1094 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9371 | val_dqn_proxy_expanded5=0.8943

Epoch 009 | train_loss=0.3891 | ce=0.3469 | ent=0.0000 | center=0.4225 | val_loss=0.1704 | val_acc=0.9556 | val_macro_f1=0.9554 | val_dqn_proxy_softmax3=0.9397 | val_dqn_proxy_expanded5=0.9220

Epoch 010 | train_loss=0.3823 | ce=0.3430 | ent=0.0000 | center=0.3936 | val_loss=0.1025 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.9342 | val_dqn_proxy_expanded5=0.8808

Epoch 011 | train_loss=0.3829 | ce=0.3460 | ent=0.0000 | center=0.3683 | val_loss=0.0843 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9756 | val_dqn_proxy_expanded5=0.9508

Epoch 012 | train_loss=0.3783 | ce=0.3447 | ent=0.0000 | center=0.3356 | val_loss=0.1059 | val_acc=0.9704 | val_macro_f1=0.9703 | val_dqn_proxy_softmax3=0.9522 | val_dqn_proxy_expanded5=0.9460

Epoch 013 | train_loss=0.3716 | ce=0.3395 | ent=0.0000 | center=0.3206 | val_loss=0.0984 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9030 | val_dqn_proxy_expanded5=0.8609

Epoch 014 | train_loss=0.3781 | ce=0.3479 | ent=0.0000 | center=0.3023 | val_loss=0.1081 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.8135 | val_dqn_proxy_expanded5=0.8586

Epoch 015 | train_loss=0.3629 | ce=0.3342 | ent=0.0000 | center=0.2867 | val_loss=0.1071 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8984 | val_dqn_proxy_expanded5=0.8767

Epoch 016 | train_loss=0.3636 | ce=0.3368 | ent=0.0000 | center=0.2676 | val_loss=0.1139 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.8977 | val_dqn_proxy_expanded5=0.8407

Epoch 017 | train_loss=0.3565 | ce=0.3306 | ent=0.0000 | center=0.2585 | val_loss=0.0928 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.7860 | val_dqn_proxy_expanded5=0.7844

Epoch 018 | train_loss=0.3548 | ce=0.3307 | ent=0.0000 | center=0.2407 | val_loss=0.0990 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.9582 | val_dqn_proxy_expanded5=0.9210

Epoch 019 | train_loss=0.3499 | ce=0.3270 | ent=0.0000 | center=0.2286 | val_loss=0.0814 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9888 | val_dqn_proxy_expanded5=0.9809

Epoch 020 | train_loss=0.3576 | ce=0.3355 | ent=0.0000 | center=0.2218 | val_loss=0.1447 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.9498 | val_dqn_proxy_expanded5=0.9390

Epoch 021 | train_loss=0.3598 | ce=0.3384 | ent=0.0000 | center=0.2134 | val_loss=0.1147 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9485 | val_dqn_proxy_expanded5=0.8908

Epoch 022 | train_loss=0.3542 | ce=0.3342 | ent=0.0000 | center=0.1997 | val_loss=0.1136 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9763 | val_dqn_proxy_expanded5=0.9646

Epoch 023 | train_loss=0.3397 | ce=0.3210 | ent=0.0000 | center=0.1879 | val_loss=0.1052 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9548 | val_dqn_proxy_expanded5=0.9013

Epoch 024 | train_loss=0.3359 | ce=0.3185 | ent=0.0000 | center=0.1746 | val_loss=0.0927 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9757 | val_dqn_proxy_expanded5=0.9430

Epoch 025 | train_loss=0.3393 | ce=0.3220 | ent=0.0000 | center=0.1721 | val_loss=0.0782 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9734 | val_dqn_proxy_expanded5=0.9494

Epoch 026 | train_loss=0.3427 | ce=0.3263 | ent=0.0000 | center=0.1640 | val_loss=0.1033 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9306 | val_dqn_proxy_expanded5=0.8655

Epoch 027 | train_loss=0.3373 | ce=0.3216 | ent=0.0000 | center=0.1570 | val_loss=0.1091 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9749 | val_dqn_proxy_expanded5=0.9484

Epoch 028 | train_loss=0.3431 | ce=0.3273 | ent=0.0000 | center=0.1579 | val_loss=0.1015 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9833 | val_dqn_proxy_expanded5=0.9576

Epoch 029 | train_loss=0.3449 | ce=0.3300 | ent=0.0000 | center=0.1490 | val_loss=0.1723 | val_acc=0.9630 | val_macro_f1=0.9628 | val_dqn_proxy_softmax3=0.8061 | val_dqn_proxy_expanded5=0.7924

Epoch 030 | train_loss=0.3516 | ce=0.3368 | ent=0.0000 | center=0.1482 | val_loss=0.0836 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9660 | val_dqn_proxy_expanded5=0.9119

Epoch 031 | train_loss=0.3469 | ce=0.3329 | ent=0.0000 | center=0.1399 | val_loss=0.0948 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8402 | val_dqn_proxy_expanded5=0.8240

Epoch 032 | train_loss=0.3341 | ce=0.3203 | ent=0.0000 | center=0.1372 | val_loss=0.0921 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9750 | val_dqn_proxy_expanded5=0.9366
Early stopping at epoch 32 (best epoch: 17)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
0,confman_baseline_knownonly_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-19_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,confman_baseline_knownonly_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-21_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"

================================================================================
Running experiment 3/32
{
  "run_name": "confman_baseline_knownonly_unkPA4_c16384_seed0",
  "task": "pa",
  "split_mode": "open_pa",
  "unknown_pas": [
    "PA4"
  ],
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "lr": 0.0005,
  "weight_decay": 0.0,
  "lambda_center": 0.1,
  "label_smoothing": 0.1,
  "entropy_loss_weight": 0.0,
  "mlp_dropout": 0.3,
  "class_weight_mode": null,
  "grad_clip_norm": null,
  "scheduler_name": "cosine",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "early_stopping_mode": "known_only",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "epochs": 200,
  "early_stopping_patience": 15,
  "save_root": "results_pa_confmanifold_coarse"
}
================================================================================

Epoch 001 | train_loss=0.7401 | ce=0.6248 | ent=0.0000 | center=1.1529 | val_loss=0.3163 | val_acc=0.8963 | val_macro_f1=0.8935 | val_dqn_proxy_softmax3=0.7347 | val_dqn_proxy_expanded5=0.6780

Epoch 002 | train_loss=0.5749 | ce=0.4796 | ent=0.0000 | center=0.9523 | val_loss=0.2144 | val_acc=0.9519 | val_macro_f1=0.9520 | val_dqn_proxy_softmax3=0.7594 | val_dqn_proxy_expanded5=0.7014

Epoch 003 | train_loss=0.4904 | ce=0.4083 | ent=0.0000 | center=0.8207 | val_loss=0.1750 | val_acc=0.9556 | val_macro_f1=0.9555 | val_dqn_proxy_softmax3=0.8838 | val_dqn_proxy_expanded5=0.8701

Epoch 004 | train_loss=0.4633 | ce=0.3896 | ent=0.0000 | center=0.7367 | val_loss=0.2175 | val_acc=0.9444 | val_macro_f1=0.9441 | val_dqn_proxy_softmax3=0.9438 | val_dqn_proxy_expanded5=0.8226

Epoch 005 | train_loss=0.4279 | ce=0.3626 | ent=0.0000 | center=0.6538 | val_loss=0.1718 | val_acc=0.9444 | val_macro_f1=0.9441 | val_dqn_proxy_softmax3=0.8419 | val_dqn_proxy_expanded5=0.7591

Epoch 006 | train_loss=0.4230 | ce=0.3641 | ent=0.0000 | center=0.5886 | val_loss=0.1174 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.7761 | val_dqn_proxy_expanded5=0.7465

Epoch 007 | train_loss=0.4091 | ce=0.3551 | ent=0.0000 | center=0.5405 | val_loss=0.1328 | val_acc=0.9593 | val_macro_f1=0.9591 | val_dqn_proxy_softmax3=0.9122 | val_dqn_proxy_expanded5=0.8362

Epoch 008 | train_loss=0.3998 | ce=0.3503 | ent=0.0000 | center=0.4954 | val_loss=0.1085 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.8511 | val_dqn_proxy_expanded5=0.7935

Epoch 009 | train_loss=0.3918 | ce=0.3453 | ent=0.0000 | center=0.4653 | val_loss=0.1153 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9238 | val_dqn_proxy_expanded5=0.8668

Epoch 010 | train_loss=0.3954 | ce=0.3523 | ent=0.0000 | center=0.4313 | val_loss=0.1413 | val_acc=0.9630 | val_macro_f1=0.9629 | val_dqn_proxy_softmax3=0.7315 | val_dqn_proxy_expanded5=0.7724

Epoch 011 | train_loss=0.3912 | ce=0.3497 | ent=0.0000 | center=0.4154 | val_loss=0.1150 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9655 | val_dqn_proxy_expanded5=0.8771

Epoch 012 | train_loss=0.3697 | ce=0.3326 | ent=0.0000 | center=0.3714 | val_loss=0.1063 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.7545 | val_dqn_proxy_expanded5=0.7295

Epoch 013 | train_loss=0.3655 | ce=0.3308 | ent=0.0000 | center=0.3470 | val_loss=0.1044 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7752 | val_dqn_proxy_expanded5=0.7386

Epoch 014 | train_loss=0.3651 | ce=0.3328 | ent=0.0000 | center=0.3237 | val_loss=0.1827 | val_acc=0.9407 | val_macro_f1=0.9403 | val_dqn_proxy_softmax3=0.7279 | val_dqn_proxy_expanded5=0.7266

Epoch 015 | train_loss=0.3593 | ce=0.3286 | ent=0.0000 | center=0.3068 | val_loss=0.1063 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.7705 | val_dqn_proxy_expanded5=0.7597

Epoch 016 | train_loss=0.3808 | ce=0.3505 | ent=0.0000 | center=0.3029 | val_loss=0.0694 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.8579 | val_dqn_proxy_expanded5=0.8154

Epoch 017 | train_loss=0.3742 | ce=0.3454 | ent=0.0000 | center=0.2874 | val_loss=0.1069 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.7735 | val_dqn_proxy_expanded5=0.7419

Epoch 018 | train_loss=0.3540 | ce=0.3276 | ent=0.0000 | center=0.2649 | val_loss=0.0962 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7750 | val_dqn_proxy_expanded5=0.7605

Epoch 019 | train_loss=0.3530 | ce=0.3278 | ent=0.0000 | center=0.2512 | val_loss=0.0882 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.7654 | val_dqn_proxy_expanded5=0.7695

Epoch 020 | train_loss=0.3466 | ce=0.3232 | ent=0.0000 | center=0.2341 | val_loss=0.0980 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.8005 | val_dqn_proxy_expanded5=0.7831

Epoch 021 | train_loss=0.3485 | ce=0.3262 | ent=0.0000 | center=0.2231 | val_loss=0.1056 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.7634 | val_dqn_proxy_expanded5=0.7656

Epoch 022 | train_loss=0.3359 | ce=0.3150 | ent=0.0000 | center=0.2098 | val_loss=0.1211 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.6852 | val_dqn_proxy_expanded5=0.7343

Epoch 023 | train_loss=0.3479 | ce=0.3277 | ent=0.0000 | center=0.2021 | val_loss=0.1592 | val_acc=0.9741 | val_macro_f1=0.9740 | val_dqn_proxy_softmax3=0.7690 | val_dqn_proxy_expanded5=0.7590

Epoch 024 | train_loss=0.3584 | ce=0.3377 | ent=0.0000 | center=0.2063 | val_loss=0.2273 | val_acc=0.9296 | val_macro_f1=0.9288 | val_dqn_proxy_softmax3=0.8788 | val_dqn_proxy_expanded5=0.8315

Epoch 025 | train_loss=0.3482 | ce=0.3291 | ent=0.0000 | center=0.1913 | val_loss=0.1228 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.7757 | val_dqn_proxy_expanded5=0.7620

Epoch 026 | train_loss=0.3419 | ce=0.3240 | ent=0.0000 | center=0.1797 | val_loss=0.1383 | val_acc=0.9741 | val_macro_f1=0.9740 | val_dqn_proxy_softmax3=0.7637 | val_dqn_proxy_expanded5=0.7381

Epoch 027 | train_loss=0.3379 | ce=0.3207 | ent=0.0000 | center=0.1727 | val_loss=0.0952 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9624 | val_dqn_proxy_expanded5=0.9011

Epoch 028 | train_loss=0.3355 | ce=0.3195 | ent=0.0000 | center=0.1596 | val_loss=0.1075 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.7639 | val_dqn_proxy_expanded5=0.7668

Epoch 029 | train_loss=0.3400 | ce=0.3238 | ent=0.0000 | center=0.1620 | val_loss=0.0874 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9595 | val_dqn_proxy_expanded5=0.9028

Epoch 030 | train_loss=0.3392 | ce=0.3239 | ent=0.0000 | center=0.1531 | val_loss=0.1084 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.7841 | val_dqn_proxy_expanded5=0.7670

Epoch 031 | train_loss=0.3273 | ce=0.3126 | ent=0.0000 | center=0.1468 | val_loss=0.0784 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.7907 | val_dqn_proxy_expanded5=0.7789

Epoch 032 | train_loss=0.3317 | ce=0.3179 | ent=0.0000 | center=0.1380 | val_loss=0.0886 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.7815 | val_dqn_proxy_expanded5=0.7764
Early stopping at epoch 32 (best epoch: 17)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
0,confman_baseline_knownonly_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-19_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,confman_baseline_knownonly_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-21_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,confman_baseline_knownonly_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-24_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"

================================================================================
Running experiment 4/32
{
  "run_name": "confman_baseline_knownonly_unkPA8_c16384_seed0",
  "task": "pa",
  "split_mode": "open_pa",
  "unknown_pas": [
    "PA8"
  ],
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "lr": 0.0005,
  "weight_decay": 0.0,
  "lambda_center": 0.1,
  "label_smoothing": 0.1,
  "entropy_loss_weight": 0.0,
  "mlp_dropout": 0.3,
  "class_weight_mode": null,
  "grad_clip_norm": null,
  "scheduler_name": "cosine",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "early_stopping_mode": "known_only",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "epochs": 200,
  "early_stopping_patience": 15,
  "save_root": "results_pa_confmanifold_coarse"
}
================================================================================

Epoch 001 | train_loss=0.5880 | ce=0.4784 | ent=0.0000 | center=1.0965 | val_loss=0.1701 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8906 | val_dqn_proxy_expanded5=0.8929

Epoch 002 | train_loss=0.4274 | ce=0.3462 | ent=0.0000 | center=0.8124 | val_loss=0.1235 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9610 | val_dqn_proxy_expanded5=0.9412

Epoch 003 | train_loss=0.4125 | ce=0.3441 | ent=0.0000 | center=0.6849 | val_loss=0.1274 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9121 | val_dqn_proxy_expanded5=0.9158

Epoch 004 | train_loss=0.4054 | ce=0.3447 | ent=0.0000 | center=0.6073 | val_loss=0.1427 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9058 | val_dqn_proxy_expanded5=0.9100

Epoch 005 | train_loss=0.3970 | ce=0.3417 | ent=0.0000 | center=0.5532 | val_loss=0.1115 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9804 | val_dqn_proxy_expanded5=0.9798

Epoch 006 | train_loss=0.3727 | ce=0.3244 | ent=0.0000 | center=0.4826 | val_loss=0.1027 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9587 | val_dqn_proxy_expanded5=0.9598

Epoch 007 | train_loss=0.3618 | ce=0.3179 | ent=0.0000 | center=0.4383 | val_loss=0.0835 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9805 | val_dqn_proxy_expanded5=0.9740

Epoch 008 | train_loss=0.3517 | ce=0.3123 | ent=0.0000 | center=0.3934 | val_loss=0.0958 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9800 | val_dqn_proxy_expanded5=0.9788

Epoch 009 | train_loss=0.3449 | ce=0.3093 | ent=0.0000 | center=0.3563 | val_loss=0.1016 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9730 | val_dqn_proxy_expanded5=0.9542

Epoch 010 | train_loss=0.3413 | ce=0.3089 | ent=0.0000 | center=0.3246 | val_loss=0.1010 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9690 | val_dqn_proxy_expanded5=0.9596

Epoch 011 | train_loss=0.3387 | ce=0.3087 | ent=0.0000 | center=0.3004 | val_loss=0.0941 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9590 | val_dqn_proxy_expanded5=0.9493

Epoch 012 | train_loss=0.3385 | ce=0.3102 | ent=0.0000 | center=0.2835 | val_loss=0.0809 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9055 | val_dqn_proxy_expanded5=0.9029

Epoch 013 | train_loss=0.3353 | ce=0.3082 | ent=0.0000 | center=0.2712 | val_loss=0.0926 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9852 | val_dqn_proxy_expanded5=0.9624

Epoch 014 | train_loss=0.3380 | ce=0.3122 | ent=0.0000 | center=0.2586 | val_loss=0.0777 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9268 | val_dqn_proxy_expanded5=0.9034

Epoch 015 | train_loss=0.3318 | ce=0.3076 | ent=0.0000 | center=0.2415 | val_loss=0.0919 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9920 | val_dqn_proxy_expanded5=0.9753

Epoch 016 | train_loss=0.3290 | ce=0.3064 | ent=0.0000 | center=0.2262 | val_loss=0.1062 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8741 | val_dqn_proxy_expanded5=0.8710

Epoch 017 | train_loss=0.3280 | ce=0.3065 | ent=0.0000 | center=0.2150 | val_loss=0.0844 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9076 | val_dqn_proxy_expanded5=0.9211

Epoch 018 | train_loss=0.3255 | ce=0.3054 | ent=0.0000 | center=0.2003 | val_loss=0.0906 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9412 | val_dqn_proxy_expanded5=0.9329

Epoch 019 | train_loss=0.3241 | ce=0.3048 | ent=0.0000 | center=0.1937 | val_loss=0.1070 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8350 | val_dqn_proxy_expanded5=0.8432

Epoch 020 | train_loss=0.3244 | ce=0.3059 | ent=0.0000 | center=0.1845 | val_loss=0.1065 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8595 | val_dqn_proxy_expanded5=0.8538

Epoch 021 | train_loss=0.3244 | ce=0.3064 | ent=0.0000 | center=0.1801 | val_loss=0.0847 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8874 | val_dqn_proxy_expanded5=0.8765

Epoch 022 | train_loss=0.3207 | ce=0.3040 | ent=0.0000 | center=0.1670 | val_loss=0.0991 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9896 | val_dqn_proxy_expanded5=0.9713
Early stopping at epoch 22 (best epoch: 7)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
3,confman_baseline_knownonly_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-26_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,confman_baseline_knownonly_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-19_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,confman_baseline_knownonly_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-21_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,confman_baseline_knownonly_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-24_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"

================================================================================
Running experiment 5/32
{
  "run_name": "confman_baseline_openconf_unkPA2_c16384_seed0",
  "task": "pa",
  "split_mode": "open_pa",
  "unknown_pas": [
    "PA2"
  ],
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "lr": 0.0005,
  "weight_decay": 0.0,
  "lambda_center": 0.1,
  "label_smoothing": 0.1,
  "entropy_loss_weight": 0.0,
  "mlp_dropout": 0.3,
  "class_weight_mode": null,
  "grad_clip_norm": null,
  "scheduler_name": "cosine",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "epochs": 200,
  "early_stopping_patience": 15,
  "save_root": "results_pa_confmanifold_coarse"
}
================================================================================

Epoch 001 | train_loss=0.6384 | ce=0.5338 | ent=0.0000 | center=1.0468 | val_loss=0.1541 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6786 | val_dqn_proxy_expanded5=0.6904

Epoch 002 | train_loss=0.4462 | ce=0.3638 | ent=0.0000 | center=0.8242 | val_loss=0.1024 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.5745 | val_dqn_proxy_expanded5=0.6534

Epoch 003 | train_loss=0.4540 | ce=0.3818 | ent=0.0000 | center=0.7217 | val_loss=0.2310 | val_acc=0.9556 | val_macro_f1=0.9552 | val_dqn_proxy_softmax3=0.8479 | val_dqn_proxy_expanded5=0.8437

Epoch 004 | train_loss=0.4212 | ce=0.3556 | ent=0.0000 | center=0.6559 | val_loss=0.1297 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7176 | val_dqn_proxy_expanded5=0.7610

Epoch 005 | train_loss=0.4108 | ce=0.3531 | ent=0.0000 | center=0.5763 | val_loss=0.1364 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6742 | val_dqn_proxy_expanded5=0.7062

Epoch 006 | train_loss=0.3933 | ce=0.3410 | ent=0.0000 | center=0.5224 | val_loss=0.1107 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7139 | val_dqn_proxy_expanded5=0.7425

Epoch 007 | train_loss=0.3886 | ce=0.3415 | ent=0.0000 | center=0.4711 | val_loss=0.0954 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8828 | val_dqn_proxy_expanded5=0.8971

Epoch 008 | train_loss=0.3958 | ce=0.3503 | ent=0.0000 | center=0.4546 | val_loss=0.0889 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6561 | val_dqn_proxy_expanded5=0.6980

Epoch 009 | train_loss=0.3739 | ce=0.3325 | ent=0.0000 | center=0.4141 | val_loss=0.0858 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7097 | val_dqn_proxy_expanded5=0.7082

Epoch 010 | train_loss=0.3717 | ce=0.3335 | ent=0.0000 | center=0.3817 | val_loss=0.0753 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9313 | val_dqn_proxy_expanded5=0.9255

Epoch 011 | train_loss=0.3544 | ce=0.3196 | ent=0.0000 | center=0.3473 | val_loss=0.0765 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8556 | val_dqn_proxy_expanded5=0.8450

Epoch 012 | train_loss=0.3529 | ce=0.3209 | ent=0.0000 | center=0.3202 | val_loss=0.0986 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7568 | val_dqn_proxy_expanded5=0.7363

Epoch 013 | train_loss=0.3516 | ce=0.3220 | ent=0.0000 | center=0.2961 | val_loss=0.0819 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7971 | val_dqn_proxy_expanded5=0.7931

Epoch 014 | train_loss=0.3442 | ce=0.3167 | ent=0.0000 | center=0.2752 | val_loss=0.0841 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7810 | val_dqn_proxy_expanded5=0.7617

Epoch 015 | train_loss=0.3400 | ce=0.3146 | ent=0.0000 | center=0.2543 | val_loss=0.1010 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6419 | val_dqn_proxy_expanded5=0.6615

Epoch 016 | train_loss=0.3370 | ce=0.3133 | ent=0.0000 | center=0.2374 | val_loss=0.1082 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6550 | val_dqn_proxy_expanded5=0.6710

Epoch 017 | train_loss=0.3396 | ce=0.3168 | ent=0.0000 | center=0.2283 | val_loss=0.0886 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7348 | val_dqn_proxy_expanded5=0.7247

Epoch 018 | train_loss=0.3356 | ce=0.3146 | ent=0.0000 | center=0.2107 | val_loss=0.1024 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.5598 | val_dqn_proxy_expanded5=0.6583

Epoch 019 | train_loss=0.3377 | ce=0.3176 | ent=0.0000 | center=0.2013 | val_loss=0.1322 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7444 | val_dqn_proxy_expanded5=0.7253

Epoch 020 | train_loss=0.3320 | ce=0.3126 | ent=0.0000 | center=0.1934 | val_loss=0.1026 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6629 | val_dqn_proxy_expanded5=0.6834

Epoch 021 | train_loss=0.3293 | ce=0.3112 | ent=0.0000 | center=0.1806 | val_loss=0.1116 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6400 | val_dqn_proxy_expanded5=0.7394

Epoch 022 | train_loss=0.3328 | ce=0.3154 | ent=0.0000 | center=0.1748 | val_loss=0.1067 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6309 | val_dqn_proxy_expanded5=0.6865

Epoch 023 | train_loss=0.3304 | ce=0.3134 | ent=0.0000 | center=0.1700 | val_loss=0.1065 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6585 | val_dqn_proxy_expanded5=0.7075

Epoch 024 | train_loss=0.3294 | ce=0.3132 | ent=0.0000 | center=0.1620 | val_loss=0.1051 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6798 | val_dqn_proxy_expanded5=0.7025

Epoch 025 | train_loss=0.3276 | ce=0.3124 | ent=0.0000 | center=0.1518 | val_loss=0.0916 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8442 | val_dqn_proxy_expanded5=0.8360
Early stopping at epoch 25 (best epoch: 10)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
3,confman_baseline_knownonly_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-26_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,confman_baseline_openconf_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-28_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,confman_baseline_knownonly_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-19_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,confman_baseline_knownonly_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-21_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,confman_baseline_knownonly_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-24_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"

================================================================================
Running experiment 6/32
{
  "run_name": "confman_baseline_openconf_unkPA3_c16384_seed0",
  "task": "pa",
  "split_mode": "open_pa",
  "unknown_pas": [
    "PA3"
  ],
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "lr": 0.0005,
  "weight_decay": 0.0,
  "lambda_center": 0.1,
  "label_smoothing": 0.1,
  "entropy_loss_weight": 0.0,
  "mlp_dropout": 0.3,
  "class_weight_mode": null,
  "grad_clip_norm": null,
  "scheduler_name": "cosine",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "epochs": 200,
  "early_stopping_patience": 15,
  "save_root": "results_pa_confmanifold_coarse"
}
================================================================================

Epoch 001 | train_loss=0.7204 | ce=0.6080 | ent=0.0000 | center=1.1236 | val_loss=0.2209 | val_acc=0.9370 | val_macro_f1=0.9368 | val_dqn_proxy_softmax3=0.8559 | val_dqn_proxy_expanded5=0.8613

Epoch 002 | train_loss=0.5197 | ce=0.4285 | ent=0.0000 | center=0.9128 | val_loss=0.2568 | val_acc=0.9185 | val_macro_f1=0.9179 | val_dqn_proxy_softmax3=0.8860 | val_dqn_proxy_expanded5=0.8798

Epoch 003 | train_loss=0.4896 | ce=0.4115 | ent=0.0000 | center=0.7814 | val_loss=0.1293 | val_acc=0.9778 | val_macro_f1=0.9779 | val_dqn_proxy_softmax3=0.9434 | val_dqn_proxy_expanded5=0.9485

Epoch 004 | train_loss=0.4658 | ce=0.3957 | ent=0.0000 | center=0.7007 | val_loss=0.1614 | val_acc=0.9741 | val_macro_f1=0.9741 | val_dqn_proxy_softmax3=0.8485 | val_dqn_proxy_expanded5=0.8552

Epoch 005 | train_loss=0.4394 | ce=0.3776 | ent=0.0000 | center=0.6172 | val_loss=0.2053 | val_acc=0.9444 | val_macro_f1=0.9441 | val_dqn_proxy_softmax3=0.9465 | val_dqn_proxy_expanded5=0.9112

Epoch 006 | train_loss=0.4270 | ce=0.3708 | ent=0.0000 | center=0.5617 | val_loss=0.1666 | val_acc=0.9444 | val_macro_f1=0.9441 | val_dqn_proxy_softmax3=0.8446 | val_dqn_proxy_expanded5=0.8295

Epoch 007 | train_loss=0.4190 | ce=0.3676 | ent=0.0000 | center=0.5141 | val_loss=0.0970 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9353 | val_dqn_proxy_expanded5=0.8871

Epoch 008 | train_loss=0.3969 | ce=0.3501 | ent=0.0000 | center=0.4685 | val_loss=0.0827 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9508 | val_dqn_proxy_expanded5=0.9262

Epoch 009 | train_loss=0.4044 | ce=0.3611 | ent=0.0000 | center=0.4333 | val_loss=0.0830 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.6578 | val_dqn_proxy_expanded5=0.7414

Epoch 010 | train_loss=0.3909 | ce=0.3506 | ent=0.0000 | center=0.4029 | val_loss=0.1197 | val_acc=0.9741 | val_macro_f1=0.9741 | val_dqn_proxy_softmax3=0.7257 | val_dqn_proxy_expanded5=0.7592

Epoch 011 | train_loss=0.3722 | ce=0.3356 | ent=0.0000 | center=0.3656 | val_loss=0.0929 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8645 | val_dqn_proxy_expanded5=0.8766

Epoch 012 | train_loss=0.3720 | ce=0.3375 | ent=0.0000 | center=0.3452 | val_loss=0.1164 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8504 | val_dqn_proxy_expanded5=0.8321

Epoch 013 | train_loss=0.3825 | ce=0.3496 | ent=0.0000 | center=0.3291 | val_loss=0.0947 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9558 | val_dqn_proxy_expanded5=0.9023

Epoch 014 | train_loss=0.3690 | ce=0.3387 | ent=0.0000 | center=0.3031 | val_loss=0.1087 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9604 | val_dqn_proxy_expanded5=0.9247

Epoch 015 | train_loss=0.3642 | ce=0.3357 | ent=0.0000 | center=0.2842 | val_loss=0.1138 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8675 | val_dqn_proxy_expanded5=0.8295

Epoch 016 | train_loss=0.3616 | ce=0.3347 | ent=0.0000 | center=0.2688 | val_loss=0.0812 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.8523 | val_dqn_proxy_expanded5=0.8159

Epoch 017 | train_loss=0.3563 | ce=0.3309 | ent=0.0000 | center=0.2541 | val_loss=0.1092 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8041 | val_dqn_proxy_expanded5=0.7893

Epoch 018 | train_loss=0.3630 | ce=0.3382 | ent=0.0000 | center=0.2481 | val_loss=0.1113 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8289 | val_dqn_proxy_expanded5=0.8270

Epoch 019 | train_loss=0.3560 | ce=0.3326 | ent=0.0000 | center=0.2339 | val_loss=0.0806 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9287 | val_dqn_proxy_expanded5=0.9006

Epoch 020 | train_loss=0.3456 | ce=0.3236 | ent=0.0000 | center=0.2204 | val_loss=0.0846 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9784 | val_dqn_proxy_expanded5=0.9439

Epoch 021 | train_loss=0.3744 | ce=0.3517 | ent=0.0000 | center=0.2261 | val_loss=0.1032 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.7343 | val_dqn_proxy_expanded5=0.7540

Epoch 022 | train_loss=0.3584 | ce=0.3372 | ent=0.0000 | center=0.2128 | val_loss=0.1483 | val_acc=0.9704 | val_macro_f1=0.9703 | val_dqn_proxy_softmax3=0.8123 | val_dqn_proxy_expanded5=0.8036

Epoch 023 | train_loss=0.3426 | ce=0.3234 | ent=0.0000 | center=0.1925 | val_loss=0.1394 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.8245 | val_dqn_proxy_expanded5=0.8173

Epoch 024 | train_loss=0.3597 | ce=0.3404 | ent=0.0000 | center=0.1925 | val_loss=0.0978 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.7747 | val_dqn_proxy_expanded5=0.7757

Epoch 025 | train_loss=0.3496 | ce=0.3315 | ent=0.0000 | center=0.1810 | val_loss=0.0987 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8323 | val_dqn_proxy_expanded5=0.8117

Epoch 026 | train_loss=0.3704 | ce=0.3525 | ent=0.0000 | center=0.1793 | val_loss=0.1400 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8769 | val_dqn_proxy_expanded5=0.8511

Epoch 027 | train_loss=0.3419 | ce=0.3253 | ent=0.0000 | center=0.1667 | val_loss=0.1001 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9640 | val_dqn_proxy_expanded5=0.9369

Epoch 028 | train_loss=0.3422 | ce=0.3264 | ent=0.0000 | center=0.1581 | val_loss=0.0870 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.7991 | val_dqn_proxy_expanded5=0.7919

Epoch 029 | train_loss=0.3475 | ce=0.3320 | ent=0.0000 | center=0.1549 | val_loss=0.1162 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8651 | val_dqn_proxy_expanded5=0.8418

Epoch 030 | train_loss=0.3356 | ce=0.3206 | ent=0.0000 | center=0.1503 | val_loss=0.0893 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.7248 | val_dqn_proxy_expanded5=0.7365

Epoch 031 | train_loss=0.3428 | ce=0.3286 | ent=0.0000 | center=0.1423 | val_loss=0.0851 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.7956 | val_dqn_proxy_expanded5=0.7860

Epoch 032 | train_loss=0.3353 | ce=0.3217 | ent=0.0000 | center=0.1360 | val_loss=0.1102 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.8524 | val_dqn_proxy_expanded5=0.8273

Epoch 033 | train_loss=0.3321 | ce=0.3190 | ent=0.0000 | center=0.1310 | val_loss=0.1075 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8604 | val_dqn_proxy_expanded5=0.8353

Epoch 034 | train_loss=0.3337 | ce=0.3209 | ent=0.0000 | center=0.1274 | val_loss=0.1049 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.7256 | val_dqn_proxy_expanded5=0.7690

Epoch 035 | train_loss=0.3321 | ce=0.3198 | ent=0.0000 | center=0.1229 | val_loss=0.0842 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9112 | val_dqn_proxy_expanded5=0.8841
Early stopping at epoch 35 (best epoch: 20)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
3,confman_baseline_knownonly_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-26_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
5,confman_baseline_openconf_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-30_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,confman_baseline_openconf_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-28_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,confman_baseline_knownonly_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-19_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,confman_baseline_knownonly_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-21_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,confman_baseline_knownonly_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-24_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"

================================================================================
Running experiment 7/32
{
  "run_name": "confman_baseline_openconf_unkPA4_c16384_seed0",
  "task": "pa",
  "split_mode": "open_pa",
  "unknown_pas": [
    "PA4"
  ],
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "lr": 0.0005,
  "weight_decay": 0.0,
  "lambda_center": 0.1,
  "label_smoothing": 0.1,
  "entropy_loss_weight": 0.0,
  "mlp_dropout": 0.3,
  "class_weight_mode": null,
  "grad_clip_norm": null,
  "scheduler_name": "cosine",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "epochs": 200,
  "early_stopping_patience": 15,
  "save_root": "results_pa_confmanifold_coarse"
}
================================================================================

Epoch 001 | train_loss=0.7337 | ce=0.6200 | ent=0.0000 | center=1.1371 | val_loss=0.3098 | val_acc=0.9000 | val_macro_f1=0.8994 | val_dqn_proxy_softmax3=0.7013 | val_dqn_proxy_expanded5=0.6694

Epoch 002 | train_loss=0.6090 | ce=0.5139 | ent=0.0000 | center=0.9505 | val_loss=0.3521 | val_acc=0.8963 | val_macro_f1=0.8951 | val_dqn_proxy_softmax3=0.7375 | val_dqn_proxy_expanded5=0.6725

Epoch 003 | train_loss=0.5021 | ce=0.4206 | ent=0.0000 | center=0.8152 | val_loss=0.1591 | val_acc=0.9741 | val_macro_f1=0.9742 | val_dqn_proxy_softmax3=0.8127 | val_dqn_proxy_expanded5=0.7327

Epoch 004 | train_loss=0.4539 | ce=0.3823 | ent=0.0000 | center=0.7157 | val_loss=0.1385 | val_acc=0.9630 | val_macro_f1=0.9629 | val_dqn_proxy_softmax3=0.8290 | val_dqn_proxy_expanded5=0.7462

Epoch 005 | train_loss=0.4429 | ce=0.3787 | ent=0.0000 | center=0.6426 | val_loss=0.0954 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.7780 | val_dqn_proxy_expanded5=0.7145

Epoch 006 | train_loss=0.4215 | ce=0.3632 | ent=0.0000 | center=0.5832 | val_loss=0.1337 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8752 | val_dqn_proxy_expanded5=0.7766

Epoch 007 | train_loss=0.4215 | ce=0.3669 | ent=0.0000 | center=0.5461 | val_loss=0.1297 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.7626 | val_dqn_proxy_expanded5=0.7129

Epoch 008 | train_loss=0.3951 | ce=0.3454 | ent=0.0000 | center=0.4974 | val_loss=0.1167 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9500 | val_dqn_proxy_expanded5=0.9112

Epoch 009 | train_loss=0.4023 | ce=0.3566 | ent=0.0000 | center=0.4566 | val_loss=0.1153 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.7696 | val_dqn_proxy_expanded5=0.7117

Epoch 010 | train_loss=0.3905 | ce=0.3477 | ent=0.0000 | center=0.4275 | val_loss=0.1275 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.7715 | val_dqn_proxy_expanded5=0.7124

Epoch 011 | train_loss=0.3801 | ce=0.3403 | ent=0.0000 | center=0.3981 | val_loss=0.1317 | val_acc=0.9704 | val_macro_f1=0.9703 | val_dqn_proxy_softmax3=0.8079 | val_dqn_proxy_expanded5=0.7498

Epoch 012 | train_loss=0.3939 | ce=0.3558 | ent=0.0000 | center=0.3805 | val_loss=0.0945 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9667 | val_dqn_proxy_expanded5=0.9036

Epoch 013 | train_loss=0.3740 | ce=0.3388 | ent=0.0000 | center=0.3512 | val_loss=0.1085 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7820 | val_dqn_proxy_expanded5=0.7207

Epoch 014 | train_loss=0.3692 | ce=0.3364 | ent=0.0000 | center=0.3281 | val_loss=0.1035 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9530 | val_dqn_proxy_expanded5=0.9103

Epoch 015 | train_loss=0.3729 | ce=0.3417 | ent=0.0000 | center=0.3114 | val_loss=0.1743 | val_acc=0.9704 | val_macro_f1=0.9703 | val_dqn_proxy_softmax3=0.7420 | val_dqn_proxy_expanded5=0.7108

Epoch 016 | train_loss=0.3669 | ce=0.3371 | ent=0.0000 | center=0.2978 | val_loss=0.1291 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7705 | val_dqn_proxy_expanded5=0.7345

Epoch 017 | train_loss=0.3641 | ce=0.3364 | ent=0.0000 | center=0.2780 | val_loss=0.1420 | val_acc=0.9630 | val_macro_f1=0.9629 | val_dqn_proxy_softmax3=0.7266 | val_dqn_proxy_expanded5=0.7191

Epoch 018 | train_loss=0.3558 | ce=0.3299 | ent=0.0000 | center=0.2593 | val_loss=0.1055 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.7348 | val_dqn_proxy_expanded5=0.7319

Epoch 019 | train_loss=0.3470 | ce=0.3225 | ent=0.0000 | center=0.2452 | val_loss=0.1047 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.8219 | val_dqn_proxy_expanded5=0.7636

Epoch 020 | train_loss=0.3522 | ce=0.3288 | ent=0.0000 | center=0.2334 | val_loss=0.1076 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.8734 | val_dqn_proxy_expanded5=0.8093

Epoch 021 | train_loss=0.3405 | ce=0.3184 | ent=0.0000 | center=0.2210 | val_loss=0.0947 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7748 | val_dqn_proxy_expanded5=0.7419

Epoch 022 | train_loss=0.3440 | ce=0.3230 | ent=0.0000 | center=0.2099 | val_loss=0.0830 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9440 | val_dqn_proxy_expanded5=0.8664

Epoch 023 | train_loss=0.3367 | ce=0.3167 | ent=0.0000 | center=0.1999 | val_loss=0.0957 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.7743 | val_dqn_proxy_expanded5=0.7429

Epoch 024 | train_loss=0.3347 | ce=0.3157 | ent=0.0000 | center=0.1910 | val_loss=0.0752 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.7755 | val_dqn_proxy_expanded5=0.7362

Epoch 025 | train_loss=0.3314 | ce=0.3135 | ent=0.0000 | center=0.1788 | val_loss=0.1372 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.7741 | val_dqn_proxy_expanded5=0.7271

Epoch 026 | train_loss=0.3515 | ce=0.3340 | ent=0.0000 | center=0.1748 | val_loss=0.1769 | val_acc=0.9630 | val_macro_f1=0.9628 | val_dqn_proxy_softmax3=0.9073 | val_dqn_proxy_expanded5=0.8775

Epoch 027 | train_loss=0.3363 | ce=0.3192 | ent=0.0000 | center=0.1709 | val_loss=0.1044 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7640 | val_dqn_proxy_expanded5=0.7241
Early stopping at epoch 27 (best epoch: 12)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
3,confman_baseline_knownonly_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-26_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
5,confman_baseline_openconf_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-30_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,confman_baseline_openconf_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-28_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,confman_baseline_openconf_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-33_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,confman_baseline_knownonly_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-19_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,confman_baseline_knownonly_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-21_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,confman_baseline_knownonly_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-24_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"

================================================================================
Running experiment 8/32
{
  "run_name": "confman_baseline_openconf_unkPA8_c16384_seed0",
  "task": "pa",
  "split_mode": "open_pa",
  "unknown_pas": [
    "PA8"
  ],
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "lr": 0.0005,
  "weight_decay": 0.0,
  "lambda_center": 0.1,
  "label_smoothing": 0.1,
  "entropy_loss_weight": 0.0,
  "mlp_dropout": 0.3,
  "class_weight_mode": null,
  "grad_clip_norm": null,
  "scheduler_name": "cosine",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "epochs": 200,
  "early_stopping_patience": 15,
  "save_root": "results_pa_confmanifold_coarse"
}
================================================================================

Epoch 001 | train_loss=0.6140 | ce=0.4983 | ent=0.0000 | center=1.1566 | val_loss=0.1735 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9323 | val_dqn_proxy_expanded5=0.9321

Epoch 002 | train_loss=0.4286 | ce=0.3411 | ent=0.0000 | center=0.8745 | val_loss=0.1166 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8593 | val_dqn_proxy_expanded5=0.8285

Epoch 003 | train_loss=0.4147 | ce=0.3404 | ent=0.0000 | center=0.7426 | val_loss=0.1289 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9086 | val_dqn_proxy_expanded5=0.8636

Epoch 004 | train_loss=0.4063 | ce=0.3404 | ent=0.0000 | center=0.6589 | val_loss=0.1060 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9566 | val_dqn_proxy_expanded5=0.9187

Epoch 005 | train_loss=0.3886 | ce=0.3301 | ent=0.0000 | center=0.5855 | val_loss=0.1050 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9108 | val_dqn_proxy_expanded5=0.8611

Epoch 006 | train_loss=0.3761 | ce=0.3235 | ent=0.0000 | center=0.5265 | val_loss=0.1253 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9037 | val_dqn_proxy_expanded5=0.8633

Epoch 007 | train_loss=0.3755 | ce=0.3260 | ent=0.0000 | center=0.4951 | val_loss=0.1170 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9714 | val_dqn_proxy_expanded5=0.9335

Epoch 008 | train_loss=0.3574 | ce=0.3128 | ent=0.0000 | center=0.4455 | val_loss=0.0904 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8735 | val_dqn_proxy_expanded5=0.8415

Epoch 009 | train_loss=0.3533 | ce=0.3129 | ent=0.0000 | center=0.4044 | val_loss=0.0882 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9267 | val_dqn_proxy_expanded5=0.8650

Epoch 010 | train_loss=0.3456 | ce=0.3088 | ent=0.0000 | center=0.3672 | val_loss=0.1050 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9302 | val_dqn_proxy_expanded5=0.8686

Epoch 011 | train_loss=0.3390 | ce=0.3060 | ent=0.0000 | center=0.3307 | val_loss=0.1103 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9570 | val_dqn_proxy_expanded5=0.9037

Epoch 012 | train_loss=0.3388 | ce=0.3075 | ent=0.0000 | center=0.3132 | val_loss=0.0874 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9001 | val_dqn_proxy_expanded5=0.8548

Epoch 013 | train_loss=0.3399 | ce=0.3100 | ent=0.0000 | center=0.2993 | val_loss=0.0902 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9403 | val_dqn_proxy_expanded5=0.8916

Epoch 014 | train_loss=0.3357 | ce=0.3076 | ent=0.0000 | center=0.2807 | val_loss=0.0888 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8193 | val_dqn_proxy_expanded5=0.8020

Epoch 015 | train_loss=0.3332 | ce=0.3074 | ent=0.0000 | center=0.2582 | val_loss=0.1047 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8714 | val_dqn_proxy_expanded5=0.8304

Epoch 016 | train_loss=0.3311 | ce=0.3064 | ent=0.0000 | center=0.2474 | val_loss=0.0930 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9690 | val_dqn_proxy_expanded5=0.8992

Epoch 017 | train_loss=0.3311 | ce=0.3079 | ent=0.0000 | center=0.2318 | val_loss=0.0923 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9406 | val_dqn_proxy_expanded5=0.8698

Epoch 018 | train_loss=0.3280 | ce=0.3060 | ent=0.0000 | center=0.2197 | val_loss=0.1080 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7783 | val_dqn_proxy_expanded5=0.7700

Epoch 019 | train_loss=0.3264 | ce=0.3054 | ent=0.0000 | center=0.2097 | val_loss=0.0859 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8589 | val_dqn_proxy_expanded5=0.8195

Epoch 020 | train_loss=0.3253 | ce=0.3052 | ent=0.0000 | center=0.2015 | val_loss=0.0944 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9597 | val_dqn_proxy_expanded5=0.8887

Epoch 021 | train_loss=0.3225 | ce=0.3040 | ent=0.0000 | center=0.1857 | val_loss=0.0884 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8142 | val_dqn_proxy_expanded5=0.7918

Epoch 022 | train_loss=0.3231 | ce=0.3047 | ent=0.0000 | center=0.1836 | val_loss=0.0905 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8623 | val_dqn_proxy_expanded5=0.8254
Early stopping at epoch 22 (best epoch: 7)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
3,confman_baseline_knownonly_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-26_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
5,confman_baseline_openconf_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-30_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,confman_baseline_openconf_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-28_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,confman_baseline_openconf_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-35_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,confman_baseline_openconf_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-33_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,confman_baseline_knownonly_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-19_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,confman_baseline_knownonly_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-21_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,confman_baseline_knownonly_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-24_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"

================================================================================
Running experiment 9/32
{
  "run_name": "confman_paperish_mild_unkPA2_c16384_seed0",
  "task": "pa",
  "split_mode": "open_pa",
  "unknown_pas": [
    "PA2"
  ],
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "lr": 0.0001,
  "weight_decay": 0.0001,
  "lambda_center": 0.1,
  "label_smoothing": 0.0,
  "entropy_loss_weight": 0.02,
  "mlp_dropout": 0.5,
  "class_weight_mode": null,
  "grad_clip_norm": 1.0,
  "scheduler_name": "plateau",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "epochs": 200,
  "early_stopping_patience": 15,
  "save_root": "results_pa_confmanifold_coarse"
}
================================================================================

Epoch 001 | train_loss=0.9557 | ce=0.8332 | ent=0.9875 | center=1.0269 | val_loss=0.3536 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7163 | val_dqn_proxy_expanded5=0.7313

Epoch 002 | train_loss=0.4028 | ce=0.2492 | ent=0.3943 | center=1.4567 | val_loss=0.1585 | val_acc=0.9630 | val_macro_f1=0.9632 | val_dqn_proxy_softmax3=0.8730 | val_dqn_proxy_expanded5=0.8693

Epoch 003 | train_loss=0.2983 | ce=0.1546 | ent=0.2392 | center=1.3896 | val_loss=0.1179 | val_acc=0.9741 | val_macro_f1=0.9742 | val_dqn_proxy_softmax3=0.7266 | val_dqn_proxy_expanded5=0.7567

Epoch 004 | train_loss=0.2646 | ce=0.1303 | ent=0.1941 | center=1.3046 | val_loss=0.0984 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6544 | val_dqn_proxy_expanded5=0.7517

Epoch 005 | train_loss=0.2535 | ce=0.1272 | ent=0.1757 | center=1.2283 | val_loss=0.0913 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6353 | val_dqn_proxy_expanded5=0.7240

Epoch 006 | train_loss=0.2418 | ce=0.1218 | ent=0.1612 | center=1.1673 | val_loss=0.0849 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.5754 | val_dqn_proxy_expanded5=0.7000

Epoch 007 | train_loss=0.2236 | ce=0.1074 | ent=0.1490 | center=1.1325 | val_loss=0.0766 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6471 | val_dqn_proxy_expanded5=0.7414

Epoch 008 | train_loss=0.2156 | ce=0.1064 | ent=0.1393 | center=1.0644 | val_loss=0.0773 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6420 | val_dqn_proxy_expanded5=0.7387

Epoch 009 | train_loss=0.2059 | ce=0.0979 | ent=0.1275 | center=1.0551 | val_loss=0.0781 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.5834 | val_dqn_proxy_expanded5=0.6912

Epoch 010 | train_loss=0.1890 | ce=0.0873 | ent=0.1294 | center=0.9906 | val_loss=0.0765 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6131 | val_dqn_proxy_expanded5=0.6952

Epoch 011 | train_loss=0.1838 | ce=0.0838 | ent=0.1133 | center=0.9774 | val_loss=0.0686 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8763 | val_dqn_proxy_expanded5=0.8834

Epoch 012 | train_loss=0.1763 | ce=0.0793 | ent=0.0956 | center=0.9508 | val_loss=0.0694 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.5823 | val_dqn_proxy_expanded5=0.6832

Epoch 013 | train_loss=0.1668 | ce=0.0731 | ent=0.0957 | center=0.9182 | val_loss=0.0675 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7270 | val_dqn_proxy_expanded5=0.7206

Epoch 014 | train_loss=0.1593 | ce=0.0679 | ent=0.0991 | center=0.8938 | val_loss=0.0632 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7320 | val_dqn_proxy_expanded5=0.7295

Epoch 015 | train_loss=0.1486 | ce=0.0605 | ent=0.0905 | center=0.8636 | val_loss=0.0493 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.5382 | val_dqn_proxy_expanded5=0.6806

Epoch 016 | train_loss=0.1497 | ce=0.0637 | ent=0.0837 | center=0.8426 | val_loss=0.0407 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6296 | val_dqn_proxy_expanded5=0.7171

Epoch 017 | train_loss=0.1332 | ce=0.0484 | ent=0.0882 | center=0.8300 | val_loss=0.0494 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7279 | val_dqn_proxy_expanded5=0.7181

Epoch 018 | train_loss=0.1271 | ce=0.0443 | ent=0.0772 | center=0.8127 | val_loss=0.0407 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6215 | val_dqn_proxy_expanded5=0.7087

Epoch 019 | train_loss=0.1195 | ce=0.0394 | ent=0.0657 | center=0.7883 | val_loss=0.0408 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6280 | val_dqn_proxy_expanded5=0.7100

Epoch 020 | train_loss=0.1134 | ce=0.0360 | ent=0.0665 | center=0.7609 | val_loss=0.0361 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.5709 | val_dqn_proxy_expanded5=0.6942

Epoch 021 | train_loss=0.1143 | ce=0.0385 | ent=0.0599 | center=0.7457 | val_loss=0.0412 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6635 | val_dqn_proxy_expanded5=0.7100

Epoch 022 | train_loss=0.1087 | ce=0.0360 | ent=0.0558 | center=0.7165 | val_loss=0.0413 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6631 | val_dqn_proxy_expanded5=0.6996

Epoch 023 | train_loss=0.1105 | ce=0.0392 | ent=0.0579 | center=0.7024 | val_loss=0.0383 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7363 | val_dqn_proxy_expanded5=0.7295

Epoch 024 | train_loss=0.1013 | ce=0.0329 | ent=0.0481 | center=0.6746 | val_loss=0.0425 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6675 | val_dqn_proxy_expanded5=0.7182

Epoch 025 | train_loss=0.1015 | ce=0.0350 | ent=0.0548 | center=0.6544 | val_loss=0.0436 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6781 | val_dqn_proxy_expanded5=0.7084

Epoch 026 | train_loss=0.0967 | ce=0.0311 | ent=0.0445 | center=0.6477 | val_loss=0.0434 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6886 | val_dqn_proxy_expanded5=0.7187
Early stopping at epoch 26 (best epoch: 11)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
3,confman_baseline_knownonly_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-26_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
5,confman_baseline_openconf_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-30_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,confman_baseline_openconf_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-28_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,confman_baseline_openconf_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-35_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
8,confman_paperish_mild_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-37_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,confman_baseline_openconf_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-33_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,confman_baseline_knownonly_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-19_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,confman_baseline_knownonly_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-21_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,confman_baseline_knownonly_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-24_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"

================================================================================
Running experiment 10/32
{
  "run_name": "confman_paperish_mild_unkPA3_c16384_seed0",
  "task": "pa",
  "split_mode": "open_pa",
  "unknown_pas": [
    "PA3"
  ],
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "lr": 0.0001,
  "weight_decay": 0.0001,
  "lambda_center": 0.1,
  "label_smoothing": 0.0,
  "entropy_loss_weight": 0.02,
  "mlp_dropout": 0.5,
  "class_weight_mode": null,
  "grad_clip_norm": 1.0,
  "scheduler_name": "plateau",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "epochs": 200,
  "early_stopping_patience": 15,
  "save_root": "results_pa_confmanifold_coarse"
}
================================================================================

Epoch 001 | train_loss=1.0288 | ce=0.9018 | ent=1.0223 | center=1.0661 | val_loss=0.4788 | val_acc=0.9407 | val_macro_f1=0.9402 | val_dqn_proxy_softmax3=0.6939 | val_dqn_proxy_expanded5=0.7178

Epoch 002 | train_loss=0.5034 | ce=0.3482 | ent=0.5290 | center=1.4464 | val_loss=0.1479 | val_acc=0.9630 | val_macro_f1=0.9630 | val_dqn_proxy_softmax3=0.8269 | val_dqn_proxy_expanded5=0.7988

Epoch 003 | train_loss=0.3935 | ce=0.2372 | ent=0.3328 | center=1.4962 | val_loss=0.1176 | val_acc=0.9704 | val_macro_f1=0.9705 | val_dqn_proxy_softmax3=0.9008 | val_dqn_proxy_expanded5=0.8553

Epoch 004 | train_loss=0.3307 | ce=0.1867 | ent=0.2761 | center=1.3851 | val_loss=0.1072 | val_acc=0.9704 | val_macro_f1=0.9706 | val_dqn_proxy_softmax3=0.9231 | val_dqn_proxy_expanded5=0.8597

Epoch 005 | train_loss=0.3076 | ce=0.1707 | ent=0.2357 | center=1.3223 | val_loss=0.1308 | val_acc=0.9444 | val_macro_f1=0.9447 | val_dqn_proxy_softmax3=0.9152 | val_dqn_proxy_expanded5=0.8622

Epoch 006 | train_loss=0.2904 | ce=0.1619 | ent=0.2218 | center=1.2406 | val_loss=0.0969 | val_acc=0.9593 | val_macro_f1=0.9595 | val_dqn_proxy_softmax3=0.8890 | val_dqn_proxy_expanded5=0.8745

Epoch 007 | train_loss=0.2668 | ce=0.1434 | ent=0.1962 | center=1.1950 | val_loss=0.1324 | val_acc=0.9370 | val_macro_f1=0.9372 | val_dqn_proxy_softmax3=0.9449 | val_dqn_proxy_expanded5=0.8882

Epoch 008 | train_loss=0.2517 | ce=0.1313 | ent=0.1919 | center=1.1649 | val_loss=0.0752 | val_acc=0.9741 | val_macro_f1=0.9742 | val_dqn_proxy_softmax3=0.9133 | val_dqn_proxy_expanded5=0.8918

Epoch 009 | train_loss=0.2681 | ce=0.1524 | ent=0.1764 | center=1.1215 | val_loss=0.0801 | val_acc=0.9667 | val_macro_f1=0.9667 | val_dqn_proxy_softmax3=0.9608 | val_dqn_proxy_expanded5=0.9392

Epoch 010 | train_loss=0.2183 | ce=0.1059 | ent=0.1558 | center=1.0933 | val_loss=0.1911 | val_acc=0.9185 | val_macro_f1=0.9183 | val_dqn_proxy_softmax3=0.9003 | val_dqn_proxy_expanded5=0.8647

Epoch 011 | train_loss=0.2371 | ce=0.1287 | ent=0.1537 | center=1.0525 | val_loss=0.1144 | val_acc=0.9481 | val_macro_f1=0.9484 | val_dqn_proxy_softmax3=0.9716 | val_dqn_proxy_expanded5=0.9509

Epoch 012 | train_loss=0.2112 | ce=0.1065 | ent=0.1410 | center=1.0196 | val_loss=0.0531 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.9595 | val_dqn_proxy_expanded5=0.9423

Epoch 013 | train_loss=0.2096 | ce=0.1078 | ent=0.1348 | center=0.9915 | val_loss=0.0487 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9658 | val_dqn_proxy_expanded5=0.9175

Epoch 014 | train_loss=0.1979 | ce=0.0985 | ent=0.1259 | center=0.9683 | val_loss=0.0523 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9398 | val_dqn_proxy_expanded5=0.8965

Epoch 015 | train_loss=0.1763 | ce=0.0814 | ent=0.1233 | center=0.9238 | val_loss=0.0435 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9601 | val_dqn_proxy_expanded5=0.9207

Epoch 016 | train_loss=0.1657 | ce=0.0709 | ent=0.1070 | center=0.9269 | val_loss=0.0685 | val_acc=0.9741 | val_macro_f1=0.9740 | val_dqn_proxy_softmax3=0.9752 | val_dqn_proxy_expanded5=0.9293

Epoch 017 | train_loss=0.1850 | ce=0.0932 | ent=0.1083 | center=0.8960 | val_loss=0.0751 | val_acc=0.9704 | val_macro_f1=0.9703 | val_dqn_proxy_softmax3=0.9732 | val_dqn_proxy_expanded5=0.9385

Epoch 018 | train_loss=0.1604 | ce=0.0703 | ent=0.1099 | center=0.8795 | val_loss=0.0436 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9212 | val_dqn_proxy_expanded5=0.9004

Epoch 019 | train_loss=0.1428 | ce=0.0544 | ent=0.0960 | center=0.8639 | val_loss=0.0499 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.9635 | val_dqn_proxy_expanded5=0.9191

Epoch 020 | train_loss=0.1500 | ce=0.0657 | ent=0.0927 | center=0.8237 | val_loss=0.0448 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.9651 | val_dqn_proxy_expanded5=0.9543

Epoch 021 | train_loss=0.1466 | ce=0.0642 | ent=0.0917 | center=0.8051 | val_loss=0.0371 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9281 | val_dqn_proxy_expanded5=0.9035

Epoch 022 | train_loss=0.1406 | ce=0.0602 | ent=0.0892 | center=0.7865 | val_loss=0.0231 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8891 | val_dqn_proxy_expanded5=0.8556

Epoch 023 | train_loss=0.1292 | ce=0.0500 | ent=0.0774 | center=0.7767 | val_loss=0.0163 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9488 | val_dqn_proxy_expanded5=0.9001

Epoch 024 | train_loss=0.1364 | ce=0.0599 | ent=0.0788 | center=0.7497 | val_loss=0.0499 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9759 | val_dqn_proxy_expanded5=0.9458

Epoch 025 | train_loss=0.1291 | ce=0.0547 | ent=0.0773 | center=0.7289 | val_loss=0.0347 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9667 | val_dqn_proxy_expanded5=0.9373

Epoch 026 | train_loss=0.1328 | ce=0.0601 | ent=0.0700 | center=0.7131 | val_loss=0.0520 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.9808 | val_dqn_proxy_expanded5=0.9587

Epoch 027 | train_loss=0.1144 | ce=0.0440 | ent=0.0758 | center=0.6888 | val_loss=0.0524 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9803 | val_dqn_proxy_expanded5=0.9391

Epoch 028 | train_loss=0.1159 | ce=0.0461 | ent=0.0687 | center=0.6848 | val_loss=0.0290 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9562 | val_dqn_proxy_expanded5=0.9005

Epoch 029 | train_loss=0.1136 | ce=0.0457 | ent=0.0680 | center=0.6660 | val_loss=0.0157 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9752 | val_dqn_proxy_expanded5=0.9322

Epoch 030 | train_loss=0.1098 | ce=0.0440 | ent=0.0558 | center=0.6464 | val_loss=0.0248 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9472 | val_dqn_proxy_expanded5=0.8950

Epoch 031 | train_loss=0.1147 | ce=0.0506 | ent=0.0632 | center=0.6289 | val_loss=0.0380 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9728 | val_dqn_proxy_expanded5=0.9342

Epoch 032 | train_loss=0.1126 | ce=0.0503 | ent=0.0558 | center=0.6116 | val_loss=0.0494 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9385 | val_dqn_proxy_expanded5=0.8970

Epoch 033 | train_loss=0.1098 | ce=0.0487 | ent=0.0657 | center=0.5978 | val_loss=0.0287 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9235 | val_dqn_proxy_expanded5=0.8775

Epoch 034 | train_loss=0.1041 | ce=0.0436 | ent=0.0501 | center=0.5952 | val_loss=0.0177 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9635 | val_dqn_proxy_expanded5=0.9182

Epoch 035 | train_loss=0.0979 | ce=0.0393 | ent=0.0501 | center=0.5764 | val_loss=0.0126 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9656 | val_dqn_proxy_expanded5=0.9257

Epoch 036 | train_loss=0.0916 | ce=0.0344 | ent=0.0473 | center=0.5632 | val_loss=0.0306 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9754 | val_dqn_proxy_expanded5=0.9618

Epoch 037 | train_loss=0.0864 | ce=0.0293 | ent=0.0452 | center=0.5620 | val_loss=0.0490 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9422 | val_dqn_proxy_expanded5=0.8905

Epoch 038 | train_loss=0.0970 | ce=0.0425 | ent=0.0444 | center=0.5366 | val_loss=0.0119 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9642 | val_dqn_proxy_expanded5=0.9189

Epoch 039 | train_loss=0.0801 | ce=0.0266 | ent=0.0402 | center=0.5268 | val_loss=0.0307 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9583 | val_dqn_proxy_expanded5=0.9096

Epoch 040 | train_loss=0.0780 | ce=0.0262 | ent=0.0410 | center=0.5102 | val_loss=0.0267 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9776 | val_dqn_proxy_expanded5=0.9329

Epoch 041 | train_loss=0.0886 | ce=0.0377 | ent=0.0404 | center=0.5008 | val_loss=0.0077 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9559 | val_dqn_proxy_expanded5=0.9022
Early stopping at epoch 41 (best epoch: 26)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
3,confman_baseline_knownonly_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-26_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,confman_paperish_mild_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-39_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
5,confman_baseline_openconf_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-30_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,confman_baseline_openconf_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-28_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,confman_baseline_openconf_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-35_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
8,confman_paperish_mild_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-37_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,confman_baseline_openconf_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-33_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,confman_baseline_knownonly_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-19_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,confman_baseline_knownonly_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-21_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,confman_baseline_knownonly_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-24_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"

================================================================================
Running experiment 11/32
{
  "run_name": "confman_paperish_mild_unkPA4_c16384_seed0",
  "task": "pa",
  "split_mode": "open_pa",
  "unknown_pas": [
    "PA4"
  ],
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "lr": 0.0001,
  "weight_decay": 0.0001,
  "lambda_center": 0.1,
  "label_smoothing": 0.0,
  "entropy_loss_weight": 0.02,
  "mlp_dropout": 0.5,
  "class_weight_mode": null,
  "grad_clip_norm": 1.0,
  "scheduler_name": "plateau",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "epochs": 200,
  "early_stopping_patience": 15,
  "save_root": "results_pa_confmanifold_coarse"
}
================================================================================

Epoch 001 | train_loss=0.9562 | ce=0.8266 | ent=0.9752 | center=1.1009 | val_loss=0.3976 | val_acc=0.8704 | val_macro_f1=0.8635 | val_dqn_proxy_softmax3=0.7043 | val_dqn_proxy_expanded5=0.7022

Epoch 002 | train_loss=0.5376 | ce=0.3627 | ent=0.5166 | center=1.6454 | val_loss=0.2740 | val_acc=0.9000 | val_macro_f1=0.8997 | val_dqn_proxy_softmax3=0.7096 | val_dqn_proxy_expanded5=0.7231

Epoch 003 | train_loss=0.4280 | ce=0.2613 | ent=0.3703 | center=1.5928 | val_loss=0.1876 | val_acc=0.9519 | val_macro_f1=0.9521 | val_dqn_proxy_softmax3=0.7406 | val_dqn_proxy_expanded5=0.7718

Epoch 004 | train_loss=0.3553 | ce=0.2041 | ent=0.2946 | center=1.4535 | val_loss=0.1675 | val_acc=0.9519 | val_macro_f1=0.9518 | val_dqn_proxy_softmax3=0.7495 | val_dqn_proxy_expanded5=0.7735

Epoch 005 | train_loss=0.3170 | ce=0.1765 | ent=0.2513 | center=1.3544 | val_loss=0.1451 | val_acc=0.9519 | val_macro_f1=0.9517 | val_dqn_proxy_softmax3=0.7480 | val_dqn_proxy_expanded5=0.7582

Epoch 006 | train_loss=0.3218 | ce=0.1909 | ent=0.2336 | center=1.2619 | val_loss=0.1496 | val_acc=0.9519 | val_macro_f1=0.9521 | val_dqn_proxy_softmax3=0.7244 | val_dqn_proxy_expanded5=0.7063

Epoch 007 | train_loss=0.2856 | ce=0.1580 | ent=0.1980 | center=1.2357 | val_loss=0.1226 | val_acc=0.9667 | val_macro_f1=0.9666 | val_dqn_proxy_softmax3=0.7624 | val_dqn_proxy_expanded5=0.7353

Epoch 008 | train_loss=0.2716 | ce=0.1506 | ent=0.1892 | center=1.1730 | val_loss=0.1283 | val_acc=0.9667 | val_macro_f1=0.9668 | val_dqn_proxy_softmax3=0.7507 | val_dqn_proxy_expanded5=0.7239

Epoch 009 | train_loss=0.2618 | ce=0.1451 | ent=0.1690 | center=1.1337 | val_loss=0.1287 | val_acc=0.9667 | val_macro_f1=0.9666 | val_dqn_proxy_softmax3=0.7553 | val_dqn_proxy_expanded5=0.7306

Epoch 010 | train_loss=0.2239 | ce=0.1094 | ent=0.1518 | center=1.1153 | val_loss=0.0954 | val_acc=0.9778 | val_macro_f1=0.9779 | val_dqn_proxy_softmax3=0.7323 | val_dqn_proxy_expanded5=0.7195

Epoch 011 | train_loss=0.2200 | ce=0.1088 | ent=0.1498 | center=1.0818 | val_loss=0.1007 | val_acc=0.9778 | val_macro_f1=0.9779 | val_dqn_proxy_softmax3=0.7492 | val_dqn_proxy_expanded5=0.7255

Epoch 012 | train_loss=0.2160 | ce=0.1095 | ent=0.1374 | center=1.0378 | val_loss=0.1002 | val_acc=0.9741 | val_macro_f1=0.9743 | val_dqn_proxy_softmax3=0.7450 | val_dqn_proxy_expanded5=0.7261

Epoch 013 | train_loss=0.2010 | ce=0.0988 | ent=0.1378 | center=0.9946 | val_loss=0.1263 | val_acc=0.9556 | val_macro_f1=0.9555 | val_dqn_proxy_softmax3=0.8514 | val_dqn_proxy_expanded5=0.7900

Epoch 014 | train_loss=0.1793 | ce=0.0781 | ent=0.1144 | center=0.9895 | val_loss=0.0699 | val_acc=0.9815 | val_macro_f1=0.9816 | val_dqn_proxy_softmax3=0.8732 | val_dqn_proxy_expanded5=0.8112

Epoch 015 | train_loss=0.1738 | ce=0.0765 | ent=0.1117 | center=0.9502 | val_loss=0.0840 | val_acc=0.9630 | val_macro_f1=0.9629 | val_dqn_proxy_softmax3=0.9100 | val_dqn_proxy_expanded5=0.8509

Epoch 016 | train_loss=0.1644 | ce=0.0688 | ent=0.1083 | center=0.9353 | val_loss=0.1016 | val_acc=0.9593 | val_macro_f1=0.9592 | val_dqn_proxy_softmax3=0.9211 | val_dqn_proxy_expanded5=0.8562

Epoch 017 | train_loss=0.1549 | ce=0.0618 | ent=0.0977 | center=0.9120 | val_loss=0.0547 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.9271 | val_dqn_proxy_expanded5=0.8641

Epoch 018 | train_loss=0.1565 | ce=0.0668 | ent=0.0949 | center=0.8778 | val_loss=0.0287 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9359 | val_dqn_proxy_expanded5=0.8795

Epoch 019 | train_loss=0.1639 | ce=0.0766 | ent=0.0999 | center=0.8537 | val_loss=0.0521 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.9300 | val_dqn_proxy_expanded5=0.8791

Epoch 020 | train_loss=0.1378 | ce=0.0526 | ent=0.0900 | center=0.8344 | val_loss=0.0330 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9336 | val_dqn_proxy_expanded5=0.8706

Epoch 021 | train_loss=0.1474 | ce=0.0644 | ent=0.0842 | center=0.8129 | val_loss=0.0268 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9557 | val_dqn_proxy_expanded5=0.8788

Epoch 022 | train_loss=0.1301 | ce=0.0493 | ent=0.0813 | center=0.7916 | val_loss=0.0142 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.8967 | val_dqn_proxy_expanded5=0.8325

Epoch 023 | train_loss=0.1205 | ce=0.0418 | ent=0.0772 | center=0.7722 | val_loss=0.0158 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.8463 | val_dqn_proxy_expanded5=0.8017

Epoch 024 | train_loss=0.1299 | ce=0.0531 | ent=0.0683 | center=0.7541 | val_loss=0.0293 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.8358 | val_dqn_proxy_expanded5=0.7850

Epoch 025 | train_loss=0.1209 | ce=0.0465 | ent=0.0702 | center=0.7293 | val_loss=0.0350 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.7168 | val_dqn_proxy_expanded5=0.7110

Epoch 026 | train_loss=0.1335 | ce=0.0606 | ent=0.0683 | center=0.7155 | val_loss=0.0212 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9097 | val_dqn_proxy_expanded5=0.8415

Epoch 027 | train_loss=0.1377 | ce=0.0664 | ent=0.0691 | center=0.6998 | val_loss=0.0103 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.7613 | val_dqn_proxy_expanded5=0.7414

Epoch 028 | train_loss=0.1164 | ce=0.0466 | ent=0.0646 | center=0.6844 | val_loss=0.0288 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7282 | val_dqn_proxy_expanded5=0.7101

Epoch 029 | train_loss=0.1046 | ce=0.0367 | ent=0.0578 | center=0.6675 | val_loss=0.0118 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.6833 | val_dqn_proxy_expanded5=0.7068

Epoch 030 | train_loss=0.1078 | ce=0.0413 | ent=0.0585 | center=0.6527 | val_loss=0.0576 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.6380 | val_dqn_proxy_expanded5=0.6702

Epoch 031 | train_loss=0.1154 | ce=0.0499 | ent=0.0604 | center=0.6429 | val_loss=0.0097 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.7626 | val_dqn_proxy_expanded5=0.7385

Epoch 032 | train_loss=0.0984 | ce=0.0352 | ent=0.0530 | center=0.6209 | val_loss=0.0080 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.8042 | val_dqn_proxy_expanded5=0.7623

Epoch 033 | train_loss=0.0875 | ce=0.0252 | ent=0.0541 | center=0.6131 | val_loss=0.0069 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.8502 | val_dqn_proxy_expanded5=0.7962

Epoch 034 | train_loss=0.0990 | ce=0.0382 | ent=0.0501 | center=0.5984 | val_loss=0.0137 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7631 | val_dqn_proxy_expanded5=0.7327

Epoch 035 | train_loss=0.1012 | ce=0.0420 | ent=0.0485 | center=0.5824 | val_loss=0.0065 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.8067 | val_dqn_proxy_expanded5=0.7522

Epoch 036 | train_loss=0.0999 | ce=0.0419 | ent=0.0507 | center=0.5707 | val_loss=0.0306 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.7683 | val_dqn_proxy_expanded5=0.7383
Early stopping at epoch 36 (best epoch: 21)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
3,confman_baseline_knownonly_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-26_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,confman_paperish_mild_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-39_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
5,confman_baseline_openconf_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-30_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,confman_baseline_openconf_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-28_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,confman_baseline_openconf_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-35_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
8,confman_paperish_mild_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-37_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,confman_baseline_openconf_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-33_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
10,confman_paperish_mild_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-43_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,confman_baseline_knownonly_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-19_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,confman_baseline_knownonly_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-21_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,confman_baseline_knownonly_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-24_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"

================================================================================
Running experiment 12/32
{
  "run_name": "confman_paperish_mild_unkPA8_c16384_seed0",
  "task": "pa",
  "split_mode": "open_pa",
  "unknown_pas": [
    "PA8"
  ],
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "lr": 0.0001,
  "weight_decay": 0.0001,
  "lambda_center": 0.1,
  "label_smoothing": 0.0,
  "entropy_loss_weight": 0.02,
  "mlp_dropout": 0.5,
  "class_weight_mode": null,
  "grad_clip_norm": 1.0,
  "scheduler_name": "plateau",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "epochs": 200,
  "early_stopping_patience": 15,
  "save_root": "results_pa_confmanifold_coarse"
}
================================================================================

Epoch 001 | train_loss=0.8929 | ce=0.7545 | ent=0.9315 | center=1.1983 | val_loss=0.2436 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.7466 | val_dqn_proxy_expanded5=0.7603

Epoch 002 | train_loss=0.3341 | ce=0.1649 | ent=0.3134 | center=1.6294 | val_loss=0.1187 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8944 | val_dqn_proxy_expanded5=0.9146

Epoch 003 | train_loss=0.2536 | ce=0.1035 | ent=0.1695 | center=1.4669 | val_loss=0.1094 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9513 | val_dqn_proxy_expanded5=0.9588

Epoch 004 | train_loss=0.2246 | ce=0.0878 | ent=0.1428 | center=1.3400 | val_loss=0.1041 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9100 | val_dqn_proxy_expanded5=0.9287

Epoch 005 | train_loss=0.2170 | ce=0.0888 | ent=0.1300 | center=1.2557 | val_loss=0.0990 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9458 | val_dqn_proxy_expanded5=0.9539

Epoch 006 | train_loss=0.2025 | ce=0.0816 | ent=0.1264 | center=1.1840 | val_loss=0.0937 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9359 | val_dqn_proxy_expanded5=0.9465

Epoch 007 | train_loss=0.1872 | ce=0.0712 | ent=0.1123 | center=1.1375 | val_loss=0.0948 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9378 | val_dqn_proxy_expanded5=0.9496

Epoch 008 | train_loss=0.1828 | ce=0.0710 | ent=0.1048 | center=1.0971 | val_loss=0.0912 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9380 | val_dqn_proxy_expanded5=0.9488

Epoch 009 | train_loss=0.1742 | ce=0.0663 | ent=0.0902 | center=1.0604 | val_loss=0.0841 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9429 | val_dqn_proxy_expanded5=0.9520

Epoch 010 | train_loss=0.1654 | ce=0.0619 | ent=0.0941 | center=1.0158 | val_loss=0.0904 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9358 | val_dqn_proxy_expanded5=0.9479

Epoch 011 | train_loss=0.1594 | ce=0.0594 | ent=0.0818 | center=0.9835 | val_loss=0.0818 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9407 | val_dqn_proxy_expanded5=0.9500

Epoch 012 | train_loss=0.1565 | ce=0.0607 | ent=0.0846 | center=0.9409 | val_loss=0.0769 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9288 | val_dqn_proxy_expanded5=0.9433

Epoch 013 | train_loss=0.1535 | ce=0.0585 | ent=0.0838 | center=0.9333 | val_loss=0.0580 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9142 | val_dqn_proxy_expanded5=0.9296

Epoch 014 | train_loss=0.1380 | ce=0.0449 | ent=0.0765 | center=0.9162 | val_loss=0.0589 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9361 | val_dqn_proxy_expanded5=0.9451

Epoch 015 | train_loss=0.1241 | ce=0.0342 | ent=0.0680 | center=0.8859 | val_loss=0.0447 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9543 | val_dqn_proxy_expanded5=0.9635

Epoch 016 | train_loss=0.1154 | ce=0.0286 | ent=0.0604 | center=0.8561 | val_loss=0.0500 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9659 | val_dqn_proxy_expanded5=0.9706

Epoch 017 | train_loss=0.1042 | ce=0.0201 | ent=0.0516 | center=0.8313 | val_loss=0.0472 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9771 | val_dqn_proxy_expanded5=0.9799

Epoch 018 | train_loss=0.1027 | ce=0.0216 | ent=0.0489 | center=0.8017 | val_loss=0.0482 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9441 | val_dqn_proxy_expanded5=0.9527

Epoch 019 | train_loss=0.1058 | ce=0.0263 | ent=0.0520 | center=0.7846 | val_loss=0.0466 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9716 | val_dqn_proxy_expanded5=0.9754

Epoch 020 | train_loss=0.0971 | ce=0.0195 | ent=0.0444 | center=0.7664 | val_loss=0.0437 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9603 | val_dqn_proxy_expanded5=0.9648

Epoch 021 | train_loss=0.0939 | ce=0.0192 | ent=0.0433 | center=0.7376 | val_loss=0.0443 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9492 | val_dqn_proxy_expanded5=0.9523

Epoch 022 | train_loss=0.0968 | ce=0.0239 | ent=0.0393 | center=0.7217 | val_loss=0.0442 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9627 | val_dqn_proxy_expanded5=0.9655

Epoch 023 | train_loss=0.0912 | ce=0.0207 | ent=0.0385 | center=0.6975 | val_loss=0.0366 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9522 | val_dqn_proxy_expanded5=0.9522

Epoch 024 | train_loss=0.0921 | ce=0.0234 | ent=0.0395 | center=0.6788 | val_loss=0.0471 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9400 | val_dqn_proxy_expanded5=0.9387

Epoch 025 | train_loss=0.0856 | ce=0.0186 | ent=0.0340 | center=0.6629 | val_loss=0.0394 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9398 | val_dqn_proxy_expanded5=0.9349

Epoch 026 | train_loss=0.0857 | ce=0.0202 | ent=0.0360 | center=0.6482 | val_loss=0.0480 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9627 | val_dqn_proxy_expanded5=0.9599

Epoch 027 | train_loss=0.0825 | ce=0.0184 | ent=0.0350 | center=0.6341 | val_loss=0.0471 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9078 | val_dqn_proxy_expanded5=0.8991

Epoch 028 | train_loss=0.0808 | ce=0.0186 | ent=0.0318 | center=0.6159 | val_loss=0.0475 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9695 | val_dqn_proxy_expanded5=0.9602

Epoch 029 | train_loss=0.0771 | ce=0.0165 | ent=0.0309 | center=0.5991 | val_loss=0.0509 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9225 | val_dqn_proxy_expanded5=0.9112

Epoch 030 | train_loss=0.0770 | ce=0.0180 | ent=0.0253 | center=0.5852 | val_loss=0.0447 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9323 | val_dqn_proxy_expanded5=0.9183

Epoch 031 | train_loss=0.0757 | ce=0.0175 | ent=0.0320 | center=0.5756 | val_loss=0.0471 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9215 | val_dqn_proxy_expanded5=0.9093

Epoch 032 | train_loss=0.0792 | ce=0.0213 | ent=0.0270 | center=0.5732 | val_loss=0.0416 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9419 | val_dqn_proxy_expanded5=0.9249
Early stopping at epoch 32 (best epoch: 17)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
11,confman_paperish_mild_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-46_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,confman_baseline_knownonly_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-26_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,confman_paperish_mild_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-39_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
5,confman_baseline_openconf_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-30_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,confman_baseline_openconf_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-28_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,confman_baseline_openconf_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-35_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
8,confman_paperish_mild_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-37_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,confman_baseline_openconf_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-33_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
10,confman_paperish_mild_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-43_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,confman_baseline_knownonly_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-19_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,confman_baseline_knownonly_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-21_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,confman_baseline_knownonly_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-24_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"

================================================================================
Running experiment 13/32
{
  "run_name": "confman_paperish_mid_unkPA2_c16384_seed0",
  "task": "pa",
  "split_mode": "open_pa",
  "unknown_pas": [
    "PA2"
  ],
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "lr": 0.0001,
  "weight_decay": 0.0001,
  "lambda_center": 0.1,
  "label_smoothing": 0.0,
  "entropy_loss_weight": 0.05,
  "mlp_dropout": 0.5,
  "class_weight_mode": null,
  "grad_clip_norm": 1.0,
  "scheduler_name": "plateau",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "epochs": 200,
  "early_stopping_patience": 15,
  "save_root": "results_pa_confmanifold_coarse"
}
================================================================================

Epoch 001 | train_loss=0.9922 | ce=0.8343 | ent=0.9847 | center=1.0862 | val_loss=0.4007 | val_acc=0.9556 | val_macro_f1=0.9552 | val_dqn_proxy_softmax3=0.7153 | val_dqn_proxy_expanded5=0.7322

Epoch 002 | train_loss=0.4211 | ce=0.2497 | ent=0.3977 | center=1.5143 | val_loss=0.1306 | val_acc=0.9741 | val_macro_f1=0.9742 | val_dqn_proxy_softmax3=0.6634 | val_dqn_proxy_expanded5=0.6818

Epoch 003 | train_loss=0.3104 | ce=0.1557 | ent=0.2275 | center=1.4334 | val_loss=0.0988 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.5916 | val_dqn_proxy_expanded5=0.6776

Epoch 004 | train_loss=0.2749 | ce=0.1306 | ent=0.1814 | center=1.3530 | val_loss=0.1156 | val_acc=0.9778 | val_macro_f1=0.9779 | val_dqn_proxy_softmax3=0.8107 | val_dqn_proxy_expanded5=0.8055

Epoch 005 | train_loss=0.2472 | ce=0.1142 | ent=0.1529 | center=1.2540 | val_loss=0.0998 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6750 | val_dqn_proxy_expanded5=0.7279

Epoch 006 | train_loss=0.2314 | ce=0.1050 | ent=0.1417 | center=1.1934 | val_loss=0.0930 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.5446 | val_dqn_proxy_expanded5=0.6641

Epoch 007 | train_loss=0.2159 | ce=0.0962 | ent=0.1269 | center=1.1330 | val_loss=0.0731 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.5410 | val_dqn_proxy_expanded5=0.6368

Epoch 008 | train_loss=0.2195 | ce=0.1046 | ent=0.1347 | center=1.0820 | val_loss=0.0727 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.5552 | val_dqn_proxy_expanded5=0.6566

Epoch 009 | train_loss=0.2033 | ce=0.0928 | ent=0.1133 | center=1.0488 | val_loss=0.0710 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6078 | val_dqn_proxy_expanded5=0.6847

Epoch 010 | train_loss=0.1989 | ce=0.0920 | ent=0.1023 | center=1.0178 | val_loss=0.0792 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7390 | val_dqn_proxy_expanded5=0.7669

Epoch 011 | train_loss=0.1872 | ce=0.0847 | ent=0.0958 | center=0.9768 | val_loss=0.0669 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6128 | val_dqn_proxy_expanded5=0.6921

Epoch 012 | train_loss=0.1757 | ce=0.0763 | ent=0.0853 | center=0.9505 | val_loss=0.0689 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6254 | val_dqn_proxy_expanded5=0.6886

Epoch 013 | train_loss=0.1860 | ce=0.0890 | ent=0.0837 | center=0.9276 | val_loss=0.0665 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.5686 | val_dqn_proxy_expanded5=0.6646

Epoch 014 | train_loss=0.1659 | ce=0.0726 | ent=0.0862 | center=0.8897 | val_loss=0.0726 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6733 | val_dqn_proxy_expanded5=0.7144

Epoch 015 | train_loss=0.1558 | ce=0.0652 | ent=0.0815 | center=0.8652 | val_loss=0.0617 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6201 | val_dqn_proxy_expanded5=0.6955

Epoch 016 | train_loss=0.1660 | ce=0.0763 | ent=0.0797 | center=0.8569 | val_loss=0.0564 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.5195 | val_dqn_proxy_expanded5=0.6488

Epoch 017 | train_loss=0.1457 | ce=0.0594 | ent=0.0712 | center=0.8271 | val_loss=0.0566 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7103 | val_dqn_proxy_expanded5=0.7541

Epoch 018 | train_loss=0.1363 | ce=0.0523 | ent=0.0683 | center=0.8056 | val_loss=0.0546 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8113 | val_dqn_proxy_expanded5=0.8350

Epoch 019 | train_loss=0.1433 | ce=0.0610 | ent=0.0633 | center=0.7912 | val_loss=0.0456 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6934 | val_dqn_proxy_expanded5=0.7311

Epoch 020 | train_loss=0.1262 | ce=0.0460 | ent=0.0658 | center=0.7695 | val_loss=0.0477 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7955 | val_dqn_proxy_expanded5=0.8195

Epoch 021 | train_loss=0.1223 | ce=0.0430 | ent=0.0583 | center=0.7633 | val_loss=0.0433 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6503 | val_dqn_proxy_expanded5=0.6848

Epoch 022 | train_loss=0.1098 | ce=0.0338 | ent=0.0490 | center=0.7357 | val_loss=0.0371 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.5995 | val_dqn_proxy_expanded5=0.6763

Epoch 023 | train_loss=0.1161 | ce=0.0419 | ent=0.0505 | center=0.7167 | val_loss=0.0405 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6408 | val_dqn_proxy_expanded5=0.6849

Epoch 024 | train_loss=0.1066 | ce=0.0347 | ent=0.0444 | center=0.6965 | val_loss=0.0357 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.5619 | val_dqn_proxy_expanded5=0.6692

Epoch 025 | train_loss=0.1043 | ce=0.0341 | ent=0.0468 | center=0.6781 | val_loss=0.0339 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.5740 | val_dqn_proxy_expanded5=0.6725

Epoch 026 | train_loss=0.0997 | ce=0.0310 | ent=0.0429 | center=0.6655 | val_loss=0.0400 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.5526 | val_dqn_proxy_expanded5=0.6654

Epoch 027 | train_loss=0.1005 | ce=0.0343 | ent=0.0423 | center=0.6409 | val_loss=0.0362 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.5986 | val_dqn_proxy_expanded5=0.6693

Epoch 028 | train_loss=0.0951 | ce=0.0304 | ent=0.0406 | center=0.6261 | val_loss=0.0489 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8205 | val_dqn_proxy_expanded5=0.8161

Epoch 029 | train_loss=0.0920 | ce=0.0289 | ent=0.0378 | center=0.6123 | val_loss=0.0431 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7015 | val_dqn_proxy_expanded5=0.7034

Epoch 030 | train_loss=0.0965 | ce=0.0352 | ent=0.0365 | center=0.5948 | val_loss=0.0390 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7224 | val_dqn_proxy_expanded5=0.7201

Epoch 031 | train_loss=0.0909 | ce=0.0308 | ent=0.0344 | center=0.5840 | val_loss=0.0389 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6291 | val_dqn_proxy_expanded5=0.6924

Epoch 032 | train_loss=0.0860 | ce=0.0274 | ent=0.0379 | center=0.5677 | val_loss=0.0424 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6891 | val_dqn_proxy_expanded5=0.6897

Epoch 033 | train_loss=0.0886 | ce=0.0312 | ent=0.0311 | center=0.5585 | val_loss=0.0379 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6685 | val_dqn_proxy_expanded5=0.7052

Epoch 034 | train_loss=0.0870 | ce=0.0297 | ent=0.0361 | center=0.5550 | val_loss=0.0371 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.5729 | val_dqn_proxy_expanded5=0.6765

Epoch 035 | train_loss=0.0845 | ce=0.0278 | ent=0.0350 | center=0.5489 | val_loss=0.0354 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6031 | val_dqn_proxy_expanded5=0.6822

Epoch 036 | train_loss=0.0828 | ce=0.0266 | ent=0.0369 | center=0.5438 | val_loss=0.0386 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6785 | val_dqn_proxy_expanded5=0.7068

Epoch 037 | train_loss=0.0896 | ce=0.0343 | ent=0.0308 | center=0.5379 | val_loss=0.0341 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.5075 | val_dqn_proxy_expanded5=0.6752

Epoch 038 | train_loss=0.0806 | ce=0.0259 | ent=0.0384 | center=0.5278 | val_loss=0.0378 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6545 | val_dqn_proxy_expanded5=0.7005

Epoch 039 | train_loss=0.0824 | ce=0.0281 | ent=0.0319 | center=0.5275 | val_loss=0.0365 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.5771 | val_dqn_proxy_expanded5=0.6845

Epoch 040 | train_loss=0.0815 | ce=0.0278 | ent=0.0338 | center=0.5208 | val_loss=0.0356 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.5251 | val_dqn_proxy_expanded5=0.6802

Epoch 041 | train_loss=0.0807 | ce=0.0270 | ent=0.0337 | center=0.5198 | val_loss=0.0373 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6299 | val_dqn_proxy_expanded5=0.7017

Epoch 042 | train_loss=0.0781 | ce=0.0250 | ent=0.0330 | center=0.5152 | val_loss=0.0388 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.5389 | val_dqn_proxy_expanded5=0.6714

Epoch 043 | train_loss=0.0781 | ce=0.0254 | ent=0.0331 | center=0.5103 | val_loss=0.0394 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7239 | val_dqn_proxy_expanded5=0.7139
Early stopping at epoch 43 (best epoch: 28)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
11,confman_paperish_mild_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-46_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,confman_baseline_knownonly_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-26_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,confman_paperish_mild_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-39_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
5,confman_baseline_openconf_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-30_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,confman_baseline_openconf_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-28_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,confman_baseline_openconf_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-35_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
8,confman_paperish_mild_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-37_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,confman_baseline_openconf_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-33_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
10,confman_paperish_mild_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-43_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,confman_baseline_knownonly_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-19_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,confman_paperish_mid_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-48_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,confman_baseline_knownonly_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-21_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,confman_baseline_knownonly_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-24_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"

================================================================================
Running experiment 14/32
{
  "run_name": "confman_paperish_mid_unkPA3_c16384_seed0",
  "task": "pa",
  "split_mode": "open_pa",
  "unknown_pas": [
    "PA3"
  ],
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "lr": 0.0001,
  "weight_decay": 0.0001,
  "lambda_center": 0.1,
  "label_smoothing": 0.0,
  "entropy_loss_weight": 0.05,
  "mlp_dropout": 0.5,
  "class_weight_mode": null,
  "grad_clip_norm": 1.0,
  "scheduler_name": "plateau",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "epochs": 200,
  "early_stopping_patience": 15,
  "save_root": "results_pa_confmanifold_coarse"
}
================================================================================

Epoch 001 | train_loss=1.0408 | ce=0.8749 | ent=1.0051 | center=1.1557 | val_loss=0.4779 | val_acc=0.8667 | val_macro_f1=0.8649 | val_dqn_proxy_softmax3=0.7160 | val_dqn_proxy_expanded5=0.7538

Epoch 002 | train_loss=0.5096 | ce=0.3263 | ent=0.5136 | center=1.5766 | val_loss=0.1679 | val_acc=0.9370 | val_macro_f1=0.9374 | val_dqn_proxy_softmax3=0.8169 | val_dqn_proxy_expanded5=0.7889

Epoch 003 | train_loss=0.4066 | ce=0.2308 | ent=0.3241 | center=1.5959 | val_loss=0.1184 | val_acc=0.9630 | val_macro_f1=0.9630 | val_dqn_proxy_softmax3=0.8981 | val_dqn_proxy_expanded5=0.8514

Epoch 004 | train_loss=0.3428 | ce=0.1825 | ent=0.2537 | center=1.4761 | val_loss=0.1057 | val_acc=0.9519 | val_macro_f1=0.9521 | val_dqn_proxy_softmax3=0.8635 | val_dqn_proxy_expanded5=0.8392

Epoch 005 | train_loss=0.3117 | ce=0.1614 | ent=0.2200 | center=1.3932 | val_loss=0.0943 | val_acc=0.9667 | val_macro_f1=0.9669 | val_dqn_proxy_softmax3=0.9568 | val_dqn_proxy_expanded5=0.9235

Epoch 006 | train_loss=0.2906 | ce=0.1466 | ent=0.2099 | center=1.3344 | val_loss=0.0780 | val_acc=0.9741 | val_macro_f1=0.9742 | val_dqn_proxy_softmax3=0.9166 | val_dqn_proxy_expanded5=0.8998

Epoch 007 | train_loss=0.2632 | ce=0.1260 | ent=0.1881 | center=1.2776 | val_loss=0.1203 | val_acc=0.9407 | val_macro_f1=0.9411 | val_dqn_proxy_softmax3=0.9144 | val_dqn_proxy_expanded5=0.8969

Epoch 008 | train_loss=0.2664 | ce=0.1343 | ent=0.1753 | center=1.2330 | val_loss=0.0745 | val_acc=0.9704 | val_macro_f1=0.9705 | val_dqn_proxy_softmax3=0.9271 | val_dqn_proxy_expanded5=0.9243

Epoch 009 | train_loss=0.2556 | ce=0.1272 | ent=0.1681 | center=1.2000 | val_loss=0.0896 | val_acc=0.9704 | val_macro_f1=0.9703 | val_dqn_proxy_softmax3=0.9603 | val_dqn_proxy_expanded5=0.9434

Epoch 010 | train_loss=0.2363 | ce=0.1108 | ent=0.1513 | center=1.1793 | val_loss=0.0487 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9649 | val_dqn_proxy_expanded5=0.9492

Epoch 011 | train_loss=0.2196 | ce=0.0979 | ent=0.1386 | center=1.1480 | val_loss=0.0625 | val_acc=0.9741 | val_macro_f1=0.9741 | val_dqn_proxy_softmax3=0.9447 | val_dqn_proxy_expanded5=0.9233

Epoch 012 | train_loss=0.2312 | ce=0.1152 | ent=0.1394 | center=1.0905 | val_loss=0.0733 | val_acc=0.9704 | val_macro_f1=0.9703 | val_dqn_proxy_softmax3=0.9605 | val_dqn_proxy_expanded5=0.9521

Epoch 013 | train_loss=0.2043 | ce=0.0906 | ent=0.1292 | center=1.0721 | val_loss=0.0825 | val_acc=0.9667 | val_macro_f1=0.9666 | val_dqn_proxy_softmax3=0.9621 | val_dqn_proxy_expanded5=0.9518

Epoch 014 | train_loss=0.2123 | ce=0.1024 | ent=0.1279 | center=1.0359 | val_loss=0.0901 | val_acc=0.9593 | val_macro_f1=0.9591 | val_dqn_proxy_softmax3=0.9656 | val_dqn_proxy_expanded5=0.9577

Epoch 015 | train_loss=0.1865 | ce=0.0793 | ent=0.1101 | center=1.0179 | val_loss=0.0371 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9682 | val_dqn_proxy_expanded5=0.9605

Epoch 016 | train_loss=0.1812 | ce=0.0768 | ent=0.1091 | center=0.9890 | val_loss=0.0605 | val_acc=0.9704 | val_macro_f1=0.9703 | val_dqn_proxy_softmax3=0.9400 | val_dqn_proxy_expanded5=0.9218

Epoch 017 | train_loss=0.1871 | ce=0.0850 | ent=0.1040 | center=0.9684 | val_loss=0.0464 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7916 | val_dqn_proxy_expanded5=0.8226

Epoch 018 | train_loss=0.1765 | ce=0.0770 | ent=0.0962 | center=0.9465 | val_loss=0.0685 | val_acc=0.9704 | val_macro_f1=0.9704 | val_dqn_proxy_softmax3=0.7558 | val_dqn_proxy_expanded5=0.7874

Epoch 019 | train_loss=0.1677 | ce=0.0708 | ent=0.0947 | center=0.9215 | val_loss=0.0701 | val_acc=0.9704 | val_macro_f1=0.9703 | val_dqn_proxy_softmax3=0.9540 | val_dqn_proxy_expanded5=0.9516

Epoch 020 | train_loss=0.1673 | ce=0.0732 | ent=0.0905 | center=0.8953 | val_loss=0.0950 | val_acc=0.9630 | val_macro_f1=0.9628 | val_dqn_proxy_softmax3=0.8959 | val_dqn_proxy_expanded5=0.9007

Epoch 021 | train_loss=0.1570 | ce=0.0648 | ent=0.0882 | center=0.8779 | val_loss=0.0502 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.9423 | val_dqn_proxy_expanded5=0.9432

Epoch 022 | train_loss=0.1433 | ce=0.0536 | ent=0.0756 | center=0.8592 | val_loss=0.0506 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9553 | val_dqn_proxy_expanded5=0.9479

Epoch 023 | train_loss=0.1257 | ce=0.0376 | ent=0.0735 | center=0.8439 | val_loss=0.0223 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9800 | val_dqn_proxy_expanded5=0.9482

Epoch 024 | train_loss=0.1319 | ce=0.0455 | ent=0.0754 | center=0.8269 | val_loss=0.0361 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9349 | val_dqn_proxy_expanded5=0.9280

Epoch 025 | train_loss=0.1258 | ce=0.0396 | ent=0.0697 | center=0.8270 | val_loss=0.0260 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9658 | val_dqn_proxy_expanded5=0.9628

Epoch 026 | train_loss=0.1313 | ce=0.0465 | ent=0.0653 | center=0.8148 | val_loss=0.0152 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9772 | val_dqn_proxy_expanded5=0.9676

Epoch 027 | train_loss=0.1250 | ce=0.0419 | ent=0.0666 | center=0.7975 | val_loss=0.0163 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9726 | val_dqn_proxy_expanded5=0.9565

Epoch 028 | train_loss=0.1151 | ce=0.0330 | ent=0.0615 | center=0.7905 | val_loss=0.0137 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9777 | val_dqn_proxy_expanded5=0.9641

Epoch 029 | train_loss=0.1295 | ce=0.0484 | ent=0.0676 | center=0.7772 | val_loss=0.0216 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9752 | val_dqn_proxy_expanded5=0.9655

Epoch 030 | train_loss=0.1319 | ce=0.0513 | ent=0.0616 | center=0.7750 | val_loss=0.0258 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9760 | val_dqn_proxy_expanded5=0.9695

Epoch 031 | train_loss=0.1225 | ce=0.0428 | ent=0.0581 | center=0.7684 | val_loss=0.0232 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9728 | val_dqn_proxy_expanded5=0.9582

Epoch 032 | train_loss=0.1256 | ce=0.0474 | ent=0.0576 | center=0.7525 | val_loss=0.0297 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9675 | val_dqn_proxy_expanded5=0.9520

Epoch 033 | train_loss=0.1315 | ce=0.0541 | ent=0.0574 | center=0.7446 | val_loss=0.0389 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9828 | val_dqn_proxy_expanded5=0.9693

Epoch 034 | train_loss=0.1276 | ce=0.0512 | ent=0.0597 | center=0.7334 | val_loss=0.0155 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9747 | val_dqn_proxy_expanded5=0.9547

Epoch 035 | train_loss=0.1051 | ce=0.0297 | ent=0.0493 | center=0.7296 | val_loss=0.0095 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9785 | val_dqn_proxy_expanded5=0.9594

Epoch 036 | train_loss=0.1052 | ce=0.0305 | ent=0.0515 | center=0.7216 | val_loss=0.0153 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9660 | val_dqn_proxy_expanded5=0.9469

Epoch 037 | train_loss=0.1099 | ce=0.0364 | ent=0.0528 | center=0.7084 | val_loss=0.0128 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9589 | val_dqn_proxy_expanded5=0.9373

Epoch 038 | train_loss=0.1071 | ce=0.0333 | ent=0.0514 | center=0.7121 | val_loss=0.0135 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9733 | val_dqn_proxy_expanded5=0.9385

Epoch 039 | train_loss=0.1189 | ce=0.0459 | ent=0.0540 | center=0.7033 | val_loss=0.0326 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9808 | val_dqn_proxy_expanded5=0.9489

Epoch 040 | train_loss=0.1076 | ce=0.0350 | ent=0.0513 | center=0.7005 | val_loss=0.0107 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9762 | val_dqn_proxy_expanded5=0.9403

Epoch 041 | train_loss=0.1084 | ce=0.0361 | ent=0.0489 | center=0.6982 | val_loss=0.0081 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9790 | val_dqn_proxy_expanded5=0.9427

Epoch 042 | train_loss=0.1046 | ce=0.0329 | ent=0.0488 | center=0.6930 | val_loss=0.0112 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9782 | val_dqn_proxy_expanded5=0.9506

Epoch 043 | train_loss=0.1085 | ce=0.0371 | ent=0.0483 | center=0.6889 | val_loss=0.0142 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9804 | val_dqn_proxy_expanded5=0.9537

Epoch 044 | train_loss=0.1132 | ce=0.0425 | ent=0.0476 | center=0.6827 | val_loss=0.0092 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9814 | val_dqn_proxy_expanded5=0.9529

Epoch 045 | train_loss=0.0992 | ce=0.0290 | ent=0.0507 | center=0.6765 | val_loss=0.0184 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9724 | val_dqn_proxy_expanded5=0.9454

Epoch 046 | train_loss=0.1076 | ce=0.0377 | ent=0.0490 | center=0.6742 | val_loss=0.0082 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9702 | val_dqn_proxy_expanded5=0.9508

Epoch 047 | train_loss=0.1031 | ce=0.0334 | ent=0.0470 | center=0.6738 | val_loss=0.0108 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9817 | val_dqn_proxy_expanded5=0.9559

Epoch 048 | train_loss=0.0930 | ce=0.0239 | ent=0.0410 | center=0.6707 | val_loss=0.0083 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9864 | val_dqn_proxy_expanded5=0.9678

Epoch 049 | train_loss=0.0950 | ce=0.0268 | ent=0.0394 | center=0.6623 | val_loss=0.0077 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9836 | val_dqn_proxy_expanded5=0.9565

Epoch 050 | train_loss=0.1064 | ce=0.0381 | ent=0.0457 | center=0.6600 | val_loss=0.0136 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9862 | val_dqn_proxy_expanded5=0.9687

Epoch 051 | train_loss=0.0978 | ce=0.0300 | ent=0.0429 | center=0.6564 | val_loss=0.0099 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9782 | val_dqn_proxy_expanded5=0.9402

Epoch 052 | train_loss=0.0900 | ce=0.0224 | ent=0.0412 | center=0.6558 | val_loss=0.0113 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9797 | val_dqn_proxy_expanded5=0.9414

Epoch 053 | train_loss=0.0852 | ce=0.0178 | ent=0.0405 | center=0.6535 | val_loss=0.0053 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9812 | val_dqn_proxy_expanded5=0.9418

Epoch 054 | train_loss=0.0988 | ce=0.0313 | ent=0.0430 | center=0.6544 | val_loss=0.0085 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9783 | val_dqn_proxy_expanded5=0.9366

Epoch 055 | train_loss=0.1073 | ce=0.0404 | ent=0.0411 | center=0.6483 | val_loss=0.0080 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9773 | val_dqn_proxy_expanded5=0.9506

Epoch 056 | train_loss=0.0940 | ce=0.0273 | ent=0.0442 | center=0.6449 | val_loss=0.0081 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9828 | val_dqn_proxy_expanded5=0.9590

Epoch 057 | train_loss=0.1012 | ce=0.0351 | ent=0.0392 | center=0.6411 | val_loss=0.0057 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9836 | val_dqn_proxy_expanded5=0.9561

Epoch 058 | train_loss=0.0992 | ce=0.0331 | ent=0.0416 | center=0.6401 | val_loss=0.0138 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9654 | val_dqn_proxy_expanded5=0.9275

Epoch 059 | train_loss=0.0882 | ce=0.0223 | ent=0.0384 | center=0.6400 | val_loss=0.0058 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9763 | val_dqn_proxy_expanded5=0.9377

Epoch 060 | train_loss=0.0873 | ce=0.0217 | ent=0.0363 | center=0.6377 | val_loss=0.0067 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9791 | val_dqn_proxy_expanded5=0.9403

Epoch 061 | train_loss=0.0939 | ce=0.0282 | ent=0.0351 | center=0.6397 | val_loss=0.0083 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9782 | val_dqn_proxy_expanded5=0.9445

Epoch 062 | train_loss=0.0824 | ce=0.0176 | ent=0.0358 | center=0.6307 | val_loss=0.0063 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9844 | val_dqn_proxy_expanded5=0.9485

Epoch 063 | train_loss=0.0897 | ce=0.0242 | ent=0.0434 | center=0.6331 | val_loss=0.0055 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9787 | val_dqn_proxy_expanded5=0.9421
Early stopping at epoch 63 (best epoch: 48)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
11,confman_paperish_mild_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-46_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,confman_baseline_knownonly_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-26_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,confman_paperish_mid_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-52_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
9,confman_paperish_mild_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-39_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
5,confman_baseline_openconf_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-30_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,confman_baseline_openconf_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-28_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,confman_baseline_openconf_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-35_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
8,confman_paperish_mild_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-37_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,confman_baseline_openconf_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-33_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
10,confman_paperish_mild_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-43_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,confman_baseline_knownonly_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-19_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,confman_paperish_mid_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-48_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,confman_baseline_knownonly_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-21_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,confman_baseline_knownonly_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-24_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"

================================================================================
Running experiment 15/32
{
  "run_name": "confman_paperish_mid_unkPA4_c16384_seed0",
  "task": "pa",
  "split_mode": "open_pa",
  "unknown_pas": [
    "PA4"
  ],
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "lr": 0.0001,
  "weight_decay": 0.0001,
  "lambda_center": 0.1,
  "label_smoothing": 0.0,
  "entropy_loss_weight": 0.05,
  "mlp_dropout": 0.5,
  "class_weight_mode": null,
  "grad_clip_norm": 1.0,
  "scheduler_name": "plateau",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "epochs": 200,
  "early_stopping_patience": 15,
  "save_root": "results_pa_confmanifold_coarse"
}
================================================================================

Epoch 001 | train_loss=0.9901 | ce=0.8332 | ent=0.9735 | center=1.0824 | val_loss=0.4500 | val_acc=0.8185 | val_macro_f1=0.7999 | val_dqn_proxy_softmax3=0.6723 | val_dqn_proxy_expanded5=0.6695

Epoch 002 | train_loss=0.5407 | ce=0.3495 | ent=0.5036 | center=1.6596 | val_loss=0.2520 | val_acc=0.9333 | val_macro_f1=0.9333 | val_dqn_proxy_softmax3=0.7300 | val_dqn_proxy_expanded5=0.7411

Epoch 003 | train_loss=0.4623 | ce=0.2825 | ent=0.3789 | center=1.6087 | val_loss=0.2328 | val_acc=0.9296 | val_macro_f1=0.9298 | val_dqn_proxy_softmax3=0.7290 | val_dqn_proxy_expanded5=0.7506

Epoch 004 | train_loss=0.3873 | ce=0.2269 | ent=0.3111 | center=1.4485 | val_loss=0.1659 | val_acc=0.9519 | val_macro_f1=0.9520 | val_dqn_proxy_softmax3=0.7502 | val_dqn_proxy_expanded5=0.7702

Epoch 005 | train_loss=0.3790 | ce=0.2314 | ent=0.2669 | center=1.3432 | val_loss=0.1713 | val_acc=0.9519 | val_macro_f1=0.9521 | val_dqn_proxy_softmax3=0.7360 | val_dqn_proxy_expanded5=0.7421

Epoch 006 | train_loss=0.3222 | ce=0.1809 | ent=0.2368 | center=1.2946 | val_loss=0.1717 | val_acc=0.9519 | val_macro_f1=0.9518 | val_dqn_proxy_softmax3=0.7474 | val_dqn_proxy_expanded5=0.7500

Epoch 007 | train_loss=0.2905 | ce=0.1576 | ent=0.2140 | center=1.2218 | val_loss=0.1232 | val_acc=0.9667 | val_macro_f1=0.9669 | val_dqn_proxy_softmax3=0.7499 | val_dqn_proxy_expanded5=0.7243

Epoch 008 | train_loss=0.2785 | ce=0.1497 | ent=0.1862 | center=1.1948 | val_loss=0.1125 | val_acc=0.9704 | val_macro_f1=0.9704 | val_dqn_proxy_softmax3=0.7684 | val_dqn_proxy_expanded5=0.7408

Epoch 009 | train_loss=0.2486 | ce=0.1247 | ent=0.1660 | center=1.1556 | val_loss=0.1243 | val_acc=0.9630 | val_macro_f1=0.9629 | val_dqn_proxy_softmax3=0.7705 | val_dqn_proxy_expanded5=0.7402

Epoch 010 | train_loss=0.2348 | ce=0.1156 | ent=0.1498 | center=1.1173 | val_loss=0.1081 | val_acc=0.9778 | val_macro_f1=0.9779 | val_dqn_proxy_softmax3=0.7522 | val_dqn_proxy_expanded5=0.7260

Epoch 011 | train_loss=0.2107 | ce=0.0959 | ent=0.1351 | center=1.0800 | val_loss=0.1024 | val_acc=0.9741 | val_macro_f1=0.9743 | val_dqn_proxy_softmax3=0.7669 | val_dqn_proxy_expanded5=0.7350

Epoch 012 | train_loss=0.2164 | ce=0.1052 | ent=0.1400 | center=1.0412 | val_loss=0.0844 | val_acc=0.9815 | val_macro_f1=0.9816 | val_dqn_proxy_softmax3=0.7753 | val_dqn_proxy_expanded5=0.7426

Epoch 013 | train_loss=0.2025 | ce=0.0947 | ent=0.1379 | center=1.0091 | val_loss=0.0772 | val_acc=0.9815 | val_macro_f1=0.9816 | val_dqn_proxy_softmax3=0.8472 | val_dqn_proxy_expanded5=0.7881

Epoch 014 | train_loss=0.1716 | ce=0.0672 | ent=0.1134 | center=0.9871 | val_loss=0.0807 | val_acc=0.9741 | val_macro_f1=0.9743 | val_dqn_proxy_softmax3=0.9010 | val_dqn_proxy_expanded5=0.8216

Epoch 015 | train_loss=0.1892 | ce=0.0879 | ent=0.1124 | center=0.9567 | val_loss=0.1144 | val_acc=0.9667 | val_macro_f1=0.9669 | val_dqn_proxy_softmax3=0.9236 | val_dqn_proxy_expanded5=0.8415

Epoch 016 | train_loss=0.1939 | ce=0.0967 | ent=0.1053 | center=0.9200 | val_loss=0.0434 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.9285 | val_dqn_proxy_expanded5=0.8974

Epoch 017 | train_loss=0.1518 | ce=0.0571 | ent=0.0991 | center=0.8975 | val_loss=0.0323 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9375 | val_dqn_proxy_expanded5=0.9188

Epoch 018 | train_loss=0.1366 | ce=0.0443 | ent=0.0920 | center=0.8767 | val_loss=0.0198 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9603 | val_dqn_proxy_expanded5=0.9274

Epoch 019 | train_loss=0.1336 | ce=0.0432 | ent=0.0850 | center=0.8612 | val_loss=0.0225 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9565 | val_dqn_proxy_expanded5=0.8873

Epoch 020 | train_loss=0.1432 | ce=0.0569 | ent=0.0801 | center=0.8227 | val_loss=0.0227 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9373 | val_dqn_proxy_expanded5=0.8600

Epoch 021 | train_loss=0.1359 | ce=0.0515 | ent=0.0811 | center=0.8027 | val_loss=0.0394 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9390 | val_dqn_proxy_expanded5=0.8652

Epoch 022 | train_loss=0.1324 | ce=0.0498 | ent=0.0761 | center=0.7878 | val_loss=0.0286 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9212 | val_dqn_proxy_expanded5=0.8459

Epoch 023 | train_loss=0.1275 | ce=0.0471 | ent=0.0720 | center=0.7676 | val_loss=0.0188 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9586 | val_dqn_proxy_expanded5=0.8668

Epoch 024 | train_loss=0.1326 | ce=0.0552 | ent=0.0696 | center=0.7387 | val_loss=0.0193 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9191 | val_dqn_proxy_expanded5=0.8377

Epoch 025 | train_loss=0.1218 | ce=0.0460 | ent=0.0667 | center=0.7244 | val_loss=0.0131 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.8962 | val_dqn_proxy_expanded5=0.8233

Epoch 026 | train_loss=0.1302 | ce=0.0562 | ent=0.0697 | center=0.7051 | val_loss=0.0303 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.8583 | val_dqn_proxy_expanded5=0.7969

Epoch 027 | train_loss=0.1431 | ce=0.0707 | ent=0.0664 | center=0.6902 | val_loss=0.0175 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7739 | val_dqn_proxy_expanded5=0.7461

Epoch 028 | train_loss=0.1174 | ce=0.0471 | ent=0.0570 | center=0.6740 | val_loss=0.0298 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.7675 | val_dqn_proxy_expanded5=0.7397

Epoch 029 | train_loss=0.1189 | ce=0.0500 | ent=0.0572 | center=0.6604 | val_loss=0.0131 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8265 | val_dqn_proxy_expanded5=0.7814

Epoch 030 | train_loss=0.1118 | ce=0.0448 | ent=0.0532 | center=0.6436 | val_loss=0.0172 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9013 | val_dqn_proxy_expanded5=0.8267

Epoch 031 | train_loss=0.1133 | ce=0.0479 | ent=0.0539 | center=0.6262 | val_loss=0.0217 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.8596 | val_dqn_proxy_expanded5=0.7999

Epoch 032 | train_loss=0.1057 | ce=0.0416 | ent=0.0513 | center=0.6146 | val_loss=0.0244 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9413 | val_dqn_proxy_expanded5=0.8546

Epoch 033 | train_loss=0.0910 | ce=0.0285 | ent=0.0473 | center=0.6009 | val_loss=0.0133 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9491 | val_dqn_proxy_expanded5=0.8604
Early stopping at epoch 33 (best epoch: 18)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
11,confman_paperish_mild_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-46_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,confman_baseline_knownonly_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-26_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,confman_paperish_mid_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-52_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
9,confman_paperish_mild_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-39_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
5,confman_baseline_openconf_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-30_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,confman_baseline_openconf_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-28_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,confman_baseline_openconf_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-35_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
14,confman_paperish_mid_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-57_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
8,confman_paperish_mild_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-37_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,confman_baseline_openconf_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-33_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
10,confman_paperish_mild_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-43_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,confman_baseline_knownonly_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-19_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,confman_paperish_mid_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-48_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,confman_baseline_knownonly_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-21_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,confman_baseline_knownonly_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-24_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"

================================================================================
Running experiment 16/32
{
  "run_name": "confman_paperish_mid_unkPA8_c16384_seed0",
  "task": "pa",
  "split_mode": "open_pa",
  "unknown_pas": [
    "PA8"
  ],
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "lr": 0.0001,
  "weight_decay": 0.0001,
  "lambda_center": 0.1,
  "label_smoothing": 0.0,
  "entropy_loss_weight": 0.05,
  "mlp_dropout": 0.5,
  "class_weight_mode": null,
  "grad_clip_norm": 1.0,
  "scheduler_name": "plateau",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "epochs": 200,
  "early_stopping_patience": 15,
  "save_root": "results_pa_confmanifold_coarse"
}
================================================================================

Epoch 001 | train_loss=0.9161 | ce=0.7587 | ent=0.9357 | center=1.1057 | val_loss=0.2439 | val_acc=0.9630 | val_macro_f1=0.9629 | val_dqn_proxy_softmax3=0.7666 | val_dqn_proxy_expanded5=0.7524

Epoch 002 | train_loss=0.3396 | ce=0.1677 | ent=0.3121 | center=1.5626 | val_loss=0.1176 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9114 | val_dqn_proxy_expanded5=0.8908

Epoch 003 | train_loss=0.2474 | ce=0.0995 | ent=0.1624 | center=1.3980 | val_loss=0.1010 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9354 | val_dqn_proxy_expanded5=0.9390

Epoch 004 | train_loss=0.2136 | ce=0.0789 | ent=0.1365 | center=1.2794 | val_loss=0.1017 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9492 | val_dqn_proxy_expanded5=0.9430

Epoch 005 | train_loss=0.2024 | ce=0.0769 | ent=0.1189 | center=1.1956 | val_loss=0.0933 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9179 | val_dqn_proxy_expanded5=0.9183

Epoch 006 | train_loss=0.1874 | ce=0.0692 | ent=0.1152 | center=1.1247 | val_loss=0.0896 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9343 | val_dqn_proxy_expanded5=0.9303

Epoch 007 | train_loss=0.1789 | ce=0.0655 | ent=0.1011 | center=1.0837 | val_loss=0.0874 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9275 | val_dqn_proxy_expanded5=0.9188

Epoch 008 | train_loss=0.1744 | ce=0.0650 | ent=0.1010 | center=1.0436 | val_loss=0.0938 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9123 | val_dqn_proxy_expanded5=0.9061

Epoch 009 | train_loss=0.1645 | ce=0.0604 | ent=0.0878 | center=0.9975 | val_loss=0.0817 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9350 | val_dqn_proxy_expanded5=0.9292

Epoch 010 | train_loss=0.1591 | ce=0.0591 | ent=0.0800 | center=0.9606 | val_loss=0.0765 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8875 | val_dqn_proxy_expanded5=0.8714

Epoch 011 | train_loss=0.1597 | ce=0.0628 | ent=0.0822 | center=0.9281 | val_loss=0.0755 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9250 | val_dqn_proxy_expanded5=0.9128

Epoch 012 | train_loss=0.1426 | ce=0.0488 | ent=0.0740 | center=0.9008 | val_loss=0.0720 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9459 | val_dqn_proxy_expanded5=0.9354

Epoch 013 | train_loss=0.1318 | ce=0.0399 | ent=0.0769 | center=0.8806 | val_loss=0.0538 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9415 | val_dqn_proxy_expanded5=0.9210

Epoch 014 | train_loss=0.1215 | ce=0.0318 | ent=0.0651 | center=0.8644 | val_loss=0.0483 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9756 | val_dqn_proxy_expanded5=0.9577

Epoch 015 | train_loss=0.1097 | ce=0.0237 | ent=0.0568 | center=0.8309 | val_loss=0.0490 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9781 | val_dqn_proxy_expanded5=0.9477

Epoch 016 | train_loss=0.1067 | ce=0.0237 | ent=0.0511 | center=0.8051 | val_loss=0.0484 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9738 | val_dqn_proxy_expanded5=0.9463

Epoch 017 | train_loss=0.1058 | ce=0.0245 | ent=0.0509 | center=0.7872 | val_loss=0.0484 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9772 | val_dqn_proxy_expanded5=0.9543

Epoch 018 | train_loss=0.0950 | ce=0.0173 | ent=0.0455 | center=0.7535 | val_loss=0.0497 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9764 | val_dqn_proxy_expanded5=0.9396

Epoch 019 | train_loss=0.1019 | ce=0.0257 | ent=0.0432 | center=0.7401 | val_loss=0.0444 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9630 | val_dqn_proxy_expanded5=0.9227

Epoch 020 | train_loss=0.0948 | ce=0.0216 | ent=0.0404 | center=0.7120 | val_loss=0.0366 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9320 | val_dqn_proxy_expanded5=0.8904

Epoch 021 | train_loss=0.0951 | ce=0.0236 | ent=0.0413 | center=0.6944 | val_loss=0.0435 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9397 | val_dqn_proxy_expanded5=0.8968

Epoch 022 | train_loss=0.0908 | ce=0.0205 | ent=0.0381 | center=0.6837 | val_loss=0.0483 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9816 | val_dqn_proxy_expanded5=0.9401

Epoch 023 | train_loss=0.0862 | ce=0.0186 | ent=0.0342 | center=0.6587 | val_loss=0.0427 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9748 | val_dqn_proxy_expanded5=0.9342

Epoch 024 | train_loss=0.0841 | ce=0.0183 | ent=0.0342 | center=0.6407 | val_loss=0.0470 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9713 | val_dqn_proxy_expanded5=0.9332

Epoch 025 | train_loss=0.0815 | ce=0.0176 | ent=0.0309 | center=0.6236 | val_loss=0.0385 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9586 | val_dqn_proxy_expanded5=0.9063

Epoch 026 | train_loss=0.0814 | ce=0.0192 | ent=0.0328 | center=0.6056 | val_loss=0.0427 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9385 | val_dqn_proxy_expanded5=0.8911

Epoch 027 | train_loss=0.0819 | ce=0.0213 | ent=0.0296 | center=0.5919 | val_loss=0.0453 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9641 | val_dqn_proxy_expanded5=0.9303

Epoch 028 | train_loss=0.0760 | ce=0.0162 | ent=0.0301 | center=0.5835 | val_loss=0.0453 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9457 | val_dqn_proxy_expanded5=0.8892

Epoch 029 | train_loss=0.0772 | ce=0.0182 | ent=0.0294 | center=0.5751 | val_loss=0.0456 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9620 | val_dqn_proxy_expanded5=0.9067

Epoch 030 | train_loss=0.0796 | ce=0.0214 | ent=0.0287 | center=0.5677 | val_loss=0.0468 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9586 | val_dqn_proxy_expanded5=0.8979

Epoch 031 | train_loss=0.0748 | ce=0.0176 | ent=0.0268 | center=0.5583 | val_loss=0.0460 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9510 | val_dqn_proxy_expanded5=0.8905

Epoch 032 | train_loss=0.0743 | ce=0.0177 | ent=0.0255 | center=0.5528 | val_loss=0.0433 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9657 | val_dqn_proxy_expanded5=0.9047

Epoch 033 | train_loss=0.0731 | ce=0.0173 | ent=0.0265 | center=0.5456 | val_loss=0.0449 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9673 | val_dqn_proxy_expanded5=0.9169

Epoch 034 | train_loss=0.0764 | ce=0.0206 | ent=0.0244 | center=0.5461 | val_loss=0.0421 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9655 | val_dqn_proxy_expanded5=0.9107

Epoch 035 | train_loss=0.0710 | ce=0.0160 | ent=0.0275 | center=0.5367 | val_loss=0.0467 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9500 | val_dqn_proxy_expanded5=0.8846

Epoch 036 | train_loss=0.0747 | ce=0.0198 | ent=0.0243 | center=0.5369 | val_loss=0.0464 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9546 | val_dqn_proxy_expanded5=0.8985

Epoch 037 | train_loss=0.0728 | ce=0.0182 | ent=0.0222 | center=0.5348 | val_loss=0.0464 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9721 | val_dqn_proxy_expanded5=0.9165
Early stopping at epoch 37 (best epoch: 22)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
11,confman_paperish_mild_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-46_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,confman_baseline_knownonly_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-26_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,confman_paperish_mid_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-52_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
9,confman_paperish_mild_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-39_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
5,confman_baseline_openconf_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-30_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,confman_baseline_openconf_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-28_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
15,confman_paperish_mid_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-59_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,confman_baseline_openconf_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-35_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
14,confman_paperish_mid_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-57_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
8,confman_paperish_mild_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-37_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,confman_baseline_openconf_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-33_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
10,confman_paperish_mild_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-43_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,confman_baseline_knownonly_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-19_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,confman_paperish_mid_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-48_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,confman_baseline_knownonly_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-21_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,confman_baseline_knownonly_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-24_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"

================================================================================
Running experiment 17/32
{
  "run_name": "confman_paperish_strong_unkPA2_c16384_seed0",
  "task": "pa",
  "split_mode": "open_pa",
  "unknown_pas": [
    "PA2"
  ],
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "lr": 0.0001,
  "weight_decay": 0.0001,
  "lambda_center": 0.1,
  "label_smoothing": 0.0,
  "entropy_loss_weight": 0.1,
  "mlp_dropout": 0.5,
  "class_weight_mode": null,
  "grad_clip_norm": 1.0,
  "scheduler_name": "plateau",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "epochs": 200,
  "early_stopping_patience": 15,
  "save_root": "results_pa_confmanifold_coarse"
}
================================================================================

Epoch 001 | train_loss=1.0507 | ce=0.8396 | ent=0.9905 | center=1.1205 | val_loss=0.3483 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7553 | val_dqn_proxy_expanded5=0.7386

Epoch 002 | train_loss=0.4358 | ce=0.2386 | ent=0.3759 | center=1.5956 | val_loss=0.1184 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8745 | val_dqn_proxy_expanded5=0.8869

Epoch 003 | train_loss=0.2930 | ce=0.1247 | ent=0.1898 | center=1.4937 | val_loss=0.1067 | val_acc=0.9778 | val_macro_f1=0.9779 | val_dqn_proxy_softmax3=0.6497 | val_dqn_proxy_expanded5=0.7455

Epoch 004 | train_loss=0.2960 | ce=0.1410 | ent=0.1658 | center=1.3847 | val_loss=0.0941 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6180 | val_dqn_proxy_expanded5=0.6986

Epoch 005 | train_loss=0.2437 | ce=0.1001 | ent=0.1436 | center=1.2925 | val_loss=0.0911 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6382 | val_dqn_proxy_expanded5=0.7497

Epoch 006 | train_loss=0.2333 | ce=0.0960 | ent=0.1278 | center=1.2455 | val_loss=0.0896 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.5138 | val_dqn_proxy_expanded5=0.6888

Epoch 007 | train_loss=0.2403 | ce=0.1076 | ent=0.1168 | center=1.2104 | val_loss=0.0883 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.5833 | val_dqn_proxy_expanded5=0.6912

Epoch 008 | train_loss=0.2310 | ce=0.1056 | ent=0.1079 | center=1.1461 | val_loss=0.0741 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6380 | val_dqn_proxy_expanded5=0.7414

Epoch 009 | train_loss=0.2082 | ce=0.0878 | ent=0.1050 | center=1.0989 | val_loss=0.0760 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.5756 | val_dqn_proxy_expanded5=0.6786

Epoch 010 | train_loss=0.2024 | ce=0.0874 | ent=0.0920 | center=1.0575 | val_loss=0.0680 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8468 | val_dqn_proxy_expanded5=0.8498

Epoch 011 | train_loss=0.1928 | ce=0.0810 | ent=0.0878 | center=1.0306 | val_loss=0.0728 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.5455 | val_dqn_proxy_expanded5=0.6672

Epoch 012 | train_loss=0.1975 | ce=0.0877 | ent=0.0813 | center=1.0166 | val_loss=0.0677 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9012 | val_dqn_proxy_expanded5=0.9044

Epoch 013 | train_loss=0.1868 | ce=0.0811 | ent=0.0821 | center=0.9752 | val_loss=0.0661 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6304 | val_dqn_proxy_expanded5=0.6747

Epoch 014 | train_loss=0.1821 | ce=0.0804 | ent=0.0732 | center=0.9439 | val_loss=0.0668 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7063 | val_dqn_proxy_expanded5=0.7196

Epoch 015 | train_loss=0.1769 | ce=0.0773 | ent=0.0746 | center=0.9210 | val_loss=0.0667 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6143 | val_dqn_proxy_expanded5=0.6661

Epoch 016 | train_loss=0.1761 | ce=0.0797 | ent=0.0591 | center=0.9046 | val_loss=0.0682 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.5916 | val_dqn_proxy_expanded5=0.6744

Epoch 017 | train_loss=0.1699 | ce=0.0750 | ent=0.0723 | center=0.8764 | val_loss=0.0703 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6569 | val_dqn_proxy_expanded5=0.7007

Epoch 018 | train_loss=0.1647 | ce=0.0726 | ent=0.0657 | center=0.8545 | val_loss=0.0631 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.5662 | val_dqn_proxy_expanded5=0.6601

Epoch 019 | train_loss=0.1454 | ce=0.0561 | ent=0.0626 | center=0.8307 | val_loss=0.0585 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.5860 | val_dqn_proxy_expanded5=0.6729

Epoch 020 | train_loss=0.1492 | ce=0.0619 | ent=0.0611 | center=0.8123 | val_loss=0.0539 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.7434 | val_dqn_proxy_expanded5=0.7467

Epoch 021 | train_loss=0.1395 | ce=0.0526 | ent=0.0649 | center=0.8042 | val_loss=0.0531 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6215 | val_dqn_proxy_expanded5=0.6849

Epoch 022 | train_loss=0.1332 | ce=0.0471 | ent=0.0614 | center=0.7992 | val_loss=0.0447 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.5743 | val_dqn_proxy_expanded5=0.6726

Epoch 023 | train_loss=0.1229 | ce=0.0404 | ent=0.0496 | center=0.7759 | val_loss=0.0412 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.5166 | val_dqn_proxy_expanded5=0.6596

Epoch 024 | train_loss=0.1190 | ce=0.0395 | ent=0.0432 | center=0.7516 | val_loss=0.0366 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6069 | val_dqn_proxy_expanded5=0.6631

Epoch 025 | train_loss=0.1096 | ce=0.0327 | ent=0.0426 | center=0.7261 | val_loss=0.0418 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6954 | val_dqn_proxy_expanded5=0.7033

Epoch 026 | train_loss=0.1090 | ce=0.0338 | ent=0.0373 | center=0.7154 | val_loss=0.0366 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.5610 | val_dqn_proxy_expanded5=0.6649

Epoch 027 | train_loss=0.1110 | ce=0.0373 | ent=0.0417 | center=0.6954 | val_loss=0.0439 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7625 | val_dqn_proxy_expanded5=0.7784
Early stopping at epoch 27 (best epoch: 12)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
11,confman_paperish_mild_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-46_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,confman_baseline_knownonly_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-26_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,confman_paperish_mid_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-52_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
9,confman_paperish_mild_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-39_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
5,confman_baseline_openconf_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-30_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,confman_baseline_openconf_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-28_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
15,confman_paperish_mid_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-59_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,confman_baseline_openconf_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-35_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
14,confman_paperish_mid_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-57_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
16,confman_paperish_strong_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/17-02_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
8,confman_paperish_mild_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-37_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,confman_baseline_openconf_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-33_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
10,confman_paperish_mild_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-43_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,confman_baseline_knownonly_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-19_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,confman_paperish_mid_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-48_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,confman_baseline_knownonly_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-21_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,confman_baseline_knownonly_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-24_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"

================================================================================
Running experiment 18/32
{
  "run_name": "confman_paperish_strong_unkPA3_c16384_seed0",
  "task": "pa",
  "split_mode": "open_pa",
  "unknown_pas": [
    "PA3"
  ],
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "lr": 0.0001,
  "weight_decay": 0.0001,
  "lambda_center": 0.1,
  "label_smoothing": 0.0,
  "entropy_loss_weight": 0.1,
  "mlp_dropout": 0.5,
  "class_weight_mode": null,
  "grad_clip_norm": 1.0,
  "scheduler_name": "plateau",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "epochs": 200,
  "early_stopping_patience": 15,
  "save_root": "results_pa_confmanifold_coarse"
}
================================================================================

Epoch 001 | train_loss=1.0783 | ce=0.8682 | ent=0.9960 | center=1.1056 | val_loss=0.4384 | val_acc=0.9000 | val_macro_f1=0.8984 | val_dqn_proxy_softmax3=0.6845 | val_dqn_proxy_expanded5=0.7196

Epoch 002 | train_loss=0.5263 | ce=0.3255 | ent=0.4845 | center=1.5239 | val_loss=0.1454 | val_acc=0.9519 | val_macro_f1=0.9521 | val_dqn_proxy_softmax3=0.7869 | val_dqn_proxy_expanded5=0.7614

Epoch 003 | train_loss=0.4162 | ce=0.2280 | ent=0.3087 | center=1.5727 | val_loss=0.1435 | val_acc=0.9407 | val_macro_f1=0.9411 | val_dqn_proxy_softmax3=0.8635 | val_dqn_proxy_expanded5=0.8127

Epoch 004 | train_loss=0.3611 | ce=0.1881 | ent=0.2456 | center=1.4847 | val_loss=0.1263 | val_acc=0.9519 | val_macro_f1=0.9521 | val_dqn_proxy_softmax3=0.7571 | val_dqn_proxy_expanded5=0.7962

Epoch 005 | train_loss=0.3137 | ce=0.1519 | ent=0.2175 | center=1.4005 | val_loss=0.1051 | val_acc=0.9593 | val_macro_f1=0.9594 | val_dqn_proxy_softmax3=0.8966 | val_dqn_proxy_expanded5=0.8649

Epoch 006 | train_loss=0.3342 | ce=0.1794 | ent=0.1961 | center=1.3516 | val_loss=0.1261 | val_acc=0.9519 | val_macro_f1=0.9519 | val_dqn_proxy_softmax3=0.8871 | val_dqn_proxy_expanded5=0.8681

Epoch 007 | train_loss=0.2808 | ce=0.1352 | ent=0.1804 | center=1.2757 | val_loss=0.0810 | val_acc=0.9630 | val_macro_f1=0.9630 | val_dqn_proxy_softmax3=0.9042 | val_dqn_proxy_expanded5=0.8780

Epoch 008 | train_loss=0.2969 | ce=0.1569 | ent=0.1707 | center=1.2291 | val_loss=0.0965 | val_acc=0.9667 | val_macro_f1=0.9667 | val_dqn_proxy_softmax3=0.9234 | val_dqn_proxy_expanded5=0.9055

Epoch 009 | train_loss=0.2647 | ce=0.1291 | ent=0.1599 | center=1.1959 | val_loss=0.0922 | val_acc=0.9593 | val_macro_f1=0.9595 | val_dqn_proxy_softmax3=0.9521 | val_dqn_proxy_expanded5=0.9226

Epoch 010 | train_loss=0.2352 | ce=0.1040 | ent=0.1409 | center=1.1711 | val_loss=0.0701 | val_acc=0.9741 | val_macro_f1=0.9741 | val_dqn_proxy_softmax3=0.9512 | val_dqn_proxy_expanded5=0.9383

Epoch 011 | train_loss=0.2259 | ce=0.0985 | ent=0.1403 | center=1.1334 | val_loss=0.1130 | val_acc=0.9630 | val_macro_f1=0.9628 | val_dqn_proxy_softmax3=0.9515 | val_dqn_proxy_expanded5=0.9388

Epoch 012 | train_loss=0.2239 | ce=0.1001 | ent=0.1332 | center=1.1043 | val_loss=0.0881 | val_acc=0.9593 | val_macro_f1=0.9592 | val_dqn_proxy_softmax3=0.9650 | val_dqn_proxy_expanded5=0.9350

Epoch 013 | train_loss=0.2042 | ce=0.0834 | ent=0.1161 | center=1.0922 | val_loss=0.0577 | val_acc=0.9741 | val_macro_f1=0.9741 | val_dqn_proxy_softmax3=0.9676 | val_dqn_proxy_expanded5=0.9470

Epoch 014 | train_loss=0.2228 | ce=0.1080 | ent=0.1194 | center=1.0280 | val_loss=0.0654 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9612 | val_dqn_proxy_expanded5=0.9325

Epoch 015 | train_loss=0.1975 | ce=0.0851 | ent=0.1082 | center=1.0159 | val_loss=0.0413 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9650 | val_dqn_proxy_expanded5=0.9307

Epoch 016 | train_loss=0.1736 | ce=0.0634 | ent=0.0987 | center=1.0031 | val_loss=0.0588 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9815 | val_dqn_proxy_expanded5=0.9540

Epoch 017 | train_loss=0.1916 | ce=0.0849 | ent=0.1032 | center=0.9639 | val_loss=0.0731 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.9379 | val_dqn_proxy_expanded5=0.9121

Epoch 018 | train_loss=0.1734 | ce=0.0709 | ent=0.0871 | center=0.9379 | val_loss=0.0439 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9546 | val_dqn_proxy_expanded5=0.9420

Epoch 019 | train_loss=0.1974 | ce=0.0952 | ent=0.1036 | center=0.9184 | val_loss=0.0745 | val_acc=0.9704 | val_macro_f1=0.9703 | val_dqn_proxy_softmax3=0.9829 | val_dqn_proxy_expanded5=0.9459

Epoch 020 | train_loss=0.1892 | ce=0.0898 | ent=0.0898 | center=0.9045 | val_loss=0.0601 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9694 | val_dqn_proxy_expanded5=0.9442

Epoch 021 | train_loss=0.1668 | ce=0.0699 | ent=0.0962 | center=0.8728 | val_loss=0.0336 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9669 | val_dqn_proxy_expanded5=0.9494

Epoch 022 | train_loss=0.1588 | ce=0.0648 | ent=0.0838 | center=0.8566 | val_loss=0.0415 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9415 | val_dqn_proxy_expanded5=0.9400

Epoch 023 | train_loss=0.1664 | ce=0.0741 | ent=0.0798 | center=0.8435 | val_loss=0.0797 | val_acc=0.9630 | val_macro_f1=0.9628 | val_dqn_proxy_softmax3=0.9777 | val_dqn_proxy_expanded5=0.9362

Epoch 024 | train_loss=0.1509 | ce=0.0616 | ent=0.0716 | center=0.8212 | val_loss=0.0263 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9702 | val_dqn_proxy_expanded5=0.9283

Epoch 025 | train_loss=0.1475 | ce=0.0595 | ent=0.0781 | center=0.8010 | val_loss=0.0297 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9853 | val_dqn_proxy_expanded5=0.9436

Epoch 026 | train_loss=0.1399 | ce=0.0551 | ent=0.0660 | center=0.7817 | val_loss=0.0671 | val_acc=0.9704 | val_macro_f1=0.9703 | val_dqn_proxy_softmax3=0.9766 | val_dqn_proxy_expanded5=0.9339

Epoch 027 | train_loss=0.1462 | ce=0.0626 | ent=0.0685 | center=0.7672 | val_loss=0.0457 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9866 | val_dqn_proxy_expanded5=0.9386

Epoch 028 | train_loss=0.1281 | ce=0.0474 | ent=0.0625 | center=0.7440 | val_loss=0.0402 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9857 | val_dqn_proxy_expanded5=0.9484

Epoch 029 | train_loss=0.1335 | ce=0.0545 | ent=0.0636 | center=0.7264 | val_loss=0.0323 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9650 | val_dqn_proxy_expanded5=0.9190

Epoch 030 | train_loss=0.1349 | ce=0.0579 | ent=0.0545 | center=0.7159 | val_loss=0.0258 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9755 | val_dqn_proxy_expanded5=0.9438

Epoch 031 | train_loss=0.1376 | ce=0.0626 | ent=0.0531 | center=0.6977 | val_loss=0.0699 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.9616 | val_dqn_proxy_expanded5=0.9181

Epoch 032 | train_loss=0.1161 | ce=0.0431 | ent=0.0493 | center=0.6806 | val_loss=0.0458 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9815 | val_dqn_proxy_expanded5=0.9448

Epoch 033 | train_loss=0.1125 | ce=0.0415 | ent=0.0529 | center=0.6575 | val_loss=0.0112 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9815 | val_dqn_proxy_expanded5=0.9559

Epoch 034 | train_loss=0.1131 | ce=0.0427 | ent=0.0482 | center=0.6564 | val_loss=0.0735 | val_acc=0.9741 | val_macro_f1=0.9741 | val_dqn_proxy_softmax3=0.9594 | val_dqn_proxy_expanded5=0.9203

Epoch 035 | train_loss=0.1062 | ce=0.0377 | ent=0.0510 | center=0.6336 | val_loss=0.0577 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.9776 | val_dqn_proxy_expanded5=0.9479

Epoch 036 | train_loss=0.1141 | ce=0.0478 | ent=0.0424 | center=0.6199 | val_loss=0.0514 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9735 | val_dqn_proxy_expanded5=0.9522

Epoch 037 | train_loss=0.1185 | ce=0.0540 | ent=0.0437 | center=0.6022 | val_loss=0.0528 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9537 | val_dqn_proxy_expanded5=0.9077

Epoch 038 | train_loss=0.1089 | ce=0.0459 | ent=0.0402 | center=0.5897 | val_loss=0.0286 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9747 | val_dqn_proxy_expanded5=0.9334

Epoch 039 | train_loss=0.1018 | ce=0.0402 | ent=0.0376 | center=0.5781 | val_loss=0.0651 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9779 | val_dqn_proxy_expanded5=0.9280

Epoch 040 | train_loss=0.0883 | ce=0.0276 | ent=0.0367 | center=0.5701 | val_loss=0.0099 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9779 | val_dqn_proxy_expanded5=0.9272

Epoch 041 | train_loss=0.0900 | ce=0.0304 | ent=0.0371 | center=0.5588 | val_loss=0.0075 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9732 | val_dqn_proxy_expanded5=0.9247

Epoch 042 | train_loss=0.0934 | ce=0.0346 | ent=0.0370 | center=0.5502 | val_loss=0.0228 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9770 | val_dqn_proxy_expanded5=0.9210
Early stopping at epoch 42 (best epoch: 27)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
11,confman_paperish_mild_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-46_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,confman_baseline_knownonly_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-26_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,confman_paperish_mid_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-52_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
9,confman_paperish_mild_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-39_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
5,confman_baseline_openconf_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-30_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,confman_baseline_openconf_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-28_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
15,confman_paperish_mid_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-59_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,confman_baseline_openconf_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-35_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
14,confman_paperish_mid_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-57_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
17,confman_paperish_strong_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/17-04_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
16,confman_paperish_strong_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/17-02_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
8,confman_paperish_mild_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-37_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,confman_baseline_openconf_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-33_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
10,confman_paperish_mild_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-43_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,confman_baseline_knownonly_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-19_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,confman_paperish_mid_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-48_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,confman_baseline_knownonly_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-21_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,confman_baseline_knownonly_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-24_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"

================================================================================
Running experiment 19/32
{
  "run_name": "confman_paperish_strong_unkPA4_c16384_seed0",
  "task": "pa",
  "split_mode": "open_pa",
  "unknown_pas": [
    "PA4"
  ],
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "lr": 0.0001,
  "weight_decay": 0.0001,
  "lambda_center": 0.1,
  "label_smoothing": 0.0,
  "entropy_loss_weight": 0.1,
  "mlp_dropout": 0.5,
  "class_weight_mode": null,
  "grad_clip_norm": 1.0,
  "scheduler_name": "plateau",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "epochs": 200,
  "early_stopping_patience": 15,
  "save_root": "results_pa_confmanifold_coarse"
}
================================================================================

Epoch 001 | train_loss=1.0487 | ce=0.8446 | ent=0.9814 | center=1.0595 | val_loss=0.4081 | val_acc=0.8556 | val_macro_f1=0.8462 | val_dqn_proxy_softmax3=0.6983 | val_dqn_proxy_expanded5=0.7012

Epoch 002 | train_loss=0.5458 | ce=0.3293 | ent=0.4808 | center=1.6846 | val_loss=0.2696 | val_acc=0.9037 | val_macro_f1=0.9022 | val_dqn_proxy_softmax3=0.7087 | val_dqn_proxy_expanded5=0.7355

Epoch 003 | train_loss=0.4792 | ce=0.2820 | ent=0.3567 | center=1.6150 | val_loss=0.2395 | val_acc=0.9074 | val_macro_f1=0.9071 | val_dqn_proxy_softmax3=0.7319 | val_dqn_proxy_expanded5=0.7606

Epoch 004 | train_loss=0.4346 | ce=0.2563 | ent=0.3007 | center=1.4820 | val_loss=0.1570 | val_acc=0.9556 | val_macro_f1=0.9557 | val_dqn_proxy_softmax3=0.7503 | val_dqn_proxy_expanded5=0.7877

Epoch 005 | train_loss=0.3649 | ce=0.2006 | ent=0.2519 | center=1.3917 | val_loss=0.1481 | val_acc=0.9556 | val_macro_f1=0.9558 | val_dqn_proxy_softmax3=0.7289 | val_dqn_proxy_expanded5=0.7621

Epoch 006 | train_loss=0.3229 | ce=0.1685 | ent=0.2138 | center=1.3303 | val_loss=0.1505 | val_acc=0.9519 | val_macro_f1=0.9516 | val_dqn_proxy_softmax3=0.7347 | val_dqn_proxy_expanded5=0.7386

Epoch 007 | train_loss=0.3477 | ce=0.2018 | ent=0.2210 | center=1.2377 | val_loss=0.1973 | val_acc=0.9370 | val_macro_f1=0.9367 | val_dqn_proxy_softmax3=0.7568 | val_dqn_proxy_expanded5=0.7717

Epoch 008 | train_loss=0.2980 | ce=0.1566 | ent=0.1893 | center=1.2250 | val_loss=0.1447 | val_acc=0.9519 | val_macro_f1=0.9516 | val_dqn_proxy_softmax3=0.7453 | val_dqn_proxy_expanded5=0.7213

Epoch 009 | train_loss=0.2581 | ce=0.1230 | ent=0.1632 | center=1.1875 | val_loss=0.0976 | val_acc=0.9778 | val_macro_f1=0.9779 | val_dqn_proxy_softmax3=0.7491 | val_dqn_proxy_expanded5=0.7240

Epoch 010 | train_loss=0.2452 | ce=0.1167 | ent=0.1488 | center=1.1362 | val_loss=0.1203 | val_acc=0.9704 | val_macro_f1=0.9706 | val_dqn_proxy_softmax3=0.7588 | val_dqn_proxy_expanded5=0.7282

Epoch 011 | train_loss=0.2449 | ce=0.1199 | ent=0.1361 | center=1.1143 | val_loss=0.1385 | val_acc=0.9519 | val_macro_f1=0.9521 | val_dqn_proxy_softmax3=0.7407 | val_dqn_proxy_expanded5=0.7147

Epoch 012 | train_loss=0.2229 | ce=0.1030 | ent=0.1324 | center=1.0668 | val_loss=0.0762 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.8029 | val_dqn_proxy_expanded5=0.7603

Epoch 013 | train_loss=0.2080 | ce=0.0918 | ent=0.1184 | center=1.0435 | val_loss=0.0718 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8515 | val_dqn_proxy_expanded5=0.7911

Epoch 014 | train_loss=0.1989 | ce=0.0869 | ent=0.1082 | center=1.0112 | val_loss=0.1008 | val_acc=0.9630 | val_macro_f1=0.9632 | val_dqn_proxy_softmax3=0.8972 | val_dqn_proxy_expanded5=0.8186

Epoch 015 | train_loss=0.1875 | ce=0.0790 | ent=0.1080 | center=0.9768 | val_loss=0.1894 | val_acc=0.9481 | val_macro_f1=0.9480 | val_dqn_proxy_softmax3=0.9153 | val_dqn_proxy_expanded5=0.8532

Epoch 016 | train_loss=0.1876 | ce=0.0821 | ent=0.0993 | center=0.9559 | val_loss=0.0445 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9384 | val_dqn_proxy_expanded5=0.8735

Epoch 017 | train_loss=0.1756 | ce=0.0728 | ent=0.1035 | center=0.9253 | val_loss=0.0497 | val_acc=0.9704 | val_macro_f1=0.9706 | val_dqn_proxy_softmax3=0.9399 | val_dqn_proxy_expanded5=0.9074

Epoch 018 | train_loss=0.1672 | ce=0.0682 | ent=0.0854 | center=0.9049 | val_loss=0.0356 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9433 | val_dqn_proxy_expanded5=0.9083

Epoch 019 | train_loss=0.1505 | ce=0.0546 | ent=0.0854 | center=0.8729 | val_loss=0.0415 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.9446 | val_dqn_proxy_expanded5=0.8697

Epoch 020 | train_loss=0.1464 | ce=0.0533 | ent=0.0766 | center=0.8549 | val_loss=0.0217 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9594 | val_dqn_proxy_expanded5=0.8899

Epoch 021 | train_loss=0.1430 | ce=0.0530 | ent=0.0729 | center=0.8270 | val_loss=0.0412 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9495 | val_dqn_proxy_expanded5=0.8603

Epoch 022 | train_loss=0.1338 | ce=0.0458 | ent=0.0718 | center=0.8075 | val_loss=0.0197 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9520 | val_dqn_proxy_expanded5=0.8604

Epoch 023 | train_loss=0.1377 | ce=0.0518 | ent=0.0724 | center=0.7861 | val_loss=0.0841 | val_acc=0.9741 | val_macro_f1=0.9740 | val_dqn_proxy_softmax3=0.8694 | val_dqn_proxy_expanded5=0.8054

Epoch 024 | train_loss=0.1312 | ce=0.0480 | ent=0.0596 | center=0.7721 | val_loss=0.0187 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7807 | val_dqn_proxy_expanded5=0.7509

Epoch 025 | train_loss=0.1299 | ce=0.0492 | ent=0.0591 | center=0.7471 | val_loss=0.0411 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8325 | val_dqn_proxy_expanded5=0.7800

Epoch 026 | train_loss=0.1410 | ce=0.0621 | ent=0.0675 | center=0.7211 | val_loss=0.0218 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.7722 | val_dqn_proxy_expanded5=0.7439

Epoch 027 | train_loss=0.1215 | ce=0.0447 | ent=0.0559 | center=0.7116 | val_loss=0.0113 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.7744 | val_dqn_proxy_expanded5=0.7463

Epoch 028 | train_loss=0.1140 | ce=0.0384 | ent=0.0554 | center=0.6997 | val_loss=0.0080 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.8538 | val_dqn_proxy_expanded5=0.8016

Epoch 029 | train_loss=0.1130 | ce=0.0401 | ent=0.0511 | center=0.6780 | val_loss=0.0105 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9214 | val_dqn_proxy_expanded5=0.8453

Epoch 030 | train_loss=0.1036 | ce=0.0328 | ent=0.0443 | center=0.6636 | val_loss=0.0162 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.8473 | val_dqn_proxy_expanded5=0.7981

Epoch 031 | train_loss=0.1093 | ce=0.0409 | ent=0.0459 | center=0.6380 | val_loss=0.0340 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8090 | val_dqn_proxy_expanded5=0.7690

Epoch 032 | train_loss=0.1102 | ce=0.0423 | ent=0.0507 | center=0.6281 | val_loss=0.0090 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.7783 | val_dqn_proxy_expanded5=0.7379

Epoch 033 | train_loss=0.1031 | ce=0.0363 | ent=0.0452 | center=0.6225 | val_loss=0.0171 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7848 | val_dqn_proxy_expanded5=0.7596

Epoch 034 | train_loss=0.0931 | ce=0.0289 | ent=0.0424 | center=0.5991 | val_loss=0.0068 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.7729 | val_dqn_proxy_expanded5=0.7565

Epoch 035 | train_loss=0.1108 | ce=0.0481 | ent=0.0402 | center=0.5871 | val_loss=0.0335 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8685 | val_dqn_proxy_expanded5=0.8105
Early stopping at epoch 35 (best epoch: 20)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
11,confman_paperish_mild_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-46_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,confman_baseline_knownonly_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-26_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,confman_paperish_mid_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-52_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
9,confman_paperish_mild_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-39_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
5,confman_baseline_openconf_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-30_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,confman_baseline_openconf_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-28_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
15,confman_paperish_mid_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-59_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,confman_baseline_openconf_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-35_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
14,confman_paperish_mid_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-57_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
17,confman_paperish_strong_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/17-04_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
16,confman_paperish_strong_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/17-02_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
18,confman_paperish_strong_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/17-08_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
8,confman_paperish_mild_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-37_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,confman_baseline_openconf_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-33_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
10,confman_paperish_mild_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-43_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,confman_baseline_knownonly_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-19_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,confman_paperish_mid_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-48_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,confman_baseline_knownonly_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-21_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,confman_baseline_knownonly_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-24_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"

================================================================================
Running experiment 20/32
{
  "run_name": "confman_paperish_strong_unkPA8_c16384_seed0",
  "task": "pa",
  "split_mode": "open_pa",
  "unknown_pas": [
    "PA8"
  ],
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "lr": 0.0001,
  "weight_decay": 0.0001,
  "lambda_center": 0.1,
  "label_smoothing": 0.0,
  "entropy_loss_weight": 0.1,
  "mlp_dropout": 0.5,
  "class_weight_mode": null,
  "grad_clip_norm": 1.0,
  "scheduler_name": "plateau",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "epochs": 200,
  "early_stopping_patience": 15,
  "save_root": "results_pa_confmanifold_coarse"
}
================================================================================

Epoch 001 | train_loss=0.9336 | ce=0.7321 | ent=0.9121 | center=1.1033 | val_loss=0.2225 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8080 | val_dqn_proxy_expanded5=0.8191

Epoch 002 | train_loss=0.3512 | ce=0.1661 | ent=0.2822 | center=1.5682 | val_loss=0.1158 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9150 | val_dqn_proxy_expanded5=0.8993

Epoch 003 | train_loss=0.2524 | ce=0.0991 | ent=0.1556 | center=1.3779 | val_loss=0.1047 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9572 | val_dqn_proxy_expanded5=0.9580

Epoch 004 | train_loss=0.2172 | ce=0.0784 | ent=0.1120 | center=1.2761 | val_loss=0.1071 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9406 | val_dqn_proxy_expanded5=0.9232

Epoch 005 | train_loss=0.2043 | ce=0.0752 | ent=0.1040 | center=1.1874 | val_loss=0.1048 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9539 | val_dqn_proxy_expanded5=0.9437

Epoch 006 | train_loss=0.1903 | ce=0.0676 | ent=0.0920 | center=1.1350 | val_loss=0.0949 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9482 | val_dqn_proxy_expanded5=0.9385

Epoch 007 | train_loss=0.1820 | ce=0.0660 | ent=0.0871 | center=1.0726 | val_loss=0.1019 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9404 | val_dqn_proxy_expanded5=0.9339

Epoch 008 | train_loss=0.1781 | ce=0.0663 | ent=0.0816 | center=1.0360 | val_loss=0.0931 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9500 | val_dqn_proxy_expanded5=0.9478

Epoch 009 | train_loss=0.1702 | ce=0.0628 | ent=0.0706 | center=1.0040 | val_loss=0.0871 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9366 | val_dqn_proxy_expanded5=0.9229

Epoch 010 | train_loss=0.1638 | ce=0.0603 | ent=0.0789 | center=0.9567 | val_loss=0.0894 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9466 | val_dqn_proxy_expanded5=0.9413

Epoch 011 | train_loss=0.1565 | ce=0.0573 | ent=0.0618 | center=0.9295 | val_loss=0.0697 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9033 | val_dqn_proxy_expanded5=0.8819

Epoch 012 | train_loss=0.1539 | ce=0.0562 | ent=0.0691 | center=0.9084 | val_loss=0.0694 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9215 | val_dqn_proxy_expanded5=0.9112

Epoch 013 | train_loss=0.1427 | ce=0.0465 | ent=0.0743 | center=0.8885 | val_loss=0.0611 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8759 | val_dqn_proxy_expanded5=0.8501

Epoch 014 | train_loss=0.1243 | ce=0.0323 | ent=0.0556 | center=0.8648 | val_loss=0.0432 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9479 | val_dqn_proxy_expanded5=0.9381

Epoch 015 | train_loss=0.1140 | ce=0.0261 | ent=0.0503 | center=0.8282 | val_loss=0.0519 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9754 | val_dqn_proxy_expanded5=0.9558

Epoch 016 | train_loss=0.1070 | ce=0.0219 | ent=0.0462 | center=0.8051 | val_loss=0.0488 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9829 | val_dqn_proxy_expanded5=0.9520

Epoch 017 | train_loss=0.1029 | ce=0.0208 | ent=0.0433 | center=0.7775 | val_loss=0.0469 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9160 | val_dqn_proxy_expanded5=0.8781

Epoch 018 | train_loss=0.1009 | ce=0.0222 | ent=0.0377 | center=0.7495 | val_loss=0.0451 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9414 | val_dqn_proxy_expanded5=0.8968

Epoch 019 | train_loss=0.0968 | ce=0.0204 | ent=0.0373 | center=0.7269 | val_loss=0.0487 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9645 | val_dqn_proxy_expanded5=0.9449

Epoch 020 | train_loss=0.0994 | ce=0.0249 | ent=0.0365 | center=0.7078 | val_loss=0.0466 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9702 | val_dqn_proxy_expanded5=0.9421

Epoch 021 | train_loss=0.0950 | ce=0.0228 | ent=0.0345 | center=0.6874 | val_loss=0.0472 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9721 | val_dqn_proxy_expanded5=0.9409

Epoch 022 | train_loss=0.0904 | ce=0.0197 | ent=0.0332 | center=0.6740 | val_loss=0.0484 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9851 | val_dqn_proxy_expanded5=0.9551

Epoch 023 | train_loss=0.0859 | ce=0.0165 | ent=0.0305 | center=0.6639 | val_loss=0.0463 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9697 | val_dqn_proxy_expanded5=0.9243

Epoch 024 | train_loss=0.0891 | ce=0.0210 | ent=0.0322 | center=0.6489 | val_loss=0.0484 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9773 | val_dqn_proxy_expanded5=0.9413

Epoch 025 | train_loss=0.0849 | ce=0.0178 | ent=0.0293 | center=0.6420 | val_loss=0.0439 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9570 | val_dqn_proxy_expanded5=0.9154

Epoch 026 | train_loss=0.0824 | ce=0.0156 | ent=0.0310 | center=0.6368 | val_loss=0.0460 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9281 | val_dqn_proxy_expanded5=0.8913

Epoch 027 | train_loss=0.0826 | ce=0.0172 | ent=0.0287 | center=0.6252 | val_loss=0.0457 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9625 | val_dqn_proxy_expanded5=0.9187

Epoch 028 | train_loss=0.0840 | ce=0.0191 | ent=0.0281 | center=0.6208 | val_loss=0.0416 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9545 | val_dqn_proxy_expanded5=0.9193

Epoch 029 | train_loss=0.0834 | ce=0.0192 | ent=0.0280 | center=0.6140 | val_loss=0.0459 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9493 | val_dqn_proxy_expanded5=0.9026

Epoch 030 | train_loss=0.0770 | ce=0.0136 | ent=0.0250 | center=0.6093 | val_loss=0.0429 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9555 | val_dqn_proxy_expanded5=0.9102

Epoch 031 | train_loss=0.0819 | ce=0.0190 | ent=0.0285 | center=0.6004 | val_loss=0.0446 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9680 | val_dqn_proxy_expanded5=0.9278

Epoch 032 | train_loss=0.0824 | ce=0.0197 | ent=0.0266 | center=0.6010 | val_loss=0.0419 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9534 | val_dqn_proxy_expanded5=0.9093

Epoch 033 | train_loss=0.0801 | ce=0.0179 | ent=0.0273 | center=0.5951 | val_loss=0.0429 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9654 | val_dqn_proxy_expanded5=0.9271

Epoch 034 | train_loss=0.0814 | ce=0.0198 | ent=0.0304 | center=0.5852 | val_loss=0.0443 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9706 | val_dqn_proxy_expanded5=0.9401

Epoch 035 | train_loss=0.0806 | ce=0.0190 | ent=0.0247 | center=0.5912 | val_loss=0.0445 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9115 | val_dqn_proxy_expanded5=0.8680

Epoch 036 | train_loss=0.0812 | ce=0.0206 | ent=0.0242 | center=0.5826 | val_loss=0.0415 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9665 | val_dqn_proxy_expanded5=0.9303

Epoch 037 | train_loss=0.0773 | ce=0.0167 | ent=0.0269 | center=0.5792 | val_loss=0.0441 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9514 | val_dqn_proxy_expanded5=0.9103
Early stopping at epoch 37 (best epoch: 22)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
11,confman_paperish_mild_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-46_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,confman_baseline_knownonly_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-26_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,confman_paperish_mid_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-52_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
19,confman_paperish_strong_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/17-10_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,confman_paperish_mild_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-39_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
5,confman_baseline_openconf_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-30_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,confman_baseline_openconf_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-28_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
15,confman_paperish_mid_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-59_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,confman_baseline_openconf_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-35_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
14,confman_paperish_mid_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-57_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
17,confman_paperish_strong_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/17-04_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
16,confman_paperish_strong_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/17-02_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
18,confman_paperish_strong_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/17-08_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
8,confman_paperish_mild_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-37_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,confman_baseline_openconf_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-33_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
10,confman_paperish_mild_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-43_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,confman_baseline_knownonly_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-19_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,confman_paperish_mid_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-48_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,confman_baseline_knownonly_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-21_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,confman_baseline_knownonly_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-24_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"

================================================================================
Running experiment 21/32
{
  "run_name": "confman_paperish_mid_nocenter_unkPA2_c16384_seed0",
  "task": "pa",
  "split_mode": "open_pa",
  "unknown_pas": [
    "PA2"
  ],
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "lr": 0.0001,
  "weight_decay": 0.0001,
  "lambda_center": 0.0,
  "label_smoothing": 0.0,
  "entropy_loss_weight": 0.05,
  "mlp_dropout": 0.5,
  "class_weight_mode": null,
  "grad_clip_norm": 1.0,
  "scheduler_name": "plateau",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "epochs": 200,
  "early_stopping_patience": 15,
  "save_root": "results_pa_confmanifold_coarse"
}
================================================================================

Epoch 001 | train_loss=0.8683 | ce=0.8195 | ent=0.9745 | center=0.0000 | val_loss=0.3183 | val_acc=0.9704 | val_macro_f1=0.9705 | val_dqn_proxy_softmax3=0.6987 | val_dqn_proxy_expanded5=0.7242

Epoch 002 | train_loss=0.2463 | ce=0.2307 | ent=0.3132 | center=0.0000 | val_loss=0.1399 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.5707 | val_dqn_proxy_expanded5=0.6735

Epoch 003 | train_loss=0.1590 | ce=0.1533 | ent=0.1137 | center=0.0000 | val_loss=0.1450 | val_acc=0.9778 | val_macro_f1=0.9779 | val_dqn_proxy_softmax3=0.6114 | val_dqn_proxy_expanded5=0.7077

Epoch 004 | train_loss=0.1374 | ce=0.1335 | ent=0.0794 | center=0.0000 | val_loss=0.1108 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.5630 | val_dqn_proxy_expanded5=0.6825

Epoch 005 | train_loss=0.1292 | ce=0.1258 | ent=0.0682 | center=0.0000 | val_loss=0.1129 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.5363 | val_dqn_proxy_expanded5=0.6545

Epoch 006 | train_loss=0.1299 | ce=0.1269 | ent=0.0595 | center=0.0000 | val_loss=0.0963 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.4895 | val_dqn_proxy_expanded5=0.6368

Epoch 007 | train_loss=0.1007 | ce=0.0971 | ent=0.0723 | center=0.0000 | val_loss=0.1070 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.5388 | val_dqn_proxy_expanded5=0.6438

Epoch 008 | train_loss=0.1028 | ce=0.1002 | ent=0.0520 | center=0.0000 | val_loss=0.0805 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.4743 | val_dqn_proxy_expanded5=0.6222

Epoch 009 | train_loss=0.0895 | ce=0.0872 | ent=0.0469 | center=0.0000 | val_loss=0.0692 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8843 | val_dqn_proxy_expanded5=0.8538

Epoch 010 | train_loss=0.1021 | ce=0.0998 | ent=0.0468 | center=0.0000 | val_loss=0.0800 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.4828 | val_dqn_proxy_expanded5=0.6101

Epoch 011 | train_loss=0.0832 | ce=0.0810 | ent=0.0429 | center=0.0000 | val_loss=0.0627 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8958 | val_dqn_proxy_expanded5=0.8638

Epoch 012 | train_loss=0.0832 | ce=0.0812 | ent=0.0402 | center=0.0000 | val_loss=0.0782 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.4536 | val_dqn_proxy_expanded5=0.6160

Epoch 013 | train_loss=0.0845 | ce=0.0825 | ent=0.0412 | center=0.0000 | val_loss=0.0668 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.4672 | val_dqn_proxy_expanded5=0.6082

Epoch 014 | train_loss=0.0812 | ce=0.0791 | ent=0.0428 | center=0.0000 | val_loss=0.0831 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.4636 | val_dqn_proxy_expanded5=0.6099

Epoch 015 | train_loss=0.0664 | ce=0.0648 | ent=0.0311 | center=0.0000 | val_loss=0.0725 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8918 | val_dqn_proxy_expanded5=0.8583

Epoch 016 | train_loss=0.0730 | ce=0.0711 | ent=0.0372 | center=0.0000 | val_loss=0.0731 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.5075 | val_dqn_proxy_expanded5=0.6394

Epoch 017 | train_loss=0.0814 | ce=0.0798 | ent=0.0312 | center=0.0000 | val_loss=0.0663 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.5022 | val_dqn_proxy_expanded5=0.6418

Epoch 018 | train_loss=0.0755 | ce=0.0738 | ent=0.0342 | center=0.0000 | val_loss=0.0783 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.5146 | val_dqn_proxy_expanded5=0.6488

Epoch 019 | train_loss=0.0638 | ce=0.0624 | ent=0.0264 | center=0.0000 | val_loss=0.0595 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.4890 | val_dqn_proxy_expanded5=0.6364

Epoch 020 | train_loss=0.0599 | ce=0.0584 | ent=0.0291 | center=0.0000 | val_loss=0.0539 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.4714 | val_dqn_proxy_expanded5=0.6413

Epoch 021 | train_loss=0.0624 | ce=0.0610 | ent=0.0289 | center=0.0000 | val_loss=0.0563 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.4715 | val_dqn_proxy_expanded5=0.6368

Epoch 022 | train_loss=0.0607 | ce=0.0592 | ent=0.0292 | center=0.0000 | val_loss=0.0634 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.5038 | val_dqn_proxy_expanded5=0.6262

Epoch 023 | train_loss=0.0480 | ce=0.0467 | ent=0.0266 | center=0.0000 | val_loss=0.0455 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.4828 | val_dqn_proxy_expanded5=0.6441

Epoch 024 | train_loss=0.0349 | ce=0.0336 | ent=0.0270 | center=0.0000 | val_loss=0.0440 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.4885 | val_dqn_proxy_expanded5=0.6466

Epoch 025 | train_loss=0.0443 | ce=0.0430 | ent=0.0258 | center=0.0000 | val_loss=0.0458 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.4962 | val_dqn_proxy_expanded5=0.6236

Epoch 026 | train_loss=0.0340 | ce=0.0330 | ent=0.0204 | center=0.0000 | val_loss=0.0459 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.4905 | val_dqn_proxy_expanded5=0.6384
Early stopping at epoch 26 (best epoch: 11)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
11,confman_paperish_mild_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-46_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,confman_baseline_knownonly_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-26_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,confman_paperish_mid_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-52_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
19,confman_paperish_strong_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/17-10_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,confman_paperish_mild_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-39_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
5,confman_baseline_openconf_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-30_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,confman_baseline_openconf_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-28_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
15,confman_paperish_mid_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-59_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,confman_baseline_openconf_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-35_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
14,confman_paperish_mid_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-57_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
17,confman_paperish_strong_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/17-04_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
16,confman_paperish_strong_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/17-02_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
18,confman_paperish_strong_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/17-08_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
8,confman_paperish_mild_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-37_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,confman_baseline_openconf_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-33_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
20,confman_paperish_mid_nocenter_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/17-13_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
10,confman_paperish_mild_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-43_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,confman_baseline_knownonly_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-19_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,confman_paperish_mid_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-48_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,confman_baseline_knownonly_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-21_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,confman_baseline_knownonly_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-24_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"

================================================================================
Running experiment 22/32
{
  "run_name": "confman_paperish_mid_nocenter_unkPA3_c16384_seed0",
  "task": "pa",
  "split_mode": "open_pa",
  "unknown_pas": [
    "PA3"
  ],
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "lr": 0.0001,
  "weight_decay": 0.0001,
  "lambda_center": 0.0,
  "label_smoothing": 0.0,
  "entropy_loss_weight": 0.05,
  "mlp_dropout": 0.5,
  "class_weight_mode": null,
  "grad_clip_norm": 1.0,
  "scheduler_name": "plateau",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "epochs": 200,
  "early_stopping_patience": 15,
  "save_root": "results_pa_confmanifold_coarse"
}
================================================================================

Epoch 001 | train_loss=0.9184 | ce=0.8685 | ent=0.9981 | center=0.0000 | val_loss=0.4502 | val_acc=0.8852 | val_macro_f1=0.8816 | val_dqn_proxy_softmax3=0.7085 | val_dqn_proxy_expanded5=0.7422

Epoch 002 | train_loss=0.3665 | ce=0.3432 | ent=0.4662 | center=0.0000 | val_loss=0.1398 | val_acc=0.9444 | val_macro_f1=0.9447 | val_dqn_proxy_softmax3=0.8442 | val_dqn_proxy_expanded5=0.7970

Epoch 003 | train_loss=0.2090 | ce=0.1976 | ent=0.2279 | center=0.0000 | val_loss=0.1164 | val_acc=0.9444 | val_macro_f1=0.9447 | val_dqn_proxy_softmax3=0.8589 | val_dqn_proxy_expanded5=0.8053

Epoch 004 | train_loss=0.1708 | ce=0.1624 | ent=0.1680 | center=0.0000 | val_loss=0.1474 | val_acc=0.9370 | val_macro_f1=0.9372 | val_dqn_proxy_softmax3=0.9401 | val_dqn_proxy_expanded5=0.8739

Epoch 005 | train_loss=0.1563 | ce=0.1498 | ent=0.1291 | center=0.0000 | val_loss=0.1091 | val_acc=0.9519 | val_macro_f1=0.9516 | val_dqn_proxy_softmax3=0.9323 | val_dqn_proxy_expanded5=0.8475

Epoch 006 | train_loss=0.1678 | ce=0.1617 | ent=0.1232 | center=0.0000 | val_loss=0.0941 | val_acc=0.9519 | val_macro_f1=0.9521 | val_dqn_proxy_softmax3=0.9254 | val_dqn_proxy_expanded5=0.8683

Epoch 007 | train_loss=0.1650 | ce=0.1601 | ent=0.0995 | center=0.0000 | val_loss=0.0757 | val_acc=0.9667 | val_macro_f1=0.9668 | val_dqn_proxy_softmax3=0.9168 | val_dqn_proxy_expanded5=0.8642

Epoch 008 | train_loss=0.1732 | ce=0.1683 | ent=0.0985 | center=0.0000 | val_loss=0.0558 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9572 | val_dqn_proxy_expanded5=0.8960

Epoch 009 | train_loss=0.1311 | ce=0.1269 | ent=0.0848 | center=0.0000 | val_loss=0.0532 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9521 | val_dqn_proxy_expanded5=0.8943

Epoch 010 | train_loss=0.1296 | ce=0.1257 | ent=0.0785 | center=0.0000 | val_loss=0.0553 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9541 | val_dqn_proxy_expanded5=0.8978

Epoch 011 | train_loss=0.1275 | ce=0.1243 | ent=0.0636 | center=0.0000 | val_loss=0.0537 | val_acc=0.9778 | val_macro_f1=0.9779 | val_dqn_proxy_softmax3=0.9521 | val_dqn_proxy_expanded5=0.8914

Epoch 012 | train_loss=0.1221 | ce=0.1186 | ent=0.0705 | center=0.0000 | val_loss=0.0544 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9559 | val_dqn_proxy_expanded5=0.8878

Epoch 013 | train_loss=0.1074 | ce=0.1046 | ent=0.0567 | center=0.0000 | val_loss=0.0435 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9268 | val_dqn_proxy_expanded5=0.8666

Epoch 014 | train_loss=0.1062 | ce=0.1030 | ent=0.0627 | center=0.0000 | val_loss=0.1919 | val_acc=0.9444 | val_macro_f1=0.9441 | val_dqn_proxy_softmax3=0.9469 | val_dqn_proxy_expanded5=0.8775

Epoch 015 | train_loss=0.1351 | ce=0.1321 | ent=0.0604 | center=0.0000 | val_loss=0.0360 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9463 | val_dqn_proxy_expanded5=0.8887

Epoch 016 | train_loss=0.1192 | ce=0.1164 | ent=0.0558 | center=0.0000 | val_loss=0.0836 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.5258 | val_dqn_proxy_expanded5=0.6256

Epoch 017 | train_loss=0.1035 | ce=0.1010 | ent=0.0512 | center=0.0000 | val_loss=0.0935 | val_acc=0.9667 | val_macro_f1=0.9666 | val_dqn_proxy_softmax3=0.9379 | val_dqn_proxy_expanded5=0.8708

Epoch 018 | train_loss=0.0961 | ce=0.0938 | ent=0.0452 | center=0.0000 | val_loss=0.0282 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9487 | val_dqn_proxy_expanded5=0.8950

Epoch 019 | train_loss=0.0881 | ce=0.0860 | ent=0.0410 | center=0.0000 | val_loss=0.1448 | val_acc=0.9481 | val_macro_f1=0.9478 | val_dqn_proxy_softmax3=0.9367 | val_dqn_proxy_expanded5=0.8874

Epoch 020 | train_loss=0.0989 | ce=0.0966 | ent=0.0456 | center=0.0000 | val_loss=0.0253 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9499 | val_dqn_proxy_expanded5=0.8892

Epoch 021 | train_loss=0.0860 | ce=0.0839 | ent=0.0425 | center=0.0000 | val_loss=0.0540 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.9280 | val_dqn_proxy_expanded5=0.8566

Epoch 022 | train_loss=0.1137 | ce=0.1118 | ent=0.0388 | center=0.0000 | val_loss=0.0361 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9037 | val_dqn_proxy_expanded5=0.8581

Epoch 023 | train_loss=0.0656 | ce=0.0636 | ent=0.0396 | center=0.0000 | val_loss=0.0259 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9612 | val_dqn_proxy_expanded5=0.9164

Epoch 024 | train_loss=0.0850 | ce=0.0833 | ent=0.0347 | center=0.0000 | val_loss=0.0497 | val_acc=0.9704 | val_macro_f1=0.9703 | val_dqn_proxy_softmax3=0.9558 | val_dqn_proxy_expanded5=0.9029

Epoch 025 | train_loss=0.1014 | ce=0.0997 | ent=0.0341 | center=0.0000 | val_loss=0.0208 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9395 | val_dqn_proxy_expanded5=0.8772

Epoch 026 | train_loss=0.1008 | ce=0.0992 | ent=0.0329 | center=0.0000 | val_loss=0.0470 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.9527 | val_dqn_proxy_expanded5=0.8956

Epoch 027 | train_loss=0.0815 | ce=0.0797 | ent=0.0368 | center=0.0000 | val_loss=0.0234 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9718 | val_dqn_proxy_expanded5=0.9211

Epoch 028 | train_loss=0.0899 | ce=0.0882 | ent=0.0347 | center=0.0000 | val_loss=0.1285 | val_acc=0.9741 | val_macro_f1=0.9740 | val_dqn_proxy_softmax3=0.9431 | val_dqn_proxy_expanded5=0.9091

Epoch 029 | train_loss=0.0590 | ce=0.0576 | ent=0.0282 | center=0.0000 | val_loss=0.0412 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9442 | val_dqn_proxy_expanded5=0.9052

Epoch 030 | train_loss=0.0619 | ce=0.0606 | ent=0.0265 | center=0.0000 | val_loss=0.0196 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9386 | val_dqn_proxy_expanded5=0.8913

Epoch 031 | train_loss=0.0746 | ce=0.0731 | ent=0.0285 | center=0.0000 | val_loss=0.0857 | val_acc=0.9667 | val_macro_f1=0.9666 | val_dqn_proxy_softmax3=0.9479 | val_dqn_proxy_expanded5=0.8830

Epoch 032 | train_loss=0.0595 | ce=0.0581 | ent=0.0275 | center=0.0000 | val_loss=0.0175 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9661 | val_dqn_proxy_expanded5=0.9226

Epoch 033 | train_loss=0.1002 | ce=0.0989 | ent=0.0257 | center=0.0000 | val_loss=0.0385 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9552 | val_dqn_proxy_expanded5=0.9226

Epoch 034 | train_loss=0.0579 | ce=0.0568 | ent=0.0210 | center=0.0000 | val_loss=0.0230 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9438 | val_dqn_proxy_expanded5=0.9107

Epoch 035 | train_loss=0.0558 | ce=0.0547 | ent=0.0225 | center=0.0000 | val_loss=0.0070 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9627 | val_dqn_proxy_expanded5=0.9245

Epoch 036 | train_loss=0.0470 | ce=0.0460 | ent=0.0195 | center=0.0000 | val_loss=0.0405 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9628 | val_dqn_proxy_expanded5=0.9290

Epoch 037 | train_loss=0.0597 | ce=0.0586 | ent=0.0201 | center=0.0000 | val_loss=0.0326 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9094 | val_dqn_proxy_expanded5=0.8337

Epoch 038 | train_loss=0.0673 | ce=0.0663 | ent=0.0209 | center=0.0000 | val_loss=0.0622 | val_acc=0.9741 | val_macro_f1=0.9740 | val_dqn_proxy_softmax3=0.9453 | val_dqn_proxy_expanded5=0.9101

Epoch 039 | train_loss=0.0555 | ce=0.0545 | ent=0.0186 | center=0.0000 | val_loss=0.0156 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9701 | val_dqn_proxy_expanded5=0.9297

Epoch 040 | train_loss=0.0520 | ce=0.0509 | ent=0.0217 | center=0.0000 | val_loss=0.0297 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9652 | val_dqn_proxy_expanded5=0.9049

Epoch 041 | train_loss=0.0481 | ce=0.0472 | ent=0.0192 | center=0.0000 | val_loss=0.0779 | val_acc=0.9704 | val_macro_f1=0.9703 | val_dqn_proxy_softmax3=0.9474 | val_dqn_proxy_expanded5=0.8773

Epoch 042 | train_loss=0.0453 | ce=0.0444 | ent=0.0181 | center=0.0000 | val_loss=0.0112 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9172 | val_dqn_proxy_expanded5=0.8450
Early stopping at epoch 42 (best epoch: 27)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
11,confman_paperish_mild_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-46_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,confman_baseline_knownonly_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-26_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,confman_paperish_mid_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-52_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
19,confman_paperish_strong_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/17-10_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,confman_paperish_mild_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-39_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
5,confman_baseline_openconf_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-30_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,confman_baseline_openconf_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-28_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
15,confman_paperish_mid_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-59_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,confman_baseline_openconf_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-35_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
14,confman_paperish_mid_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-57_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
17,confman_paperish_strong_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/17-04_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
16,confman_paperish_strong_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/17-02_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
21,confman_paperish_mid_nocenter_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/17-16_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
18,confman_paperish_strong_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/17-08_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
8,confman_paperish_mild_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-37_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,confman_baseline_openconf_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-33_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
20,confman_paperish_mid_nocenter_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/17-13_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
10,confman_paperish_mild_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-43_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,confman_baseline_knownonly_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-19_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,confman_paperish_mid_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-48_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,confman_baseline_knownonly_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-21_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,confman_baseline_knownonly_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-24_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"

================================================================================
Running experiment 23/32
{
  "run_name": "confman_paperish_mid_nocenter_unkPA4_c16384_seed0",
  "task": "pa",
  "split_mode": "open_pa",
  "unknown_pas": [
    "PA4"
  ],
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "lr": 0.0001,
  "weight_decay": 0.0001,
  "lambda_center": 0.0,
  "label_smoothing": 0.0,
  "entropy_loss_weight": 0.05,
  "mlp_dropout": 0.5,
  "class_weight_mode": null,
  "grad_clip_norm": 1.0,
  "scheduler_name": "plateau",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "epochs": 200,
  "early_stopping_patience": 15,
  "save_root": "results_pa_confmanifold_coarse"
}
================================================================================

Epoch 001 | train_loss=0.8651 | ce=0.8169 | ent=0.9636 | center=0.0000 | val_loss=0.3700 | val_acc=0.9185 | val_macro_f1=0.9173 | val_dqn_proxy_softmax3=0.7144 | val_dqn_proxy_expanded5=0.7219

Epoch 002 | train_loss=0.3570 | ce=0.3350 | ent=0.4408 | center=0.0000 | val_loss=0.2466 | val_acc=0.9185 | val_macro_f1=0.9169 | val_dqn_proxy_softmax3=0.7043 | val_dqn_proxy_expanded5=0.7222

Epoch 003 | train_loss=0.2744 | ce=0.2618 | ent=0.2519 | center=0.0000 | val_loss=0.2091 | val_acc=0.9333 | val_macro_f1=0.9327 | val_dqn_proxy_softmax3=0.7331 | val_dqn_proxy_expanded5=0.7562

Epoch 004 | train_loss=0.2695 | ce=0.2593 | ent=0.2037 | center=0.0000 | val_loss=0.2767 | val_acc=0.9185 | val_macro_f1=0.9183 | val_dqn_proxy_softmax3=0.7643 | val_dqn_proxy_expanded5=0.7847

Epoch 005 | train_loss=0.2595 | ce=0.2507 | ent=0.1744 | center=0.0000 | val_loss=0.2516 | val_acc=0.9222 | val_macro_f1=0.9219 | val_dqn_proxy_softmax3=0.7746 | val_dqn_proxy_expanded5=0.8018

Epoch 006 | train_loss=0.2497 | ce=0.2417 | ent=0.1602 | center=0.0000 | val_loss=0.2188 | val_acc=0.9296 | val_macro_f1=0.9294 | val_dqn_proxy_softmax3=0.8122 | val_dqn_proxy_expanded5=0.8394

Epoch 007 | train_loss=0.1968 | ce=0.1902 | ent=0.1313 | center=0.0000 | val_loss=0.1464 | val_acc=0.9519 | val_macro_f1=0.9521 | val_dqn_proxy_softmax3=0.7805 | val_dqn_proxy_expanded5=0.8248

Epoch 008 | train_loss=0.1745 | ce=0.1688 | ent=0.1141 | center=0.0000 | val_loss=0.1221 | val_acc=0.9630 | val_macro_f1=0.9632 | val_dqn_proxy_softmax3=0.8455 | val_dqn_proxy_expanded5=0.8671

Epoch 009 | train_loss=0.1823 | ce=0.1766 | ent=0.1139 | center=0.0000 | val_loss=0.1107 | val_acc=0.9593 | val_macro_f1=0.9592 | val_dqn_proxy_softmax3=0.8952 | val_dqn_proxy_expanded5=0.9149

Epoch 010 | train_loss=0.1580 | ce=0.1525 | ent=0.1107 | center=0.0000 | val_loss=0.1123 | val_acc=0.9667 | val_macro_f1=0.9669 | val_dqn_proxy_softmax3=0.8950 | val_dqn_proxy_expanded5=0.8932

Epoch 011 | train_loss=0.1542 | ce=0.1497 | ent=0.0897 | center=0.0000 | val_loss=0.1086 | val_acc=0.9593 | val_macro_f1=0.9592 | val_dqn_proxy_softmax3=0.9175 | val_dqn_proxy_expanded5=0.9112

Epoch 012 | train_loss=0.1057 | ce=0.1017 | ent=0.0811 | center=0.0000 | val_loss=0.0734 | val_acc=0.9630 | val_macro_f1=0.9630 | val_dqn_proxy_softmax3=0.8921 | val_dqn_proxy_expanded5=0.8882

Epoch 013 | train_loss=0.1093 | ce=0.1059 | ent=0.0687 | center=0.0000 | val_loss=0.0630 | val_acc=0.9778 | val_macro_f1=0.9779 | val_dqn_proxy_softmax3=0.9150 | val_dqn_proxy_expanded5=0.9130

Epoch 014 | train_loss=0.1062 | ce=0.1034 | ent=0.0553 | center=0.0000 | val_loss=0.0851 | val_acc=0.9704 | val_macro_f1=0.9704 | val_dqn_proxy_softmax3=0.9233 | val_dqn_proxy_expanded5=0.9138

Epoch 015 | train_loss=0.1140 | ce=0.1110 | ent=0.0608 | center=0.0000 | val_loss=0.1171 | val_acc=0.9667 | val_macro_f1=0.9666 | val_dqn_proxy_softmax3=0.8880 | val_dqn_proxy_expanded5=0.8704

Epoch 016 | train_loss=0.0943 | ce=0.0914 | ent=0.0577 | center=0.0000 | val_loss=0.0845 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.9486 | val_dqn_proxy_expanded5=0.9474

Epoch 017 | train_loss=0.0830 | ce=0.0809 | ent=0.0427 | center=0.0000 | val_loss=0.0444 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.9327 | val_dqn_proxy_expanded5=0.9178

Epoch 018 | train_loss=0.0852 | ce=0.0829 | ent=0.0467 | center=0.0000 | val_loss=0.0270 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9288 | val_dqn_proxy_expanded5=0.9115

Epoch 019 | train_loss=0.0728 | ce=0.0708 | ent=0.0406 | center=0.0000 | val_loss=0.0274 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9341 | val_dqn_proxy_expanded5=0.9257

Epoch 020 | train_loss=0.0628 | ce=0.0608 | ent=0.0408 | center=0.0000 | val_loss=0.0906 | val_acc=0.9704 | val_macro_f1=0.9703 | val_dqn_proxy_softmax3=0.9040 | val_dqn_proxy_expanded5=0.8758

Epoch 021 | train_loss=0.0862 | ce=0.0843 | ent=0.0384 | center=0.0000 | val_loss=0.0408 | val_acc=0.9741 | val_macro_f1=0.9741 | val_dqn_proxy_softmax3=0.8686 | val_dqn_proxy_expanded5=0.8307

Epoch 022 | train_loss=0.0820 | ce=0.0800 | ent=0.0394 | center=0.0000 | val_loss=0.0096 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9354 | val_dqn_proxy_expanded5=0.9023

Epoch 023 | train_loss=0.0572 | ce=0.0558 | ent=0.0299 | center=0.0000 | val_loss=0.1014 | val_acc=0.9741 | val_macro_f1=0.9740 | val_dqn_proxy_softmax3=0.9018 | val_dqn_proxy_expanded5=0.8609

Epoch 024 | train_loss=0.0718 | ce=0.0702 | ent=0.0314 | center=0.0000 | val_loss=0.0123 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.5116 | val_dqn_proxy_expanded5=0.6025

Epoch 025 | train_loss=0.0677 | ce=0.0660 | ent=0.0325 | center=0.0000 | val_loss=0.0131 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.3904 | val_dqn_proxy_expanded5=0.5835

Epoch 026 | train_loss=0.0468 | ce=0.0454 | ent=0.0261 | center=0.0000 | val_loss=0.0238 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9321 | val_dqn_proxy_expanded5=0.8786

Epoch 027 | train_loss=0.0680 | ce=0.0665 | ent=0.0298 | center=0.0000 | val_loss=0.0079 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.5063 | val_dqn_proxy_expanded5=0.5938

Epoch 028 | train_loss=0.0528 | ce=0.0516 | ent=0.0242 | center=0.0000 | val_loss=0.0092 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.8075 | val_dqn_proxy_expanded5=0.7710

Epoch 029 | train_loss=0.0535 | ce=0.0521 | ent=0.0280 | center=0.0000 | val_loss=0.0229 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.6509 | val_dqn_proxy_expanded5=0.6712

Epoch 030 | train_loss=0.0473 | ce=0.0463 | ent=0.0207 | center=0.0000 | val_loss=0.0134 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.8635 | val_dqn_proxy_expanded5=0.8221

Epoch 031 | train_loss=0.0598 | ce=0.0585 | ent=0.0258 | center=0.0000 | val_loss=0.0497 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8416 | val_dqn_proxy_expanded5=0.7940
Early stopping at epoch 31 (best epoch: 16)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
11,confman_paperish_mild_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-46_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,confman_baseline_knownonly_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-26_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,confman_paperish_mid_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-52_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
19,confman_paperish_strong_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/17-10_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,confman_paperish_mild_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-39_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
5,confman_baseline_openconf_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-30_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,confman_baseline_openconf_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-28_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
15,confman_paperish_mid_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-59_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,confman_baseline_openconf_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-35_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
22,confman_paperish_mid_nocenter_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/17-19_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
14,confman_paperish_mid_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-57_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
17,confman_paperish_strong_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/17-04_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
16,confman_paperish_strong_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/17-02_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
21,confman_paperish_mid_nocenter_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/17-16_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
18,confman_paperish_strong_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/17-08_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
8,confman_paperish_mild_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-37_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,confman_baseline_openconf_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-33_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
20,confman_paperish_mid_nocenter_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/17-13_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
10,confman_paperish_mild_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-43_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,confman_baseline_knownonly_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-19_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,confman_paperish_mid_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-48_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,confman_baseline_knownonly_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-21_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,confman_baseline_knownonly_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-24_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"

================================================================================
Running experiment 24/32
{
  "run_name": "confman_paperish_mid_nocenter_unkPA8_c16384_seed0",
  "task": "pa",
  "split_mode": "open_pa",
  "unknown_pas": [
    "PA8"
  ],
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "lr": 0.0001,
  "weight_decay": 0.0001,
  "lambda_center": 0.0,
  "label_smoothing": 0.0,
  "entropy_loss_weight": 0.05,
  "mlp_dropout": 0.5,
  "class_weight_mode": null,
  "grad_clip_norm": 1.0,
  "scheduler_name": "plateau",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "epochs": 200,
  "early_stopping_patience": 15,
  "save_root": "results_pa_confmanifold_coarse"
}
================================================================================

Epoch 001 | train_loss=0.8628 | ce=0.8141 | ent=0.9736 | center=0.0000 | val_loss=0.2921 | val_acc=0.9407 | val_macro_f1=0.9405 | val_dqn_proxy_softmax3=0.7797 | val_dqn_proxy_expanded5=0.7714

Epoch 002 | train_loss=0.1767 | ce=0.1645 | ent=0.2446 | center=0.0000 | val_loss=0.1704 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9109 | val_dqn_proxy_expanded5=0.8902

Epoch 003 | train_loss=0.1143 | ce=0.1111 | ent=0.0632 | center=0.0000 | val_loss=0.1692 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8805 | val_dqn_proxy_expanded5=0.8691

Epoch 004 | train_loss=0.0832 | ce=0.0812 | ent=0.0394 | center=0.0000 | val_loss=0.1572 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9024 | val_dqn_proxy_expanded5=0.9041

Epoch 005 | train_loss=0.0858 | ce=0.0838 | ent=0.0407 | center=0.0000 | val_loss=0.1512 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8597 | val_dqn_proxy_expanded5=0.8701

Epoch 006 | train_loss=0.0712 | ce=0.0698 | ent=0.0271 | center=0.0000 | val_loss=0.1314 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8657 | val_dqn_proxy_expanded5=0.8907

Epoch 007 | train_loss=0.0720 | ce=0.0706 | ent=0.0283 | center=0.0000 | val_loss=0.1293 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8511 | val_dqn_proxy_expanded5=0.8614

Epoch 008 | train_loss=0.0723 | ce=0.0711 | ent=0.0244 | center=0.0000 | val_loss=0.0989 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8343 | val_dqn_proxy_expanded5=0.8452

Epoch 009 | train_loss=0.0647 | ce=0.0635 | ent=0.0242 | center=0.0000 | val_loss=0.0995 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8329 | val_dqn_proxy_expanded5=0.8372

Epoch 010 | train_loss=0.0563 | ce=0.0550 | ent=0.0255 | center=0.0000 | val_loss=0.1061 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8353 | val_dqn_proxy_expanded5=0.8580

Epoch 011 | train_loss=0.0606 | ce=0.0593 | ent=0.0259 | center=0.0000 | val_loss=0.1060 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8287 | val_dqn_proxy_expanded5=0.8558

Epoch 012 | train_loss=0.0584 | ce=0.0572 | ent=0.0249 | center=0.0000 | val_loss=0.1223 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8331 | val_dqn_proxy_expanded5=0.8587

Epoch 013 | train_loss=0.0697 | ce=0.0683 | ent=0.0286 | center=0.0000 | val_loss=0.0952 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8377 | val_dqn_proxy_expanded5=0.8657

Epoch 014 | train_loss=0.0607 | ce=0.0592 | ent=0.0301 | center=0.0000 | val_loss=0.1035 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8494 | val_dqn_proxy_expanded5=0.8788

Epoch 015 | train_loss=0.0555 | ce=0.0542 | ent=0.0257 | center=0.0000 | val_loss=0.0902 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.7681 | val_dqn_proxy_expanded5=0.8051

Epoch 016 | train_loss=0.0445 | ce=0.0430 | ent=0.0295 | center=0.0000 | val_loss=0.0892 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8417 | val_dqn_proxy_expanded5=0.8652

Epoch 017 | train_loss=0.0618 | ce=0.0605 | ent=0.0259 | center=0.0000 | val_loss=0.0987 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8164 | val_dqn_proxy_expanded5=0.8548
Early stopping at epoch 17 (best epoch: 2)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
11,confman_paperish_mild_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-46_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,confman_baseline_knownonly_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-26_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,confman_paperish_mid_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-52_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
19,confman_paperish_strong_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/17-10_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,confman_paperish_mild_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-39_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
5,confman_baseline_openconf_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-30_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,confman_baseline_openconf_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-28_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
15,confman_paperish_mid_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-59_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,confman_baseline_openconf_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-35_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
22,confman_paperish_mid_nocenter_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/17-19_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
14,confman_paperish_mid_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-57_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
17,confman_paperish_strong_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/17-04_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
23,confman_paperish_mid_nocenter_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/17-22_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
16,confman_paperish_strong_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/17-02_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
21,confman_paperish_mid_nocenter_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/17-16_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
18,confman_paperish_strong_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/17-08_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
8,confman_paperish_mild_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-37_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,confman_baseline_openconf_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-33_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
20,confman_paperish_mid_nocenter_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/17-13_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
10,confman_paperish_mild_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-43_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,confman_baseline_knownonly_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-19_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,confman_paperish_mid_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-48_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,confman_baseline_knownonly_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-21_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,confman_baseline_knownonly_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-24_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"

================================================================================
Running experiment 25/32
{
  "run_name": "confman_paperish_mid_lowdrop_unkPA2_c16384_seed0",
  "task": "pa",
  "split_mode": "open_pa",
  "unknown_pas": [
    "PA2"
  ],
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "lr": 0.0001,
  "weight_decay": 0.0001,
  "lambda_center": 0.1,
  "label_smoothing": 0.0,
  "entropy_loss_weight": 0.05,
  "mlp_dropout": 0.3,
  "class_weight_mode": null,
  "grad_clip_norm": 1.0,
  "scheduler_name": "plateau",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "epochs": 200,
  "early_stopping_patience": 15,
  "save_root": "results_pa_confmanifold_coarse"
}
================================================================================

Epoch 001 | train_loss=0.7869 | ce=0.6307 | ent=0.8006 | center=1.1617 | val_loss=0.1688 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7599 | val_dqn_proxy_expanded5=0.7923

Epoch 002 | train_loss=0.3046 | ce=0.1610 | ent=0.2124 | center=1.3303 | val_loss=0.1026 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6535 | val_dqn_proxy_expanded5=0.7537

Epoch 003 | train_loss=0.2404 | ce=0.1194 | ent=0.1626 | center=1.1294 | val_loss=0.0868 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.5671 | val_dqn_proxy_expanded5=0.6990

Epoch 004 | train_loss=0.2287 | ce=0.1174 | ent=0.1290 | center=1.0487 | val_loss=0.0824 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6043 | val_dqn_proxy_expanded5=0.7184

Epoch 005 | train_loss=0.2122 | ce=0.1084 | ent=0.1170 | center=0.9796 | val_loss=0.0829 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.5921 | val_dqn_proxy_expanded5=0.7125

Epoch 006 | train_loss=0.1938 | ce=0.0958 | ent=0.1073 | center=0.9261 | val_loss=0.0796 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6110 | val_dqn_proxy_expanded5=0.7276

Epoch 007 | train_loss=0.1752 | ce=0.0835 | ent=0.0906 | center=0.8719 | val_loss=0.0684 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6546 | val_dqn_proxy_expanded5=0.7359

Epoch 008 | train_loss=0.1796 | ce=0.0926 | ent=0.1036 | center=0.8187 | val_loss=0.0736 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7167 | val_dqn_proxy_expanded5=0.7461

Epoch 009 | train_loss=0.1632 | ce=0.0801 | ent=0.0876 | center=0.7873 | val_loss=0.0612 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6175 | val_dqn_proxy_expanded5=0.7162

Epoch 010 | train_loss=0.1555 | ce=0.0747 | ent=0.0816 | center=0.7675 | val_loss=0.0756 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6188 | val_dqn_proxy_expanded5=0.7157

Epoch 011 | train_loss=0.1364 | ce=0.0594 | ent=0.0854 | center=0.7267 | val_loss=0.0663 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6289 | val_dqn_proxy_expanded5=0.7193

Epoch 012 | train_loss=0.1454 | ce=0.0718 | ent=0.0697 | center=0.7012 | val_loss=0.0586 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.5938 | val_dqn_proxy_expanded5=0.7068

Epoch 013 | train_loss=0.1392 | ce=0.0682 | ent=0.0698 | center=0.6758 | val_loss=0.0543 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6977 | val_dqn_proxy_expanded5=0.7412

Epoch 014 | train_loss=0.1197 | ce=0.0515 | ent=0.0710 | center=0.6466 | val_loss=0.0623 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8772 | val_dqn_proxy_expanded5=0.8536

Epoch 015 | train_loss=0.1266 | ce=0.0598 | ent=0.0674 | center=0.6348 | val_loss=0.0425 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6771 | val_dqn_proxy_expanded5=0.7346

Epoch 016 | train_loss=0.1147 | ce=0.0509 | ent=0.0602 | center=0.6077 | val_loss=0.0407 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.5129 | val_dqn_proxy_expanded5=0.6842

Epoch 017 | train_loss=0.0966 | ce=0.0351 | ent=0.0483 | center=0.5913 | val_loss=0.0480 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8595 | val_dqn_proxy_expanded5=0.8246

Epoch 018 | train_loss=0.0927 | ce=0.0342 | ent=0.0496 | center=0.5594 | val_loss=0.0518 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8420 | val_dqn_proxy_expanded5=0.8061

Epoch 019 | train_loss=0.0894 | ce=0.0326 | ent=0.0393 | center=0.5483 | val_loss=0.0374 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6801 | val_dqn_proxy_expanded5=0.7450

Epoch 020 | train_loss=0.0893 | ce=0.0352 | ent=0.0408 | center=0.5203 | val_loss=0.0377 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.5546 | val_dqn_proxy_expanded5=0.6919

Epoch 021 | train_loss=0.0844 | ce=0.0315 | ent=0.0425 | center=0.5086 | val_loss=0.0401 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6579 | val_dqn_proxy_expanded5=0.7367

Epoch 022 | train_loss=0.0815 | ce=0.0310 | ent=0.0349 | center=0.4877 | val_loss=0.0346 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6361 | val_dqn_proxy_expanded5=0.7268

Epoch 023 | train_loss=0.0798 | ce=0.0297 | ent=0.0430 | center=0.4790 | val_loss=0.0423 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.5968 | val_dqn_proxy_expanded5=0.7048

Epoch 024 | train_loss=0.0719 | ce=0.0249 | ent=0.0321 | center=0.4543 | val_loss=0.0428 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.5919 | val_dqn_proxy_expanded5=0.7022

Epoch 025 | train_loss=0.0755 | ce=0.0299 | ent=0.0314 | center=0.4406 | val_loss=0.0393 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.5562 | val_dqn_proxy_expanded5=0.7006

Epoch 026 | train_loss=0.0754 | ce=0.0311 | ent=0.0324 | center=0.4273 | val_loss=0.0396 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6754 | val_dqn_proxy_expanded5=0.7390

Epoch 027 | train_loss=0.0727 | ce=0.0294 | ent=0.0315 | center=0.4174 | val_loss=0.0364 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6300 | val_dqn_proxy_expanded5=0.7242

Epoch 028 | train_loss=0.0687 | ce=0.0274 | ent=0.0321 | center=0.3971 | val_loss=0.0371 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7110 | val_dqn_proxy_expanded5=0.7573

Epoch 029 | train_loss=0.0702 | ce=0.0303 | ent=0.0249 | center=0.3869 | val_loss=0.0348 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6022 | val_dqn_proxy_expanded5=0.7253
Early stopping at epoch 29 (best epoch: 14)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
11,confman_paperish_mild_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-46_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,confman_baseline_knownonly_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-26_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,confman_paperish_mid_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-52_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
19,confman_paperish_strong_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/17-10_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,confman_paperish_mild_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-39_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
5,confman_baseline_openconf_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-30_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,confman_baseline_openconf_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-28_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
15,confman_paperish_mid_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-59_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,confman_baseline_openconf_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-35_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
22,confman_paperish_mid_nocenter_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/17-19_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
14,confman_paperish_mid_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-57_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
17,confman_paperish_strong_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/17-04_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
23,confman_paperish_mid_nocenter_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/17-22_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
16,confman_paperish_strong_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/17-02_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
21,confman_paperish_mid_nocenter_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/17-16_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
18,confman_paperish_strong_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/17-08_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
8,confman_paperish_mild_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-37_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,confman_baseline_openconf_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-33_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
20,confman_paperish_mid_nocenter_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/17-13_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
10,confman_paperish_mild_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-43_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,confman_baseline_knownonly_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-19_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
24,confman_paperish_mid_lowdrop_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/17-23_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,confman_paperish_mid_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-48_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,confman_baseline_knownonly_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-21_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,confman_baseline_knownonly_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-24_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"

================================================================================
Running experiment 26/32
{
  "run_name": "confman_paperish_mid_lowdrop_unkPA3_c16384_seed0",
  "task": "pa",
  "split_mode": "open_pa",
  "unknown_pas": [
    "PA3"
  ],
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "lr": 0.0001,
  "weight_decay": 0.0001,
  "lambda_center": 0.1,
  "label_smoothing": 0.0,
  "entropy_loss_weight": 0.05,
  "mlp_dropout": 0.3,
  "class_weight_mode": null,
  "grad_clip_norm": 1.0,
  "scheduler_name": "plateau",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "epochs": 200,
  "early_stopping_patience": 15,
  "save_root": "results_pa_confmanifold_coarse"
}
================================================================================

Epoch 001 | train_loss=0.8489 | ce=0.6919 | ent=0.8633 | center=1.1378 | val_loss=0.2217 | val_acc=0.9333 | val_macro_f1=0.9334 | val_dqn_proxy_softmax3=0.8290 | val_dqn_proxy_expanded5=0.7882

Epoch 002 | train_loss=0.4198 | ce=0.2615 | ent=0.3286 | center=1.4187 | val_loss=0.1135 | val_acc=0.9704 | val_macro_f1=0.9706 | val_dqn_proxy_softmax3=0.9051 | val_dqn_proxy_expanded5=0.8610

Epoch 003 | train_loss=0.3302 | ce=0.1872 | ent=0.2263 | center=1.3171 | val_loss=0.1279 | val_acc=0.9481 | val_macro_f1=0.9484 | val_dqn_proxy_softmax3=0.8657 | val_dqn_proxy_expanded5=0.8447

Epoch 004 | train_loss=0.2784 | ce=0.1471 | ent=0.1904 | center=1.2180 | val_loss=0.1045 | val_acc=0.9519 | val_macro_f1=0.9521 | val_dqn_proxy_softmax3=0.9419 | val_dqn_proxy_expanded5=0.9074

Epoch 005 | train_loss=0.2566 | ce=0.1342 | ent=0.1595 | center=1.1444 | val_loss=0.1053 | val_acc=0.9556 | val_macro_f1=0.9558 | val_dqn_proxy_softmax3=0.9759 | val_dqn_proxy_expanded5=0.9529

Epoch 006 | train_loss=0.2496 | ce=0.1354 | ent=0.1660 | center=1.0595 | val_loss=0.0834 | val_acc=0.9741 | val_macro_f1=0.9740 | val_dqn_proxy_softmax3=0.9460 | val_dqn_proxy_expanded5=0.9318

Epoch 007 | train_loss=0.2180 | ce=0.1105 | ent=0.1344 | center=1.0078 | val_loss=0.0798 | val_acc=0.9704 | val_macro_f1=0.9704 | val_dqn_proxy_softmax3=0.9453 | val_dqn_proxy_expanded5=0.9268

Epoch 008 | train_loss=0.2320 | ce=0.1284 | ent=0.1380 | center=0.9668 | val_loss=0.0632 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.9633 | val_dqn_proxy_expanded5=0.9561

Epoch 009 | train_loss=0.1839 | ce=0.0862 | ent=0.1085 | center=0.9225 | val_loss=0.0892 | val_acc=0.9630 | val_macro_f1=0.9628 | val_dqn_proxy_softmax3=0.9763 | val_dqn_proxy_expanded5=0.9670

Epoch 010 | train_loss=0.1911 | ce=0.0968 | ent=0.1122 | center=0.8867 | val_loss=0.0797 | val_acc=0.9704 | val_macro_f1=0.9703 | val_dqn_proxy_softmax3=0.9807 | val_dqn_proxy_expanded5=0.9764

Epoch 011 | train_loss=0.1688 | ce=0.0790 | ent=0.1014 | center=0.8473 | val_loss=0.0779 | val_acc=0.9667 | val_macro_f1=0.9667 | val_dqn_proxy_softmax3=0.9094 | val_dqn_proxy_expanded5=0.8728

Epoch 012 | train_loss=0.1677 | ce=0.0797 | ent=0.0950 | center=0.8329 | val_loss=0.0444 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9699 | val_dqn_proxy_expanded5=0.9355

Epoch 013 | train_loss=0.1665 | ce=0.0817 | ent=0.0968 | center=0.7990 | val_loss=0.0554 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.9598 | val_dqn_proxy_expanded5=0.9336

Epoch 014 | train_loss=0.1594 | ce=0.0770 | ent=0.0814 | center=0.7824 | val_loss=0.0407 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9525 | val_dqn_proxy_expanded5=0.9343

Epoch 015 | train_loss=0.1646 | ce=0.0862 | ent=0.0823 | center=0.7428 | val_loss=0.0466 | val_acc=0.9778 | val_macro_f1=0.9779 | val_dqn_proxy_softmax3=0.9394 | val_dqn_proxy_expanded5=0.9120

Epoch 016 | train_loss=0.1393 | ce=0.0629 | ent=0.0797 | center=0.7241 | val_loss=0.0366 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9542 | val_dqn_proxy_expanded5=0.9035

Epoch 017 | train_loss=0.1332 | ce=0.0609 | ent=0.0680 | center=0.6888 | val_loss=0.0210 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9762 | val_dqn_proxy_expanded5=0.9353

Epoch 018 | train_loss=0.1279 | ce=0.0584 | ent=0.0653 | center=0.6617 | val_loss=0.0448 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.9769 | val_dqn_proxy_expanded5=0.9318

Epoch 019 | train_loss=0.1241 | ce=0.0568 | ent=0.0704 | center=0.6378 | val_loss=0.1147 | val_acc=0.9556 | val_macro_f1=0.9554 | val_dqn_proxy_softmax3=0.9728 | val_dqn_proxy_expanded5=0.9405

Epoch 020 | train_loss=0.1220 | ce=0.0571 | ent=0.0666 | center=0.6155 | val_loss=0.0296 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9698 | val_dqn_proxy_expanded5=0.9423

Epoch 021 | train_loss=0.1153 | ce=0.0516 | ent=0.0649 | center=0.6050 | val_loss=0.0592 | val_acc=0.9741 | val_macro_f1=0.9740 | val_dqn_proxy_softmax3=0.9657 | val_dqn_proxy_expanded5=0.9488

Epoch 022 | train_loss=0.1186 | ce=0.0576 | ent=0.0625 | center=0.5784 | val_loss=0.1261 | val_acc=0.9593 | val_macro_f1=0.9591 | val_dqn_proxy_softmax3=0.9703 | val_dqn_proxy_expanded5=0.9213

Epoch 023 | train_loss=0.1234 | ce=0.0650 | ent=0.0583 | center=0.5551 | val_loss=0.0321 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9696 | val_dqn_proxy_expanded5=0.9411

Epoch 024 | train_loss=0.0961 | ce=0.0397 | ent=0.0508 | center=0.5382 | val_loss=0.0208 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9866 | val_dqn_proxy_expanded5=0.9602

Epoch 025 | train_loss=0.1227 | ce=0.0677 | ent=0.0494 | center=0.5253 | val_loss=0.0158 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9729 | val_dqn_proxy_expanded5=0.9437

Epoch 026 | train_loss=0.1070 | ce=0.0526 | ent=0.0501 | center=0.5182 | val_loss=0.0164 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9816 | val_dqn_proxy_expanded5=0.9580

Epoch 027 | train_loss=0.0913 | ce=0.0384 | ent=0.0458 | center=0.5066 | val_loss=0.0129 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9899 | val_dqn_proxy_expanded5=0.9678

Epoch 028 | train_loss=0.0998 | ce=0.0479 | ent=0.0463 | center=0.4957 | val_loss=0.0273 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9780 | val_dqn_proxy_expanded5=0.9441

Epoch 029 | train_loss=0.0922 | ce=0.0409 | ent=0.0426 | center=0.4919 | val_loss=0.0133 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9907 | val_dqn_proxy_expanded5=0.9726

Epoch 030 | train_loss=0.0970 | ce=0.0468 | ent=0.0454 | center=0.4793 | val_loss=0.0168 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9918 | val_dqn_proxy_expanded5=0.9753

Epoch 031 | train_loss=0.0771 | ce=0.0274 | ent=0.0436 | center=0.4745 | val_loss=0.0662 | val_acc=0.9704 | val_macro_f1=0.9703 | val_dqn_proxy_softmax3=0.9770 | val_dqn_proxy_expanded5=0.9493

Epoch 032 | train_loss=0.0819 | ce=0.0330 | ent=0.0383 | center=0.4698 | val_loss=0.0328 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9808 | val_dqn_proxy_expanded5=0.9520

Epoch 033 | train_loss=0.0756 | ce=0.0278 | ent=0.0352 | center=0.4606 | val_loss=0.0108 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9934 | val_dqn_proxy_expanded5=0.9780

Epoch 034 | train_loss=0.0778 | ce=0.0312 | ent=0.0341 | center=0.4491 | val_loss=0.0541 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9948 | val_dqn_proxy_expanded5=0.9767

Epoch 035 | train_loss=0.0726 | ce=0.0265 | ent=0.0326 | center=0.4448 | val_loss=0.0131 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9839 | val_dqn_proxy_expanded5=0.9584

Epoch 036 | train_loss=0.0897 | ce=0.0440 | ent=0.0400 | center=0.4373 | val_loss=0.0522 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9849 | val_dqn_proxy_expanded5=0.9612

Epoch 037 | train_loss=0.0757 | ce=0.0316 | ent=0.0321 | center=0.4254 | val_loss=0.0297 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9861 | val_dqn_proxy_expanded5=0.9722

Epoch 038 | train_loss=0.0812 | ce=0.0370 | ent=0.0372 | center=0.4232 | val_loss=0.0069 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9890 | val_dqn_proxy_expanded5=0.9641

Epoch 039 | train_loss=0.0861 | ce=0.0430 | ent=0.0299 | center=0.4169 | val_loss=0.0110 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9833 | val_dqn_proxy_expanded5=0.9734

Epoch 040 | train_loss=0.0853 | ce=0.0431 | ent=0.0288 | center=0.4080 | val_loss=0.0607 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9846 | val_dqn_proxy_expanded5=0.9634

Epoch 041 | train_loss=0.0763 | ce=0.0342 | ent=0.0315 | center=0.4047 | val_loss=0.0375 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9844 | val_dqn_proxy_expanded5=0.9657

Epoch 042 | train_loss=0.0737 | ce=0.0328 | ent=0.0256 | center=0.3959 | val_loss=0.0331 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9872 | val_dqn_proxy_expanded5=0.9647

Epoch 043 | train_loss=0.0755 | ce=0.0348 | ent=0.0325 | center=0.3904 | val_loss=0.0382 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9884 | val_dqn_proxy_expanded5=0.9565

Epoch 044 | train_loss=0.0757 | ce=0.0358 | ent=0.0295 | center=0.3845 | val_loss=0.0682 | val_acc=0.9741 | val_macro_f1=0.9740 | val_dqn_proxy_softmax3=0.9780 | val_dqn_proxy_expanded5=0.9519

Epoch 045 | train_loss=0.0688 | ce=0.0298 | ent=0.0254 | center=0.3772 | val_loss=0.0088 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9893 | val_dqn_proxy_expanded5=0.9695

Epoch 046 | train_loss=0.0736 | ce=0.0349 | ent=0.0274 | center=0.3731 | val_loss=0.0132 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9863 | val_dqn_proxy_expanded5=0.9692

Epoch 047 | train_loss=0.0708 | ce=0.0319 | ent=0.0303 | center=0.3734 | val_loss=0.0301 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9841 | val_dqn_proxy_expanded5=0.9700

Epoch 048 | train_loss=0.0566 | ce=0.0190 | ent=0.0223 | center=0.3645 | val_loss=0.0073 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9847 | val_dqn_proxy_expanded5=0.9758

Epoch 049 | train_loss=0.0642 | ce=0.0262 | ent=0.0291 | center=0.3654 | val_loss=0.0097 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9920 | val_dqn_proxy_expanded5=0.9780
Early stopping at epoch 49 (best epoch: 34)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
11,confman_paperish_mild_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-46_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,confman_baseline_knownonly_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-26_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,confman_paperish_mid_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-52_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
19,confman_paperish_strong_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/17-10_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
25,confman_paperish_mid_lowdrop_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/17-25_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,confman_paperish_mild_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-39_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
5,confman_baseline_openconf_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-30_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,confman_baseline_openconf_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-28_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
15,confman_paperish_mid_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-59_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,confman_baseline_openconf_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-35_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
22,confman_paperish_mid_nocenter_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/17-19_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
14,confman_paperish_mid_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-57_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
17,confman_paperish_strong_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/17-04_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
23,confman_paperish_mid_nocenter_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/17-22_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
16,confman_paperish_strong_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/17-02_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
21,confman_paperish_mid_nocenter_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/17-16_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
18,confman_paperish_strong_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/17-08_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
8,confman_paperish_mild_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-37_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,confman_baseline_openconf_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-33_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
20,confman_paperish_mid_nocenter_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/17-13_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
10,confman_paperish_mild_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-43_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,confman_baseline_knownonly_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-19_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
24,confman_paperish_mid_lowdrop_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/17-23_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,confman_paperish_mid_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-48_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,confman_baseline_knownonly_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-21_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,confman_baseline_knownonly_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-24_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"

================================================================================
Running experiment 27/32
{
  "run_name": "confman_paperish_mid_lowdrop_unkPA4_c16384_seed0",
  "task": "pa",
  "split_mode": "open_pa",
  "unknown_pas": [
    "PA4"
  ],
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "lr": 0.0001,
  "weight_decay": 0.0001,
  "lambda_center": 0.1,
  "label_smoothing": 0.0,
  "entropy_loss_weight": 0.05,
  "mlp_dropout": 0.3,
  "class_weight_mode": null,
  "grad_clip_norm": 1.0,
  "scheduler_name": "plateau",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "epochs": 200,
  "early_stopping_patience": 15,
  "save_root": "results_pa_confmanifold_coarse"
}
================================================================================

Epoch 001 | train_loss=0.8198 | ce=0.6606 | ent=0.8268 | center=1.1790 | val_loss=0.2641 | val_acc=0.9296 | val_macro_f1=0.9295 | val_dqn_proxy_softmax3=0.7316 | val_dqn_proxy_expanded5=0.7233

Epoch 002 | train_loss=0.4395 | ce=0.2722 | ent=0.3415 | center=1.5016 | val_loss=0.1909 | val_acc=0.9370 | val_macro_f1=0.9370 | val_dqn_proxy_softmax3=0.7435 | val_dqn_proxy_expanded5=0.7482

Epoch 003 | train_loss=0.3828 | ce=0.2404 | ent=0.2765 | center=1.2860 | val_loss=0.2146 | val_acc=0.9296 | val_macro_f1=0.9291 | val_dqn_proxy_softmax3=0.7445 | val_dqn_proxy_expanded5=0.7506

Epoch 004 | train_loss=0.3227 | ce=0.1954 | ent=0.2261 | center=1.1596 | val_loss=0.1921 | val_acc=0.9259 | val_macro_f1=0.9257 | val_dqn_proxy_softmax3=0.7202 | val_dqn_proxy_expanded5=0.7043

Epoch 005 | train_loss=0.3009 | ce=0.1838 | ent=0.2030 | center=1.0696 | val_loss=0.1474 | val_acc=0.9444 | val_macro_f1=0.9446 | val_dqn_proxy_softmax3=0.7450 | val_dqn_proxy_expanded5=0.7214

Epoch 006 | train_loss=0.2578 | ce=0.1451 | ent=0.1695 | center=1.0417 | val_loss=0.1121 | val_acc=0.9630 | val_macro_f1=0.9629 | val_dqn_proxy_softmax3=0.8017 | val_dqn_proxy_expanded5=0.7647

Epoch 007 | train_loss=0.2506 | ce=0.1438 | ent=0.1527 | center=0.9922 | val_loss=0.1002 | val_acc=0.9704 | val_macro_f1=0.9706 | val_dqn_proxy_softmax3=0.7899 | val_dqn_proxy_expanded5=0.7498

Epoch 008 | train_loss=0.2159 | ce=0.1132 | ent=0.1453 | center=0.9550 | val_loss=0.1304 | val_acc=0.9519 | val_macro_f1=0.9517 | val_dqn_proxy_softmax3=0.7708 | val_dqn_proxy_expanded5=0.7293

Epoch 009 | train_loss=0.2178 | ce=0.1194 | ent=0.1324 | center=0.9174 | val_loss=0.1062 | val_acc=0.9704 | val_macro_f1=0.9706 | val_dqn_proxy_softmax3=0.8831 | val_dqn_proxy_expanded5=0.8089

Epoch 010 | train_loss=0.1936 | ce=0.0997 | ent=0.1165 | center=0.8811 | val_loss=0.1289 | val_acc=0.9593 | val_macro_f1=0.9595 | val_dqn_proxy_softmax3=0.8889 | val_dqn_proxy_expanded5=0.8102

Epoch 011 | train_loss=0.1860 | ce=0.0965 | ent=0.1194 | center=0.8358 | val_loss=0.0687 | val_acc=0.9667 | val_macro_f1=0.9667 | val_dqn_proxy_softmax3=0.9371 | val_dqn_proxy_expanded5=0.8784

Epoch 012 | train_loss=0.1648 | ce=0.0780 | ent=0.0995 | center=0.8179 | val_loss=0.0445 | val_acc=0.9815 | val_macro_f1=0.9816 | val_dqn_proxy_softmax3=0.9357 | val_dqn_proxy_expanded5=0.8894

Epoch 013 | train_loss=0.1659 | ce=0.0819 | ent=0.1029 | center=0.7886 | val_loss=0.0471 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9440 | val_dqn_proxy_expanded5=0.9164

Epoch 014 | train_loss=0.1589 | ce=0.0779 | ent=0.0917 | center=0.7634 | val_loss=0.0439 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9315 | val_dqn_proxy_expanded5=0.8843

Epoch 015 | train_loss=0.1349 | ce=0.0571 | ent=0.0888 | center=0.7335 | val_loss=0.0315 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9493 | val_dqn_proxy_expanded5=0.8941

Epoch 016 | train_loss=0.1253 | ce=0.0516 | ent=0.0807 | center=0.6974 | val_loss=0.0600 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.8877 | val_dqn_proxy_expanded5=0.8102

Epoch 017 | train_loss=0.1407 | ce=0.0689 | ent=0.0802 | center=0.6773 | val_loss=0.0263 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9415 | val_dqn_proxy_expanded5=0.8523

Epoch 018 | train_loss=0.1064 | ce=0.0375 | ent=0.0651 | center=0.6568 | val_loss=0.0482 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.9384 | val_dqn_proxy_expanded5=0.8482

Epoch 019 | train_loss=0.1170 | ce=0.0501 | ent=0.0678 | center=0.6353 | val_loss=0.1109 | val_acc=0.9444 | val_macro_f1=0.9441 | val_dqn_proxy_softmax3=0.9388 | val_dqn_proxy_expanded5=0.8550

Epoch 020 | train_loss=0.1232 | ce=0.0587 | ent=0.0651 | center=0.6126 | val_loss=0.1063 | val_acc=0.9630 | val_macro_f1=0.9628 | val_dqn_proxy_softmax3=0.8691 | val_dqn_proxy_expanded5=0.8010

Epoch 021 | train_loss=0.1061 | ce=0.0446 | ent=0.0557 | center=0.5868 | val_loss=0.0237 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9057 | val_dqn_proxy_expanded5=0.8279

Epoch 022 | train_loss=0.1110 | ce=0.0515 | ent=0.0553 | center=0.5671 | val_loss=0.0150 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9098 | val_dqn_proxy_expanded5=0.8317

Epoch 023 | train_loss=0.0974 | ce=0.0399 | ent=0.0520 | center=0.5491 | val_loss=0.0103 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9164 | val_dqn_proxy_expanded5=0.8365

Epoch 024 | train_loss=0.1004 | ce=0.0446 | ent=0.0540 | center=0.5315 | val_loss=0.0199 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8973 | val_dqn_proxy_expanded5=0.8253

Epoch 025 | train_loss=0.0920 | ce=0.0375 | ent=0.0485 | center=0.5210 | val_loss=0.0201 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9387 | val_dqn_proxy_expanded5=0.8508

Epoch 026 | train_loss=0.0924 | ce=0.0390 | ent=0.0517 | center=0.5082 | val_loss=0.0109 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.8561 | val_dqn_proxy_expanded5=0.7971

Epoch 027 | train_loss=0.0844 | ce=0.0339 | ent=0.0443 | center=0.4831 | val_loss=0.0172 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9016 | val_dqn_proxy_expanded5=0.8271

Epoch 028 | train_loss=0.0893 | ce=0.0400 | ent=0.0399 | center=0.4739 | val_loss=0.0179 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7791 | val_dqn_proxy_expanded5=0.7490

Epoch 029 | train_loss=0.0877 | ce=0.0395 | ent=0.0426 | center=0.4609 | val_loss=0.0070 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.7958 | val_dqn_proxy_expanded5=0.7604

Epoch 030 | train_loss=0.0891 | ce=0.0428 | ent=0.0402 | center=0.4426 | val_loss=0.0158 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.7474 | val_dqn_proxy_expanded5=0.7031
Early stopping at epoch 30 (best epoch: 15)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
11,confman_paperish_mild_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-46_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,confman_baseline_knownonly_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-26_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,confman_paperish_mid_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-52_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
19,confman_paperish_strong_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/17-10_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
25,confman_paperish_mid_lowdrop_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/17-25_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,confman_paperish_mild_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-39_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
5,confman_baseline_openconf_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-30_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,confman_baseline_openconf_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-28_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
15,confman_paperish_mid_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-59_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,confman_baseline_openconf_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-35_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
22,confman_paperish_mid_nocenter_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/17-19_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
14,confman_paperish_mid_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-57_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
17,confman_paperish_strong_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/17-04_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
23,confman_paperish_mid_nocenter_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/17-22_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
16,confman_paperish_strong_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/17-02_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
21,confman_paperish_mid_nocenter_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/17-16_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
18,confman_paperish_strong_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/17-08_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
8,confman_paperish_mild_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-37_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,confman_baseline_openconf_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-33_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
20,confman_paperish_mid_nocenter_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/17-13_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
10,confman_paperish_mild_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-43_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
26,confman_paperish_mid_lowdrop_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/17-30_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,confman_baseline_knownonly_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-19_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
24,confman_paperish_mid_lowdrop_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/17-23_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,confman_paperish_mid_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-48_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,confman_baseline_knownonly_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-21_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,confman_baseline_knownonly_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-24_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"

================================================================================
Running experiment 28/32
{
  "run_name": "confman_paperish_mid_lowdrop_unkPA8_c16384_seed0",
  "task": "pa",
  "split_mode": "open_pa",
  "unknown_pas": [
    "PA8"
  ],
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "lr": 0.0001,
  "weight_decay": 0.0001,
  "lambda_center": 0.1,
  "label_smoothing": 0.0,
  "entropy_loss_weight": 0.05,
  "mlp_dropout": 0.3,
  "class_weight_mode": null,
  "grad_clip_norm": 1.0,
  "scheduler_name": "plateau",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "epochs": 200,
  "early_stopping_patience": 15,
  "save_root": "results_pa_confmanifold_coarse"
}
================================================================================

Epoch 001 | train_loss=0.7128 | ce=0.5551 | ent=0.7332 | center=1.2107 | val_loss=0.1361 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8831 | val_dqn_proxy_expanded5=0.8926

Epoch 002 | train_loss=0.2293 | ce=0.0875 | ent=0.1678 | center=1.3344 | val_loss=0.1090 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9370 | val_dqn_proxy_expanded5=0.9322

Epoch 003 | train_loss=0.2005 | ce=0.0805 | ent=0.1213 | center=1.1387 | val_loss=0.1027 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9474 | val_dqn_proxy_expanded5=0.9388

Epoch 004 | train_loss=0.1740 | ce=0.0668 | ent=0.1002 | center=1.0215 | val_loss=0.0941 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9298 | val_dqn_proxy_expanded5=0.9156

Epoch 005 | train_loss=0.1623 | ce=0.0623 | ent=0.0874 | center=0.9562 | val_loss=0.0874 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8814 | val_dqn_proxy_expanded5=0.8894

Epoch 006 | train_loss=0.1572 | ce=0.0637 | ent=0.0827 | center=0.8937 | val_loss=0.0783 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8828 | val_dqn_proxy_expanded5=0.8972

Epoch 007 | train_loss=0.1436 | ce=0.0553 | ent=0.0871 | center=0.8393 | val_loss=0.0794 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9231 | val_dqn_proxy_expanded5=0.9228

Epoch 008 | train_loss=0.1398 | ce=0.0558 | ent=0.0722 | center=0.8033 | val_loss=0.0728 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9071 | val_dqn_proxy_expanded5=0.9241

Epoch 009 | train_loss=0.1296 | ce=0.0498 | ent=0.0717 | center=0.7616 | val_loss=0.0816 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9300 | val_dqn_proxy_expanded5=0.9372

Epoch 010 | train_loss=0.1292 | ce=0.0531 | ent=0.0651 | center=0.7280 | val_loss=0.0736 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8971 | val_dqn_proxy_expanded5=0.9087

Epoch 011 | train_loss=0.1095 | ce=0.0370 | ent=0.0636 | center=0.6939 | val_loss=0.0560 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9242 | val_dqn_proxy_expanded5=0.9361

Epoch 012 | train_loss=0.1039 | ce=0.0341 | ent=0.0566 | center=0.6698 | val_loss=0.0441 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9296 | val_dqn_proxy_expanded5=0.9413

Epoch 013 | train_loss=0.0896 | ce=0.0231 | ent=0.0489 | center=0.6409 | val_loss=0.0519 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9654 | val_dqn_proxy_expanded5=0.9685

Epoch 014 | train_loss=0.0907 | ce=0.0285 | ent=0.0458 | center=0.5996 | val_loss=0.0412 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9449 | val_dqn_proxy_expanded5=0.9489

Epoch 015 | train_loss=0.0765 | ce=0.0178 | ent=0.0365 | center=0.5691 | val_loss=0.0467 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9716 | val_dqn_proxy_expanded5=0.9616

Epoch 016 | train_loss=0.0741 | ce=0.0184 | ent=0.0326 | center=0.5405 | val_loss=0.0395 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9528 | val_dqn_proxy_expanded5=0.9478

Epoch 017 | train_loss=0.0744 | ce=0.0205 | ent=0.0371 | center=0.5205 | val_loss=0.0487 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9530 | val_dqn_proxy_expanded5=0.9574

Epoch 018 | train_loss=0.0712 | ce=0.0195 | ent=0.0272 | center=0.5031 | val_loss=0.0420 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8683 | val_dqn_proxy_expanded5=0.8458

Epoch 019 | train_loss=0.0647 | ce=0.0165 | ent=0.0287 | center=0.4675 | val_loss=0.0505 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9739 | val_dqn_proxy_expanded5=0.9500

Epoch 020 | train_loss=0.0642 | ce=0.0186 | ent=0.0242 | center=0.4435 | val_loss=0.0390 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9267 | val_dqn_proxy_expanded5=0.9115

Epoch 021 | train_loss=0.0898 | ce=0.0449 | ent=0.0296 | center=0.4337 | val_loss=0.0513 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8862 | val_dqn_proxy_expanded5=0.8600

Epoch 022 | train_loss=0.0616 | ce=0.0188 | ent=0.0236 | center=0.4159 | val_loss=0.0414 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9203 | val_dqn_proxy_expanded5=0.8996

Epoch 023 | train_loss=0.0562 | ce=0.0148 | ent=0.0240 | center=0.4022 | val_loss=0.0512 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9647 | val_dqn_proxy_expanded5=0.9337

Epoch 024 | train_loss=0.0562 | ce=0.0165 | ent=0.0221 | center=0.3854 | val_loss=0.0473 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9689 | val_dqn_proxy_expanded5=0.9434

Epoch 025 | train_loss=0.0580 | ce=0.0196 | ent=0.0195 | center=0.3748 | val_loss=0.0364 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9066 | val_dqn_proxy_expanded5=0.8690

Epoch 026 | train_loss=0.0530 | ce=0.0159 | ent=0.0228 | center=0.3595 | val_loss=0.0370 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9258 | val_dqn_proxy_expanded5=0.9035

Epoch 027 | train_loss=0.0549 | ce=0.0185 | ent=0.0196 | center=0.3536 | val_loss=0.0407 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9462 | val_dqn_proxy_expanded5=0.9167

Epoch 028 | train_loss=0.0552 | ce=0.0197 | ent=0.0207 | center=0.3440 | val_loss=0.0396 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9427 | val_dqn_proxy_expanded5=0.9130

Epoch 029 | train_loss=0.0503 | ce=0.0159 | ent=0.0181 | center=0.3353 | val_loss=0.0382 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9251 | val_dqn_proxy_expanded5=0.9001

Epoch 030 | train_loss=0.0505 | ce=0.0167 | ent=0.0174 | center=0.3292 | val_loss=0.0435 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9615 | val_dqn_proxy_expanded5=0.9323

Epoch 031 | train_loss=0.0469 | ce=0.0142 | ent=0.0207 | center=0.3171 | val_loss=0.0492 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9472 | val_dqn_proxy_expanded5=0.9169

Epoch 032 | train_loss=0.0500 | ce=0.0177 | ent=0.0171 | center=0.3147 | val_loss=0.0435 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9168 | val_dqn_proxy_expanded5=0.8835

Epoch 033 | train_loss=0.0507 | ce=0.0191 | ent=0.0155 | center=0.3088 | val_loss=0.0457 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9437 | val_dqn_proxy_expanded5=0.9028

Epoch 034 | train_loss=0.0464 | ce=0.0155 | ent=0.0154 | center=0.3010 | val_loss=0.0388 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9455 | val_dqn_proxy_expanded5=0.9099
Early stopping at epoch 34 (best epoch: 19)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
11,confman_paperish_mild_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-46_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,confman_baseline_knownonly_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-26_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,confman_paperish_mid_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-52_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
19,confman_paperish_strong_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/17-10_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
25,confman_paperish_mid_lowdrop_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/17-25_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
27,confman_paperish_mid_lowdrop_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/17-32_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,confman_paperish_mild_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-39_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
5,confman_baseline_openconf_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-30_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,confman_baseline_openconf_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-28_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
15,confman_paperish_mid_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-59_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,confman_baseline_openconf_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-35_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
22,confman_paperish_mid_nocenter_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/17-19_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
14,confman_paperish_mid_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-57_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
17,confman_paperish_strong_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/17-04_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
23,confman_paperish_mid_nocenter_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/17-22_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
16,confman_paperish_strong_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/17-02_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
21,confman_paperish_mid_nocenter_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/17-16_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
18,confman_paperish_strong_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/17-08_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
8,confman_paperish_mild_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-37_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,confman_baseline_openconf_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-33_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
20,confman_paperish_mid_nocenter_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/17-13_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
10,confman_paperish_mild_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-43_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
26,confman_paperish_mid_lowdrop_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/17-30_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,confman_baseline_knownonly_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-19_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
24,confman_paperish_mid_lowdrop_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/17-23_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,confman_paperish_mid_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-48_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,confman_baseline_knownonly_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-21_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,confman_baseline_knownonly_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-24_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"

================================================================================
Running experiment 29/32
{
  "run_name": "confman_paperish_mid_smooth_unkPA2_c16384_seed0",
  "task": "pa",
  "split_mode": "open_pa",
  "unknown_pas": [
    "PA2"
  ],
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "lr": 0.0001,
  "weight_decay": 0.0001,
  "lambda_center": 0.1,
  "label_smoothing": 0.05,
  "entropy_loss_weight": 0.05,
  "mlp_dropout": 0.5,
  "class_weight_mode": null,
  "grad_clip_norm": 1.0,
  "scheduler_name": "plateau",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "epochs": 200,
  "early_stopping_patience": 15,
  "save_root": "results_pa_confmanifold_coarse"
}
================================================================================

Epoch 001 | train_loss=1.0150 | ce=0.8443 | ent=0.9732 | center=1.2202 | val_loss=0.4271 | val_acc=0.9185 | val_macro_f1=0.9170 | val_dqn_proxy_softmax3=0.6809 | val_dqn_proxy_expanded5=0.6861

Epoch 002 | train_loss=0.5408 | ce=0.3671 | ent=0.4693 | center=1.5025 | val_loss=0.1399 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6872 | val_dqn_proxy_expanded5=0.7273

Epoch 003 | train_loss=0.4445 | ce=0.2875 | ent=0.3088 | center=1.4156 | val_loss=0.1198 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7530 | val_dqn_proxy_expanded5=0.7925

Epoch 004 | train_loss=0.4126 | ce=0.2678 | ent=0.2849 | center=1.3059 | val_loss=0.1072 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8955 | val_dqn_proxy_expanded5=0.8938

Epoch 005 | train_loss=0.4083 | ce=0.2717 | ent=0.2833 | center=1.2238 | val_loss=0.1000 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6595 | val_dqn_proxy_expanded5=0.7271

Epoch 006 | train_loss=0.3745 | ce=0.2441 | ent=0.2445 | center=1.1816 | val_loss=0.0991 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6564 | val_dqn_proxy_expanded5=0.7366

Epoch 007 | train_loss=0.3713 | ce=0.2469 | ent=0.2483 | center=1.1197 | val_loss=0.0981 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6061 | val_dqn_proxy_expanded5=0.6927

Epoch 008 | train_loss=0.3693 | ce=0.2485 | ent=0.2483 | center=1.0837 | val_loss=0.0911 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6479 | val_dqn_proxy_expanded5=0.7010

Epoch 009 | train_loss=0.3698 | ce=0.2523 | ent=0.2499 | center=1.0503 | val_loss=0.0995 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7458 | val_dqn_proxy_expanded5=0.7376

Epoch 010 | train_loss=0.3578 | ce=0.2437 | ent=0.2427 | center=1.0202 | val_loss=0.0891 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8413 | val_dqn_proxy_expanded5=0.8486

Epoch 011 | train_loss=0.3591 | ce=0.2476 | ent=0.2425 | center=0.9942 | val_loss=0.0825 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7198 | val_dqn_proxy_expanded5=0.7312

Epoch 012 | train_loss=0.3436 | ce=0.2350 | ent=0.2285 | center=0.9722 | val_loss=0.0963 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7246 | val_dqn_proxy_expanded5=0.7331

Epoch 013 | train_loss=0.3474 | ce=0.2408 | ent=0.2259 | center=0.9525 | val_loss=0.0845 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8501 | val_dqn_proxy_expanded5=0.8601

Epoch 014 | train_loss=0.3385 | ce=0.2348 | ent=0.2206 | center=0.9267 | val_loss=0.0797 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7326 | val_dqn_proxy_expanded5=0.7259

Epoch 015 | train_loss=0.3342 | ce=0.2326 | ent=0.2214 | center=0.9054 | val_loss=0.0746 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6769 | val_dqn_proxy_expanded5=0.7263

Epoch 016 | train_loss=0.3231 | ce=0.2239 | ent=0.2166 | center=0.8834 | val_loss=0.0789 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7454 | val_dqn_proxy_expanded5=0.7912

Epoch 017 | train_loss=0.3210 | ce=0.2235 | ent=0.2102 | center=0.8700 | val_loss=0.0773 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6922 | val_dqn_proxy_expanded5=0.7155

Epoch 018 | train_loss=0.3177 | ce=0.2225 | ent=0.2062 | center=0.8493 | val_loss=0.0778 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7538 | val_dqn_proxy_expanded5=0.7548

Epoch 019 | train_loss=0.3113 | ce=0.2173 | ent=0.2102 | center=0.8349 | val_loss=0.0728 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6480 | val_dqn_proxy_expanded5=0.7103
Early stopping at epoch 19 (best epoch: 4)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
11,confman_paperish_mild_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-46_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,confman_baseline_knownonly_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-26_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,confman_paperish_mid_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-52_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
19,confman_paperish_strong_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/17-10_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
25,confman_paperish_mid_lowdrop_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/17-25_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
27,confman_paperish_mid_lowdrop_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/17-32_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,confman_paperish_mild_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-39_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
5,confman_baseline_openconf_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-30_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,confman_baseline_openconf_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-28_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
15,confman_paperish_mid_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-59_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,confman_baseline_openconf_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-35_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
22,confman_paperish_mid_nocenter_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/17-19_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
14,confman_paperish_mid_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-57_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
17,confman_paperish_strong_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/17-04_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
23,confman_paperish_mid_nocenter_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/17-22_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
16,confman_paperish_strong_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/17-02_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
21,confman_paperish_mid_nocenter_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/17-16_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
18,confman_paperish_strong_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/17-08_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
28,confman_paperish_mid_smooth_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/17-35_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
8,confman_paperish_mild_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-37_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,confman_baseline_openconf_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-33_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
20,confman_paperish_mid_nocenter_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/17-13_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
10,confman_paperish_mild_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-43_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
26,confman_paperish_mid_lowdrop_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/17-30_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,confman_baseline_knownonly_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-19_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
24,confman_paperish_mid_lowdrop_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/17-23_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,confman_paperish_mid_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-48_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,confman_baseline_knownonly_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-21_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,confman_baseline_knownonly_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-24_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"

================================================================================
Running experiment 30/32
{
  "run_name": "confman_paperish_mid_smooth_unkPA3_c16384_seed0",
  "task": "pa",
  "split_mode": "open_pa",
  "unknown_pas": [
    "PA3"
  ],
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "lr": 0.0001,
  "weight_decay": 0.0001,
  "lambda_center": 0.1,
  "label_smoothing": 0.05,
  "entropy_loss_weight": 0.05,
  "mlp_dropout": 0.5,
  "class_weight_mode": null,
  "grad_clip_norm": 1.0,
  "scheduler_name": "plateau",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "epochs": 200,
  "early_stopping_patience": 15,
  "save_root": "results_pa_confmanifold_coarse"
}
================================================================================

Epoch 001 | train_loss=1.0397 | ce=0.8817 | ent=1.0078 | center=1.0757 | val_loss=0.4647 | val_acc=0.7815 | val_macro_f1=0.7490 | val_dqn_proxy_softmax3=0.6842 | val_dqn_proxy_expanded5=0.7055

Epoch 002 | train_loss=0.5904 | ce=0.4226 | ent=0.5326 | center=1.4116 | val_loss=0.1777 | val_acc=0.9556 | val_macro_f1=0.9558 | val_dqn_proxy_softmax3=0.8093 | val_dqn_proxy_expanded5=0.8078

Epoch 003 | train_loss=0.5001 | ce=0.3438 | ent=0.4063 | center=1.3597 | val_loss=0.1921 | val_acc=0.9370 | val_macro_f1=0.9373 | val_dqn_proxy_softmax3=0.8317 | val_dqn_proxy_expanded5=0.8392

Epoch 004 | train_loss=0.4671 | ce=0.3243 | ent=0.3561 | center=1.2505 | val_loss=0.1422 | val_acc=0.9519 | val_macro_f1=0.9521 | val_dqn_proxy_softmax3=0.8019 | val_dqn_proxy_expanded5=0.8158

Epoch 005 | train_loss=0.4559 | ce=0.3208 | ent=0.3342 | center=1.1840 | val_loss=0.1250 | val_acc=0.9593 | val_macro_f1=0.9593 | val_dqn_proxy_softmax3=0.8687 | val_dqn_proxy_expanded5=0.8772

Epoch 006 | train_loss=0.4497 | ce=0.3204 | ent=0.3234 | center=1.1316 | val_loss=0.1175 | val_acc=0.9667 | val_macro_f1=0.9667 | val_dqn_proxy_softmax3=0.8612 | val_dqn_proxy_expanded5=0.8702

Epoch 007 | train_loss=0.4089 | ce=0.2831 | ent=0.3043 | center=1.1049 | val_loss=0.1290 | val_acc=0.9444 | val_macro_f1=0.9448 | val_dqn_proxy_softmax3=0.9537 | val_dqn_proxy_expanded5=0.9534

Epoch 008 | train_loss=0.3947 | ce=0.2734 | ent=0.2894 | center=1.0673 | val_loss=0.1549 | val_acc=0.9481 | val_macro_f1=0.9484 | val_dqn_proxy_softmax3=0.8414 | val_dqn_proxy_expanded5=0.8503

Epoch 009 | train_loss=0.3997 | ce=0.2817 | ent=0.2935 | center=1.0331 | val_loss=0.1007 | val_acc=0.9741 | val_macro_f1=0.9742 | val_dqn_proxy_softmax3=0.9449 | val_dqn_proxy_expanded5=0.9513

Epoch 010 | train_loss=0.3869 | ce=0.2719 | ent=0.2810 | center=1.0094 | val_loss=0.0969 | val_acc=0.9741 | val_macro_f1=0.9741 | val_dqn_proxy_softmax3=0.9592 | val_dqn_proxy_expanded5=0.9619

Epoch 011 | train_loss=0.3799 | ce=0.2676 | ent=0.2757 | center=0.9851 | val_loss=0.1113 | val_acc=0.9519 | val_macro_f1=0.9521 | val_dqn_proxy_softmax3=0.9457 | val_dqn_proxy_expanded5=0.9480

Epoch 012 | train_loss=0.3690 | ce=0.2597 | ent=0.2680 | center=0.9585 | val_loss=0.1015 | val_acc=0.9667 | val_macro_f1=0.9666 | val_dqn_proxy_softmax3=0.9482 | val_dqn_proxy_expanded5=0.9529

Epoch 013 | train_loss=0.3536 | ce=0.2476 | ent=0.2685 | center=0.9262 | val_loss=0.0711 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9744 | val_dqn_proxy_expanded5=0.9705

Epoch 014 | train_loss=0.3532 | ce=0.2493 | ent=0.2495 | center=0.9142 | val_loss=0.0708 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9560 | val_dqn_proxy_expanded5=0.9518

Epoch 015 | train_loss=0.3363 | ce=0.2349 | ent=0.2484 | center=0.8897 | val_loss=0.0743 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.9680 | val_dqn_proxy_expanded5=0.9533

Epoch 016 | train_loss=0.3449 | ce=0.2458 | ent=0.2451 | center=0.8684 | val_loss=0.0814 | val_acc=0.9741 | val_macro_f1=0.9741 | val_dqn_proxy_softmax3=0.9421 | val_dqn_proxy_expanded5=0.9403

Epoch 017 | train_loss=0.3407 | ce=0.2437 | ent=0.2404 | center=0.8500 | val_loss=0.0694 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9507 | val_dqn_proxy_expanded5=0.9533

Epoch 018 | train_loss=0.3263 | ce=0.2318 | ent=0.2421 | center=0.8243 | val_loss=0.0610 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9739 | val_dqn_proxy_expanded5=0.9657

Epoch 019 | train_loss=0.3304 | ce=0.2380 | ent=0.2317 | center=0.8081 | val_loss=0.0599 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9648 | val_dqn_proxy_expanded5=0.9616

Epoch 020 | train_loss=0.3180 | ce=0.2273 | ent=0.2269 | center=0.7932 | val_loss=0.0516 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9582 | val_dqn_proxy_expanded5=0.9577

Epoch 021 | train_loss=0.3159 | ce=0.2276 | ent=0.2163 | center=0.7752 | val_loss=0.0814 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9829 | val_dqn_proxy_expanded5=0.9764

Epoch 022 | train_loss=0.3098 | ce=0.2234 | ent=0.2205 | center=0.7534 | val_loss=0.0624 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9840 | val_dqn_proxy_expanded5=0.9832

Epoch 023 | train_loss=0.3275 | ce=0.2418 | ent=0.2291 | center=0.7418 | val_loss=0.0544 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9758 | val_dqn_proxy_expanded5=0.9472

Epoch 024 | train_loss=0.3053 | ce=0.2223 | ent=0.2201 | center=0.7195 | val_loss=0.0660 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9622 | val_dqn_proxy_expanded5=0.9635

Epoch 025 | train_loss=0.3076 | ce=0.2263 | ent=0.2104 | center=0.7081 | val_loss=0.0503 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9719 | val_dqn_proxy_expanded5=0.9606

Epoch 026 | train_loss=0.2957 | ce=0.2160 | ent=0.2140 | center=0.6901 | val_loss=0.0761 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9133 | val_dqn_proxy_expanded5=0.8789

Epoch 027 | train_loss=0.2986 | ce=0.2205 | ent=0.2075 | center=0.6769 | val_loss=0.0722 | val_acc=0.9741 | val_macro_f1=0.9740 | val_dqn_proxy_softmax3=0.9634 | val_dqn_proxy_expanded5=0.9464

Epoch 028 | train_loss=0.2985 | ce=0.2217 | ent=0.2068 | center=0.6642 | val_loss=0.0436 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9488 | val_dqn_proxy_expanded5=0.9263

Epoch 029 | train_loss=0.2944 | ce=0.2189 | ent=0.2059 | center=0.6521 | val_loss=0.0733 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9585 | val_dqn_proxy_expanded5=0.9553

Epoch 030 | train_loss=0.2909 | ce=0.2166 | ent=0.2074 | center=0.6396 | val_loss=0.0670 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.9694 | val_dqn_proxy_expanded5=0.9462

Epoch 031 | train_loss=0.2858 | ce=0.2135 | ent=0.1990 | center=0.6240 | val_loss=0.0432 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9694 | val_dqn_proxy_expanded5=0.9226

Epoch 032 | train_loss=0.2847 | ce=0.2138 | ent=0.1987 | center=0.6094 | val_loss=0.0974 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.9640 | val_dqn_proxy_expanded5=0.9389

Epoch 033 | train_loss=0.2941 | ce=0.2240 | ent=0.2003 | center=0.6005 | val_loss=0.0489 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8993 | val_dqn_proxy_expanded5=0.8584

Epoch 034 | train_loss=0.2841 | ce=0.2156 | ent=0.1995 | center=0.5845 | val_loss=0.0760 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.9851 | val_dqn_proxy_expanded5=0.9691

Epoch 035 | train_loss=0.2911 | ce=0.2236 | ent=0.1999 | center=0.5750 | val_loss=0.0771 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.9565 | val_dqn_proxy_expanded5=0.8977

Epoch 036 | train_loss=0.2833 | ce=0.2171 | ent=0.2002 | center=0.5619 | val_loss=0.0378 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9799 | val_dqn_proxy_expanded5=0.9437

Epoch 037 | train_loss=0.2762 | ce=0.2116 | ent=0.1938 | center=0.5496 | val_loss=0.1024 | val_acc=0.9741 | val_macro_f1=0.9740 | val_dqn_proxy_softmax3=0.9393 | val_dqn_proxy_expanded5=0.9187

Epoch 038 | train_loss=0.2771 | ce=0.2129 | ent=0.2010 | center=0.5410 | val_loss=0.0611 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9715 | val_dqn_proxy_expanded5=0.9273

Epoch 039 | train_loss=0.2706 | ce=0.2081 | ent=0.1864 | center=0.5325 | val_loss=0.0405 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9793 | val_dqn_proxy_expanded5=0.9403

Epoch 040 | train_loss=0.2684 | ce=0.2069 | ent=0.1911 | center=0.5195 | val_loss=0.0480 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9695 | val_dqn_proxy_expanded5=0.9369

Epoch 041 | train_loss=0.2632 | ce=0.2029 | ent=0.1881 | center=0.5087 | val_loss=0.0628 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9741 | val_dqn_proxy_expanded5=0.9237

Epoch 042 | train_loss=0.2613 | ce=0.2025 | ent=0.1828 | center=0.4958 | val_loss=0.0438 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9545 | val_dqn_proxy_expanded5=0.9277

Epoch 043 | train_loss=0.2585 | ce=0.2005 | ent=0.1834 | center=0.4886 | val_loss=0.0405 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9682 | val_dqn_proxy_expanded5=0.9134

Epoch 044 | train_loss=0.2538 | ce=0.1965 | ent=0.1827 | center=0.4824 | val_loss=0.0601 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9702 | val_dqn_proxy_expanded5=0.9353

Epoch 045 | train_loss=0.2494 | ce=0.1928 | ent=0.1763 | center=0.4778 | val_loss=0.0494 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9701 | val_dqn_proxy_expanded5=0.9240

Epoch 046 | train_loss=0.2527 | ce=0.1966 | ent=0.1788 | center=0.4717 | val_loss=0.0452 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9807 | val_dqn_proxy_expanded5=0.9493

Epoch 047 | train_loss=0.2493 | ce=0.1936 | ent=0.1777 | center=0.4676 | val_loss=0.0405 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9798 | val_dqn_proxy_expanded5=0.9401

Epoch 048 | train_loss=0.2536 | ce=0.1981 | ent=0.1837 | center=0.4635 | val_loss=0.0420 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9854 | val_dqn_proxy_expanded5=0.9338

Epoch 049 | train_loss=0.2487 | ce=0.1940 | ent=0.1745 | center=0.4589 | val_loss=0.0456 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9821 | val_dqn_proxy_expanded5=0.9427

Epoch 050 | train_loss=0.2476 | ce=0.1933 | ent=0.1778 | center=0.4537 | val_loss=0.0378 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9819 | val_dqn_proxy_expanded5=0.9428

Epoch 051 | train_loss=0.2535 | ce=0.1993 | ent=0.1760 | center=0.4539 | val_loss=0.0390 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9892 | val_dqn_proxy_expanded5=0.9330

Epoch 052 | train_loss=0.2475 | ce=0.1935 | ent=0.1785 | center=0.4510 | val_loss=0.0393 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9764 | val_dqn_proxy_expanded5=0.9285

Epoch 053 | train_loss=0.2509 | ce=0.1970 | ent=0.1774 | center=0.4499 | val_loss=0.0386 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9878 | val_dqn_proxy_expanded5=0.9473

Epoch 054 | train_loss=0.2512 | ce=0.1977 | ent=0.1764 | center=0.4474 | val_loss=0.0338 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9874 | val_dqn_proxy_expanded5=0.9468

Epoch 055 | train_loss=0.2529 | ce=0.1997 | ent=0.1713 | center=0.4457 | val_loss=0.0364 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9874 | val_dqn_proxy_expanded5=0.9424

Epoch 056 | train_loss=0.2455 | ce=0.1924 | ent=0.1764 | center=0.4430 | val_loss=0.0474 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9743 | val_dqn_proxy_expanded5=0.9444

Epoch 057 | train_loss=0.2437 | ce=0.1910 | ent=0.1779 | center=0.4384 | val_loss=0.0432 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9732 | val_dqn_proxy_expanded5=0.9368

Epoch 058 | train_loss=0.2461 | ce=0.1936 | ent=0.1754 | center=0.4376 | val_loss=0.0307 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9897 | val_dqn_proxy_expanded5=0.9500

Epoch 059 | train_loss=0.2511 | ce=0.1987 | ent=0.1789 | center=0.4341 | val_loss=0.0377 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9858 | val_dqn_proxy_expanded5=0.9384

Epoch 060 | train_loss=0.2477 | ce=0.1955 | ent=0.1756 | center=0.4341 | val_loss=0.0373 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9896 | val_dqn_proxy_expanded5=0.9548

Epoch 061 | train_loss=0.2399 | ce=0.1881 | ent=0.1734 | center=0.4304 | val_loss=0.0345 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9940 | val_dqn_proxy_expanded5=0.9519

Epoch 062 | train_loss=0.2451 | ce=0.1935 | ent=0.1769 | center=0.4277 | val_loss=0.0336 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9846 | val_dqn_proxy_expanded5=0.9365

Epoch 063 | train_loss=0.2445 | ce=0.1931 | ent=0.1768 | center=0.4257 | val_loss=0.0389 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9833 | val_dqn_proxy_expanded5=0.9457

Epoch 064 | train_loss=0.2436 | ce=0.1929 | ent=0.1712 | center=0.4220 | val_loss=0.0343 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9871 | val_dqn_proxy_expanded5=0.9320

Epoch 065 | train_loss=0.2504 | ce=0.1993 | ent=0.1787 | center=0.4216 | val_loss=0.0349 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9871 | val_dqn_proxy_expanded5=0.9453

Epoch 066 | train_loss=0.2476 | ce=0.1970 | ent=0.1678 | center=0.4216 | val_loss=0.0360 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9917 | val_dqn_proxy_expanded5=0.9578

Epoch 067 | train_loss=0.2417 | ce=0.1912 | ent=0.1718 | center=0.4190 | val_loss=0.0356 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9886 | val_dqn_proxy_expanded5=0.9468

Epoch 068 | train_loss=0.2397 | ce=0.1892 | ent=0.1736 | center=0.4185 | val_loss=0.0366 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9811 | val_dqn_proxy_expanded5=0.9403

Epoch 069 | train_loss=0.2402 | ce=0.1901 | ent=0.1726 | center=0.4151 | val_loss=0.0340 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9898 | val_dqn_proxy_expanded5=0.9404

Epoch 070 | train_loss=0.2432 | ce=0.1931 | ent=0.1761 | center=0.4134 | val_loss=0.0391 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9842 | val_dqn_proxy_expanded5=0.9463

Epoch 071 | train_loss=0.2435 | ce=0.1931 | ent=0.1752 | center=0.4163 | val_loss=0.0362 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9889 | val_dqn_proxy_expanded5=0.9491

Epoch 072 | train_loss=0.2443 | ce=0.1943 | ent=0.1730 | center=0.4135 | val_loss=0.0351 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9869 | val_dqn_proxy_expanded5=0.9510

Epoch 073 | train_loss=0.2412 | ce=0.1909 | ent=0.1764 | center=0.4146 | val_loss=0.0302 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9903 | val_dqn_proxy_expanded5=0.9484

Epoch 074 | train_loss=0.2383 | ce=0.1885 | ent=0.1701 | center=0.4129 | val_loss=0.0326 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9875 | val_dqn_proxy_expanded5=0.9393

Epoch 075 | train_loss=0.2411 | ce=0.1910 | ent=0.1722 | center=0.4145 | val_loss=0.0315 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9922 | val_dqn_proxy_expanded5=0.9450

Epoch 076 | train_loss=0.2401 | ce=0.1902 | ent=0.1718 | center=0.4122 | val_loss=0.0309 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9875 | val_dqn_proxy_expanded5=0.9436
Early stopping at epoch 76 (best epoch: 61)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
11,confman_paperish_mild_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-46_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,confman_baseline_knownonly_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-26_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,confman_paperish_mid_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-52_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
19,confman_paperish_strong_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/17-10_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
25,confman_paperish_mid_lowdrop_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/17-25_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
27,confman_paperish_mid_lowdrop_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/17-32_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,confman_paperish_mild_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-39_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
5,confman_baseline_openconf_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-30_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
29,confman_paperish_mid_smooth_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/17-37_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
4,confman_baseline_openconf_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-28_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
15,confman_paperish_mid_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-59_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,confman_baseline_openconf_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-35_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
22,confman_paperish_mid_nocenter_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/17-19_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
14,confman_paperish_mid_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-57_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
17,confman_paperish_strong_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/17-04_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
23,confman_paperish_mid_nocenter_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/17-22_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
16,confman_paperish_strong_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/17-02_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
21,confman_paperish_mid_nocenter_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/17-16_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
18,confman_paperish_strong_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/17-08_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
28,confman_paperish_mid_smooth_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/17-35_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
8,confman_paperish_mild_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-37_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,confman_baseline_openconf_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-33_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
20,confman_paperish_mid_nocenter_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/17-13_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
10,confman_paperish_mild_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-43_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
26,confman_paperish_mid_lowdrop_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/17-30_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,confman_baseline_knownonly_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-19_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
24,confman_paperish_mid_lowdrop_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/17-23_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,confman_paperish_mid_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-48_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,confman_baseline_knownonly_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-21_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,confman_baseline_knownonly_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-24_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"

================================================================================
Running experiment 31/32
{
  "run_name": "confman_paperish_mid_smooth_unkPA4_c16384_seed0",
  "task": "pa",
  "split_mode": "open_pa",
  "unknown_pas": [
    "PA4"
  ],
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "lr": 0.0001,
  "weight_decay": 0.0001,
  "lambda_center": 0.1,
  "label_smoothing": 0.05,
  "entropy_loss_weight": 0.05,
  "mlp_dropout": 0.5,
  "class_weight_mode": null,
  "grad_clip_norm": 1.0,
  "scheduler_name": "plateau",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "epochs": 200,
  "early_stopping_patience": 15,
  "save_root": "results_pa_confmanifold_coarse"
}
================================================================================

Epoch 001 | train_loss=1.0458 | ce=0.8928 | ent=1.0053 | center=1.0273 | val_loss=0.4900 | val_acc=0.7889 | val_macro_f1=0.7593 | val_dqn_proxy_softmax3=0.6412 | val_dqn_proxy_expanded5=0.6433

Epoch 002 | train_loss=0.6677 | ce=0.4994 | ent=0.5786 | center=1.3939 | val_loss=0.2898 | val_acc=0.9148 | val_macro_f1=0.9141 | val_dqn_proxy_softmax3=0.7267 | val_dqn_proxy_expanded5=0.7421

Epoch 003 | train_loss=0.5328 | ce=0.3796 | ent=0.4474 | center=1.3082 | val_loss=0.2058 | val_acc=0.9556 | val_macro_f1=0.9556 | val_dqn_proxy_softmax3=0.7392 | val_dqn_proxy_expanded5=0.7708

Epoch 004 | train_loss=0.4887 | ce=0.3487 | ent=0.3866 | center=1.2066 | val_loss=0.1910 | val_acc=0.9519 | val_macro_f1=0.9519 | val_dqn_proxy_softmax3=0.7406 | val_dqn_proxy_expanded5=0.7701

Epoch 005 | train_loss=0.4702 | ce=0.3377 | ent=0.3552 | center=1.1472 | val_loss=0.2342 | val_acc=0.9148 | val_macro_f1=0.9145 | val_dqn_proxy_softmax3=0.7237 | val_dqn_proxy_expanded5=0.7381

Epoch 006 | train_loss=0.4447 | ce=0.3183 | ent=0.3261 | center=1.1012 | val_loss=0.1804 | val_acc=0.9444 | val_macro_f1=0.9446 | val_dqn_proxy_softmax3=0.7329 | val_dqn_proxy_expanded5=0.7101

Epoch 007 | train_loss=0.4041 | ce=0.2833 | ent=0.3033 | center=1.0564 | val_loss=0.1405 | val_acc=0.9630 | val_macro_f1=0.9629 | val_dqn_proxy_softmax3=0.7644 | val_dqn_proxy_expanded5=0.7368

Epoch 008 | train_loss=0.3936 | ce=0.2762 | ent=0.2883 | center=1.0296 | val_loss=0.2090 | val_acc=0.9333 | val_macro_f1=0.9329 | val_dqn_proxy_softmax3=0.7529 | val_dqn_proxy_expanded5=0.7534

Epoch 009 | train_loss=0.3839 | ce=0.2704 | ent=0.2821 | center=0.9945 | val_loss=0.1165 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.7642 | val_dqn_proxy_expanded5=0.7378

Epoch 010 | train_loss=0.3728 | ce=0.2622 | ent=0.2761 | center=0.9679 | val_loss=0.1395 | val_acc=0.9593 | val_macro_f1=0.9592 | val_dqn_proxy_softmax3=0.7632 | val_dqn_proxy_expanded5=0.7381

Epoch 011 | train_loss=0.3686 | ce=0.2613 | ent=0.2539 | center=0.9464 | val_loss=0.1186 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.7578 | val_dqn_proxy_expanded5=0.7364

Epoch 012 | train_loss=0.3524 | ce=0.2482 | ent=0.2573 | center=0.9129 | val_loss=0.1370 | val_acc=0.9556 | val_macro_f1=0.9557 | val_dqn_proxy_softmax3=0.7551 | val_dqn_proxy_expanded5=0.7327

Epoch 013 | train_loss=0.3497 | ce=0.2474 | ent=0.2410 | center=0.9022 | val_loss=0.1027 | val_acc=0.9741 | val_macro_f1=0.9741 | val_dqn_proxy_softmax3=0.7554 | val_dqn_proxy_expanded5=0.7288

Epoch 014 | train_loss=0.3387 | ce=0.2406 | ent=0.2483 | center=0.8566 | val_loss=0.0949 | val_acc=0.9741 | val_macro_f1=0.9741 | val_dqn_proxy_softmax3=0.8318 | val_dqn_proxy_expanded5=0.7783

Epoch 015 | train_loss=0.3370 | ce=0.2408 | ent=0.2414 | center=0.8418 | val_loss=0.1089 | val_acc=0.9630 | val_macro_f1=0.9630 | val_dqn_proxy_softmax3=0.9048 | val_dqn_proxy_expanded5=0.8264

Epoch 016 | train_loss=0.3235 | ce=0.2299 | ent=0.2441 | center=0.8147 | val_loss=0.0671 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9475 | val_dqn_proxy_expanded5=0.8866

Epoch 017 | train_loss=0.3174 | ce=0.2262 | ent=0.2299 | center=0.7973 | val_loss=0.0878 | val_acc=0.9741 | val_macro_f1=0.9743 | val_dqn_proxy_softmax3=0.9292 | val_dqn_proxy_expanded5=0.8953

Epoch 018 | train_loss=0.3150 | ce=0.2256 | ent=0.2295 | center=0.7796 | val_loss=0.0533 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9495 | val_dqn_proxy_expanded5=0.9169

Epoch 019 | train_loss=0.3054 | ce=0.2182 | ent=0.2210 | center=0.7613 | val_loss=0.0877 | val_acc=0.9741 | val_macro_f1=0.9740 | val_dqn_proxy_softmax3=0.9496 | val_dqn_proxy_expanded5=0.9183

Epoch 020 | train_loss=0.3107 | ce=0.2255 | ent=0.2208 | center=0.7416 | val_loss=0.1131 | val_acc=0.9704 | val_macro_f1=0.9703 | val_dqn_proxy_softmax3=0.9462 | val_dqn_proxy_expanded5=0.9155

Epoch 021 | train_loss=0.2975 | ce=0.2146 | ent=0.2133 | center=0.7230 | val_loss=0.0774 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9549 | val_dqn_proxy_expanded5=0.8908

Epoch 022 | train_loss=0.3016 | ce=0.2196 | ent=0.2174 | center=0.7118 | val_loss=0.0652 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.9399 | val_dqn_proxy_expanded5=0.8783

Epoch 023 | train_loss=0.2969 | ce=0.2166 | ent=0.2094 | center=0.6981 | val_loss=0.0696 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.8636 | val_dqn_proxy_expanded5=0.8012

Epoch 024 | train_loss=0.2978 | ce=0.2194 | ent=0.2166 | center=0.6758 | val_loss=0.0838 | val_acc=0.9704 | val_macro_f1=0.9703 | val_dqn_proxy_softmax3=0.9068 | val_dqn_proxy_expanded5=0.8368

Epoch 025 | train_loss=0.2846 | ce=0.2079 | ent=0.2004 | center=0.6672 | val_loss=0.0497 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9535 | val_dqn_proxy_expanded5=0.8613

Epoch 026 | train_loss=0.2784 | ce=0.2028 | ent=0.1989 | center=0.6559 | val_loss=0.0448 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9629 | val_dqn_proxy_expanded5=0.8699

Epoch 027 | train_loss=0.2808 | ce=0.2057 | ent=0.1988 | center=0.6510 | val_loss=0.0563 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9209 | val_dqn_proxy_expanded5=0.8392

Epoch 028 | train_loss=0.2782 | ce=0.2039 | ent=0.2033 | center=0.6413 | val_loss=0.0398 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9656 | val_dqn_proxy_expanded5=0.8784

Epoch 029 | train_loss=0.2785 | ce=0.2048 | ent=0.2012 | center=0.6359 | val_loss=0.0402 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9374 | val_dqn_proxy_expanded5=0.8562

Epoch 030 | train_loss=0.2821 | ce=0.2096 | ent=0.1980 | center=0.6263 | val_loss=0.0522 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.8692 | val_dqn_proxy_expanded5=0.8068

Epoch 031 | train_loss=0.2805 | ce=0.2083 | ent=0.1974 | center=0.6236 | val_loss=0.0410 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9080 | val_dqn_proxy_expanded5=0.8330

Epoch 032 | train_loss=0.2760 | ce=0.2049 | ent=0.1992 | center=0.6123 | val_loss=0.0529 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.8949 | val_dqn_proxy_expanded5=0.8237

Epoch 033 | train_loss=0.2708 | ce=0.2004 | ent=0.1941 | center=0.6071 | val_loss=0.0392 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.8746 | val_dqn_proxy_expanded5=0.8126

Epoch 034 | train_loss=0.2669 | ce=0.1975 | ent=0.1914 | center=0.5978 | val_loss=0.0462 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.7946 | val_dqn_proxy_expanded5=0.7630

Epoch 035 | train_loss=0.2761 | ce=0.2070 | ent=0.1941 | center=0.5940 | val_loss=0.0481 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.7928 | val_dqn_proxy_expanded5=0.7571

Epoch 036 | train_loss=0.2680 | ce=0.1996 | ent=0.1950 | center=0.5865 | val_loss=0.0613 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7990 | val_dqn_proxy_expanded5=0.7622

Epoch 037 | train_loss=0.2694 | ce=0.2017 | ent=0.1842 | center=0.5843 | val_loss=0.0432 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.7898 | val_dqn_proxy_expanded5=0.7597

Epoch 038 | train_loss=0.2652 | ce=0.1985 | ent=0.1876 | center=0.5735 | val_loss=0.0435 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.7988 | val_dqn_proxy_expanded5=0.7701

Epoch 039 | train_loss=0.2683 | ce=0.2022 | ent=0.1859 | center=0.5677 | val_loss=0.0420 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.7889 | val_dqn_proxy_expanded5=0.7654

Epoch 040 | train_loss=0.2594 | ce=0.1936 | ent=0.1903 | center=0.5637 | val_loss=0.0442 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.7946 | val_dqn_proxy_expanded5=0.7594

Epoch 041 | train_loss=0.2613 | ce=0.1961 | ent=0.1839 | center=0.5603 | val_loss=0.0359 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.7947 | val_dqn_proxy_expanded5=0.7636

Epoch 042 | train_loss=0.2644 | ce=0.1993 | ent=0.1878 | center=0.5575 | val_loss=0.0373 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.8076 | val_dqn_proxy_expanded5=0.7711

Epoch 043 | train_loss=0.2635 | ce=0.1988 | ent=0.1861 | center=0.5541 | val_loss=0.0401 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.7923 | val_dqn_proxy_expanded5=0.7621
Early stopping at epoch 43 (best epoch: 28)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
11,confman_paperish_mild_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-46_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,confman_baseline_knownonly_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-26_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,confman_paperish_mid_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-52_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
19,confman_paperish_strong_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/17-10_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
25,confman_paperish_mid_lowdrop_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/17-25_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
27,confman_paperish_mid_lowdrop_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/17-32_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,confman_paperish_mild_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-39_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
5,confman_baseline_openconf_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-30_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
29,confman_paperish_mid_smooth_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/17-37_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
4,confman_baseline_openconf_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-28_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
15,confman_paperish_mid_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-59_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,confman_baseline_openconf_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-35_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
22,confman_paperish_mid_nocenter_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/17-19_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
14,confman_paperish_mid_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-57_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
17,confman_paperish_strong_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/17-04_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
23,confman_paperish_mid_nocenter_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/17-22_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
16,confman_paperish_strong_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/17-02_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
21,confman_paperish_mid_nocenter_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/17-16_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
18,confman_paperish_strong_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/17-08_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
28,confman_paperish_mid_smooth_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/17-35_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
8,confman_paperish_mild_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-37_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,confman_baseline_openconf_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-33_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
30,confman_paperish_mid_smooth_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/17-43_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
20,confman_paperish_mid_nocenter_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/17-13_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
10,confman_paperish_mild_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-43_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
26,confman_paperish_mid_lowdrop_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/17-30_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,confman_baseline_knownonly_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-19_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
24,confman_paperish_mid_lowdrop_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/17-23_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,confman_paperish_mid_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-48_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,confman_baseline_knownonly_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-21_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,confman_baseline_knownonly_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-24_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"

================================================================================
Running experiment 32/32
{
  "run_name": "confman_paperish_mid_smooth_unkPA8_c16384_seed0",
  "task": "pa",
  "split_mode": "open_pa",
  "unknown_pas": [
    "PA8"
  ],
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "lr": 0.0001,
  "weight_decay": 0.0001,
  "lambda_center": 0.1,
  "label_smoothing": 0.05,
  "entropy_loss_weight": 0.05,
  "mlp_dropout": 0.5,
  "class_weight_mode": null,
  "grad_clip_norm": 1.0,
  "scheduler_name": "plateau",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "epochs": 200,
  "early_stopping_patience": 15,
  "save_root": "results_pa_confmanifold_coarse"
}
================================================================================

Epoch 001 | train_loss=0.9598 | ce=0.8087 | ent=0.9671 | center=1.0272 | val_loss=0.2512 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8483 | val_dqn_proxy_expanded5=0.8296

Epoch 002 | train_loss=0.4317 | ce=0.2860 | ent=0.3643 | center=1.2749 | val_loss=0.1226 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9501 | val_dqn_proxy_expanded5=0.9101

Epoch 003 | train_loss=0.3748 | ce=0.2487 | ent=0.2667 | center=1.1271 | val_loss=0.1128 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9030 | val_dqn_proxy_expanded5=0.8875

Epoch 004 | train_loss=0.3464 | ce=0.2312 | ent=0.2360 | center=1.0340 | val_loss=0.1111 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9036 | val_dqn_proxy_expanded5=0.8893

Epoch 005 | train_loss=0.3397 | ce=0.2317 | ent=0.2330 | center=0.9633 | val_loss=0.1117 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9345 | val_dqn_proxy_expanded5=0.9370

Epoch 006 | train_loss=0.3270 | ce=0.2242 | ent=0.2229 | center=0.9169 | val_loss=0.1036 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9444 | val_dqn_proxy_expanded5=0.9514

Epoch 007 | train_loss=0.3246 | ce=0.2255 | ent=0.2196 | center=0.8812 | val_loss=0.1072 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9349 | val_dqn_proxy_expanded5=0.9422

Epoch 008 | train_loss=0.3188 | ce=0.2238 | ent=0.2172 | center=0.8413 | val_loss=0.0990 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9580 | val_dqn_proxy_expanded5=0.9627

Epoch 009 | train_loss=0.3130 | ce=0.2209 | ent=0.2081 | center=0.8166 | val_loss=0.1019 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9392 | val_dqn_proxy_expanded5=0.9440

Epoch 010 | train_loss=0.3073 | ce=0.2179 | ent=0.2066 | center=0.7908 | val_loss=0.0955 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9535 | val_dqn_proxy_expanded5=0.9586

Epoch 011 | train_loss=0.3069 | ce=0.2198 | ent=0.2067 | center=0.7677 | val_loss=0.0927 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9307 | val_dqn_proxy_expanded5=0.9363

Epoch 012 | train_loss=0.3013 | ce=0.2164 | ent=0.2046 | center=0.7470 | val_loss=0.0923 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9419 | val_dqn_proxy_expanded5=0.9511

Epoch 013 | train_loss=0.2977 | ce=0.2149 | ent=0.1990 | center=0.7285 | val_loss=0.0904 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9345 | val_dqn_proxy_expanded5=0.9438

Epoch 014 | train_loss=0.2907 | ce=0.2099 | ent=0.2001 | center=0.7079 | val_loss=0.0787 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9307 | val_dqn_proxy_expanded5=0.9404

Epoch 015 | train_loss=0.2867 | ce=0.2069 | ent=0.1994 | center=0.6989 | val_loss=0.0692 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9403 | val_dqn_proxy_expanded5=0.9521

Epoch 016 | train_loss=0.2774 | ce=0.1993 | ent=0.1930 | center=0.6851 | val_loss=0.0672 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9746 | val_dqn_proxy_expanded5=0.9730

Epoch 017 | train_loss=0.2731 | ce=0.1968 | ent=0.1916 | center=0.6673 | val_loss=0.0527 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9356 | val_dqn_proxy_expanded5=0.9472

Epoch 018 | train_loss=0.2675 | ce=0.1928 | ent=0.1839 | center=0.6549 | val_loss=0.0653 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9804 | val_dqn_proxy_expanded5=0.9812

Epoch 019 | train_loss=0.2692 | ce=0.1957 | ent=0.1851 | center=0.6424 | val_loss=0.0606 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9782 | val_dqn_proxy_expanded5=0.9750

Epoch 020 | train_loss=0.2614 | ce=0.1902 | ent=0.1831 | center=0.6200 | val_loss=0.0601 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9442 | val_dqn_proxy_expanded5=0.9535

Epoch 021 | train_loss=0.2607 | ce=0.1910 | ent=0.1748 | center=0.6095 | val_loss=0.0590 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9260 | val_dqn_proxy_expanded5=0.9392

Epoch 022 | train_loss=0.2584 | ce=0.1899 | ent=0.1773 | center=0.5963 | val_loss=0.0550 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9649 | val_dqn_proxy_expanded5=0.9710

Epoch 023 | train_loss=0.2594 | ce=0.1923 | ent=0.1752 | center=0.5825 | val_loss=0.0523 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9525 | val_dqn_proxy_expanded5=0.9619

Epoch 024 | train_loss=0.2543 | ce=0.1886 | ent=0.1721 | center=0.5709 | val_loss=0.0581 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9638 | val_dqn_proxy_expanded5=0.9699

Epoch 025 | train_loss=0.2531 | ce=0.1887 | ent=0.1717 | center=0.5580 | val_loss=0.0584 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9003 | val_dqn_proxy_expanded5=0.9166

Epoch 026 | train_loss=0.2536 | ce=0.1901 | ent=0.1765 | center=0.5476 | val_loss=0.0557 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9660 | val_dqn_proxy_expanded5=0.9712

Epoch 027 | train_loss=0.2516 | ce=0.1896 | ent=0.1711 | center=0.5351 | val_loss=0.0563 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9730 | val_dqn_proxy_expanded5=0.9766

Epoch 028 | train_loss=0.2510 | ce=0.1899 | ent=0.1715 | center=0.5247 | val_loss=0.0587 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9841 | val_dqn_proxy_expanded5=0.9843

Epoch 029 | train_loss=0.2489 | ce=0.1892 | ent=0.1659 | center=0.5136 | val_loss=0.0532 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9743 | val_dqn_proxy_expanded5=0.9779

Epoch 030 | train_loss=0.2480 | ce=0.1891 | ent=0.1720 | center=0.5030 | val_loss=0.0590 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9770 | val_dqn_proxy_expanded5=0.9805

Epoch 031 | train_loss=0.2462 | ce=0.1879 | ent=0.1682 | center=0.4988 | val_loss=0.0588 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9511 | val_dqn_proxy_expanded5=0.9612

Epoch 032 | train_loss=0.2444 | ce=0.1867 | ent=0.1686 | center=0.4923 | val_loss=0.0557 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9426 | val_dqn_proxy_expanded5=0.9528

Epoch 033 | train_loss=0.2461 | ce=0.1889 | ent=0.1691 | center=0.4878 | val_loss=0.0555 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9656 | val_dqn_proxy_expanded5=0.9712

Epoch 034 | train_loss=0.2448 | ce=0.1882 | ent=0.1649 | center=0.4833 | val_loss=0.0571 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9509 | val_dqn_proxy_expanded5=0.9586

Epoch 035 | train_loss=0.2441 | ce=0.1882 | ent=0.1673 | center=0.4754 | val_loss=0.0597 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9703 | val_dqn_proxy_expanded5=0.9744

Epoch 036 | train_loss=0.2434 | ce=0.1875 | ent=0.1716 | center=0.4738 | val_loss=0.0575 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9358 | val_dqn_proxy_expanded5=0.9465

Epoch 037 | train_loss=0.2426 | ce=0.1873 | ent=0.1654 | center=0.4707 | val_loss=0.0562 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9506 | val_dqn_proxy_expanded5=0.9585

Epoch 038 | train_loss=0.2422 | ce=0.1871 | ent=0.1662 | center=0.4678 | val_loss=0.0555 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9312 | val_dqn_proxy_expanded5=0.9417

Epoch 039 | train_loss=0.2419 | ce=0.1871 | ent=0.1643 | center=0.4651 | val_loss=0.0585 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9396 | val_dqn_proxy_expanded5=0.9460

Epoch 040 | train_loss=0.2402 | ce=0.1857 | ent=0.1689 | center=0.4608 | val_loss=0.0557 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9401 | val_dqn_proxy_expanded5=0.9508

Epoch 041 | train_loss=0.2404 | ce=0.1862 | ent=0.1654 | center=0.4592 | val_loss=0.0581 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9295 | val_dqn_proxy_expanded5=0.9393

Epoch 042 | train_loss=0.2412 | ce=0.1869 | ent=0.1726 | center=0.4564 | val_loss=0.0542 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9376 | val_dqn_proxy_expanded5=0.9486

Epoch 043 | train_loss=0.2423 | ce=0.1884 | ent=0.1638 | center=0.4571 | val_loss=0.0563 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9403 | val_dqn_proxy_expanded5=0.9484
Early stopping at epoch 43 (best epoch: 28)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
31,confman_paperish_mid_smooth_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/17-46_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
11,confman_paperish_mild_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-46_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,confman_baseline_knownonly_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-26_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,confman_paperish_mid_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-52_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
19,confman_paperish_strong_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/17-10_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
25,confman_paperish_mid_lowdrop_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/17-25_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
27,confman_paperish_mid_lowdrop_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/17-32_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,confman_paperish_mild_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-39_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
5,confman_baseline_openconf_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-30_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
29,confman_paperish_mid_smooth_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/17-37_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
4,confman_baseline_openconf_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-28_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
15,confman_paperish_mid_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-59_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,confman_baseline_openconf_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/16-35_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
22,confman_paperish_mid_nocenter_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/17-19_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
14,confman_paperish_mid_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-57_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
17,confman_paperish_strong_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/17-04_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
23,confman_paperish_mid_nocenter_unkPA8_c16384_seed0,results_pa_confmanifold_coarse/17-22_04-29-26_...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
16,confman_paperish_strong_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/17-02_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
21,confman_paperish_mid_nocenter_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/17-16_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
18,confman_paperish_strong_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/17-08_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
28,confman_paperish_mid_smooth_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/17-35_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
8,confman_paperish_mild_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-37_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,confman_baseline_openconf_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-33_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
30,confman_paperish_mid_smooth_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/17-43_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
20,confman_paperish_mid_nocenter_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/17-13_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
10,confman_paperish_mild_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-43_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
26,confman_paperish_mid_lowdrop_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/17-30_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,confman_baseline_knownonly_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-19_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
24,confman_paperish_mid_lowdrop_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/17-23_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,confman_paperish_mid_unkPA2_c16384_seed0,results_pa_confmanifold_coarse/16-48_04-29-26_...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,confman_baseline_knownonly_unkPA3_c16384_seed0,results_pa_confmanifold_coarse/16-21_04-29-26_...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,confman_baseline_knownonly_unkPA4_c16384_seed0,results_pa_confmanifold_coarse/16-24_04-29-26_...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,known_only,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"

In [7]:
import os

DATA_ROOT = os.path.expanduser("~/Adam/varMax/PADataset/data")

def make_confmanifold_refined_sweep_experiment_list():
    unknown_pas_list = ["PA2", "PA3", "PA4", "PA8"]

    common = {
        "task": "pa",
        "split_mode": "open_pa",
        "normalize": True,
        "cache_len": 16384,
        "batch_size": 16,
        "seed": 0,

        # true open-val manifold controls
        "open_val_frac": 0.15,
        "build_balanced_val_open": True,
        "manifold_balance_seed": 0,
        "require_true_val_open": True,
        "allow_val_open_fallback": False,

        # manifold-aware model selection
        "confidence_temperature": 1.0,
        "early_stopping_mode": "open_conf",
        "model_selection_metric": "val_macro_f1",   # ignored for open_conf stopping
        "open_conf_selection_metric": "dqn_proxy_softmax3",

        # training schedule
        "scheduler_name": "cosine",
        "scheduler_factor": 0.5,
        "scheduler_patience": 5,
        "scheduler_min_lr": 1e-7,
        "epochs": 200,
        "early_stopping_patience": 15,

        # fixed unless explicitly overridden
        "weight_decay": 0.0,
        "lambda_center": 0.1,
        "class_weight_mode": None,
        "grad_clip_norm": None,

        "save_root": "results_pa_confmanifold_refined",
    }

    families = [
        # -------------------------------------------------
        # Winner control + local refinements
        # -------------------------------------------------
        {
            "tag": "ref_base_ctrl",
            "lr": 5e-4,
            "label_smoothing": 0.10,
            "entropy_loss_weight": 0.00,
            "mlp_dropout": 0.30,
        },
        {
            "tag": "ref_base_ls005",
            "lr": 5e-4,
            "label_smoothing": 0.05,
            "entropy_loss_weight": 0.00,
            "mlp_dropout": 0.30,
        },
        {
            "tag": "ref_base_ls002",
            "lr": 5e-4,
            "label_smoothing": 0.02,
            "entropy_loss_weight": 0.00,
            "mlp_dropout": 0.30,
        },
        {
            "tag": "ref_base_ls000",
            "lr": 5e-4,
            "label_smoothing": 0.00,
            "entropy_loss_weight": 0.00,
            "mlp_dropout": 0.30,
        },
        {
            "tag": "ref_base_drop040",
            "lr": 5e-4,
            "label_smoothing": 0.10,
            "entropy_loss_weight": 0.00,
            "mlp_dropout": 0.40,
        },
        {
            "tag": "ref_base_drop050",
            "lr": 5e-4,
            "label_smoothing": 0.10,
            "entropy_loss_weight": 0.00,
            "mlp_dropout": 0.50,
        },
        {
            "tag": "ref_base_ent002",
            "lr": 5e-4,
            "label_smoothing": 0.10,
            "entropy_loss_weight": 0.02,
            "mlp_dropout": 0.30,
        },
        {
            "tag": "ref_base_ent005",
            "lr": 5e-4,
            "label_smoothing": 0.10,
            "entropy_loss_weight": 0.05,
            "mlp_dropout": 0.30,
        },
        {
            "tag": "ref_base_ent010",
            "lr": 5e-4,
            "label_smoothing": 0.10,
            "entropy_loss_weight": 0.10,
            "mlp_dropout": 0.30,
        },
        {
            "tag": "ref_base_lr2e4",
            "lr": 2e-4,
            "label_smoothing": 0.10,
            "entropy_loss_weight": 0.00,
            "mlp_dropout": 0.30,
        },

        # -------------------------------------------------
        # Best paperish runner-up + local refinements
        # -------------------------------------------------
        {
            "tag": "ref_pms_ctrl",
            "lr": 1e-4,
            "weight_decay": 1e-4,
            "lambda_center": 0.1,
            "label_smoothing": 0.05,
            "entropy_loss_weight": 0.05,
            "mlp_dropout": 0.50,
            "grad_clip_norm": 1.0,
            "scheduler_name": "plateau",
        },
        {
            "tag": "ref_pms_ent000",
            "lr": 1e-4,
            "weight_decay": 1e-4,
            "lambda_center": 0.1,
            "label_smoothing": 0.05,
            "entropy_loss_weight": 0.00,
            "mlp_dropout": 0.50,
            "grad_clip_norm": 1.0,
            "scheduler_name": "plateau",
        },
        {
            "tag": "ref_pms_ent002",
            "lr": 1e-4,
            "weight_decay": 1e-4,
            "lambda_center": 0.1,
            "label_smoothing": 0.05,
            "entropy_loss_weight": 0.02,
            "mlp_dropout": 0.50,
            "grad_clip_norm": 1.0,
            "scheduler_name": "plateau",
        },
        {
            "tag": "ref_pms_drop040",
            "lr": 1e-4,
            "weight_decay": 1e-4,
            "lambda_center": 0.1,
            "label_smoothing": 0.05,
            "entropy_loss_weight": 0.05,
            "mlp_dropout": 0.40,
            "grad_clip_norm": 1.0,
            "scheduler_name": "plateau",
        },
        {
            "tag": "ref_pms_lr2e4",
            "lr": 2e-4,
            "weight_decay": 1e-4,
            "lambda_center": 0.1,
            "label_smoothing": 0.05,
            "entropy_loss_weight": 0.05,
            "mlp_dropout": 0.50,
            "grad_clip_norm": 1.0,
            "scheduler_name": "plateau",
        },

        # -------------------------------------------------
        # One direct ablation: does center loss matter?
        # -------------------------------------------------
        {
            "tag": "ref_base_nocenter",
            "lr": 5e-4,
            "lambda_center": 0.0,
            "label_smoothing": 0.10,
            "entropy_loss_weight": 0.00,
            "mlp_dropout": 0.30,
        },
    ]

    experiment_list = []
    for fam in families:
        for unknown_pa in unknown_pas_list:
            cfg = dict(common)
            cfg.update(fam)
            cfg["unknown_pas"] = (unknown_pa,)
            cfg["run_name"] = f"{fam['tag']}_unk{unknown_pa}_c16384_seed0"
            experiment_list.append(cfg)

    return experiment_list


experiment_list = make_confmanifold_refined_sweep_experiment_list()
print("n experiments:", len(experiment_list))
experiment_list[:3]

n experiments: 64

[{'task': 'pa',
  'split_mode': 'open_pa',
  'normalize': True,
  'cache_len': 16384,
  'batch_size': 16,
  'seed': 0,
  'open_val_frac': 0.15,
  'build_balanced_val_open': True,
  'manifold_balance_seed': 0,
  'require_true_val_open': True,
  'allow_val_open_fallback': False,
  'confidence_temperature': 1.0,
  'early_stopping_mode': 'open_conf',
  'model_selection_metric': 'val_macro_f1',
  'open_conf_selection_metric': 'dqn_proxy_softmax3',
  'scheduler_name': 'cosine',
  'scheduler_factor': 0.5,
  'scheduler_patience': 5,
  'scheduler_min_lr': 1e-07,
  'epochs': 200,
  'early_stopping_patience': 15,
  'weight_decay': 0.0,
  'lambda_center': 0.1,
  'class_weight_mode': None,
  'grad_clip_norm': None,
  'save_root': 'results_pa_confmanifold_refined',
  'tag': 'ref_base_ctrl',
  'lr': 0.0005,
  'label_smoothing': 0.1,
  'entropy_loss_weight': 0.0,
  'mlp_dropout': 0.3,
  'unknown_pas': ('PA2',),
  'run_name': 'ref_base_ctrl_unkPA2_c16384_seed0'},
 {'task': 'pa',
  'split_mode': 'open_pa',
  'normalize': True,
  'cache_len': 16384,
  'batch_size': 16,
  'seed': 0,
  'open_val_frac': 0.15,
  'build_balanced_val_open': True,
  'manifold_balance_seed': 0,
  'require_true_val_open': True,
  'allow_val_open_fallback': False,
  'confidence_temperature': 1.0,
  'early_stopping_mode': 'open_conf',
  'model_selection_metric': 'val_macro_f1',
  'open_conf_selection_metric': 'dqn_proxy_softmax3',
  'scheduler_name': 'cosine',
  'scheduler_factor': 0.5,
  'scheduler_patience': 5,
  'scheduler_min_lr': 1e-07,
  'epochs': 200,
  'early_stopping_patience': 15,
  'weight_decay': 0.0,
  'lambda_center': 0.1,
  'class_weight_mode': None,
  'grad_clip_norm': None,
  'save_root': 'results_pa_confmanifold_refined',
  'tag': 'ref_base_ctrl',
  'lr': 0.0005,
  'label_smoothing': 0.1,
  'entropy_loss_weight': 0.0,
  'mlp_dropout': 0.3,
  'unknown_pas': ('PA3',),
  'run_name': 'ref_base_ctrl_unkPA3_c16384_seed0'},
 {'task': 'pa',
  'split_mode': 'open_pa',
  'normalize': True,
  'cache_len': 16384,
  'batch_size': 16,
  'seed': 0,
  'open_val_frac': 0.15,
  'build_balanced_val_open': True,
  'manifold_balance_seed': 0,
  'require_true_val_open': True,
  'allow_val_open_fallback': False,
  'confidence_temperature': 1.0,
  'early_stopping_mode': 'open_conf',
  'model_selection_metric': 'val_macro_f1',
  'open_conf_selection_metric': 'dqn_proxy_softmax3',
  'scheduler_name': 'cosine',
  'scheduler_factor': 0.5,
  'scheduler_patience': 5,
  'scheduler_min_lr': 1e-07,
  'epochs': 200,
  'early_stopping_patience': 15,
  'weight_decay': 0.0,
  'lambda_center': 0.1,
  'class_weight_mode': None,
  'grad_clip_norm': None,
  'save_root': 'results_pa_confmanifold_refined',
  'tag': 'ref_base_ctrl',
  'lr': 0.0005,
  'label_smoothing': 0.1,
  'entropy_loss_weight': 0.0,
  'mlp_dropout': 0.3,
  'unknown_pas': ('PA4',),
  'run_name': 'ref_base_ctrl_unkPA4_c16384_seed0'}]

In [8]:
results_df = run_experiment_suite(
    experiment_list=experiment_list,
    data_root=DATA_ROOT,
    leaderboard_path="confmanifold_refined_leaderboard.csv",
)

================================================================================
Running experiment 1/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "cosine",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": null,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_base_ctrl",
  "lr": 0.0005,
  "label_smoothing": 0.1,
  "entropy_loss_weight": 0.0,
  "mlp_dropout": 0.3,
  "unknown_pas": [
    "PA2"
  ],
  "run_name": "ref_base_ctrl_unkPA2_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.6408 | ce=0.5328 | ent=0.0000 | center=1.0794 | val_loss=0.1479 | val_acc=0.9741 | val_macro_f1=0.9742 | val_dqn_proxy_softmax3=0.8193 | val_dqn_proxy_expanded5=0.8159

Epoch 002 | train_loss=0.4547 | ce=0.3723 | ent=0.0000 | center=0.8241 | val_loss=0.1328 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8423 | val_dqn_proxy_expanded5=0.8210

Epoch 003 | train_loss=0.4318 | ce=0.3606 | ent=0.0000 | center=0.7115 | val_loss=0.1196 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6020 | val_dqn_proxy_expanded5=0.6688

Epoch 004 | train_loss=0.4364 | ce=0.3707 | ent=0.0000 | center=0.6578 | val_loss=0.1263 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6851 | val_dqn_proxy_expanded5=0.7501

Epoch 005 | train_loss=0.4030 | ce=0.3448 | ent=0.0000 | center=0.5826 | val_loss=0.1212 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7880 | val_dqn_proxy_expanded5=0.7874

Epoch 006 | train_loss=0.4020 | ce=0.3487 | ent=0.0000 | center=0.5327 | val_loss=0.1028 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7113 | val_dqn_proxy_expanded5=0.7445

Epoch 007 | train_loss=0.3973 | ce=0.3478 | ent=0.0000 | center=0.4959 | val_loss=0.1095 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.5860 | val_dqn_proxy_expanded5=0.6564

Epoch 008 | train_loss=0.3793 | ce=0.3338 | ent=0.0000 | center=0.4554 | val_loss=0.0872 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.5334 | val_dqn_proxy_expanded5=0.7100

Epoch 009 | train_loss=0.3573 | ce=0.3166 | ent=0.0000 | center=0.4063 | val_loss=0.1003 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6227 | val_dqn_proxy_expanded5=0.7316

Epoch 010 | train_loss=0.3526 | ce=0.3161 | ent=0.0000 | center=0.3654 | val_loss=0.1151 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7463 | val_dqn_proxy_expanded5=0.8061

Epoch 011 | train_loss=0.3529 | ce=0.3183 | ent=0.0000 | center=0.3466 | val_loss=0.0925 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6562 | val_dqn_proxy_expanded5=0.7653

Epoch 012 | train_loss=0.3465 | ce=0.3149 | ent=0.0000 | center=0.3160 | val_loss=0.0777 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9156 | val_dqn_proxy_expanded5=0.8586

Epoch 013 | train_loss=0.3430 | ce=0.3131 | ent=0.0000 | center=0.2990 | val_loss=0.0966 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7435 | val_dqn_proxy_expanded5=0.8039

Epoch 014 | train_loss=0.3440 | ce=0.3161 | ent=0.0000 | center=0.2785 | val_loss=0.0944 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6035 | val_dqn_proxy_expanded5=0.7261

Epoch 015 | train_loss=0.3411 | ce=0.3150 | ent=0.0000 | center=0.2612 | val_loss=0.0826 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7700 | val_dqn_proxy_expanded5=0.7774

Epoch 016 | train_loss=0.3396 | ce=0.3147 | ent=0.0000 | center=0.2492 | val_loss=0.0932 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9007 | val_dqn_proxy_expanded5=0.8468

Epoch 017 | train_loss=0.3449 | ce=0.3204 | ent=0.0000 | center=0.2447 | val_loss=0.0918 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7484 | val_dqn_proxy_expanded5=0.8094

Epoch 018 | train_loss=0.3424 | ce=0.3186 | ent=0.0000 | center=0.2378 | val_loss=0.0941 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.5745 | val_dqn_proxy_expanded5=0.7255

Epoch 019 | train_loss=0.3345 | ce=0.3128 | ent=0.0000 | center=0.2167 | val_loss=0.1039 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7572 | val_dqn_proxy_expanded5=0.8143

Epoch 020 | train_loss=0.3363 | ce=0.3158 | ent=0.0000 | center=0.2050 | val_loss=0.1066 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7751 | val_dqn_proxy_expanded5=0.8145

Epoch 021 | train_loss=0.3341 | ce=0.3144 | ent=0.0000 | center=0.1970 | val_loss=0.1152 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8078 | val_dqn_proxy_expanded5=0.8406

Epoch 022 | train_loss=0.3347 | ce=0.3160 | ent=0.0000 | center=0.1874 | val_loss=0.0936 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8378 | val_dqn_proxy_expanded5=0.7907

Epoch 023 | train_loss=0.3331 | ce=0.3149 | ent=0.0000 | center=0.1820 | val_loss=0.0915 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6941 | val_dqn_proxy_expanded5=0.7836

Epoch 024 | train_loss=0.3347 | ce=0.3169 | ent=0.0000 | center=0.1779 | val_loss=0.0940 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7773 | val_dqn_proxy_expanded5=0.8148

Epoch 025 | train_loss=0.3346 | ce=0.3175 | ent=0.0000 | center=0.1715 | val_loss=0.1135 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7198 | val_dqn_proxy_expanded5=0.7855

Epoch 026 | train_loss=0.3290 | ce=0.3129 | ent=0.0000 | center=0.1613 | val_loss=0.0905 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7129 | val_dqn_proxy_expanded5=0.7903

Epoch 027 | train_loss=0.3276 | ce=0.3122 | ent=0.0000 | center=0.1539 | val_loss=0.0988 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7168 | val_dqn_proxy_expanded5=0.7778
Early stopping at epoch 27 (best epoch: 12)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"

================================================================================
Running experiment 2/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "cosine",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": null,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_base_ctrl",
  "lr": 0.0005,
  "label_smoothing": 0.1,
  "entropy_loss_weight": 0.0,
  "mlp_dropout": 0.3,
  "unknown_pas": [
    "PA3"
  ],
  "run_name": "ref_base_ctrl_unkPA3_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.6930 | ce=0.5865 | ent=0.0000 | center=1.0658 | val_loss=0.3516 | val_acc=0.8444 | val_macro_f1=0.8424 | val_dqn_proxy_softmax3=0.7084 | val_dqn_proxy_expanded5=0.7438

Epoch 002 | train_loss=0.5498 | ce=0.4623 | ent=0.0000 | center=0.8755 | val_loss=0.1914 | val_acc=0.9630 | val_macro_f1=0.9628 | val_dqn_proxy_softmax3=0.7373 | val_dqn_proxy_expanded5=0.7435

Epoch 003 | train_loss=0.4952 | ce=0.4188 | ent=0.0000 | center=0.7637 | val_loss=0.2471 | val_acc=0.9222 | val_macro_f1=0.9211 | val_dqn_proxy_softmax3=0.9307 | val_dqn_proxy_expanded5=0.9051

Epoch 004 | train_loss=0.4448 | ce=0.3774 | ent=0.0000 | center=0.6733 | val_loss=0.1525 | val_acc=0.9704 | val_macro_f1=0.9703 | val_dqn_proxy_softmax3=0.9342 | val_dqn_proxy_expanded5=0.9107

Epoch 005 | train_loss=0.4546 | ce=0.3945 | ent=0.0000 | center=0.6013 | val_loss=0.1404 | val_acc=0.9667 | val_macro_f1=0.9666 | val_dqn_proxy_softmax3=0.7001 | val_dqn_proxy_expanded5=0.7478

Epoch 006 | train_loss=0.4302 | ce=0.3760 | ent=0.0000 | center=0.5419 | val_loss=0.1600 | val_acc=0.9630 | val_macro_f1=0.9628 | val_dqn_proxy_softmax3=0.9358 | val_dqn_proxy_expanded5=0.9027

Epoch 007 | train_loss=0.4048 | ce=0.3558 | ent=0.0000 | center=0.4896 | val_loss=0.0932 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9245 | val_dqn_proxy_expanded5=0.8706

Epoch 008 | train_loss=0.3943 | ce=0.3496 | ent=0.0000 | center=0.4471 | val_loss=0.1190 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.8524 | val_dqn_proxy_expanded5=0.8208

Epoch 009 | train_loss=0.3919 | ce=0.3506 | ent=0.0000 | center=0.4130 | val_loss=0.1033 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9852 | val_dqn_proxy_expanded5=0.9276

Epoch 010 | train_loss=0.4028 | ce=0.3639 | ent=0.0000 | center=0.3891 | val_loss=0.1037 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.7995 | val_dqn_proxy_expanded5=0.7891

Epoch 011 | train_loss=0.3743 | ce=0.3390 | ent=0.0000 | center=0.3533 | val_loss=0.1798 | val_acc=0.9593 | val_macro_f1=0.9592 | val_dqn_proxy_softmax3=0.8437 | val_dqn_proxy_expanded5=0.8152

Epoch 012 | train_loss=0.3709 | ce=0.3377 | ent=0.0000 | center=0.3317 | val_loss=0.0795 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9644 | val_dqn_proxy_expanded5=0.9126

Epoch 013 | train_loss=0.3604 | ce=0.3301 | ent=0.0000 | center=0.3025 | val_loss=0.1842 | val_acc=0.9481 | val_macro_f1=0.9478 | val_dqn_proxy_softmax3=0.9243 | val_dqn_proxy_expanded5=0.8745

Epoch 014 | train_loss=0.3900 | ce=0.3602 | ent=0.0000 | center=0.2975 | val_loss=0.1389 | val_acc=0.9741 | val_macro_f1=0.9740 | val_dqn_proxy_softmax3=0.9546 | val_dqn_proxy_expanded5=0.9079

Epoch 015 | train_loss=0.3735 | ce=0.3459 | ent=0.0000 | center=0.2754 | val_loss=0.0961 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9769 | val_dqn_proxy_expanded5=0.9178

Epoch 016 | train_loss=0.3587 | ce=0.3326 | ent=0.0000 | center=0.2612 | val_loss=0.0908 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9154 | val_dqn_proxy_expanded5=0.8629

Epoch 017 | train_loss=0.3696 | ce=0.3446 | ent=0.0000 | center=0.2496 | val_loss=0.0896 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9598 | val_dqn_proxy_expanded5=0.9058

Epoch 018 | train_loss=0.3609 | ce=0.3373 | ent=0.0000 | center=0.2362 | val_loss=0.0938 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9613 | val_dqn_proxy_expanded5=0.9237

Epoch 019 | train_loss=0.3432 | ce=0.3210 | ent=0.0000 | center=0.2219 | val_loss=0.0770 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9739 | val_dqn_proxy_expanded5=0.9052

Epoch 020 | train_loss=0.3670 | ce=0.3453 | ent=0.0000 | center=0.2173 | val_loss=0.1012 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9324 | val_dqn_proxy_expanded5=0.8896

Epoch 021 | train_loss=0.3577 | ce=0.3373 | ent=0.0000 | center=0.2037 | val_loss=0.1046 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9520 | val_dqn_proxy_expanded5=0.9099

Epoch 022 | train_loss=0.3496 | ce=0.3304 | ent=0.0000 | center=0.1923 | val_loss=0.0959 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9795 | val_dqn_proxy_expanded5=0.9414

Epoch 023 | train_loss=0.3539 | ce=0.3356 | ent=0.0000 | center=0.1834 | val_loss=0.2172 | val_acc=0.9556 | val_macro_f1=0.9554 | val_dqn_proxy_softmax3=0.8325 | val_dqn_proxy_expanded5=0.8150

Epoch 024 | train_loss=0.3452 | ce=0.3273 | ent=0.0000 | center=0.1796 | val_loss=0.0895 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9637 | val_dqn_proxy_expanded5=0.9159
Early stopping at epoch 24 (best epoch: 9)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"

================================================================================
Running experiment 3/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "cosine",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": null,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_base_ctrl",
  "lr": 0.0005,
  "label_smoothing": 0.1,
  "entropy_loss_weight": 0.0,
  "mlp_dropout": 0.3,
  "unknown_pas": [
    "PA4"
  ],
  "run_name": "ref_base_ctrl_unkPA4_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.6901 | ce=0.5810 | ent=0.0000 | center=1.0908 | val_loss=0.2934 | val_acc=0.9333 | val_macro_f1=0.9329 | val_dqn_proxy_softmax3=0.7746 | val_dqn_proxy_expanded5=0.7765

Epoch 002 | train_loss=0.5358 | ce=0.4510 | ent=0.0000 | center=0.8476 | val_loss=0.1951 | val_acc=0.9630 | val_macro_f1=0.9630 | val_dqn_proxy_softmax3=0.8286 | val_dqn_proxy_expanded5=0.7855

Epoch 003 | train_loss=0.5004 | ce=0.4269 | ent=0.0000 | center=0.7354 | val_loss=0.1918 | val_acc=0.9630 | val_macro_f1=0.9629 | val_dqn_proxy_softmax3=0.8894 | val_dqn_proxy_expanded5=0.8128

Epoch 004 | train_loss=0.4438 | ce=0.3800 | ent=0.0000 | center=0.6376 | val_loss=0.1529 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8678 | val_dqn_proxy_expanded5=0.7780

Epoch 005 | train_loss=0.4250 | ce=0.3684 | ent=0.0000 | center=0.5667 | val_loss=0.1366 | val_acc=0.9852 | val_macro_f1=0.9851 | val_dqn_proxy_softmax3=0.7396 | val_dqn_proxy_expanded5=0.7064

Epoch 006 | train_loss=0.4040 | ce=0.3528 | ent=0.0000 | center=0.5123 | val_loss=0.1347 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.7437 | val_dqn_proxy_expanded5=0.7309

Epoch 007 | train_loss=0.4072 | ce=0.3607 | ent=0.0000 | center=0.4645 | val_loss=0.1449 | val_acc=0.9556 | val_macro_f1=0.9554 | val_dqn_proxy_softmax3=0.7279 | val_dqn_proxy_expanded5=0.7100

Epoch 008 | train_loss=0.4031 | ce=0.3603 | ent=0.0000 | center=0.4288 | val_loss=0.1435 | val_acc=0.9667 | val_macro_f1=0.9666 | val_dqn_proxy_softmax3=0.7633 | val_dqn_proxy_expanded5=0.7110

Epoch 009 | train_loss=0.3848 | ce=0.3450 | ent=0.0000 | center=0.3978 | val_loss=0.1594 | val_acc=0.9556 | val_macro_f1=0.9554 | val_dqn_proxy_softmax3=0.7478 | val_dqn_proxy_expanded5=0.7165

Epoch 010 | train_loss=0.3776 | ce=0.3409 | ent=0.0000 | center=0.3663 | val_loss=0.2190 | val_acc=0.9407 | val_macro_f1=0.9403 | val_dqn_proxy_softmax3=0.9062 | val_dqn_proxy_expanded5=0.8521

Epoch 011 | train_loss=0.3776 | ce=0.3434 | ent=0.0000 | center=0.3422 | val_loss=0.1364 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.7937 | val_dqn_proxy_expanded5=0.7218

Epoch 012 | train_loss=0.3735 | ce=0.3410 | ent=0.0000 | center=0.3254 | val_loss=0.0963 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.7746 | val_dqn_proxy_expanded5=0.7521

Epoch 013 | train_loss=0.3590 | ce=0.3295 | ent=0.0000 | center=0.2951 | val_loss=0.1276 | val_acc=0.9741 | val_macro_f1=0.9740 | val_dqn_proxy_softmax3=0.8355 | val_dqn_proxy_expanded5=0.7941

Epoch 014 | train_loss=0.3581 | ce=0.3300 | ent=0.0000 | center=0.2811 | val_loss=0.2175 | val_acc=0.9370 | val_macro_f1=0.9365 | val_dqn_proxy_softmax3=0.7169 | val_dqn_proxy_expanded5=0.6979

Epoch 015 | train_loss=0.3593 | ce=0.3319 | ent=0.0000 | center=0.2743 | val_loss=0.1081 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.7668 | val_dqn_proxy_expanded5=0.7516

Epoch 016 | train_loss=0.3438 | ce=0.3190 | ent=0.0000 | center=0.2477 | val_loss=0.1005 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7770 | val_dqn_proxy_expanded5=0.7645

Epoch 017 | train_loss=0.3528 | ce=0.3289 | ent=0.0000 | center=0.2393 | val_loss=0.1381 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9136 | val_dqn_proxy_expanded5=0.8418

Epoch 018 | train_loss=0.3696 | ce=0.3458 | ent=0.0000 | center=0.2386 | val_loss=0.1338 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9135 | val_dqn_proxy_expanded5=0.8298

Epoch 019 | train_loss=0.3579 | ce=0.3359 | ent=0.0000 | center=0.2199 | val_loss=0.1192 | val_acc=0.9741 | val_macro_f1=0.9740 | val_dqn_proxy_softmax3=0.7703 | val_dqn_proxy_expanded5=0.7288

Epoch 020 | train_loss=0.3463 | ce=0.3251 | ent=0.0000 | center=0.2111 | val_loss=0.1302 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.9321 | val_dqn_proxy_expanded5=0.8507

Epoch 021 | train_loss=0.3480 | ce=0.3280 | ent=0.0000 | center=0.1995 | val_loss=0.1054 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.7820 | val_dqn_proxy_expanded5=0.7735

Epoch 022 | train_loss=0.3436 | ce=0.3250 | ent=0.0000 | center=0.1862 | val_loss=0.0958 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.7801 | val_dqn_proxy_expanded5=0.7782

Epoch 023 | train_loss=0.3457 | ce=0.3278 | ent=0.0000 | center=0.1794 | val_loss=0.0861 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6867 | val_dqn_proxy_expanded5=0.7470

Epoch 024 | train_loss=0.3391 | ce=0.3223 | ent=0.0000 | center=0.1680 | val_loss=0.0855 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.7886 | val_dqn_proxy_expanded5=0.7455

Epoch 025 | train_loss=0.3385 | ce=0.3222 | ent=0.0000 | center=0.1631 | val_loss=0.0854 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9573 | val_dqn_proxy_expanded5=0.8748

Epoch 026 | train_loss=0.3343 | ce=0.3184 | ent=0.0000 | center=0.1584 | val_loss=0.1065 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.7648 | val_dqn_proxy_expanded5=0.7473

Epoch 027 | train_loss=0.3355 | ce=0.3202 | ent=0.0000 | center=0.1532 | val_loss=0.0809 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8552 | val_dqn_proxy_expanded5=0.8120

Epoch 028 | train_loss=0.3394 | ce=0.3247 | ent=0.0000 | center=0.1472 | val_loss=0.1170 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8841 | val_dqn_proxy_expanded5=0.8388

Epoch 029 | train_loss=0.3315 | ce=0.3176 | ent=0.0000 | center=0.1390 | val_loss=0.1059 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7758 | val_dqn_proxy_expanded5=0.7647

Epoch 030 | train_loss=0.3301 | ce=0.3172 | ent=0.0000 | center=0.1291 | val_loss=0.1793 | val_acc=0.9630 | val_macro_f1=0.9628 | val_dqn_proxy_softmax3=0.7529 | val_dqn_proxy_expanded5=0.7561

Epoch 031 | train_loss=0.3368 | ce=0.3238 | ent=0.0000 | center=0.1296 | val_loss=0.1001 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7921 | val_dqn_proxy_expanded5=0.7450

Epoch 032 | train_loss=0.3663 | ce=0.3510 | ent=0.0000 | center=0.1531 | val_loss=0.1107 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.7488 | val_dqn_proxy_expanded5=0.7490

Epoch 033 | train_loss=0.3351 | ce=0.3219 | ent=0.0000 | center=0.1327 | val_loss=0.1005 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.7804 | val_dqn_proxy_expanded5=0.7417

Epoch 034 | train_loss=0.3396 | ce=0.3274 | ent=0.0000 | center=0.1220 | val_loss=0.0838 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.7667 | val_dqn_proxy_expanded5=0.7678

Epoch 035 | train_loss=0.3256 | ce=0.3146 | ent=0.0000 | center=0.1093 | val_loss=0.0956 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.7765 | val_dqn_proxy_expanded5=0.7527

Epoch 036 | train_loss=0.3215 | ce=0.3110 | ent=0.0000 | center=0.1047 | val_loss=0.0927 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9790 | val_dqn_proxy_expanded5=0.8995

Epoch 037 | train_loss=0.3297 | ce=0.3194 | ent=0.0000 | center=0.1028 | val_loss=0.0617 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.7593 | val_dqn_proxy_expanded5=0.7668

Epoch 038 | train_loss=0.3339 | ce=0.3236 | ent=0.0000 | center=0.1026 | val_loss=0.2009 | val_acc=0.9259 | val_macro_f1=0.9250 | val_dqn_proxy_softmax3=0.6760 | val_dqn_proxy_expanded5=0.7087

Epoch 039 | train_loss=0.3306 | ce=0.3208 | ent=0.0000 | center=0.0984 | val_loss=0.1024 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7850 | val_dqn_proxy_expanded5=0.7625

Epoch 040 | train_loss=0.3208 | ce=0.3114 | ent=0.0000 | center=0.0935 | val_loss=0.0780 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.7883 | val_dqn_proxy_expanded5=0.7623

Epoch 041 | train_loss=0.3237 | ce=0.3147 | ent=0.0000 | center=0.0906 | val_loss=0.1635 | val_acc=0.9630 | val_macro_f1=0.9628 | val_dqn_proxy_softmax3=0.7655 | val_dqn_proxy_expanded5=0.7566

Epoch 042 | train_loss=0.3359 | ce=0.3266 | ent=0.0000 | center=0.0929 | val_loss=0.0945 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.6912 | val_dqn_proxy_expanded5=0.7258

Epoch 043 | train_loss=0.3236 | ce=0.3149 | ent=0.0000 | center=0.0867 | val_loss=0.0974 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.7677 | val_dqn_proxy_expanded5=0.7524

Epoch 044 | train_loss=0.3132 | ce=0.3050 | ent=0.0000 | center=0.0813 | val_loss=0.0978 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9592 | val_dqn_proxy_expanded5=0.8973

Epoch 045 | train_loss=0.3322 | ce=0.3243 | ent=0.0000 | center=0.0796 | val_loss=0.1653 | val_acc=0.9630 | val_macro_f1=0.9628 | val_dqn_proxy_softmax3=0.7720 | val_dqn_proxy_expanded5=0.7308

Epoch 046 | train_loss=0.3312 | ce=0.3232 | ent=0.0000 | center=0.0808 | val_loss=0.0714 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.7876 | val_dqn_proxy_expanded5=0.7467

Epoch 047 | train_loss=0.3252 | ce=0.3172 | ent=0.0000 | center=0.0803 | val_loss=0.0914 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7920 | val_dqn_proxy_expanded5=0.7635

Epoch 048 | train_loss=0.3156 | ce=0.3083 | ent=0.0000 | center=0.0728 | val_loss=0.1242 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7552 | val_dqn_proxy_expanded5=0.7564

Epoch 049 | train_loss=0.3208 | ce=0.3137 | ent=0.0000 | center=0.0701 | val_loss=0.0915 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.7644 | val_dqn_proxy_expanded5=0.7487

Epoch 050 | train_loss=0.3153 | ce=0.3086 | ent=0.0000 | center=0.0674 | val_loss=0.1248 | val_acc=0.9667 | val_macro_f1=0.9666 | val_dqn_proxy_softmax3=0.7292 | val_dqn_proxy_expanded5=0.7327

Epoch 051 | train_loss=0.3273 | ce=0.3203 | ent=0.0000 | center=0.0698 | val_loss=0.0999 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.7758 | val_dqn_proxy_expanded5=0.7520
Early stopping at epoch 51 (best epoch: 36)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,ref_base_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-29_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"

================================================================================
Running experiment 4/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "cosine",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": null,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_base_ctrl",
  "lr": 0.0005,
  "label_smoothing": 0.1,
  "entropy_loss_weight": 0.0,
  "mlp_dropout": 0.3,
  "unknown_pas": [
    "PA8"
  ],
  "run_name": "ref_base_ctrl_unkPA8_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.5904 | ce=0.4834 | ent=0.0000 | center=1.0701 | val_loss=0.1265 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9730 | val_dqn_proxy_expanded5=0.9699

Epoch 002 | train_loss=0.4265 | ce=0.3459 | ent=0.0000 | center=0.8055 | val_loss=0.1175 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9177 | val_dqn_proxy_expanded5=0.8820

Epoch 003 | train_loss=0.4043 | ce=0.3368 | ent=0.0000 | center=0.6749 | val_loss=0.1196 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8534 | val_dqn_proxy_expanded5=0.8474

Epoch 004 | train_loss=0.4099 | ce=0.3483 | ent=0.0000 | center=0.6158 | val_loss=0.1400 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9209 | val_dqn_proxy_expanded5=0.9051

Epoch 005 | train_loss=0.3976 | ce=0.3432 | ent=0.0000 | center=0.5439 | val_loss=0.1249 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8415 | val_dqn_proxy_expanded5=0.8308

Epoch 006 | train_loss=0.3806 | ce=0.3313 | ent=0.0000 | center=0.4928 | val_loss=0.1245 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9086 | val_dqn_proxy_expanded5=0.8597

Epoch 007 | train_loss=0.3678 | ce=0.3247 | ent=0.0000 | center=0.4307 | val_loss=0.1035 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9298 | val_dqn_proxy_expanded5=0.8960

Epoch 008 | train_loss=0.3545 | ce=0.3161 | ent=0.0000 | center=0.3840 | val_loss=0.1721 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.8638 | val_dqn_proxy_expanded5=0.8492

Epoch 009 | train_loss=0.3474 | ce=0.3124 | ent=0.0000 | center=0.3507 | val_loss=0.1112 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8609 | val_dqn_proxy_expanded5=0.8250

Epoch 010 | train_loss=0.3428 | ce=0.3113 | ent=0.0000 | center=0.3150 | val_loss=0.1070 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9113 | val_dqn_proxy_expanded5=0.8643

Epoch 011 | train_loss=0.3362 | ce=0.3077 | ent=0.0000 | center=0.2850 | val_loss=0.0981 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9754 | val_dqn_proxy_expanded5=0.9139

Epoch 012 | train_loss=0.3392 | ce=0.3121 | ent=0.0000 | center=0.2715 | val_loss=0.0980 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9155 | val_dqn_proxy_expanded5=0.8611

Epoch 013 | train_loss=0.3330 | ce=0.3077 | ent=0.0000 | center=0.2526 | val_loss=0.0991 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9072 | val_dqn_proxy_expanded5=0.8644

Epoch 014 | train_loss=0.3342 | ce=0.3101 | ent=0.0000 | center=0.2408 | val_loss=0.1067 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9230 | val_dqn_proxy_expanded5=0.8763

Epoch 015 | train_loss=0.3311 | ce=0.3082 | ent=0.0000 | center=0.2283 | val_loss=0.0956 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9360 | val_dqn_proxy_expanded5=0.8888

Epoch 016 | train_loss=0.3275 | ce=0.3061 | ent=0.0000 | center=0.2149 | val_loss=0.0994 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9807 | val_dqn_proxy_expanded5=0.9183

Epoch 017 | train_loss=0.3251 | ce=0.3050 | ent=0.0000 | center=0.2013 | val_loss=0.0982 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9037 | val_dqn_proxy_expanded5=0.8573

Epoch 018 | train_loss=0.3245 | ce=0.3055 | ent=0.0000 | center=0.1905 | val_loss=0.0956 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9394 | val_dqn_proxy_expanded5=0.8819

Epoch 019 | train_loss=0.3214 | ce=0.3032 | ent=0.0000 | center=0.1820 | val_loss=0.0950 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9291 | val_dqn_proxy_expanded5=0.8718

Epoch 020 | train_loss=0.3431 | ce=0.3234 | ent=0.0000 | center=0.1972 | val_loss=0.1063 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9149 | val_dqn_proxy_expanded5=0.8838

Epoch 021 | train_loss=0.3268 | ce=0.3086 | ent=0.0000 | center=0.1818 | val_loss=0.0918 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9830 | val_dqn_proxy_expanded5=0.9230

Epoch 022 | train_loss=0.3256 | ce=0.3086 | ent=0.0000 | center=0.1703 | val_loss=0.1040 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9841 | val_dqn_proxy_expanded5=0.9227

Epoch 023 | train_loss=0.3203 | ce=0.3045 | ent=0.0000 | center=0.1574 | val_loss=0.0965 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9151 | val_dqn_proxy_expanded5=0.8675

Epoch 024 | train_loss=0.3213 | ce=0.3062 | ent=0.0000 | center=0.1513 | val_loss=0.0929 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8927 | val_dqn_proxy_expanded5=0.8526

Epoch 025 | train_loss=0.3179 | ce=0.3036 | ent=0.0000 | center=0.1428 | val_loss=0.0991 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9759 | val_dqn_proxy_expanded5=0.9182

Epoch 026 | train_loss=0.3168 | ce=0.3031 | ent=0.0000 | center=0.1372 | val_loss=0.1083 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9097 | val_dqn_proxy_expanded5=0.8617

Epoch 027 | train_loss=0.3173 | ce=0.3041 | ent=0.0000 | center=0.1323 | val_loss=0.0858 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9448 | val_dqn_proxy_expanded5=0.8921

Epoch 028 | train_loss=0.3161 | ce=0.3037 | ent=0.0000 | center=0.1240 | val_loss=0.1066 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8497 | val_dqn_proxy_expanded5=0.8246

Epoch 029 | train_loss=0.3164 | ce=0.3043 | ent=0.0000 | center=0.1212 | val_loss=0.0915 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8660 | val_dqn_proxy_expanded5=0.8375

Epoch 030 | train_loss=0.3137 | ce=0.3022 | ent=0.0000 | center=0.1145 | val_loss=0.0942 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9497 | val_dqn_proxy_expanded5=0.8977

Epoch 031 | train_loss=0.3150 | ce=0.3039 | ent=0.0000 | center=0.1117 | val_loss=0.0877 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8541 | val_dqn_proxy_expanded5=0.8282

Epoch 032 | train_loss=0.3145 | ce=0.3038 | ent=0.0000 | center=0.1070 | val_loss=0.0835 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8199 | val_dqn_proxy_expanded5=0.8116

Epoch 033 | train_loss=0.3133 | ce=0.3029 | ent=0.0000 | center=0.1045 | val_loss=0.0998 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8495 | val_dqn_proxy_expanded5=0.8237

Epoch 034 | train_loss=0.3131 | ce=0.3035 | ent=0.0000 | center=0.0960 | val_loss=0.0936 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9099 | val_dqn_proxy_expanded5=0.8694

Epoch 035 | train_loss=0.3183 | ce=0.3081 | ent=0.0000 | center=0.1016 | val_loss=0.1017 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9545 | val_dqn_proxy_expanded5=0.9017

Epoch 036 | train_loss=0.3195 | ce=0.3094 | ent=0.0000 | center=0.1009 | val_loss=0.0973 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8281 | val_dqn_proxy_expanded5=0.8134

Epoch 037 | train_loss=0.3150 | ce=0.3055 | ent=0.0000 | center=0.0946 | val_loss=0.0997 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8580 | val_dqn_proxy_expanded5=0.8302
Early stopping at epoch 37 (best epoch: 22)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
3,ref_base_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,ref_base_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-29_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"

================================================================================
Running experiment 5/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "cosine",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": null,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_base_ls005",
  "lr": 0.0005,
  "label_smoothing": 0.05,
  "entropy_loss_weight": 0.0,
  "mlp_dropout": 0.3,
  "unknown_pas": [
    "PA2"
  ],
  "run_name": "ref_base_ls005_unkPA2_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.5564 | ce=0.4415 | ent=0.0000 | center=1.1493 | val_loss=0.1480 | val_acc=0.9630 | val_macro_f1=0.9632 | val_dqn_proxy_softmax3=0.7520 | val_dqn_proxy_expanded5=0.7573

Epoch 002 | train_loss=0.3487 | ce=0.2598 | ent=0.0000 | center=0.8889 | val_loss=0.1012 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8879 | val_dqn_proxy_expanded5=0.8794

Epoch 003 | train_loss=0.3549 | ce=0.2751 | ent=0.0000 | center=0.7976 | val_loss=0.1438 | val_acc=0.9778 | val_macro_f1=0.9779 | val_dqn_proxy_softmax3=0.6013 | val_dqn_proxy_expanded5=0.6885

Epoch 004 | train_loss=0.3066 | ce=0.2390 | ent=0.0000 | center=0.6760 | val_loss=0.1033 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6912 | val_dqn_proxy_expanded5=0.7345

Epoch 005 | train_loss=0.2824 | ce=0.2222 | ent=0.0000 | center=0.6023 | val_loss=0.0815 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.5799 | val_dqn_proxy_expanded5=0.6858

Epoch 006 | train_loss=0.2895 | ce=0.2337 | ent=0.0000 | center=0.5585 | val_loss=0.0932 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8743 | val_dqn_proxy_expanded5=0.8375

Epoch 007 | train_loss=0.2837 | ce=0.2328 | ent=0.0000 | center=0.5091 | val_loss=0.1023 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8570 | val_dqn_proxy_expanded5=0.8618

Epoch 008 | train_loss=0.2771 | ce=0.2295 | ent=0.0000 | center=0.4753 | val_loss=0.0782 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6492 | val_dqn_proxy_expanded5=0.7034

Epoch 009 | train_loss=0.2479 | ce=0.2059 | ent=0.0000 | center=0.4208 | val_loss=0.0602 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6116 | val_dqn_proxy_expanded5=0.6577

Epoch 010 | train_loss=0.2365 | ce=0.1977 | ent=0.0000 | center=0.3873 | val_loss=0.0639 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7828 | val_dqn_proxy_expanded5=0.7786

Epoch 011 | train_loss=0.2417 | ce=0.2056 | ent=0.0000 | center=0.3612 | val_loss=0.0582 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7717 | val_dqn_proxy_expanded5=0.7600

Epoch 012 | train_loss=0.2294 | ce=0.1959 | ent=0.0000 | center=0.3347 | val_loss=0.0681 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9052 | val_dqn_proxy_expanded5=0.8837

Epoch 013 | train_loss=0.2320 | ce=0.2007 | ent=0.0000 | center=0.3136 | val_loss=0.0696 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7247 | val_dqn_proxy_expanded5=0.7152

Epoch 014 | train_loss=0.2231 | ce=0.1943 | ent=0.0000 | center=0.2883 | val_loss=0.0693 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6963 | val_dqn_proxy_expanded5=0.7496

Epoch 015 | train_loss=0.2249 | ce=0.1974 | ent=0.0000 | center=0.2745 | val_loss=0.0696 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7963 | val_dqn_proxy_expanded5=0.7486

Epoch 016 | train_loss=0.2177 | ce=0.1923 | ent=0.0000 | center=0.2540 | val_loss=0.0587 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6976 | val_dqn_proxy_expanded5=0.7622

Epoch 017 | train_loss=0.2184 | ce=0.1947 | ent=0.0000 | center=0.2372 | val_loss=0.0762 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7269 | val_dqn_proxy_expanded5=0.7582

Epoch 018 | train_loss=0.2166 | ce=0.1934 | ent=0.0000 | center=0.2319 | val_loss=0.0600 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8888 | val_dqn_proxy_expanded5=0.8634

Epoch 019 | train_loss=0.2177 | ce=0.1957 | ent=0.0000 | center=0.2197 | val_loss=0.0616 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7915 | val_dqn_proxy_expanded5=0.7870

Epoch 020 | train_loss=0.2130 | ce=0.1921 | ent=0.0000 | center=0.2088 | val_loss=0.0606 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6118 | val_dqn_proxy_expanded5=0.7328

Epoch 021 | train_loss=0.2156 | ce=0.1956 | ent=0.0000 | center=0.1998 | val_loss=0.0654 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8056 | val_dqn_proxy_expanded5=0.7881

Epoch 022 | train_loss=0.2153 | ce=0.1961 | ent=0.0000 | center=0.1919 | val_loss=0.0698 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7480 | val_dqn_proxy_expanded5=0.7785

Epoch 023 | train_loss=0.2129 | ce=0.1946 | ent=0.0000 | center=0.1835 | val_loss=0.0591 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.5792 | val_dqn_proxy_expanded5=0.7216

Epoch 024 | train_loss=0.2112 | ce=0.1940 | ent=0.0000 | center=0.1725 | val_loss=0.0982 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8640 | val_dqn_proxy_expanded5=0.8843

Epoch 025 | train_loss=0.2109 | ce=0.1940 | ent=0.0000 | center=0.1684 | val_loss=0.0695 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7273 | val_dqn_proxy_expanded5=0.7780

Epoch 026 | train_loss=0.2116 | ce=0.1956 | ent=0.0000 | center=0.1596 | val_loss=0.0618 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8137 | val_dqn_proxy_expanded5=0.8044

Epoch 027 | train_loss=0.2099 | ce=0.1942 | ent=0.0000 | center=0.1578 | val_loss=0.0717 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8445 | val_dqn_proxy_expanded5=0.8060
Early stopping at epoch 27 (best epoch: 12)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
3,ref_base_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,ref_base_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-29_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
4,ref_base_ls005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-36_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"

================================================================================
Running experiment 6/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "cosine",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": null,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_base_ls005",
  "lr": 0.0005,
  "label_smoothing": 0.05,
  "entropy_loss_weight": 0.0,
  "mlp_dropout": 0.3,
  "unknown_pas": [
    "PA3"
  ],
  "run_name": "ref_base_ls005_unkPA3_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.6635 | ce=0.5497 | ent=0.0000 | center=1.1381 | val_loss=0.2823 | val_acc=0.8704 | val_macro_f1=0.8608 | val_dqn_proxy_softmax3=0.8009 | val_dqn_proxy_expanded5=0.7715

Epoch 002 | train_loss=0.4185 | ce=0.3243 | ent=0.0000 | center=0.9418 | val_loss=0.1535 | val_acc=0.9593 | val_macro_f1=0.9593 | val_dqn_proxy_softmax3=0.8368 | val_dqn_proxy_expanded5=0.8123

Epoch 003 | train_loss=0.3707 | ce=0.2905 | ent=0.0000 | center=0.8020 | val_loss=0.1023 | val_acc=0.9630 | val_macro_f1=0.9632 | val_dqn_proxy_softmax3=0.6913 | val_dqn_proxy_expanded5=0.7388

Epoch 004 | train_loss=0.3893 | ce=0.3189 | ent=0.0000 | center=0.7039 | val_loss=0.1043 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9725 | val_dqn_proxy_expanded5=0.8913

Epoch 005 | train_loss=0.3359 | ce=0.2728 | ent=0.0000 | center=0.6315 | val_loss=0.0904 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6850 | val_dqn_proxy_expanded5=0.7193

Epoch 006 | train_loss=0.3282 | ce=0.2701 | ent=0.0000 | center=0.5805 | val_loss=0.0911 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.7773 | val_dqn_proxy_expanded5=0.8282

Epoch 007 | train_loss=0.2965 | ce=0.2442 | ent=0.0000 | center=0.5223 | val_loss=0.1581 | val_acc=0.9481 | val_macro_f1=0.9478 | val_dqn_proxy_softmax3=0.8102 | val_dqn_proxy_expanded5=0.8166

Epoch 008 | train_loss=0.2945 | ce=0.2476 | ent=0.0000 | center=0.4685 | val_loss=0.0754 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7772 | val_dqn_proxy_expanded5=0.8023

Epoch 009 | train_loss=0.2794 | ce=0.2362 | ent=0.0000 | center=0.4324 | val_loss=0.0784 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9874 | val_dqn_proxy_expanded5=0.9536

Epoch 010 | train_loss=0.3110 | ce=0.2684 | ent=0.0000 | center=0.4256 | val_loss=0.0651 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9557 | val_dqn_proxy_expanded5=0.9174

Epoch 011 | train_loss=0.2716 | ce=0.2331 | ent=0.0000 | center=0.3851 | val_loss=0.0570 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9755 | val_dqn_proxy_expanded5=0.9181

Epoch 012 | train_loss=0.2601 | ce=0.2251 | ent=0.0000 | center=0.3494 | val_loss=0.0798 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.9400 | val_dqn_proxy_expanded5=0.9217

Epoch 013 | train_loss=0.2563 | ce=0.2235 | ent=0.0000 | center=0.3278 | val_loss=0.0563 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9846 | val_dqn_proxy_expanded5=0.9521

Epoch 014 | train_loss=0.2413 | ce=0.2109 | ent=0.0000 | center=0.3033 | val_loss=0.1140 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.9524 | val_dqn_proxy_expanded5=0.9277

Epoch 015 | train_loss=0.2465 | ce=0.2179 | ent=0.0000 | center=0.2864 | val_loss=0.0688 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.9664 | val_dqn_proxy_expanded5=0.9278

Epoch 016 | train_loss=0.2559 | ce=0.2282 | ent=0.0000 | center=0.2773 | val_loss=0.1120 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.7194 | val_dqn_proxy_expanded5=0.7370

Epoch 017 | train_loss=0.2471 | ce=0.2205 | ent=0.0000 | center=0.2666 | val_loss=0.0665 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9642 | val_dqn_proxy_expanded5=0.9244

Epoch 018 | train_loss=0.2400 | ce=0.2155 | ent=0.0000 | center=0.2448 | val_loss=0.0708 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9430 | val_dqn_proxy_expanded5=0.9072

Epoch 019 | train_loss=0.2618 | ce=0.2374 | ent=0.0000 | center=0.2436 | val_loss=0.0618 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9384 | val_dqn_proxy_expanded5=0.9037

Epoch 020 | train_loss=0.2311 | ce=0.2087 | ent=0.0000 | center=0.2247 | val_loss=0.0554 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9787 | val_dqn_proxy_expanded5=0.9218

Epoch 021 | train_loss=0.2376 | ce=0.2157 | ent=0.0000 | center=0.2184 | val_loss=0.0769 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9512 | val_dqn_proxy_expanded5=0.9040

Epoch 022 | train_loss=0.2415 | ce=0.2198 | ent=0.0000 | center=0.2161 | val_loss=0.1030 | val_acc=0.9741 | val_macro_f1=0.9740 | val_dqn_proxy_softmax3=0.9594 | val_dqn_proxy_expanded5=0.9051

Epoch 023 | train_loss=0.2323 | ce=0.2122 | ent=0.0000 | center=0.2003 | val_loss=0.0810 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9064 | val_dqn_proxy_expanded5=0.8687

Epoch 024 | train_loss=0.2275 | ce=0.2081 | ent=0.0000 | center=0.1943 | val_loss=0.0582 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9888 | val_dqn_proxy_expanded5=0.9333

Epoch 025 | train_loss=0.2314 | ce=0.2136 | ent=0.0000 | center=0.1780 | val_loss=0.0673 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9365 | val_dqn_proxy_expanded5=0.8661

Epoch 026 | train_loss=0.2128 | ce=0.1959 | ent=0.0000 | center=0.1695 | val_loss=0.0526 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9672 | val_dqn_proxy_expanded5=0.9341

Epoch 027 | train_loss=0.2190 | ce=0.2025 | ent=0.0000 | center=0.1655 | val_loss=0.0834 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9734 | val_dqn_proxy_expanded5=0.9079

Epoch 028 | train_loss=0.2308 | ce=0.2148 | ent=0.0000 | center=0.1593 | val_loss=0.0571 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9607 | val_dqn_proxy_expanded5=0.8946

Epoch 029 | train_loss=0.2300 | ce=0.2146 | ent=0.0000 | center=0.1542 | val_loss=0.1294 | val_acc=0.9704 | val_macro_f1=0.9703 | val_dqn_proxy_softmax3=0.9269 | val_dqn_proxy_expanded5=0.8523

Epoch 030 | train_loss=0.2300 | ce=0.2147 | ent=0.0000 | center=0.1531 | val_loss=0.0539 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9134 | val_dqn_proxy_expanded5=0.8823

Epoch 031 | train_loss=0.2143 | ce=0.2000 | ent=0.0000 | center=0.1430 | val_loss=0.1187 | val_acc=0.9741 | val_macro_f1=0.9741 | val_dqn_proxy_softmax3=0.9308 | val_dqn_proxy_expanded5=0.8832

Epoch 032 | train_loss=0.2209 | ce=0.2073 | ent=0.0000 | center=0.1353 | val_loss=0.0639 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9701 | val_dqn_proxy_expanded5=0.9102

Epoch 033 | train_loss=0.2189 | ce=0.2058 | ent=0.0000 | center=0.1315 | val_loss=0.0501 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9144 | val_dqn_proxy_expanded5=0.8768

Epoch 034 | train_loss=0.2136 | ce=0.2012 | ent=0.0000 | center=0.1246 | val_loss=0.0591 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9704 | val_dqn_proxy_expanded5=0.9289

Epoch 035 | train_loss=0.2062 | ce=0.1943 | ent=0.0000 | center=0.1190 | val_loss=0.0605 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9162 | val_dqn_proxy_expanded5=0.9188

Epoch 036 | train_loss=0.2095 | ce=0.1980 | ent=0.0000 | center=0.1153 | val_loss=0.0606 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9729 | val_dqn_proxy_expanded5=0.9254

Epoch 037 | train_loss=0.2149 | ce=0.2037 | ent=0.0000 | center=0.1123 | val_loss=0.0410 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9598 | val_dqn_proxy_expanded5=0.8972

Epoch 038 | train_loss=0.2176 | ce=0.2065 | ent=0.0000 | center=0.1104 | val_loss=0.0472 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9210 | val_dqn_proxy_expanded5=0.8918

Epoch 039 | train_loss=0.2301 | ce=0.2178 | ent=0.0000 | center=0.1226 | val_loss=0.0584 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9460 | val_dqn_proxy_expanded5=0.8824
Early stopping at epoch 39 (best epoch: 24)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
5,ref_base_ls005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,ref_base_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,ref_base_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-29_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
4,ref_base_ls005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-36_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"

================================================================================
Running experiment 7/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "cosine",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": null,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_base_ls005",
  "lr": 0.0005,
  "label_smoothing": 0.05,
  "entropy_loss_weight": 0.0,
  "mlp_dropout": 0.3,
  "unknown_pas": [
    "PA4"
  ],
  "run_name": "ref_base_ls005_unkPA4_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.6644 | ce=0.5342 | ent=0.0000 | center=1.3023 | val_loss=0.2331 | val_acc=0.9407 | val_macro_f1=0.9408 | val_dqn_proxy_softmax3=0.7422 | val_dqn_proxy_expanded5=0.6845

Epoch 002 | train_loss=0.5124 | ce=0.4060 | ent=0.0000 | center=1.0642 | val_loss=0.2079 | val_acc=0.9593 | val_macro_f1=0.9595 | val_dqn_proxy_softmax3=0.8087 | val_dqn_proxy_expanded5=0.7585

Epoch 003 | train_loss=0.4073 | ce=0.3119 | ent=0.0000 | center=0.9542 | val_loss=0.1234 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8890 | val_dqn_proxy_expanded5=0.8179

Epoch 004 | train_loss=0.4076 | ce=0.3244 | ent=0.0000 | center=0.8322 | val_loss=0.1348 | val_acc=0.9444 | val_macro_f1=0.9441 | val_dqn_proxy_softmax3=0.7531 | val_dqn_proxy_expanded5=0.7094

Epoch 005 | train_loss=0.3312 | ce=0.2555 | ent=0.0000 | center=0.7573 | val_loss=0.1304 | val_acc=0.9556 | val_macro_f1=0.9554 | val_dqn_proxy_softmax3=0.7378 | val_dqn_proxy_expanded5=0.7586

Epoch 006 | train_loss=0.3118 | ce=0.2447 | ent=0.0000 | center=0.6704 | val_loss=0.0839 | val_acc=0.9741 | val_macro_f1=0.9740 | val_dqn_proxy_softmax3=0.7320 | val_dqn_proxy_expanded5=0.7536

Epoch 007 | train_loss=0.3017 | ce=0.2409 | ent=0.0000 | center=0.6080 | val_loss=0.1169 | val_acc=0.9667 | val_macro_f1=0.9666 | val_dqn_proxy_softmax3=0.6947 | val_dqn_proxy_expanded5=0.7274

Epoch 008 | train_loss=0.3167 | ce=0.2609 | ent=0.0000 | center=0.5578 | val_loss=0.1871 | val_acc=0.9259 | val_macro_f1=0.9250 | val_dqn_proxy_softmax3=0.8646 | val_dqn_proxy_expanded5=0.8067

Epoch 009 | train_loss=0.3263 | ce=0.2721 | ent=0.0000 | center=0.5418 | val_loss=0.0851 | val_acc=0.9741 | val_macro_f1=0.9740 | val_dqn_proxy_softmax3=0.7732 | val_dqn_proxy_expanded5=0.7730

Epoch 010 | train_loss=0.2827 | ce=0.2328 | ent=0.0000 | center=0.4991 | val_loss=0.0700 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.6927 | val_dqn_proxy_expanded5=0.7361

Epoch 011 | train_loss=0.2814 | ce=0.2360 | ent=0.0000 | center=0.4537 | val_loss=0.0596 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7571 | val_dqn_proxy_expanded5=0.7791

Epoch 012 | train_loss=0.2554 | ce=0.2141 | ent=0.0000 | center=0.4131 | val_loss=0.0575 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6957 | val_dqn_proxy_expanded5=0.7532

Epoch 013 | train_loss=0.2516 | ce=0.2130 | ent=0.0000 | center=0.3866 | val_loss=0.0505 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9344 | val_dqn_proxy_expanded5=0.8941

Epoch 014 | train_loss=0.2569 | ce=0.2205 | ent=0.0000 | center=0.3642 | val_loss=0.1122 | val_acc=0.9667 | val_macro_f1=0.9667 | val_dqn_proxy_softmax3=0.6771 | val_dqn_proxy_expanded5=0.7570

Epoch 015 | train_loss=0.2676 | ce=0.2324 | ent=0.0000 | center=0.3521 | val_loss=0.0574 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.8618 | val_dqn_proxy_expanded5=0.8115

Epoch 016 | train_loss=0.2485 | ce=0.2146 | ent=0.0000 | center=0.3396 | val_loss=0.0804 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7529 | val_dqn_proxy_expanded5=0.7869

Epoch 017 | train_loss=0.2373 | ce=0.2057 | ent=0.0000 | center=0.3164 | val_loss=0.0519 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8555 | val_dqn_proxy_expanded5=0.8478

Epoch 018 | train_loss=0.2562 | ce=0.2261 | ent=0.0000 | center=0.3016 | val_loss=0.0622 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7640 | val_dqn_proxy_expanded5=0.7939

Epoch 019 | train_loss=0.2572 | ce=0.2282 | ent=0.0000 | center=0.2897 | val_loss=0.0524 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7615 | val_dqn_proxy_expanded5=0.7901

Epoch 020 | train_loss=0.2360 | ce=0.2091 | ent=0.0000 | center=0.2693 | val_loss=0.1003 | val_acc=0.9741 | val_macro_f1=0.9740 | val_dqn_proxy_softmax3=0.6843 | val_dqn_proxy_expanded5=0.7355

Epoch 021 | train_loss=0.2397 | ce=0.2130 | ent=0.0000 | center=0.2665 | val_loss=0.0600 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.7242 | val_dqn_proxy_expanded5=0.7676

Epoch 022 | train_loss=0.2268 | ce=0.2016 | ent=0.0000 | center=0.2524 | val_loss=0.0553 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8554 | val_dqn_proxy_expanded5=0.8146

Epoch 023 | train_loss=0.2334 | ce=0.2091 | ent=0.0000 | center=0.2431 | val_loss=0.0567 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7682 | val_dqn_proxy_expanded5=0.7859

Epoch 024 | train_loss=0.2279 | ce=0.2053 | ent=0.0000 | center=0.2256 | val_loss=0.0747 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.7523 | val_dqn_proxy_expanded5=0.7736

Epoch 025 | train_loss=0.2212 | ce=0.1999 | ent=0.0000 | center=0.2129 | val_loss=0.0402 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9591 | val_dqn_proxy_expanded5=0.9081

Epoch 026 | train_loss=0.2238 | ce=0.2034 | ent=0.0000 | center=0.2047 | val_loss=0.1062 | val_acc=0.9593 | val_macro_f1=0.9591 | val_dqn_proxy_softmax3=0.7634 | val_dqn_proxy_expanded5=0.7856

Epoch 027 | train_loss=0.2246 | ce=0.2047 | ent=0.0000 | center=0.1988 | val_loss=0.0438 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.7676 | val_dqn_proxy_expanded5=0.7907

Epoch 028 | train_loss=0.2196 | ce=0.2007 | ent=0.0000 | center=0.1892 | val_loss=0.0790 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.7070 | val_dqn_proxy_expanded5=0.7488

Epoch 029 | train_loss=0.2373 | ce=0.2182 | ent=0.0000 | center=0.1916 | val_loss=0.0858 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.9196 | val_dqn_proxy_expanded5=0.8804

Epoch 030 | train_loss=0.2300 | ce=0.2109 | ent=0.0000 | center=0.1912 | val_loss=0.0543 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9129 | val_dqn_proxy_expanded5=0.8814

Epoch 031 | train_loss=0.2178 | ce=0.2005 | ent=0.0000 | center=0.1726 | val_loss=0.0678 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9032 | val_dqn_proxy_expanded5=0.8801

Epoch 032 | train_loss=0.2181 | ce=0.2015 | ent=0.0000 | center=0.1658 | val_loss=0.1005 | val_acc=0.9704 | val_macro_f1=0.9703 | val_dqn_proxy_softmax3=0.6851 | val_dqn_proxy_expanded5=0.7280

Epoch 033 | train_loss=0.2300 | ce=0.2134 | ent=0.0000 | center=0.1665 | val_loss=0.0643 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9340 | val_dqn_proxy_expanded5=0.8727

Epoch 034 | train_loss=0.2247 | ce=0.2077 | ent=0.0000 | center=0.1704 | val_loss=0.1043 | val_acc=0.9704 | val_macro_f1=0.9703 | val_dqn_proxy_softmax3=0.7360 | val_dqn_proxy_expanded5=0.7863

Epoch 035 | train_loss=0.2106 | ce=0.1956 | ent=0.0000 | center=0.1499 | val_loss=0.0814 | val_acc=0.9667 | val_macro_f1=0.9666 | val_dqn_proxy_softmax3=0.9344 | val_dqn_proxy_expanded5=0.8956

Epoch 036 | train_loss=0.2113 | ce=0.1971 | ent=0.0000 | center=0.1419 | val_loss=0.0440 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8951 | val_dqn_proxy_expanded5=0.8630

Epoch 037 | train_loss=0.2083 | ce=0.1946 | ent=0.0000 | center=0.1368 | val_loss=0.0604 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.7769 | val_dqn_proxy_expanded5=0.7902

Epoch 038 | train_loss=0.2061 | ce=0.1930 | ent=0.0000 | center=0.1314 | val_loss=0.0609 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.7779 | val_dqn_proxy_expanded5=0.7797

Epoch 039 | train_loss=0.2028 | ce=0.1903 | ent=0.0000 | center=0.1245 | val_loss=0.0562 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.6938 | val_dqn_proxy_expanded5=0.7708

Epoch 040 | train_loss=0.2082 | ce=0.1957 | ent=0.0000 | center=0.1256 | val_loss=0.0528 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.7934 | val_dqn_proxy_expanded5=0.7964
Early stopping at epoch 40 (best epoch: 25)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
5,ref_base_ls005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,ref_base_ls005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-42_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,ref_base_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,ref_base_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-29_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
4,ref_base_ls005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-36_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"

================================================================================
Running experiment 8/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "cosine",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": null,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_base_ls005",
  "lr": 0.0005,
  "label_smoothing": 0.05,
  "entropy_loss_weight": 0.0,
  "mlp_dropout": 0.3,
  "unknown_pas": [
    "PA8"
  ],
  "run_name": "ref_base_ls005_unkPA8_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.4959 | ce=0.3772 | ent=0.0000 | center=1.1873 | val_loss=0.1028 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8903 | val_dqn_proxy_expanded5=0.8961

Epoch 002 | train_loss=0.3279 | ce=0.2384 | ent=0.0000 | center=0.8954 | val_loss=0.1049 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9276 | val_dqn_proxy_expanded5=0.9186

Epoch 003 | train_loss=0.3035 | ce=0.2275 | ent=0.0000 | center=0.7595 | val_loss=0.1003 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9691 | val_dqn_proxy_expanded5=0.9581

Epoch 004 | train_loss=0.2788 | ce=0.2141 | ent=0.0000 | center=0.6468 | val_loss=0.0847 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9214 | val_dqn_proxy_expanded5=0.9260

Epoch 005 | train_loss=0.2659 | ce=0.2093 | ent=0.0000 | center=0.5657 | val_loss=0.0746 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9651 | val_dqn_proxy_expanded5=0.9566

Epoch 006 | train_loss=0.2467 | ce=0.1975 | ent=0.0000 | center=0.4922 | val_loss=0.0837 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9509 | val_dqn_proxy_expanded5=0.9225

Epoch 007 | train_loss=0.2425 | ce=0.1972 | ent=0.0000 | center=0.4531 | val_loss=0.0606 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9533 | val_dqn_proxy_expanded5=0.9104

Epoch 008 | train_loss=0.2286 | ce=0.1890 | ent=0.0000 | center=0.3959 | val_loss=0.0662 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9214 | val_dqn_proxy_expanded5=0.8794

Epoch 009 | train_loss=0.2224 | ce=0.1872 | ent=0.0000 | center=0.3516 | val_loss=0.0669 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9429 | val_dqn_proxy_expanded5=0.8933

Epoch 010 | train_loss=0.2192 | ce=0.1868 | ent=0.0000 | center=0.3245 | val_loss=0.0676 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8706 | val_dqn_proxy_expanded5=0.8347

Epoch 011 | train_loss=0.2200 | ce=0.1898 | ent=0.0000 | center=0.3018 | val_loss=0.0609 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9461 | val_dqn_proxy_expanded5=0.8901

Epoch 012 | train_loss=0.2138 | ce=0.1860 | ent=0.0000 | center=0.2785 | val_loss=0.0542 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9401 | val_dqn_proxy_expanded5=0.8926

Epoch 013 | train_loss=0.2137 | ce=0.1870 | ent=0.0000 | center=0.2668 | val_loss=0.0616 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9349 | val_dqn_proxy_expanded5=0.8810

Epoch 014 | train_loss=0.2125 | ce=0.1873 | ent=0.0000 | center=0.2519 | val_loss=0.0643 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9802 | val_dqn_proxy_expanded5=0.9220

Epoch 015 | train_loss=0.2080 | ce=0.1847 | ent=0.0000 | center=0.2333 | val_loss=0.0638 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8834 | val_dqn_proxy_expanded5=0.8443

Epoch 016 | train_loss=0.2125 | ce=0.1902 | ent=0.0000 | center=0.2234 | val_loss=0.0745 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9226 | val_dqn_proxy_expanded5=0.8824

Epoch 017 | train_loss=0.2124 | ce=0.1903 | ent=0.0000 | center=0.2216 | val_loss=0.0623 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9446 | val_dqn_proxy_expanded5=0.8837

Epoch 018 | train_loss=0.2217 | ce=0.1995 | ent=0.0000 | center=0.2216 | val_loss=0.0780 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9549 | val_dqn_proxy_expanded5=0.9556

Epoch 019 | train_loss=0.2407 | ce=0.2148 | ent=0.0000 | center=0.2596 | val_loss=0.0682 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8695 | val_dqn_proxy_expanded5=0.8399

Epoch 020 | train_loss=0.2118 | ce=0.1910 | ent=0.0000 | center=0.2084 | val_loss=0.0545 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9089 | val_dqn_proxy_expanded5=0.8767

Epoch 021 | train_loss=0.2120 | ce=0.1920 | ent=0.0000 | center=0.2001 | val_loss=0.0616 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8764 | val_dqn_proxy_expanded5=0.8362

Epoch 022 | train_loss=0.2026 | ce=0.1842 | ent=0.0000 | center=0.1837 | val_loss=0.0614 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9712 | val_dqn_proxy_expanded5=0.9077

Epoch 023 | train_loss=0.2017 | ce=0.1845 | ent=0.0000 | center=0.1723 | val_loss=0.0640 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8893 | val_dqn_proxy_expanded5=0.8461

Epoch 024 | train_loss=0.2014 | ce=0.1850 | ent=0.0000 | center=0.1635 | val_loss=0.0578 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9315 | val_dqn_proxy_expanded5=0.8763

Epoch 025 | train_loss=0.2010 | ce=0.1854 | ent=0.0000 | center=0.1562 | val_loss=0.0604 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9564 | val_dqn_proxy_expanded5=0.8904

Epoch 026 | train_loss=0.1998 | ce=0.1849 | ent=0.0000 | center=0.1485 | val_loss=0.0731 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9430 | val_dqn_proxy_expanded5=0.8880

Epoch 027 | train_loss=0.1994 | ce=0.1853 | ent=0.0000 | center=0.1410 | val_loss=0.0632 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9640 | val_dqn_proxy_expanded5=0.9208

Epoch 028 | train_loss=0.1967 | ce=0.1831 | ent=0.0000 | center=0.1359 | val_loss=0.0589 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9324 | val_dqn_proxy_expanded5=0.8742

Epoch 029 | train_loss=0.1976 | ce=0.1845 | ent=0.0000 | center=0.1311 | val_loss=0.0708 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8573 | val_dqn_proxy_expanded5=0.8274
Early stopping at epoch 29 (best epoch: 14)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
5,ref_base_ls005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,ref_base_ls005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-45_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,ref_base_ls005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-42_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,ref_base_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,ref_base_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-29_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
4,ref_base_ls005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-36_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"

================================================================================
Running experiment 9/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "cosine",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": null,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_base_ls002",
  "lr": 0.0005,
  "label_smoothing": 0.02,
  "entropy_loss_weight": 0.0,
  "mlp_dropout": 0.3,
  "unknown_pas": [
    "PA2"
  ],
  "run_name": "ref_base_ls002_unkPA2_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.5189 | ce=0.3933 | ent=0.0000 | center=1.2563 | val_loss=0.1403 | val_acc=0.9593 | val_macro_f1=0.9595 | val_dqn_proxy_softmax3=0.6366 | val_dqn_proxy_expanded5=0.7231

Epoch 002 | train_loss=0.3000 | ce=0.1999 | ent=0.0000 | center=1.0010 | val_loss=0.7695 | val_acc=0.6593 | val_macro_f1=0.5481 | val_dqn_proxy_softmax3=0.6719 | val_dqn_proxy_expanded5=0.6740

Epoch 003 | train_loss=0.2743 | ce=0.1872 | ent=0.0000 | center=0.8715 | val_loss=0.0950 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6527 | val_dqn_proxy_expanded5=0.6844

Epoch 004 | train_loss=0.2470 | ce=0.1704 | ent=0.0000 | center=0.7660 | val_loss=0.0836 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6344 | val_dqn_proxy_expanded5=0.7446

Epoch 005 | train_loss=0.2590 | ce=0.1896 | ent=0.0000 | center=0.6940 | val_loss=0.0956 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9450 | val_dqn_proxy_expanded5=0.9447

Epoch 006 | train_loss=0.2210 | ce=0.1583 | ent=0.0000 | center=0.6271 | val_loss=0.0713 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.5807 | val_dqn_proxy_expanded5=0.6654

Epoch 007 | train_loss=0.1962 | ce=0.1410 | ent=0.0000 | center=0.5516 | val_loss=0.0637 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6710 | val_dqn_proxy_expanded5=0.7312

Epoch 008 | train_loss=0.1720 | ce=0.1219 | ent=0.0000 | center=0.5006 | val_loss=0.0555 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6264 | val_dqn_proxy_expanded5=0.6978

Epoch 009 | train_loss=0.1749 | ce=0.1291 | ent=0.0000 | center=0.4575 | val_loss=0.0489 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8203 | val_dqn_proxy_expanded5=0.8632

Epoch 010 | train_loss=0.1631 | ce=0.1197 | ent=0.0000 | center=0.4346 | val_loss=0.0454 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7817 | val_dqn_proxy_expanded5=0.7589

Epoch 011 | train_loss=0.1484 | ce=0.1086 | ent=0.0000 | center=0.3975 | val_loss=0.0440 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8172 | val_dqn_proxy_expanded5=0.7689

Epoch 012 | train_loss=0.1449 | ce=0.1085 | ent=0.0000 | center=0.3647 | val_loss=0.0489 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6086 | val_dqn_proxy_expanded5=0.6960

Epoch 013 | train_loss=0.1501 | ce=0.1154 | ent=0.0000 | center=0.3465 | val_loss=0.0474 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.5427 | val_dqn_proxy_expanded5=0.6620

Epoch 014 | train_loss=0.1417 | ce=0.1094 | ent=0.0000 | center=0.3230 | val_loss=0.0479 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9279 | val_dqn_proxy_expanded5=0.8719

Epoch 015 | train_loss=0.1379 | ce=0.1077 | ent=0.0000 | center=0.3022 | val_loss=0.0421 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6922 | val_dqn_proxy_expanded5=0.6805

Epoch 016 | train_loss=0.1323 | ce=0.1037 | ent=0.0000 | center=0.2863 | val_loss=0.0447 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.5159 | val_dqn_proxy_expanded5=0.6756

Epoch 017 | train_loss=0.1319 | ce=0.1051 | ent=0.0000 | center=0.2679 | val_loss=0.0493 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8604 | val_dqn_proxy_expanded5=0.8217

Epoch 018 | train_loss=0.1322 | ce=0.1069 | ent=0.0000 | center=0.2528 | val_loss=0.0421 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7262 | val_dqn_proxy_expanded5=0.7448

Epoch 019 | train_loss=0.1330 | ce=0.1084 | ent=0.0000 | center=0.2457 | val_loss=0.0455 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8177 | val_dqn_proxy_expanded5=0.7842

Epoch 020 | train_loss=0.1361 | ce=0.1122 | ent=0.0000 | center=0.2388 | val_loss=0.0768 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6462 | val_dqn_proxy_expanded5=0.7546
Early stopping at epoch 20 (best epoch: 5)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
8,ref_base_ls002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-47_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
5,ref_base_ls005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,ref_base_ls005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-45_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,ref_base_ls005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-42_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,ref_base_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,ref_base_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-29_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
4,ref_base_ls005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-36_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"

================================================================================
Running experiment 10/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "cosine",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": null,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_base_ls002",
  "lr": 0.0005,
  "label_smoothing": 0.02,
  "entropy_loss_weight": 0.0,
  "mlp_dropout": 0.3,
  "unknown_pas": [
    "PA3"
  ],
  "run_name": "ref_base_ls002_unkPA3_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.6604 | ce=0.5423 | ent=0.0000 | center=1.1810 | val_loss=0.2073 | val_acc=0.9148 | val_macro_f1=0.9115 | val_dqn_proxy_softmax3=0.8565 | val_dqn_proxy_expanded5=0.8437

Epoch 002 | train_loss=0.4122 | ce=0.3109 | ent=0.0000 | center=1.0131 | val_loss=0.1017 | val_acc=0.9667 | val_macro_f1=0.9667 | val_dqn_proxy_softmax3=0.5356 | val_dqn_proxy_expanded5=0.6511

Epoch 003 | train_loss=0.3319 | ce=0.2431 | ent=0.0000 | center=0.8877 | val_loss=0.1611 | val_acc=0.9296 | val_macro_f1=0.9288 | val_dqn_proxy_softmax3=0.9033 | val_dqn_proxy_expanded5=0.8839

Epoch 004 | train_loss=0.2850 | ce=0.2071 | ent=0.0000 | center=0.7793 | val_loss=0.1030 | val_acc=0.9667 | val_macro_f1=0.9666 | val_dqn_proxy_softmax3=0.9100 | val_dqn_proxy_expanded5=0.9042

Epoch 005 | train_loss=0.3047 | ce=0.2344 | ent=0.0000 | center=0.7031 | val_loss=0.0793 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.9373 | val_dqn_proxy_expanded5=0.9397

Epoch 006 | train_loss=0.2678 | ce=0.2032 | ent=0.0000 | center=0.6466 | val_loss=0.0950 | val_acc=0.9704 | val_macro_f1=0.9703 | val_dqn_proxy_softmax3=0.9333 | val_dqn_proxy_expanded5=0.9170

Epoch 007 | train_loss=0.2461 | ce=0.1874 | ent=0.0000 | center=0.5871 | val_loss=0.2431 | val_acc=0.9148 | val_macro_f1=0.9134 | val_dqn_proxy_softmax3=0.9111 | val_dqn_proxy_expanded5=0.8994

Epoch 008 | train_loss=0.2228 | ce=0.1692 | ent=0.0000 | center=0.5368 | val_loss=0.0778 | val_acc=0.9704 | val_macro_f1=0.9703 | val_dqn_proxy_softmax3=0.9154 | val_dqn_proxy_expanded5=0.9140

Epoch 009 | train_loss=0.2232 | ce=0.1733 | ent=0.0000 | center=0.4983 | val_loss=0.0803 | val_acc=0.9704 | val_macro_f1=0.9704 | val_dqn_proxy_softmax3=0.8883 | val_dqn_proxy_expanded5=0.8597

Epoch 010 | train_loss=0.1967 | ce=0.1518 | ent=0.0000 | center=0.4489 | val_loss=0.0715 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.6526 | val_dqn_proxy_expanded5=0.7349

Epoch 011 | train_loss=0.2123 | ce=0.1694 | ent=0.0000 | center=0.4296 | val_loss=0.0586 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9310 | val_dqn_proxy_expanded5=0.9145

Epoch 012 | train_loss=0.1730 | ce=0.1340 | ent=0.0000 | center=0.3904 | val_loss=0.0504 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9805 | val_dqn_proxy_expanded5=0.9365

Epoch 013 | train_loss=0.2089 | ce=0.1721 | ent=0.0000 | center=0.3685 | val_loss=0.0717 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9022 | val_dqn_proxy_expanded5=0.8668

Epoch 014 | train_loss=0.1683 | ce=0.1347 | ent=0.0000 | center=0.3364 | val_loss=0.0658 | val_acc=0.9704 | val_macro_f1=0.9704 | val_dqn_proxy_softmax3=0.9104 | val_dqn_proxy_expanded5=0.8988

Epoch 015 | train_loss=0.1641 | ce=0.1325 | ent=0.0000 | center=0.3166 | val_loss=0.0714 | val_acc=0.9704 | val_macro_f1=0.9703 | val_dqn_proxy_softmax3=0.8926 | val_dqn_proxy_expanded5=0.8596

Epoch 016 | train_loss=0.1514 | ce=0.1219 | ent=0.0000 | center=0.2954 | val_loss=0.0756 | val_acc=0.9741 | val_macro_f1=0.9741 | val_dqn_proxy_softmax3=0.9554 | val_dqn_proxy_expanded5=0.9327

Epoch 017 | train_loss=0.1491 | ce=0.1218 | ent=0.0000 | center=0.2730 | val_loss=0.0545 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9659 | val_dqn_proxy_expanded5=0.9292

Epoch 018 | train_loss=0.1663 | ce=0.1392 | ent=0.0000 | center=0.2704 | val_loss=0.0704 | val_acc=0.9778 | val_macro_f1=0.9779 | val_dqn_proxy_softmax3=0.9054 | val_dqn_proxy_expanded5=0.9154

Epoch 019 | train_loss=0.1611 | ce=0.1346 | ent=0.0000 | center=0.2653 | val_loss=0.0424 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9870 | val_dqn_proxy_expanded5=0.9451

Epoch 020 | train_loss=0.1451 | ce=0.1204 | ent=0.0000 | center=0.2474 | val_loss=0.0550 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9455 | val_dqn_proxy_expanded5=0.9275

Epoch 021 | train_loss=0.1467 | ce=0.1238 | ent=0.0000 | center=0.2291 | val_loss=0.0527 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9745 | val_dqn_proxy_expanded5=0.9372

Epoch 022 | train_loss=0.1405 | ce=0.1185 | ent=0.0000 | center=0.2208 | val_loss=0.0354 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.8206 | val_dqn_proxy_expanded5=0.8359

Epoch 023 | train_loss=0.1649 | ce=0.1428 | ent=0.0000 | center=0.2204 | val_loss=0.0844 | val_acc=0.9741 | val_macro_f1=0.9740 | val_dqn_proxy_softmax3=0.6846 | val_dqn_proxy_expanded5=0.7242

Epoch 024 | train_loss=0.1854 | ce=0.1619 | ent=0.0000 | center=0.2354 | val_loss=0.0746 | val_acc=0.9741 | val_macro_f1=0.9740 | val_dqn_proxy_softmax3=0.9400 | val_dqn_proxy_expanded5=0.9161

Epoch 025 | train_loss=0.1420 | ce=0.1214 | ent=0.0000 | center=0.2061 | val_loss=0.0437 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9642 | val_dqn_proxy_expanded5=0.9234

Epoch 026 | train_loss=0.1483 | ce=0.1291 | ent=0.0000 | center=0.1917 | val_loss=0.0636 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.9587 | val_dqn_proxy_expanded5=0.9163

Epoch 027 | train_loss=0.1300 | ce=0.1119 | ent=0.0000 | center=0.1812 | val_loss=0.0328 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9789 | val_dqn_proxy_expanded5=0.9360

Epoch 028 | train_loss=0.1414 | ce=0.1239 | ent=0.0000 | center=0.1751 | val_loss=0.0564 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.9492 | val_dqn_proxy_expanded5=0.9446

Epoch 029 | train_loss=0.1424 | ce=0.1253 | ent=0.0000 | center=0.1710 | val_loss=0.0372 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9125 | val_dqn_proxy_expanded5=0.9101

Epoch 030 | train_loss=0.1688 | ce=0.1498 | ent=0.0000 | center=0.1899 | val_loss=0.0481 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9090 | val_dqn_proxy_expanded5=0.9312

Epoch 031 | train_loss=0.1515 | ce=0.1294 | ent=0.0000 | center=0.2206 | val_loss=0.0247 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9886 | val_dqn_proxy_expanded5=0.9437

Epoch 032 | train_loss=0.1392 | ce=0.1225 | ent=0.0000 | center=0.1668 | val_loss=0.0199 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9881 | val_dqn_proxy_expanded5=0.9524

Epoch 033 | train_loss=0.1489 | ce=0.1332 | ent=0.0000 | center=0.1573 | val_loss=0.0670 | val_acc=0.9704 | val_macro_f1=0.9704 | val_dqn_proxy_softmax3=0.9395 | val_dqn_proxy_expanded5=0.9003

Epoch 034 | train_loss=0.1339 | ce=0.1186 | ent=0.0000 | center=0.1525 | val_loss=0.0375 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9936 | val_dqn_proxy_expanded5=0.9434

Epoch 035 | train_loss=0.1299 | ce=0.1158 | ent=0.0000 | center=0.1412 | val_loss=0.0494 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9663 | val_dqn_proxy_expanded5=0.9317

Epoch 036 | train_loss=0.1393 | ce=0.1251 | ent=0.0000 | center=0.1427 | val_loss=0.0344 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9033 | val_dqn_proxy_expanded5=0.8721

Epoch 037 | train_loss=0.1289 | ce=0.1160 | ent=0.0000 | center=0.1289 | val_loss=0.0434 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9377 | val_dqn_proxy_expanded5=0.9446

Epoch 038 | train_loss=0.1168 | ce=0.1042 | ent=0.0000 | center=0.1262 | val_loss=0.0304 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9325 | val_dqn_proxy_expanded5=0.8929

Epoch 039 | train_loss=0.1318 | ce=0.1193 | ent=0.0000 | center=0.1251 | val_loss=0.0587 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9656 | val_dqn_proxy_expanded5=0.9446

Epoch 040 | train_loss=0.1191 | ce=0.1074 | ent=0.0000 | center=0.1168 | val_loss=0.0497 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9572 | val_dqn_proxy_expanded5=0.9191

Epoch 041 | train_loss=0.1431 | ce=0.1309 | ent=0.0000 | center=0.1225 | val_loss=0.0246 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9037 | val_dqn_proxy_expanded5=0.8691

Epoch 042 | train_loss=0.1299 | ce=0.1181 | ent=0.0000 | center=0.1180 | val_loss=0.0371 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9666 | val_dqn_proxy_expanded5=0.9328

Epoch 043 | train_loss=0.1163 | ce=0.1055 | ent=0.0000 | center=0.1082 | val_loss=0.0260 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8838 | val_dqn_proxy_expanded5=0.8586

Epoch 044 | train_loss=0.1220 | ce=0.1113 | ent=0.0000 | center=0.1073 | val_loss=0.0634 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8995 | val_dqn_proxy_expanded5=0.8719

Epoch 045 | train_loss=0.1307 | ce=0.1160 | ent=0.0000 | center=0.1468 | val_loss=0.0511 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.8743 | val_dqn_proxy_expanded5=0.8768

Epoch 046 | train_loss=0.1149 | ce=0.1043 | ent=0.0000 | center=0.1063 | val_loss=0.0342 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.8990 | val_dqn_proxy_expanded5=0.8879

Epoch 047 | train_loss=0.1321 | ce=0.1215 | ent=0.0000 | center=0.1059 | val_loss=0.0469 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8559 | val_dqn_proxy_expanded5=0.8678

Epoch 048 | train_loss=0.1161 | ce=0.1059 | ent=0.0000 | center=0.1026 | val_loss=0.0212 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9159 | val_dqn_proxy_expanded5=0.8852

Epoch 049 | train_loss=0.1203 | ce=0.1102 | ent=0.0000 | center=0.1006 | val_loss=0.0383 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9454 | val_dqn_proxy_expanded5=0.9064
Early stopping at epoch 49 (best epoch: 34)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
8,ref_base_ls002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-47_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,ref_base_ls002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-49_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
5,ref_base_ls005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,ref_base_ls005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-45_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,ref_base_ls005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-42_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,ref_base_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,ref_base_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-29_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
4,ref_base_ls005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-36_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"

================================================================================
Running experiment 11/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "cosine",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": null,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_base_ls002",
  "lr": 0.0005,
  "label_smoothing": 0.02,
  "entropy_loss_weight": 0.0,
  "mlp_dropout": 0.3,
  "unknown_pas": [
    "PA4"
  ],
  "run_name": "ref_base_ls002_unkPA4_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.6148 | ce=0.4844 | ent=0.0000 | center=1.3040 | val_loss=0.3030 | val_acc=0.8889 | val_macro_f1=0.8875 | val_dqn_proxy_softmax3=0.7002 | val_dqn_proxy_expanded5=0.7322

Epoch 002 | train_loss=0.4000 | ce=0.2985 | ent=0.0000 | center=1.0147 | val_loss=0.1710 | val_acc=0.9481 | val_macro_f1=0.9484 | val_dqn_proxy_softmax3=0.7486 | val_dqn_proxy_expanded5=0.7206

Epoch 003 | train_loss=0.3441 | ce=0.2537 | ent=0.0000 | center=0.9038 | val_loss=0.1758 | val_acc=0.9407 | val_macro_f1=0.9411 | val_dqn_proxy_softmax3=0.8388 | val_dqn_proxy_expanded5=0.7785

Epoch 004 | train_loss=0.2746 | ce=0.1941 | ent=0.0000 | center=0.8045 | val_loss=0.0899 | val_acc=0.9593 | val_macro_f1=0.9591 | val_dqn_proxy_softmax3=0.9567 | val_dqn_proxy_expanded5=0.8651

Epoch 005 | train_loss=0.2655 | ce=0.1929 | ent=0.0000 | center=0.7266 | val_loss=0.0996 | val_acc=0.9741 | val_macro_f1=0.9741 | val_dqn_proxy_softmax3=0.7766 | val_dqn_proxy_expanded5=0.7136

Epoch 006 | train_loss=0.2458 | ce=0.1810 | ent=0.0000 | center=0.6476 | val_loss=0.0922 | val_acc=0.9593 | val_macro_f1=0.9593 | val_dqn_proxy_softmax3=0.7430 | val_dqn_proxy_expanded5=0.6906

Epoch 007 | train_loss=0.2623 | ce=0.2011 | ent=0.0000 | center=0.6123 | val_loss=0.0828 | val_acc=0.9667 | val_macro_f1=0.9666 | val_dqn_proxy_softmax3=0.7354 | val_dqn_proxy_expanded5=0.6841

Epoch 008 | train_loss=0.2035 | ce=0.1509 | ent=0.0000 | center=0.5264 | val_loss=0.0445 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9389 | val_dqn_proxy_expanded5=0.8514

Epoch 009 | train_loss=0.1865 | ce=0.1389 | ent=0.0000 | center=0.4760 | val_loss=0.0484 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7776 | val_dqn_proxy_expanded5=0.7202

Epoch 010 | train_loss=0.1808 | ce=0.1367 | ent=0.0000 | center=0.4408 | val_loss=0.0358 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9555 | val_dqn_proxy_expanded5=0.8926

Epoch 011 | train_loss=0.2047 | ce=0.1636 | ent=0.0000 | center=0.4113 | val_loss=0.0458 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7628 | val_dqn_proxy_expanded5=0.7076

Epoch 012 | train_loss=0.1773 | ce=0.1388 | ent=0.0000 | center=0.3857 | val_loss=0.1092 | val_acc=0.9481 | val_macro_f1=0.9478 | val_dqn_proxy_softmax3=0.9228 | val_dqn_proxy_expanded5=0.8831

Epoch 013 | train_loss=0.1824 | ce=0.1461 | ent=0.0000 | center=0.3634 | val_loss=0.0544 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.7470 | val_dqn_proxy_expanded5=0.7156

Epoch 014 | train_loss=0.1541 | ce=0.1197 | ent=0.0000 | center=0.3444 | val_loss=0.0815 | val_acc=0.9630 | val_macro_f1=0.9625 | val_dqn_proxy_softmax3=0.6852 | val_dqn_proxy_expanded5=0.7043

Epoch 015 | train_loss=0.1744 | ce=0.1406 | ent=0.0000 | center=0.3380 | val_loss=0.0525 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.7422 | val_dqn_proxy_expanded5=0.7172

Epoch 016 | train_loss=0.1952 | ce=0.1607 | ent=0.0000 | center=0.3456 | val_loss=0.0509 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9534 | val_dqn_proxy_expanded5=0.8686

Epoch 017 | train_loss=0.1751 | ce=0.1445 | ent=0.0000 | center=0.3069 | val_loss=0.0566 | val_acc=0.9741 | val_macro_f1=0.9740 | val_dqn_proxy_softmax3=0.6914 | val_dqn_proxy_expanded5=0.6737

Epoch 018 | train_loss=0.1491 | ce=0.1203 | ent=0.0000 | center=0.2885 | val_loss=0.0356 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7675 | val_dqn_proxy_expanded5=0.7384

Epoch 019 | train_loss=0.1406 | ce=0.1143 | ent=0.0000 | center=0.2633 | val_loss=0.0608 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.7224 | val_dqn_proxy_expanded5=0.7494
Early stopping at epoch 19 (best epoch: 4)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
8,ref_base_ls002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-47_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,ref_base_ls002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-49_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
5,ref_base_ls005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,ref_base_ls005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-45_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,ref_base_ls005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-42_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,ref_base_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,ref_base_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-29_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
4,ref_base_ls005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-36_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
10,ref_base_ls002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-53_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"

================================================================================
Running experiment 12/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "cosine",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": null,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_base_ls002",
  "lr": 0.0005,
  "label_smoothing": 0.02,
  "entropy_loss_weight": 0.0,
  "mlp_dropout": 0.3,
  "unknown_pas": [
    "PA8"
  ],
  "run_name": "ref_base_ls002_unkPA8_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.4567 | ce=0.3357 | ent=0.0000 | center=1.2100 | val_loss=0.1588 | val_acc=0.9741 | val_macro_f1=0.9740 | val_dqn_proxy_softmax3=0.7764 | val_dqn_proxy_expanded5=0.7665

Epoch 002 | train_loss=0.2456 | ce=0.1532 | ent=0.0000 | center=0.9232 | val_loss=0.1028 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8526 | val_dqn_proxy_expanded5=0.8607

Epoch 003 | train_loss=0.2107 | ce=0.1348 | ent=0.0000 | center=0.7588 | val_loss=0.0991 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8612 | val_dqn_proxy_expanded5=0.8649

Epoch 004 | train_loss=0.2094 | ce=0.1425 | ent=0.0000 | center=0.6686 | val_loss=0.0714 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9182 | val_dqn_proxy_expanded5=0.9161

Epoch 005 | train_loss=0.1924 | ce=0.1327 | ent=0.0000 | center=0.5972 | val_loss=0.0705 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8541 | val_dqn_proxy_expanded5=0.8613

Epoch 006 | train_loss=0.1672 | ce=0.1145 | ent=0.0000 | center=0.5275 | val_loss=0.0495 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9789 | val_dqn_proxy_expanded5=0.9580

Epoch 007 | train_loss=0.1488 | ce=0.1030 | ent=0.0000 | center=0.4587 | val_loss=0.0505 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9457 | val_dqn_proxy_expanded5=0.9088

Epoch 008 | train_loss=0.1428 | ce=0.1021 | ent=0.0000 | center=0.4066 | val_loss=0.0453 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9655 | val_dqn_proxy_expanded5=0.9466

Epoch 009 | train_loss=0.1394 | ce=0.1023 | ent=0.0000 | center=0.3709 | val_loss=0.0414 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9308 | val_dqn_proxy_expanded5=0.8979

Epoch 010 | train_loss=0.1505 | ce=0.1138 | ent=0.0000 | center=0.3670 | val_loss=0.0464 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8772 | val_dqn_proxy_expanded5=0.8397

Epoch 011 | train_loss=0.1341 | ce=0.1006 | ent=0.0000 | center=0.3345 | val_loss=0.0448 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9288 | val_dqn_proxy_expanded5=0.8893

Epoch 012 | train_loss=0.1280 | ce=0.0981 | ent=0.0000 | center=0.2983 | val_loss=0.0498 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8368 | val_dqn_proxy_expanded5=0.8069

Epoch 013 | train_loss=0.1268 | ce=0.0982 | ent=0.0000 | center=0.2857 | val_loss=0.0412 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8601 | val_dqn_proxy_expanded5=0.8295

Epoch 014 | train_loss=0.1257 | ce=0.0992 | ent=0.0000 | center=0.2653 | val_loss=0.0531 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9503 | val_dqn_proxy_expanded5=0.8932

Epoch 015 | train_loss=0.1223 | ce=0.0976 | ent=0.0000 | center=0.2472 | val_loss=0.0490 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9764 | val_dqn_proxy_expanded5=0.9527

Epoch 016 | train_loss=0.1198 | ce=0.0967 | ent=0.0000 | center=0.2306 | val_loss=0.0450 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8324 | val_dqn_proxy_expanded5=0.8006

Epoch 017 | train_loss=0.1177 | ce=0.0953 | ent=0.0000 | center=0.2233 | val_loss=0.0474 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9401 | val_dqn_proxy_expanded5=0.8889

Epoch 018 | train_loss=0.1177 | ce=0.0964 | ent=0.0000 | center=0.2128 | val_loss=0.0488 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9782 | val_dqn_proxy_expanded5=0.9352

Epoch 019 | train_loss=0.1176 | ce=0.0970 | ent=0.0000 | center=0.2063 | val_loss=0.0495 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9751 | val_dqn_proxy_expanded5=0.9154

Epoch 020 | train_loss=0.1156 | ce=0.0966 | ent=0.0000 | center=0.1902 | val_loss=0.0437 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8892 | val_dqn_proxy_expanded5=0.8455

Epoch 021 | train_loss=0.1147 | ce=0.0964 | ent=0.0000 | center=0.1828 | val_loss=0.0438 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9339 | val_dqn_proxy_expanded5=0.8982
Early stopping at epoch 21 (best epoch: 6)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
11,ref_base_ls002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
8,ref_base_ls002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-47_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,ref_base_ls002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-49_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
5,ref_base_ls005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,ref_base_ls005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-45_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,ref_base_ls005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-42_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,ref_base_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,ref_base_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-29_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
4,ref_base_ls005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-36_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
10,ref_base_ls002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-53_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"

================================================================================
Running experiment 13/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "cosine",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": null,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_base_ls000",
  "lr": 0.0005,
  "label_smoothing": 0.0,
  "entropy_loss_weight": 0.0,
  "mlp_dropout": 0.3,
  "unknown_pas": [
    "PA2"
  ],
  "run_name": "ref_base_ls000_unkPA2_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.4877 | ce=0.3699 | ent=0.0000 | center=1.1775 | val_loss=0.1283 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.6817 | val_dqn_proxy_expanded5=0.7036

Epoch 002 | train_loss=0.2270 | ce=0.1282 | ent=0.0000 | center=0.9882 | val_loss=0.0849 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.5877 | val_dqn_proxy_expanded5=0.6814

Epoch 003 | train_loss=0.1832 | ce=0.1027 | ent=0.0000 | center=0.8053 | val_loss=0.0734 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.5987 | val_dqn_proxy_expanded5=0.6770

Epoch 004 | train_loss=0.1699 | ce=0.0969 | ent=0.0000 | center=0.7299 | val_loss=0.0722 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.5547 | val_dqn_proxy_expanded5=0.6656

Epoch 005 | train_loss=0.1521 | ce=0.0861 | ent=0.0000 | center=0.6597 | val_loss=0.0707 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6420 | val_dqn_proxy_expanded5=0.7118

Epoch 006 | train_loss=0.1131 | ce=0.0570 | ent=0.0000 | center=0.5603 | val_loss=0.0502 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6210 | val_dqn_proxy_expanded5=0.6777

Epoch 007 | train_loss=0.0977 | ce=0.0445 | ent=0.0000 | center=0.5315 | val_loss=0.0424 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.5964 | val_dqn_proxy_expanded5=0.6690

Epoch 008 | train_loss=0.0812 | ce=0.0362 | ent=0.0000 | center=0.4499 | val_loss=0.0416 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.4593 | val_dqn_proxy_expanded5=0.6386

Epoch 009 | train_loss=0.0714 | ce=0.0298 | ent=0.0000 | center=0.4157 | val_loss=0.0319 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.4685 | val_dqn_proxy_expanded5=0.6462

Epoch 010 | train_loss=0.1045 | ce=0.0648 | ent=0.0000 | center=0.3968 | val_loss=0.0419 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.5990 | val_dqn_proxy_expanded5=0.6692

Epoch 011 | train_loss=0.0904 | ce=0.0441 | ent=0.0000 | center=0.4624 | val_loss=0.0320 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.4903 | val_dqn_proxy_expanded5=0.6718

Epoch 012 | train_loss=0.0645 | ce=0.0286 | ent=0.0000 | center=0.3591 | val_loss=0.0347 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.4738 | val_dqn_proxy_expanded5=0.6658

Epoch 013 | train_loss=0.0641 | ce=0.0319 | ent=0.0000 | center=0.3217 | val_loss=0.0346 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.5221 | val_dqn_proxy_expanded5=0.6734

Epoch 014 | train_loss=0.0588 | ce=0.0283 | ent=0.0000 | center=0.3051 | val_loss=0.0318 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.4809 | val_dqn_proxy_expanded5=0.6706

Epoch 015 | train_loss=0.0578 | ce=0.0295 | ent=0.0000 | center=0.2829 | val_loss=0.0375 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6092 | val_dqn_proxy_expanded5=0.6860

Epoch 016 | train_loss=0.0546 | ce=0.0280 | ent=0.0000 | center=0.2667 | val_loss=0.0333 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8897 | val_dqn_proxy_expanded5=0.8946

Epoch 017 | train_loss=0.0541 | ce=0.0286 | ent=0.0000 | center=0.2550 | val_loss=0.0333 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.5396 | val_dqn_proxy_expanded5=0.6871

Epoch 018 | train_loss=0.0688 | ce=0.0425 | ent=0.0000 | center=0.2634 | val_loss=0.0359 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.5626 | val_dqn_proxy_expanded5=0.6857

Epoch 019 | train_loss=0.0526 | ce=0.0287 | ent=0.0000 | center=0.2389 | val_loss=0.0332 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.5838 | val_dqn_proxy_expanded5=0.6927

Epoch 020 | train_loss=0.0495 | ce=0.0263 | ent=0.0000 | center=0.2317 | val_loss=0.0442 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6025 | val_dqn_proxy_expanded5=0.6977

Epoch 021 | train_loss=0.0536 | ce=0.0315 | ent=0.0000 | center=0.2214 | val_loss=0.0312 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6009 | val_dqn_proxy_expanded5=0.7104

Epoch 022 | train_loss=0.0464 | ce=0.0261 | ent=0.0000 | center=0.2031 | val_loss=0.0375 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6616 | val_dqn_proxy_expanded5=0.7060

Epoch 023 | train_loss=0.0487 | ce=0.0293 | ent=0.0000 | center=0.1941 | val_loss=0.0309 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6082 | val_dqn_proxy_expanded5=0.6957

Epoch 024 | train_loss=0.0469 | ce=0.0281 | ent=0.0000 | center=0.1885 | val_loss=0.0312 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.4879 | val_dqn_proxy_expanded5=0.6728

Epoch 025 | train_loss=0.0488 | ce=0.0302 | ent=0.0000 | center=0.1856 | val_loss=0.0327 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6282 | val_dqn_proxy_expanded5=0.7519

Epoch 026 | train_loss=0.0468 | ce=0.0289 | ent=0.0000 | center=0.1787 | val_loss=0.0312 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6290 | val_dqn_proxy_expanded5=0.7485

Epoch 027 | train_loss=0.0591 | ce=0.0414 | ent=0.0000 | center=0.1777 | val_loss=0.0422 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9373 | val_dqn_proxy_expanded5=0.9406

Epoch 028 | train_loss=0.1067 | ce=0.0760 | ent=0.0000 | center=0.3074 | val_loss=0.0826 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.8863 | val_dqn_proxy_expanded5=0.8921

Epoch 029 | train_loss=0.0498 | ce=0.0280 | ent=0.0000 | center=0.2183 | val_loss=0.0339 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.5078 | val_dqn_proxy_expanded5=0.6850

Epoch 030 | train_loss=0.0503 | ce=0.0321 | ent=0.0000 | center=0.1813 | val_loss=0.0312 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.4727 | val_dqn_proxy_expanded5=0.6751

Epoch 031 | train_loss=0.0430 | ce=0.0264 | ent=0.0000 | center=0.1666 | val_loss=0.0322 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.5113 | val_dqn_proxy_expanded5=0.6769

Epoch 032 | train_loss=0.0420 | ce=0.0265 | ent=0.0000 | center=0.1546 | val_loss=0.0326 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6125 | val_dqn_proxy_expanded5=0.6883

Epoch 033 | train_loss=0.0397 | ce=0.0249 | ent=0.0000 | center=0.1475 | val_loss=0.0309 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.5150 | val_dqn_proxy_expanded5=0.6776

Epoch 034 | train_loss=0.0430 | ce=0.0287 | ent=0.0000 | center=0.1424 | val_loss=0.0311 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.4728 | val_dqn_proxy_expanded5=0.6744

Epoch 035 | train_loss=0.0399 | ce=0.0265 | ent=0.0000 | center=0.1340 | val_loss=0.0314 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.4934 | val_dqn_proxy_expanded5=0.6839

Epoch 036 | train_loss=0.0380 | ce=0.0248 | ent=0.0000 | center=0.1319 | val_loss=0.0408 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6485 | val_dqn_proxy_expanded5=0.7003

Epoch 037 | train_loss=0.0627 | ce=0.0463 | ent=0.0000 | center=0.1635 | val_loss=0.0392 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.5651 | val_dqn_proxy_expanded5=0.6915

Epoch 038 | train_loss=0.0515 | ce=0.0341 | ent=0.0000 | center=0.1739 | val_loss=0.0368 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.5911 | val_dqn_proxy_expanded5=0.6822

Epoch 039 | train_loss=0.0425 | ce=0.0288 | ent=0.0000 | center=0.1372 | val_loss=0.0352 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.5983 | val_dqn_proxy_expanded5=0.6948

Epoch 040 | train_loss=0.0399 | ce=0.0271 | ent=0.0000 | center=0.1282 | val_loss=0.0428 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6092 | val_dqn_proxy_expanded5=0.7059

Epoch 041 | train_loss=0.0403 | ce=0.0287 | ent=0.0000 | center=0.1163 | val_loss=0.0326 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.4543 | val_dqn_proxy_expanded5=0.6481

Epoch 042 | train_loss=0.0371 | ce=0.0258 | ent=0.0000 | center=0.1136 | val_loss=0.0320 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.4122 | val_dqn_proxy_expanded5=0.6610
Early stopping at epoch 42 (best epoch: 27)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
11,ref_base_ls002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
8,ref_base_ls002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-47_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,ref_base_ls000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-56_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,ref_base_ls002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-49_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
5,ref_base_ls005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,ref_base_ls005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-45_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,ref_base_ls005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-42_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,ref_base_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,ref_base_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-29_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
4,ref_base_ls005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-36_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
10,ref_base_ls002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-53_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"

================================================================================
Running experiment 14/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "cosine",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": null,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_base_ls000",
  "lr": 0.0005,
  "label_smoothing": 0.0,
  "entropy_loss_weight": 0.0,
  "mlp_dropout": 0.3,
  "unknown_pas": [
    "PA3"
  ],
  "run_name": "ref_base_ls000_unkPA3_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.5326 | ce=0.4041 | ent=0.0000 | center=1.2848 | val_loss=0.1685 | val_acc=0.9407 | val_macro_f1=0.9403 | val_dqn_proxy_softmax3=0.7135 | val_dqn_proxy_expanded5=0.7155

Epoch 002 | train_loss=0.3335 | ce=0.2240 | ent=0.0000 | center=1.0947 | val_loss=0.1060 | val_acc=0.9741 | val_macro_f1=0.9741 | val_dqn_proxy_softmax3=0.9165 | val_dqn_proxy_expanded5=0.8648

Epoch 003 | train_loss=0.2420 | ce=0.1526 | ent=0.0000 | center=0.8933 | val_loss=0.1457 | val_acc=0.9370 | val_macro_f1=0.9365 | val_dqn_proxy_softmax3=0.7342 | val_dqn_proxy_expanded5=0.7273

Epoch 004 | train_loss=0.2508 | ce=0.1706 | ent=0.0000 | center=0.8017 | val_loss=0.1155 | val_acc=0.9519 | val_macro_f1=0.9516 | val_dqn_proxy_softmax3=0.8806 | val_dqn_proxy_expanded5=0.8589

Epoch 005 | train_loss=0.1551 | ce=0.0831 | ent=0.0000 | center=0.7208 | val_loss=0.0522 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.9363 | val_dqn_proxy_expanded5=0.8983

Epoch 006 | train_loss=0.1978 | ce=0.1312 | ent=0.0000 | center=0.6651 | val_loss=0.1753 | val_acc=0.9407 | val_macro_f1=0.9403 | val_dqn_proxy_softmax3=0.8467 | val_dqn_proxy_expanded5=0.7985

Epoch 007 | train_loss=0.1856 | ce=0.1263 | ent=0.0000 | center=0.5935 | val_loss=0.0608 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8779 | val_dqn_proxy_expanded5=0.8829

Epoch 008 | train_loss=0.1434 | ce=0.0877 | ent=0.0000 | center=0.5577 | val_loss=0.0517 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.8868 | val_dqn_proxy_expanded5=0.8282

Epoch 009 | train_loss=0.1637 | ce=0.1116 | ent=0.0000 | center=0.5210 | val_loss=0.0635 | val_acc=0.9741 | val_macro_f1=0.9740 | val_dqn_proxy_softmax3=0.9135 | val_dqn_proxy_expanded5=0.9150

Epoch 010 | train_loss=0.1410 | ce=0.0901 | ent=0.0000 | center=0.5092 | val_loss=0.0354 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9493 | val_dqn_proxy_expanded5=0.9424

Epoch 011 | train_loss=0.1057 | ce=0.0617 | ent=0.0000 | center=0.4398 | val_loss=0.0389 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9472 | val_dqn_proxy_expanded5=0.9024

Epoch 012 | train_loss=0.0926 | ce=0.0524 | ent=0.0000 | center=0.4024 | val_loss=0.1193 | val_acc=0.9556 | val_macro_f1=0.9554 | val_dqn_proxy_softmax3=0.9050 | val_dqn_proxy_expanded5=0.8447

Epoch 013 | train_loss=0.1083 | ce=0.0697 | ent=0.0000 | center=0.3860 | val_loss=0.0801 | val_acc=0.9593 | val_macro_f1=0.9591 | val_dqn_proxy_softmax3=0.5539 | val_dqn_proxy_expanded5=0.6108

Epoch 014 | train_loss=0.1044 | ce=0.0680 | ent=0.0000 | center=0.3642 | val_loss=0.0399 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.8798 | val_dqn_proxy_expanded5=0.8406

Epoch 015 | train_loss=0.1187 | ce=0.0827 | ent=0.0000 | center=0.3592 | val_loss=0.0289 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8927 | val_dqn_proxy_expanded5=0.8369

Epoch 016 | train_loss=0.0985 | ce=0.0657 | ent=0.0000 | center=0.3276 | val_loss=0.0573 | val_acc=0.9704 | val_macro_f1=0.9703 | val_dqn_proxy_softmax3=0.9169 | val_dqn_proxy_expanded5=0.8745

Epoch 017 | train_loss=0.0869 | ce=0.0554 | ent=0.0000 | center=0.3145 | val_loss=0.0223 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.6490 | val_dqn_proxy_expanded5=0.6923

Epoch 018 | train_loss=0.0728 | ce=0.0419 | ent=0.0000 | center=0.3089 | val_loss=0.0248 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9454 | val_dqn_proxy_expanded5=0.8861

Epoch 019 | train_loss=0.0845 | ce=0.0564 | ent=0.0000 | center=0.2806 | val_loss=0.0342 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6530 | val_dqn_proxy_expanded5=0.6942

Epoch 020 | train_loss=0.0895 | ce=0.0603 | ent=0.0000 | center=0.2917 | val_loss=0.0206 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9688 | val_dqn_proxy_expanded5=0.9561

Epoch 021 | train_loss=0.0984 | ce=0.0704 | ent=0.0000 | center=0.2803 | val_loss=0.0617 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.6393 | val_dqn_proxy_expanded5=0.6949

Epoch 022 | train_loss=0.0816 | ce=0.0554 | ent=0.0000 | center=0.2628 | val_loss=0.0346 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.8317 | val_dqn_proxy_expanded5=0.7926

Epoch 023 | train_loss=0.0757 | ce=0.0511 | ent=0.0000 | center=0.2453 | val_loss=0.0232 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9046 | val_dqn_proxy_expanded5=0.8577

Epoch 024 | train_loss=0.0626 | ce=0.0391 | ent=0.0000 | center=0.2342 | val_loss=0.0376 | val_acc=0.9741 | val_macro_f1=0.9741 | val_dqn_proxy_softmax3=0.8096 | val_dqn_proxy_expanded5=0.7746

Epoch 025 | train_loss=0.0780 | ce=0.0559 | ent=0.0000 | center=0.2216 | val_loss=0.0758 | val_acc=0.9704 | val_macro_f1=0.9703 | val_dqn_proxy_softmax3=0.8339 | val_dqn_proxy_expanded5=0.7984

Epoch 026 | train_loss=0.0638 | ce=0.0418 | ent=0.0000 | center=0.2206 | val_loss=0.0230 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9015 | val_dqn_proxy_expanded5=0.8475

Epoch 027 | train_loss=0.0587 | ce=0.0385 | ent=0.0000 | center=0.2018 | val_loss=0.0533 | val_acc=0.9741 | val_macro_f1=0.9741 | val_dqn_proxy_softmax3=0.8873 | val_dqn_proxy_expanded5=0.8444

Epoch 028 | train_loss=0.0668 | ce=0.0456 | ent=0.0000 | center=0.2127 | val_loss=0.0238 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.6904 | val_dqn_proxy_expanded5=0.7476

Epoch 029 | train_loss=0.0502 | ce=0.0310 | ent=0.0000 | center=0.1917 | val_loss=0.0654 | val_acc=0.9741 | val_macro_f1=0.9741 | val_dqn_proxy_softmax3=0.6460 | val_dqn_proxy_expanded5=0.6938

Epoch 030 | train_loss=0.0794 | ce=0.0595 | ent=0.0000 | center=0.1993 | val_loss=0.0476 | val_acc=0.9852 | val_macro_f1=0.9853 | val_dqn_proxy_softmax3=0.9371 | val_dqn_proxy_expanded5=0.9315

Epoch 031 | train_loss=0.0742 | ce=0.0525 | ent=0.0000 | center=0.2170 | val_loss=0.0300 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9040 | val_dqn_proxy_expanded5=0.8612

Epoch 032 | train_loss=0.0686 | ce=0.0506 | ent=0.0000 | center=0.1801 | val_loss=0.0250 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8030 | val_dqn_proxy_expanded5=0.7689

Epoch 033 | train_loss=0.0562 | ce=0.0385 | ent=0.0000 | center=0.1771 | val_loss=0.0131 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.8416 | val_dqn_proxy_expanded5=0.8120

Epoch 034 | train_loss=0.0406 | ce=0.0237 | ent=0.0000 | center=0.1691 | val_loss=0.0153 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8497 | val_dqn_proxy_expanded5=0.8230

Epoch 035 | train_loss=0.0457 | ce=0.0297 | ent=0.0000 | center=0.1594 | val_loss=0.0147 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9154 | val_dqn_proxy_expanded5=0.8639
Early stopping at epoch 35 (best epoch: 20)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
11,ref_base_ls002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,ref_base_ls000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-59_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
8,ref_base_ls002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-47_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,ref_base_ls000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-56_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,ref_base_ls002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-49_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
5,ref_base_ls005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,ref_base_ls005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-45_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,ref_base_ls005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-42_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,ref_base_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,ref_base_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-29_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
4,ref_base_ls005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-36_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
10,ref_base_ls002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-53_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"

================================================================================
Running experiment 15/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "cosine",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": null,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_base_ls000",
  "lr": 0.0005,
  "label_smoothing": 0.0,
  "entropy_loss_weight": 0.0,
  "mlp_dropout": 0.3,
  "unknown_pas": [
    "PA4"
  ],
  "run_name": "ref_base_ls000_unkPA4_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.6399 | ce=0.4946 | ent=0.0000 | center=1.4522 | val_loss=0.2802 | val_acc=0.8963 | val_macro_f1=0.8942 | val_dqn_proxy_softmax3=0.7239 | val_dqn_proxy_expanded5=0.7529

Epoch 002 | train_loss=0.3529 | ce=0.2371 | ent=0.0000 | center=1.1578 | val_loss=0.1732 | val_acc=0.9333 | val_macro_f1=0.9331 | val_dqn_proxy_softmax3=0.8844 | val_dqn_proxy_expanded5=0.8401

Epoch 003 | train_loss=0.3000 | ce=0.1976 | ent=0.0000 | center=1.0239 | val_loss=0.1873 | val_acc=0.9074 | val_macro_f1=0.9054 | val_dqn_proxy_softmax3=0.8194 | val_dqn_proxy_expanded5=0.7741

Epoch 004 | train_loss=0.2940 | ce=0.2004 | ent=0.0000 | center=0.9367 | val_loss=0.1081 | val_acc=0.9741 | val_macro_f1=0.9742 | val_dqn_proxy_softmax3=0.8060 | val_dqn_proxy_expanded5=0.7599

Epoch 005 | train_loss=0.1882 | ce=0.1073 | ent=0.0000 | center=0.8096 | val_loss=0.0715 | val_acc=0.9704 | val_macro_f1=0.9703 | val_dqn_proxy_softmax3=0.8274 | val_dqn_proxy_expanded5=0.7457

Epoch 006 | train_loss=0.1890 | ce=0.1170 | ent=0.0000 | center=0.7202 | val_loss=0.0720 | val_acc=0.9667 | val_macro_f1=0.9666 | val_dqn_proxy_softmax3=0.8285 | val_dqn_proxy_expanded5=0.7725

Epoch 007 | train_loss=0.1588 | ce=0.0927 | ent=0.0000 | center=0.6614 | val_loss=0.1837 | val_acc=0.9222 | val_macro_f1=0.9211 | val_dqn_proxy_softmax3=0.5498 | val_dqn_proxy_expanded5=0.5873

Epoch 008 | train_loss=0.1465 | ce=0.0860 | ent=0.0000 | center=0.6057 | val_loss=0.1088 | val_acc=0.9519 | val_macro_f1=0.9516 | val_dqn_proxy_softmax3=0.6410 | val_dqn_proxy_expanded5=0.6477

Epoch 009 | train_loss=0.1310 | ce=0.0729 | ent=0.0000 | center=0.5809 | val_loss=0.0572 | val_acc=0.9630 | val_macro_f1=0.9628 | val_dqn_proxy_softmax3=0.7076 | val_dqn_proxy_expanded5=0.6791

Epoch 010 | train_loss=0.1216 | ce=0.0684 | ent=0.0000 | center=0.5322 | val_loss=0.0442 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6997 | val_dqn_proxy_expanded5=0.6935

Epoch 011 | train_loss=0.1589 | ce=0.1074 | ent=0.0000 | center=0.5150 | val_loss=0.1102 | val_acc=0.9444 | val_macro_f1=0.9441 | val_dqn_proxy_softmax3=0.6831 | val_dqn_proxy_expanded5=0.6760

Epoch 012 | train_loss=0.1226 | ce=0.0760 | ent=0.0000 | center=0.4663 | val_loss=0.0313 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6360 | val_dqn_proxy_expanded5=0.6853

Epoch 013 | train_loss=0.0925 | ce=0.0501 | ent=0.0000 | center=0.4238 | val_loss=0.0271 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.7570 | val_dqn_proxy_expanded5=0.7810

Epoch 014 | train_loss=0.0928 | ce=0.0524 | ent=0.0000 | center=0.4044 | val_loss=0.0229 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.6425 | val_dqn_proxy_expanded5=0.7088

Epoch 015 | train_loss=0.0798 | ce=0.0408 | ent=0.0000 | center=0.3900 | val_loss=0.0411 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.6937 | val_dqn_proxy_expanded5=0.7141

Epoch 016 | train_loss=0.0799 | ce=0.0427 | ent=0.0000 | center=0.3717 | val_loss=0.0597 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.6826 | val_dqn_proxy_expanded5=0.7298

Epoch 017 | train_loss=0.1006 | ce=0.0659 | ent=0.0000 | center=0.3466 | val_loss=0.0472 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.6105 | val_dqn_proxy_expanded5=0.6955
Early stopping at epoch 17 (best epoch: 2)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
11,ref_base_ls002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,ref_base_ls000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-59_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
8,ref_base_ls002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-47_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,ref_base_ls000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-56_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,ref_base_ls002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-49_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
5,ref_base_ls005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,ref_base_ls005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-45_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,ref_base_ls005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-42_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,ref_base_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,ref_base_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-29_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
4,ref_base_ls005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-36_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
10,ref_base_ls002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-53_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
14,ref_base_ls000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-02_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"

================================================================================
Running experiment 16/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "cosine",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": null,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_base_ls000",
  "lr": 0.0005,
  "label_smoothing": 0.0,
  "entropy_loss_weight": 0.0,
  "mlp_dropout": 0.3,
  "unknown_pas": [
    "PA8"
  ],
  "run_name": "ref_base_ls000_unkPA8_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.3981 | ce=0.2719 | ent=0.0000 | center=1.2623 | val_loss=0.0942 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9343 | val_dqn_proxy_expanded5=0.9450

Epoch 002 | train_loss=0.1717 | ce=0.0723 | ent=0.0000 | center=0.9946 | val_loss=0.0862 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9168 | val_dqn_proxy_expanded5=0.9290

Epoch 003 | train_loss=0.1493 | ce=0.0635 | ent=0.0000 | center=0.8585 | val_loss=0.0773 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9413 | val_dqn_proxy_expanded5=0.9416

Epoch 004 | train_loss=0.1282 | ce=0.0570 | ent=0.0000 | center=0.7120 | val_loss=0.0603 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8531 | val_dqn_proxy_expanded5=0.8612

Epoch 005 | train_loss=0.1070 | ce=0.0449 | ent=0.0000 | center=0.6207 | val_loss=0.0528 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9579 | val_dqn_proxy_expanded5=0.9527

Epoch 006 | train_loss=0.0968 | ce=0.0350 | ent=0.0000 | center=0.6179 | val_loss=0.0400 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9406 | val_dqn_proxy_expanded5=0.9259

Epoch 007 | train_loss=0.0708 | ce=0.0221 | ent=0.0000 | center=0.4866 | val_loss=0.0410 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9295 | val_dqn_proxy_expanded5=0.9149

Epoch 008 | train_loss=0.0671 | ce=0.0214 | ent=0.0000 | center=0.4568 | val_loss=0.0472 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9204 | val_dqn_proxy_expanded5=0.8990

Epoch 009 | train_loss=0.0765 | ce=0.0325 | ent=0.0000 | center=0.4406 | val_loss=0.0525 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8829 | val_dqn_proxy_expanded5=0.8643

Epoch 010 | train_loss=0.0540 | ce=0.0163 | ent=0.0000 | center=0.3771 | val_loss=0.0548 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9845 | val_dqn_proxy_expanded5=0.9622

Epoch 011 | train_loss=0.0523 | ce=0.0184 | ent=0.0000 | center=0.3388 | val_loss=0.0361 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8845 | val_dqn_proxy_expanded5=0.8568

Epoch 012 | train_loss=0.0992 | ce=0.0609 | ent=0.0000 | center=0.3831 | val_loss=0.0526 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8739 | val_dqn_proxy_expanded5=0.8531

Epoch 013 | train_loss=0.0677 | ce=0.0266 | ent=0.0000 | center=0.4113 | val_loss=0.0480 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8622 | val_dqn_proxy_expanded5=0.8283

Epoch 014 | train_loss=0.0531 | ce=0.0205 | ent=0.0000 | center=0.3263 | val_loss=0.0511 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9679 | val_dqn_proxy_expanded5=0.9487

Epoch 015 | train_loss=0.0497 | ce=0.0189 | ent=0.0000 | center=0.3084 | val_loss=0.0449 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8761 | val_dqn_proxy_expanded5=0.8450

Epoch 016 | train_loss=0.0494 | ce=0.0213 | ent=0.0000 | center=0.2817 | val_loss=0.0315 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8567 | val_dqn_proxy_expanded5=0.8254

Epoch 017 | train_loss=0.0457 | ce=0.0202 | ent=0.0000 | center=0.2554 | val_loss=0.0321 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8864 | val_dqn_proxy_expanded5=0.8554

Epoch 018 | train_loss=0.0445 | ce=0.0205 | ent=0.0000 | center=0.2404 | val_loss=0.0331 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8997 | val_dqn_proxy_expanded5=0.8729

Epoch 019 | train_loss=0.0419 | ce=0.0186 | ent=0.0000 | center=0.2336 | val_loss=0.0357 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8520 | val_dqn_proxy_expanded5=0.8321

Epoch 020 | train_loss=0.0387 | ce=0.0167 | ent=0.0000 | center=0.2198 | val_loss=0.0537 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8915 | val_dqn_proxy_expanded5=0.8569

Epoch 021 | train_loss=0.0405 | ce=0.0195 | ent=0.0000 | center=0.2101 | val_loss=0.0492 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8512 | val_dqn_proxy_expanded5=0.8241

Epoch 022 | train_loss=0.0415 | ce=0.0210 | ent=0.0000 | center=0.2050 | val_loss=0.0329 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8993 | val_dqn_proxy_expanded5=0.8712

Epoch 023 | train_loss=0.0383 | ce=0.0191 | ent=0.0000 | center=0.1921 | val_loss=0.0314 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8559 | val_dqn_proxy_expanded5=0.8316

Epoch 024 | train_loss=0.0321 | ce=0.0136 | ent=0.0000 | center=0.1853 | val_loss=0.0453 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8529 | val_dqn_proxy_expanded5=0.8347

Epoch 025 | train_loss=0.0353 | ce=0.0175 | ent=0.0000 | center=0.1779 | val_loss=0.0493 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8931 | val_dqn_proxy_expanded5=0.8646
Early stopping at epoch 25 (best epoch: 10)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
11,ref_base_ls002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
15,ref_base_ls000_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-04_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,ref_base_ls000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-59_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
8,ref_base_ls002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-47_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,ref_base_ls000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-56_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,ref_base_ls002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-49_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
5,ref_base_ls005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,ref_base_ls005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-45_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,ref_base_ls005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-42_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,ref_base_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,ref_base_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-29_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
4,ref_base_ls005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-36_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
10,ref_base_ls002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-53_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
14,ref_base_ls000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-02_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"

================================================================================
Running experiment 17/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "cosine",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": null,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_base_drop040",
  "lr": 0.0005,
  "label_smoothing": 0.1,
  "entropy_loss_weight": 0.0,
  "mlp_dropout": 0.4,
  "unknown_pas": [
    "PA2"
  ],
  "run_name": "ref_base_drop040_unkPA2_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.7088 | ce=0.5903 | ent=0.0000 | center=1.1850 | val_loss=0.1887 | val_acc=0.9667 | val_macro_f1=0.9669 | val_dqn_proxy_softmax3=0.8636 | val_dqn_proxy_expanded5=0.8492

Epoch 002 | train_loss=0.4865 | ce=0.3886 | ent=0.0000 | center=0.9789 | val_loss=0.1373 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6565 | val_dqn_proxy_expanded5=0.7262

Epoch 003 | train_loss=0.4807 | ce=0.3949 | ent=0.0000 | center=0.8581 | val_loss=0.1221 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7042 | val_dqn_proxy_expanded5=0.7076

Epoch 004 | train_loss=0.4347 | ce=0.3577 | ent=0.0000 | center=0.7700 | val_loss=0.1383 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6056 | val_dqn_proxy_expanded5=0.6657

Epoch 005 | train_loss=0.4288 | ce=0.3578 | ent=0.0000 | center=0.7094 | val_loss=0.1051 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6902 | val_dqn_proxy_expanded5=0.7170

Epoch 006 | train_loss=0.4246 | ce=0.3586 | ent=0.0000 | center=0.6595 | val_loss=0.1065 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7406 | val_dqn_proxy_expanded5=0.7870

Epoch 007 | train_loss=0.4004 | ce=0.3398 | ent=0.0000 | center=0.6062 | val_loss=0.1121 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7402 | val_dqn_proxy_expanded5=0.8061

Epoch 008 | train_loss=0.4023 | ce=0.3456 | ent=0.0000 | center=0.5675 | val_loss=0.0980 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8173 | val_dqn_proxy_expanded5=0.8423

Epoch 009 | train_loss=0.3857 | ce=0.3330 | ent=0.0000 | center=0.5275 | val_loss=0.0856 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6417 | val_dqn_proxy_expanded5=0.7077

Epoch 010 | train_loss=0.3719 | ce=0.3228 | ent=0.0000 | center=0.4908 | val_loss=0.0918 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7042 | val_dqn_proxy_expanded5=0.7220

Epoch 011 | train_loss=0.3619 | ce=0.3171 | ent=0.0000 | center=0.4475 | val_loss=0.0999 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7991 | val_dqn_proxy_expanded5=0.8339

Epoch 012 | train_loss=0.3632 | ce=0.3211 | ent=0.0000 | center=0.4215 | val_loss=0.1109 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8153 | val_dqn_proxy_expanded5=0.8479

Epoch 013 | train_loss=0.3603 | ce=0.3204 | ent=0.0000 | center=0.3997 | val_loss=0.1019 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6209 | val_dqn_proxy_expanded5=0.6977

Epoch 014 | train_loss=0.3560 | ce=0.3191 | ent=0.0000 | center=0.3691 | val_loss=0.1022 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.5824 | val_dqn_proxy_expanded5=0.6597

Epoch 015 | train_loss=0.3545 | ce=0.3191 | ent=0.0000 | center=0.3538 | val_loss=0.0964 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7401 | val_dqn_proxy_expanded5=0.7322

Epoch 016 | train_loss=0.3502 | ce=0.3172 | ent=0.0000 | center=0.3309 | val_loss=0.1096 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7346 | val_dqn_proxy_expanded5=0.7780
Early stopping at epoch 16 (best epoch: 1)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
11,ref_base_ls002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
15,ref_base_ls000_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-04_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,ref_base_ls000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-59_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
8,ref_base_ls002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-47_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,ref_base_ls000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-56_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,ref_base_ls002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-49_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
5,ref_base_ls005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,ref_base_ls005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-45_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,ref_base_ls005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-42_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,ref_base_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,ref_base_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-29_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
4,ref_base_ls005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-36_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
16,ref_base_drop040_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-06_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
10,ref_base_ls002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-53_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
14,ref_base_ls000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-02_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"

================================================================================
Running experiment 18/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "cosine",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": null,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_base_drop040",
  "lr": 0.0005,
  "label_smoothing": 0.1,
  "entropy_loss_weight": 0.0,
  "mlp_dropout": 0.4,
  "unknown_pas": [
    "PA3"
  ],
  "run_name": "ref_base_drop040_unkPA3_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.7646 | ce=0.6489 | ent=0.0000 | center=1.1576 | val_loss=0.2902 | val_acc=0.9630 | val_macro_f1=0.9632 | val_dqn_proxy_softmax3=0.8348 | val_dqn_proxy_expanded5=0.8361

Epoch 002 | train_loss=0.5389 | ce=0.4420 | ent=0.0000 | center=0.9693 | val_loss=0.2168 | val_acc=0.9296 | val_macro_f1=0.9300 | val_dqn_proxy_softmax3=0.7984 | val_dqn_proxy_expanded5=0.7909

Epoch 003 | train_loss=0.4959 | ce=0.4113 | ent=0.0000 | center=0.8456 | val_loss=0.2443 | val_acc=0.9111 | val_macro_f1=0.9108 | val_dqn_proxy_softmax3=0.7508 | val_dqn_proxy_expanded5=0.7933

Epoch 004 | train_loss=0.4874 | ce=0.4113 | ent=0.0000 | center=0.7609 | val_loss=0.1605 | val_acc=0.9667 | val_macro_f1=0.9667 | val_dqn_proxy_softmax3=0.9015 | val_dqn_proxy_expanded5=0.8791

Epoch 005 | train_loss=0.4894 | ce=0.4196 | ent=0.0000 | center=0.6974 | val_loss=0.1553 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.7378 | val_dqn_proxy_expanded5=0.7797

Epoch 006 | train_loss=0.4299 | ce=0.3674 | ent=0.0000 | center=0.6245 | val_loss=0.1272 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9498 | val_dqn_proxy_expanded5=0.9199

Epoch 007 | train_loss=0.4239 | ce=0.3671 | ent=0.0000 | center=0.5680 | val_loss=0.1164 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9554 | val_dqn_proxy_expanded5=0.9209

Epoch 008 | train_loss=0.4281 | ce=0.3755 | ent=0.0000 | center=0.5261 | val_loss=0.1053 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9672 | val_dqn_proxy_expanded5=0.9375

Epoch 009 | train_loss=0.4081 | ce=0.3593 | ent=0.0000 | center=0.4886 | val_loss=0.1304 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9614 | val_dqn_proxy_expanded5=0.9342

Epoch 010 | train_loss=0.3975 | ce=0.3523 | ent=0.0000 | center=0.4526 | val_loss=0.1261 | val_acc=0.9741 | val_macro_f1=0.9738 | val_dqn_proxy_softmax3=0.7189 | val_dqn_proxy_expanded5=0.7061

Epoch 011 | train_loss=0.3892 | ce=0.3467 | ent=0.0000 | center=0.4247 | val_loss=0.1876 | val_acc=0.9556 | val_macro_f1=0.9554 | val_dqn_proxy_softmax3=0.9329 | val_dqn_proxy_expanded5=0.9192

Epoch 012 | train_loss=0.3906 | ce=0.3503 | ent=0.0000 | center=0.4030 | val_loss=0.1444 | val_acc=0.9704 | val_macro_f1=0.9703 | val_dqn_proxy_softmax3=0.9732 | val_dqn_proxy_expanded5=0.9497

Epoch 013 | train_loss=0.3899 | ce=0.3521 | ent=0.0000 | center=0.3774 | val_loss=0.0961 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9567 | val_dqn_proxy_expanded5=0.9186

Epoch 014 | train_loss=0.3787 | ce=0.3434 | ent=0.0000 | center=0.3525 | val_loss=0.1086 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9762 | val_dqn_proxy_expanded5=0.9512

Epoch 015 | train_loss=0.3759 | ce=0.3430 | ent=0.0000 | center=0.3283 | val_loss=0.1290 | val_acc=0.9667 | val_macro_f1=0.9666 | val_dqn_proxy_softmax3=0.9409 | val_dqn_proxy_expanded5=0.8948

Epoch 016 | train_loss=0.3667 | ce=0.3359 | ent=0.0000 | center=0.3087 | val_loss=0.0793 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9883 | val_dqn_proxy_expanded5=0.9451

Epoch 017 | train_loss=0.3696 | ce=0.3397 | ent=0.0000 | center=0.2993 | val_loss=0.1058 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9633 | val_dqn_proxy_expanded5=0.9237

Epoch 018 | train_loss=0.3759 | ce=0.3474 | ent=0.0000 | center=0.2852 | val_loss=0.1820 | val_acc=0.9667 | val_macro_f1=0.9666 | val_dqn_proxy_softmax3=0.8995 | val_dqn_proxy_expanded5=0.8799

Epoch 019 | train_loss=0.3708 | ce=0.3437 | ent=0.0000 | center=0.2708 | val_loss=0.1061 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9589 | val_dqn_proxy_expanded5=0.9255

Epoch 020 | train_loss=0.3620 | ce=0.3363 | ent=0.0000 | center=0.2569 | val_loss=0.1013 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9866 | val_dqn_proxy_expanded5=0.9707

Epoch 021 | train_loss=0.3585 | ce=0.3342 | ent=0.0000 | center=0.2433 | val_loss=0.0912 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9728 | val_dqn_proxy_expanded5=0.9124

Epoch 022 | train_loss=0.3724 | ce=0.3489 | ent=0.0000 | center=0.2350 | val_loss=0.1285 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9215 | val_dqn_proxy_expanded5=0.9206

Epoch 023 | train_loss=0.3561 | ce=0.3335 | ent=0.0000 | center=0.2265 | val_loss=0.1308 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.9544 | val_dqn_proxy_expanded5=0.8918

Epoch 024 | train_loss=0.3728 | ce=0.3510 | ent=0.0000 | center=0.2179 | val_loss=0.1134 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9097 | val_dqn_proxy_expanded5=0.8754

Epoch 025 | train_loss=0.3596 | ce=0.3388 | ent=0.0000 | center=0.2073 | val_loss=0.1354 | val_acc=0.9704 | val_macro_f1=0.9703 | val_dqn_proxy_softmax3=0.8411 | val_dqn_proxy_expanded5=0.8351

Epoch 026 | train_loss=0.3444 | ce=0.3250 | ent=0.0000 | center=0.1942 | val_loss=0.0862 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8182 | val_dqn_proxy_expanded5=0.8110

Epoch 027 | train_loss=0.3494 | ce=0.3306 | ent=0.0000 | center=0.1880 | val_loss=0.0887 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9627 | val_dqn_proxy_expanded5=0.8951

Epoch 028 | train_loss=0.3392 | ce=0.3211 | ent=0.0000 | center=0.1815 | val_loss=0.0993 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8862 | val_dqn_proxy_expanded5=0.8494

Epoch 029 | train_loss=0.3447 | ce=0.3274 | ent=0.0000 | center=0.1730 | val_loss=0.1019 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9676 | val_dqn_proxy_expanded5=0.9181

Epoch 030 | train_loss=0.3398 | ce=0.3230 | ent=0.0000 | center=0.1672 | val_loss=0.1034 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9737 | val_dqn_proxy_expanded5=0.9228

Epoch 031 | train_loss=0.3411 | ce=0.3253 | ent=0.0000 | center=0.1579 | val_loss=0.1377 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.8894 | val_dqn_proxy_expanded5=0.8724
Early stopping at epoch 31 (best epoch: 16)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
11,ref_base_ls002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
15,ref_base_ls000_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-04_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,ref_base_ls000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-59_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
8,ref_base_ls002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-47_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,ref_base_ls000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-56_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
17,ref_base_drop040_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-07_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,ref_base_ls002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-49_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
5,ref_base_ls005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,ref_base_ls005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-45_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,ref_base_ls005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-42_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,ref_base_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,ref_base_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-29_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
4,ref_base_ls005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-36_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
16,ref_base_drop040_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-06_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
10,ref_base_ls002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-53_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
14,ref_base_ls000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-02_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"

================================================================================
Running experiment 19/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "cosine",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": null,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_base_drop040",
  "lr": 0.0005,
  "label_smoothing": 0.1,
  "entropy_loss_weight": 0.0,
  "mlp_dropout": 0.4,
  "unknown_pas": [
    "PA4"
  ],
  "run_name": "ref_base_drop040_unkPA4_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.7594 | ce=0.6407 | ent=0.0000 | center=1.1872 | val_loss=0.2700 | val_acc=0.9370 | val_macro_f1=0.9370 | val_dqn_proxy_softmax3=0.7389 | val_dqn_proxy_expanded5=0.7748

Epoch 002 | train_loss=0.5662 | ce=0.4656 | ent=0.0000 | center=1.0056 | val_loss=0.1808 | val_acc=0.9519 | val_macro_f1=0.9520 | val_dqn_proxy_softmax3=0.8550 | val_dqn_proxy_expanded5=0.8164

Epoch 003 | train_loss=0.4985 | ce=0.4102 | ent=0.0000 | center=0.8835 | val_loss=0.1812 | val_acc=0.9630 | val_macro_f1=0.9628 | val_dqn_proxy_softmax3=0.9031 | val_dqn_proxy_expanded5=0.8210

Epoch 004 | train_loss=0.4770 | ce=0.3979 | ent=0.0000 | center=0.7912 | val_loss=0.2006 | val_acc=0.9333 | val_macro_f1=0.9329 | val_dqn_proxy_softmax3=0.7312 | val_dqn_proxy_expanded5=0.6819

Epoch 005 | train_loss=0.4735 | ce=0.4012 | ent=0.0000 | center=0.7225 | val_loss=0.1405 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.7903 | val_dqn_proxy_expanded5=0.7309

Epoch 006 | train_loss=0.4333 | ce=0.3681 | ent=0.0000 | center=0.6519 | val_loss=0.0940 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.7549 | val_dqn_proxy_expanded5=0.7024

Epoch 007 | train_loss=0.4103 | ce=0.3500 | ent=0.0000 | center=0.6029 | val_loss=0.0949 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9513 | val_dqn_proxy_expanded5=0.8656

Epoch 008 | train_loss=0.4121 | ce=0.3569 | ent=0.0000 | center=0.5519 | val_loss=0.1079 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7543 | val_dqn_proxy_expanded5=0.7031

Epoch 009 | train_loss=0.4112 | ce=0.3603 | ent=0.0000 | center=0.5088 | val_loss=0.1062 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9351 | val_dqn_proxy_expanded5=0.8456

Epoch 010 | train_loss=0.4048 | ce=0.3566 | ent=0.0000 | center=0.4818 | val_loss=0.0960 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.8556 | val_dqn_proxy_expanded5=0.7936

Epoch 011 | train_loss=0.3827 | ce=0.3380 | ent=0.0000 | center=0.4464 | val_loss=0.1614 | val_acc=0.9593 | val_macro_f1=0.9591 | val_dqn_proxy_softmax3=0.8587 | val_dqn_proxy_expanded5=0.7718

Epoch 012 | train_loss=0.3817 | ce=0.3400 | ent=0.0000 | center=0.4171 | val_loss=0.0966 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7533 | val_dqn_proxy_expanded5=0.7031

Epoch 013 | train_loss=0.3793 | ce=0.3404 | ent=0.0000 | center=0.3887 | val_loss=0.1043 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7748 | val_dqn_proxy_expanded5=0.7173

Epoch 014 | train_loss=0.3760 | ce=0.3399 | ent=0.0000 | center=0.3617 | val_loss=0.1149 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7672 | val_dqn_proxy_expanded5=0.7263

Epoch 015 | train_loss=0.3714 | ce=0.3368 | ent=0.0000 | center=0.3453 | val_loss=0.1207 | val_acc=0.9593 | val_macro_f1=0.9591 | val_dqn_proxy_softmax3=0.7558 | val_dqn_proxy_expanded5=0.7058

Epoch 016 | train_loss=0.3650 | ce=0.3319 | ent=0.0000 | center=0.3310 | val_loss=0.0965 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.7686 | val_dqn_proxy_expanded5=0.7238

Epoch 017 | train_loss=0.3820 | ce=0.3503 | ent=0.0000 | center=0.3170 | val_loss=0.0998 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.7424 | val_dqn_proxy_expanded5=0.7159

Epoch 018 | train_loss=0.3628 | ce=0.3329 | ent=0.0000 | center=0.2986 | val_loss=0.1187 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.8119 | val_dqn_proxy_expanded5=0.7464

Epoch 019 | train_loss=0.3508 | ce=0.3230 | ent=0.0000 | center=0.2779 | val_loss=0.0844 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.7691 | val_dqn_proxy_expanded5=0.7425

Epoch 020 | train_loss=0.3620 | ce=0.3350 | ent=0.0000 | center=0.2706 | val_loss=0.0962 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7591 | val_dqn_proxy_expanded5=0.7098

Epoch 021 | train_loss=0.3687 | ce=0.3424 | ent=0.0000 | center=0.2632 | val_loss=0.1319 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.6687 | val_dqn_proxy_expanded5=0.7220

Epoch 022 | train_loss=0.3615 | ce=0.3366 | ent=0.0000 | center=0.2486 | val_loss=0.1142 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.7904 | val_dqn_proxy_expanded5=0.7449
Early stopping at epoch 22 (best epoch: 7)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
11,ref_base_ls002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
15,ref_base_ls000_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-04_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,ref_base_ls000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-59_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
8,ref_base_ls002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-47_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,ref_base_ls000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-56_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
17,ref_base_drop040_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-07_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,ref_base_ls002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-49_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
5,ref_base_ls005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,ref_base_ls005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-45_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,ref_base_ls005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-42_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,ref_base_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,ref_base_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-29_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
4,ref_base_ls005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-36_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
18,ref_base_drop040_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-09_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
16,ref_base_drop040_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-06_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
10,ref_base_ls002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-53_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
14,ref_base_ls000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-02_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"

================================================================================
Running experiment 20/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "cosine",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": null,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_base_drop040",
  "lr": 0.0005,
  "label_smoothing": 0.1,
  "entropy_loss_weight": 0.0,
  "mlp_dropout": 0.4,
  "unknown_pas": [
    "PA8"
  ],
  "run_name": "ref_base_drop040_unkPA8_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.6142 | ce=0.4999 | ent=0.0000 | center=1.1423 | val_loss=0.1479 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9423 | val_dqn_proxy_expanded5=0.9101

Epoch 002 | train_loss=0.4474 | ce=0.3577 | ent=0.0000 | center=0.8965 | val_loss=0.1207 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9414 | val_dqn_proxy_expanded5=0.9123

Epoch 003 | train_loss=0.4356 | ce=0.3559 | ent=0.0000 | center=0.7970 | val_loss=0.1483 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9601 | val_dqn_proxy_expanded5=0.9348

Epoch 004 | train_loss=0.4073 | ce=0.3366 | ent=0.0000 | center=0.7067 | val_loss=0.1071 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9552 | val_dqn_proxy_expanded5=0.9348

Epoch 005 | train_loss=0.3963 | ce=0.3330 | ent=0.0000 | center=0.6333 | val_loss=0.1085 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9676 | val_dqn_proxy_expanded5=0.9575

Epoch 006 | train_loss=0.3923 | ce=0.3331 | ent=0.0000 | center=0.5922 | val_loss=0.0841 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9619 | val_dqn_proxy_expanded5=0.9400

Epoch 007 | train_loss=0.3846 | ce=0.3294 | ent=0.0000 | center=0.5518 | val_loss=0.1107 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9717 | val_dqn_proxy_expanded5=0.9402

Epoch 008 | train_loss=0.3654 | ce=0.3155 | ent=0.0000 | center=0.4991 | val_loss=0.0881 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9668 | val_dqn_proxy_expanded5=0.9264

Epoch 009 | train_loss=0.3575 | ce=0.3123 | ent=0.0000 | center=0.4525 | val_loss=0.1151 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9121 | val_dqn_proxy_expanded5=0.8676

Epoch 010 | train_loss=0.3516 | ce=0.3103 | ent=0.0000 | center=0.4134 | val_loss=0.0968 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9077 | val_dqn_proxy_expanded5=0.8659

Epoch 011 | train_loss=0.3478 | ce=0.3095 | ent=0.0000 | center=0.3826 | val_loss=0.0943 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9089 | val_dqn_proxy_expanded5=0.8805

Epoch 012 | train_loss=0.3471 | ce=0.3114 | ent=0.0000 | center=0.3561 | val_loss=0.1076 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9736 | val_dqn_proxy_expanded5=0.9295

Epoch 013 | train_loss=0.3420 | ce=0.3088 | ent=0.0000 | center=0.3317 | val_loss=0.0961 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9000 | val_dqn_proxy_expanded5=0.8579

Epoch 014 | train_loss=0.3449 | ce=0.3133 | ent=0.0000 | center=0.3167 | val_loss=0.1166 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8971 | val_dqn_proxy_expanded5=0.8593

Epoch 015 | train_loss=0.3375 | ce=0.3082 | ent=0.0000 | center=0.2928 | val_loss=0.0868 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9557 | val_dqn_proxy_expanded5=0.9098

Epoch 016 | train_loss=0.3396 | ce=0.3115 | ent=0.0000 | center=0.2814 | val_loss=0.1092 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9434 | val_dqn_proxy_expanded5=0.9009

Epoch 017 | train_loss=0.3379 | ce=0.3113 | ent=0.0000 | center=0.2663 | val_loss=0.0878 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9153 | val_dqn_proxy_expanded5=0.8813

Epoch 018 | train_loss=0.3360 | ce=0.3107 | ent=0.0000 | center=0.2531 | val_loss=0.0971 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9235 | val_dqn_proxy_expanded5=0.8864

Epoch 019 | train_loss=0.3292 | ce=0.3059 | ent=0.0000 | center=0.2325 | val_loss=0.1024 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9506 | val_dqn_proxy_expanded5=0.9093

Epoch 020 | train_loss=0.3308 | ce=0.3082 | ent=0.0000 | center=0.2266 | val_loss=0.0930 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8791 | val_dqn_proxy_expanded5=0.8377

Epoch 021 | train_loss=0.3277 | ce=0.3066 | ent=0.0000 | center=0.2111 | val_loss=0.0849 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9491 | val_dqn_proxy_expanded5=0.9125

Epoch 022 | train_loss=0.3272 | ce=0.3068 | ent=0.0000 | center=0.2040 | val_loss=0.1078 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9742 | val_dqn_proxy_expanded5=0.9309

Epoch 023 | train_loss=0.3253 | ce=0.3061 | ent=0.0000 | center=0.1922 | val_loss=0.1020 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9453 | val_dqn_proxy_expanded5=0.8890

Epoch 024 | train_loss=0.3258 | ce=0.3073 | ent=0.0000 | center=0.1851 | val_loss=0.1028 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9537 | val_dqn_proxy_expanded5=0.8920

Epoch 025 | train_loss=0.3240 | ce=0.3064 | ent=0.0000 | center=0.1759 | val_loss=0.0911 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9668 | val_dqn_proxy_expanded5=0.9138

Epoch 026 | train_loss=0.3218 | ce=0.3052 | ent=0.0000 | center=0.1656 | val_loss=0.1192 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9032 | val_dqn_proxy_expanded5=0.8641

Epoch 027 | train_loss=0.3230 | ce=0.3069 | ent=0.0000 | center=0.1615 | val_loss=0.1122 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9381 | val_dqn_proxy_expanded5=0.8822

Epoch 028 | train_loss=0.3233 | ce=0.3078 | ent=0.0000 | center=0.1544 | val_loss=0.0924 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8833 | val_dqn_proxy_expanded5=0.8410

Epoch 029 | train_loss=0.3229 | ce=0.3081 | ent=0.0000 | center=0.1473 | val_loss=0.0893 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9240 | val_dqn_proxy_expanded5=0.8730

Epoch 030 | train_loss=0.3444 | ce=0.3280 | ent=0.0000 | center=0.1644 | val_loss=0.1158 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8891 | val_dqn_proxy_expanded5=0.8643

Epoch 031 | train_loss=0.3321 | ce=0.3162 | ent=0.0000 | center=0.1590 | val_loss=0.1048 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8415 | val_dqn_proxy_expanded5=0.8209

Epoch 032 | train_loss=0.3276 | ce=0.3125 | ent=0.0000 | center=0.1514 | val_loss=0.1046 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9539 | val_dqn_proxy_expanded5=0.8952

Epoch 033 | train_loss=0.3213 | ce=0.3078 | ent=0.0000 | center=0.1345 | val_loss=0.1053 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9015 | val_dqn_proxy_expanded5=0.8533

Epoch 034 | train_loss=0.3206 | ce=0.3076 | ent=0.0000 | center=0.1298 | val_loss=0.1004 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9090 | val_dqn_proxy_expanded5=0.8552

Epoch 035 | train_loss=0.3204 | ce=0.3081 | ent=0.0000 | center=0.1226 | val_loss=0.0858 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9058 | val_dqn_proxy_expanded5=0.8619

Epoch 036 | train_loss=0.3177 | ce=0.3061 | ent=0.0000 | center=0.1160 | val_loss=0.0978 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8867 | val_dqn_proxy_expanded5=0.8453

Epoch 037 | train_loss=0.3163 | ce=0.3053 | ent=0.0000 | center=0.1099 | val_loss=0.0935 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9104 | val_dqn_proxy_expanded5=0.8573
Early stopping at epoch 37 (best epoch: 22)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
11,ref_base_ls002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
15,ref_base_ls000_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-04_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,ref_base_ls000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-59_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
8,ref_base_ls002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-47_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,ref_base_ls000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-56_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
17,ref_base_drop040_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-07_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,ref_base_ls002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-49_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
19,ref_base_drop040_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-11_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
5,ref_base_ls005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,ref_base_ls005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-45_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,ref_base_ls005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-42_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,ref_base_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,ref_base_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-29_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
4,ref_base_ls005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-36_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
18,ref_base_drop040_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-09_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
16,ref_base_drop040_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-06_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
10,ref_base_ls002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-53_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
14,ref_base_ls000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-02_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"

================================================================================
Running experiment 21/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "cosine",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": null,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_base_drop050",
  "lr": 0.0005,
  "label_smoothing": 0.1,
  "entropy_loss_weight": 0.0,
  "mlp_dropout": 0.5,
  "unknown_pas": [
    "PA2"
  ],
  "run_name": "ref_base_drop050_unkPA2_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.7262 | ce=0.6085 | ent=0.0000 | center=1.1773 | val_loss=0.1911 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9012 | val_dqn_proxy_expanded5=0.8747

Epoch 002 | train_loss=0.5272 | ce=0.4269 | ent=0.0000 | center=1.0027 | val_loss=0.1444 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8495 | val_dqn_proxy_expanded5=0.8230

Epoch 003 | train_loss=0.4694 | ce=0.3808 | ent=0.0000 | center=0.8862 | val_loss=0.1258 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6830 | val_dqn_proxy_expanded5=0.7281

Epoch 004 | train_loss=0.4506 | ce=0.3716 | ent=0.0000 | center=0.7894 | val_loss=0.1563 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8558 | val_dqn_proxy_expanded5=0.8222

Epoch 005 | train_loss=0.4393 | ce=0.3663 | ent=0.0000 | center=0.7301 | val_loss=0.1372 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7517 | val_dqn_proxy_expanded5=0.7928

Epoch 006 | train_loss=0.4184 | ce=0.3514 | ent=0.0000 | center=0.6706 | val_loss=0.1163 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6530 | val_dqn_proxy_expanded5=0.7221

Epoch 007 | train_loss=0.4163 | ce=0.3535 | ent=0.0000 | center=0.6284 | val_loss=0.1032 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7693 | val_dqn_proxy_expanded5=0.7859

Epoch 008 | train_loss=0.4043 | ce=0.3459 | ent=0.0000 | center=0.5836 | val_loss=0.1089 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9109 | val_dqn_proxy_expanded5=0.8689

Epoch 009 | train_loss=0.3885 | ce=0.3337 | ent=0.0000 | center=0.5482 | val_loss=0.0860 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8858 | val_dqn_proxy_expanded5=0.9007

Epoch 010 | train_loss=0.3879 | ce=0.3363 | ent=0.0000 | center=0.5163 | val_loss=0.0922 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7339 | val_dqn_proxy_expanded5=0.7677

Epoch 011 | train_loss=0.3746 | ce=0.3272 | ent=0.0000 | center=0.4739 | val_loss=0.0881 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8865 | val_dqn_proxy_expanded5=0.8824

Epoch 012 | train_loss=0.3679 | ce=0.3237 | ent=0.0000 | center=0.4421 | val_loss=0.0952 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6491 | val_dqn_proxy_expanded5=0.7036

Epoch 013 | train_loss=0.3671 | ce=0.3251 | ent=0.0000 | center=0.4205 | val_loss=0.0896 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6988 | val_dqn_proxy_expanded5=0.7443

Epoch 014 | train_loss=0.3671 | ce=0.3274 | ent=0.0000 | center=0.3968 | val_loss=0.0830 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8859 | val_dqn_proxy_expanded5=0.8871

Epoch 015 | train_loss=0.3656 | ce=0.3277 | ent=0.0000 | center=0.3791 | val_loss=0.1232 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7114 | val_dqn_proxy_expanded5=0.7420

Epoch 016 | train_loss=0.3589 | ce=0.3237 | ent=0.0000 | center=0.3523 | val_loss=0.1069 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6577 | val_dqn_proxy_expanded5=0.7122

Epoch 017 | train_loss=0.3568 | ce=0.3235 | ent=0.0000 | center=0.3331 | val_loss=0.0981 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8163 | val_dqn_proxy_expanded5=0.8334

Epoch 018 | train_loss=0.3483 | ce=0.3171 | ent=0.0000 | center=0.3112 | val_loss=0.1063 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8316 | val_dqn_proxy_expanded5=0.8386

Epoch 019 | train_loss=0.3565 | ce=0.3272 | ent=0.0000 | center=0.2930 | val_loss=0.1340 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6606 | val_dqn_proxy_expanded5=0.7055

Epoch 020 | train_loss=0.3668 | ce=0.3376 | ent=0.0000 | center=0.2920 | val_loss=0.1134 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8668 | val_dqn_proxy_expanded5=0.8294

Epoch 021 | train_loss=0.3568 | ce=0.3291 | ent=0.0000 | center=0.2768 | val_loss=0.1079 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8537 | val_dqn_proxy_expanded5=0.8341

Epoch 022 | train_loss=0.3538 | ce=0.3274 | ent=0.0000 | center=0.2635 | val_loss=0.1009 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8913 | val_dqn_proxy_expanded5=0.8658

Epoch 023 | train_loss=0.3467 | ce=0.3220 | ent=0.0000 | center=0.2464 | val_loss=0.1135 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9123 | val_dqn_proxy_expanded5=0.8914

Epoch 024 | train_loss=0.3422 | ce=0.3194 | ent=0.0000 | center=0.2275 | val_loss=0.0913 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9213 | val_dqn_proxy_expanded5=0.9040

Epoch 025 | train_loss=0.3444 | ce=0.3223 | ent=0.0000 | center=0.2206 | val_loss=0.1087 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.5180 | val_dqn_proxy_expanded5=0.6318

Epoch 026 | train_loss=0.3378 | ce=0.3171 | ent=0.0000 | center=0.2062 | val_loss=0.1039 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6668 | val_dqn_proxy_expanded5=0.7038

Epoch 027 | train_loss=0.3377 | ce=0.3180 | ent=0.0000 | center=0.1969 | val_loss=0.1145 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8924 | val_dqn_proxy_expanded5=0.8698

Epoch 028 | train_loss=0.3363 | ce=0.3178 | ent=0.0000 | center=0.1857 | val_loss=0.1186 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7996 | val_dqn_proxy_expanded5=0.7767

Epoch 029 | train_loss=0.3381 | ce=0.3198 | ent=0.0000 | center=0.1822 | val_loss=0.0987 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8099 | val_dqn_proxy_expanded5=0.8168

Epoch 030 | train_loss=0.3355 | ce=0.3184 | ent=0.0000 | center=0.1711 | val_loss=0.1094 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6732 | val_dqn_proxy_expanded5=0.7069

Epoch 031 | train_loss=0.3390 | ce=0.3225 | ent=0.0000 | center=0.1656 | val_loss=0.0836 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7877 | val_dqn_proxy_expanded5=0.7643

Epoch 032 | train_loss=0.3368 | ce=0.3206 | ent=0.0000 | center=0.1627 | val_loss=0.1034 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8095 | val_dqn_proxy_expanded5=0.7837

Epoch 033 | train_loss=0.3414 | ce=0.3262 | ent=0.0000 | center=0.1526 | val_loss=0.1601 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7672 | val_dqn_proxy_expanded5=0.7938

Epoch 034 | train_loss=0.3416 | ce=0.3262 | ent=0.0000 | center=0.1549 | val_loss=0.0966 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8717 | val_dqn_proxy_expanded5=0.8397

Epoch 035 | train_loss=0.3298 | ce=0.3158 | ent=0.0000 | center=0.1396 | val_loss=0.1046 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9138 | val_dqn_proxy_expanded5=0.8897

Epoch 036 | train_loss=0.3385 | ce=0.3244 | ent=0.0000 | center=0.1404 | val_loss=0.0951 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8835 | val_dqn_proxy_expanded5=0.8514

Epoch 037 | train_loss=0.3527 | ce=0.3386 | ent=0.0000 | center=0.1413 | val_loss=0.1183 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9245 | val_dqn_proxy_expanded5=0.9082

Epoch 038 | train_loss=0.3379 | ce=0.3239 | ent=0.0000 | center=0.1399 | val_loss=0.1162 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7164 | val_dqn_proxy_expanded5=0.7158

Epoch 039 | train_loss=0.3363 | ce=0.3228 | ent=0.0000 | center=0.1352 | val_loss=0.1090 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.5755 | val_dqn_proxy_expanded5=0.6355

Epoch 040 | train_loss=0.3320 | ce=0.3197 | ent=0.0000 | center=0.1232 | val_loss=0.1022 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7624 | val_dqn_proxy_expanded5=0.7423

Epoch 041 | train_loss=0.3312 | ce=0.3195 | ent=0.0000 | center=0.1173 | val_loss=0.1219 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7993 | val_dqn_proxy_expanded5=0.7870

Epoch 042 | train_loss=0.3332 | ce=0.3219 | ent=0.0000 | center=0.1131 | val_loss=0.0930 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8306 | val_dqn_proxy_expanded5=0.8226

Epoch 043 | train_loss=0.3397 | ce=0.3283 | ent=0.0000 | center=0.1142 | val_loss=0.1069 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8972 | val_dqn_proxy_expanded5=0.8698

Epoch 044 | train_loss=0.3307 | ce=0.3199 | ent=0.0000 | center=0.1079 | val_loss=0.0976 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7515 | val_dqn_proxy_expanded5=0.7368

Epoch 045 | train_loss=0.3268 | ce=0.3164 | ent=0.0000 | center=0.1045 | val_loss=0.1018 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8099 | val_dqn_proxy_expanded5=0.7811

Epoch 046 | train_loss=0.3245 | ce=0.3149 | ent=0.0000 | center=0.0960 | val_loss=0.1114 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6916 | val_dqn_proxy_expanded5=0.6891

Epoch 047 | train_loss=0.3246 | ce=0.3154 | ent=0.0000 | center=0.0918 | val_loss=0.1041 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8897 | val_dqn_proxy_expanded5=0.8400

Epoch 048 | train_loss=0.3262 | ce=0.3173 | ent=0.0000 | center=0.0888 | val_loss=0.1227 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9175 | val_dqn_proxy_expanded5=0.8693

Epoch 049 | train_loss=0.3232 | ce=0.3147 | ent=0.0000 | center=0.0850 | val_loss=0.0996 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8740 | val_dqn_proxy_expanded5=0.8312

Epoch 050 | train_loss=0.3228 | ce=0.3147 | ent=0.0000 | center=0.0814 | val_loss=0.1037 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8519 | val_dqn_proxy_expanded5=0.8148

Epoch 051 | train_loss=0.3240 | ce=0.3159 | ent=0.0000 | center=0.0810 | val_loss=0.1177 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8667 | val_dqn_proxy_expanded5=0.8366

Epoch 052 | train_loss=0.3262 | ce=0.3184 | ent=0.0000 | center=0.0776 | val_loss=0.1196 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8113 | val_dqn_proxy_expanded5=0.8147
Early stopping at epoch 52 (best epoch: 37)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
11,ref_base_ls002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
15,ref_base_ls000_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-04_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,ref_base_ls000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-59_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
8,ref_base_ls002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-47_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,ref_base_ls000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-56_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
17,ref_base_drop040_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-07_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,ref_base_ls002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-49_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
19,ref_base_drop040_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-11_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
5,ref_base_ls005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,ref_base_ls005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-45_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,ref_base_ls005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-42_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,ref_base_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
20,ref_base_drop050_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-14_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
2,ref_base_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-29_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
4,ref_base_ls005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-36_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
18,ref_base_drop040_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-09_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
16,ref_base_drop040_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-06_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
10,ref_base_ls002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-53_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
14,ref_base_ls000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-02_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"

================================================================================
Running experiment 22/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "cosine",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": null,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_base_drop050",
  "lr": 0.0005,
  "label_smoothing": 0.1,
  "entropy_loss_weight": 0.0,
  "mlp_dropout": 0.5,
  "unknown_pas": [
    "PA3"
  ],
  "run_name": "ref_base_drop050_unkPA3_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.7907 | ce=0.6676 | ent=0.0000 | center=1.2310 | val_loss=0.2292 | val_acc=0.9593 | val_macro_f1=0.9592 | val_dqn_proxy_softmax3=0.8272 | val_dqn_proxy_expanded5=0.7910

Epoch 002 | train_loss=0.5747 | ce=0.4651 | ent=0.0000 | center=1.0960 | val_loss=0.2065 | val_acc=0.9444 | val_macro_f1=0.9443 | val_dqn_proxy_softmax3=0.8094 | val_dqn_proxy_expanded5=0.7684

Epoch 003 | train_loss=0.5484 | ce=0.4526 | ent=0.0000 | center=0.9584 | val_loss=0.1745 | val_acc=0.9519 | val_macro_f1=0.9521 | val_dqn_proxy_softmax3=0.7704 | val_dqn_proxy_expanded5=0.7778

Epoch 004 | train_loss=0.5115 | ce=0.4249 | ent=0.0000 | center=0.8657 | val_loss=0.2208 | val_acc=0.9370 | val_macro_f1=0.9366 | val_dqn_proxy_softmax3=0.9299 | val_dqn_proxy_expanded5=0.8800

Epoch 005 | train_loss=0.4788 | ce=0.3987 | ent=0.0000 | center=0.8017 | val_loss=0.2109 | val_acc=0.9333 | val_macro_f1=0.9334 | val_dqn_proxy_softmax3=0.8500 | val_dqn_proxy_expanded5=0.8270

Epoch 006 | train_loss=0.4697 | ce=0.3954 | ent=0.0000 | center=0.7436 | val_loss=0.1439 | val_acc=0.9667 | val_macro_f1=0.9666 | val_dqn_proxy_softmax3=0.9253 | val_dqn_proxy_expanded5=0.8670

Epoch 007 | train_loss=0.4476 | ce=0.3791 | ent=0.0000 | center=0.6847 | val_loss=0.1296 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9274 | val_dqn_proxy_expanded5=0.8718

Epoch 008 | train_loss=0.4508 | ce=0.3864 | ent=0.0000 | center=0.6434 | val_loss=0.1404 | val_acc=0.9704 | val_macro_f1=0.9703 | val_dqn_proxy_softmax3=0.7688 | val_dqn_proxy_expanded5=0.8125

Epoch 009 | train_loss=0.4299 | ce=0.3697 | ent=0.0000 | center=0.6025 | val_loss=0.0990 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7730 | val_dqn_proxy_expanded5=0.7732

Epoch 010 | train_loss=0.4152 | ce=0.3589 | ent=0.0000 | center=0.5630 | val_loss=0.1207 | val_acc=0.9741 | val_macro_f1=0.9740 | val_dqn_proxy_softmax3=0.9377 | val_dqn_proxy_expanded5=0.8987

Epoch 011 | train_loss=0.4110 | ce=0.3581 | ent=0.0000 | center=0.5294 | val_loss=0.1376 | val_acc=0.9704 | val_macro_f1=0.9703 | val_dqn_proxy_softmax3=0.8703 | val_dqn_proxy_expanded5=0.8311

Epoch 012 | train_loss=0.4177 | ce=0.3677 | ent=0.0000 | center=0.5001 | val_loss=0.2149 | val_acc=0.9444 | val_macro_f1=0.9441 | val_dqn_proxy_softmax3=0.7218 | val_dqn_proxy_expanded5=0.7575

Epoch 013 | train_loss=0.4157 | ce=0.3680 | ent=0.0000 | center=0.4769 | val_loss=0.1032 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.6709 | val_dqn_proxy_expanded5=0.7716

Epoch 014 | train_loss=0.3969 | ce=0.3525 | ent=0.0000 | center=0.4436 | val_loss=0.1192 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.7806 | val_dqn_proxy_expanded5=0.7981

Epoch 015 | train_loss=0.4021 | ce=0.3602 | ent=0.0000 | center=0.4187 | val_loss=0.1456 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.7709 | val_dqn_proxy_expanded5=0.7463

Epoch 016 | train_loss=0.3928 | ce=0.3530 | ent=0.0000 | center=0.3978 | val_loss=0.1301 | val_acc=0.9741 | val_macro_f1=0.9741 | val_dqn_proxy_softmax3=0.8298 | val_dqn_proxy_expanded5=0.7929

Epoch 017 | train_loss=0.4008 | ce=0.3626 | ent=0.0000 | center=0.3822 | val_loss=0.1142 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9453 | val_dqn_proxy_expanded5=0.8781

Epoch 018 | train_loss=0.3924 | ce=0.3560 | ent=0.0000 | center=0.3647 | val_loss=0.1510 | val_acc=0.9630 | val_macro_f1=0.9628 | val_dqn_proxy_softmax3=0.9244 | val_dqn_proxy_expanded5=0.8697

Epoch 019 | train_loss=0.3705 | ce=0.3367 | ent=0.0000 | center=0.3377 | val_loss=0.1135 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9750 | val_dqn_proxy_expanded5=0.9375

Epoch 020 | train_loss=0.3799 | ce=0.3474 | ent=0.0000 | center=0.3259 | val_loss=0.0996 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9377 | val_dqn_proxy_expanded5=0.8906

Epoch 021 | train_loss=0.3668 | ce=0.3360 | ent=0.0000 | center=0.3082 | val_loss=0.1248 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.8394 | val_dqn_proxy_expanded5=0.8074

Epoch 022 | train_loss=0.3635 | ce=0.3342 | ent=0.0000 | center=0.2927 | val_loss=0.0962 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9826 | val_dqn_proxy_expanded5=0.9343

Epoch 023 | train_loss=0.3721 | ce=0.3437 | ent=0.0000 | center=0.2841 | val_loss=0.0946 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9502 | val_dqn_proxy_expanded5=0.8984

Epoch 024 | train_loss=0.3565 | ce=0.3297 | ent=0.0000 | center=0.2678 | val_loss=0.1380 | val_acc=0.9704 | val_macro_f1=0.9703 | val_dqn_proxy_softmax3=0.8810 | val_dqn_proxy_expanded5=0.8281

Epoch 025 | train_loss=0.3659 | ce=0.3397 | ent=0.0000 | center=0.2619 | val_loss=0.1081 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9816 | val_dqn_proxy_expanded5=0.9523

Epoch 026 | train_loss=0.3925 | ce=0.3666 | ent=0.0000 | center=0.2586 | val_loss=0.1341 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9146 | val_dqn_proxy_expanded5=0.8752

Epoch 027 | train_loss=0.3668 | ce=0.3415 | ent=0.0000 | center=0.2523 | val_loss=0.1195 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8252 | val_dqn_proxy_expanded5=0.7954

Epoch 028 | train_loss=0.3621 | ce=0.3386 | ent=0.0000 | center=0.2351 | val_loss=0.1594 | val_acc=0.9704 | val_macro_f1=0.9703 | val_dqn_proxy_softmax3=0.8180 | val_dqn_proxy_expanded5=0.7978

Epoch 029 | train_loss=0.3532 | ce=0.3313 | ent=0.0000 | center=0.2192 | val_loss=0.1137 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9622 | val_dqn_proxy_expanded5=0.9113

Epoch 030 | train_loss=0.3532 | ce=0.3322 | ent=0.0000 | center=0.2096 | val_loss=0.1095 | val_acc=0.9741 | val_macro_f1=0.9740 | val_dqn_proxy_softmax3=0.8171 | val_dqn_proxy_expanded5=0.7902

Epoch 031 | train_loss=0.3542 | ce=0.3340 | ent=0.0000 | center=0.2022 | val_loss=0.1000 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9700 | val_dqn_proxy_expanded5=0.9440

Epoch 032 | train_loss=0.3469 | ce=0.3271 | ent=0.0000 | center=0.1983 | val_loss=0.1191 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9132 | val_dqn_proxy_expanded5=0.8642

Epoch 033 | train_loss=0.3511 | ce=0.3322 | ent=0.0000 | center=0.1887 | val_loss=0.1321 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.8775 | val_dqn_proxy_expanded5=0.8433

Epoch 034 | train_loss=0.3501 | ce=0.3313 | ent=0.0000 | center=0.1885 | val_loss=0.0944 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.8073 | val_dqn_proxy_expanded5=0.7937

Epoch 035 | train_loss=0.3423 | ce=0.3246 | ent=0.0000 | center=0.1768 | val_loss=0.0885 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9753 | val_dqn_proxy_expanded5=0.9301

Epoch 036 | train_loss=0.3547 | ce=0.3371 | ent=0.0000 | center=0.1754 | val_loss=0.0892 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9812 | val_dqn_proxy_expanded5=0.9460

Epoch 037 | train_loss=0.3468 | ce=0.3294 | ent=0.0000 | center=0.1748 | val_loss=0.1307 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.7856 | val_dqn_proxy_expanded5=0.7809
Early stopping at epoch 37 (best epoch: 22)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
11,ref_base_ls002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
15,ref_base_ls000_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-04_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,ref_base_ls000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-59_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
8,ref_base_ls002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-47_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,ref_base_ls000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-56_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
17,ref_base_drop040_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-07_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,ref_base_ls002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-49_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
19,ref_base_drop040_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-11_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
5,ref_base_ls005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,ref_base_ls005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-45_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,ref_base_ls005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-42_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,ref_base_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
21,ref_base_drop050_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-18_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
20,ref_base_drop050_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-14_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
2,ref_base_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-29_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
4,ref_base_ls005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-36_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
18,ref_base_drop040_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-09_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
16,ref_base_drop040_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-06_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
10,ref_base_ls002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-53_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
14,ref_base_ls000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-02_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"

================================================================================
Running experiment 23/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "cosine",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": null,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_base_drop050",
  "lr": 0.0005,
  "label_smoothing": 0.1,
  "entropy_loss_weight": 0.0,
  "mlp_dropout": 0.5,
  "unknown_pas": [
    "PA4"
  ],
  "run_name": "ref_base_drop050_unkPA4_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.8083 | ce=0.6770 | ent=0.0000 | center=1.3133 | val_loss=0.3576 | val_acc=0.9074 | val_macro_f1=0.9068 | val_dqn_proxy_softmax3=0.7328 | val_dqn_proxy_expanded5=0.6689

Epoch 002 | train_loss=0.5925 | ce=0.4775 | ent=0.0000 | center=1.1499 | val_loss=0.2605 | val_acc=0.9296 | val_macro_f1=0.9289 | val_dqn_proxy_softmax3=0.7154 | val_dqn_proxy_expanded5=0.7006

Epoch 003 | train_loss=0.5912 | ce=0.4890 | ent=0.0000 | center=1.0220 | val_loss=0.1923 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.7129 | val_dqn_proxy_expanded5=0.7010

Epoch 004 | train_loss=0.5344 | ce=0.4395 | ent=0.0000 | center=0.9488 | val_loss=0.2167 | val_acc=0.9556 | val_macro_f1=0.9558 | val_dqn_proxy_softmax3=0.7035 | val_dqn_proxy_expanded5=0.6777

Epoch 005 | train_loss=0.4821 | ce=0.3964 | ent=0.0000 | center=0.8572 | val_loss=0.1839 | val_acc=0.9630 | val_macro_f1=0.9628 | val_dqn_proxy_softmax3=0.7787 | val_dqn_proxy_expanded5=0.7084

Epoch 006 | train_loss=0.4784 | ce=0.3982 | ent=0.0000 | center=0.8027 | val_loss=0.1771 | val_acc=0.9444 | val_macro_f1=0.9441 | val_dqn_proxy_softmax3=0.9017 | val_dqn_proxy_expanded5=0.8302

Epoch 007 | train_loss=0.4714 | ce=0.3969 | ent=0.0000 | center=0.7448 | val_loss=0.2560 | val_acc=0.9296 | val_macro_f1=0.9288 | val_dqn_proxy_softmax3=0.8372 | val_dqn_proxy_expanded5=0.7498

Epoch 008 | train_loss=0.4416 | ce=0.3726 | ent=0.0000 | center=0.6894 | val_loss=0.1482 | val_acc=0.9741 | val_macro_f1=0.9740 | val_dqn_proxy_softmax3=0.7613 | val_dqn_proxy_expanded5=0.7223

Epoch 009 | train_loss=0.4379 | ce=0.3734 | ent=0.0000 | center=0.6456 | val_loss=0.1154 | val_acc=0.9704 | val_macro_f1=0.9704 | val_dqn_proxy_softmax3=0.8977 | val_dqn_proxy_expanded5=0.8469

Epoch 010 | train_loss=0.4358 | ce=0.3756 | ent=0.0000 | center=0.6026 | val_loss=0.1213 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.6980 | val_dqn_proxy_expanded5=0.7230

Epoch 011 | train_loss=0.4112 | ce=0.3546 | ent=0.0000 | center=0.5657 | val_loss=0.1403 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.7492 | val_dqn_proxy_expanded5=0.7385

Epoch 012 | train_loss=0.4072 | ce=0.3541 | ent=0.0000 | center=0.5302 | val_loss=0.1292 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7589 | val_dqn_proxy_expanded5=0.7392

Epoch 013 | train_loss=0.3992 | ce=0.3480 | ent=0.0000 | center=0.5121 | val_loss=0.1348 | val_acc=0.9667 | val_macro_f1=0.9669 | val_dqn_proxy_softmax3=0.9327 | val_dqn_proxy_expanded5=0.8884

Epoch 014 | train_loss=0.4129 | ce=0.3651 | ent=0.0000 | center=0.4776 | val_loss=0.0987 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7527 | val_dqn_proxy_expanded5=0.7461

Epoch 015 | train_loss=0.3874 | ce=0.3409 | ent=0.0000 | center=0.4650 | val_loss=0.1531 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7659 | val_dqn_proxy_expanded5=0.7400

Epoch 016 | train_loss=0.3908 | ce=0.3480 | ent=0.0000 | center=0.4282 | val_loss=0.0992 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.7616 | val_dqn_proxy_expanded5=0.7408

Epoch 017 | train_loss=0.3759 | ce=0.3352 | ent=0.0000 | center=0.4070 | val_loss=0.1392 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.7635 | val_dqn_proxy_expanded5=0.7364

Epoch 018 | train_loss=0.3820 | ce=0.3432 | ent=0.0000 | center=0.3877 | val_loss=0.1027 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.7789 | val_dqn_proxy_expanded5=0.7531

Epoch 019 | train_loss=0.3860 | ce=0.3493 | ent=0.0000 | center=0.3672 | val_loss=0.1497 | val_acc=0.9593 | val_macro_f1=0.9591 | val_dqn_proxy_softmax3=0.7521 | val_dqn_proxy_expanded5=0.7143

Epoch 020 | train_loss=0.3719 | ce=0.3361 | ent=0.0000 | center=0.3577 | val_loss=0.1092 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.8798 | val_dqn_proxy_expanded5=0.8225

Epoch 021 | train_loss=0.3681 | ce=0.3344 | ent=0.0000 | center=0.3369 | val_loss=0.1482 | val_acc=0.9667 | val_macro_f1=0.9666 | val_dqn_proxy_softmax3=0.7438 | val_dqn_proxy_expanded5=0.7346

Epoch 022 | train_loss=0.3764 | ce=0.3441 | ent=0.0000 | center=0.3228 | val_loss=0.1128 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7611 | val_dqn_proxy_expanded5=0.7317

Epoch 023 | train_loss=0.3634 | ce=0.3329 | ent=0.0000 | center=0.3056 | val_loss=0.1564 | val_acc=0.9481 | val_macro_f1=0.9478 | val_dqn_proxy_softmax3=0.7438 | val_dqn_proxy_expanded5=0.7644

Epoch 024 | train_loss=0.3580 | ce=0.3291 | ent=0.0000 | center=0.2892 | val_loss=0.1196 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.7860 | val_dqn_proxy_expanded5=0.7533

Epoch 025 | train_loss=0.3518 | ce=0.3241 | ent=0.0000 | center=0.2770 | val_loss=0.0892 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.7917 | val_dqn_proxy_expanded5=0.7588

Epoch 026 | train_loss=0.3480 | ce=0.3218 | ent=0.0000 | center=0.2619 | val_loss=0.0864 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7723 | val_dqn_proxy_expanded5=0.7610

Epoch 027 | train_loss=0.3687 | ce=0.3434 | ent=0.0000 | center=0.2523 | val_loss=0.1202 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.7506 | val_dqn_proxy_expanded5=0.7616

Epoch 028 | train_loss=0.3632 | ce=0.3381 | ent=0.0000 | center=0.2513 | val_loss=0.0909 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9602 | val_dqn_proxy_expanded5=0.8831

Epoch 029 | train_loss=0.3629 | ce=0.3391 | ent=0.0000 | center=0.2383 | val_loss=0.1020 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.7792 | val_dqn_proxy_expanded5=0.7628

Epoch 030 | train_loss=0.3479 | ce=0.3248 | ent=0.0000 | center=0.2313 | val_loss=0.0917 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.7761 | val_dqn_proxy_expanded5=0.7808

Epoch 031 | train_loss=0.3580 | ce=0.3363 | ent=0.0000 | center=0.2174 | val_loss=0.1024 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.7587 | val_dqn_proxy_expanded5=0.7532

Epoch 032 | train_loss=0.3556 | ce=0.3339 | ent=0.0000 | center=0.2170 | val_loss=0.0969 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.7288 | val_dqn_proxy_expanded5=0.7386

Epoch 033 | train_loss=0.3494 | ce=0.3290 | ent=0.0000 | center=0.2041 | val_loss=0.1011 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.7995 | val_dqn_proxy_expanded5=0.8070

Epoch 034 | train_loss=0.3478 | ce=0.3285 | ent=0.0000 | center=0.1937 | val_loss=0.1065 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.7711 | val_dqn_proxy_expanded5=0.7447

Epoch 035 | train_loss=0.3414 | ce=0.3232 | ent=0.0000 | center=0.1825 | val_loss=0.1194 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7713 | val_dqn_proxy_expanded5=0.7627

Epoch 036 | train_loss=0.3468 | ce=0.3289 | ent=0.0000 | center=0.1797 | val_loss=0.1144 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.7456 | val_dqn_proxy_expanded5=0.7642

Epoch 037 | train_loss=0.3410 | ce=0.3235 | ent=0.0000 | center=0.1754 | val_loss=0.0858 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.7811 | val_dqn_proxy_expanded5=0.7568

Epoch 038 | train_loss=0.3465 | ce=0.3301 | ent=0.0000 | center=0.1644 | val_loss=0.1074 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.7847 | val_dqn_proxy_expanded5=0.7561

Epoch 039 | train_loss=0.3564 | ce=0.3402 | ent=0.0000 | center=0.1616 | val_loss=0.1019 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.6851 | val_dqn_proxy_expanded5=0.7046

Epoch 040 | train_loss=0.3425 | ce=0.3265 | ent=0.0000 | center=0.1599 | val_loss=0.0908 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7826 | val_dqn_proxy_expanded5=0.7612

Epoch 041 | train_loss=0.3395 | ce=0.3244 | ent=0.0000 | center=0.1513 | val_loss=0.1127 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7764 | val_dqn_proxy_expanded5=0.7699

Epoch 042 | train_loss=0.3362 | ce=0.3216 | ent=0.0000 | center=0.1457 | val_loss=0.0892 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7765 | val_dqn_proxy_expanded5=0.7609

Epoch 043 | train_loss=0.3391 | ce=0.3245 | ent=0.0000 | center=0.1465 | val_loss=0.1321 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7216 | val_dqn_proxy_expanded5=0.7459
Early stopping at epoch 43 (best epoch: 28)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
11,ref_base_ls002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
15,ref_base_ls000_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-04_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,ref_base_ls000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-59_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
8,ref_base_ls002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-47_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,ref_base_ls000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-56_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
17,ref_base_drop040_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-07_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,ref_base_ls002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-49_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
19,ref_base_drop040_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-11_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
5,ref_base_ls005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,ref_base_ls005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-45_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,ref_base_ls005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-42_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,ref_base_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
21,ref_base_drop050_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-18_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
20,ref_base_drop050_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-14_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
2,ref_base_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-29_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
22,ref_base_drop050_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-21_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,ref_base_ls005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-36_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
18,ref_base_drop040_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-09_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
16,ref_base_drop040_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-06_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
10,ref_base_ls002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-53_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
14,ref_base_ls000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-02_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"

================================================================================
Running experiment 24/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "cosine",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": null,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_base_drop050",
  "lr": 0.0005,
  "label_smoothing": 0.1,
  "entropy_loss_weight": 0.0,
  "mlp_dropout": 0.5,
  "unknown_pas": [
    "PA8"
  ],
  "run_name": "ref_base_drop050_unkPA8_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.6639 | ce=0.5375 | ent=0.0000 | center=1.2647 | val_loss=0.1389 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9698 | val_dqn_proxy_expanded5=0.9603

Epoch 002 | train_loss=0.4675 | ce=0.3633 | ent=0.0000 | center=1.0414 | val_loss=0.1305 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9656 | val_dqn_proxy_expanded5=0.9607

Epoch 003 | train_loss=0.4597 | ce=0.3677 | ent=0.0000 | center=0.9198 | val_loss=0.1408 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9647 | val_dqn_proxy_expanded5=0.9485

Epoch 004 | train_loss=0.4294 | ce=0.3472 | ent=0.0000 | center=0.8222 | val_loss=0.1159 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8836 | val_dqn_proxy_expanded5=0.8737

Epoch 005 | train_loss=0.4225 | ce=0.3460 | ent=0.0000 | center=0.7650 | val_loss=0.1058 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8545 | val_dqn_proxy_expanded5=0.8607

Epoch 006 | train_loss=0.4064 | ce=0.3354 | ent=0.0000 | center=0.7097 | val_loss=0.0935 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9367 | val_dqn_proxy_expanded5=0.9383

Epoch 007 | train_loss=0.3937 | ce=0.3279 | ent=0.0000 | center=0.6583 | val_loss=0.1085 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9359 | val_dqn_proxy_expanded5=0.9177

Epoch 008 | train_loss=0.3869 | ce=0.3262 | ent=0.0000 | center=0.6074 | val_loss=0.1006 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9478 | val_dqn_proxy_expanded5=0.9281

Epoch 009 | train_loss=0.3760 | ce=0.3199 | ent=0.0000 | center=0.5607 | val_loss=0.0885 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9554 | val_dqn_proxy_expanded5=0.9495

Epoch 010 | train_loss=0.3674 | ce=0.3154 | ent=0.0000 | center=0.5194 | val_loss=0.1068 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8967 | val_dqn_proxy_expanded5=0.9044

Epoch 011 | train_loss=0.3682 | ce=0.3192 | ent=0.0000 | center=0.4894 | val_loss=0.0933 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9218 | val_dqn_proxy_expanded5=0.8988

Epoch 012 | train_loss=0.3649 | ce=0.3192 | ent=0.0000 | center=0.4574 | val_loss=0.1097 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9666 | val_dqn_proxy_expanded5=0.9326

Epoch 013 | train_loss=0.3610 | ce=0.3177 | ent=0.0000 | center=0.4333 | val_loss=0.1043 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8950 | val_dqn_proxy_expanded5=0.8983

Epoch 014 | train_loss=0.3566 | ce=0.3162 | ent=0.0000 | center=0.4045 | val_loss=0.0990 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9059 | val_dqn_proxy_expanded5=0.9260

Epoch 015 | train_loss=0.3516 | ce=0.3135 | ent=0.0000 | center=0.3815 | val_loss=0.1071 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9449 | val_dqn_proxy_expanded5=0.9215

Epoch 016 | train_loss=0.3493 | ce=0.3138 | ent=0.0000 | center=0.3548 | val_loss=0.1028 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8408 | val_dqn_proxy_expanded5=0.8518
Early stopping at epoch 16 (best epoch: 1)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
23,ref_base_drop050_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-25_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
11,ref_base_ls002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
15,ref_base_ls000_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-04_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,ref_base_ls000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-59_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
8,ref_base_ls002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-47_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,ref_base_ls000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-56_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
17,ref_base_drop040_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-07_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,ref_base_ls002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-49_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
19,ref_base_drop040_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-11_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
5,ref_base_ls005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,ref_base_ls005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-45_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,ref_base_ls005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-42_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,ref_base_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
21,ref_base_drop050_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-18_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
20,ref_base_drop050_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-14_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
2,ref_base_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-29_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
22,ref_base_drop050_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-21_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,ref_base_ls005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-36_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
18,ref_base_drop040_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-09_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
16,ref_base_drop040_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-06_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
10,ref_base_ls002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-53_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
14,ref_base_ls000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-02_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"

================================================================================
Running experiment 25/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "cosine",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": null,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_base_ent002",
  "lr": 0.0005,
  "label_smoothing": 0.1,
  "entropy_loss_weight": 0.02,
  "mlp_dropout": 0.3,
  "unknown_pas": [
    "PA2"
  ],
  "run_name": "ref_base_ent002_unkPA2_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.6468 | ce=0.5287 | ent=0.5457 | center=1.0722 | val_loss=0.1681 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8171 | val_dqn_proxy_expanded5=0.7908

Epoch 002 | train_loss=0.4824 | ce=0.3901 | ent=0.3893 | center=0.8450 | val_loss=0.1139 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8891 | val_dqn_proxy_expanded5=0.8754

Epoch 003 | train_loss=0.4358 | ce=0.3574 | ent=0.3585 | center=0.7126 | val_loss=0.1395 | val_acc=0.9741 | val_macro_f1=0.9742 | val_dqn_proxy_softmax3=0.8592 | val_dqn_proxy_expanded5=0.8684

Epoch 004 | train_loss=0.4237 | ce=0.3527 | ent=0.3472 | center=0.6405 | val_loss=0.1164 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8565 | val_dqn_proxy_expanded5=0.8753

Epoch 005 | train_loss=0.4215 | ce=0.3564 | ent=0.3450 | center=0.5827 | val_loss=0.1301 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8405 | val_dqn_proxy_expanded5=0.8320

Epoch 006 | train_loss=0.4044 | ce=0.3433 | ent=0.3370 | center=0.5438 | val_loss=0.0958 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8337 | val_dqn_proxy_expanded5=0.8406

Epoch 007 | train_loss=0.3760 | ce=0.3219 | ent=0.3122 | center=0.4788 | val_loss=0.0874 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7811 | val_dqn_proxy_expanded5=0.8076

Epoch 008 | train_loss=0.3706 | ce=0.3208 | ent=0.3119 | center=0.4351 | val_loss=0.0962 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9312 | val_dqn_proxy_expanded5=0.9189

Epoch 009 | train_loss=0.3679 | ce=0.3216 | ent=0.3086 | center=0.4015 | val_loss=0.0950 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6881 | val_dqn_proxy_expanded5=0.7542

Epoch 010 | train_loss=0.3883 | ce=0.3440 | ent=0.3246 | center=0.3781 | val_loss=0.0814 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.5437 | val_dqn_proxy_expanded5=0.6360

Epoch 011 | train_loss=0.3585 | ce=0.3176 | ent=0.3117 | center=0.3471 | val_loss=0.0810 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7301 | val_dqn_proxy_expanded5=0.7653

Epoch 012 | train_loss=0.3536 | ce=0.3165 | ent=0.3023 | center=0.3111 | val_loss=0.0847 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9019 | val_dqn_proxy_expanded5=0.8837

Epoch 013 | train_loss=0.3566 | ce=0.3211 | ent=0.3103 | center=0.2930 | val_loss=0.0828 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7966 | val_dqn_proxy_expanded5=0.8070

Epoch 014 | train_loss=0.3504 | ce=0.3170 | ent=0.2987 | center=0.2744 | val_loss=0.1150 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6998 | val_dqn_proxy_expanded5=0.7184

Epoch 015 | train_loss=0.3490 | ce=0.3169 | ent=0.3062 | center=0.2598 | val_loss=0.0854 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6571 | val_dqn_proxy_expanded5=0.7039

Epoch 016 | train_loss=0.3443 | ce=0.3144 | ent=0.3000 | center=0.2383 | val_loss=0.1003 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7312 | val_dqn_proxy_expanded5=0.7618

Epoch 017 | train_loss=0.3461 | ce=0.3171 | ent=0.3035 | center=0.2285 | val_loss=0.0941 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6292 | val_dqn_proxy_expanded5=0.6845

Epoch 018 | train_loss=0.3413 | ce=0.3135 | ent=0.2977 | center=0.2184 | val_loss=0.1004 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6410 | val_dqn_proxy_expanded5=0.6915

Epoch 019 | train_loss=0.3482 | ce=0.3213 | ent=0.3073 | center=0.2072 | val_loss=0.0886 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7090 | val_dqn_proxy_expanded5=0.7488

Epoch 020 | train_loss=0.3387 | ce=0.3132 | ent=0.2996 | center=0.1954 | val_loss=0.1095 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8207 | val_dqn_proxy_expanded5=0.8141

Epoch 021 | train_loss=0.3414 | ce=0.3167 | ent=0.3044 | center=0.1863 | val_loss=0.0837 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6857 | val_dqn_proxy_expanded5=0.7253

Epoch 022 | train_loss=0.3375 | ce=0.3139 | ent=0.3006 | center=0.1759 | val_loss=0.0954 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8398 | val_dqn_proxy_expanded5=0.8294

Epoch 023 | train_loss=0.3375 | ce=0.3149 | ent=0.2996 | center=0.1666 | val_loss=0.1014 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6717 | val_dqn_proxy_expanded5=0.6962
Early stopping at epoch 23 (best epoch: 8)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
23,ref_base_drop050_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-25_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
11,ref_base_ls002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
15,ref_base_ls000_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-04_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,ref_base_ls000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-59_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
8,ref_base_ls002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-47_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,ref_base_ls000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-56_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
17,ref_base_drop040_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-07_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,ref_base_ls002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-49_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
24,ref_base_ent002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-26_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
19,ref_base_drop040_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-11_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
5,ref_base_ls005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,ref_base_ls005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-45_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,ref_base_ls005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-42_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,ref_base_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
21,ref_base_drop050_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-18_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
20,ref_base_drop050_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-14_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
2,ref_base_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-29_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
22,ref_base_drop050_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-21_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,ref_base_ls005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-36_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
18,ref_base_drop040_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-09_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
16,ref_base_drop040_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-06_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
10,ref_base_ls002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-53_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
14,ref_base_ls000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-02_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"

================================================================================
Running experiment 26/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "cosine",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": null,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_base_ent002",
  "lr": 0.0005,
  "label_smoothing": 0.1,
  "entropy_loss_weight": 0.02,
  "mlp_dropout": 0.3,
  "unknown_pas": [
    "PA3"
  ],
  "run_name": "ref_base_ent002_unkPA3_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.7492 | ce=0.6347 | ent=0.6409 | center=1.0177 | val_loss=0.1933 | val_acc=0.9481 | val_macro_f1=0.9484 | val_dqn_proxy_softmax3=0.8637 | val_dqn_proxy_expanded5=0.8651

Epoch 002 | train_loss=0.5547 | ce=0.4607 | ent=0.4543 | center=0.8492 | val_loss=0.2314 | val_acc=0.9407 | val_macro_f1=0.9400 | val_dqn_proxy_softmax3=0.8582 | val_dqn_proxy_expanded5=0.8624

Epoch 003 | train_loss=0.5085 | ce=0.4264 | ent=0.4284 | center=0.7350 | val_loss=0.1922 | val_acc=0.9444 | val_macro_f1=0.9441 | val_dqn_proxy_softmax3=0.8439 | val_dqn_proxy_expanded5=0.8493

Epoch 004 | train_loss=0.4623 | ce=0.3899 | ent=0.3875 | center=0.6468 | val_loss=0.1338 | val_acc=0.9593 | val_macro_f1=0.9591 | val_dqn_proxy_softmax3=0.9537 | val_dqn_proxy_expanded5=0.9520

Epoch 005 | train_loss=0.4594 | ce=0.3946 | ent=0.3838 | center=0.5714 | val_loss=0.1794 | val_acc=0.9444 | val_macro_f1=0.9441 | val_dqn_proxy_softmax3=0.9346 | val_dqn_proxy_expanded5=0.9310

Epoch 006 | train_loss=0.4359 | ce=0.3767 | ent=0.3681 | center=0.5182 | val_loss=0.1899 | val_acc=0.9556 | val_macro_f1=0.9554 | val_dqn_proxy_softmax3=0.9251 | val_dqn_proxy_expanded5=0.8898

Epoch 007 | train_loss=0.4094 | ce=0.3560 | ent=0.3562 | center=0.4636 | val_loss=0.1161 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9550 | val_dqn_proxy_expanded5=0.9054

Epoch 008 | train_loss=0.3955 | ce=0.3466 | ent=0.3435 | center=0.4204 | val_loss=0.0772 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9391 | val_dqn_proxy_expanded5=0.9075

Epoch 009 | train_loss=0.4086 | ce=0.3627 | ent=0.3444 | center=0.3907 | val_loss=0.1409 | val_acc=0.9630 | val_macro_f1=0.9628 | val_dqn_proxy_softmax3=0.9149 | val_dqn_proxy_expanded5=0.8472

Epoch 010 | train_loss=0.3858 | ce=0.3432 | ent=0.3326 | center=0.3601 | val_loss=0.1089 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9634 | val_dqn_proxy_expanded5=0.8894

Epoch 011 | train_loss=0.3975 | ce=0.3565 | ent=0.3474 | center=0.3407 | val_loss=0.0802 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9628 | val_dqn_proxy_expanded5=0.9084

Epoch 012 | train_loss=0.3978 | ce=0.3583 | ent=0.3409 | center=0.3266 | val_loss=0.0865 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9436 | val_dqn_proxy_expanded5=0.8768

Epoch 013 | train_loss=0.3930 | ce=0.3556 | ent=0.3449 | center=0.3055 | val_loss=0.0867 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.8068 | val_dqn_proxy_expanded5=0.7979

Epoch 014 | train_loss=0.3700 | ce=0.3353 | ent=0.3204 | center=0.2832 | val_loss=0.1287 | val_acc=0.9704 | val_macro_f1=0.9704 | val_dqn_proxy_softmax3=0.9462 | val_dqn_proxy_expanded5=0.9169

Epoch 015 | train_loss=0.3812 | ce=0.3476 | ent=0.3372 | center=0.2685 | val_loss=0.1069 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9421 | val_dqn_proxy_expanded5=0.9155

Epoch 016 | train_loss=0.3775 | ce=0.3455 | ent=0.3308 | center=0.2539 | val_loss=0.2095 | val_acc=0.9407 | val_macro_f1=0.9403 | val_dqn_proxy_softmax3=0.9010 | val_dqn_proxy_expanded5=0.8647

Epoch 017 | train_loss=0.3567 | ce=0.3267 | ent=0.3223 | center=0.2359 | val_loss=0.0942 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9581 | val_dqn_proxy_expanded5=0.8842

Epoch 018 | train_loss=0.3578 | ce=0.3289 | ent=0.3156 | center=0.2265 | val_loss=0.1091 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9645 | val_dqn_proxy_expanded5=0.9453

Epoch 019 | train_loss=0.3537 | ce=0.3259 | ent=0.3084 | center=0.2157 | val_loss=0.1069 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9921 | val_dqn_proxy_expanded5=0.9443

Epoch 020 | train_loss=0.3547 | ce=0.3276 | ent=0.3180 | center=0.2076 | val_loss=0.0775 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9463 | val_dqn_proxy_expanded5=0.9130

Epoch 021 | train_loss=0.3470 | ce=0.3212 | ent=0.3120 | center=0.1960 | val_loss=0.0919 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9585 | val_dqn_proxy_expanded5=0.8996

Epoch 022 | train_loss=0.3543 | ce=0.3294 | ent=0.3173 | center=0.1854 | val_loss=0.0845 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8867 | val_dqn_proxy_expanded5=0.8489

Epoch 023 | train_loss=0.3623 | ce=0.3376 | ent=0.3224 | center=0.1827 | val_loss=0.0691 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9860 | val_dqn_proxy_expanded5=0.9337

Epoch 024 | train_loss=0.3573 | ce=0.3337 | ent=0.3223 | center=0.1713 | val_loss=0.0773 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9753 | val_dqn_proxy_expanded5=0.9185

Epoch 025 | train_loss=0.3490 | ce=0.3264 | ent=0.3112 | center=0.1637 | val_loss=0.1256 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8517 | val_dqn_proxy_expanded5=0.7931

Epoch 026 | train_loss=0.3408 | ce=0.3189 | ent=0.3087 | center=0.1576 | val_loss=0.1179 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8760 | val_dqn_proxy_expanded5=0.8401

Epoch 027 | train_loss=0.3536 | ce=0.3318 | ent=0.3147 | center=0.1552 | val_loss=0.0792 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9814 | val_dqn_proxy_expanded5=0.9436

Epoch 028 | train_loss=0.3374 | ce=0.3169 | ent=0.3106 | center=0.1436 | val_loss=0.0932 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8364 | val_dqn_proxy_expanded5=0.8074

Epoch 029 | train_loss=0.3472 | ce=0.3267 | ent=0.3122 | center=0.1430 | val_loss=0.0866 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9207 | val_dqn_proxy_expanded5=0.8731

Epoch 030 | train_loss=0.3561 | ce=0.3357 | ent=0.3210 | center=0.1391 | val_loss=0.0994 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9610 | val_dqn_proxy_expanded5=0.9138

Epoch 031 | train_loss=0.3386 | ce=0.3192 | ent=0.3094 | center=0.1326 | val_loss=0.0935 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.8641 | val_dqn_proxy_expanded5=0.8358

Epoch 032 | train_loss=0.3508 | ce=0.3316 | ent=0.3193 | center=0.1287 | val_loss=0.0846 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9621 | val_dqn_proxy_expanded5=0.9372

Epoch 033 | train_loss=0.3493 | ce=0.3296 | ent=0.3158 | center=0.1333 | val_loss=0.0844 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.8985 | val_dqn_proxy_expanded5=0.8805

Epoch 034 | train_loss=0.3515 | ce=0.3316 | ent=0.3170 | center=0.1357 | val_loss=0.0726 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9016 | val_dqn_proxy_expanded5=0.8491
Early stopping at epoch 34 (best epoch: 19)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
23,ref_base_drop050_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-25_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
11,ref_base_ls002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
15,ref_base_ls000_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-04_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,ref_base_ls000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-59_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
8,ref_base_ls002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-47_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,ref_base_ls000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-56_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
17,ref_base_drop040_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-07_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,ref_base_ls002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-49_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
25,ref_base_ent002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-28_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
24,ref_base_ent002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-26_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
19,ref_base_drop040_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-11_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
5,ref_base_ls005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,ref_base_ls005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-45_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,ref_base_ls005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-42_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,ref_base_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
21,ref_base_drop050_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-18_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
20,ref_base_drop050_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-14_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
2,ref_base_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-29_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
22,ref_base_drop050_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-21_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,ref_base_ls005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-36_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
18,ref_base_drop040_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-09_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
16,ref_base_drop040_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-06_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
10,ref_base_ls002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-53_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
14,ref_base_ls000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-02_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"

================================================================================
Running experiment 27/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "cosine",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": null,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_base_ent002",
  "lr": 0.0005,
  "label_smoothing": 0.1,
  "entropy_loss_weight": 0.02,
  "mlp_dropout": 0.3,
  "unknown_pas": [
    "PA4"
  ],
  "run_name": "ref_base_ent002_unkPA4_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.7538 | ce=0.6204 | ent=0.6408 | center=1.2054 | val_loss=0.2356 | val_acc=0.9444 | val_macro_f1=0.9441 | val_dqn_proxy_softmax3=0.7382 | val_dqn_proxy_expanded5=0.7126

Epoch 002 | train_loss=0.5786 | ce=0.4722 | ent=0.4678 | center=0.9707 | val_loss=0.2793 | val_acc=0.9074 | val_macro_f1=0.9060 | val_dqn_proxy_softmax3=0.6976 | val_dqn_proxy_expanded5=0.6578

Epoch 003 | train_loss=0.5114 | ce=0.4184 | ent=0.4285 | center=0.8445 | val_loss=0.1852 | val_acc=0.9630 | val_macro_f1=0.9632 | val_dqn_proxy_softmax3=0.7893 | val_dqn_proxy_expanded5=0.7192

Epoch 004 | train_loss=0.4782 | ce=0.3957 | ent=0.3972 | center=0.7456 | val_loss=0.1555 | val_acc=0.9556 | val_macro_f1=0.9554 | val_dqn_proxy_softmax3=0.7106 | val_dqn_proxy_expanded5=0.6982

Epoch 005 | train_loss=0.4568 | ce=0.3823 | ent=0.3829 | center=0.6687 | val_loss=0.1162 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.7765 | val_dqn_proxy_expanded5=0.7094

Epoch 006 | train_loss=0.4278 | ce=0.3601 | ent=0.3563 | center=0.6058 | val_loss=0.1590 | val_acc=0.9481 | val_macro_f1=0.9478 | val_dqn_proxy_softmax3=0.7354 | val_dqn_proxy_expanded5=0.6862

Epoch 007 | train_loss=0.4404 | ce=0.3787 | ent=0.3639 | center=0.5445 | val_loss=0.1518 | val_acc=0.9630 | val_macro_f1=0.9628 | val_dqn_proxy_softmax3=0.7156 | val_dqn_proxy_expanded5=0.6782

Epoch 008 | train_loss=0.4058 | ce=0.3489 | ent=0.3439 | center=0.5007 | val_loss=0.1714 | val_acc=0.9593 | val_macro_f1=0.9591 | val_dqn_proxy_softmax3=0.7305 | val_dqn_proxy_expanded5=0.6837

Epoch 009 | train_loss=0.4233 | ce=0.3698 | ent=0.3614 | center=0.4620 | val_loss=0.1630 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.7677 | val_dqn_proxy_expanded5=0.7034

Epoch 010 | train_loss=0.4038 | ce=0.3533 | ent=0.3358 | center=0.4386 | val_loss=0.1569 | val_acc=0.9741 | val_macro_f1=0.9740 | val_dqn_proxy_softmax3=0.8974 | val_dqn_proxy_expanded5=0.8191

Epoch 011 | train_loss=0.3803 | ce=0.3345 | ent=0.3283 | center=0.3915 | val_loss=0.1052 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7684 | val_dqn_proxy_expanded5=0.7157

Epoch 012 | train_loss=0.3792 | ce=0.3361 | ent=0.3234 | center=0.3672 | val_loss=0.0890 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9468 | val_dqn_proxy_expanded5=0.8844

Epoch 013 | train_loss=0.3748 | ce=0.3339 | ent=0.3256 | center=0.3434 | val_loss=0.0978 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.7888 | val_dqn_proxy_expanded5=0.7307

Epoch 014 | train_loss=0.3760 | ce=0.3366 | ent=0.3259 | center=0.3292 | val_loss=0.1252 | val_acc=0.9630 | val_macro_f1=0.9628 | val_dqn_proxy_softmax3=0.7887 | val_dqn_proxy_expanded5=0.7495

Epoch 015 | train_loss=0.3686 | ce=0.3319 | ent=0.3165 | center=0.3040 | val_loss=0.1099 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8779 | val_dqn_proxy_expanded5=0.8141

Epoch 016 | train_loss=0.3560 | ce=0.3213 | ent=0.3096 | center=0.2844 | val_loss=0.1342 | val_acc=0.9704 | val_macro_f1=0.9703 | val_dqn_proxy_softmax3=0.8060 | val_dqn_proxy_expanded5=0.7607

Epoch 017 | train_loss=0.3641 | ce=0.3304 | ent=0.3201 | center=0.2729 | val_loss=0.1064 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9498 | val_dqn_proxy_expanded5=0.8597

Epoch 018 | train_loss=0.3598 | ce=0.3278 | ent=0.3153 | center=0.2565 | val_loss=0.0846 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9613 | val_dqn_proxy_expanded5=0.8664

Epoch 019 | train_loss=0.3594 | ce=0.3290 | ent=0.3130 | center=0.2422 | val_loss=0.1106 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.7735 | val_dqn_proxy_expanded5=0.7100

Epoch 020 | train_loss=0.3549 | ce=0.3254 | ent=0.3171 | center=0.2319 | val_loss=0.1244 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8569 | val_dqn_proxy_expanded5=0.7991

Epoch 021 | train_loss=0.3592 | ce=0.3308 | ent=0.3127 | center=0.2213 | val_loss=0.0858 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7610 | val_dqn_proxy_expanded5=0.7086

Epoch 022 | train_loss=0.3514 | ce=0.3240 | ent=0.3161 | center=0.2109 | val_loss=0.1612 | val_acc=0.9704 | val_macro_f1=0.9703 | val_dqn_proxy_softmax3=0.6778 | val_dqn_proxy_expanded5=0.6668

Epoch 023 | train_loss=0.3558 | ce=0.3294 | ent=0.3090 | center=0.2019 | val_loss=0.1017 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7579 | val_dqn_proxy_expanded5=0.7052

Epoch 024 | train_loss=0.3521 | ce=0.3265 | ent=0.3155 | center=0.1920 | val_loss=0.1147 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6874 | val_dqn_proxy_expanded5=0.6690

Epoch 025 | train_loss=0.3469 | ce=0.3220 | ent=0.3121 | center=0.1860 | val_loss=0.1106 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.7118 | val_dqn_proxy_expanded5=0.6895

Epoch 026 | train_loss=0.3501 | ce=0.3250 | ent=0.3132 | center=0.1891 | val_loss=0.1008 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.7779 | val_dqn_proxy_expanded5=0.7148

Epoch 027 | train_loss=0.3447 | ce=0.3210 | ent=0.3084 | center=0.1757 | val_loss=0.0989 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7688 | val_dqn_proxy_expanded5=0.7124

Epoch 028 | train_loss=0.3435 | ce=0.3207 | ent=0.3109 | center=0.1650 | val_loss=0.0758 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8214 | val_dqn_proxy_expanded5=0.7794

Epoch 029 | train_loss=0.3328 | ce=0.3117 | ent=0.3002 | center=0.1517 | val_loss=0.1291 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.7335 | val_dqn_proxy_expanded5=0.7292

Epoch 030 | train_loss=0.3476 | ce=0.3262 | ent=0.3134 | center=0.1510 | val_loss=0.0770 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7794 | val_dqn_proxy_expanded5=0.7184

Epoch 031 | train_loss=0.3342 | ce=0.3136 | ent=0.3022 | center=0.1460 | val_loss=0.0743 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.7677 | val_dqn_proxy_expanded5=0.7122

Epoch 032 | train_loss=0.3424 | ce=0.3220 | ent=0.3088 | center=0.1427 | val_loss=0.1038 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7673 | val_dqn_proxy_expanded5=0.7076

Epoch 033 | train_loss=0.3453 | ce=0.3255 | ent=0.3095 | center=0.1363 | val_loss=0.1161 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6521 | val_dqn_proxy_expanded5=0.6849
Early stopping at epoch 33 (best epoch: 18)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
23,ref_base_drop050_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-25_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
11,ref_base_ls002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
15,ref_base_ls000_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-04_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,ref_base_ls000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-59_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
8,ref_base_ls002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-47_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,ref_base_ls000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-56_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
17,ref_base_drop040_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-07_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,ref_base_ls002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-49_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
25,ref_base_ent002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-28_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
24,ref_base_ent002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-26_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
19,ref_base_drop040_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-11_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
5,ref_base_ls005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,ref_base_ls005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-45_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,ref_base_ls005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-42_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,ref_base_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
21,ref_base_drop050_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-18_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
20,ref_base_drop050_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-14_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
2,ref_base_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-29_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
22,ref_base_drop050_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-21_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,ref_base_ls005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-36_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
26,ref_base_ent002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-31_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
18,ref_base_drop040_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-09_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
16,ref_base_drop040_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-06_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
10,ref_base_ls002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-53_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
14,ref_base_ls000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-02_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"

================================================================================
Running experiment 28/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "cosine",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": null,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_base_ent002",
  "lr": 0.0005,
  "label_smoothing": 0.1,
  "entropy_loss_weight": 0.02,
  "mlp_dropout": 0.3,
  "unknown_pas": [
    "PA8"
  ],
  "run_name": "ref_base_ent002_unkPA8_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.5780 | ce=0.4676 | ent=0.4887 | center=1.0064 | val_loss=0.1183 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9599 | val_dqn_proxy_expanded5=0.9396

Epoch 002 | train_loss=0.4302 | ce=0.3483 | ent=0.3412 | center=0.7506 | val_loss=0.1419 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8907 | val_dqn_proxy_expanded5=0.8524

Epoch 003 | train_loss=0.4166 | ce=0.3453 | ent=0.3422 | center=0.6442 | val_loss=0.1250 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9625 | val_dqn_proxy_expanded5=0.9218

Epoch 004 | train_loss=0.4000 | ce=0.3364 | ent=0.3264 | center=0.5707 | val_loss=0.1305 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9406 | val_dqn_proxy_expanded5=0.9025

Epoch 005 | train_loss=0.3880 | ce=0.3304 | ent=0.3253 | center=0.5111 | val_loss=0.0937 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9277 | val_dqn_proxy_expanded5=0.8910

Epoch 006 | train_loss=0.3703 | ce=0.3187 | ent=0.3100 | center=0.4543 | val_loss=0.0904 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9653 | val_dqn_proxy_expanded5=0.9196

Epoch 007 | train_loss=0.3637 | ce=0.3167 | ent=0.3045 | center=0.4089 | val_loss=0.0949 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9629 | val_dqn_proxy_expanded5=0.9191

Epoch 008 | train_loss=0.3551 | ce=0.3125 | ent=0.3028 | center=0.3655 | val_loss=0.0808 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8923 | val_dqn_proxy_expanded5=0.8509

Epoch 009 | train_loss=0.3511 | ce=0.3117 | ent=0.2984 | center=0.3342 | val_loss=0.0790 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8862 | val_dqn_proxy_expanded5=0.8383

Epoch 010 | train_loss=0.3513 | ce=0.3139 | ent=0.2982 | center=0.3138 | val_loss=0.0940 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9749 | val_dqn_proxy_expanded5=0.8979

Epoch 011 | train_loss=0.3442 | ce=0.3100 | ent=0.2945 | center=0.2830 | val_loss=0.1064 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9200 | val_dqn_proxy_expanded5=0.8778

Epoch 012 | train_loss=0.3406 | ce=0.3082 | ent=0.2960 | center=0.2645 | val_loss=0.0944 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9662 | val_dqn_proxy_expanded5=0.9112

Epoch 013 | train_loss=0.3420 | ce=0.3108 | ent=0.2973 | center=0.2530 | val_loss=0.0782 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9177 | val_dqn_proxy_expanded5=0.8564

Epoch 014 | train_loss=0.3362 | ce=0.3072 | ent=0.2926 | center=0.2311 | val_loss=0.0905 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9564 | val_dqn_proxy_expanded5=0.9078

Epoch 015 | train_loss=0.3317 | ce=0.3045 | ent=0.2918 | center=0.2135 | val_loss=0.0808 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9411 | val_dqn_proxy_expanded5=0.8966

Epoch 016 | train_loss=0.3398 | ce=0.3126 | ent=0.2969 | center=0.2126 | val_loss=0.0819 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8844 | val_dqn_proxy_expanded5=0.8420

Epoch 017 | train_loss=0.3317 | ce=0.3061 | ent=0.2900 | center=0.1982 | val_loss=0.0973 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9691 | val_dqn_proxy_expanded5=0.9080

Epoch 018 | train_loss=0.3400 | ce=0.3142 | ent=0.3015 | center=0.1984 | val_loss=0.1091 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9673 | val_dqn_proxy_expanded5=0.9150

Epoch 019 | train_loss=0.3328 | ce=0.3084 | ent=0.2943 | center=0.1848 | val_loss=0.0991 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9266 | val_dqn_proxy_expanded5=0.8676

Epoch 020 | train_loss=0.3286 | ce=0.3056 | ent=0.2915 | center=0.1717 | val_loss=0.1060 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9237 | val_dqn_proxy_expanded5=0.8608

Epoch 021 | train_loss=0.3274 | ce=0.3052 | ent=0.2944 | center=0.1626 | val_loss=0.0959 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9457 | val_dqn_proxy_expanded5=0.8807

Epoch 022 | train_loss=0.3268 | ce=0.3054 | ent=0.2922 | center=0.1559 | val_loss=0.0828 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9696 | val_dqn_proxy_expanded5=0.8925

Epoch 023 | train_loss=0.3242 | ce=0.3036 | ent=0.2918 | center=0.1478 | val_loss=0.0874 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9198 | val_dqn_proxy_expanded5=0.8615

Epoch 024 | train_loss=0.3247 | ce=0.3048 | ent=0.2919 | center=0.1413 | val_loss=0.0875 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9301 | val_dqn_proxy_expanded5=0.8659

Epoch 025 | train_loss=0.3246 | ce=0.3054 | ent=0.2921 | center=0.1343 | val_loss=0.0850 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9064 | val_dqn_proxy_expanded5=0.8485
Early stopping at epoch 25 (best epoch: 10)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
23,ref_base_drop050_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-25_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
11,ref_base_ls002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
15,ref_base_ls000_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-04_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,ref_base_ls000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-59_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
8,ref_base_ls002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-47_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,ref_base_ls000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-56_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
17,ref_base_drop040_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-07_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,ref_base_ls002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-49_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
25,ref_base_ent002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-28_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
24,ref_base_ent002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-26_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
19,ref_base_drop040_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-11_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
5,ref_base_ls005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,ref_base_ls005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-45_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
27,ref_base_ent002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,ref_base_ls005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-42_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,ref_base_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
21,ref_base_drop050_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-18_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
20,ref_base_drop050_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-14_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
2,ref_base_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-29_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
22,ref_base_drop050_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-21_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,ref_base_ls005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-36_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
26,ref_base_ent002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-31_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
18,ref_base_drop040_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-09_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
16,ref_base_drop040_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-06_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
10,ref_base_ls002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-53_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
14,ref_base_ls000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-02_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"

================================================================================
Running experiment 29/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "cosine",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": null,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_base_ent005",
  "lr": 0.0005,
  "label_smoothing": 0.1,
  "entropy_loss_weight": 0.05,
  "mlp_dropout": 0.3,
  "unknown_pas": [
    "PA2"
  ],
  "run_name": "ref_base_ent005_unkPA2_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.6512 | ce=0.5174 | ent=0.5259 | center=1.0743 | val_loss=0.2167 | val_acc=0.9556 | val_macro_f1=0.9558 | val_dqn_proxy_softmax3=0.7077 | val_dqn_proxy_expanded5=0.7413

Epoch 002 | train_loss=0.4868 | ce=0.3835 | ent=0.3705 | center=0.8481 | val_loss=0.1210 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8550 | val_dqn_proxy_expanded5=0.8166

Epoch 003 | train_loss=0.4434 | ce=0.3540 | ent=0.3317 | center=0.7288 | val_loss=0.1126 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.5629 | val_dqn_proxy_expanded5=0.6398

Epoch 004 | train_loss=0.4579 | ce=0.3745 | ent=0.3431 | center=0.6622 | val_loss=0.1306 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8999 | val_dqn_proxy_expanded5=0.8765

Epoch 005 | train_loss=0.4193 | ce=0.3444 | ent=0.3264 | center=0.5862 | val_loss=0.1000 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7389 | val_dqn_proxy_expanded5=0.7597

Epoch 006 | train_loss=0.4106 | ce=0.3414 | ent=0.3210 | center=0.5317 | val_loss=0.0996 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8825 | val_dqn_proxy_expanded5=0.8423

Epoch 007 | train_loss=0.4087 | ce=0.3441 | ent=0.3127 | center=0.4903 | val_loss=0.1096 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6483 | val_dqn_proxy_expanded5=0.7005

Epoch 008 | train_loss=0.3819 | ce=0.3226 | ent=0.2949 | center=0.4457 | val_loss=0.0967 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6453 | val_dqn_proxy_expanded5=0.7258

Epoch 009 | train_loss=0.3718 | ce=0.3174 | ent=0.2890 | center=0.3997 | val_loss=0.0897 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7700 | val_dqn_proxy_expanded5=0.7801

Epoch 010 | train_loss=0.3842 | ce=0.3316 | ent=0.2965 | center=0.3782 | val_loss=0.0777 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6647 | val_dqn_proxy_expanded5=0.6589

Epoch 011 | train_loss=0.3662 | ce=0.3171 | ent=0.2905 | center=0.3455 | val_loss=0.0733 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8848 | val_dqn_proxy_expanded5=0.8338

Epoch 012 | train_loss=0.3624 | ce=0.3165 | ent=0.2841 | center=0.3172 | val_loss=0.0829 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7503 | val_dqn_proxy_expanded5=0.7186

Epoch 013 | train_loss=0.3595 | ce=0.3159 | ent=0.2827 | center=0.2945 | val_loss=0.0841 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9571 | val_dqn_proxy_expanded5=0.9096

Epoch 014 | train_loss=0.3563 | ce=0.3152 | ent=0.2832 | center=0.2694 | val_loss=0.0723 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8540 | val_dqn_proxy_expanded5=0.8498

Epoch 015 | train_loss=0.3560 | ce=0.3155 | ent=0.2844 | center=0.2629 | val_loss=0.0736 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6869 | val_dqn_proxy_expanded5=0.7084

Epoch 016 | train_loss=0.3597 | ce=0.3201 | ent=0.2840 | center=0.2532 | val_loss=0.0714 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.5874 | val_dqn_proxy_expanded5=0.6669

Epoch 017 | train_loss=0.3564 | ce=0.3183 | ent=0.2896 | center=0.2363 | val_loss=0.0765 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7399 | val_dqn_proxy_expanded5=0.7233

Epoch 018 | train_loss=0.3512 | ce=0.3148 | ent=0.2796 | center=0.2241 | val_loss=0.0911 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6243 | val_dqn_proxy_expanded5=0.7663

Epoch 019 | train_loss=0.3540 | ce=0.3187 | ent=0.2891 | center=0.2083 | val_loss=0.0752 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.5927 | val_dqn_proxy_expanded5=0.6437

Epoch 020 | train_loss=0.3496 | ce=0.3152 | ent=0.2804 | center=0.2038 | val_loss=0.0866 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7432 | val_dqn_proxy_expanded5=0.7993

Epoch 021 | train_loss=0.3499 | ce=0.3170 | ent=0.2807 | center=0.1885 | val_loss=0.0900 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.5705 | val_dqn_proxy_expanded5=0.7089

Epoch 022 | train_loss=0.3441 | ce=0.3124 | ent=0.2805 | center=0.1767 | val_loss=0.0945 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7349 | val_dqn_proxy_expanded5=0.8038

Epoch 023 | train_loss=0.3437 | ce=0.3127 | ent=0.2817 | center=0.1692 | val_loss=0.0840 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7635 | val_dqn_proxy_expanded5=0.7885

Epoch 024 | train_loss=0.3404 | ce=0.3102 | ent=0.2798 | center=0.1619 | val_loss=0.0913 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6460 | val_dqn_proxy_expanded5=0.7612

Epoch 025 | train_loss=0.3437 | ce=0.3141 | ent=0.2833 | center=0.1541 | val_loss=0.0837 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7356 | val_dqn_proxy_expanded5=0.7687

Epoch 026 | train_loss=0.3563 | ce=0.3259 | ent=0.2928 | center=0.1576 | val_loss=0.0699 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.5718 | val_dqn_proxy_expanded5=0.6863

Epoch 027 | train_loss=0.3452 | ce=0.3158 | ent=0.2828 | center=0.1521 | val_loss=0.0788 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6655 | val_dqn_proxy_expanded5=0.7008

Epoch 028 | train_loss=0.3423 | ce=0.3144 | ent=0.2844 | center=0.1376 | val_loss=0.0916 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6260 | val_dqn_proxy_expanded5=0.7306
Early stopping at epoch 28 (best epoch: 13)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
23,ref_base_drop050_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-25_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
11,ref_base_ls002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
15,ref_base_ls000_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-04_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,ref_base_ls000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-59_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
8,ref_base_ls002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-47_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,ref_base_ls000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-56_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
17,ref_base_drop040_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-07_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,ref_base_ls002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-49_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
25,ref_base_ent002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-28_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
24,ref_base_ent002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-26_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
19,ref_base_drop040_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-11_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
5,ref_base_ls005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,ref_base_ls005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-45_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
27,ref_base_ent002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,ref_base_ls005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-42_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,ref_base_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
21,ref_base_drop050_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-18_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
20,ref_base_drop050_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-14_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
28,ref_base_ent005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-35_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,ref_base_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-29_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
22,ref_base_drop050_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-21_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,ref_base_ls005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-36_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
26,ref_base_ent002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-31_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
18,ref_base_drop040_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-09_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
16,ref_base_drop040_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-06_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
10,ref_base_ls002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-53_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
14,ref_base_ls000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-02_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"

================================================================================
Running experiment 30/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "cosine",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": null,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_base_ent005",
  "lr": 0.0005,
  "label_smoothing": 0.1,
  "entropy_loss_weight": 0.05,
  "mlp_dropout": 0.3,
  "unknown_pas": [
    "PA3"
  ],
  "run_name": "ref_base_ent005_unkPA3_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.7499 | ce=0.6041 | ent=0.6120 | center=1.1515 | val_loss=0.2432 | val_acc=0.9370 | val_macro_f1=0.9374 | val_dqn_proxy_softmax3=0.6829 | val_dqn_proxy_expanded5=0.7367

Epoch 002 | train_loss=0.5885 | ce=0.4715 | ent=0.4545 | center=0.9435 | val_loss=0.1648 | val_acc=0.9630 | val_macro_f1=0.9632 | val_dqn_proxy_softmax3=0.7340 | val_dqn_proxy_expanded5=0.7600

Epoch 003 | train_loss=0.5355 | ce=0.4337 | ent=0.4170 | center=0.8091 | val_loss=0.1466 | val_acc=0.9556 | val_macro_f1=0.9557 | val_dqn_proxy_softmax3=0.8132 | val_dqn_proxy_expanded5=0.7967

Epoch 004 | train_loss=0.4942 | ce=0.4046 | ent=0.3851 | center=0.7038 | val_loss=0.1609 | val_acc=0.9704 | val_macro_f1=0.9704 | val_dqn_proxy_softmax3=0.8498 | val_dqn_proxy_expanded5=0.8547

Epoch 005 | train_loss=0.4808 | ce=0.3987 | ent=0.3751 | center=0.6336 | val_loss=0.1417 | val_acc=0.9593 | val_macro_f1=0.9592 | val_dqn_proxy_softmax3=0.9504 | val_dqn_proxy_expanded5=0.9194

Epoch 006 | train_loss=0.4624 | ce=0.3868 | ent=0.3622 | center=0.5749 | val_loss=0.2029 | val_acc=0.9185 | val_macro_f1=0.9183 | val_dqn_proxy_softmax3=0.8229 | val_dqn_proxy_expanded5=0.8282

Epoch 007 | train_loss=0.4250 | ce=0.3559 | ent=0.3366 | center=0.5228 | val_loss=0.1104 | val_acc=0.9667 | val_macro_f1=0.9666 | val_dqn_proxy_softmax3=0.9445 | val_dqn_proxy_expanded5=0.9263

Epoch 008 | train_loss=0.4155 | ce=0.3519 | ent=0.3268 | center=0.4720 | val_loss=0.1198 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.9497 | val_dqn_proxy_expanded5=0.9170

Epoch 009 | train_loss=0.4079 | ce=0.3480 | ent=0.3197 | center=0.4385 | val_loss=0.0794 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9313 | val_dqn_proxy_expanded5=0.8924

Epoch 010 | train_loss=0.4117 | ce=0.3548 | ent=0.3213 | center=0.4079 | val_loss=0.1143 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9679 | val_dqn_proxy_expanded5=0.9500

Epoch 011 | train_loss=0.4165 | ce=0.3611 | ent=0.3364 | center=0.3864 | val_loss=0.1126 | val_acc=0.9741 | val_macro_f1=0.9740 | val_dqn_proxy_softmax3=0.9795 | val_dqn_proxy_expanded5=0.9229

Epoch 012 | train_loss=0.4010 | ce=0.3496 | ent=0.3192 | center=0.3544 | val_loss=0.1537 | val_acc=0.9481 | val_macro_f1=0.9478 | val_dqn_proxy_softmax3=0.9519 | val_dqn_proxy_expanded5=0.9122

Epoch 013 | train_loss=0.4143 | ce=0.3636 | ent=0.3315 | center=0.3411 | val_loss=0.0870 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.8469 | val_dqn_proxy_expanded5=0.8254

Epoch 014 | train_loss=0.3863 | ce=0.3396 | ent=0.3095 | center=0.3123 | val_loss=0.1038 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9792 | val_dqn_proxy_expanded5=0.9575

Epoch 015 | train_loss=0.3799 | ce=0.3353 | ent=0.3034 | center=0.2947 | val_loss=0.0984 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9797 | val_dqn_proxy_expanded5=0.9600

Epoch 016 | train_loss=0.3830 | ce=0.3394 | ent=0.3151 | center=0.2778 | val_loss=0.0854 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9589 | val_dqn_proxy_expanded5=0.9276

Epoch 017 | train_loss=0.3856 | ce=0.3435 | ent=0.3116 | center=0.2647 | val_loss=0.1100 | val_acc=0.9667 | val_macro_f1=0.9666 | val_dqn_proxy_softmax3=0.9557 | val_dqn_proxy_expanded5=0.9576

Epoch 018 | train_loss=0.3706 | ce=0.3309 | ent=0.2995 | center=0.2475 | val_loss=0.0836 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9330 | val_dqn_proxy_expanded5=0.9530

Epoch 019 | train_loss=0.3726 | ce=0.3339 | ent=0.3042 | center=0.2343 | val_loss=0.1232 | val_acc=0.9630 | val_macro_f1=0.9628 | val_dqn_proxy_softmax3=0.8194 | val_dqn_proxy_expanded5=0.8173

Epoch 020 | train_loss=0.3734 | ce=0.3358 | ent=0.3037 | center=0.2245 | val_loss=0.0844 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9829 | val_dqn_proxy_expanded5=0.9731

Epoch 021 | train_loss=0.3646 | ce=0.3285 | ent=0.2997 | center=0.2117 | val_loss=0.0863 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9782 | val_dqn_proxy_expanded5=0.9718

Epoch 022 | train_loss=0.3680 | ce=0.3326 | ent=0.2991 | center=0.2040 | val_loss=0.1168 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9353 | val_dqn_proxy_expanded5=0.9273

Epoch 023 | train_loss=0.3774 | ce=0.3417 | ent=0.3097 | center=0.2025 | val_loss=0.0843 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.8434 | val_dqn_proxy_expanded5=0.8433

Epoch 024 | train_loss=0.3743 | ce=0.3401 | ent=0.3089 | center=0.1878 | val_loss=0.0810 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9570 | val_dqn_proxy_expanded5=0.9300

Epoch 025 | train_loss=0.3651 | ce=0.3315 | ent=0.2989 | center=0.1864 | val_loss=0.0869 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9840 | val_dqn_proxy_expanded5=0.9623

Epoch 026 | train_loss=0.3634 | ce=0.3312 | ent=0.2994 | center=0.1725 | val_loss=0.0741 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9772 | val_dqn_proxy_expanded5=0.9501

Epoch 027 | train_loss=0.3527 | ce=0.3218 | ent=0.2914 | center=0.1626 | val_loss=0.1263 | val_acc=0.9667 | val_macro_f1=0.9666 | val_dqn_proxy_softmax3=0.9664 | val_dqn_proxy_expanded5=0.9178

Epoch 028 | train_loss=0.3555 | ce=0.3253 | ent=0.2949 | center=0.1552 | val_loss=0.0914 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9592 | val_dqn_proxy_expanded5=0.9342

Epoch 029 | train_loss=0.3587 | ce=0.3286 | ent=0.2988 | center=0.1516 | val_loss=0.0915 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9399 | val_dqn_proxy_expanded5=0.9066

Epoch 030 | train_loss=0.3477 | ce=0.3187 | ent=0.2850 | center=0.1472 | val_loss=0.0796 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9898 | val_dqn_proxy_expanded5=0.9470

Epoch 031 | train_loss=0.3566 | ce=0.3276 | ent=0.2957 | center=0.1427 | val_loss=0.0902 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9687 | val_dqn_proxy_expanded5=0.9285

Epoch 032 | train_loss=0.3530 | ce=0.3246 | ent=0.2958 | center=0.1359 | val_loss=0.0710 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9690 | val_dqn_proxy_expanded5=0.9248

Epoch 033 | train_loss=0.3513 | ce=0.3236 | ent=0.2949 | center=0.1289 | val_loss=0.0759 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9833 | val_dqn_proxy_expanded5=0.9318

Epoch 034 | train_loss=0.3526 | ce=0.3255 | ent=0.2947 | center=0.1239 | val_loss=0.1281 | val_acc=0.9667 | val_macro_f1=0.9666 | val_dqn_proxy_softmax3=0.8021 | val_dqn_proxy_expanded5=0.8277

Epoch 035 | train_loss=0.3681 | ce=0.3401 | ent=0.3068 | center=0.1266 | val_loss=0.0959 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9662 | val_dqn_proxy_expanded5=0.9205

Epoch 036 | train_loss=0.3461 | ce=0.3199 | ent=0.2914 | center=0.1166 | val_loss=0.0904 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9620 | val_dqn_proxy_expanded5=0.9056

Epoch 037 | train_loss=0.3499 | ce=0.3239 | ent=0.2902 | center=0.1145 | val_loss=0.1106 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9593 | val_dqn_proxy_expanded5=0.9189

Epoch 038 | train_loss=0.3484 | ce=0.3229 | ent=0.2929 | center=0.1094 | val_loss=0.0773 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9707 | val_dqn_proxy_expanded5=0.9233

Epoch 039 | train_loss=0.3412 | ce=0.3164 | ent=0.2884 | center=0.1037 | val_loss=0.1024 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9358 | val_dqn_proxy_expanded5=0.8970

Epoch 040 | train_loss=0.3533 | ce=0.3282 | ent=0.2945 | center=0.1045 | val_loss=0.0843 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9642 | val_dqn_proxy_expanded5=0.9193

Epoch 041 | train_loss=0.3374 | ce=0.3133 | ent=0.2840 | center=0.0984 | val_loss=0.0958 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9619 | val_dqn_proxy_expanded5=0.9273

Epoch 042 | train_loss=0.3383 | ce=0.3147 | ent=0.2869 | center=0.0927 | val_loss=0.0772 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7719 | val_dqn_proxy_expanded5=0.7498

Epoch 043 | train_loss=0.3490 | ce=0.3249 | ent=0.2940 | center=0.0944 | val_loss=0.0711 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9719 | val_dqn_proxy_expanded5=0.9264

Epoch 044 | train_loss=0.3420 | ce=0.3187 | ent=0.2867 | center=0.0900 | val_loss=0.0999 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.9541 | val_dqn_proxy_expanded5=0.9343

Epoch 045 | train_loss=0.3471 | ce=0.3234 | ent=0.2941 | center=0.0906 | val_loss=0.0878 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9443 | val_dqn_proxy_expanded5=0.8831
Early stopping at epoch 45 (best epoch: 30)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
23,ref_base_drop050_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-25_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
11,ref_base_ls002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
15,ref_base_ls000_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-04_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,ref_base_ls000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-59_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
8,ref_base_ls002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-47_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,ref_base_ls000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-56_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
17,ref_base_drop040_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-07_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
29,ref_base_ent005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,ref_base_ls002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-49_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
25,ref_base_ent002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-28_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
24,ref_base_ent002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-26_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
19,ref_base_drop040_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-11_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
5,ref_base_ls005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,ref_base_ls005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-45_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
27,ref_base_ent002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,ref_base_ls005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-42_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,ref_base_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
21,ref_base_drop050_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-18_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
20,ref_base_drop050_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-14_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
28,ref_base_ent005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-35_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,ref_base_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-29_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
22,ref_base_drop050_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-21_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,ref_base_ls005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-36_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
26,ref_base_ent002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-31_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
18,ref_base_drop040_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-09_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
16,ref_base_drop040_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-06_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
10,ref_base_ls002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-53_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
14,ref_base_ls000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-02_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"

================================================================================
Running experiment 31/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "cosine",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": null,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_base_ent005",
  "lr": 0.0005,
  "label_smoothing": 0.1,
  "entropy_loss_weight": 0.05,
  "mlp_dropout": 0.3,
  "unknown_pas": [
    "PA4"
  ],
  "run_name": "ref_base_ent005_unkPA4_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.7201 | ce=0.5837 | ent=0.5931 | center=1.0681 | val_loss=0.3087 | val_acc=0.8852 | val_macro_f1=0.8801 | val_dqn_proxy_softmax3=0.6978 | val_dqn_proxy_expanded5=0.7052

Epoch 002 | train_loss=0.5561 | ce=0.4486 | ent=0.4304 | center=0.8599 | val_loss=0.1577 | val_acc=0.9667 | val_macro_f1=0.9669 | val_dqn_proxy_softmax3=0.7495 | val_dqn_proxy_expanded5=0.6978

Epoch 003 | train_loss=0.4971 | ce=0.4035 | ent=0.3935 | center=0.7391 | val_loss=0.1434 | val_acc=0.9667 | val_macro_f1=0.9669 | val_dqn_proxy_softmax3=0.9197 | val_dqn_proxy_expanded5=0.8410

Epoch 004 | train_loss=0.4837 | ce=0.3991 | ent=0.3768 | center=0.6575 | val_loss=0.2644 | val_acc=0.9148 | val_macro_f1=0.9134 | val_dqn_proxy_softmax3=0.9041 | val_dqn_proxy_expanded5=0.8572

Epoch 005 | train_loss=0.4501 | ce=0.3726 | ent=0.3572 | center=0.5963 | val_loss=0.1211 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.7716 | val_dqn_proxy_expanded5=0.7105

Epoch 006 | train_loss=0.4374 | ce=0.3669 | ent=0.3374 | center=0.5356 | val_loss=0.2055 | val_acc=0.9259 | val_macro_f1=0.9250 | val_dqn_proxy_softmax3=0.8600 | val_dqn_proxy_expanded5=0.7828

Epoch 007 | train_loss=0.4245 | ce=0.3586 | ent=0.3377 | center=0.4902 | val_loss=0.0945 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.8803 | val_dqn_proxy_expanded5=0.8125

Epoch 008 | train_loss=0.4189 | ce=0.3571 | ent=0.3347 | center=0.4509 | val_loss=0.1128 | val_acc=0.9704 | val_macro_f1=0.9703 | val_dqn_proxy_softmax3=0.7950 | val_dqn_proxy_expanded5=0.7521

Epoch 009 | train_loss=0.3989 | ce=0.3418 | ent=0.3168 | center=0.4123 | val_loss=0.1053 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.7421 | val_dqn_proxy_expanded5=0.7052

Epoch 010 | train_loss=0.4151 | ce=0.3598 | ent=0.3246 | center=0.3912 | val_loss=0.1913 | val_acc=0.9296 | val_macro_f1=0.9280 | val_dqn_proxy_softmax3=0.6575 | val_dqn_proxy_expanded5=0.7212

Epoch 011 | train_loss=0.3871 | ce=0.3354 | ent=0.3050 | center=0.3647 | val_loss=0.1310 | val_acc=0.9704 | val_macro_f1=0.9703 | val_dqn_proxy_softmax3=0.7246 | val_dqn_proxy_expanded5=0.7208

Epoch 012 | train_loss=0.3928 | ce=0.3432 | ent=0.3164 | center=0.3376 | val_loss=0.0839 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7572 | val_dqn_proxy_expanded5=0.7350

Epoch 013 | train_loss=0.4003 | ce=0.3522 | ent=0.3160 | center=0.3230 | val_loss=0.1234 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.7432 | val_dqn_proxy_expanded5=0.7224

Epoch 014 | train_loss=0.3734 | ce=0.3285 | ent=0.3030 | center=0.2975 | val_loss=0.0995 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7486 | val_dqn_proxy_expanded5=0.7640

Epoch 015 | train_loss=0.3739 | ce=0.3308 | ent=0.3006 | center=0.2802 | val_loss=0.0936 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.7934 | val_dqn_proxy_expanded5=0.7619

Epoch 016 | train_loss=0.3676 | ce=0.3265 | ent=0.2995 | center=0.2609 | val_loss=0.0892 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7743 | val_dqn_proxy_expanded5=0.7467

Epoch 017 | train_loss=0.3606 | ce=0.3212 | ent=0.2932 | center=0.2475 | val_loss=0.0978 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7617 | val_dqn_proxy_expanded5=0.7482

Epoch 018 | train_loss=0.3640 | ce=0.3257 | ent=0.2960 | center=0.2358 | val_loss=0.1174 | val_acc=0.9704 | val_macro_f1=0.9703 | val_dqn_proxy_softmax3=0.7442 | val_dqn_proxy_expanded5=0.7193
Early stopping at epoch 18 (best epoch: 3)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
23,ref_base_drop050_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-25_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
11,ref_base_ls002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
15,ref_base_ls000_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-04_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,ref_base_ls000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-59_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
8,ref_base_ls002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-47_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,ref_base_ls000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-56_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
17,ref_base_drop040_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-07_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
29,ref_base_ent005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,ref_base_ls002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-49_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
25,ref_base_ent002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-28_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
24,ref_base_ent002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-26_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
19,ref_base_drop040_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-11_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
5,ref_base_ls005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,ref_base_ls005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-45_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
27,ref_base_ent002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,ref_base_ls005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-42_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,ref_base_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
21,ref_base_drop050_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-18_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
20,ref_base_drop050_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-14_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
28,ref_base_ent005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-35_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,ref_base_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-29_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
22,ref_base_drop050_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-21_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,ref_base_ls005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-36_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
26,ref_base_ent002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-31_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
18,ref_base_drop040_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-09_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
30,ref_base_ent005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-41_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
16,ref_base_drop040_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-06_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
10,ref_base_ls002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-53_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
14,ref_base_ls000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-02_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"

================================================================================
Running experiment 32/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "cosine",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": null,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_base_ent005",
  "lr": 0.0005,
  "label_smoothing": 0.1,
  "entropy_loss_weight": 0.05,
  "mlp_dropout": 0.3,
  "unknown_pas": [
    "PA8"
  ],
  "run_name": "ref_base_ent005_unkPA8_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.6395 | ce=0.4959 | ent=0.5133 | center=1.1790 | val_loss=0.1235 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9411 | val_dqn_proxy_expanded5=0.9421

Epoch 002 | train_loss=0.4501 | ce=0.3448 | ent=0.3297 | center=0.8877 | val_loss=0.1179 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9471 | val_dqn_proxy_expanded5=0.9494

Epoch 003 | train_loss=0.4433 | ce=0.3512 | ent=0.3283 | center=0.7568 | val_loss=0.1148 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9389 | val_dqn_proxy_expanded5=0.9368

Epoch 004 | train_loss=0.4161 | ce=0.3355 | ent=0.3135 | center=0.6491 | val_loss=0.1211 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9281 | val_dqn_proxy_expanded5=0.9387

Epoch 005 | train_loss=0.4049 | ce=0.3318 | ent=0.3057 | center=0.5779 | val_loss=0.1032 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9679 | val_dqn_proxy_expanded5=0.9653

Epoch 006 | train_loss=0.3984 | ce=0.3319 | ent=0.3044 | center=0.5132 | val_loss=0.1083 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9295 | val_dqn_proxy_expanded5=0.9428

Epoch 007 | train_loss=0.3811 | ce=0.3196 | ent=0.2919 | center=0.4684 | val_loss=0.0847 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9406 | val_dqn_proxy_expanded5=0.9406

Epoch 008 | train_loss=0.3684 | ce=0.3128 | ent=0.2803 | center=0.4158 | val_loss=0.0962 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8362 | val_dqn_proxy_expanded5=0.8400

Epoch 009 | train_loss=0.3691 | ce=0.3164 | ent=0.2858 | center=0.3840 | val_loss=0.0752 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9392 | val_dqn_proxy_expanded5=0.9518

Epoch 010 | train_loss=0.3630 | ce=0.3138 | ent=0.2804 | center=0.3512 | val_loss=0.0888 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9848 | val_dqn_proxy_expanded5=0.9847

Epoch 011 | train_loss=0.3538 | ce=0.3084 | ent=0.2732 | center=0.3178 | val_loss=0.0861 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9090 | val_dqn_proxy_expanded5=0.9321

Epoch 012 | train_loss=0.3545 | ce=0.3106 | ent=0.2773 | center=0.2999 | val_loss=0.0907 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9303 | val_dqn_proxy_expanded5=0.9429

Epoch 013 | train_loss=0.3565 | ce=0.3136 | ent=0.2839 | center=0.2868 | val_loss=0.0800 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9522 | val_dqn_proxy_expanded5=0.9591

Epoch 014 | train_loss=0.3468 | ce=0.3071 | ent=0.2700 | center=0.2623 | val_loss=0.0761 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9064 | val_dqn_proxy_expanded5=0.9232

Epoch 015 | train_loss=0.3454 | ce=0.3065 | ent=0.2771 | center=0.2502 | val_loss=0.0720 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8693 | val_dqn_proxy_expanded5=0.8964

Epoch 016 | train_loss=0.3462 | ce=0.3089 | ent=0.2754 | center=0.2352 | val_loss=0.0856 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8995 | val_dqn_proxy_expanded5=0.9086

Epoch 017 | train_loss=0.3423 | ce=0.3063 | ent=0.2724 | center=0.2240 | val_loss=0.1007 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9820 | val_dqn_proxy_expanded5=0.9798

Epoch 018 | train_loss=0.3740 | ce=0.3337 | ent=0.2985 | center=0.2536 | val_loss=0.0813 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9278 | val_dqn_proxy_expanded5=0.9363

Epoch 019 | train_loss=0.3496 | ce=0.3135 | ent=0.2783 | center=0.2220 | val_loss=0.0990 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8263 | val_dqn_proxy_expanded5=0.8459

Epoch 020 | train_loss=0.3425 | ce=0.3085 | ent=0.2768 | center=0.2014 | val_loss=0.0866 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9323 | val_dqn_proxy_expanded5=0.9249

Epoch 021 | train_loss=0.3394 | ce=0.3065 | ent=0.2779 | center=0.1909 | val_loss=0.0826 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9465 | val_dqn_proxy_expanded5=0.9525

Epoch 022 | train_loss=0.3377 | ce=0.3060 | ent=0.2730 | center=0.1814 | val_loss=0.0803 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8757 | val_dqn_proxy_expanded5=0.8743

Epoch 023 | train_loss=0.3361 | ce=0.3053 | ent=0.2717 | center=0.1723 | val_loss=0.0987 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9091 | val_dqn_proxy_expanded5=0.9011

Epoch 024 | train_loss=0.3351 | ce=0.3049 | ent=0.2732 | center=0.1657 | val_loss=0.0933 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9104 | val_dqn_proxy_expanded5=0.9169

Epoch 025 | train_loss=0.3353 | ce=0.3058 | ent=0.2757 | center=0.1575 | val_loss=0.0827 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8878 | val_dqn_proxy_expanded5=0.8841
Early stopping at epoch 25 (best epoch: 10)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
31,ref_base_ent005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-43_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
23,ref_base_drop050_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-25_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
11,ref_base_ls002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
15,ref_base_ls000_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-04_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,ref_base_ls000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-59_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
8,ref_base_ls002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-47_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,ref_base_ls000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-56_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
17,ref_base_drop040_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-07_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
29,ref_base_ent005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,ref_base_ls002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-49_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
25,ref_base_ent002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-28_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
24,ref_base_ent002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-26_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
19,ref_base_drop040_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-11_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
5,ref_base_ls005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,ref_base_ls005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-45_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
27,ref_base_ent002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,ref_base_ls005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-42_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,ref_base_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
21,ref_base_drop050_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-18_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
20,ref_base_drop050_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-14_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
28,ref_base_ent005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-35_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,ref_base_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-29_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
22,ref_base_drop050_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-21_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,ref_base_ls005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-36_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
26,ref_base_ent002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-31_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
18,ref_base_drop040_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-09_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
30,ref_base_ent005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-41_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
16,ref_base_drop040_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-06_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
10,ref_base_ls002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-53_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
14,ref_base_ls000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-02_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"

================================================================================
Running experiment 33/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "cosine",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": null,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_base_ent010",
  "lr": 0.0005,
  "label_smoothing": 0.1,
  "entropy_loss_weight": 0.1,
  "mlp_dropout": 0.3,
  "unknown_pas": [
    "PA2"
  ],
  "run_name": "ref_base_ent010_unkPA2_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.7099 | ce=0.5504 | ent=0.5357 | center=1.0596 | val_loss=0.1687 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8289 | val_dqn_proxy_expanded5=0.8241

Epoch 002 | train_loss=0.5102 | ce=0.3913 | ent=0.3501 | center=0.8387 | val_loss=0.1161 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9143 | val_dqn_proxy_expanded5=0.9162

Epoch 003 | train_loss=0.4708 | ce=0.3663 | ent=0.3276 | center=0.7178 | val_loss=0.1091 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7085 | val_dqn_proxy_expanded5=0.6934

Epoch 004 | train_loss=0.4521 | ce=0.3590 | ent=0.3026 | center=0.6284 | val_loss=0.1261 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8582 | val_dqn_proxy_expanded5=0.8501

Epoch 005 | train_loss=0.4449 | ce=0.3583 | ent=0.3023 | center=0.5636 | val_loss=0.1250 | val_acc=0.9778 | val_macro_f1=0.9779 | val_dqn_proxy_softmax3=0.6325 | val_dqn_proxy_expanded5=0.6869

Epoch 006 | train_loss=0.4323 | ce=0.3505 | ent=0.3027 | center=0.5161 | val_loss=0.1180 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8878 | val_dqn_proxy_expanded5=0.8344

Epoch 007 | train_loss=0.4073 | ce=0.3326 | ent=0.2784 | center=0.4683 | val_loss=0.0880 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6599 | val_dqn_proxy_expanded5=0.7343

Epoch 008 | train_loss=0.3983 | ce=0.3285 | ent=0.2727 | center=0.4252 | val_loss=0.0735 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7347 | val_dqn_proxy_expanded5=0.7689

Epoch 009 | train_loss=0.3823 | ce=0.3180 | ent=0.2638 | center=0.3789 | val_loss=0.0781 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8190 | val_dqn_proxy_expanded5=0.8298

Epoch 010 | train_loss=0.3829 | ce=0.3217 | ent=0.2621 | center=0.3503 | val_loss=0.0795 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7689 | val_dqn_proxy_expanded5=0.7835

Epoch 011 | train_loss=0.3803 | ce=0.3216 | ent=0.2617 | center=0.3258 | val_loss=0.0816 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8385 | val_dqn_proxy_expanded5=0.8045

Epoch 012 | train_loss=0.3791 | ce=0.3231 | ent=0.2598 | center=0.3007 | val_loss=0.1187 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7573 | val_dqn_proxy_expanded5=0.7488

Epoch 013 | train_loss=0.3912 | ce=0.3341 | ent=0.2748 | center=0.2961 | val_loss=0.0700 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8862 | val_dqn_proxy_expanded5=0.8519

Epoch 014 | train_loss=0.3735 | ce=0.3197 | ent=0.2617 | center=0.2755 | val_loss=0.0761 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6398 | val_dqn_proxy_expanded5=0.7543

Epoch 015 | train_loss=0.3699 | ce=0.3192 | ent=0.2556 | center=0.2512 | val_loss=0.0896 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8781 | val_dqn_proxy_expanded5=0.8872

Epoch 016 | train_loss=0.3759 | ce=0.3251 | ent=0.2634 | center=0.2451 | val_loss=0.0913 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6499 | val_dqn_proxy_expanded5=0.7546

Epoch 017 | train_loss=0.3657 | ce=0.3178 | ent=0.2532 | center=0.2256 | val_loss=0.0852 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8024 | val_dqn_proxy_expanded5=0.8052
Early stopping at epoch 17 (best epoch: 2)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
31,ref_base_ent005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-43_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
23,ref_base_drop050_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-25_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
11,ref_base_ls002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
15,ref_base_ls000_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-04_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,ref_base_ls000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-59_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
8,ref_base_ls002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-47_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,ref_base_ls000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-56_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
17,ref_base_drop040_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-07_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
29,ref_base_ent005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,ref_base_ls002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-49_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
25,ref_base_ent002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-28_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
24,ref_base_ent002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-26_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
19,ref_base_drop040_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-11_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
32,ref_base_ent010_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-45_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
5,ref_base_ls005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,ref_base_ls005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-45_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
27,ref_base_ent002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,ref_base_ls005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-42_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,ref_base_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
21,ref_base_drop050_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-18_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
20,ref_base_drop050_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-14_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
28,ref_base_ent005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-35_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,ref_base_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-29_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
22,ref_base_drop050_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-21_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,ref_base_ls005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-36_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
26,ref_base_ent002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-31_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
18,ref_base_drop040_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-09_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
30,ref_base_ent005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-41_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
16,ref_base_drop040_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-06_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
10,ref_base_ls002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-53_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
14,ref_base_ls000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-02_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"

================================================================================
Running experiment 34/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "cosine",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": null,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_base_ent010",
  "lr": 0.0005,
  "label_smoothing": 0.1,
  "entropy_loss_weight": 0.1,
  "mlp_dropout": 0.3,
  "unknown_pas": [
    "PA3"
  ],
  "run_name": "ref_base_ent010_unkPA3_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.7687 | ce=0.5935 | ent=0.5829 | center=1.1691 | val_loss=0.1613 | val_acc=0.9704 | val_macro_f1=0.9704 | val_dqn_proxy_softmax3=0.7136 | val_dqn_proxy_expanded5=0.7550

Epoch 002 | train_loss=0.5571 | ce=0.4231 | ent=0.3789 | center=0.9614 | val_loss=0.1551 | val_acc=0.9519 | val_macro_f1=0.9521 | val_dqn_proxy_softmax3=0.9410 | val_dqn_proxy_expanded5=0.9199

Epoch 003 | train_loss=0.5147 | ce=0.3977 | ent=0.3598 | center=0.8103 | val_loss=0.1214 | val_acc=0.9667 | val_macro_f1=0.9666 | val_dqn_proxy_softmax3=0.9273 | val_dqn_proxy_expanded5=0.9130

Epoch 004 | train_loss=0.5134 | ce=0.4070 | ent=0.3537 | center=0.7103 | val_loss=0.1130 | val_acc=0.9704 | val_macro_f1=0.9704 | val_dqn_proxy_softmax3=0.9049 | val_dqn_proxy_expanded5=0.8848

Epoch 005 | train_loss=0.4954 | ce=0.3970 | ent=0.3440 | center=0.6402 | val_loss=0.1375 | val_acc=0.9741 | val_macro_f1=0.9741 | val_dqn_proxy_softmax3=0.8774 | val_dqn_proxy_expanded5=0.8849

Epoch 006 | train_loss=0.4652 | ce=0.3755 | ent=0.3199 | center=0.5770 | val_loss=0.2027 | val_acc=0.9333 | val_macro_f1=0.9327 | val_dqn_proxy_softmax3=0.9261 | val_dqn_proxy_expanded5=0.9136

Epoch 007 | train_loss=0.4715 | ce=0.3856 | ent=0.3285 | center=0.5305 | val_loss=0.1588 | val_acc=0.9667 | val_macro_f1=0.9666 | val_dqn_proxy_softmax3=0.9429 | val_dqn_proxy_expanded5=0.9352

Epoch 008 | train_loss=0.4530 | ce=0.3723 | ent=0.3239 | center=0.4830 | val_loss=0.0772 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9596 | val_dqn_proxy_expanded5=0.9360

Epoch 009 | train_loss=0.4356 | ce=0.3609 | ent=0.3040 | center=0.4429 | val_loss=0.0739 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9207 | val_dqn_proxy_expanded5=0.8725

Epoch 010 | train_loss=0.4168 | ce=0.3473 | ent=0.2896 | center=0.4059 | val_loss=0.0779 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.8849 | val_dqn_proxy_expanded5=0.8575

Epoch 011 | train_loss=0.4363 | ce=0.3665 | ent=0.3094 | center=0.3892 | val_loss=0.0861 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9536 | val_dqn_proxy_expanded5=0.9130

Epoch 012 | train_loss=0.4115 | ce=0.3475 | ent=0.2852 | center=0.3545 | val_loss=0.0932 | val_acc=0.9741 | val_macro_f1=0.9740 | val_dqn_proxy_softmax3=0.9738 | val_dqn_proxy_expanded5=0.9364

Epoch 013 | train_loss=0.4113 | ce=0.3488 | ent=0.2896 | center=0.3355 | val_loss=0.1049 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8989 | val_dqn_proxy_expanded5=0.8464

Epoch 014 | train_loss=0.4146 | ce=0.3535 | ent=0.2957 | center=0.3149 | val_loss=0.1951 | val_acc=0.9259 | val_macro_f1=0.9250 | val_dqn_proxy_softmax3=0.9380 | val_dqn_proxy_expanded5=0.8849

Epoch 015 | train_loss=0.4176 | ce=0.3575 | ent=0.2969 | center=0.3033 | val_loss=0.0768 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9666 | val_dqn_proxy_expanded5=0.9487

Epoch 016 | train_loss=0.3841 | ce=0.3298 | ent=0.2707 | center=0.2728 | val_loss=0.0763 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9723 | val_dqn_proxy_expanded5=0.9020

Epoch 017 | train_loss=0.3867 | ce=0.3328 | ent=0.2778 | center=0.2607 | val_loss=0.0589 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9800 | val_dqn_proxy_expanded5=0.9597

Epoch 018 | train_loss=0.3818 | ce=0.3304 | ent=0.2689 | center=0.2453 | val_loss=0.0770 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7202 | val_dqn_proxy_expanded5=0.7787

Epoch 019 | train_loss=0.3908 | ce=0.3394 | ent=0.2774 | center=0.2362 | val_loss=0.1558 | val_acc=0.9630 | val_macro_f1=0.9628 | val_dqn_proxy_softmax3=0.9311 | val_dqn_proxy_expanded5=0.8976

Epoch 020 | train_loss=0.3792 | ce=0.3295 | ent=0.2729 | center=0.2232 | val_loss=0.0723 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9849 | val_dqn_proxy_expanded5=0.9519

Epoch 021 | train_loss=0.3741 | ce=0.3265 | ent=0.2680 | center=0.2087 | val_loss=0.0724 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9790 | val_dqn_proxy_expanded5=0.9257

Epoch 022 | train_loss=0.3790 | ce=0.3316 | ent=0.2704 | center=0.2036 | val_loss=0.1168 | val_acc=0.9741 | val_macro_f1=0.9740 | val_dqn_proxy_softmax3=0.9659 | val_dqn_proxy_expanded5=0.9509

Epoch 023 | train_loss=0.3810 | ce=0.3337 | ent=0.2713 | center=0.2019 | val_loss=0.0774 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9844 | val_dqn_proxy_expanded5=0.9325

Epoch 024 | train_loss=0.3713 | ce=0.3254 | ent=0.2718 | center=0.1873 | val_loss=0.0935 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9473 | val_dqn_proxy_expanded5=0.9175

Epoch 025 | train_loss=0.3810 | ce=0.3352 | ent=0.2727 | center=0.1852 | val_loss=0.0926 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9843 | val_dqn_proxy_expanded5=0.9460

Epoch 026 | train_loss=0.3720 | ce=0.3283 | ent=0.2661 | center=0.1706 | val_loss=0.1139 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.9314 | val_dqn_proxy_expanded5=0.9025

Epoch 027 | train_loss=0.3790 | ce=0.3341 | ent=0.2795 | center=0.1696 | val_loss=0.1132 | val_acc=0.9741 | val_macro_f1=0.9740 | val_dqn_proxy_softmax3=0.8323 | val_dqn_proxy_expanded5=0.7919

Epoch 028 | train_loss=0.3837 | ce=0.3390 | ent=0.2747 | center=0.1717 | val_loss=0.0706 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9811 | val_dqn_proxy_expanded5=0.9442

Epoch 029 | train_loss=0.3653 | ce=0.3229 | ent=0.2660 | center=0.1579 | val_loss=0.0596 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9711 | val_dqn_proxy_expanded5=0.9545

Epoch 030 | train_loss=0.3721 | ce=0.3301 | ent=0.2693 | center=0.1513 | val_loss=0.0953 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.9468 | val_dqn_proxy_expanded5=0.9071

Epoch 031 | train_loss=0.3746 | ce=0.3324 | ent=0.2726 | center=0.1489 | val_loss=0.0839 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9287 | val_dqn_proxy_expanded5=0.8820

Epoch 032 | train_loss=0.3953 | ce=0.3515 | ent=0.2872 | center=0.1516 | val_loss=0.0795 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8992 | val_dqn_proxy_expanded5=0.8716

Epoch 033 | train_loss=0.3638 | ce=0.3233 | ent=0.2623 | center=0.1429 | val_loss=0.0775 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9863 | val_dqn_proxy_expanded5=0.9656

Epoch 034 | train_loss=0.3789 | ce=0.3377 | ent=0.2755 | center=0.1366 | val_loss=0.0936 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9663 | val_dqn_proxy_expanded5=0.9173

Epoch 035 | train_loss=0.3678 | ce=0.3274 | ent=0.2701 | center=0.1331 | val_loss=0.0685 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9682 | val_dqn_proxy_expanded5=0.9363

Epoch 036 | train_loss=0.3664 | ce=0.3271 | ent=0.2631 | center=0.1296 | val_loss=0.0827 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9774 | val_dqn_proxy_expanded5=0.9692

Epoch 037 | train_loss=0.3599 | ce=0.3213 | ent=0.2648 | center=0.1212 | val_loss=0.0817 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9777 | val_dqn_proxy_expanded5=0.9360

Epoch 038 | train_loss=0.3652 | ce=0.3266 | ent=0.2678 | center=0.1176 | val_loss=0.0717 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9608 | val_dqn_proxy_expanded5=0.9306

Epoch 039 | train_loss=0.3513 | ce=0.3146 | ent=0.2581 | center=0.1096 | val_loss=0.0747 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9087 | val_dqn_proxy_expanded5=0.8778

Epoch 040 | train_loss=0.3662 | ce=0.3289 | ent=0.2622 | center=0.1117 | val_loss=0.0814 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9824 | val_dqn_proxy_expanded5=0.9291

Epoch 041 | train_loss=0.3556 | ce=0.3183 | ent=0.2656 | center=0.1074 | val_loss=0.0576 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9773 | val_dqn_proxy_expanded5=0.9263

Epoch 042 | train_loss=0.3583 | ce=0.3220 | ent=0.2625 | center=0.1004 | val_loss=0.0615 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9816 | val_dqn_proxy_expanded5=0.9268

Epoch 043 | train_loss=0.3482 | ce=0.3134 | ent=0.2535 | center=0.0950 | val_loss=0.1017 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.9865 | val_dqn_proxy_expanded5=0.9401

Epoch 044 | train_loss=0.3713 | ce=0.3343 | ent=0.2713 | center=0.0982 | val_loss=0.0955 | val_acc=0.9704 | val_macro_f1=0.9703 | val_dqn_proxy_softmax3=0.9717 | val_dqn_proxy_expanded5=0.9307

Epoch 045 | train_loss=0.3619 | ce=0.3252 | ent=0.2660 | center=0.1011 | val_loss=0.0792 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9719 | val_dqn_proxy_expanded5=0.9280

Epoch 046 | train_loss=0.3594 | ce=0.3238 | ent=0.2629 | center=0.0932 | val_loss=0.1143 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.8780 | val_dqn_proxy_expanded5=0.8418

Epoch 047 | train_loss=0.3569 | ce=0.3212 | ent=0.2644 | center=0.0920 | val_loss=0.0964 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6510 | val_dqn_proxy_expanded5=0.6955

Epoch 048 | train_loss=0.3514 | ce=0.3169 | ent=0.2575 | center=0.0881 | val_loss=0.0609 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9898 | val_dqn_proxy_expanded5=0.9667

Epoch 049 | train_loss=0.3564 | ce=0.3218 | ent=0.2599 | center=0.0859 | val_loss=0.0702 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.8613 | val_dqn_proxy_expanded5=0.8180

Epoch 050 | train_loss=0.3439 | ce=0.3102 | ent=0.2557 | center=0.0814 | val_loss=0.0701 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.8635 | val_dqn_proxy_expanded5=0.8281

Epoch 051 | train_loss=0.3467 | ce=0.3136 | ent=0.2532 | center=0.0777 | val_loss=0.0568 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9894 | val_dqn_proxy_expanded5=0.9544

Epoch 052 | train_loss=0.3517 | ce=0.3182 | ent=0.2594 | center=0.0758 | val_loss=0.0617 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.7661 | val_dqn_proxy_expanded5=0.7653

Epoch 053 | train_loss=0.3478 | ce=0.3143 | ent=0.2576 | center=0.0773 | val_loss=0.0544 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9747 | val_dqn_proxy_expanded5=0.9192

Epoch 054 | train_loss=0.3429 | ce=0.3101 | ent=0.2526 | center=0.0756 | val_loss=0.0545 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9121 | val_dqn_proxy_expanded5=0.8621

Epoch 055 | train_loss=0.3542 | ce=0.3213 | ent=0.2580 | center=0.0709 | val_loss=0.0738 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8607 | val_dqn_proxy_expanded5=0.9031

Epoch 056 | train_loss=0.3552 | ce=0.3214 | ent=0.2633 | center=0.0738 | val_loss=0.0480 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9842 | val_dqn_proxy_expanded5=0.9655

Epoch 057 | train_loss=0.3488 | ce=0.3162 | ent=0.2551 | center=0.0700 | val_loss=0.0610 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9785 | val_dqn_proxy_expanded5=0.9513

Epoch 058 | train_loss=0.3563 | ce=0.3231 | ent=0.2646 | center=0.0669 | val_loss=0.0690 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9700 | val_dqn_proxy_expanded5=0.9472

Epoch 059 | train_loss=0.3510 | ce=0.3187 | ent=0.2571 | center=0.0654 | val_loss=0.0920 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9388 | val_dqn_proxy_expanded5=0.8944

Epoch 060 | train_loss=0.3434 | ce=0.3119 | ent=0.2509 | center=0.0634 | val_loss=0.0681 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.8406 | val_dqn_proxy_expanded5=0.8391

Epoch 061 | train_loss=0.3538 | ce=0.3209 | ent=0.2647 | center=0.0640 | val_loss=0.0561 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9850 | val_dqn_proxy_expanded5=0.9504

Epoch 062 | train_loss=0.3444 | ce=0.3127 | ent=0.2554 | center=0.0607 | val_loss=0.0757 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9015 | val_dqn_proxy_expanded5=0.8646

Epoch 063 | train_loss=0.3472 | ce=0.3159 | ent=0.2524 | center=0.0610 | val_loss=0.0886 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9570 | val_dqn_proxy_expanded5=0.9114
Early stopping at epoch 63 (best epoch: 48)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
31,ref_base_ent005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-43_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
23,ref_base_drop050_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-25_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
11,ref_base_ls002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
33,ref_base_ent010_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-46_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
15,ref_base_ls000_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-04_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,ref_base_ls000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-59_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
8,ref_base_ls002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-47_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,ref_base_ls000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-56_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
17,ref_base_drop040_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-07_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
29,ref_base_ent005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,ref_base_ls002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-49_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
25,ref_base_ent002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-28_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
24,ref_base_ent002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-26_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
19,ref_base_drop040_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-11_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
32,ref_base_ent010_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-45_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
5,ref_base_ls005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,ref_base_ls005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-45_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
27,ref_base_ent002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,ref_base_ls005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-42_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,ref_base_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
21,ref_base_drop050_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-18_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
20,ref_base_drop050_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-14_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
28,ref_base_ent005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-35_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,ref_base_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-29_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
22,ref_base_drop050_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-21_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,ref_base_ls005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-36_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
26,ref_base_ent002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-31_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
18,ref_base_drop040_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-09_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
30,ref_base_ent005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-41_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
16,ref_base_drop040_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-06_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
10,ref_base_ls002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-53_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
14,ref_base_ls000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-02_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"

================================================================================
Running experiment 35/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "cosine",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": null,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_base_ent010",
  "lr": 0.0005,
  "label_smoothing": 0.1,
  "entropy_loss_weight": 0.1,
  "mlp_dropout": 0.3,
  "unknown_pas": [
    "PA4"
  ],
  "run_name": "ref_base_ent010_unkPA4_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.8193 | ce=0.6444 | ent=0.6222 | center=1.1260 | val_loss=0.2452 | val_acc=0.9333 | val_macro_f1=0.9331 | val_dqn_proxy_softmax3=0.7085 | val_dqn_proxy_expanded5=0.6880

Epoch 002 | train_loss=0.5746 | ce=0.4429 | ent=0.4015 | center=0.9158 | val_loss=0.2938 | val_acc=0.8926 | val_macro_f1=0.8912 | val_dqn_proxy_softmax3=0.7094 | val_dqn_proxy_expanded5=0.6821

Epoch 003 | train_loss=0.5541 | ce=0.4373 | ent=0.3909 | center=0.7772 | val_loss=0.1641 | val_acc=0.9519 | val_macro_f1=0.9521 | val_dqn_proxy_softmax3=0.8769 | val_dqn_proxy_expanded5=0.7998

Epoch 004 | train_loss=0.5100 | ce=0.4051 | ent=0.3662 | center=0.6826 | val_loss=0.0900 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9314 | val_dqn_proxy_expanded5=0.8462

Epoch 005 | train_loss=0.4672 | ce=0.3735 | ent=0.3281 | center=0.6096 | val_loss=0.1753 | val_acc=0.9519 | val_macro_f1=0.9516 | val_dqn_proxy_softmax3=0.7068 | val_dqn_proxy_expanded5=0.7341

Epoch 006 | train_loss=0.4580 | ce=0.3722 | ent=0.3136 | center=0.5450 | val_loss=0.1255 | val_acc=0.9667 | val_macro_f1=0.9666 | val_dqn_proxy_softmax3=0.8842 | val_dqn_proxy_expanded5=0.8299

Epoch 007 | train_loss=0.4739 | ce=0.3890 | ent=0.3336 | center=0.5153 | val_loss=0.0997 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7545 | val_dqn_proxy_expanded5=0.7364

Epoch 008 | train_loss=0.4468 | ce=0.3682 | ent=0.3100 | center=0.4762 | val_loss=0.1813 | val_acc=0.9296 | val_macro_f1=0.9288 | val_dqn_proxy_softmax3=0.8362 | val_dqn_proxy_expanded5=0.8098

Epoch 009 | train_loss=0.4256 | ce=0.3528 | ent=0.3024 | center=0.4252 | val_loss=0.0986 | val_acc=0.9741 | val_macro_f1=0.9740 | val_dqn_proxy_softmax3=0.9159 | val_dqn_proxy_expanded5=0.8795

Epoch 010 | train_loss=0.4157 | ce=0.3468 | ent=0.2934 | center=0.3955 | val_loss=0.0679 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7670 | val_dqn_proxy_expanded5=0.7521

Epoch 011 | train_loss=0.4049 | ce=0.3400 | ent=0.2831 | center=0.3658 | val_loss=0.0677 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9476 | val_dqn_proxy_expanded5=0.8739

Epoch 012 | train_loss=0.4118 | ce=0.3486 | ent=0.2892 | center=0.3424 | val_loss=0.1267 | val_acc=0.9704 | val_macro_f1=0.9704 | val_dqn_proxy_softmax3=0.7136 | val_dqn_proxy_expanded5=0.7693

Epoch 013 | train_loss=0.4021 | ce=0.3415 | ent=0.2808 | center=0.3247 | val_loss=0.1099 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9343 | val_dqn_proxy_expanded5=0.8506

Epoch 014 | train_loss=0.3902 | ce=0.3319 | ent=0.2760 | center=0.3070 | val_loss=0.0754 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9359 | val_dqn_proxy_expanded5=0.8757

Epoch 015 | train_loss=0.4027 | ce=0.3446 | ent=0.2874 | center=0.2939 | val_loss=0.0953 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7146 | val_dqn_proxy_expanded5=0.7509

Epoch 016 | train_loss=0.3952 | ce=0.3396 | ent=0.2792 | center=0.2766 | val_loss=0.0781 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.7574 | val_dqn_proxy_expanded5=0.7738

Epoch 017 | train_loss=0.3783 | ce=0.3253 | ent=0.2697 | center=0.2599 | val_loss=0.0822 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7628 | val_dqn_proxy_expanded5=0.7797

Epoch 018 | train_loss=0.3785 | ce=0.3273 | ent=0.2663 | center=0.2454 | val_loss=0.1077 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.7693 | val_dqn_proxy_expanded5=0.7785

Epoch 019 | train_loss=0.3688 | ce=0.3192 | ent=0.2636 | center=0.2322 | val_loss=0.0773 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9600 | val_dqn_proxy_expanded5=0.8937

Epoch 020 | train_loss=0.3847 | ce=0.3348 | ent=0.2718 | center=0.2274 | val_loss=0.0606 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8400 | val_dqn_proxy_expanded5=0.8176

Epoch 021 | train_loss=0.3841 | ce=0.3344 | ent=0.2717 | center=0.2257 | val_loss=0.0858 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.7573 | val_dqn_proxy_expanded5=0.7751

Epoch 022 | train_loss=0.3885 | ce=0.3395 | ent=0.2793 | center=0.2102 | val_loss=0.0808 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9504 | val_dqn_proxy_expanded5=0.8690

Epoch 023 | train_loss=0.3737 | ce=0.3268 | ent=0.2709 | center=0.1984 | val_loss=0.0731 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.7648 | val_dqn_proxy_expanded5=0.7795

Epoch 024 | train_loss=0.3819 | ce=0.3352 | ent=0.2736 | center=0.1936 | val_loss=0.0950 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7820 | val_dqn_proxy_expanded5=0.7711

Epoch 025 | train_loss=0.3697 | ce=0.3253 | ent=0.2638 | center=0.1801 | val_loss=0.1084 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7710 | val_dqn_proxy_expanded5=0.7779

Epoch 026 | train_loss=0.3644 | ce=0.3207 | ent=0.2655 | center=0.1718 | val_loss=0.0766 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.7630 | val_dqn_proxy_expanded5=0.7683

Epoch 027 | train_loss=0.3646 | ce=0.3222 | ent=0.2612 | center=0.1632 | val_loss=0.0800 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.7720 | val_dqn_proxy_expanded5=0.7840

Epoch 028 | train_loss=0.3763 | ce=0.3325 | ent=0.2731 | center=0.1657 | val_loss=0.0781 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7655 | val_dqn_proxy_expanded5=0.7807

Epoch 029 | train_loss=0.3645 | ce=0.3226 | ent=0.2656 | center=0.1532 | val_loss=0.0762 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.8684 | val_dqn_proxy_expanded5=0.8271

Epoch 030 | train_loss=0.3609 | ce=0.3205 | ent=0.2610 | center=0.1426 | val_loss=0.0866 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7680 | val_dqn_proxy_expanded5=0.7748

Epoch 031 | train_loss=0.3618 | ce=0.3217 | ent=0.2623 | center=0.1386 | val_loss=0.0684 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.8312 | val_dqn_proxy_expanded5=0.7993

Epoch 032 | train_loss=0.3650 | ce=0.3245 | ent=0.2667 | center=0.1379 | val_loss=0.0717 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8500 | val_dqn_proxy_expanded5=0.8089

Epoch 033 | train_loss=0.3616 | ce=0.3223 | ent=0.2605 | center=0.1329 | val_loss=0.0792 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.7614 | val_dqn_proxy_expanded5=0.7649

Epoch 034 | train_loss=0.3592 | ce=0.3200 | ent=0.2646 | center=0.1270 | val_loss=0.0585 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.7818 | val_dqn_proxy_expanded5=0.7560
Early stopping at epoch 34 (best epoch: 19)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
31,ref_base_ent005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-43_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
23,ref_base_drop050_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-25_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
11,ref_base_ls002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
33,ref_base_ent010_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-46_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
15,ref_base_ls000_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-04_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,ref_base_ls000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-59_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
8,ref_base_ls002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-47_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,ref_base_ls000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-56_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
17,ref_base_drop040_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-07_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
29,ref_base_ent005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,ref_base_ls002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-49_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
25,ref_base_ent002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-28_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
24,ref_base_ent002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-26_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
19,ref_base_drop040_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-11_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
32,ref_base_ent010_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-45_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
5,ref_base_ls005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,ref_base_ls005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-45_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
27,ref_base_ent002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,ref_base_ls005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-42_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,ref_base_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
21,ref_base_drop050_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-18_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
20,ref_base_drop050_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-14_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
28,ref_base_ent005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-35_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,ref_base_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-29_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
22,ref_base_drop050_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-21_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
34,ref_base_ent010_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-52_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,ref_base_ls005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-36_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
26,ref_base_ent002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-31_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
18,ref_base_drop040_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-09_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
30,ref_base_ent005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-41_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
16,ref_base_drop040_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-06_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
10,ref_base_ls002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-53_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
14,ref_base_ls000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-02_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"

================================================================================
Running experiment 36/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "cosine",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": null,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_base_ent010",
  "lr": 0.0005,
  "label_smoothing": 0.1,
  "entropy_loss_weight": 0.1,
  "mlp_dropout": 0.3,
  "unknown_pas": [
    "PA8"
  ],
  "run_name": "ref_base_ent010_unkPA8_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.6421 | ce=0.4818 | ent=0.4691 | center=1.1339 | val_loss=0.1468 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8847 | val_dqn_proxy_expanded5=0.8888

Epoch 002 | train_loss=0.4632 | ce=0.3482 | ent=0.3052 | center=0.8449 | val_loss=0.1095 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9282 | val_dqn_proxy_expanded5=0.8971

Epoch 003 | train_loss=0.4581 | ce=0.3541 | ent=0.3066 | center=0.7330 | val_loss=0.1027 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9294 | val_dqn_proxy_expanded5=0.9139

Epoch 004 | train_loss=0.4260 | ce=0.3349 | ent=0.2826 | center=0.6286 | val_loss=0.1042 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8909 | val_dqn_proxy_expanded5=0.8765

Epoch 005 | train_loss=0.4107 | ce=0.3283 | ent=0.2801 | center=0.5440 | val_loss=0.0759 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9533 | val_dqn_proxy_expanded5=0.9345

Epoch 006 | train_loss=0.4006 | ce=0.3252 | ent=0.2666 | center=0.4876 | val_loss=0.1103 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8329 | val_dqn_proxy_expanded5=0.8131

Epoch 007 | train_loss=0.4008 | ce=0.3288 | ent=0.2713 | center=0.4487 | val_loss=0.0763 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9046 | val_dqn_proxy_expanded5=0.8749

Epoch 008 | train_loss=0.3770 | ce=0.3126 | ent=0.2524 | center=0.3911 | val_loss=0.0778 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8689 | val_dqn_proxy_expanded5=0.8436

Epoch 009 | train_loss=0.3728 | ce=0.3124 | ent=0.2510 | center=0.3523 | val_loss=0.0921 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8306 | val_dqn_proxy_expanded5=0.8017

Epoch 010 | train_loss=0.3729 | ce=0.3140 | ent=0.2535 | center=0.3357 | val_loss=0.0694 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9446 | val_dqn_proxy_expanded5=0.9056

Epoch 011 | train_loss=0.3673 | ce=0.3113 | ent=0.2509 | center=0.3089 | val_loss=0.0865 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9543 | val_dqn_proxy_expanded5=0.9176

Epoch 012 | train_loss=0.3691 | ce=0.3145 | ent=0.2513 | center=0.2944 | val_loss=0.0786 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9610 | val_dqn_proxy_expanded5=0.9264

Epoch 013 | train_loss=0.3645 | ce=0.3118 | ent=0.2517 | center=0.2752 | val_loss=0.0718 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9338 | val_dqn_proxy_expanded5=0.9011

Epoch 014 | train_loss=0.3595 | ce=0.3094 | ent=0.2478 | center=0.2533 | val_loss=0.0709 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9515 | val_dqn_proxy_expanded5=0.9006

Epoch 015 | train_loss=0.3569 | ce=0.3084 | ent=0.2444 | center=0.2416 | val_loss=0.0861 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8794 | val_dqn_proxy_expanded5=0.8568

Epoch 016 | train_loss=0.3545 | ce=0.3076 | ent=0.2454 | center=0.2239 | val_loss=0.0850 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9695 | val_dqn_proxy_expanded5=0.9153

Epoch 017 | train_loss=0.3550 | ce=0.3089 | ent=0.2472 | center=0.2143 | val_loss=0.0749 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8412 | val_dqn_proxy_expanded5=0.8148

Epoch 018 | train_loss=0.3594 | ce=0.3133 | ent=0.2528 | center=0.2080 | val_loss=0.0765 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9549 | val_dqn_proxy_expanded5=0.8985

Epoch 019 | train_loss=0.3533 | ce=0.3089 | ent=0.2463 | center=0.1980 | val_loss=0.0823 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9629 | val_dqn_proxy_expanded5=0.9192

Epoch 020 | train_loss=0.3519 | ce=0.3088 | ent=0.2449 | center=0.1861 | val_loss=0.0747 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8631 | val_dqn_proxy_expanded5=0.8225

Epoch 021 | train_loss=0.3518 | ce=0.3093 | ent=0.2461 | center=0.1792 | val_loss=0.0837 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9178 | val_dqn_proxy_expanded5=0.8727

Epoch 022 | train_loss=0.3487 | ce=0.3072 | ent=0.2450 | center=0.1698 | val_loss=0.0840 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8550 | val_dqn_proxy_expanded5=0.8161

Epoch 023 | train_loss=0.3493 | ce=0.3080 | ent=0.2482 | center=0.1651 | val_loss=0.0762 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9016 | val_dqn_proxy_expanded5=0.8477

Epoch 024 | train_loss=0.3493 | ce=0.3087 | ent=0.2489 | center=0.1563 | val_loss=0.0788 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9197 | val_dqn_proxy_expanded5=0.8717

Epoch 025 | train_loss=0.3480 | ce=0.3081 | ent=0.2470 | center=0.1521 | val_loss=0.0758 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8650 | val_dqn_proxy_expanded5=0.8360

Epoch 026 | train_loss=0.3462 | ce=0.3072 | ent=0.2431 | center=0.1465 | val_loss=0.0885 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9045 | val_dqn_proxy_expanded5=0.8515

Epoch 027 | train_loss=0.3450 | ce=0.3065 | ent=0.2474 | center=0.1374 | val_loss=0.0819 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8683 | val_dqn_proxy_expanded5=0.8303

Epoch 028 | train_loss=0.3451 | ce=0.3070 | ent=0.2462 | center=0.1343 | val_loss=0.0756 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9601 | val_dqn_proxy_expanded5=0.8932

Epoch 029 | train_loss=0.3438 | ce=0.3067 | ent=0.2447 | center=0.1264 | val_loss=0.0827 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8272 | val_dqn_proxy_expanded5=0.8061

Epoch 030 | train_loss=0.3462 | ce=0.3088 | ent=0.2481 | center=0.1259 | val_loss=0.0764 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9230 | val_dqn_proxy_expanded5=0.8689

Epoch 031 | train_loss=0.3441 | ce=0.3074 | ent=0.2463 | center=0.1212 | val_loss=0.0753 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9388 | val_dqn_proxy_expanded5=0.8755
Early stopping at epoch 31 (best epoch: 16)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
31,ref_base_ent005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-43_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
23,ref_base_drop050_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-25_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
11,ref_base_ls002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
33,ref_base_ent010_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-46_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
15,ref_base_ls000_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-04_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,ref_base_ls000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-59_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
8,ref_base_ls002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-47_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,ref_base_ls000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-56_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
17,ref_base_drop040_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-07_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
29,ref_base_ent005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,ref_base_ls002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-49_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
25,ref_base_ent002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-28_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
24,ref_base_ent002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-26_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
19,ref_base_drop040_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-11_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
32,ref_base_ent010_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-45_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
5,ref_base_ls005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,ref_base_ls005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-45_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
27,ref_base_ent002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,ref_base_ls005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-42_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,ref_base_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
35,ref_base_ent010_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
21,ref_base_drop050_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-18_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
20,ref_base_drop050_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-14_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
28,ref_base_ent005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-35_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,ref_base_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-29_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
22,ref_base_drop050_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-21_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
34,ref_base_ent010_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-52_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,ref_base_ls005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-36_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
26,ref_base_ent002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-31_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
18,ref_base_drop040_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-09_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
30,ref_base_ent005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-41_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
16,ref_base_drop040_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-06_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
10,ref_base_ls002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-53_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
14,ref_base_ls000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-02_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"

================================================================================
Running experiment 37/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "cosine",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": null,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_base_lr2e4",
  "lr": 0.0002,
  "label_smoothing": 0.1,
  "entropy_loss_weight": 0.0,
  "mlp_dropout": 0.3,
  "unknown_pas": [
    "PA2"
  ],
  "run_name": "ref_base_lr2e4_unkPA2_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.7386 | ce=0.6185 | ent=0.0000 | center=1.2012 | val_loss=0.2684 | val_acc=0.9296 | val_macro_f1=0.9298 | val_dqn_proxy_softmax3=0.7147 | val_dqn_proxy_expanded5=0.7477

Epoch 002 | train_loss=0.5046 | ce=0.4001 | ent=0.0000 | center=1.0450 | val_loss=0.1923 | val_acc=0.9519 | val_macro_f1=0.9521 | val_dqn_proxy_softmax3=0.6985 | val_dqn_proxy_expanded5=0.7425

Epoch 003 | train_loss=0.4573 | ce=0.3658 | ent=0.0000 | center=0.9146 | val_loss=0.1322 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6480 | val_dqn_proxy_expanded5=0.6879

Epoch 004 | train_loss=0.4316 | ce=0.3485 | ent=0.0000 | center=0.8311 | val_loss=0.1294 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8637 | val_dqn_proxy_expanded5=0.8503

Epoch 005 | train_loss=0.4253 | ce=0.3484 | ent=0.0000 | center=0.7690 | val_loss=0.1115 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6365 | val_dqn_proxy_expanded5=0.6859

Epoch 006 | train_loss=0.4188 | ce=0.3462 | ent=0.0000 | center=0.7257 | val_loss=0.1488 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6932 | val_dqn_proxy_expanded5=0.7464

Epoch 007 | train_loss=0.4085 | ce=0.3402 | ent=0.0000 | center=0.6826 | val_loss=0.1169 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6404 | val_dqn_proxy_expanded5=0.6862

Epoch 008 | train_loss=0.4082 | ce=0.3430 | ent=0.0000 | center=0.6522 | val_loss=0.1239 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7527 | val_dqn_proxy_expanded5=0.7952

Epoch 009 | train_loss=0.4014 | ce=0.3390 | ent=0.0000 | center=0.6231 | val_loss=0.1208 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8403 | val_dqn_proxy_expanded5=0.8100

Epoch 010 | train_loss=0.4006 | ce=0.3404 | ent=0.0000 | center=0.6022 | val_loss=0.0962 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6998 | val_dqn_proxy_expanded5=0.7279

Epoch 011 | train_loss=0.3771 | ce=0.3208 | ent=0.0000 | center=0.5630 | val_loss=0.1107 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7832 | val_dqn_proxy_expanded5=0.7932

Epoch 012 | train_loss=0.3732 | ce=0.3195 | ent=0.0000 | center=0.5375 | val_loss=0.0796 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8706 | val_dqn_proxy_expanded5=0.8446

Epoch 013 | train_loss=0.3715 | ce=0.3200 | ent=0.0000 | center=0.5150 | val_loss=0.0905 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8418 | val_dqn_proxy_expanded5=0.8153

Epoch 014 | train_loss=0.3711 | ce=0.3216 | ent=0.0000 | center=0.4948 | val_loss=0.0844 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8322 | val_dqn_proxy_expanded5=0.8266

Epoch 015 | train_loss=0.3626 | ce=0.3159 | ent=0.0000 | center=0.4669 | val_loss=0.0914 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9083 | val_dqn_proxy_expanded5=0.8641

Epoch 016 | train_loss=0.3613 | ce=0.3165 | ent=0.0000 | center=0.4478 | val_loss=0.0829 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6568 | val_dqn_proxy_expanded5=0.6750

Epoch 017 | train_loss=0.3584 | ce=0.3158 | ent=0.0000 | center=0.4265 | val_loss=0.0844 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7799 | val_dqn_proxy_expanded5=0.7946

Epoch 018 | train_loss=0.3635 | ce=0.3217 | ent=0.0000 | center=0.4178 | val_loss=0.0718 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7527 | val_dqn_proxy_expanded5=0.7794

Epoch 019 | train_loss=0.3775 | ce=0.3363 | ent=0.0000 | center=0.4118 | val_loss=0.0923 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.5140 | val_dqn_proxy_expanded5=0.6129

Epoch 020 | train_loss=0.3538 | ce=0.3151 | ent=0.0000 | center=0.3868 | val_loss=0.0922 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8385 | val_dqn_proxy_expanded5=0.8120

Epoch 021 | train_loss=0.3640 | ce=0.3262 | ent=0.0000 | center=0.3779 | val_loss=0.1051 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9611 | val_dqn_proxy_expanded5=0.8805

Epoch 022 | train_loss=0.3545 | ce=0.3176 | ent=0.0000 | center=0.3688 | val_loss=0.0940 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6547 | val_dqn_proxy_expanded5=0.6667

Epoch 023 | train_loss=0.3476 | ce=0.3128 | ent=0.0000 | center=0.3476 | val_loss=0.0871 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9361 | val_dqn_proxy_expanded5=0.8747

Epoch 024 | train_loss=0.3479 | ce=0.3142 | ent=0.0000 | center=0.3369 | val_loss=0.1035 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6826 | val_dqn_proxy_expanded5=0.7014

Epoch 025 | train_loss=0.3450 | ce=0.3128 | ent=0.0000 | center=0.3221 | val_loss=0.1101 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7301 | val_dqn_proxy_expanded5=0.7256

Epoch 026 | train_loss=0.3452 | ce=0.3135 | ent=0.0000 | center=0.3162 | val_loss=0.0951 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8723 | val_dqn_proxy_expanded5=0.8247

Epoch 027 | train_loss=0.3500 | ce=0.3193 | ent=0.0000 | center=0.3072 | val_loss=0.1156 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8838 | val_dqn_proxy_expanded5=0.8718

Epoch 028 | train_loss=0.3487 | ce=0.3183 | ent=0.0000 | center=0.3034 | val_loss=0.1097 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6526 | val_dqn_proxy_expanded5=0.6628

Epoch 029 | train_loss=0.3427 | ce=0.3137 | ent=0.0000 | center=0.2899 | val_loss=0.0984 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9425 | val_dqn_proxy_expanded5=0.8678

Epoch 030 | train_loss=0.3415 | ce=0.3134 | ent=0.0000 | center=0.2812 | val_loss=0.0870 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6945 | val_dqn_proxy_expanded5=0.6855

Epoch 031 | train_loss=0.3398 | ce=0.3127 | ent=0.0000 | center=0.2716 | val_loss=0.0962 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6420 | val_dqn_proxy_expanded5=0.6491

Epoch 032 | train_loss=0.3394 | ce=0.3127 | ent=0.0000 | center=0.2673 | val_loss=0.0968 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6754 | val_dqn_proxy_expanded5=0.6574

Epoch 033 | train_loss=0.3381 | ce=0.3123 | ent=0.0000 | center=0.2584 | val_loss=0.0941 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8429 | val_dqn_proxy_expanded5=0.7803

Epoch 034 | train_loss=0.3380 | ce=0.3126 | ent=0.0000 | center=0.2534 | val_loss=0.0890 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9254 | val_dqn_proxy_expanded5=0.8610

Epoch 035 | train_loss=0.3398 | ce=0.3148 | ent=0.0000 | center=0.2503 | val_loss=0.0898 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6899 | val_dqn_proxy_expanded5=0.6711

Epoch 036 | train_loss=0.3357 | ce=0.3113 | ent=0.0000 | center=0.2434 | val_loss=0.0868 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7024 | val_dqn_proxy_expanded5=0.7229
Early stopping at epoch 36 (best epoch: 21)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
31,ref_base_ent005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-43_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
23,ref_base_drop050_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-25_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
11,ref_base_ls002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
33,ref_base_ent010_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-46_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
15,ref_base_ls000_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-04_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,ref_base_ls000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-59_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
8,ref_base_ls002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-47_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,ref_base_ls000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-56_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
17,ref_base_drop040_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-07_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
29,ref_base_ent005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,ref_base_ls002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-49_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
25,ref_base_ent002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-28_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
24,ref_base_ent002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-26_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
19,ref_base_drop040_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-11_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
32,ref_base_ent010_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-45_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
5,ref_base_ls005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,ref_base_ls005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-45_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
27,ref_base_ent002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,ref_base_ls005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-42_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,ref_base_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
35,ref_base_ent010_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
21,ref_base_drop050_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-18_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
20,ref_base_drop050_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-14_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
28,ref_base_ent005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-35_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,ref_base_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-29_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
22,ref_base_drop050_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-21_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
34,ref_base_ent010_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-52_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
36,ref_base_lr2e4_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-57_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,ref_base_ls005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-36_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
26,ref_base_ent002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-31_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
18,ref_base_drop040_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-09_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
30,ref_base_ent005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-41_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
16,ref_base_drop040_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-06_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
10,ref_base_ls002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-53_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
14,ref_base_ls000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-02_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"

================================================================================
Running experiment 38/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "cosine",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": null,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_base_lr2e4",
  "lr": 0.0002,
  "label_smoothing": 0.1,
  "entropy_loss_weight": 0.0,
  "mlp_dropout": 0.3,
  "unknown_pas": [
    "PA3"
  ],
  "run_name": "ref_base_lr2e4_unkPA3_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.7579 | ce=0.6510 | ent=0.0000 | center=1.0691 | val_loss=0.2377 | val_acc=0.9593 | val_macro_f1=0.9588 | val_dqn_proxy_softmax3=0.8638 | val_dqn_proxy_expanded5=0.8016

Epoch 002 | train_loss=0.5354 | ce=0.4387 | ent=0.0000 | center=0.9670 | val_loss=0.1866 | val_acc=0.9481 | val_macro_f1=0.9484 | val_dqn_proxy_softmax3=0.8364 | val_dqn_proxy_expanded5=0.8142

Epoch 003 | train_loss=0.5029 | ce=0.4165 | ent=0.0000 | center=0.8645 | val_loss=0.1891 | val_acc=0.9519 | val_macro_f1=0.9518 | val_dqn_proxy_softmax3=0.9073 | val_dqn_proxy_expanded5=0.8750

Epoch 004 | train_loss=0.4975 | ce=0.4186 | ent=0.0000 | center=0.7894 | val_loss=0.2067 | val_acc=0.9259 | val_macro_f1=0.9259 | val_dqn_proxy_softmax3=0.7403 | val_dqn_proxy_expanded5=0.7497

Epoch 005 | train_loss=0.4537 | ce=0.3794 | ent=0.0000 | center=0.7426 | val_loss=0.1591 | val_acc=0.9444 | val_macro_f1=0.9447 | val_dqn_proxy_softmax3=0.8950 | val_dqn_proxy_expanded5=0.9022

Epoch 006 | train_loss=0.4609 | ce=0.3913 | ent=0.0000 | center=0.6966 | val_loss=0.1383 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9356 | val_dqn_proxy_expanded5=0.9071

Epoch 007 | train_loss=0.4277 | ce=0.3621 | ent=0.0000 | center=0.6556 | val_loss=0.1612 | val_acc=0.9444 | val_macro_f1=0.9441 | val_dqn_proxy_softmax3=0.9680 | val_dqn_proxy_expanded5=0.9221

Epoch 008 | train_loss=0.4260 | ce=0.3635 | ent=0.0000 | center=0.6248 | val_loss=0.1105 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9567 | val_dqn_proxy_expanded5=0.9230

Epoch 009 | train_loss=0.4109 | ce=0.3516 | ent=0.0000 | center=0.5931 | val_loss=0.1098 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9446 | val_dqn_proxy_expanded5=0.8965

Epoch 010 | train_loss=0.4088 | ce=0.3521 | ent=0.0000 | center=0.5669 | val_loss=0.1243 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9604 | val_dqn_proxy_expanded5=0.9226

Epoch 011 | train_loss=0.3987 | ce=0.3446 | ent=0.0000 | center=0.5414 | val_loss=0.1458 | val_acc=0.9667 | val_macro_f1=0.9666 | val_dqn_proxy_softmax3=0.9571 | val_dqn_proxy_expanded5=0.9439

Epoch 012 | train_loss=0.3994 | ce=0.3478 | ent=0.0000 | center=0.5158 | val_loss=0.1135 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9262 | val_dqn_proxy_expanded5=0.9196

Epoch 013 | train_loss=0.3855 | ce=0.3361 | ent=0.0000 | center=0.4934 | val_loss=0.1190 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9813 | val_dqn_proxy_expanded5=0.9430

Epoch 014 | train_loss=0.3885 | ce=0.3410 | ent=0.0000 | center=0.4755 | val_loss=0.0955 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9755 | val_dqn_proxy_expanded5=0.9530

Epoch 015 | train_loss=0.3772 | ce=0.3318 | ent=0.0000 | center=0.4544 | val_loss=0.0936 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9792 | val_dqn_proxy_expanded5=0.9593

Epoch 016 | train_loss=0.3737 | ce=0.3299 | ent=0.0000 | center=0.4379 | val_loss=0.0887 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9243 | val_dqn_proxy_expanded5=0.9160

Epoch 017 | train_loss=0.3765 | ce=0.3343 | ent=0.0000 | center=0.4222 | val_loss=0.1433 | val_acc=0.9667 | val_macro_f1=0.9666 | val_dqn_proxy_softmax3=0.9634 | val_dqn_proxy_expanded5=0.9466

Epoch 018 | train_loss=0.3844 | ce=0.3432 | ent=0.0000 | center=0.4114 | val_loss=0.0942 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9680 | val_dqn_proxy_expanded5=0.9546

Epoch 019 | train_loss=0.3692 | ce=0.3296 | ent=0.0000 | center=0.3959 | val_loss=0.1050 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9880 | val_dqn_proxy_expanded5=0.9606

Epoch 020 | train_loss=0.3659 | ce=0.3281 | ent=0.0000 | center=0.3780 | val_loss=0.0845 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9872 | val_dqn_proxy_expanded5=0.9398

Epoch 021 | train_loss=0.3675 | ce=0.3307 | ent=0.0000 | center=0.3683 | val_loss=0.1005 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9793 | val_dqn_proxy_expanded5=0.9334

Epoch 022 | train_loss=0.3677 | ce=0.3323 | ent=0.0000 | center=0.3537 | val_loss=0.0900 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9757 | val_dqn_proxy_expanded5=0.9290

Epoch 023 | train_loss=0.3530 | ce=0.3192 | ent=0.0000 | center=0.3376 | val_loss=0.0656 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9877 | val_dqn_proxy_expanded5=0.9600

Epoch 024 | train_loss=0.3638 | ce=0.3306 | ent=0.0000 | center=0.3321 | val_loss=0.0849 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9937 | val_dqn_proxy_expanded5=0.9555

Epoch 025 | train_loss=0.3555 | ce=0.3235 | ent=0.0000 | center=0.3203 | val_loss=0.0800 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9852 | val_dqn_proxy_expanded5=0.9429

Epoch 026 | train_loss=0.3620 | ce=0.3305 | ent=0.0000 | center=0.3148 | val_loss=0.1157 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.9505 | val_dqn_proxy_expanded5=0.9494

Epoch 027 | train_loss=0.3539 | ce=0.3236 | ent=0.0000 | center=0.3029 | val_loss=0.0920 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9895 | val_dqn_proxy_expanded5=0.9339

Epoch 028 | train_loss=0.3476 | ce=0.3183 | ent=0.0000 | center=0.2936 | val_loss=0.0826 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9855 | val_dqn_proxy_expanded5=0.9405

Epoch 029 | train_loss=0.3488 | ce=0.3205 | ent=0.0000 | center=0.2822 | val_loss=0.1012 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9906 | val_dqn_proxy_expanded5=0.9467

Epoch 030 | train_loss=0.3461 | ce=0.3186 | ent=0.0000 | center=0.2742 | val_loss=0.0776 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9834 | val_dqn_proxy_expanded5=0.9262

Epoch 031 | train_loss=0.3543 | ce=0.3274 | ent=0.0000 | center=0.2693 | val_loss=0.0905 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9879 | val_dqn_proxy_expanded5=0.9526

Epoch 032 | train_loss=0.3426 | ce=0.3165 | ent=0.0000 | center=0.2606 | val_loss=0.0872 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9898 | val_dqn_proxy_expanded5=0.9447

Epoch 033 | train_loss=0.3450 | ce=0.3197 | ent=0.0000 | center=0.2537 | val_loss=0.1307 | val_acc=0.9667 | val_macro_f1=0.9666 | val_dqn_proxy_softmax3=0.9748 | val_dqn_proxy_expanded5=0.9407

Epoch 034 | train_loss=0.3530 | ce=0.3278 | ent=0.0000 | center=0.2522 | val_loss=0.0905 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9877 | val_dqn_proxy_expanded5=0.9391

Epoch 035 | train_loss=0.3456 | ce=0.3212 | ent=0.0000 | center=0.2435 | val_loss=0.0877 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9414 | val_dqn_proxy_expanded5=0.9024

Epoch 036 | train_loss=0.3391 | ce=0.3155 | ent=0.0000 | center=0.2358 | val_loss=0.0816 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9947 | val_dqn_proxy_expanded5=0.9484

Epoch 037 | train_loss=0.3491 | ce=0.3257 | ent=0.0000 | center=0.2347 | val_loss=0.0894 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9086 | val_dqn_proxy_expanded5=0.9095

Epoch 038 | train_loss=0.3412 | ce=0.3184 | ent=0.0000 | center=0.2280 | val_loss=0.0791 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9443 | val_dqn_proxy_expanded5=0.9326

Epoch 039 | train_loss=0.3334 | ce=0.3116 | ent=0.0000 | center=0.2184 | val_loss=0.0933 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9684 | val_dqn_proxy_expanded5=0.9578

Epoch 040 | train_loss=0.3473 | ce=0.3257 | ent=0.0000 | center=0.2156 | val_loss=0.0842 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9746 | val_dqn_proxy_expanded5=0.9521

Epoch 041 | train_loss=0.3421 | ce=0.3210 | ent=0.0000 | center=0.2117 | val_loss=0.1019 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9883 | val_dqn_proxy_expanded5=0.9590

Epoch 042 | train_loss=0.3389 | ce=0.3185 | ent=0.0000 | center=0.2037 | val_loss=0.0933 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9283 | val_dqn_proxy_expanded5=0.9392

Epoch 043 | train_loss=0.3451 | ce=0.3248 | ent=0.0000 | center=0.2027 | val_loss=0.0884 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9732 | val_dqn_proxy_expanded5=0.9143

Epoch 044 | train_loss=0.3292 | ce=0.3101 | ent=0.0000 | center=0.1914 | val_loss=0.0890 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9903 | val_dqn_proxy_expanded5=0.9336

Epoch 045 | train_loss=0.3331 | ce=0.3142 | ent=0.0000 | center=0.1890 | val_loss=0.0808 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9744 | val_dqn_proxy_expanded5=0.9487

Epoch 046 | train_loss=0.3390 | ce=0.3202 | ent=0.0000 | center=0.1875 | val_loss=0.0839 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9851 | val_dqn_proxy_expanded5=0.9450

Epoch 047 | train_loss=0.3337 | ce=0.3154 | ent=0.0000 | center=0.1827 | val_loss=0.0996 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9761 | val_dqn_proxy_expanded5=0.9220

Epoch 048 | train_loss=0.3350 | ce=0.3170 | ent=0.0000 | center=0.1808 | val_loss=0.0920 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9565 | val_dqn_proxy_expanded5=0.9468

Epoch 049 | train_loss=0.3340 | ce=0.3165 | ent=0.0000 | center=0.1755 | val_loss=0.0901 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9821 | val_dqn_proxy_expanded5=0.9571

Epoch 050 | train_loss=0.3266 | ce=0.3096 | ent=0.0000 | center=0.1698 | val_loss=0.0910 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9830 | val_dqn_proxy_expanded5=0.9620

Epoch 051 | train_loss=0.3279 | ce=0.3111 | ent=0.0000 | center=0.1683 | val_loss=0.0828 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9913 | val_dqn_proxy_expanded5=0.9595
Early stopping at epoch 51 (best epoch: 36)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
31,ref_base_ent005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-43_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
23,ref_base_drop050_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-25_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
11,ref_base_ls002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
33,ref_base_ent010_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-46_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
15,ref_base_ls000_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-04_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,ref_base_ls000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-59_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
8,ref_base_ls002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-47_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,ref_base_ls000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-56_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
17,ref_base_drop040_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-07_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
29,ref_base_ent005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,ref_base_ls002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-49_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
37,ref_base_lr2e4_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-00_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
25,ref_base_ent002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-28_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
24,ref_base_ent002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-26_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
19,ref_base_drop040_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-11_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
32,ref_base_ent010_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-45_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
5,ref_base_ls005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,ref_base_ls005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-45_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
27,ref_base_ent002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,ref_base_ls005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-42_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,ref_base_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
35,ref_base_ent010_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
21,ref_base_drop050_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-18_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
20,ref_base_drop050_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-14_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
28,ref_base_ent005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-35_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,ref_base_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-29_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
22,ref_base_drop050_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-21_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
34,ref_base_ent010_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-52_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
36,ref_base_lr2e4_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-57_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,ref_base_ls005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-36_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
26,ref_base_ent002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-31_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
18,ref_base_drop040_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-09_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
30,ref_base_ent005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-41_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
16,ref_base_drop040_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-06_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
10,ref_base_ls002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-53_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
14,ref_base_ls000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-02_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"

================================================================================
Running experiment 39/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "cosine",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": null,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_base_lr2e4",
  "lr": 0.0002,
  "label_smoothing": 0.1,
  "entropy_loss_weight": 0.0,
  "mlp_dropout": 0.3,
  "unknown_pas": [
    "PA4"
  ],
  "run_name": "ref_base_lr2e4_unkPA4_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.7928 | ce=0.6735 | ent=0.0000 | center=1.1934 | val_loss=0.2734 | val_acc=0.9259 | val_macro_f1=0.9250 | val_dqn_proxy_softmax3=0.7287 | val_dqn_proxy_expanded5=0.7349

Epoch 002 | train_loss=0.6164 | ce=0.5078 | ent=0.0000 | center=1.0863 | val_loss=0.3643 | val_acc=0.8963 | val_macro_f1=0.8961 | val_dqn_proxy_softmax3=0.7038 | val_dqn_proxy_expanded5=0.6954

Epoch 003 | train_loss=0.5212 | ce=0.4249 | ent=0.0000 | center=0.9635 | val_loss=0.2284 | val_acc=0.9259 | val_macro_f1=0.9255 | val_dqn_proxy_softmax3=0.7486 | val_dqn_proxy_expanded5=0.6907

Epoch 004 | train_loss=0.4884 | ce=0.4006 | ent=0.0000 | center=0.8781 | val_loss=0.1807 | val_acc=0.9556 | val_macro_f1=0.9555 | val_dqn_proxy_softmax3=0.8493 | val_dqn_proxy_expanded5=0.7899

Epoch 005 | train_loss=0.4879 | ce=0.4061 | ent=0.0000 | center=0.8178 | val_loss=0.1369 | val_acc=0.9778 | val_macro_f1=0.9779 | val_dqn_proxy_softmax3=0.9257 | val_dqn_proxy_expanded5=0.8655

Epoch 006 | train_loss=0.4505 | ce=0.3728 | ent=0.0000 | center=0.7765 | val_loss=0.2219 | val_acc=0.9259 | val_macro_f1=0.9253 | val_dqn_proxy_softmax3=0.9178 | val_dqn_proxy_expanded5=0.8776

Epoch 007 | train_loss=0.4494 | ce=0.3768 | ent=0.0000 | center=0.7262 | val_loss=0.1589 | val_acc=0.9630 | val_macro_f1=0.9628 | val_dqn_proxy_softmax3=0.8975 | val_dqn_proxy_expanded5=0.8194

Epoch 008 | train_loss=0.4235 | ce=0.3542 | ent=0.0000 | center=0.6929 | val_loss=0.1477 | val_acc=0.9667 | val_macro_f1=0.9666 | val_dqn_proxy_softmax3=0.7997 | val_dqn_proxy_expanded5=0.7554

Epoch 009 | train_loss=0.4296 | ce=0.3636 | ent=0.0000 | center=0.6594 | val_loss=0.1856 | val_acc=0.9667 | val_macro_f1=0.9666 | val_dqn_proxy_softmax3=0.8047 | val_dqn_proxy_expanded5=0.7394

Epoch 010 | train_loss=0.4158 | ce=0.3524 | ent=0.0000 | center=0.6343 | val_loss=0.0996 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.7804 | val_dqn_proxy_expanded5=0.7501

Epoch 011 | train_loss=0.3979 | ce=0.3379 | ent=0.0000 | center=0.5992 | val_loss=0.1347 | val_acc=0.9704 | val_macro_f1=0.9703 | val_dqn_proxy_softmax3=0.7585 | val_dqn_proxy_expanded5=0.7293

Epoch 012 | train_loss=0.3995 | ce=0.3419 | ent=0.0000 | center=0.5756 | val_loss=0.1240 | val_acc=0.9741 | val_macro_f1=0.9740 | val_dqn_proxy_softmax3=0.7572 | val_dqn_proxy_expanded5=0.7293

Epoch 013 | train_loss=0.3883 | ce=0.3334 | ent=0.0000 | center=0.5498 | val_loss=0.0950 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.7827 | val_dqn_proxy_expanded5=0.7832

Epoch 014 | train_loss=0.3807 | ce=0.3281 | ent=0.0000 | center=0.5262 | val_loss=0.0832 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.8613 | val_dqn_proxy_expanded5=0.8308

Epoch 015 | train_loss=0.3869 | ce=0.3356 | ent=0.0000 | center=0.5130 | val_loss=0.1039 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.7891 | val_dqn_proxy_expanded5=0.7899

Epoch 016 | train_loss=0.3768 | ce=0.3276 | ent=0.0000 | center=0.4928 | val_loss=0.1073 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.7708 | val_dqn_proxy_expanded5=0.7418

Epoch 017 | train_loss=0.3761 | ce=0.3291 | ent=0.0000 | center=0.4705 | val_loss=0.1173 | val_acc=0.9704 | val_macro_f1=0.9703 | val_dqn_proxy_softmax3=0.7676 | val_dqn_proxy_expanded5=0.7380

Epoch 018 | train_loss=0.3707 | ce=0.3251 | ent=0.0000 | center=0.4561 | val_loss=0.0950 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.8068 | val_dqn_proxy_expanded5=0.8004

Epoch 019 | train_loss=0.3761 | ce=0.3316 | ent=0.0000 | center=0.4449 | val_loss=0.1151 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9568 | val_dqn_proxy_expanded5=0.9198

Epoch 020 | train_loss=0.3708 | ce=0.3279 | ent=0.0000 | center=0.4287 | val_loss=0.0916 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9749 | val_dqn_proxy_expanded5=0.9317

Epoch 021 | train_loss=0.3592 | ce=0.3177 | ent=0.0000 | center=0.4149 | val_loss=0.0879 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.7767 | val_dqn_proxy_expanded5=0.7202

Epoch 022 | train_loss=0.3647 | ce=0.3242 | ent=0.0000 | center=0.4046 | val_loss=0.0827 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9250 | val_dqn_proxy_expanded5=0.8818

Epoch 023 | train_loss=0.3551 | ce=0.3162 | ent=0.0000 | center=0.3893 | val_loss=0.1065 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.8005 | val_dqn_proxy_expanded5=0.7954

Epoch 024 | train_loss=0.3531 | ce=0.3154 | ent=0.0000 | center=0.3766 | val_loss=0.0837 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9068 | val_dqn_proxy_expanded5=0.8696

Epoch 025 | train_loss=0.3610 | ce=0.3242 | ent=0.0000 | center=0.3682 | val_loss=0.1003 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7796 | val_dqn_proxy_expanded5=0.7491

Epoch 026 | train_loss=0.3556 | ce=0.3196 | ent=0.0000 | center=0.3602 | val_loss=0.1067 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.7658 | val_dqn_proxy_expanded5=0.7383

Epoch 027 | train_loss=0.3503 | ce=0.3151 | ent=0.0000 | center=0.3515 | val_loss=0.0988 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.7755 | val_dqn_proxy_expanded5=0.7191

Epoch 028 | train_loss=0.3497 | ce=0.3157 | ent=0.0000 | center=0.3402 | val_loss=0.0891 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7845 | val_dqn_proxy_expanded5=0.7529

Epoch 029 | train_loss=0.3503 | ce=0.3173 | ent=0.0000 | center=0.3303 | val_loss=0.0959 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7918 | val_dqn_proxy_expanded5=0.7599

Epoch 030 | train_loss=0.3615 | ce=0.3287 | ent=0.0000 | center=0.3285 | val_loss=0.1208 | val_acc=0.9704 | val_macro_f1=0.9703 | val_dqn_proxy_softmax3=0.7573 | val_dqn_proxy_expanded5=0.6995

Epoch 031 | train_loss=0.3520 | ce=0.3199 | ent=0.0000 | center=0.3209 | val_loss=0.0764 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.7927 | val_dqn_proxy_expanded5=0.7597

Epoch 032 | train_loss=0.3467 | ce=0.3158 | ent=0.0000 | center=0.3083 | val_loss=0.0760 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9398 | val_dqn_proxy_expanded5=0.8538

Epoch 033 | train_loss=0.3488 | ce=0.3188 | ent=0.0000 | center=0.3000 | val_loss=0.1081 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.7599 | val_dqn_proxy_expanded5=0.7094

Epoch 034 | train_loss=0.3460 | ce=0.3167 | ent=0.0000 | center=0.2929 | val_loss=0.0830 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.7768 | val_dqn_proxy_expanded5=0.7500

Epoch 035 | train_loss=0.3378 | ce=0.3096 | ent=0.0000 | center=0.2826 | val_loss=0.0824 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.8911 | val_dqn_proxy_expanded5=0.8231
Early stopping at epoch 35 (best epoch: 20)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
31,ref_base_ent005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-43_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
23,ref_base_drop050_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-25_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
11,ref_base_ls002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
33,ref_base_ent010_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-46_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
15,ref_base_ls000_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-04_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,ref_base_ls000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-59_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
8,ref_base_ls002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-47_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,ref_base_ls000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-56_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
17,ref_base_drop040_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-07_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
29,ref_base_ent005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,ref_base_ls002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-49_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
37,ref_base_lr2e4_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-00_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
25,ref_base_ent002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-28_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
24,ref_base_ent002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-26_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
19,ref_base_drop040_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-11_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
32,ref_base_ent010_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-45_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
5,ref_base_ls005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,ref_base_ls005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-45_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
27,ref_base_ent002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
38,ref_base_lr2e4_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-04_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,ref_base_ls005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-42_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,ref_base_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
35,ref_base_ent010_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
21,ref_base_drop050_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-18_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
20,ref_base_drop050_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-14_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
28,ref_base_ent005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-35_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,ref_base_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-29_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
22,ref_base_drop050_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-21_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
34,ref_base_ent010_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-52_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
36,ref_base_lr2e4_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-57_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,ref_base_ls005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-36_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
26,ref_base_ent002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-31_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
18,ref_base_drop040_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-09_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
30,ref_base_ent005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-41_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
16,ref_base_drop040_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-06_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
10,ref_base_ls002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-53_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
14,ref_base_ls000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-02_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"

================================================================================
Running experiment 40/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "cosine",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": null,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_base_lr2e4",
  "lr": 0.0002,
  "label_smoothing": 0.1,
  "entropy_loss_weight": 0.0,
  "mlp_dropout": 0.3,
  "unknown_pas": [
    "PA8"
  ],
  "run_name": "ref_base_lr2e4_unkPA8_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.6478 | ce=0.5400 | ent=0.0000 | center=1.0784 | val_loss=0.1647 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9563 | val_dqn_proxy_expanded5=0.9360

Epoch 002 | train_loss=0.4509 | ce=0.3609 | ent=0.0000 | center=0.8998 | val_loss=0.1363 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8857 | val_dqn_proxy_expanded5=0.8509

Epoch 003 | train_loss=0.4226 | ce=0.3423 | ent=0.0000 | center=0.8029 | val_loss=0.1339 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9362 | val_dqn_proxy_expanded5=0.9072

Epoch 004 | train_loss=0.4085 | ce=0.3351 | ent=0.0000 | center=0.7345 | val_loss=0.1356 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9739 | val_dqn_proxy_expanded5=0.9402

Epoch 005 | train_loss=0.4017 | ce=0.3336 | ent=0.0000 | center=0.6813 | val_loss=0.1406 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9447 | val_dqn_proxy_expanded5=0.8977

Epoch 006 | train_loss=0.3928 | ce=0.3290 | ent=0.0000 | center=0.6379 | val_loss=0.1251 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9171 | val_dqn_proxy_expanded5=0.8712

Epoch 007 | train_loss=0.3862 | ce=0.3261 | ent=0.0000 | center=0.6009 | val_loss=0.1174 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9706 | val_dqn_proxy_expanded5=0.9278

Epoch 008 | train_loss=0.3802 | ce=0.3233 | ent=0.0000 | center=0.5690 | val_loss=0.1096 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9520 | val_dqn_proxy_expanded5=0.9029

Epoch 009 | train_loss=0.3720 | ce=0.3179 | ent=0.0000 | center=0.5413 | val_loss=0.1023 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9539 | val_dqn_proxy_expanded5=0.9097

Epoch 010 | train_loss=0.3652 | ce=0.3142 | ent=0.0000 | center=0.5101 | val_loss=0.1033 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9721 | val_dqn_proxy_expanded5=0.9186

Epoch 011 | train_loss=0.3604 | ce=0.3122 | ent=0.0000 | center=0.4820 | val_loss=0.1092 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9466 | val_dqn_proxy_expanded5=0.8745

Epoch 012 | train_loss=0.3557 | ce=0.3102 | ent=0.0000 | center=0.4551 | val_loss=0.1043 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9258 | val_dqn_proxy_expanded5=0.8680

Epoch 013 | train_loss=0.3532 | ce=0.3102 | ent=0.0000 | center=0.4302 | val_loss=0.0876 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9057 | val_dqn_proxy_expanded5=0.8507

Epoch 014 | train_loss=0.3476 | ce=0.3071 | ent=0.0000 | center=0.4055 | val_loss=0.0965 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9654 | val_dqn_proxy_expanded5=0.9102

Epoch 015 | train_loss=0.3459 | ce=0.3075 | ent=0.0000 | center=0.3837 | val_loss=0.1065 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9654 | val_dqn_proxy_expanded5=0.9042

Epoch 016 | train_loss=0.3467 | ce=0.3100 | ent=0.0000 | center=0.3676 | val_loss=0.0897 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9639 | val_dqn_proxy_expanded5=0.8926

Epoch 017 | train_loss=0.3463 | ce=0.3105 | ent=0.0000 | center=0.3579 | val_loss=0.0884 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8903 | val_dqn_proxy_expanded5=0.8392

Epoch 018 | train_loss=0.3393 | ce=0.3061 | ent=0.0000 | center=0.3322 | val_loss=0.0865 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8952 | val_dqn_proxy_expanded5=0.8383

Epoch 019 | train_loss=0.3377 | ce=0.3058 | ent=0.0000 | center=0.3194 | val_loss=0.0946 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9421 | val_dqn_proxy_expanded5=0.8902
Early stopping at epoch 19 (best epoch: 4)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
31,ref_base_ent005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-43_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
23,ref_base_drop050_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-25_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
11,ref_base_ls002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
33,ref_base_ent010_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-46_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
15,ref_base_ls000_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-04_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,ref_base_ls000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-59_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
39,ref_base_lr2e4_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-07_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
8,ref_base_ls002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-47_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,ref_base_ls000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-56_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
17,ref_base_drop040_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-07_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
29,ref_base_ent005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,ref_base_ls002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-49_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
37,ref_base_lr2e4_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-00_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
25,ref_base_ent002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-28_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
24,ref_base_ent002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-26_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
19,ref_base_drop040_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-11_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
32,ref_base_ent010_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-45_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
5,ref_base_ls005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,ref_base_ls005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-45_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
27,ref_base_ent002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
38,ref_base_lr2e4_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-04_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,ref_base_ls005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-42_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,ref_base_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
35,ref_base_ent010_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
21,ref_base_drop050_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-18_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
20,ref_base_drop050_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-14_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
28,ref_base_ent005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-35_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,ref_base_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-29_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
22,ref_base_drop050_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-21_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
34,ref_base_ent010_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-52_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
36,ref_base_lr2e4_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-57_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,ref_base_ls005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-36_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
26,ref_base_ent002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-31_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
18,ref_base_drop040_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-09_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
30,ref_base_ent005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-41_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
16,ref_base_drop040_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-06_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
10,ref_base_ls002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-53_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
14,ref_base_ls000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-02_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"

================================================================================
Running experiment 41/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "plateau",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0001,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": 1.0,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_pms_ctrl",
  "lr": 0.0001,
  "label_smoothing": 0.05,
  "entropy_loss_weight": 0.05,
  "mlp_dropout": 0.5,
  "unknown_pas": [
    "PA2"
  ],
  "run_name": "ref_pms_ctrl_unkPA2_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.9989 | ce=0.8422 | ent=0.9787 | center=1.0773 | val_loss=0.3509 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7943 | val_dqn_proxy_expanded5=0.7777

Epoch 002 | train_loss=0.5128 | ce=0.3514 | ent=0.4512 | center=1.3880 | val_loss=0.1506 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8324 | val_dqn_proxy_expanded5=0.8547

Epoch 003 | train_loss=0.4252 | ce=0.2840 | ent=0.3246 | center=1.2493 | val_loss=0.1218 | val_acc=0.9778 | val_macro_f1=0.9779 | val_dqn_proxy_softmax3=0.6718 | val_dqn_proxy_expanded5=0.7385

Epoch 004 | train_loss=0.4053 | ce=0.2736 | ent=0.2916 | center=1.1715 | val_loss=0.1099 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6667 | val_dqn_proxy_expanded5=0.7371

Epoch 005 | train_loss=0.3841 | ce=0.2603 | ent=0.2684 | center=1.1047 | val_loss=0.1058 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6666 | val_dqn_proxy_expanded5=0.7375

Epoch 006 | train_loss=0.3781 | ce=0.2604 | ent=0.2726 | center=1.0410 | val_loss=0.1048 | val_acc=0.9778 | val_macro_f1=0.9779 | val_dqn_proxy_softmax3=0.6594 | val_dqn_proxy_expanded5=0.6960

Epoch 007 | train_loss=0.3593 | ce=0.2461 | ent=0.2438 | center=1.0106 | val_loss=0.0909 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6736 | val_dqn_proxy_expanded5=0.7084

Epoch 008 | train_loss=0.3526 | ce=0.2432 | ent=0.2430 | center=0.9726 | val_loss=0.0923 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8374 | val_dqn_proxy_expanded5=0.8331

Epoch 009 | train_loss=0.3423 | ce=0.2361 | ent=0.2355 | center=0.9445 | val_loss=0.0914 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6658 | val_dqn_proxy_expanded5=0.7205

Epoch 010 | train_loss=0.3373 | ce=0.2347 | ent=0.2366 | center=0.9079 | val_loss=0.0882 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6244 | val_dqn_proxy_expanded5=0.6949

Epoch 011 | train_loss=0.3363 | ce=0.2361 | ent=0.2237 | center=0.8896 | val_loss=0.0905 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6802 | val_dqn_proxy_expanded5=0.6946

Epoch 012 | train_loss=0.3238 | ce=0.2267 | ent=0.2250 | center=0.8584 | val_loss=0.0817 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7443 | val_dqn_proxy_expanded5=0.7285

Epoch 013 | train_loss=0.3235 | ce=0.2285 | ent=0.2210 | center=0.8399 | val_loss=0.0849 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7287 | val_dqn_proxy_expanded5=0.7259

Epoch 014 | train_loss=0.3261 | ce=0.2334 | ent=0.2179 | center=0.8184 | val_loss=0.0785 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7523 | val_dqn_proxy_expanded5=0.7349

Epoch 015 | train_loss=0.3243 | ce=0.2332 | ent=0.2213 | center=0.8003 | val_loss=0.0783 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8306 | val_dqn_proxy_expanded5=0.8210

Epoch 016 | train_loss=0.3134 | ce=0.2243 | ent=0.2140 | center=0.7835 | val_loss=0.0725 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8103 | val_dqn_proxy_expanded5=0.7952

Epoch 017 | train_loss=0.3081 | ce=0.2206 | ent=0.2103 | center=0.7697 | val_loss=0.0667 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6613 | val_dqn_proxy_expanded5=0.7171

Epoch 018 | train_loss=0.2929 | ce=0.2077 | ent=0.2091 | center=0.7467 | val_loss=0.0606 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8527 | val_dqn_proxy_expanded5=0.8519

Epoch 019 | train_loss=0.2985 | ce=0.2142 | ent=0.2093 | center=0.7380 | val_loss=0.0626 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6099 | val_dqn_proxy_expanded5=0.6870

Epoch 020 | train_loss=0.2828 | ce=0.2009 | ent=0.1919 | center=0.7237 | val_loss=0.0601 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7253 | val_dqn_proxy_expanded5=0.7342

Epoch 021 | train_loss=0.2837 | ce=0.2034 | ent=0.1922 | center=0.7063 | val_loss=0.0627 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6657 | val_dqn_proxy_expanded5=0.6812

Epoch 022 | train_loss=0.2819 | ce=0.2030 | ent=0.1930 | center=0.6922 | val_loss=0.0512 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8255 | val_dqn_proxy_expanded5=0.8292

Epoch 023 | train_loss=0.2755 | ce=0.1987 | ent=0.1860 | center=0.6755 | val_loss=0.0551 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7108 | val_dqn_proxy_expanded5=0.7116

Epoch 024 | train_loss=0.2756 | ce=0.2001 | ent=0.1831 | center=0.6638 | val_loss=0.0520 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6259 | val_dqn_proxy_expanded5=0.6897

Epoch 025 | train_loss=0.2738 | ce=0.1999 | ent=0.1817 | center=0.6477 | val_loss=0.0581 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6324 | val_dqn_proxy_expanded5=0.7001

Epoch 026 | train_loss=0.2731 | ce=0.2004 | ent=0.1860 | center=0.6344 | val_loss=0.0512 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7014 | val_dqn_proxy_expanded5=0.7040

Epoch 027 | train_loss=0.2774 | ce=0.2052 | ent=0.1924 | center=0.6257 | val_loss=0.0510 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7979 | val_dqn_proxy_expanded5=0.8030

Epoch 028 | train_loss=0.2712 | ce=0.2008 | ent=0.1827 | center=0.6122 | val_loss=0.0562 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6478 | val_dqn_proxy_expanded5=0.6550

Epoch 029 | train_loss=0.2700 | ce=0.2005 | ent=0.1851 | center=0.6030 | val_loss=0.0555 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7324 | val_dqn_proxy_expanded5=0.7254

Epoch 030 | train_loss=0.2668 | ce=0.1986 | ent=0.1841 | center=0.5901 | val_loss=0.0532 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7826 | val_dqn_proxy_expanded5=0.7710

Epoch 031 | train_loss=0.2637 | ce=0.1970 | ent=0.1787 | center=0.5778 | val_loss=0.0561 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8028 | val_dqn_proxy_expanded5=0.7879

Epoch 032 | train_loss=0.2673 | ce=0.2016 | ent=0.1778 | center=0.5685 | val_loss=0.0608 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6509 | val_dqn_proxy_expanded5=0.7436

Epoch 033 | train_loss=0.2661 | ce=0.2014 | ent=0.1809 | center=0.5567 | val_loss=0.0565 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8671 | val_dqn_proxy_expanded5=0.8539

Epoch 034 | train_loss=0.2660 | ce=0.2021 | ent=0.1748 | center=0.5513 | val_loss=0.0531 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7263 | val_dqn_proxy_expanded5=0.7285

Epoch 035 | train_loss=0.2592 | ce=0.1960 | ent=0.1794 | center=0.5416 | val_loss=0.0567 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8089 | val_dqn_proxy_expanded5=0.7952

Epoch 036 | train_loss=0.2590 | ce=0.1965 | ent=0.1775 | center=0.5362 | val_loss=0.0572 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6745 | val_dqn_proxy_expanded5=0.6880

Epoch 037 | train_loss=0.2603 | ce=0.1984 | ent=0.1759 | center=0.5311 | val_loss=0.0544 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7594 | val_dqn_proxy_expanded5=0.7412

Epoch 038 | train_loss=0.2576 | ce=0.1962 | ent=0.1767 | center=0.5254 | val_loss=0.0573 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7828 | val_dqn_proxy_expanded5=0.7704

Epoch 039 | train_loss=0.2570 | ce=0.1961 | ent=0.1809 | center=0.5185 | val_loss=0.0508 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6630 | val_dqn_proxy_expanded5=0.6811

Epoch 040 | train_loss=0.2563 | ce=0.1961 | ent=0.1736 | center=0.5152 | val_loss=0.0526 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6588 | val_dqn_proxy_expanded5=0.6781

Epoch 041 | train_loss=0.2551 | ce=0.1952 | ent=0.1778 | center=0.5098 | val_loss=0.0528 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7164 | val_dqn_proxy_expanded5=0.7148

Epoch 042 | train_loss=0.2589 | ce=0.1997 | ent=0.1755 | center=0.5046 | val_loss=0.0544 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7297 | val_dqn_proxy_expanded5=0.7233

Epoch 043 | train_loss=0.2567 | ce=0.1979 | ent=0.1768 | center=0.4991 | val_loss=0.0560 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6468 | val_dqn_proxy_expanded5=0.6645

Epoch 044 | train_loss=0.2540 | ce=0.1959 | ent=0.1749 | center=0.4934 | val_loss=0.0535 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7920 | val_dqn_proxy_expanded5=0.7813

Epoch 045 | train_loss=0.2527 | ce=0.1953 | ent=0.1703 | center=0.4893 | val_loss=0.0563 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7779 | val_dqn_proxy_expanded5=0.7588

Epoch 046 | train_loss=0.2514 | ce=0.1940 | ent=0.1785 | center=0.4849 | val_loss=0.0538 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7756 | val_dqn_proxy_expanded5=0.7720

Epoch 047 | train_loss=0.2547 | ce=0.1977 | ent=0.1755 | center=0.4818 | val_loss=0.0549 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8041 | val_dqn_proxy_expanded5=0.7905

Epoch 048 | train_loss=0.2514 | ce=0.1950 | ent=0.1695 | center=0.4792 | val_loss=0.0551 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6460 | val_dqn_proxy_expanded5=0.7109
Early stopping at epoch 48 (best epoch: 33)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
31,ref_base_ent005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-43_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
23,ref_base_drop050_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-25_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
11,ref_base_ls002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
33,ref_base_ent010_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-46_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
15,ref_base_ls000_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-04_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,ref_base_ls000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-59_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
39,ref_base_lr2e4_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-07_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
8,ref_base_ls002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-47_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,ref_base_ls000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-56_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
17,ref_base_drop040_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-07_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
29,ref_base_ent005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,ref_base_ls002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-49_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
37,ref_base_lr2e4_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-00_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
25,ref_base_ent002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-28_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
24,ref_base_ent002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-26_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
19,ref_base_drop040_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-11_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
32,ref_base_ent010_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-45_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
5,ref_base_ls005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,ref_base_ls005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-45_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
27,ref_base_ent002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
38,ref_base_lr2e4_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-04_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,ref_base_ls005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-42_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,ref_base_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
35,ref_base_ent010_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
21,ref_base_drop050_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-18_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
20,ref_base_drop050_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-14_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
28,ref_base_ent005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-35_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,ref_base_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-29_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
22,ref_base_drop050_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-21_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
34,ref_base_ent010_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-52_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
36,ref_base_lr2e4_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-57_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,ref_base_ls005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-36_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
26,ref_base_ent002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-31_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
40,ref_pms_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/23-08_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
18,ref_base_drop040_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-09_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
30,ref_base_ent005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-41_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
16,ref_base_drop040_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-06_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
10,ref_base_ls002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-53_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
14,ref_base_ls000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-02_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"

================================================================================
Running experiment 42/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "plateau",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0001,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": 1.0,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_pms_ctrl",
  "lr": 0.0001,
  "label_smoothing": 0.05,
  "entropy_loss_weight": 0.05,
  "mlp_dropout": 0.5,
  "unknown_pas": [
    "PA3"
  ],
  "run_name": "ref_pms_ctrl_unkPA3_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=1.0502 | ce=0.8860 | ent=1.0043 | center=1.1391 | val_loss=0.4782 | val_acc=0.8407 | val_macro_f1=0.8293 | val_dqn_proxy_softmax3=0.6916 | val_dqn_proxy_expanded5=0.7165

Epoch 002 | train_loss=0.6367 | ce=0.4685 | ent=0.5602 | center=1.4020 | val_loss=0.2410 | val_acc=0.9185 | val_macro_f1=0.9183 | val_dqn_proxy_softmax3=0.7376 | val_dqn_proxy_expanded5=0.7274

Epoch 003 | train_loss=0.5026 | ce=0.3466 | ent=0.3942 | center=1.3622 | val_loss=0.1688 | val_acc=0.9444 | val_macro_f1=0.9447 | val_dqn_proxy_softmax3=0.8823 | val_dqn_proxy_expanded5=0.8246

Epoch 004 | train_loss=0.4660 | ce=0.3226 | ent=0.3552 | center=1.2565 | val_loss=0.1487 | val_acc=0.9481 | val_macro_f1=0.9484 | val_dqn_proxy_softmax3=0.8137 | val_dqn_proxy_expanded5=0.7972

Epoch 005 | train_loss=0.4509 | ce=0.3157 | ent=0.3266 | center=1.1888 | val_loss=0.1095 | val_acc=0.9741 | val_macro_f1=0.9742 | val_dqn_proxy_softmax3=0.7210 | val_dqn_proxy_expanded5=0.7702

Epoch 006 | train_loss=0.4405 | ce=0.3111 | ent=0.3157 | center=1.1360 | val_loss=0.1268 | val_acc=0.9593 | val_macro_f1=0.9595 | val_dqn_proxy_softmax3=0.6579 | val_dqn_proxy_expanded5=0.7545

Epoch 007 | train_loss=0.4193 | ce=0.2955 | ent=0.2960 | center=1.0907 | val_loss=0.1170 | val_acc=0.9704 | val_macro_f1=0.9706 | val_dqn_proxy_softmax3=0.7053 | val_dqn_proxy_expanded5=0.7631

Epoch 008 | train_loss=0.3965 | ce=0.2770 | ent=0.2877 | center=1.0519 | val_loss=0.1019 | val_acc=0.9667 | val_macro_f1=0.9669 | val_dqn_proxy_softmax3=0.9605 | val_dqn_proxy_expanded5=0.9304

Epoch 009 | train_loss=0.3902 | ce=0.2731 | ent=0.2739 | center=1.0335 | val_loss=0.1327 | val_acc=0.9704 | val_macro_f1=0.9703 | val_dqn_proxy_softmax3=0.9507 | val_dqn_proxy_expanded5=0.9019

Epoch 010 | train_loss=0.3790 | ce=0.2655 | ent=0.2778 | center=0.9964 | val_loss=0.1004 | val_acc=0.9704 | val_macro_f1=0.9706 | val_dqn_proxy_softmax3=0.9702 | val_dqn_proxy_expanded5=0.9292

Epoch 011 | train_loss=0.3639 | ce=0.2536 | ent=0.2535 | center=0.9763 | val_loss=0.0747 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.9592 | val_dqn_proxy_expanded5=0.9264

Epoch 012 | train_loss=0.3726 | ce=0.2652 | ent=0.2621 | center=0.9432 | val_loss=0.0794 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.9643 | val_dqn_proxy_expanded5=0.9497

Epoch 013 | train_loss=0.3511 | ce=0.2471 | ent=0.2525 | center=0.9139 | val_loss=0.0751 | val_acc=0.9741 | val_macro_f1=0.9742 | val_dqn_proxy_softmax3=0.9531 | val_dqn_proxy_expanded5=0.9226

Epoch 014 | train_loss=0.3433 | ce=0.2411 | ent=0.2480 | center=0.8973 | val_loss=0.0897 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.9802 | val_dqn_proxy_expanded5=0.9555

Epoch 015 | train_loss=0.3322 | ce=0.2330 | ent=0.2347 | center=0.8752 | val_loss=0.0733 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9585 | val_dqn_proxy_expanded5=0.9276

Epoch 016 | train_loss=0.3361 | ce=0.2389 | ent=0.2369 | center=0.8537 | val_loss=0.0673 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9629 | val_dqn_proxy_expanded5=0.9452

Epoch 017 | train_loss=0.3379 | ce=0.2421 | ent=0.2415 | center=0.8381 | val_loss=0.0647 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9853 | val_dqn_proxy_expanded5=0.9615

Epoch 018 | train_loss=0.3324 | ce=0.2388 | ent=0.2384 | center=0.8171 | val_loss=0.0948 | val_acc=0.9741 | val_macro_f1=0.9741 | val_dqn_proxy_softmax3=0.9516 | val_dqn_proxy_expanded5=0.9050

Epoch 019 | train_loss=0.3299 | ce=0.2377 | ent=0.2276 | center=0.8082 | val_loss=0.0736 | val_acc=0.9815 | val_macro_f1=0.9816 | val_dqn_proxy_softmax3=0.9802 | val_dqn_proxy_expanded5=0.9278

Epoch 020 | train_loss=0.3178 | ce=0.2274 | ent=0.2267 | center=0.7905 | val_loss=0.0605 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.7619 | val_dqn_proxy_expanded5=0.7252

Epoch 021 | train_loss=0.3116 | ce=0.2231 | ent=0.2148 | center=0.7774 | val_loss=0.0506 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9775 | val_dqn_proxy_expanded5=0.9459

Epoch 022 | train_loss=0.3048 | ce=0.2190 | ent=0.2225 | center=0.7462 | val_loss=0.0761 | val_acc=0.9741 | val_macro_f1=0.9740 | val_dqn_proxy_softmax3=0.9688 | val_dqn_proxy_expanded5=0.9292

Epoch 023 | train_loss=0.3011 | ce=0.2168 | ent=0.2085 | center=0.7390 | val_loss=0.0451 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9721 | val_dqn_proxy_expanded5=0.9366

Epoch 024 | train_loss=0.2952 | ce=0.2126 | ent=0.2117 | center=0.7196 | val_loss=0.0479 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9496 | val_dqn_proxy_expanded5=0.9104

Epoch 025 | train_loss=0.2900 | ce=0.2091 | ent=0.2025 | center=0.7077 | val_loss=0.0460 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9651 | val_dqn_proxy_expanded5=0.9124

Epoch 026 | train_loss=0.2963 | ce=0.2167 | ent=0.2080 | center=0.6927 | val_loss=0.0498 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9708 | val_dqn_proxy_expanded5=0.9390

Epoch 027 | train_loss=0.2934 | ce=0.2149 | ent=0.1988 | center=0.6849 | val_loss=0.0472 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9696 | val_dqn_proxy_expanded5=0.9262

Epoch 028 | train_loss=0.2939 | ce=0.2168 | ent=0.2093 | center=0.6669 | val_loss=0.0810 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9593 | val_dqn_proxy_expanded5=0.9075

Epoch 029 | train_loss=0.2831 | ce=0.2073 | ent=0.2048 | center=0.6552 | val_loss=0.0571 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9886 | val_dqn_proxy_expanded5=0.9688

Epoch 030 | train_loss=0.2777 | ce=0.2037 | ent=0.1889 | center=0.6460 | val_loss=0.0389 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9880 | val_dqn_proxy_expanded5=0.9537

Epoch 031 | train_loss=0.2813 | ce=0.2082 | ent=0.1882 | center=0.6366 | val_loss=0.0411 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9777 | val_dqn_proxy_expanded5=0.9439

Epoch 032 | train_loss=0.2722 | ce=0.2000 | ent=0.1830 | center=0.6303 | val_loss=0.0371 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9827 | val_dqn_proxy_expanded5=0.9513

Epoch 033 | train_loss=0.2748 | ce=0.2029 | ent=0.1904 | center=0.6231 | val_loss=0.0406 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9887 | val_dqn_proxy_expanded5=0.9626

Epoch 034 | train_loss=0.2760 | ce=0.2050 | ent=0.1861 | center=0.6169 | val_loss=0.0446 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9768 | val_dqn_proxy_expanded5=0.9438

Epoch 035 | train_loss=0.2704 | ce=0.2004 | ent=0.1846 | center=0.6081 | val_loss=0.0519 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9827 | val_dqn_proxy_expanded5=0.9463

Epoch 036 | train_loss=0.2722 | ce=0.2024 | ent=0.1894 | center=0.6031 | val_loss=0.0496 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9882 | val_dqn_proxy_expanded5=0.9608

Epoch 037 | train_loss=0.2814 | ce=0.2119 | ent=0.1898 | center=0.5999 | val_loss=0.0383 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9800 | val_dqn_proxy_expanded5=0.9499

Epoch 038 | train_loss=0.2702 | ce=0.2017 | ent=0.1845 | center=0.5921 | val_loss=0.0367 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9776 | val_dqn_proxy_expanded5=0.9531

Epoch 039 | train_loss=0.2681 | ce=0.2002 | ent=0.1861 | center=0.5855 | val_loss=0.0508 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9775 | val_dqn_proxy_expanded5=0.9454

Epoch 040 | train_loss=0.2701 | ce=0.2028 | ent=0.1898 | center=0.5786 | val_loss=0.0370 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9792 | val_dqn_proxy_expanded5=0.9495

Epoch 041 | train_loss=0.2673 | ce=0.2006 | ent=0.1879 | center=0.5723 | val_loss=0.0525 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9856 | val_dqn_proxy_expanded5=0.9557

Epoch 042 | train_loss=0.2631 | ce=0.1975 | ent=0.1789 | center=0.5667 | val_loss=0.0527 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9806 | val_dqn_proxy_expanded5=0.9520

Epoch 043 | train_loss=0.2722 | ce=0.2069 | ent=0.1815 | center=0.5632 | val_loss=0.0405 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9791 | val_dqn_proxy_expanded5=0.9464

Epoch 044 | train_loss=0.2640 | ce=0.1994 | ent=0.1783 | center=0.5563 | val_loss=0.0413 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9805 | val_dqn_proxy_expanded5=0.9385

Epoch 045 | train_loss=0.2635 | ce=0.1990 | ent=0.1843 | center=0.5530 | val_loss=0.0357 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9828 | val_dqn_proxy_expanded5=0.9358

Epoch 046 | train_loss=0.2632 | ce=0.1994 | ent=0.1808 | center=0.5474 | val_loss=0.0363 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9864 | val_dqn_proxy_expanded5=0.9517

Epoch 047 | train_loss=0.2539 | ce=0.1908 | ent=0.1769 | center=0.5424 | val_loss=0.0333 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9747 | val_dqn_proxy_expanded5=0.9354

Epoch 048 | train_loss=0.2584 | ce=0.1953 | ent=0.1773 | center=0.5424 | val_loss=0.0325 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9881 | val_dqn_proxy_expanded5=0.9583
Early stopping at epoch 48 (best epoch: 33)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
31,ref_base_ent005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-43_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
23,ref_base_drop050_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-25_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
11,ref_base_ls002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
33,ref_base_ent010_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-46_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
15,ref_base_ls000_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-04_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
41,ref_pms_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-12_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,ref_base_ls000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-59_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
39,ref_base_lr2e4_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-07_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
8,ref_base_ls002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-47_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,ref_base_ls000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-56_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
17,ref_base_drop040_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-07_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
29,ref_base_ent005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,ref_base_ls002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-49_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
37,ref_base_lr2e4_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-00_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
25,ref_base_ent002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-28_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
24,ref_base_ent002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-26_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
19,ref_base_drop040_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-11_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
32,ref_base_ent010_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-45_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
5,ref_base_ls005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,ref_base_ls005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-45_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
27,ref_base_ent002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
38,ref_base_lr2e4_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-04_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,ref_base_ls005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-42_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,ref_base_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
35,ref_base_ent010_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
21,ref_base_drop050_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-18_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
20,ref_base_drop050_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-14_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
28,ref_base_ent005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-35_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,ref_base_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-29_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
22,ref_base_drop050_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-21_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
34,ref_base_ent010_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-52_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
36,ref_base_lr2e4_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-57_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,ref_base_ls005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-36_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
26,ref_base_ent002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-31_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
40,ref_pms_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/23-08_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
18,ref_base_drop040_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-09_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
30,ref_base_ent005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-41_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
16,ref_base_drop040_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-06_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
10,ref_base_ls002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-53_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
14,ref_base_ls000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-02_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"

================================================================================
Running experiment 43/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "plateau",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0001,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": 1.0,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_pms_ctrl",
  "lr": 0.0001,
  "label_smoothing": 0.05,
  "entropy_loss_weight": 0.05,
  "mlp_dropout": 0.5,
  "unknown_pas": [
    "PA4"
  ],
  "run_name": "ref_pms_ctrl_unkPA4_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=1.0027 | ce=0.8376 | ent=0.9678 | center=1.1672 | val_loss=0.3767 | val_acc=0.9148 | val_macro_f1=0.9129 | val_dqn_proxy_softmax3=0.6984 | val_dqn_proxy_expanded5=0.6725

Epoch 002 | train_loss=0.6467 | ce=0.4638 | ent=0.5551 | center=1.5515 | val_loss=0.2666 | val_acc=0.9185 | val_macro_f1=0.9180 | val_dqn_proxy_softmax3=0.7337 | val_dqn_proxy_expanded5=0.7389

Epoch 003 | train_loss=0.5753 | ce=0.4075 | ent=0.4531 | center=1.4510 | val_loss=0.2087 | val_acc=0.9444 | val_macro_f1=0.9443 | val_dqn_proxy_softmax3=0.7365 | val_dqn_proxy_expanded5=0.7451

Epoch 004 | train_loss=0.5004 | ce=0.3442 | ent=0.3813 | center=1.3706 | val_loss=0.2281 | val_acc=0.9185 | val_macro_f1=0.9184 | val_dqn_proxy_softmax3=0.7426 | val_dqn_proxy_expanded5=0.7197

Epoch 005 | train_loss=0.4603 | ce=0.3146 | ent=0.3472 | center=1.2835 | val_loss=0.1678 | val_acc=0.9519 | val_macro_f1=0.9521 | val_dqn_proxy_softmax3=0.7470 | val_dqn_proxy_expanded5=0.7193

Epoch 006 | train_loss=0.4481 | ce=0.3096 | ent=0.3332 | center=1.2181 | val_loss=0.1585 | val_acc=0.9593 | val_macro_f1=0.9592 | val_dqn_proxy_softmax3=0.7344 | val_dqn_proxy_expanded5=0.7104

Epoch 007 | train_loss=0.4424 | ce=0.3088 | ent=0.3235 | center=1.1743 | val_loss=0.2258 | val_acc=0.9296 | val_macro_f1=0.9293 | val_dqn_proxy_softmax3=0.7593 | val_dqn_proxy_expanded5=0.7308

Epoch 008 | train_loss=0.4253 | ce=0.2966 | ent=0.3056 | center=1.1344 | val_loss=0.1222 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.7583 | val_dqn_proxy_expanded5=0.7337

Epoch 009 | train_loss=0.4028 | ce=0.2781 | ent=0.2946 | center=1.1003 | val_loss=0.1329 | val_acc=0.9556 | val_macro_f1=0.9557 | val_dqn_proxy_softmax3=0.7525 | val_dqn_proxy_expanded5=0.7262

Epoch 010 | train_loss=0.3806 | ce=0.2602 | ent=0.2726 | center=1.0678 | val_loss=0.1138 | val_acc=0.9778 | val_macro_f1=0.9779 | val_dqn_proxy_softmax3=0.7562 | val_dqn_proxy_expanded5=0.7317

Epoch 011 | train_loss=0.3891 | ce=0.2729 | ent=0.2721 | center=1.0258 | val_loss=0.1059 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.7779 | val_dqn_proxy_expanded5=0.7474

Epoch 012 | train_loss=0.3759 | ce=0.2619 | ent=0.2631 | center=1.0082 | val_loss=0.1244 | val_acc=0.9593 | val_macro_f1=0.9593 | val_dqn_proxy_softmax3=0.7387 | val_dqn_proxy_expanded5=0.7121

Epoch 013 | train_loss=0.3590 | ce=0.2487 | ent=0.2599 | center=0.9731 | val_loss=0.1426 | val_acc=0.9444 | val_macro_f1=0.9442 | val_dqn_proxy_softmax3=0.8578 | val_dqn_proxy_expanded5=0.7988

Epoch 014 | train_loss=0.3700 | ce=0.2624 | ent=0.2556 | center=0.9478 | val_loss=0.0792 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9177 | val_dqn_proxy_expanded5=0.8384

Epoch 015 | train_loss=0.3404 | ce=0.2362 | ent=0.2408 | center=0.9223 | val_loss=0.0772 | val_acc=0.9741 | val_macro_f1=0.9743 | val_dqn_proxy_softmax3=0.9307 | val_dqn_proxy_expanded5=0.8503

Epoch 016 | train_loss=0.3430 | ce=0.2412 | ent=0.2306 | center=0.9026 | val_loss=0.0731 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9354 | val_dqn_proxy_expanded5=0.8808

Epoch 017 | train_loss=0.3309 | ce=0.2315 | ent=0.2323 | center=0.8769 | val_loss=0.0565 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9446 | val_dqn_proxy_expanded5=0.9165

Epoch 018 | train_loss=0.3257 | ce=0.2284 | ent=0.2288 | center=0.8592 | val_loss=0.0646 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9561 | val_dqn_proxy_expanded5=0.8981

Epoch 019 | train_loss=0.3308 | ce=0.2353 | ent=0.2320 | center=0.8391 | val_loss=0.0584 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9476 | val_dqn_proxy_expanded5=0.8897

Epoch 020 | train_loss=0.3143 | ce=0.2215 | ent=0.2235 | center=0.8159 | val_loss=0.0546 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9056 | val_dqn_proxy_expanded5=0.8348

Epoch 021 | train_loss=0.3088 | ce=0.2175 | ent=0.2155 | center=0.8054 | val_loss=0.0491 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9146 | val_dqn_proxy_expanded5=0.8464

Epoch 022 | train_loss=0.3042 | ce=0.2150 | ent=0.2146 | center=0.7842 | val_loss=0.0653 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9258 | val_dqn_proxy_expanded5=0.8534

Epoch 023 | train_loss=0.3138 | ce=0.2267 | ent=0.2122 | center=0.7646 | val_loss=0.0713 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9342 | val_dqn_proxy_expanded5=0.8680

Epoch 024 | train_loss=0.3091 | ce=0.2235 | ent=0.2177 | center=0.7478 | val_loss=0.0607 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9337 | val_dqn_proxy_expanded5=0.8616

Epoch 025 | train_loss=0.3052 | ce=0.2214 | ent=0.2102 | center=0.7327 | val_loss=0.0510 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8976 | val_dqn_proxy_expanded5=0.8363

Epoch 026 | train_loss=0.2893 | ce=0.2078 | ent=0.2006 | center=0.7148 | val_loss=0.0833 | val_acc=0.9704 | val_macro_f1=0.9703 | val_dqn_proxy_softmax3=0.8720 | val_dqn_proxy_expanded5=0.8140

Epoch 027 | train_loss=0.2910 | ce=0.2109 | ent=0.1998 | center=0.7014 | val_loss=0.0420 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9405 | val_dqn_proxy_expanded5=0.8696

Epoch 028 | train_loss=0.2912 | ce=0.2125 | ent=0.1995 | center=0.6873 | val_loss=0.0512 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7701 | val_dqn_proxy_expanded5=0.7405

Epoch 029 | train_loss=0.2833 | ce=0.2064 | ent=0.1979 | center=0.6708 | val_loss=0.0466 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.8312 | val_dqn_proxy_expanded5=0.7836

Epoch 030 | train_loss=0.2876 | ce=0.2115 | ent=0.2009 | center=0.6599 | val_loss=0.0485 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9187 | val_dqn_proxy_expanded5=0.8497

Epoch 031 | train_loss=0.2804 | ce=0.2061 | ent=0.1905 | center=0.6475 | val_loss=0.0629 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8560 | val_dqn_proxy_expanded5=0.7959

Epoch 032 | train_loss=0.2795 | ce=0.2066 | ent=0.1921 | center=0.6327 | val_loss=0.0480 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8942 | val_dqn_proxy_expanded5=0.8259

Epoch 033 | train_loss=0.2811 | ce=0.2090 | ent=0.1971 | center=0.6223 | val_loss=0.0644 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8406 | val_dqn_proxy_expanded5=0.7941
Early stopping at epoch 33 (best epoch: 18)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
31,ref_base_ent005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-43_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
23,ref_base_drop050_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-25_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
11,ref_base_ls002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
33,ref_base_ent010_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-46_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
15,ref_base_ls000_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-04_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
41,ref_pms_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-12_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,ref_base_ls000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-59_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
39,ref_base_lr2e4_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-07_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
8,ref_base_ls002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-47_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,ref_base_ls000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-56_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
17,ref_base_drop040_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-07_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
29,ref_base_ent005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,ref_base_ls002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-49_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
37,ref_base_lr2e4_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-00_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
25,ref_base_ent002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-28_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
24,ref_base_ent002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-26_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
19,ref_base_drop040_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-11_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
32,ref_base_ent010_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-45_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
5,ref_base_ls005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,ref_base_ls005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-45_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
27,ref_base_ent002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
38,ref_base_lr2e4_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-04_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,ref_base_ls005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-42_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,ref_base_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
35,ref_base_ent010_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
21,ref_base_drop050_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-18_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
20,ref_base_drop050_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-14_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
42,ref_pms_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-16_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
28,ref_base_ent005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-35_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,ref_base_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-29_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
22,ref_base_drop050_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-21_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
34,ref_base_ent010_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-52_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
36,ref_base_lr2e4_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-57_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,ref_base_ls005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-36_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
26,ref_base_ent002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-31_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
40,ref_pms_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/23-08_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
18,ref_base_drop040_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-09_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
30,ref_base_ent005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-41_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
16,ref_base_drop040_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-06_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
10,ref_base_ls002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-53_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
14,ref_base_ls000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-02_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"

================================================================================
Running experiment 44/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "plateau",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0001,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": 1.0,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_pms_ctrl",
  "lr": 0.0001,
  "label_smoothing": 0.05,
  "entropy_loss_weight": 0.05,
  "mlp_dropout": 0.5,
  "unknown_pas": [
    "PA8"
  ],
  "run_name": "ref_pms_ctrl_unkPA8_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.9454 | ce=0.7927 | ent=0.9480 | center=1.0530 | val_loss=0.2291 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8582 | val_dqn_proxy_expanded5=0.8671

Epoch 002 | train_loss=0.4320 | ce=0.2817 | ent=0.3628 | center=1.3219 | val_loss=0.1228 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9669 | val_dqn_proxy_expanded5=0.9691

Epoch 003 | train_loss=0.3662 | ce=0.2377 | ent=0.2635 | center=1.1532 | val_loss=0.1095 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9556 | val_dqn_proxy_expanded5=0.9414

Epoch 004 | train_loss=0.3577 | ce=0.2387 | ent=0.2463 | center=1.0668 | val_loss=0.1034 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9534 | val_dqn_proxy_expanded5=0.9413

Epoch 005 | train_loss=0.3345 | ce=0.2232 | ent=0.2329 | center=0.9973 | val_loss=0.1058 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9550 | val_dqn_proxy_expanded5=0.9411

Epoch 006 | train_loss=0.3351 | ce=0.2286 | ent=0.2344 | center=0.9479 | val_loss=0.1030 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9411 | val_dqn_proxy_expanded5=0.9236

Epoch 007 | train_loss=0.3284 | ce=0.2263 | ent=0.2239 | center=0.9090 | val_loss=0.1023 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9691 | val_dqn_proxy_expanded5=0.9550

Epoch 008 | train_loss=0.3195 | ce=0.2209 | ent=0.2166 | center=0.8776 | val_loss=0.1013 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9484 | val_dqn_proxy_expanded5=0.9262

Epoch 009 | train_loss=0.3217 | ce=0.2260 | ent=0.2221 | center=0.8456 | val_loss=0.0995 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9664 | val_dqn_proxy_expanded5=0.9449

Epoch 010 | train_loss=0.3129 | ce=0.2198 | ent=0.2135 | center=0.8241 | val_loss=0.1013 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9233 | val_dqn_proxy_expanded5=0.8983

Epoch 011 | train_loss=0.3056 | ce=0.2151 | ent=0.2037 | center=0.8031 | val_loss=0.0937 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9492 | val_dqn_proxy_expanded5=0.9129

Epoch 012 | train_loss=0.3040 | ce=0.2164 | ent=0.2092 | center=0.7719 | val_loss=0.0883 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9204 | val_dqn_proxy_expanded5=0.8880

Epoch 013 | train_loss=0.3038 | ce=0.2176 | ent=0.2061 | center=0.7584 | val_loss=0.0835 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9373 | val_dqn_proxy_expanded5=0.9038

Epoch 014 | train_loss=0.2976 | ce=0.2130 | ent=0.2106 | center=0.7410 | val_loss=0.0806 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9416 | val_dqn_proxy_expanded5=0.9182

Epoch 015 | train_loss=0.2877 | ce=0.2056 | ent=0.2053 | center=0.7177 | val_loss=0.0674 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9346 | val_dqn_proxy_expanded5=0.9004

Epoch 016 | train_loss=0.2858 | ce=0.2054 | ent=0.1966 | center=0.7063 | val_loss=0.0662 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9596 | val_dqn_proxy_expanded5=0.9243

Epoch 017 | train_loss=0.2804 | ce=0.2016 | ent=0.1914 | center=0.6917 | val_loss=0.0666 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9366 | val_dqn_proxy_expanded5=0.8999

Epoch 018 | train_loss=0.2740 | ce=0.1974 | ent=0.1888 | center=0.6715 | val_loss=0.0593 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9795 | val_dqn_proxy_expanded5=0.9416

Epoch 019 | train_loss=0.2675 | ce=0.1927 | ent=0.1862 | center=0.6546 | val_loss=0.0582 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9508 | val_dqn_proxy_expanded5=0.9032

Epoch 020 | train_loss=0.2678 | ce=0.1944 | ent=0.1839 | center=0.6419 | val_loss=0.0549 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9789 | val_dqn_proxy_expanded5=0.9288

Epoch 021 | train_loss=0.2637 | ce=0.1923 | ent=0.1795 | center=0.6241 | val_loss=0.0604 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9466 | val_dqn_proxy_expanded5=0.8892

Epoch 022 | train_loss=0.2623 | ce=0.1923 | ent=0.1779 | center=0.6107 | val_loss=0.0569 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9841 | val_dqn_proxy_expanded5=0.9341

Epoch 023 | train_loss=0.2577 | ce=0.1890 | ent=0.1758 | center=0.5988 | val_loss=0.0581 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9518 | val_dqn_proxy_expanded5=0.8994

Epoch 024 | train_loss=0.2593 | ce=0.1921 | ent=0.1754 | center=0.5838 | val_loss=0.0580 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9876 | val_dqn_proxy_expanded5=0.9367

Epoch 025 | train_loss=0.2542 | ce=0.1884 | ent=0.1749 | center=0.5706 | val_loss=0.0594 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9477 | val_dqn_proxy_expanded5=0.8960

Epoch 026 | train_loss=0.2538 | ce=0.1891 | ent=0.1751 | center=0.5595 | val_loss=0.0549 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9686 | val_dqn_proxy_expanded5=0.9103

Epoch 027 | train_loss=0.2515 | ce=0.1881 | ent=0.1718 | center=0.5481 | val_loss=0.0560 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9731 | val_dqn_proxy_expanded5=0.9147

Epoch 028 | train_loss=0.2503 | ce=0.1876 | ent=0.1714 | center=0.5409 | val_loss=0.0528 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9398 | val_dqn_proxy_expanded5=0.8899

Epoch 029 | train_loss=0.2515 | ce=0.1893 | ent=0.1706 | center=0.5361 | val_loss=0.0571 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9737 | val_dqn_proxy_expanded5=0.9161

Epoch 030 | train_loss=0.2502 | ce=0.1885 | ent=0.1738 | center=0.5307 | val_loss=0.0570 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9351 | val_dqn_proxy_expanded5=0.8859

Epoch 031 | train_loss=0.2497 | ce=0.1888 | ent=0.1672 | center=0.5254 | val_loss=0.0587 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9640 | val_dqn_proxy_expanded5=0.9079

Epoch 032 | train_loss=0.2472 | ce=0.1870 | ent=0.1708 | center=0.5164 | val_loss=0.0591 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9864 | val_dqn_proxy_expanded5=0.9265

Epoch 033 | train_loss=0.2475 | ce=0.1877 | ent=0.1715 | center=0.5118 | val_loss=0.0558 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9426 | val_dqn_proxy_expanded5=0.8896

Epoch 034 | train_loss=0.2472 | ce=0.1879 | ent=0.1725 | center=0.5073 | val_loss=0.0580 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9691 | val_dqn_proxy_expanded5=0.9112

Epoch 035 | train_loss=0.2466 | ce=0.1880 | ent=0.1693 | center=0.5013 | val_loss=0.0553 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9637 | val_dqn_proxy_expanded5=0.9056

Epoch 036 | train_loss=0.2446 | ce=0.1862 | ent=0.1694 | center=0.4996 | val_loss=0.0558 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9188 | val_dqn_proxy_expanded5=0.8736

Epoch 037 | train_loss=0.2467 | ce=0.1887 | ent=0.1685 | center=0.4958 | val_loss=0.0558 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9568 | val_dqn_proxy_expanded5=0.9002

Epoch 038 | train_loss=0.2446 | ce=0.1867 | ent=0.1708 | center=0.4932 | val_loss=0.0543 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9405 | val_dqn_proxy_expanded5=0.8901

Epoch 039 | train_loss=0.2439 | ce=0.1868 | ent=0.1658 | center=0.4889 | val_loss=0.0550 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9198 | val_dqn_proxy_expanded5=0.8732
Early stopping at epoch 39 (best epoch: 24)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
31,ref_base_ent005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-43_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
23,ref_base_drop050_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-25_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
11,ref_base_ls002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
33,ref_base_ent010_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-46_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
15,ref_base_ls000_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-04_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
41,ref_pms_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-12_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,ref_base_ls000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-59_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
39,ref_base_lr2e4_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-07_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
8,ref_base_ls002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-47_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,ref_base_ls000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-56_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
17,ref_base_drop040_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-07_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
29,ref_base_ent005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,ref_base_ls002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-49_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
37,ref_base_lr2e4_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-00_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
43,ref_pms_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-19_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
25,ref_base_ent002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-28_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
24,ref_base_ent002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-26_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
19,ref_base_drop040_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-11_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
32,ref_base_ent010_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-45_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
5,ref_base_ls005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,ref_base_ls005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-45_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
27,ref_base_ent002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
38,ref_base_lr2e4_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-04_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,ref_base_ls005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-42_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,ref_base_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
35,ref_base_ent010_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
21,ref_base_drop050_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-18_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
20,ref_base_drop050_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-14_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
42,ref_pms_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-16_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
28,ref_base_ent005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-35_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,ref_base_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-29_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
22,ref_base_drop050_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-21_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
34,ref_base_ent010_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-52_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
36,ref_base_lr2e4_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-57_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,ref_base_ls005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-36_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
26,ref_base_ent002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-31_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
40,ref_pms_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/23-08_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
18,ref_base_drop040_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-09_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
30,ref_base_ent005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-41_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
16,ref_base_drop040_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-06_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
10,ref_base_ls002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-53_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
14,ref_base_ls000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-02_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"

================================================================================
Running experiment 45/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "plateau",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0001,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": 1.0,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_pms_ent000",
  "lr": 0.0001,
  "label_smoothing": 0.05,
  "entropy_loss_weight": 0.0,
  "mlp_dropout": 0.5,
  "unknown_pas": [
    "PA2"
  ],
  "run_name": "ref_pms_ent000_unkPA2_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.9635 | ce=0.8611 | ent=0.0000 | center=1.0240 | val_loss=0.3873 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7927 | val_dqn_proxy_expanded5=0.7751

Epoch 002 | train_loss=0.5104 | ce=0.3851 | ent=0.0000 | center=1.2530 | val_loss=0.1903 | val_acc=0.9593 | val_macro_f1=0.9589 | val_dqn_proxy_softmax3=0.8532 | val_dqn_proxy_expanded5=0.8590

Epoch 003 | train_loss=0.4057 | ce=0.2891 | ent=0.0000 | center=1.1661 | val_loss=0.1520 | val_acc=0.9630 | val_macro_f1=0.9632 | val_dqn_proxy_softmax3=0.6834 | val_dqn_proxy_expanded5=0.7386

Epoch 004 | train_loss=0.3706 | ce=0.2633 | ent=0.0000 | center=1.0730 | val_loss=0.1119 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6161 | val_dqn_proxy_expanded5=0.7179

Epoch 005 | train_loss=0.3566 | ce=0.2566 | ent=0.0000 | center=1.0001 | val_loss=0.1032 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6643 | val_dqn_proxy_expanded5=0.7461

Epoch 006 | train_loss=0.3456 | ce=0.2496 | ent=0.0000 | center=0.9598 | val_loss=0.1046 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6700 | val_dqn_proxy_expanded5=0.7143

Epoch 007 | train_loss=0.3436 | ce=0.2522 | ent=0.0000 | center=0.9133 | val_loss=0.1102 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8504 | val_dqn_proxy_expanded5=0.8603

Epoch 008 | train_loss=0.3284 | ce=0.2402 | ent=0.0000 | center=0.8822 | val_loss=0.1002 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7709 | val_dqn_proxy_expanded5=0.7596

Epoch 009 | train_loss=0.3245 | ce=0.2392 | ent=0.0000 | center=0.8525 | val_loss=0.1016 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6134 | val_dqn_proxy_expanded5=0.6970

Epoch 010 | train_loss=0.3303 | ce=0.2474 | ent=0.0000 | center=0.8295 | val_loss=0.1054 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7928 | val_dqn_proxy_expanded5=0.8053

Epoch 011 | train_loss=0.3165 | ce=0.2360 | ent=0.0000 | center=0.8054 | val_loss=0.0849 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6561 | val_dqn_proxy_expanded5=0.7364

Epoch 012 | train_loss=0.3129 | ce=0.2340 | ent=0.0000 | center=0.7886 | val_loss=0.0898 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7705 | val_dqn_proxy_expanded5=0.7499

Epoch 013 | train_loss=0.3056 | ce=0.2290 | ent=0.0000 | center=0.7662 | val_loss=0.0800 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7055 | val_dqn_proxy_expanded5=0.7282

Epoch 014 | train_loss=0.3005 | ce=0.2258 | ent=0.0000 | center=0.7466 | val_loss=0.0807 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7408 | val_dqn_proxy_expanded5=0.7316

Epoch 015 | train_loss=0.2977 | ce=0.2247 | ent=0.0000 | center=0.7303 | val_loss=0.0704 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7799 | val_dqn_proxy_expanded5=0.7628

Epoch 016 | train_loss=0.2883 | ce=0.2161 | ent=0.0000 | center=0.7226 | val_loss=0.0667 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6566 | val_dqn_proxy_expanded5=0.7373

Epoch 017 | train_loss=0.2808 | ce=0.2101 | ent=0.0000 | center=0.7075 | val_loss=0.0663 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7354 | val_dqn_proxy_expanded5=0.7383
Early stopping at epoch 17 (best epoch: 2)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
31,ref_base_ent005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-43_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
23,ref_base_drop050_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-25_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
11,ref_base_ls002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
33,ref_base_ent010_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-46_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
15,ref_base_ls000_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-04_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
41,ref_pms_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-12_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,ref_base_ls000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-59_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
39,ref_base_lr2e4_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-07_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
8,ref_base_ls002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-47_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,ref_base_ls000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-56_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
17,ref_base_drop040_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-07_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
29,ref_base_ent005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,ref_base_ls002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-49_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
37,ref_base_lr2e4_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-00_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
43,ref_pms_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-19_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
25,ref_base_ent002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-28_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
24,ref_base_ent002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-26_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
19,ref_base_drop040_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-11_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
32,ref_base_ent010_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-45_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
5,ref_base_ls005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,ref_base_ls005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-45_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
27,ref_base_ent002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
38,ref_base_lr2e4_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-04_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,ref_base_ls005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-42_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,ref_base_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
35,ref_base_ent010_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
21,ref_base_drop050_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-18_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
20,ref_base_drop050_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-14_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
42,ref_pms_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-16_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
28,ref_base_ent005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-35_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,ref_base_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-29_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
22,ref_base_drop050_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-21_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
44,ref_pms_ent000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/23-22_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
34,ref_base_ent010_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-52_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
36,ref_base_lr2e4_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-57_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,ref_base_ls005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-36_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
26,ref_base_ent002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-31_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
40,ref_pms_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/23-08_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
18,ref_base_drop040_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-09_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
30,ref_base_ent005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-41_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
16,ref_base_drop040_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-06_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
10,ref_base_ls002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-53_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
14,ref_base_ls000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-02_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"

================================================================================
Running experiment 46/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "plateau",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0001,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": 1.0,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_pms_ent000",
  "lr": 0.0001,
  "label_smoothing": 0.05,
  "entropy_loss_weight": 0.0,
  "mlp_dropout": 0.5,
  "unknown_pas": [
    "PA3"
  ],
  "run_name": "ref_pms_ent000_unkPA3_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=1.0031 | ce=0.8981 | ent=0.0000 | center=1.0505 | val_loss=0.5013 | val_acc=0.8370 | val_macro_f1=0.8250 | val_dqn_proxy_softmax3=0.7144 | val_dqn_proxy_expanded5=0.7361

Epoch 002 | train_loss=0.5946 | ce=0.4608 | ent=0.0000 | center=1.3377 | val_loss=0.2154 | val_acc=0.9259 | val_macro_f1=0.9259 | val_dqn_proxy_softmax3=0.7876 | val_dqn_proxy_expanded5=0.7721

Epoch 003 | train_loss=0.4895 | ce=0.3567 | ent=0.0000 | center=1.3280 | val_loss=0.1753 | val_acc=0.9407 | val_macro_f1=0.9410 | val_dqn_proxy_softmax3=0.8749 | val_dqn_proxy_expanded5=0.8402

Epoch 004 | train_loss=0.4384 | ce=0.3158 | ent=0.0000 | center=1.2266 | val_loss=0.1389 | val_acc=0.9556 | val_macro_f1=0.9558 | val_dqn_proxy_softmax3=0.8911 | val_dqn_proxy_expanded5=0.8770

Epoch 005 | train_loss=0.4341 | ce=0.3178 | ent=0.0000 | center=1.1629 | val_loss=0.1408 | val_acc=0.9519 | val_macro_f1=0.9518 | val_dqn_proxy_softmax3=0.8845 | val_dqn_proxy_expanded5=0.8592

Epoch 006 | train_loss=0.3974 | ce=0.2860 | ent=0.0000 | center=1.1139 | val_loss=0.1433 | val_acc=0.9481 | val_macro_f1=0.9484 | val_dqn_proxy_softmax3=0.9423 | val_dqn_proxy_expanded5=0.9185

Epoch 007 | train_loss=0.3883 | ce=0.2811 | ent=0.0000 | center=1.0722 | val_loss=0.1059 | val_acc=0.9741 | val_macro_f1=0.9743 | val_dqn_proxy_softmax3=0.9759 | val_dqn_proxy_expanded5=0.9597

Epoch 008 | train_loss=0.3775 | ce=0.2749 | ent=0.0000 | center=1.0262 | val_loss=0.1523 | val_acc=0.9444 | val_macro_f1=0.9447 | val_dqn_proxy_softmax3=0.9679 | val_dqn_proxy_expanded5=0.9491

Epoch 009 | train_loss=0.3781 | ce=0.2790 | ent=0.0000 | center=0.9911 | val_loss=0.1393 | val_acc=0.9519 | val_macro_f1=0.9516 | val_dqn_proxy_softmax3=0.9637 | val_dqn_proxy_expanded5=0.9493

Epoch 010 | train_loss=0.3671 | ce=0.2696 | ent=0.0000 | center=0.9758 | val_loss=0.1091 | val_acc=0.9593 | val_macro_f1=0.9594 | val_dqn_proxy_softmax3=0.9064 | val_dqn_proxy_expanded5=0.9037

Epoch 011 | train_loss=0.3502 | ce=0.2555 | ent=0.0000 | center=0.9466 | val_loss=0.0972 | val_acc=0.9741 | val_macro_f1=0.9742 | val_dqn_proxy_softmax3=0.9564 | val_dqn_proxy_expanded5=0.9306

Epoch 012 | train_loss=0.3642 | ce=0.2727 | ent=0.0000 | center=0.9156 | val_loss=0.1380 | val_acc=0.9481 | val_macro_f1=0.9484 | val_dqn_proxy_softmax3=0.9602 | val_dqn_proxy_expanded5=0.9498

Epoch 013 | train_loss=0.3316 | ce=0.2426 | ent=0.0000 | center=0.8897 | val_loss=0.1007 | val_acc=0.9667 | val_macro_f1=0.9666 | val_dqn_proxy_softmax3=0.9710 | val_dqn_proxy_expanded5=0.9410

Epoch 014 | train_loss=0.3347 | ce=0.2478 | ent=0.0000 | center=0.8691 | val_loss=0.0821 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9289 | val_dqn_proxy_expanded5=0.9293

Epoch 015 | train_loss=0.3231 | ce=0.2388 | ent=0.0000 | center=0.8433 | val_loss=0.1182 | val_acc=0.9556 | val_macro_f1=0.9556 | val_dqn_proxy_softmax3=0.9576 | val_dqn_proxy_expanded5=0.9190

Epoch 016 | train_loss=0.3377 | ce=0.2552 | ent=0.0000 | center=0.8246 | val_loss=0.0775 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9307 | val_dqn_proxy_expanded5=0.9063

Epoch 017 | train_loss=0.3155 | ce=0.2350 | ent=0.0000 | center=0.8053 | val_loss=0.0879 | val_acc=0.9741 | val_macro_f1=0.9740 | val_dqn_proxy_softmax3=0.8873 | val_dqn_proxy_expanded5=0.8835

Epoch 018 | train_loss=0.3012 | ce=0.2227 | ent=0.0000 | center=0.7851 | val_loss=0.0677 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9289 | val_dqn_proxy_expanded5=0.9105

Epoch 019 | train_loss=0.3006 | ce=0.2230 | ent=0.0000 | center=0.7756 | val_loss=0.0596 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9334 | val_dqn_proxy_expanded5=0.9016

Epoch 020 | train_loss=0.2906 | ce=0.2158 | ent=0.0000 | center=0.7483 | val_loss=0.0564 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8940 | val_dqn_proxy_expanded5=0.8639

Epoch 021 | train_loss=0.2971 | ce=0.2234 | ent=0.0000 | center=0.7373 | val_loss=0.0908 | val_acc=0.9704 | val_macro_f1=0.9704 | val_dqn_proxy_softmax3=0.9619 | val_dqn_proxy_expanded5=0.9267

Epoch 022 | train_loss=0.3016 | ce=0.2299 | ent=0.0000 | center=0.7174 | val_loss=0.0784 | val_acc=0.9741 | val_macro_f1=0.9740 | val_dqn_proxy_softmax3=0.9756 | val_dqn_proxy_expanded5=0.9476
Early stopping at epoch 22 (best epoch: 7)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
31,ref_base_ent005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-43_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
23,ref_base_drop050_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-25_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
11,ref_base_ls002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
33,ref_base_ent010_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-46_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
15,ref_base_ls000_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-04_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
41,ref_pms_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-12_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,ref_base_ls000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-59_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
39,ref_base_lr2e4_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-07_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
8,ref_base_ls002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-47_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,ref_base_ls000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-56_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
17,ref_base_drop040_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-07_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
29,ref_base_ent005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,ref_base_ls002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-49_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
37,ref_base_lr2e4_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-00_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
43,ref_pms_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-19_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
45,ref_pms_ent000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-23_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
25,ref_base_ent002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-28_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
24,ref_base_ent002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-26_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
19,ref_base_drop040_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-11_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
32,ref_base_ent010_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-45_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
5,ref_base_ls005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,ref_base_ls005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-45_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
27,ref_base_ent002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
38,ref_base_lr2e4_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-04_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,ref_base_ls005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-42_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,ref_base_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
35,ref_base_ent010_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
21,ref_base_drop050_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-18_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
20,ref_base_drop050_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-14_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
42,ref_pms_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-16_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
28,ref_base_ent005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-35_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,ref_base_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-29_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
22,ref_base_drop050_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-21_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
44,ref_pms_ent000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/23-22_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
34,ref_base_ent010_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-52_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
36,ref_base_lr2e4_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-57_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,ref_base_ls005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-36_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
26,ref_base_ent002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-31_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
40,ref_pms_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/23-08_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
18,ref_base_drop040_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-09_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
30,ref_base_ent005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-41_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
16,ref_base_drop040_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-06_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
10,ref_base_ls002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-53_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
14,ref_base_ls000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-02_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"

================================================================================
Running experiment 47/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "plateau",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0001,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": 1.0,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_pms_ent000",
  "lr": 0.0001,
  "label_smoothing": 0.05,
  "entropy_loss_weight": 0.0,
  "mlp_dropout": 0.5,
  "unknown_pas": [
    "PA4"
  ],
  "run_name": "ref_pms_ent000_unkPA4_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.9868 | ce=0.8785 | ent=0.0000 | center=1.0824 | val_loss=0.4503 | val_acc=0.8519 | val_macro_f1=0.8408 | val_dqn_proxy_softmax3=0.6650 | val_dqn_proxy_expanded5=0.6768

Epoch 002 | train_loss=0.6115 | ce=0.4645 | ent=0.0000 | center=1.4696 | val_loss=0.2864 | val_acc=0.9148 | val_macro_f1=0.9146 | val_dqn_proxy_softmax3=0.7194 | val_dqn_proxy_expanded5=0.7474

Epoch 003 | train_loss=0.5390 | ce=0.4027 | ent=0.0000 | center=1.3631 | val_loss=0.2154 | val_acc=0.9556 | val_macro_f1=0.9556 | val_dqn_proxy_softmax3=0.7454 | val_dqn_proxy_expanded5=0.7873

Epoch 004 | train_loss=0.4694 | ce=0.3426 | ent=0.0000 | center=1.2688 | val_loss=0.1870 | val_acc=0.9667 | val_macro_f1=0.9668 | val_dqn_proxy_softmax3=0.7543 | val_dqn_proxy_expanded5=0.7749

Epoch 005 | train_loss=0.4545 | ce=0.3338 | ent=0.0000 | center=1.2067 | val_loss=0.2537 | val_acc=0.9259 | val_macro_f1=0.9258 | val_dqn_proxy_softmax3=0.7295 | val_dqn_proxy_expanded5=0.7444

Epoch 006 | train_loss=0.4288 | ce=0.3137 | ent=0.0000 | center=1.1513 | val_loss=0.1670 | val_acc=0.9667 | val_macro_f1=0.9669 | val_dqn_proxy_softmax3=0.7459 | val_dqn_proxy_expanded5=0.7272

Epoch 007 | train_loss=0.4197 | ce=0.3077 | ent=0.0000 | center=1.1194 | val_loss=0.1596 | val_acc=0.9556 | val_macro_f1=0.9555 | val_dqn_proxy_softmax3=0.7413 | val_dqn_proxy_expanded5=0.7280

Epoch 008 | train_loss=0.3939 | ce=0.2863 | ent=0.0000 | center=1.0763 | val_loss=0.1297 | val_acc=0.9741 | val_macro_f1=0.9742 | val_dqn_proxy_softmax3=0.7518 | val_dqn_proxy_expanded5=0.7296

Epoch 009 | train_loss=0.3897 | ce=0.2850 | ent=0.0000 | center=1.0474 | val_loss=0.1406 | val_acc=0.9630 | val_macro_f1=0.9630 | val_dqn_proxy_softmax3=0.7556 | val_dqn_proxy_expanded5=0.7320

Epoch 010 | train_loss=0.3728 | ce=0.2710 | ent=0.0000 | center=1.0176 | val_loss=0.1769 | val_acc=0.9481 | val_macro_f1=0.9480 | val_dqn_proxy_softmax3=0.7639 | val_dqn_proxy_expanded5=0.7378

Epoch 011 | train_loss=0.3640 | ce=0.2649 | ent=0.0000 | center=0.9912 | val_loss=0.1176 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.7730 | val_dqn_proxy_expanded5=0.7418

Epoch 012 | train_loss=0.3468 | ce=0.2508 | ent=0.0000 | center=0.9602 | val_loss=0.1653 | val_acc=0.9370 | val_macro_f1=0.9367 | val_dqn_proxy_softmax3=0.8648 | val_dqn_proxy_expanded5=0.8183

Epoch 013 | train_loss=0.3374 | ce=0.2438 | ent=0.0000 | center=0.9356 | val_loss=0.0906 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9156 | val_dqn_proxy_expanded5=0.8579

Epoch 014 | train_loss=0.3234 | ce=0.2330 | ent=0.0000 | center=0.9042 | val_loss=0.0808 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9481 | val_dqn_proxy_expanded5=0.8917

Epoch 015 | train_loss=0.3321 | ce=0.2436 | ent=0.0000 | center=0.8844 | val_loss=0.0734 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9578 | val_dqn_proxy_expanded5=0.8976

Epoch 016 | train_loss=0.3220 | ce=0.2352 | ent=0.0000 | center=0.8685 | val_loss=0.0806 | val_acc=0.9778 | val_macro_f1=0.9779 | val_dqn_proxy_softmax3=0.9332 | val_dqn_proxy_expanded5=0.8811

Epoch 017 | train_loss=0.3157 | ce=0.2307 | ent=0.0000 | center=0.8500 | val_loss=0.0708 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9551 | val_dqn_proxy_expanded5=0.8961

Epoch 018 | train_loss=0.3128 | ce=0.2303 | ent=0.0000 | center=0.8253 | val_loss=0.0769 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9574 | val_dqn_proxy_expanded5=0.8980

Epoch 019 | train_loss=0.3079 | ce=0.2270 | ent=0.0000 | center=0.8086 | val_loss=0.0832 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9559 | val_dqn_proxy_expanded5=0.8932

Epoch 020 | train_loss=0.2978 | ce=0.2187 | ent=0.0000 | center=0.7905 | val_loss=0.0662 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9594 | val_dqn_proxy_expanded5=0.8977

Epoch 021 | train_loss=0.3056 | ce=0.2287 | ent=0.0000 | center=0.7696 | val_loss=0.1059 | val_acc=0.9593 | val_macro_f1=0.9591 | val_dqn_proxy_softmax3=0.9066 | val_dqn_proxy_expanded5=0.8616

Epoch 022 | train_loss=0.2885 | ce=0.2126 | ent=0.0000 | center=0.7585 | val_loss=0.0500 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9361 | val_dqn_proxy_expanded5=0.8598

Epoch 023 | train_loss=0.2920 | ce=0.2175 | ent=0.0000 | center=0.7456 | val_loss=0.0504 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.8028 | val_dqn_proxy_expanded5=0.7714

Epoch 024 | train_loss=0.2903 | ce=0.2175 | ent=0.0000 | center=0.7273 | val_loss=0.0703 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.7743 | val_dqn_proxy_expanded5=0.7452

Epoch 025 | train_loss=0.2784 | ce=0.2075 | ent=0.0000 | center=0.7091 | val_loss=0.0727 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8531 | val_dqn_proxy_expanded5=0.7949

Epoch 026 | train_loss=0.2843 | ce=0.2147 | ent=0.0000 | center=0.6964 | val_loss=0.0727 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8601 | val_dqn_proxy_expanded5=0.8045

Epoch 027 | train_loss=0.2777 | ce=0.2099 | ent=0.0000 | center=0.6781 | val_loss=0.0564 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.7880 | val_dqn_proxy_expanded5=0.7564

Epoch 028 | train_loss=0.2688 | ce=0.2021 | ent=0.0000 | center=0.6666 | val_loss=0.0491 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.7846 | val_dqn_proxy_expanded5=0.7560

Epoch 029 | train_loss=0.2724 | ce=0.2071 | ent=0.0000 | center=0.6532 | val_loss=0.0515 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7865 | val_dqn_proxy_expanded5=0.7541

Epoch 030 | train_loss=0.2814 | ce=0.2175 | ent=0.0000 | center=0.6385 | val_loss=0.0654 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7779 | val_dqn_proxy_expanded5=0.7505

Epoch 031 | train_loss=0.2745 | ce=0.2114 | ent=0.0000 | center=0.6311 | val_loss=0.0531 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.7676 | val_dqn_proxy_expanded5=0.7308

Epoch 032 | train_loss=0.2752 | ce=0.2137 | ent=0.0000 | center=0.6148 | val_loss=0.0531 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7768 | val_dqn_proxy_expanded5=0.7203

Epoch 033 | train_loss=0.2656 | ce=0.2050 | ent=0.0000 | center=0.6061 | val_loss=0.0469 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.7828 | val_dqn_proxy_expanded5=0.7576

Epoch 034 | train_loss=0.2659 | ce=0.2065 | ent=0.0000 | center=0.5940 | val_loss=0.0494 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.7699 | val_dqn_proxy_expanded5=0.7542

Epoch 035 | train_loss=0.2632 | ce=0.2051 | ent=0.0000 | center=0.5808 | val_loss=0.0628 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.7857 | val_dqn_proxy_expanded5=0.7535
Early stopping at epoch 35 (best epoch: 20)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
31,ref_base_ent005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-43_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
23,ref_base_drop050_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-25_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
11,ref_base_ls002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
33,ref_base_ent010_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-46_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
15,ref_base_ls000_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-04_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
41,ref_pms_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-12_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,ref_base_ls000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-59_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
39,ref_base_lr2e4_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-07_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
8,ref_base_ls002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-47_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,ref_base_ls000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-56_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
17,ref_base_drop040_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-07_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
29,ref_base_ent005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,ref_base_ls002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-49_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
37,ref_base_lr2e4_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-00_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
43,ref_pms_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-19_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
45,ref_pms_ent000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-23_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
25,ref_base_ent002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-28_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
24,ref_base_ent002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-26_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
19,ref_base_drop040_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-11_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
32,ref_base_ent010_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-45_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
5,ref_base_ls005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,ref_base_ls005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-45_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
27,ref_base_ent002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
38,ref_base_lr2e4_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-04_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,ref_base_ls005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-42_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,ref_base_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
35,ref_base_ent010_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
21,ref_base_drop050_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-18_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
20,ref_base_drop050_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-14_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
42,ref_pms_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-16_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
28,ref_base_ent005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-35_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,ref_base_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-29_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
46,ref_pms_ent000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-25_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
22,ref_base_drop050_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-21_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
44,ref_pms_ent000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/23-22_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
34,ref_base_ent010_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-52_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
36,ref_base_lr2e4_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-57_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,ref_base_ls005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-36_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
26,ref_base_ent002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-31_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
40,ref_pms_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/23-08_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
18,ref_base_drop040_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-09_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
30,ref_base_ent005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-41_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
16,ref_base_drop040_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-06_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
10,ref_base_ls002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-53_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
14,ref_base_ls000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-02_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"

================================================================================
Running experiment 48/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "plateau",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0001,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": 1.0,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_pms_ent000",
  "lr": 0.0001,
  "label_smoothing": 0.05,
  "entropy_loss_weight": 0.0,
  "mlp_dropout": 0.5,
  "unknown_pas": [
    "PA8"
  ],
  "run_name": "ref_pms_ent000_unkPA8_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.8890 | ce=0.7778 | ent=0.0000 | center=1.1126 | val_loss=0.2315 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8274 | val_dqn_proxy_expanded5=0.8056

Epoch 002 | train_loss=0.4347 | ce=0.2926 | ent=0.0000 | center=1.4204 | val_loss=0.1312 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9180 | val_dqn_proxy_expanded5=0.8954

Epoch 003 | train_loss=0.3777 | ce=0.2539 | ent=0.0000 | center=1.2379 | val_loss=0.1163 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9649 | val_dqn_proxy_expanded5=0.9646

Epoch 004 | train_loss=0.3543 | ce=0.2399 | ent=0.0000 | center=1.1433 | val_loss=0.1163 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9514 | val_dqn_proxy_expanded5=0.9563

Epoch 005 | train_loss=0.3337 | ce=0.2268 | ent=0.0000 | center=1.0693 | val_loss=0.1087 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9171 | val_dqn_proxy_expanded5=0.9019

Epoch 006 | train_loss=0.3247 | ce=0.2232 | ent=0.0000 | center=1.0146 | val_loss=0.1109 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9053 | val_dqn_proxy_expanded5=0.8964

Epoch 007 | train_loss=0.3282 | ce=0.2307 | ent=0.0000 | center=0.9745 | val_loss=0.1042 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9383 | val_dqn_proxy_expanded5=0.9441

Epoch 008 | train_loss=0.3177 | ce=0.2234 | ent=0.0000 | center=0.9428 | val_loss=0.1023 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9330 | val_dqn_proxy_expanded5=0.9313

Epoch 009 | train_loss=0.3132 | ce=0.2220 | ent=0.0000 | center=0.9115 | val_loss=0.1010 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9433 | val_dqn_proxy_expanded5=0.9416

Epoch 010 | train_loss=0.3082 | ce=0.2204 | ent=0.0000 | center=0.8780 | val_loss=0.0975 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9359 | val_dqn_proxy_expanded5=0.9250

Epoch 011 | train_loss=0.3027 | ce=0.2173 | ent=0.0000 | center=0.8542 | val_loss=0.0913 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9415 | val_dqn_proxy_expanded5=0.9249

Epoch 012 | train_loss=0.2975 | ce=0.2139 | ent=0.0000 | center=0.8354 | val_loss=0.0896 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9442 | val_dqn_proxy_expanded5=0.9369

Epoch 013 | train_loss=0.2959 | ce=0.2145 | ent=0.0000 | center=0.8137 | val_loss=0.0887 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9501 | val_dqn_proxy_expanded5=0.9337

Epoch 014 | train_loss=0.2942 | ce=0.2148 | ent=0.0000 | center=0.7943 | val_loss=0.0791 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9377 | val_dqn_proxy_expanded5=0.9279

Epoch 015 | train_loss=0.2865 | ce=0.2089 | ent=0.0000 | center=0.7759 | val_loss=0.0807 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9151 | val_dqn_proxy_expanded5=0.9016

Epoch 016 | train_loss=0.2840 | ce=0.2085 | ent=0.0000 | center=0.7549 | val_loss=0.0840 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9341 | val_dqn_proxy_expanded5=0.9138

Epoch 017 | train_loss=0.2807 | ce=0.2068 | ent=0.0000 | center=0.7396 | val_loss=0.0701 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9199 | val_dqn_proxy_expanded5=0.9027

Epoch 018 | train_loss=0.2697 | ce=0.1976 | ent=0.0000 | center=0.7206 | val_loss=0.0664 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9793 | val_dqn_proxy_expanded5=0.9693

Epoch 019 | train_loss=0.2665 | ce=0.1961 | ent=0.0000 | center=0.7043 | val_loss=0.0644 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9444 | val_dqn_proxy_expanded5=0.9151

Epoch 020 | train_loss=0.2636 | ce=0.1948 | ent=0.0000 | center=0.6873 | val_loss=0.0574 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9468 | val_dqn_proxy_expanded5=0.9121

Epoch 021 | train_loss=0.2598 | ce=0.1926 | ent=0.0000 | center=0.6726 | val_loss=0.0672 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9710 | val_dqn_proxy_expanded5=0.9402

Epoch 022 | train_loss=0.2593 | ce=0.1937 | ent=0.0000 | center=0.6559 | val_loss=0.0592 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9637 | val_dqn_proxy_expanded5=0.9223

Epoch 023 | train_loss=0.2554 | ce=0.1913 | ent=0.0000 | center=0.6408 | val_loss=0.0616 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9730 | val_dqn_proxy_expanded5=0.9393

Epoch 024 | train_loss=0.2545 | ce=0.1920 | ent=0.0000 | center=0.6251 | val_loss=0.0603 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9526 | val_dqn_proxy_expanded5=0.9115

Epoch 025 | train_loss=0.2520 | ce=0.1910 | ent=0.0000 | center=0.6101 | val_loss=0.0614 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9760 | val_dqn_proxy_expanded5=0.9332

Epoch 026 | train_loss=0.2507 | ce=0.1911 | ent=0.0000 | center=0.5958 | val_loss=0.0588 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9172 | val_dqn_proxy_expanded5=0.8785

Epoch 027 | train_loss=0.2483 | ce=0.1901 | ent=0.0000 | center=0.5829 | val_loss=0.0619 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9548 | val_dqn_proxy_expanded5=0.9077

Epoch 028 | train_loss=0.2470 | ce=0.1895 | ent=0.0000 | center=0.5755 | val_loss=0.0603 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9460 | val_dqn_proxy_expanded5=0.9041

Epoch 029 | train_loss=0.2467 | ce=0.1897 | ent=0.0000 | center=0.5698 | val_loss=0.0611 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9111 | val_dqn_proxy_expanded5=0.8730

Epoch 030 | train_loss=0.2435 | ce=0.1873 | ent=0.0000 | center=0.5624 | val_loss=0.0628 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9594 | val_dqn_proxy_expanded5=0.9105

Epoch 031 | train_loss=0.2438 | ce=0.1882 | ent=0.0000 | center=0.5560 | val_loss=0.0571 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9494 | val_dqn_proxy_expanded5=0.9106

Epoch 032 | train_loss=0.2419 | ce=0.1868 | ent=0.0000 | center=0.5515 | val_loss=0.0616 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9862 | val_dqn_proxy_expanded5=0.9503

Epoch 033 | train_loss=0.2425 | ce=0.1881 | ent=0.0000 | center=0.5442 | val_loss=0.0619 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9638 | val_dqn_proxy_expanded5=0.9181

Epoch 034 | train_loss=0.2427 | ce=0.1890 | ent=0.0000 | center=0.5373 | val_loss=0.0566 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9459 | val_dqn_proxy_expanded5=0.9025

Epoch 035 | train_loss=0.2425 | ce=0.1892 | ent=0.0000 | center=0.5329 | val_loss=0.0643 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9422 | val_dqn_proxy_expanded5=0.9010

Epoch 036 | train_loss=0.2398 | ce=0.1871 | ent=0.0000 | center=0.5270 | val_loss=0.0617 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9678 | val_dqn_proxy_expanded5=0.9189

Epoch 037 | train_loss=0.2396 | ce=0.1878 | ent=0.0000 | center=0.5182 | val_loss=0.0603 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9506 | val_dqn_proxy_expanded5=0.9104

Epoch 038 | train_loss=0.2409 | ce=0.1895 | ent=0.0000 | center=0.5142 | val_loss=0.0610 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9725 | val_dqn_proxy_expanded5=0.9295

Epoch 039 | train_loss=0.2386 | ce=0.1876 | ent=0.0000 | center=0.5104 | val_loss=0.0653 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9819 | val_dqn_proxy_expanded5=0.9296

Epoch 040 | train_loss=0.2384 | ce=0.1882 | ent=0.0000 | center=0.5027 | val_loss=0.0583 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9376 | val_dqn_proxy_expanded5=0.8942

Epoch 041 | train_loss=0.2376 | ce=0.1879 | ent=0.0000 | center=0.4970 | val_loss=0.0614 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9336 | val_dqn_proxy_expanded5=0.8844

Epoch 042 | train_loss=0.2377 | ce=0.1883 | ent=0.0000 | center=0.4940 | val_loss=0.0614 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9551 | val_dqn_proxy_expanded5=0.9049

Epoch 043 | train_loss=0.2363 | ce=0.1873 | ent=0.0000 | center=0.4898 | val_loss=0.0601 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9814 | val_dqn_proxy_expanded5=0.9260

Epoch 044 | train_loss=0.2354 | ce=0.1869 | ent=0.0000 | center=0.4857 | val_loss=0.0603 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9615 | val_dqn_proxy_expanded5=0.9177

Epoch 045 | train_loss=0.2336 | ce=0.1850 | ent=0.0000 | center=0.4856 | val_loss=0.0629 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9244 | val_dqn_proxy_expanded5=0.8759

Epoch 046 | train_loss=0.2365 | ce=0.1883 | ent=0.0000 | center=0.4820 | val_loss=0.0624 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9623 | val_dqn_proxy_expanded5=0.9096

Epoch 047 | train_loss=0.2367 | ce=0.1886 | ent=0.0000 | center=0.4806 | val_loss=0.0607 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9466 | val_dqn_proxy_expanded5=0.9031
Early stopping at epoch 47 (best epoch: 32)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
31,ref_base_ent005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-43_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
23,ref_base_drop050_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-25_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
11,ref_base_ls002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
33,ref_base_ent010_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-46_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
15,ref_base_ls000_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-04_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
41,ref_pms_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-12_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,ref_base_ls000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-59_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
47,ref_pms_ent000_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-28_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
39,ref_base_lr2e4_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-07_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
8,ref_base_ls002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-47_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,ref_base_ls000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-56_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
17,ref_base_drop040_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-07_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
29,ref_base_ent005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,ref_base_ls002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-49_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
37,ref_base_lr2e4_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-00_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
43,ref_pms_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-19_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
45,ref_pms_ent000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-23_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
25,ref_base_ent002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-28_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
24,ref_base_ent002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-26_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
19,ref_base_drop040_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-11_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
32,ref_base_ent010_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-45_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
5,ref_base_ls005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,ref_base_ls005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-45_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
27,ref_base_ent002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
38,ref_base_lr2e4_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-04_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,ref_base_ls005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-42_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,ref_base_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
35,ref_base_ent010_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
21,ref_base_drop050_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-18_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
20,ref_base_drop050_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-14_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
42,ref_pms_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-16_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
28,ref_base_ent005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-35_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,ref_base_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-29_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
46,ref_pms_ent000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-25_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
22,ref_base_drop050_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-21_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
44,ref_pms_ent000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/23-22_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
34,ref_base_ent010_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-52_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
36,ref_base_lr2e4_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-57_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,ref_base_ls005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-36_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
26,ref_base_ent002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-31_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
40,ref_pms_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/23-08_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
18,ref_base_drop040_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-09_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
30,ref_base_ent005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-41_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
16,ref_base_drop040_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-06_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
10,ref_base_ls002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-53_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
14,ref_base_ls000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-02_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"

================================================================================
Running experiment 49/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "plateau",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0001,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": 1.0,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_pms_ent002",
  "lr": 0.0001,
  "label_smoothing": 0.05,
  "entropy_loss_weight": 0.02,
  "mlp_dropout": 0.5,
  "unknown_pas": [
    "PA2"
  ],
  "run_name": "ref_pms_ent002_unkPA2_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.9621 | ce=0.8333 | ent=0.9814 | center=1.0913 | val_loss=0.3392 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7436 | val_dqn_proxy_expanded5=0.7324

Epoch 002 | train_loss=0.5061 | ce=0.3595 | ent=0.4534 | center=1.3751 | val_loss=0.1491 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8441 | val_dqn_proxy_expanded5=0.8441

Epoch 003 | train_loss=0.4191 | ce=0.2863 | ent=0.3379 | center=1.2601 | val_loss=0.1177 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6703 | val_dqn_proxy_expanded5=0.7151

Epoch 004 | train_loss=0.3975 | ce=0.2742 | ent=0.3046 | center=1.1717 | val_loss=0.1172 | val_acc=0.9778 | val_macro_f1=0.9779 | val_dqn_proxy_softmax3=0.6049 | val_dqn_proxy_expanded5=0.6868

Epoch 005 | train_loss=0.3809 | ce=0.2646 | ent=0.2864 | center=1.1060 | val_loss=0.1085 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8608 | val_dqn_proxy_expanded5=0.8600

Epoch 006 | train_loss=0.3708 | ce=0.2598 | ent=0.2765 | center=1.0542 | val_loss=0.1020 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6696 | val_dqn_proxy_expanded5=0.7159

Epoch 007 | train_loss=0.3610 | ce=0.2544 | ent=0.2644 | center=1.0128 | val_loss=0.0961 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6627 | val_dqn_proxy_expanded5=0.7363

Epoch 008 | train_loss=0.3511 | ce=0.2485 | ent=0.2605 | center=0.9737 | val_loss=0.0976 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7119 | val_dqn_proxy_expanded5=0.7106

Epoch 009 | train_loss=0.3500 | ce=0.2506 | ent=0.2573 | center=0.9417 | val_loss=0.1030 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6536 | val_dqn_proxy_expanded5=0.6692

Epoch 010 | train_loss=0.3357 | ce=0.2390 | ent=0.2540 | center=0.9158 | val_loss=0.0994 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6644 | val_dqn_proxy_expanded5=0.7269

Epoch 011 | train_loss=0.3379 | ce=0.2431 | ent=0.2456 | center=0.8987 | val_loss=0.1065 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8651 | val_dqn_proxy_expanded5=0.8639

Epoch 012 | train_loss=0.3244 | ce=0.2326 | ent=0.2504 | center=0.8683 | val_loss=0.0943 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8075 | val_dqn_proxy_expanded5=0.8174

Epoch 013 | train_loss=0.3199 | ce=0.2304 | ent=0.2326 | center=0.8490 | val_loss=0.0830 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6770 | val_dqn_proxy_expanded5=0.6897

Epoch 014 | train_loss=0.3225 | ce=0.2349 | ent=0.2354 | center=0.8287 | val_loss=0.0902 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.5828 | val_dqn_proxy_expanded5=0.6673

Epoch 015 | train_loss=0.3089 | ce=0.2234 | ent=0.2345 | center=0.8086 | val_loss=0.0727 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7857 | val_dqn_proxy_expanded5=0.7868

Epoch 016 | train_loss=0.3088 | ce=0.2253 | ent=0.2231 | center=0.7908 | val_loss=0.0686 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6676 | val_dqn_proxy_expanded5=0.7160

Epoch 017 | train_loss=0.3111 | ce=0.2288 | ent=0.2309 | center=0.7772 | val_loss=0.0749 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6343 | val_dqn_proxy_expanded5=0.6962

Epoch 018 | train_loss=0.3029 | ce=0.2223 | ent=0.2264 | center=0.7608 | val_loss=0.0883 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8779 | val_dqn_proxy_expanded5=0.8822

Epoch 019 | train_loss=0.2939 | ce=0.2148 | ent=0.2218 | center=0.7465 | val_loss=0.0643 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7472 | val_dqn_proxy_expanded5=0.7283

Epoch 020 | train_loss=0.2874 | ce=0.2099 | ent=0.2248 | center=0.7299 | val_loss=0.0601 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8259 | val_dqn_proxy_expanded5=0.8053

Epoch 021 | train_loss=0.2842 | ce=0.2082 | ent=0.2101 | center=0.7176 | val_loss=0.0654 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.5549 | val_dqn_proxy_expanded5=0.6865

Epoch 022 | train_loss=0.2798 | ce=0.2057 | ent=0.2111 | center=0.6991 | val_loss=0.0575 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7613 | val_dqn_proxy_expanded5=0.7503

Epoch 023 | train_loss=0.2729 | ce=0.2001 | ent=0.2037 | center=0.6873 | val_loss=0.0620 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7290 | val_dqn_proxy_expanded5=0.7212

Epoch 024 | train_loss=0.2719 | ce=0.2007 | ent=0.1988 | center=0.6723 | val_loss=0.0595 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6850 | val_dqn_proxy_expanded5=0.7226

Epoch 025 | train_loss=0.2695 | ce=0.1998 | ent=0.2058 | center=0.6562 | val_loss=0.0565 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6846 | val_dqn_proxy_expanded5=0.7260

Epoch 026 | train_loss=0.2685 | ce=0.2000 | ent=0.1958 | center=0.6461 | val_loss=0.0640 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7875 | val_dqn_proxy_expanded5=0.7646

Epoch 027 | train_loss=0.2638 | ce=0.1967 | ent=0.2014 | center=0.6299 | val_loss=0.0588 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7876 | val_dqn_proxy_expanded5=0.7635

Epoch 028 | train_loss=0.2655 | ce=0.1998 | ent=0.1964 | center=0.6174 | val_loss=0.0657 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7419 | val_dqn_proxy_expanded5=0.7381

Epoch 029 | train_loss=0.2648 | ce=0.2001 | ent=0.1970 | center=0.6076 | val_loss=0.0640 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6681 | val_dqn_proxy_expanded5=0.7100

Epoch 030 | train_loss=0.2619 | ce=0.1985 | ent=0.1949 | center=0.5956 | val_loss=0.0604 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.5544 | val_dqn_proxy_expanded5=0.6967

Epoch 031 | train_loss=0.2624 | ce=0.1999 | ent=0.1993 | center=0.5846 | val_loss=0.0648 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8432 | val_dqn_proxy_expanded5=0.8217

Epoch 032 | train_loss=0.2600 | ce=0.1987 | ent=0.1945 | center=0.5747 | val_loss=0.0616 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7959 | val_dqn_proxy_expanded5=0.7753

Epoch 033 | train_loss=0.2566 | ce=0.1959 | ent=0.1952 | center=0.5683 | val_loss=0.0609 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7558 | val_dqn_proxy_expanded5=0.7469
Early stopping at epoch 33 (best epoch: 18)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
31,ref_base_ent005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-43_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
23,ref_base_drop050_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-25_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
11,ref_base_ls002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
33,ref_base_ent010_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-46_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
15,ref_base_ls000_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-04_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
41,ref_pms_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-12_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,ref_base_ls000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-59_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
47,ref_pms_ent000_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-28_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
39,ref_base_lr2e4_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-07_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
8,ref_base_ls002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-47_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,ref_base_ls000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-56_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
17,ref_base_drop040_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-07_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
29,ref_base_ent005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,ref_base_ls002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-49_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
37,ref_base_lr2e4_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-00_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
43,ref_pms_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-19_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
45,ref_pms_ent000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-23_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
25,ref_base_ent002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-28_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
24,ref_base_ent002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-26_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
19,ref_base_drop040_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-11_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
32,ref_base_ent010_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-45_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
5,ref_base_ls005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,ref_base_ls005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-45_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
27,ref_base_ent002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
38,ref_base_lr2e4_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-04_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,ref_base_ls005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-42_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,ref_base_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
35,ref_base_ent010_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
21,ref_base_drop050_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-18_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
20,ref_base_drop050_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-14_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
42,ref_pms_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-16_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
28,ref_base_ent005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-35_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,ref_base_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-29_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
46,ref_pms_ent000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-25_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
22,ref_base_drop050_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-21_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
44,ref_pms_ent000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/23-22_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
48,ref_pms_ent002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/23-32_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
34,ref_base_ent010_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-52_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
36,ref_base_lr2e4_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-57_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,ref_base_ls005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-36_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
26,ref_base_ent002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-31_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
40,ref_pms_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/23-08_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
18,ref_base_drop040_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-09_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
30,ref_base_ent005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-41_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
16,ref_base_drop040_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-06_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
10,ref_base_ls002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-53_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
14,ref_base_ls000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-02_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"

================================================================================
Running experiment 50/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "plateau",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0001,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": 1.0,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_pms_ent002",
  "lr": 0.0001,
  "label_smoothing": 0.05,
  "entropy_loss_weight": 0.02,
  "mlp_dropout": 0.5,
  "unknown_pas": [
    "PA3"
  ],
  "run_name": "ref_pms_ent002_unkPA3_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=1.0130 | ce=0.8908 | ent=1.0093 | center=1.0198 | val_loss=0.4413 | val_acc=0.8667 | val_macro_f1=0.8633 | val_dqn_proxy_softmax3=0.7043 | val_dqn_proxy_expanded5=0.7512

Epoch 002 | train_loss=0.6002 | ce=0.4571 | ent=0.5619 | center=1.3188 | val_loss=0.2060 | val_acc=0.9370 | val_macro_f1=0.9373 | val_dqn_proxy_softmax3=0.8798 | val_dqn_proxy_expanded5=0.8346

Epoch 003 | train_loss=0.4984 | ce=0.3633 | ent=0.4312 | center=1.2646 | val_loss=0.1627 | val_acc=0.9481 | val_macro_f1=0.9484 | val_dqn_proxy_softmax3=0.9152 | val_dqn_proxy_expanded5=0.8768

Epoch 004 | train_loss=0.4670 | ce=0.3417 | ent=0.3795 | center=1.1772 | val_loss=0.1303 | val_acc=0.9778 | val_macro_f1=0.9779 | val_dqn_proxy_softmax3=0.9499 | val_dqn_proxy_expanded5=0.9162

Epoch 005 | train_loss=0.4256 | ce=0.3056 | ent=0.3464 | center=1.1313 | val_loss=0.1263 | val_acc=0.9667 | val_macro_f1=0.9667 | val_dqn_proxy_softmax3=0.9185 | val_dqn_proxy_expanded5=0.8953

Epoch 006 | train_loss=0.3978 | ce=0.2849 | ent=0.3216 | center=1.0649 | val_loss=0.1130 | val_acc=0.9741 | val_macro_f1=0.9741 | val_dqn_proxy_softmax3=0.9345 | val_dqn_proxy_expanded5=0.9196

Epoch 007 | train_loss=0.3988 | ce=0.2894 | ent=0.3093 | center=1.0318 | val_loss=0.0956 | val_acc=0.9778 | val_macro_f1=0.9779 | val_dqn_proxy_softmax3=0.9155 | val_dqn_proxy_expanded5=0.9009

Epoch 008 | train_loss=0.3879 | ce=0.2837 | ent=0.3151 | center=0.9788 | val_loss=0.0958 | val_acc=0.9704 | val_macro_f1=0.9705 | val_dqn_proxy_softmax3=0.9492 | val_dqn_proxy_expanded5=0.9280

Epoch 009 | train_loss=0.3704 | ce=0.2698 | ent=0.2934 | center=0.9472 | val_loss=0.0985 | val_acc=0.9667 | val_macro_f1=0.9666 | val_dqn_proxy_softmax3=0.9589 | val_dqn_proxy_expanded5=0.9346

Epoch 010 | train_loss=0.3506 | ce=0.2529 | ent=0.2766 | center=0.9222 | val_loss=0.1004 | val_acc=0.9704 | val_macro_f1=0.9703 | val_dqn_proxy_softmax3=0.9769 | val_dqn_proxy_expanded5=0.9445

Epoch 011 | train_loss=0.3553 | ce=0.2607 | ent=0.2743 | center=0.8917 | val_loss=0.0973 | val_acc=0.9704 | val_macro_f1=0.9704 | val_dqn_proxy_softmax3=0.9166 | val_dqn_proxy_expanded5=0.9104

Epoch 012 | train_loss=0.3450 | ce=0.2533 | ent=0.2782 | center=0.8613 | val_loss=0.0958 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.9633 | val_dqn_proxy_expanded5=0.9213

Epoch 013 | train_loss=0.3373 | ce=0.2475 | ent=0.2680 | center=0.8446 | val_loss=0.1009 | val_acc=0.9704 | val_macro_f1=0.9703 | val_dqn_proxy_softmax3=0.9496 | val_dqn_proxy_expanded5=0.9026

Epoch 014 | train_loss=0.3224 | ce=0.2348 | ent=0.2565 | center=0.8244 | val_loss=0.0701 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9754 | val_dqn_proxy_expanded5=0.9266

Epoch 015 | train_loss=0.3129 | ce=0.2267 | ent=0.2483 | center=0.8120 | val_loss=0.0729 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9646 | val_dqn_proxy_expanded5=0.9278

Epoch 016 | train_loss=0.3125 | ce=0.2274 | ent=0.2432 | center=0.8020 | val_loss=0.0870 | val_acc=0.9741 | val_macro_f1=0.9740 | val_dqn_proxy_softmax3=0.9520 | val_dqn_proxy_expanded5=0.9297

Epoch 017 | train_loss=0.3153 | ce=0.2311 | ent=0.2496 | center=0.7920 | val_loss=0.0652 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9775 | val_dqn_proxy_expanded5=0.9662

Epoch 018 | train_loss=0.3077 | ce=0.2250 | ent=0.2450 | center=0.7775 | val_loss=0.0674 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9683 | val_dqn_proxy_expanded5=0.9248

Epoch 019 | train_loss=0.3082 | ce=0.2269 | ent=0.2522 | center=0.7626 | val_loss=0.0649 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9860 | val_dqn_proxy_expanded5=0.9408

Epoch 020 | train_loss=0.2985 | ce=0.2180 | ent=0.2346 | center=0.7583 | val_loss=0.0542 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9765 | val_dqn_proxy_expanded5=0.9535

Epoch 021 | train_loss=0.2978 | ce=0.2182 | ent=0.2334 | center=0.7493 | val_loss=0.0618 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9826 | val_dqn_proxy_expanded5=0.9353

Epoch 022 | train_loss=0.2880 | ce=0.2096 | ent=0.2249 | center=0.7392 | val_loss=0.0542 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9701 | val_dqn_proxy_expanded5=0.9509

Epoch 023 | train_loss=0.2925 | ce=0.2151 | ent=0.2296 | center=0.7275 | val_loss=0.0593 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9774 | val_dqn_proxy_expanded5=0.9446

Epoch 024 | train_loss=0.2879 | ce=0.2114 | ent=0.2268 | center=0.7196 | val_loss=0.0677 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9844 | val_dqn_proxy_expanded5=0.9666

Epoch 025 | train_loss=0.2932 | ce=0.2179 | ent=0.2270 | center=0.7080 | val_loss=0.0466 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9721 | val_dqn_proxy_expanded5=0.9291

Epoch 026 | train_loss=0.2884 | ce=0.2139 | ent=0.2253 | center=0.6998 | val_loss=0.0522 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9765 | val_dqn_proxy_expanded5=0.9293

Epoch 027 | train_loss=0.2835 | ce=0.2099 | ent=0.2238 | center=0.6905 | val_loss=0.0531 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9779 | val_dqn_proxy_expanded5=0.9390

Epoch 028 | train_loss=0.2810 | ce=0.2081 | ent=0.2224 | center=0.6849 | val_loss=0.0547 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9708 | val_dqn_proxy_expanded5=0.9313

Epoch 029 | train_loss=0.2779 | ce=0.2061 | ent=0.2184 | center=0.6741 | val_loss=0.0611 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9796 | val_dqn_proxy_expanded5=0.9375

Epoch 030 | train_loss=0.2773 | ce=0.2066 | ent=0.2193 | center=0.6628 | val_loss=0.0458 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9872 | val_dqn_proxy_expanded5=0.9423

Epoch 031 | train_loss=0.2760 | ce=0.2060 | ent=0.2090 | center=0.6582 | val_loss=0.0529 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9789 | val_dqn_proxy_expanded5=0.9509

Epoch 032 | train_loss=0.2787 | ce=0.2091 | ent=0.2204 | center=0.6520 | val_loss=0.0515 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9784 | val_dqn_proxy_expanded5=0.9419

Epoch 033 | train_loss=0.2859 | ce=0.2173 | ent=0.2173 | center=0.6426 | val_loss=0.0458 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9823 | val_dqn_proxy_expanded5=0.9380

Epoch 034 | train_loss=0.2740 | ce=0.2059 | ent=0.2089 | center=0.6389 | val_loss=0.0405 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9717 | val_dqn_proxy_expanded5=0.9220

Epoch 035 | train_loss=0.2744 | ce=0.2076 | ent=0.2122 | center=0.6248 | val_loss=0.0622 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9794 | val_dqn_proxy_expanded5=0.9523

Epoch 036 | train_loss=0.2742 | ce=0.2079 | ent=0.2112 | center=0.6205 | val_loss=0.0519 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9847 | val_dqn_proxy_expanded5=0.9470

Epoch 037 | train_loss=0.2717 | ce=0.2061 | ent=0.2120 | center=0.6129 | val_loss=0.0470 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9818 | val_dqn_proxy_expanded5=0.9344

Epoch 038 | train_loss=0.2653 | ce=0.2004 | ent=0.2065 | center=0.6077 | val_loss=0.0488 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9852 | val_dqn_proxy_expanded5=0.9526

Epoch 039 | train_loss=0.2712 | ce=0.2071 | ent=0.2132 | center=0.5977 | val_loss=0.0536 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9698 | val_dqn_proxy_expanded5=0.9117

Epoch 040 | train_loss=0.2686 | ce=0.2050 | ent=0.2058 | center=0.5954 | val_loss=0.0440 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9837 | val_dqn_proxy_expanded5=0.9344

Epoch 041 | train_loss=0.2678 | ce=0.2048 | ent=0.2116 | center=0.5881 | val_loss=0.0417 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9850 | val_dqn_proxy_expanded5=0.9359

Epoch 042 | train_loss=0.2581 | ce=0.1953 | ent=0.2050 | center=0.5865 | val_loss=0.0414 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9818 | val_dqn_proxy_expanded5=0.9416

Epoch 043 | train_loss=0.2626 | ce=0.2002 | ent=0.1985 | center=0.5836 | val_loss=0.0371 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9830 | val_dqn_proxy_expanded5=0.9383

Epoch 044 | train_loss=0.2613 | ce=0.1996 | ent=0.1985 | center=0.5772 | val_loss=0.0423 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9817 | val_dqn_proxy_expanded5=0.9326

Epoch 045 | train_loss=0.2587 | ce=0.1974 | ent=0.2008 | center=0.5732 | val_loss=0.0434 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9855 | val_dqn_proxy_expanded5=0.9525
Early stopping at epoch 45 (best epoch: 30)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
31,ref_base_ent005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-43_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
23,ref_base_drop050_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-25_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
11,ref_base_ls002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
33,ref_base_ent010_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-46_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
15,ref_base_ls000_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-04_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
41,ref_pms_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-12_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,ref_base_ls000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-59_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
47,ref_pms_ent000_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-28_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
39,ref_base_lr2e4_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-07_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
8,ref_base_ls002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-47_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,ref_base_ls000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-56_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
17,ref_base_drop040_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-07_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
29,ref_base_ent005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,ref_base_ls002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-49_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
37,ref_base_lr2e4_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-00_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
49,ref_pms_ent002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-35_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
43,ref_pms_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-19_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
45,ref_pms_ent000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-23_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
25,ref_base_ent002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-28_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
24,ref_base_ent002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-26_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
19,ref_base_drop040_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-11_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
32,ref_base_ent010_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-45_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
5,ref_base_ls005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,ref_base_ls005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-45_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
27,ref_base_ent002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
38,ref_base_lr2e4_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-04_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,ref_base_ls005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-42_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,ref_base_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
35,ref_base_ent010_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
21,ref_base_drop050_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-18_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
20,ref_base_drop050_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-14_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
42,ref_pms_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-16_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
28,ref_base_ent005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-35_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,ref_base_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-29_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
46,ref_pms_ent000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-25_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
22,ref_base_drop050_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-21_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
44,ref_pms_ent000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/23-22_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
48,ref_pms_ent002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/23-32_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
34,ref_base_ent010_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-52_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
36,ref_base_lr2e4_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-57_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,ref_base_ls005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-36_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
26,ref_base_ent002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-31_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
40,ref_pms_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/23-08_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
18,ref_base_drop040_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-09_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
30,ref_base_ent005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-41_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
16,ref_base_drop040_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-06_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
10,ref_base_ls002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-53_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
14,ref_base_ls000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-02_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"

================================================================================
Running experiment 51/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "plateau",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0001,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": 1.0,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_pms_ent002",
  "lr": 0.0001,
  "label_smoothing": 0.05,
  "entropy_loss_weight": 0.02,
  "mlp_dropout": 0.5,
  "unknown_pas": [
    "PA4"
  ],
  "run_name": "ref_pms_ent002_unkPA4_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.9603 | ce=0.8439 | ent=0.9642 | center=0.9714 | val_loss=0.4122 | val_acc=0.8704 | val_macro_f1=0.8630 | val_dqn_proxy_softmax3=0.6751 | val_dqn_proxy_expanded5=0.6746

Epoch 002 | train_loss=0.5922 | ce=0.4521 | ent=0.5612 | center=1.2890 | val_loss=0.2946 | val_acc=0.9296 | val_macro_f1=0.9294 | val_dqn_proxy_softmax3=0.7466 | val_dqn_proxy_expanded5=0.7572

Epoch 003 | train_loss=0.5311 | ce=0.4015 | ent=0.4578 | center=1.2043 | val_loss=0.2300 | val_acc=0.9333 | val_macro_f1=0.9333 | val_dqn_proxy_softmax3=0.7402 | val_dqn_proxy_expanded5=0.7636

Epoch 004 | train_loss=0.4746 | ce=0.3545 | ent=0.4019 | center=1.1211 | val_loss=0.1787 | val_acc=0.9667 | val_macro_f1=0.9669 | val_dqn_proxy_softmax3=0.7434 | val_dqn_proxy_expanded5=0.7513

Epoch 005 | train_loss=0.4464 | ce=0.3332 | ent=0.3711 | center=1.0571 | val_loss=0.1636 | val_acc=0.9556 | val_macro_f1=0.9556 | val_dqn_proxy_softmax3=0.7545 | val_dqn_proxy_expanded5=0.7304

Epoch 006 | train_loss=0.4207 | ce=0.3126 | ent=0.3435 | center=1.0122 | val_loss=0.1589 | val_acc=0.9556 | val_macro_f1=0.9556 | val_dqn_proxy_softmax3=0.7421 | val_dqn_proxy_expanded5=0.7167

Epoch 007 | train_loss=0.3942 | ce=0.2898 | ent=0.3119 | center=0.9819 | val_loss=0.1514 | val_acc=0.9593 | val_macro_f1=0.9594 | val_dqn_proxy_softmax3=0.7501 | val_dqn_proxy_expanded5=0.7232

Epoch 008 | train_loss=0.3850 | ce=0.2845 | ent=0.3104 | center=0.9424 | val_loss=0.1514 | val_acc=0.9667 | val_macro_f1=0.9669 | val_dqn_proxy_softmax3=0.7461 | val_dqn_proxy_expanded5=0.7198

Epoch 009 | train_loss=0.3716 | ce=0.2738 | ent=0.2944 | center=0.9195 | val_loss=0.1281 | val_acc=0.9741 | val_macro_f1=0.9743 | val_dqn_proxy_softmax3=0.7602 | val_dqn_proxy_expanded5=0.7002

Epoch 010 | train_loss=0.3655 | ce=0.2709 | ent=0.2890 | center=0.8886 | val_loss=0.1405 | val_acc=0.9593 | val_macro_f1=0.9592 | val_dqn_proxy_softmax3=0.7552 | val_dqn_proxy_expanded5=0.7282

Epoch 011 | train_loss=0.3539 | ce=0.2623 | ent=0.2868 | center=0.8590 | val_loss=0.1220 | val_acc=0.9667 | val_macro_f1=0.9667 | val_dqn_proxy_softmax3=0.7584 | val_dqn_proxy_expanded5=0.7310

Epoch 012 | train_loss=0.3416 | ce=0.2524 | ent=0.2683 | center=0.8377 | val_loss=0.1438 | val_acc=0.9667 | val_macro_f1=0.9669 | val_dqn_proxy_softmax3=0.7541 | val_dqn_proxy_expanded5=0.7258

Epoch 013 | train_loss=0.3645 | ce=0.2776 | ent=0.2809 | center=0.8127 | val_loss=0.1001 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.7777 | val_dqn_proxy_expanded5=0.7445

Epoch 014 | train_loss=0.3250 | ce=0.2405 | ent=0.2618 | center=0.7929 | val_loss=0.0927 | val_acc=0.9778 | val_macro_f1=0.9779 | val_dqn_proxy_softmax3=0.8759 | val_dqn_proxy_expanded5=0.8041

Epoch 015 | train_loss=0.3203 | ce=0.2380 | ent=0.2540 | center=0.7722 | val_loss=0.0970 | val_acc=0.9741 | val_macro_f1=0.9741 | val_dqn_proxy_softmax3=0.9110 | val_dqn_proxy_expanded5=0.8522

Epoch 016 | train_loss=0.3094 | ce=0.2293 | ent=0.2456 | center=0.7520 | val_loss=0.0860 | val_acc=0.9704 | val_macro_f1=0.9704 | val_dqn_proxy_softmax3=0.9386 | val_dqn_proxy_expanded5=0.9056

Epoch 017 | train_loss=0.3198 | ce=0.2419 | ent=0.2503 | center=0.7287 | val_loss=0.0869 | val_acc=0.9667 | val_macro_f1=0.9669 | val_dqn_proxy_softmax3=0.9213 | val_dqn_proxy_expanded5=0.8980

Epoch 018 | train_loss=0.3094 | ce=0.2336 | ent=0.2380 | center=0.7108 | val_loss=0.0788 | val_acc=0.9741 | val_macro_f1=0.9740 | val_dqn_proxy_softmax3=0.9444 | val_dqn_proxy_expanded5=0.9421

Epoch 019 | train_loss=0.2952 | ce=0.2214 | ent=0.2398 | center=0.6906 | val_loss=0.0676 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9517 | val_dqn_proxy_expanded5=0.9311

Epoch 020 | train_loss=0.2960 | ce=0.2241 | ent=0.2371 | center=0.6715 | val_loss=0.0605 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9494 | val_dqn_proxy_expanded5=0.9085

Epoch 021 | train_loss=0.2942 | ce=0.2237 | ent=0.2279 | center=0.6593 | val_loss=0.0590 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9458 | val_dqn_proxy_expanded5=0.8660

Epoch 022 | train_loss=0.2785 | ce=0.2098 | ent=0.2265 | center=0.6415 | val_loss=0.0438 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.8886 | val_dqn_proxy_expanded5=0.8184

Epoch 023 | train_loss=0.2826 | ce=0.2150 | ent=0.2219 | center=0.6317 | val_loss=0.0446 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9326 | val_dqn_proxy_expanded5=0.8554

Epoch 024 | train_loss=0.2816 | ce=0.2161 | ent=0.2185 | center=0.6119 | val_loss=0.0579 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9543 | val_dqn_proxy_expanded5=0.8686

Epoch 025 | train_loss=0.2759 | ce=0.2115 | ent=0.2147 | center=0.6015 | val_loss=0.0544 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9663 | val_dqn_proxy_expanded5=0.8765

Epoch 026 | train_loss=0.2743 | ce=0.2113 | ent=0.2131 | center=0.5873 | val_loss=0.0472 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9116 | val_dqn_proxy_expanded5=0.8419

Epoch 027 | train_loss=0.2663 | ce=0.2048 | ent=0.2087 | center=0.5732 | val_loss=0.0837 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.8795 | val_dqn_proxy_expanded5=0.8224

Epoch 028 | train_loss=0.2745 | ce=0.2139 | ent=0.2144 | center=0.5628 | val_loss=0.0433 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.7738 | val_dqn_proxy_expanded5=0.7405

Epoch 029 | train_loss=0.2718 | ce=0.2122 | ent=0.2165 | center=0.5528 | val_loss=0.0378 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.7822 | val_dqn_proxy_expanded5=0.7461

Epoch 030 | train_loss=0.2673 | ce=0.2087 | ent=0.2090 | center=0.5441 | val_loss=0.0421 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.7807 | val_dqn_proxy_expanded5=0.7283

Epoch 031 | train_loss=0.2631 | ce=0.2057 | ent=0.2143 | center=0.5308 | val_loss=0.0631 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7618 | val_dqn_proxy_expanded5=0.7606

Epoch 032 | train_loss=0.2675 | ce=0.2111 | ent=0.2104 | center=0.5220 | val_loss=0.0421 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9142 | val_dqn_proxy_expanded5=0.8550

Epoch 033 | train_loss=0.2527 | ce=0.1973 | ent=0.2021 | center=0.5136 | val_loss=0.0469 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7744 | val_dqn_proxy_expanded5=0.7605

Epoch 034 | train_loss=0.2681 | ce=0.2137 | ent=0.2027 | center=0.5034 | val_loss=0.0482 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.7791 | val_dqn_proxy_expanded5=0.7342

Epoch 035 | train_loss=0.2560 | ce=0.2029 | ent=0.2040 | center=0.4908 | val_loss=0.0448 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.7727 | val_dqn_proxy_expanded5=0.7532

Epoch 036 | train_loss=0.2573 | ce=0.2048 | ent=0.2053 | center=0.4839 | val_loss=0.0485 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.7801 | val_dqn_proxy_expanded5=0.7475

Epoch 037 | train_loss=0.2559 | ce=0.2039 | ent=0.2005 | center=0.4801 | val_loss=0.0441 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.7845 | val_dqn_proxy_expanded5=0.7538

Epoch 038 | train_loss=0.2470 | ce=0.1959 | ent=0.1894 | center=0.4736 | val_loss=0.0492 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.7809 | val_dqn_proxy_expanded5=0.7663

Epoch 039 | train_loss=0.2492 | ce=0.1987 | ent=0.1930 | center=0.4671 | val_loss=0.0400 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.7854 | val_dqn_proxy_expanded5=0.7680

Epoch 040 | train_loss=0.2485 | ce=0.1983 | ent=0.1947 | center=0.4627 | val_loss=0.0493 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.7764 | val_dqn_proxy_expanded5=0.7546
Early stopping at epoch 40 (best epoch: 25)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
31,ref_base_ent005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-43_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
23,ref_base_drop050_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-25_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
11,ref_base_ls002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
33,ref_base_ent010_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-46_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
15,ref_base_ls000_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-04_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
41,ref_pms_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-12_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,ref_base_ls000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-59_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
47,ref_pms_ent000_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-28_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
39,ref_base_lr2e4_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-07_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
8,ref_base_ls002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-47_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,ref_base_ls000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-56_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
17,ref_base_drop040_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-07_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
29,ref_base_ent005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,ref_base_ls002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-49_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
37,ref_base_lr2e4_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-00_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
49,ref_pms_ent002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-35_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
43,ref_pms_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-19_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
45,ref_pms_ent000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-23_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
25,ref_base_ent002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-28_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
24,ref_base_ent002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-26_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
19,ref_base_drop040_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-11_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
32,ref_base_ent010_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-45_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
5,ref_base_ls005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,ref_base_ls005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-45_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
27,ref_base_ent002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
38,ref_base_lr2e4_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-04_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,ref_base_ls005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-42_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,ref_base_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
35,ref_base_ent010_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
21,ref_base_drop050_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-18_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
20,ref_base_drop050_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-14_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
42,ref_pms_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-16_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
28,ref_base_ent005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-35_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,ref_base_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-29_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
46,ref_pms_ent000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-25_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
22,ref_base_drop050_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-21_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
44,ref_pms_ent000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/23-22_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
48,ref_pms_ent002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/23-32_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
34,ref_base_ent010_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-52_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
36,ref_base_lr2e4_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-57_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,ref_base_ls005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-36_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
26,ref_base_ent002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-31_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
40,ref_pms_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/23-08_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
18,ref_base_drop040_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-09_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
30,ref_base_ent005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-41_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
50,ref_pms_ent002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-38_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
16,ref_base_drop040_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-06_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
10,ref_base_ls002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-53_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
14,ref_base_ls000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-02_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"

================================================================================
Running experiment 52/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "plateau",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0001,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": 1.0,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_pms_ent002",
  "lr": 0.0001,
  "label_smoothing": 0.05,
  "entropy_loss_weight": 0.02,
  "mlp_dropout": 0.5,
  "unknown_pas": [
    "PA8"
  ],
  "run_name": "ref_pms_ent002_unkPA8_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.9152 | ce=0.7877 | ent=0.9433 | center=1.0868 | val_loss=0.2195 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8451 | val_dqn_proxy_expanded5=0.8356

Epoch 002 | train_loss=0.4323 | ce=0.2867 | ent=0.3790 | center=1.3809 | val_loss=0.1218 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9335 | val_dqn_proxy_expanded5=0.9374

Epoch 003 | train_loss=0.3725 | ce=0.2431 | ent=0.2864 | center=1.2372 | val_loss=0.1160 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9543 | val_dqn_proxy_expanded5=0.9482

Epoch 004 | train_loss=0.3525 | ce=0.2336 | ent=0.2624 | center=1.1365 | val_loss=0.1123 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9648 | val_dqn_proxy_expanded5=0.9496

Epoch 005 | train_loss=0.3395 | ce=0.2270 | ent=0.2443 | center=1.0761 | val_loss=0.1092 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9567 | val_dqn_proxy_expanded5=0.9577

Epoch 006 | train_loss=0.3379 | ce=0.2311 | ent=0.2545 | center=1.0170 | val_loss=0.1082 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9436 | val_dqn_proxy_expanded5=0.9296

Epoch 007 | train_loss=0.3317 | ce=0.2288 | ent=0.2433 | center=0.9808 | val_loss=0.1104 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9711 | val_dqn_proxy_expanded5=0.9681

Epoch 008 | train_loss=0.3197 | ce=0.2211 | ent=0.2383 | center=0.9383 | val_loss=0.1003 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9477 | val_dqn_proxy_expanded5=0.9424

Epoch 009 | train_loss=0.3178 | ce=0.2224 | ent=0.2310 | center=0.9079 | val_loss=0.0993 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9675 | val_dqn_proxy_expanded5=0.9647

Epoch 010 | train_loss=0.3131 | ce=0.2204 | ent=0.2285 | center=0.8812 | val_loss=0.1004 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9466 | val_dqn_proxy_expanded5=0.9446

Epoch 011 | train_loss=0.3092 | ce=0.2195 | ent=0.2328 | center=0.8508 | val_loss=0.0967 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9606 | val_dqn_proxy_expanded5=0.9493

Epoch 012 | train_loss=0.3070 | ce=0.2191 | ent=0.2226 | center=0.8343 | val_loss=0.0949 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9696 | val_dqn_proxy_expanded5=0.9614

Epoch 013 | train_loss=0.2971 | ce=0.2121 | ent=0.2186 | center=0.8064 | val_loss=0.1000 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9301 | val_dqn_proxy_expanded5=0.9061

Epoch 014 | train_loss=0.2938 | ce=0.2109 | ent=0.2217 | center=0.7842 | val_loss=0.0862 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9617 | val_dqn_proxy_expanded5=0.9342

Epoch 015 | train_loss=0.2908 | ce=0.2096 | ent=0.2195 | center=0.7679 | val_loss=0.0742 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9522 | val_dqn_proxy_expanded5=0.9247

Epoch 016 | train_loss=0.2822 | ce=0.2032 | ent=0.2077 | center=0.7482 | val_loss=0.0643 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9683 | val_dqn_proxy_expanded5=0.9397

Epoch 017 | train_loss=0.2729 | ce=0.1959 | ent=0.2080 | center=0.7292 | val_loss=0.0568 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9606 | val_dqn_proxy_expanded5=0.9176

Epoch 018 | train_loss=0.2726 | ce=0.1973 | ent=0.2050 | center=0.7122 | val_loss=0.0654 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9789 | val_dqn_proxy_expanded5=0.9555

Epoch 019 | train_loss=0.2665 | ce=0.1931 | ent=0.1943 | center=0.6947 | val_loss=0.0616 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9697 | val_dqn_proxy_expanded5=0.9304

Epoch 020 | train_loss=0.2610 | ce=0.1895 | ent=0.1953 | center=0.6764 | val_loss=0.0610 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9731 | val_dqn_proxy_expanded5=0.9336

Epoch 021 | train_loss=0.2630 | ce=0.1931 | ent=0.1928 | center=0.6608 | val_loss=0.0587 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9667 | val_dqn_proxy_expanded5=0.9237

Epoch 022 | train_loss=0.2598 | ce=0.1917 | ent=0.1948 | center=0.6427 | val_loss=0.0583 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9796 | val_dqn_proxy_expanded5=0.9352

Epoch 023 | train_loss=0.2591 | ce=0.1918 | ent=0.1939 | center=0.6342 | val_loss=0.0541 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9841 | val_dqn_proxy_expanded5=0.9450

Epoch 024 | train_loss=0.2582 | ce=0.1924 | ent=0.1875 | center=0.6199 | val_loss=0.0713 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9274 | val_dqn_proxy_expanded5=0.8734

Epoch 025 | train_loss=0.2553 | ce=0.1910 | ent=0.1916 | center=0.6049 | val_loss=0.0581 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9326 | val_dqn_proxy_expanded5=0.8813

Epoch 026 | train_loss=0.2530 | ce=0.1901 | ent=0.1870 | center=0.5918 | val_loss=0.0592 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9464 | val_dqn_proxy_expanded5=0.8925

Epoch 027 | train_loss=0.2522 | ce=0.1904 | ent=0.1883 | center=0.5800 | val_loss=0.0628 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9391 | val_dqn_proxy_expanded5=0.8871

Epoch 028 | train_loss=0.2516 | ce=0.1911 | ent=0.1886 | center=0.5663 | val_loss=0.0572 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9873 | val_dqn_proxy_expanded5=0.9431

Epoch 029 | train_loss=0.2488 | ce=0.1897 | ent=0.1889 | center=0.5532 | val_loss=0.0565 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9620 | val_dqn_proxy_expanded5=0.9075

Epoch 030 | train_loss=0.2482 | ce=0.1902 | ent=0.1808 | center=0.5437 | val_loss=0.0616 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9547 | val_dqn_proxy_expanded5=0.8973

Epoch 031 | train_loss=0.2478 | ce=0.1902 | ent=0.1860 | center=0.5396 | val_loss=0.0592 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9540 | val_dqn_proxy_expanded5=0.8924

Epoch 032 | train_loss=0.2454 | ce=0.1886 | ent=0.1838 | center=0.5317 | val_loss=0.0580 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9552 | val_dqn_proxy_expanded5=0.8927

Epoch 033 | train_loss=0.2437 | ce=0.1875 | ent=0.1856 | center=0.5244 | val_loss=0.0584 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9414 | val_dqn_proxy_expanded5=0.8823

Epoch 034 | train_loss=0.2443 | ce=0.1887 | ent=0.1817 | center=0.5195 | val_loss=0.0571 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9493 | val_dqn_proxy_expanded5=0.8890

Epoch 035 | train_loss=0.2430 | ce=0.1881 | ent=0.1827 | center=0.5124 | val_loss=0.0572 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9601 | val_dqn_proxy_expanded5=0.8988

Epoch 036 | train_loss=0.2430 | ce=0.1884 | ent=0.1803 | center=0.5097 | val_loss=0.0587 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9407 | val_dqn_proxy_expanded5=0.8813

Epoch 037 | train_loss=0.2400 | ce=0.1858 | ent=0.1832 | center=0.5050 | val_loss=0.0554 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9747 | val_dqn_proxy_expanded5=0.9124

Epoch 038 | train_loss=0.2412 | ce=0.1872 | ent=0.1801 | center=0.5037 | val_loss=0.0584 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9365 | val_dqn_proxy_expanded5=0.8802

Epoch 039 | train_loss=0.2411 | ce=0.1875 | ent=0.1826 | center=0.4999 | val_loss=0.0590 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9573 | val_dqn_proxy_expanded5=0.8940

Epoch 040 | train_loss=0.2399 | ce=0.1865 | ent=0.1817 | center=0.4981 | val_loss=0.0580 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9787 | val_dqn_proxy_expanded5=0.9146

Epoch 041 | train_loss=0.2390 | ce=0.1861 | ent=0.1818 | center=0.4927 | val_loss=0.0577 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9436 | val_dqn_proxy_expanded5=0.8830

Epoch 042 | train_loss=0.2382 | ce=0.1853 | ent=0.1788 | center=0.4927 | val_loss=0.0571 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9538 | val_dqn_proxy_expanded5=0.8909

Epoch 043 | train_loss=0.2404 | ce=0.1876 | ent=0.1820 | center=0.4917 | val_loss=0.0570 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9507 | val_dqn_proxy_expanded5=0.8894
Early stopping at epoch 43 (best epoch: 28)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
31,ref_base_ent005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-43_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
23,ref_base_drop050_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-25_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
11,ref_base_ls002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
33,ref_base_ent010_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-46_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
15,ref_base_ls000_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-04_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
41,ref_pms_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-12_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,ref_base_ls000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-59_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
47,ref_pms_ent000_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-28_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
39,ref_base_lr2e4_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-07_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
8,ref_base_ls002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-47_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,ref_base_ls000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-56_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
51,ref_pms_ent002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-42_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
17,ref_base_drop040_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-07_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
29,ref_base_ent005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,ref_base_ls002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-49_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
37,ref_base_lr2e4_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-00_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
49,ref_pms_ent002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-35_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
43,ref_pms_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-19_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
45,ref_pms_ent000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-23_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
25,ref_base_ent002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-28_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
24,ref_base_ent002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-26_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
19,ref_base_drop040_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-11_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
32,ref_base_ent010_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-45_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
5,ref_base_ls005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,ref_base_ls005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-45_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
27,ref_base_ent002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
38,ref_base_lr2e4_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-04_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,ref_base_ls005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-42_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,ref_base_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
35,ref_base_ent010_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
21,ref_base_drop050_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-18_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
20,ref_base_drop050_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-14_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
42,ref_pms_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-16_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
28,ref_base_ent005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-35_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,ref_base_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-29_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
46,ref_pms_ent000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-25_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
22,ref_base_drop050_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-21_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
44,ref_pms_ent000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/23-22_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
48,ref_pms_ent002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/23-32_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
34,ref_base_ent010_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-52_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
36,ref_base_lr2e4_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-57_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,ref_base_ls005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-36_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
26,ref_base_ent002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-31_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
40,ref_pms_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/23-08_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
18,ref_base_drop040_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-09_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
30,ref_base_ent005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-41_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
50,ref_pms_ent002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-38_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
16,ref_base_drop040_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-06_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
10,ref_base_ls002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-53_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
14,ref_base_ls000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-02_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"

================================================================================
Running experiment 53/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "plateau",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0001,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": 1.0,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_pms_drop040",
  "lr": 0.0001,
  "label_smoothing": 0.05,
  "entropy_loss_weight": 0.05,
  "mlp_dropout": 0.4,
  "unknown_pas": [
    "PA2"
  ],
  "run_name": "ref_pms_drop040_unkPA2_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.9458 | ce=0.7917 | ent=0.9239 | center=1.0784 | val_loss=0.2520 | val_acc=0.9815 | val_macro_f1=0.9814 | val_dqn_proxy_softmax3=0.7400 | val_dqn_proxy_expanded5=0.7200

Epoch 002 | train_loss=0.4709 | ce=0.3283 | ent=0.3743 | center=1.2393 | val_loss=0.1549 | val_acc=0.9741 | val_macro_f1=0.9742 | val_dqn_proxy_softmax3=0.7352 | val_dqn_proxy_expanded5=0.7441

Epoch 003 | train_loss=0.3972 | ce=0.2733 | ent=0.2890 | center=1.0951 | val_loss=0.1119 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7541 | val_dqn_proxy_expanded5=0.7649

Epoch 004 | train_loss=0.3712 | ce=0.2576 | ent=0.2623 | center=1.0046 | val_loss=0.0979 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.5961 | val_dqn_proxy_expanded5=0.6646

Epoch 005 | train_loss=0.3524 | ce=0.2456 | ent=0.2429 | center=0.9465 | val_loss=0.0956 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.5996 | val_dqn_proxy_expanded5=0.6721

Epoch 006 | train_loss=0.3516 | ce=0.2500 | ent=0.2366 | center=0.8973 | val_loss=0.0970 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6535 | val_dqn_proxy_expanded5=0.7113

Epoch 007 | train_loss=0.3471 | ce=0.2489 | ent=0.2472 | center=0.8591 | val_loss=0.0923 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7746 | val_dqn_proxy_expanded5=0.8012

Epoch 008 | train_loss=0.3296 | ce=0.2353 | ent=0.2245 | center=0.8304 | val_loss=0.0940 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7083 | val_dqn_proxy_expanded5=0.7533

Epoch 009 | train_loss=0.3270 | ce=0.2357 | ent=0.2322 | center=0.7977 | val_loss=0.0850 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8486 | val_dqn_proxy_expanded5=0.8305

Epoch 010 | train_loss=0.3168 | ce=0.2281 | ent=0.2224 | center=0.7757 | val_loss=0.0814 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7219 | val_dqn_proxy_expanded5=0.7660

Epoch 011 | train_loss=0.3183 | ce=0.2321 | ent=0.2146 | center=0.7551 | val_loss=0.0796 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6643 | val_dqn_proxy_expanded5=0.7218

Epoch 012 | train_loss=0.3151 | ce=0.2310 | ent=0.2226 | center=0.7296 | val_loss=0.0768 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6394 | val_dqn_proxy_expanded5=0.6875

Epoch 013 | train_loss=0.3139 | ce=0.2317 | ent=0.2181 | center=0.7122 | val_loss=0.1021 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8182 | val_dqn_proxy_expanded5=0.8027

Epoch 014 | train_loss=0.3033 | ce=0.2236 | ent=0.2085 | center=0.6923 | val_loss=0.0762 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6507 | val_dqn_proxy_expanded5=0.7091

Epoch 015 | train_loss=0.2984 | ce=0.2211 | ent=0.2077 | center=0.6691 | val_loss=0.0700 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7483 | val_dqn_proxy_expanded5=0.7743

Epoch 016 | train_loss=0.2926 | ce=0.2170 | ent=0.2012 | center=0.6556 | val_loss=0.0664 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9206 | val_dqn_proxy_expanded5=0.9150

Epoch 017 | train_loss=0.2849 | ce=0.2112 | ent=0.2012 | center=0.6363 | val_loss=0.0613 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8273 | val_dqn_proxy_expanded5=0.8468

Epoch 018 | train_loss=0.2788 | ce=0.2065 | ent=0.1959 | center=0.6250 | val_loss=0.0599 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.5803 | val_dqn_proxy_expanded5=0.6529

Epoch 019 | train_loss=0.2696 | ce=0.1994 | ent=0.1919 | center=0.6055 | val_loss=0.0575 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8292 | val_dqn_proxy_expanded5=0.8441

Epoch 020 | train_loss=0.2683 | ce=0.1995 | ent=0.1875 | center=0.5947 | val_loss=0.0631 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6663 | val_dqn_proxy_expanded5=0.6888

Epoch 021 | train_loss=0.2665 | ce=0.1995 | ent=0.1827 | center=0.5783 | val_loss=0.0574 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8442 | val_dqn_proxy_expanded5=0.8469

Epoch 022 | train_loss=0.2656 | ce=0.2000 | ent=0.1889 | center=0.5615 | val_loss=0.0531 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7548 | val_dqn_proxy_expanded5=0.7791

Epoch 023 | train_loss=0.2592 | ce=0.1954 | ent=0.1768 | center=0.5495 | val_loss=0.0571 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7908 | val_dqn_proxy_expanded5=0.8061

Epoch 024 | train_loss=0.2595 | ce=0.1971 | ent=0.1802 | center=0.5343 | val_loss=0.0575 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8250 | val_dqn_proxy_expanded5=0.8280

Epoch 025 | train_loss=0.2590 | ce=0.1984 | ent=0.1752 | center=0.5188 | val_loss=0.0517 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6687 | val_dqn_proxy_expanded5=0.6720

Epoch 026 | train_loss=0.2574 | ce=0.1978 | ent=0.1775 | center=0.5073 | val_loss=0.0576 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8036 | val_dqn_proxy_expanded5=0.8072

Epoch 027 | train_loss=0.2546 | ce=0.1963 | ent=0.1764 | center=0.4948 | val_loss=0.0523 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7436 | val_dqn_proxy_expanded5=0.7436

Epoch 028 | train_loss=0.2571 | ce=0.1996 | ent=0.1761 | center=0.4866 | val_loss=0.0568 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7692 | val_dqn_proxy_expanded5=0.7663

Epoch 029 | train_loss=0.2550 | ce=0.1988 | ent=0.1747 | center=0.4741 | val_loss=0.0616 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7709 | val_dqn_proxy_expanded5=0.7492

Epoch 030 | train_loss=0.2487 | ce=0.1935 | ent=0.1755 | center=0.4640 | val_loss=0.0604 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9373 | val_dqn_proxy_expanded5=0.8891

Epoch 031 | train_loss=0.2500 | ce=0.1964 | ent=0.1734 | center=0.4495 | val_loss=0.0535 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8645 | val_dqn_proxy_expanded5=0.8448

Epoch 032 | train_loss=0.2493 | ce=0.1961 | ent=0.1764 | center=0.4435 | val_loss=0.0571 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7847 | val_dqn_proxy_expanded5=0.7611

Epoch 033 | train_loss=0.2488 | ce=0.1965 | ent=0.1722 | center=0.4369 | val_loss=0.0548 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6235 | val_dqn_proxy_expanded5=0.6256

Epoch 034 | train_loss=0.2471 | ce=0.1951 | ent=0.1732 | center=0.4330 | val_loss=0.0538 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6583 | val_dqn_proxy_expanded5=0.6686

Epoch 035 | train_loss=0.2477 | ce=0.1963 | ent=0.1716 | center=0.4279 | val_loss=0.0523 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7523 | val_dqn_proxy_expanded5=0.7390

Epoch 036 | train_loss=0.2440 | ce=0.1935 | ent=0.1674 | center=0.4214 | val_loss=0.0617 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.5734 | val_dqn_proxy_expanded5=0.6731

Epoch 037 | train_loss=0.2463 | ce=0.1965 | ent=0.1708 | center=0.4132 | val_loss=0.0542 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6920 | val_dqn_proxy_expanded5=0.6919

Epoch 038 | train_loss=0.2422 | ce=0.1922 | ent=0.1723 | center=0.4133 | val_loss=0.0550 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7722 | val_dqn_proxy_expanded5=0.7410

Epoch 039 | train_loss=0.2446 | ce=0.1949 | ent=0.1741 | center=0.4100 | val_loss=0.0536 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7426 | val_dqn_proxy_expanded5=0.7281

Epoch 040 | train_loss=0.2429 | ce=0.1937 | ent=0.1697 | center=0.4074 | val_loss=0.0531 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6143 | val_dqn_proxy_expanded5=0.6890

Epoch 041 | train_loss=0.2448 | ce=0.1957 | ent=0.1691 | center=0.4059 | val_loss=0.0550 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8261 | val_dqn_proxy_expanded5=0.7864

Epoch 042 | train_loss=0.2430 | ce=0.1944 | ent=0.1697 | center=0.4014 | val_loss=0.0529 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8232 | val_dqn_proxy_expanded5=0.7789

Epoch 043 | train_loss=0.2425 | ce=0.1942 | ent=0.1677 | center=0.3991 | val_loss=0.0547 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8397 | val_dqn_proxy_expanded5=0.7961

Epoch 044 | train_loss=0.2411 | ce=0.1931 | ent=0.1697 | center=0.3953 | val_loss=0.0548 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8247 | val_dqn_proxy_expanded5=0.7841

Epoch 045 | train_loss=0.2415 | ce=0.1936 | ent=0.1688 | center=0.3946 | val_loss=0.0552 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7967 | val_dqn_proxy_expanded5=0.7707
Early stopping at epoch 45 (best epoch: 30)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
31,ref_base_ent005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-43_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
23,ref_base_drop050_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-25_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
11,ref_base_ls002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
33,ref_base_ent010_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-46_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
15,ref_base_ls000_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-04_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
41,ref_pms_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-12_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,ref_base_ls000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-59_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
47,ref_pms_ent000_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-28_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
39,ref_base_lr2e4_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-07_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
8,ref_base_ls002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-47_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
12,ref_base_ls000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-56_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
51,ref_pms_ent002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-42_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
17,ref_base_drop040_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-07_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
29,ref_base_ent005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,ref_base_ls002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-49_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
37,ref_base_lr2e4_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-00_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
49,ref_pms_ent002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-35_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
43,ref_pms_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-19_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
45,ref_pms_ent000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-23_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
25,ref_base_ent002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-28_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
24,ref_base_ent002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-26_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
19,ref_base_drop040_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-11_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
32,ref_base_ent010_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-45_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
5,ref_base_ls005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,ref_base_ls005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-45_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
27,ref_base_ent002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
38,ref_base_lr2e4_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-04_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,ref_base_ls005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-42_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,ref_base_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
35,ref_base_ent010_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
21,ref_base_drop050_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-18_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
20,ref_base_drop050_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-14_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
42,ref_pms_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-16_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
28,ref_base_ent005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-35_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,ref_base_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-29_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
46,ref_pms_ent000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-25_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
22,ref_base_drop050_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-21_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
52,ref_pms_drop040_unkPA2_c16384_seed0,results_pa_confmanifold_refined/23-45_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
44,ref_pms_ent000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/23-22_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
48,ref_pms_ent002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/23-32_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
34,ref_base_ent010_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-52_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
36,ref_base_lr2e4_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-57_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,ref_base_ls005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-36_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
26,ref_base_ent002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-31_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
40,ref_pms_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/23-08_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
18,ref_base_drop040_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-09_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
30,ref_base_ent005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-41_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
50,ref_pms_ent002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-38_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
16,ref_base_drop040_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-06_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
10,ref_base_ls002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-53_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
14,ref_base_ls000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-02_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"

================================================================================
Running experiment 54/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "plateau",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0001,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": 1.0,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_pms_drop040",
  "lr": 0.0001,
  "label_smoothing": 0.05,
  "entropy_loss_weight": 0.05,
  "mlp_dropout": 0.4,
  "unknown_pas": [
    "PA3"
  ],
  "run_name": "ref_pms_drop040_unkPA3_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.9441 | ce=0.8008 | ent=0.9418 | center=0.9622 | val_loss=0.3036 | val_acc=0.9259 | val_macro_f1=0.9253 | val_dqn_proxy_softmax3=0.7865 | val_dqn_proxy_expanded5=0.7990

Epoch 002 | train_loss=0.5180 | ce=0.3724 | ent=0.4475 | center=1.2322 | val_loss=0.1883 | val_acc=0.9259 | val_macro_f1=0.9263 | val_dqn_proxy_softmax3=0.7990 | val_dqn_proxy_expanded5=0.7947

Epoch 003 | train_loss=0.4643 | ce=0.3328 | ent=0.3664 | center=1.1316 | val_loss=0.1450 | val_acc=0.9444 | val_macro_f1=0.9448 | val_dqn_proxy_softmax3=0.8225 | val_dqn_proxy_expanded5=0.8178

Epoch 004 | train_loss=0.4366 | ce=0.3147 | ent=0.3305 | center=1.0538 | val_loss=0.1338 | val_acc=0.9593 | val_macro_f1=0.9591 | val_dqn_proxy_softmax3=0.9097 | val_dqn_proxy_expanded5=0.9058

Epoch 005 | train_loss=0.4196 | ce=0.3047 | ent=0.3155 | center=0.9912 | val_loss=0.1315 | val_acc=0.9481 | val_macro_f1=0.9484 | val_dqn_proxy_softmax3=0.9705 | val_dqn_proxy_expanded5=0.9392

Epoch 006 | train_loss=0.3978 | ce=0.2881 | ent=0.2939 | center=0.9506 | val_loss=0.1041 | val_acc=0.9704 | val_macro_f1=0.9706 | val_dqn_proxy_softmax3=0.6661 | val_dqn_proxy_expanded5=0.7456

Epoch 007 | train_loss=0.3845 | ce=0.2786 | ent=0.2753 | center=0.9205 | val_loss=0.0854 | val_acc=0.9815 | val_macro_f1=0.9816 | val_dqn_proxy_softmax3=0.9778 | val_dqn_proxy_expanded5=0.9683

Epoch 008 | train_loss=0.3767 | ce=0.2746 | ent=0.2950 | center=0.8739 | val_loss=0.1026 | val_acc=0.9630 | val_macro_f1=0.9628 | val_dqn_proxy_softmax3=0.9688 | val_dqn_proxy_expanded5=0.9597

Epoch 009 | train_loss=0.3696 | ce=0.2706 | ent=0.2665 | center=0.8569 | val_loss=0.1149 | val_acc=0.9704 | val_macro_f1=0.9703 | val_dqn_proxy_softmax3=0.9757 | val_dqn_proxy_expanded5=0.9694

Epoch 010 | train_loss=0.3576 | ce=0.2624 | ent=0.2579 | center=0.8237 | val_loss=0.1584 | val_acc=0.9407 | val_macro_f1=0.9403 | val_dqn_proxy_softmax3=0.8798 | val_dqn_proxy_expanded5=0.8905

Epoch 011 | train_loss=0.3534 | ce=0.2614 | ent=0.2449 | center=0.7976 | val_loss=0.1004 | val_acc=0.9741 | val_macro_f1=0.9740 | val_dqn_proxy_softmax3=0.9691 | val_dqn_proxy_expanded5=0.9542

Epoch 012 | train_loss=0.3387 | ce=0.2495 | ent=0.2502 | center=0.7664 | val_loss=0.0665 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9745 | val_dqn_proxy_expanded5=0.9597

Epoch 013 | train_loss=0.3220 | ce=0.2355 | ent=0.2354 | center=0.7477 | val_loss=0.0684 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9665 | val_dqn_proxy_expanded5=0.9616

Epoch 014 | train_loss=0.3132 | ce=0.2292 | ent=0.2299 | center=0.7249 | val_loss=0.0624 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9384 | val_dqn_proxy_expanded5=0.9073

Epoch 015 | train_loss=0.3178 | ce=0.2357 | ent=0.2332 | center=0.7046 | val_loss=0.0843 | val_acc=0.9741 | val_macro_f1=0.9741 | val_dqn_proxy_softmax3=0.9654 | val_dqn_proxy_expanded5=0.9279

Epoch 016 | train_loss=0.3086 | ce=0.2288 | ent=0.2205 | center=0.6877 | val_loss=0.0552 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9374 | val_dqn_proxy_expanded5=0.9073

Epoch 017 | train_loss=0.2908 | ce=0.2132 | ent=0.2126 | center=0.6691 | val_loss=0.0605 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9820 | val_dqn_proxy_expanded5=0.9632

Epoch 018 | train_loss=0.2991 | ce=0.2231 | ent=0.2234 | center=0.6484 | val_loss=0.0541 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9792 | val_dqn_proxy_expanded5=0.9563

Epoch 019 | train_loss=0.3016 | ce=0.2278 | ent=0.2170 | center=0.6300 | val_loss=0.0925 | val_acc=0.9704 | val_macro_f1=0.9703 | val_dqn_proxy_softmax3=0.9835 | val_dqn_proxy_expanded5=0.9507

Epoch 020 | train_loss=0.2887 | ce=0.2172 | ent=0.2041 | center=0.6132 | val_loss=0.0493 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9862 | val_dqn_proxy_expanded5=0.9455

Epoch 021 | train_loss=0.2806 | ce=0.2100 | ent=0.2083 | center=0.6013 | val_loss=0.0581 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9800 | val_dqn_proxy_expanded5=0.9555

Epoch 022 | train_loss=0.2950 | ce=0.2260 | ent=0.2070 | center=0.5864 | val_loss=0.0620 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9747 | val_dqn_proxy_expanded5=0.9385

Epoch 023 | train_loss=0.2855 | ce=0.2185 | ent=0.2041 | center=0.5674 | val_loss=0.0475 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9840 | val_dqn_proxy_expanded5=0.9433

Epoch 024 | train_loss=0.2830 | ce=0.2179 | ent=0.1972 | center=0.5527 | val_loss=0.0409 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9793 | val_dqn_proxy_expanded5=0.9441

Epoch 025 | train_loss=0.2712 | ce=0.2074 | ent=0.1971 | center=0.5389 | val_loss=0.0556 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9743 | val_dqn_proxy_expanded5=0.9367

Epoch 026 | train_loss=0.2620 | ce=0.2006 | ent=0.1853 | center=0.5219 | val_loss=0.0456 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9877 | val_dqn_proxy_expanded5=0.9550

Epoch 027 | train_loss=0.2683 | ce=0.2076 | ent=0.1923 | center=0.5109 | val_loss=0.0402 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9866 | val_dqn_proxy_expanded5=0.9378

Epoch 028 | train_loss=0.2696 | ce=0.2103 | ent=0.1945 | center=0.4955 | val_loss=0.0583 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9830 | val_dqn_proxy_expanded5=0.9410

Epoch 029 | train_loss=0.2682 | ce=0.2101 | ent=0.1923 | center=0.4844 | val_loss=0.0498 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9701 | val_dqn_proxy_expanded5=0.9271

Epoch 030 | train_loss=0.2667 | ce=0.2099 | ent=0.1874 | center=0.4742 | val_loss=0.0487 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9751 | val_dqn_proxy_expanded5=0.9293

Epoch 031 | train_loss=0.2683 | ce=0.2123 | ent=0.1858 | center=0.4678 | val_loss=0.0529 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9848 | val_dqn_proxy_expanded5=0.9444

Epoch 032 | train_loss=0.2567 | ce=0.2022 | ent=0.1879 | center=0.4506 | val_loss=0.0472 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9878 | val_dqn_proxy_expanded5=0.9531

Epoch 033 | train_loss=0.2512 | ce=0.1980 | ent=0.1825 | center=0.4408 | val_loss=0.0458 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9854 | val_dqn_proxy_expanded5=0.9514

Epoch 034 | train_loss=0.2517 | ce=0.1992 | ent=0.1826 | center=0.4334 | val_loss=0.0518 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9840 | val_dqn_proxy_expanded5=0.9432

Epoch 035 | train_loss=0.2479 | ce=0.1962 | ent=0.1808 | center=0.4258 | val_loss=0.0475 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9796 | val_dqn_proxy_expanded5=0.9336

Epoch 036 | train_loss=0.2478 | ce=0.1967 | ent=0.1811 | center=0.4204 | val_loss=0.0436 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9843 | val_dqn_proxy_expanded5=0.9438

Epoch 037 | train_loss=0.2470 | ce=0.1964 | ent=0.1776 | center=0.4167 | val_loss=0.0409 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9870 | val_dqn_proxy_expanded5=0.9299

Epoch 038 | train_loss=0.2429 | ce=0.1933 | ent=0.1764 | center=0.4083 | val_loss=0.0473 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9863 | val_dqn_proxy_expanded5=0.9469

Epoch 039 | train_loss=0.2499 | ce=0.2005 | ent=0.1804 | center=0.4039 | val_loss=0.0431 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9851 | val_dqn_proxy_expanded5=0.9319

Epoch 040 | train_loss=0.2439 | ce=0.1950 | ent=0.1767 | center=0.4008 | val_loss=0.0370 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9806 | val_dqn_proxy_expanded5=0.9359

Epoch 041 | train_loss=0.2399 | ce=0.1916 | ent=0.1706 | center=0.3978 | val_loss=0.0436 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9845 | val_dqn_proxy_expanded5=0.9373

Epoch 042 | train_loss=0.2411 | ce=0.1932 | ent=0.1708 | center=0.3935 | val_loss=0.0378 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9952 | val_dqn_proxy_expanded5=0.9487

Epoch 043 | train_loss=0.2408 | ce=0.1928 | ent=0.1761 | center=0.3919 | val_loss=0.0414 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9888 | val_dqn_proxy_expanded5=0.9521

Epoch 044 | train_loss=0.2379 | ce=0.1903 | ent=0.1711 | center=0.3896 | val_loss=0.0419 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9865 | val_dqn_proxy_expanded5=0.9335

Epoch 045 | train_loss=0.2435 | ce=0.1958 | ent=0.1780 | center=0.3873 | val_loss=0.0357 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9906 | val_dqn_proxy_expanded5=0.9399

Epoch 046 | train_loss=0.2388 | ce=0.1915 | ent=0.1758 | center=0.3845 | val_loss=0.0392 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9886 | val_dqn_proxy_expanded5=0.9492

Epoch 047 | train_loss=0.2388 | ce=0.1921 | ent=0.1675 | center=0.3833 | val_loss=0.0349 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9906 | val_dqn_proxy_expanded5=0.9442

Epoch 048 | train_loss=0.2385 | ce=0.1919 | ent=0.1714 | center=0.3805 | val_loss=0.0349 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9961 | val_dqn_proxy_expanded5=0.9538

Epoch 049 | train_loss=0.2365 | ce=0.1900 | ent=0.1721 | center=0.3788 | val_loss=0.0341 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9946 | val_dqn_proxy_expanded5=0.9491

Epoch 050 | train_loss=0.2352 | ce=0.1893 | ent=0.1703 | center=0.3742 | val_loss=0.0339 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9913 | val_dqn_proxy_expanded5=0.9390

Epoch 051 | train_loss=0.2400 | ce=0.1940 | ent=0.1745 | center=0.3729 | val_loss=0.0325 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9912 | val_dqn_proxy_expanded5=0.9516

Epoch 052 | train_loss=0.2371 | ce=0.1916 | ent=0.1708 | center=0.3698 | val_loss=0.0346 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9923 | val_dqn_proxy_expanded5=0.9445

Epoch 053 | train_loss=0.2374 | ce=0.1921 | ent=0.1727 | center=0.3672 | val_loss=0.0372 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9912 | val_dqn_proxy_expanded5=0.9440

Epoch 054 | train_loss=0.2404 | ce=0.1951 | ent=0.1747 | center=0.3656 | val_loss=0.0454 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9918 | val_dqn_proxy_expanded5=0.9503

Epoch 055 | train_loss=0.2322 | ce=0.1874 | ent=0.1712 | center=0.3626 | val_loss=0.0356 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9851 | val_dqn_proxy_expanded5=0.9410

Epoch 056 | train_loss=0.2370 | ce=0.1925 | ent=0.1685 | center=0.3612 | val_loss=0.0339 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9893 | val_dqn_proxy_expanded5=0.9448

Epoch 057 | train_loss=0.2406 | ce=0.1959 | ent=0.1732 | center=0.3604 | val_loss=0.0381 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9896 | val_dqn_proxy_expanded5=0.9492

Epoch 058 | train_loss=0.2306 | ce=0.1865 | ent=0.1696 | center=0.3565 | val_loss=0.0334 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9914 | val_dqn_proxy_expanded5=0.9472

Epoch 059 | train_loss=0.2317 | ce=0.1880 | ent=0.1649 | center=0.3544 | val_loss=0.0370 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9852 | val_dqn_proxy_expanded5=0.9406

Epoch 060 | train_loss=0.2379 | ce=0.1936 | ent=0.1727 | center=0.3569 | val_loss=0.0348 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9932 | val_dqn_proxy_expanded5=0.9456

Epoch 061 | train_loss=0.2329 | ce=0.1891 | ent=0.1676 | center=0.3541 | val_loss=0.0356 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9902 | val_dqn_proxy_expanded5=0.9452

Epoch 062 | train_loss=0.2372 | ce=0.1934 | ent=0.1710 | center=0.3529 | val_loss=0.0413 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9876 | val_dqn_proxy_expanded5=0.9445

Epoch 063 | train_loss=0.2346 | ce=0.1910 | ent=0.1707 | center=0.3510 | val_loss=0.0358 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9862 | val_dqn_proxy_expanded5=0.9447
Early stopping at epoch 63 (best epoch: 48)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
31,ref_base_ent005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-43_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
23,ref_base_drop050_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-25_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
11,ref_base_ls002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
33,ref_base_ent010_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-46_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
15,ref_base_ls000_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-04_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
41,ref_pms_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-12_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,ref_base_ls000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-59_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
47,ref_pms_ent000_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-28_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
39,ref_base_lr2e4_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-07_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
8,ref_base_ls002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-47_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
53,ref_pms_drop040_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-49_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
12,ref_base_ls000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-56_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
51,ref_pms_ent002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-42_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
17,ref_base_drop040_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-07_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
29,ref_base_ent005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,ref_base_ls002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-49_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
37,ref_base_lr2e4_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-00_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
49,ref_pms_ent002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-35_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
43,ref_pms_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-19_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
45,ref_pms_ent000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-23_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
25,ref_base_ent002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-28_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
24,ref_base_ent002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-26_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
19,ref_base_drop040_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-11_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
32,ref_base_ent010_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-45_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
5,ref_base_ls005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,ref_base_ls005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-45_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
27,ref_base_ent002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
38,ref_base_lr2e4_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-04_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,ref_base_ls005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-42_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,ref_base_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
35,ref_base_ent010_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
21,ref_base_drop050_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-18_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
20,ref_base_drop050_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-14_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
42,ref_pms_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-16_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
28,ref_base_ent005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-35_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,ref_base_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-29_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
46,ref_pms_ent000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-25_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
22,ref_base_drop050_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-21_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
52,ref_pms_drop040_unkPA2_c16384_seed0,results_pa_confmanifold_refined/23-45_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
44,ref_pms_ent000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/23-22_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
48,ref_pms_ent002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/23-32_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
34,ref_base_ent010_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-52_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
36,ref_base_lr2e4_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-57_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,ref_base_ls005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-36_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
26,ref_base_ent002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-31_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
40,ref_pms_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/23-08_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
18,ref_base_drop040_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-09_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
30,ref_base_ent005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-41_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
50,ref_pms_ent002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-38_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
16,ref_base_drop040_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-06_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
10,ref_base_ls002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-53_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
14,ref_base_ls000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-02_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"

================================================================================
Running experiment 55/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "plateau",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0001,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": 1.0,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_pms_drop040",
  "lr": 0.0001,
  "label_smoothing": 0.05,
  "entropy_loss_weight": 0.05,
  "mlp_dropout": 0.4,
  "unknown_pas": [
    "PA4"
  ],
  "run_name": "ref_pms_drop040_unkPA4_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.9163 | ce=0.7568 | ent=0.8798 | center=1.1555 | val_loss=0.3512 | val_acc=0.8926 | val_macro_f1=0.8898 | val_dqn_proxy_softmax3=0.7005 | val_dqn_proxy_expanded5=0.7080

Epoch 002 | train_loss=0.5927 | ce=0.4304 | ent=0.4724 | center=1.3869 | val_loss=0.2309 | val_acc=0.9481 | val_macro_f1=0.9480 | val_dqn_proxy_softmax3=0.7282 | val_dqn_proxy_expanded5=0.7479

Epoch 003 | train_loss=0.5185 | ce=0.3742 | ent=0.4040 | center=1.2403 | val_loss=0.2090 | val_acc=0.9370 | val_macro_f1=0.9368 | val_dqn_proxy_softmax3=0.7532 | val_dqn_proxy_expanded5=0.7652

Epoch 004 | train_loss=0.4962 | ce=0.3619 | ent=0.3666 | center=1.1595 | val_loss=0.1719 | val_acc=0.9519 | val_macro_f1=0.9516 | val_dqn_proxy_softmax3=0.7199 | val_dqn_proxy_expanded5=0.7308

Epoch 005 | train_loss=0.4550 | ce=0.3270 | ent=0.3311 | center=1.1147 | val_loss=0.1532 | val_acc=0.9519 | val_macro_f1=0.9520 | val_dqn_proxy_softmax3=0.7568 | val_dqn_proxy_expanded5=0.7264

Epoch 006 | train_loss=0.4347 | ce=0.3135 | ent=0.3116 | center=1.0564 | val_loss=0.1356 | val_acc=0.9667 | val_macro_f1=0.9669 | val_dqn_proxy_softmax3=0.7493 | val_dqn_proxy_expanded5=0.7210

Epoch 007 | train_loss=0.3879 | ce=0.2703 | ent=0.2856 | center=1.0331 | val_loss=0.1308 | val_acc=0.9630 | val_macro_f1=0.9630 | val_dqn_proxy_softmax3=0.7360 | val_dqn_proxy_expanded5=0.7125

Epoch 008 | train_loss=0.3896 | ce=0.2771 | ent=0.2795 | center=0.9849 | val_loss=0.1236 | val_acc=0.9704 | val_macro_f1=0.9705 | val_dqn_proxy_softmax3=0.7609 | val_dqn_proxy_expanded5=0.7318

Epoch 009 | train_loss=0.3831 | ce=0.2736 | ent=0.2676 | center=0.9609 | val_loss=0.1557 | val_acc=0.9593 | val_macro_f1=0.9592 | val_dqn_proxy_softmax3=0.8429 | val_dqn_proxy_expanded5=0.7821

Epoch 010 | train_loss=0.3511 | ce=0.2455 | ent=0.2541 | center=0.9293 | val_loss=0.1083 | val_acc=0.9704 | val_macro_f1=0.9703 | val_dqn_proxy_softmax3=0.8488 | val_dqn_proxy_expanded5=0.7906

Epoch 011 | train_loss=0.3405 | ce=0.2381 | ent=0.2376 | center=0.9051 | val_loss=0.0805 | val_acc=0.9815 | val_macro_f1=0.9816 | val_dqn_proxy_softmax3=0.9372 | val_dqn_proxy_expanded5=0.8477

Epoch 012 | train_loss=0.3454 | ce=0.2455 | ent=0.2414 | center=0.8784 | val_loss=0.0779 | val_acc=0.9778 | val_macro_f1=0.9779 | val_dqn_proxy_softmax3=0.9342 | val_dqn_proxy_expanded5=0.8579

Epoch 013 | train_loss=0.3343 | ce=0.2373 | ent=0.2342 | center=0.8527 | val_loss=0.0766 | val_acc=0.9704 | val_macro_f1=0.9706 | val_dqn_proxy_softmax3=0.9286 | val_dqn_proxy_expanded5=0.8965

Epoch 014 | train_loss=0.3151 | ce=0.2212 | ent=0.2243 | center=0.8269 | val_loss=0.0622 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9605 | val_dqn_proxy_expanded5=0.9272

Epoch 015 | train_loss=0.3228 | ce=0.2311 | ent=0.2245 | center=0.8045 | val_loss=0.0803 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.9352 | val_dqn_proxy_expanded5=0.8699

Epoch 016 | train_loss=0.3100 | ce=0.2209 | ent=0.2208 | center=0.7807 | val_loss=0.0649 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9025 | val_dqn_proxy_expanded5=0.8267

Epoch 017 | train_loss=0.3034 | ce=0.2163 | ent=0.2113 | center=0.7646 | val_loss=0.0599 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8519 | val_dqn_proxy_expanded5=0.7928

Epoch 018 | train_loss=0.2991 | ce=0.2142 | ent=0.2089 | center=0.7445 | val_loss=0.0667 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9235 | val_dqn_proxy_expanded5=0.8375

Epoch 019 | train_loss=0.3039 | ce=0.2204 | ent=0.2122 | center=0.7283 | val_loss=0.0664 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9027 | val_dqn_proxy_expanded5=0.8244

Epoch 020 | train_loss=0.2989 | ce=0.2176 | ent=0.2014 | center=0.7120 | val_loss=0.0614 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.8851 | val_dqn_proxy_expanded5=0.8138

Epoch 021 | train_loss=0.2974 | ce=0.2175 | ent=0.2093 | center=0.6943 | val_loss=0.0493 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9187 | val_dqn_proxy_expanded5=0.8403

Epoch 022 | train_loss=0.2846 | ce=0.2068 | ent=0.1959 | center=0.6796 | val_loss=0.0654 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7744 | val_dqn_proxy_expanded5=0.7458

Epoch 023 | train_loss=0.2761 | ce=0.2004 | ent=0.1893 | center=0.6623 | val_loss=0.0778 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8652 | val_dqn_proxy_expanded5=0.8043

Epoch 024 | train_loss=0.2785 | ce=0.2042 | ent=0.1957 | center=0.6451 | val_loss=0.0589 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.7628 | val_dqn_proxy_expanded5=0.7350

Epoch 025 | train_loss=0.2741 | ce=0.2014 | ent=0.1916 | center=0.6306 | val_loss=0.0404 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.7562 | val_dqn_proxy_expanded5=0.7316

Epoch 026 | train_loss=0.2739 | ce=0.2026 | ent=0.1910 | center=0.6179 | val_loss=0.0553 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.7737 | val_dqn_proxy_expanded5=0.7430

Epoch 027 | train_loss=0.2740 | ce=0.2041 | ent=0.1871 | center=0.6048 | val_loss=0.0496 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.7705 | val_dqn_proxy_expanded5=0.7402

Epoch 028 | train_loss=0.2689 | ce=0.2004 | ent=0.1885 | center=0.5906 | val_loss=0.0346 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.8065 | val_dqn_proxy_expanded5=0.7666

Epoch 029 | train_loss=0.2690 | ce=0.2021 | ent=0.1851 | center=0.5770 | val_loss=0.0441 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8935 | val_dqn_proxy_expanded5=0.8202
Early stopping at epoch 29 (best epoch: 14)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
31,ref_base_ent005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-43_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
23,ref_base_drop050_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-25_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
11,ref_base_ls002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
33,ref_base_ent010_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-46_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
15,ref_base_ls000_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-04_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
41,ref_pms_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-12_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,ref_base_ls000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-59_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
47,ref_pms_ent000_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-28_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
39,ref_base_lr2e4_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-07_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
8,ref_base_ls002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-47_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
53,ref_pms_drop040_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-49_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
12,ref_base_ls000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-56_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
51,ref_pms_ent002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-42_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
17,ref_base_drop040_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-07_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
29,ref_base_ent005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,ref_base_ls002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-49_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
37,ref_base_lr2e4_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-00_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
49,ref_pms_ent002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-35_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
43,ref_pms_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-19_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
45,ref_pms_ent000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-23_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
25,ref_base_ent002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-28_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
24,ref_base_ent002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-26_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
19,ref_base_drop040_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-11_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
32,ref_base_ent010_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-45_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
5,ref_base_ls005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,ref_base_ls005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-45_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
27,ref_base_ent002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
38,ref_base_lr2e4_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-04_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,ref_base_ls005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-42_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
54,ref_pms_drop040_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-54_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,ref_base_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
35,ref_base_ent010_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
21,ref_base_drop050_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-18_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
20,ref_base_drop050_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-14_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
42,ref_pms_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-16_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
28,ref_base_ent005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-35_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,ref_base_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-29_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
46,ref_pms_ent000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-25_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
22,ref_base_drop050_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-21_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
52,ref_pms_drop040_unkPA2_c16384_seed0,results_pa_confmanifold_refined/23-45_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
44,ref_pms_ent000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/23-22_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
48,ref_pms_ent002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/23-32_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
34,ref_base_ent010_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-52_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
36,ref_base_lr2e4_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-57_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,ref_base_ls005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-36_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
26,ref_base_ent002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-31_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
40,ref_pms_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/23-08_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
18,ref_base_drop040_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-09_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
30,ref_base_ent005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-41_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
50,ref_pms_ent002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-38_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
16,ref_base_drop040_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-06_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
10,ref_base_ls002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-53_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
14,ref_base_ls000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-02_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"

================================================================================
Running experiment 56/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "plateau",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0001,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": 1.0,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_pms_drop040",
  "lr": 0.0001,
  "label_smoothing": 0.05,
  "entropy_loss_weight": 0.05,
  "mlp_dropout": 0.4,
  "unknown_pas": [
    "PA8"
  ],
  "run_name": "ref_pms_drop040_unkPA8_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.8372 | ce=0.6830 | ent=0.8381 | center=1.1233 | val_loss=0.1921 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8741 | val_dqn_proxy_expanded5=0.8885

Epoch 002 | train_loss=0.3923 | ce=0.2527 | ent=0.2989 | center=1.2470 | val_loss=0.1203 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9420 | val_dqn_proxy_expanded5=0.9361

Epoch 003 | train_loss=0.3561 | ce=0.2354 | ent=0.2503 | center=1.0825 | val_loss=0.1076 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9511 | val_dqn_proxy_expanded5=0.9560

Epoch 004 | train_loss=0.3382 | ce=0.2269 | ent=0.2282 | center=0.9992 | val_loss=0.1060 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9409 | val_dqn_proxy_expanded5=0.9347

Epoch 005 | train_loss=0.3278 | ce=0.2229 | ent=0.2224 | center=0.9381 | val_loss=0.1068 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9631 | val_dqn_proxy_expanded5=0.9622

Epoch 006 | train_loss=0.3223 | ce=0.2220 | ent=0.2195 | center=0.8931 | val_loss=0.1072 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8989 | val_dqn_proxy_expanded5=0.8835

Epoch 007 | train_loss=0.3188 | ce=0.2219 | ent=0.2177 | center=0.8601 | val_loss=0.0950 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9403 | val_dqn_proxy_expanded5=0.9116

Epoch 008 | train_loss=0.3152 | ce=0.2220 | ent=0.2169 | center=0.8232 | val_loss=0.0926 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9084 | val_dqn_proxy_expanded5=0.8840

Epoch 009 | train_loss=0.3060 | ce=0.2157 | ent=0.2040 | center=0.8010 | val_loss=0.0912 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9525 | val_dqn_proxy_expanded5=0.9224

Epoch 010 | train_loss=0.3074 | ce=0.2200 | ent=0.2009 | center=0.7745 | val_loss=0.0892 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9092 | val_dqn_proxy_expanded5=0.8739

Epoch 011 | train_loss=0.2931 | ce=0.2087 | ent=0.2007 | center=0.7433 | val_loss=0.0875 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9380 | val_dqn_proxy_expanded5=0.9123

Epoch 012 | train_loss=0.2935 | ce=0.2114 | ent=0.2021 | center=0.7198 | val_loss=0.0834 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8947 | val_dqn_proxy_expanded5=0.8551

Epoch 013 | train_loss=0.2913 | ce=0.2112 | ent=0.1972 | center=0.7023 | val_loss=0.0800 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9260 | val_dqn_proxy_expanded5=0.8992

Epoch 014 | train_loss=0.2782 | ce=0.2007 | ent=0.1931 | center=0.6784 | val_loss=0.0677 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9693 | val_dqn_proxy_expanded5=0.9304

Epoch 015 | train_loss=0.2732 | ce=0.1973 | ent=0.1944 | center=0.6622 | val_loss=0.0640 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8859 | val_dqn_proxy_expanded5=0.8455

Epoch 016 | train_loss=0.2682 | ce=0.1940 | ent=0.1843 | center=0.6492 | val_loss=0.0561 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9740 | val_dqn_proxy_expanded5=0.9354

Epoch 017 | train_loss=0.2621 | ce=0.1904 | ent=0.1789 | center=0.6274 | val_loss=0.0597 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9749 | val_dqn_proxy_expanded5=0.9305

Epoch 018 | train_loss=0.2620 | ce=0.1920 | ent=0.1788 | center=0.6104 | val_loss=0.0578 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9838 | val_dqn_proxy_expanded5=0.9397

Epoch 019 | train_loss=0.2593 | ce=0.1917 | ent=0.1720 | center=0.5905 | val_loss=0.0624 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9861 | val_dqn_proxy_expanded5=0.9386

Epoch 020 | train_loss=0.2554 | ce=0.1898 | ent=0.1748 | center=0.5687 | val_loss=0.0568 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9549 | val_dqn_proxy_expanded5=0.9037

Epoch 021 | train_loss=0.2527 | ce=0.1889 | ent=0.1719 | center=0.5519 | val_loss=0.0579 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9788 | val_dqn_proxy_expanded5=0.9278

Epoch 022 | train_loss=0.2515 | ce=0.1888 | ent=0.1766 | center=0.5385 | val_loss=0.0521 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9751 | val_dqn_proxy_expanded5=0.9193

Epoch 023 | train_loss=0.2506 | ce=0.1897 | ent=0.1690 | center=0.5241 | val_loss=0.0596 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9805 | val_dqn_proxy_expanded5=0.9187

Epoch 024 | train_loss=0.2469 | ce=0.1875 | ent=0.1719 | center=0.5089 | val_loss=0.0543 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9199 | val_dqn_proxy_expanded5=0.8707

Epoch 025 | train_loss=0.2461 | ce=0.1885 | ent=0.1653 | center=0.4933 | val_loss=0.0583 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8925 | val_dqn_proxy_expanded5=0.8458

Epoch 026 | train_loss=0.2447 | ce=0.1885 | ent=0.1692 | center=0.4773 | val_loss=0.0573 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9870 | val_dqn_proxy_expanded5=0.9335

Epoch 027 | train_loss=0.2414 | ce=0.1866 | ent=0.1654 | center=0.4655 | val_loss=0.0586 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9510 | val_dqn_proxy_expanded5=0.8930

Epoch 028 | train_loss=0.2395 | ce=0.1861 | ent=0.1673 | center=0.4503 | val_loss=0.0575 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8990 | val_dqn_proxy_expanded5=0.8533

Epoch 029 | train_loss=0.2381 | ce=0.1856 | ent=0.1654 | center=0.4420 | val_loss=0.0595 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9871 | val_dqn_proxy_expanded5=0.9227

Epoch 030 | train_loss=0.2386 | ce=0.1867 | ent=0.1643 | center=0.4369 | val_loss=0.0561 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9415 | val_dqn_proxy_expanded5=0.8882

Epoch 031 | train_loss=0.2366 | ce=0.1856 | ent=0.1659 | center=0.4272 | val_loss=0.0573 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9865 | val_dqn_proxy_expanded5=0.9294

Epoch 032 | train_loss=0.2372 | ce=0.1865 | ent=0.1666 | center=0.4244 | val_loss=0.0555 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9697 | val_dqn_proxy_expanded5=0.9185

Epoch 033 | train_loss=0.2371 | ce=0.1871 | ent=0.1619 | center=0.4185 | val_loss=0.0602 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9724 | val_dqn_proxy_expanded5=0.9098

Epoch 034 | train_loss=0.2351 | ce=0.1854 | ent=0.1697 | center=0.4112 | val_loss=0.0572 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9036 | val_dqn_proxy_expanded5=0.8489

Epoch 035 | train_loss=0.2351 | ce=0.1861 | ent=0.1626 | center=0.4088 | val_loss=0.0550 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9718 | val_dqn_proxy_expanded5=0.9152

Epoch 036 | train_loss=0.2353 | ce=0.1867 | ent=0.1603 | center=0.4060 | val_loss=0.0572 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9711 | val_dqn_proxy_expanded5=0.9160

Epoch 037 | train_loss=0.2332 | ce=0.1850 | ent=0.1645 | center=0.3999 | val_loss=0.0560 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9325 | val_dqn_proxy_expanded5=0.8792

Epoch 038 | train_loss=0.2339 | ce=0.1858 | ent=0.1623 | center=0.3994 | val_loss=0.0573 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9547 | val_dqn_proxy_expanded5=0.8958

Epoch 039 | train_loss=0.2329 | ce=0.1852 | ent=0.1636 | center=0.3948 | val_loss=0.0572 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9328 | val_dqn_proxy_expanded5=0.8778

Epoch 040 | train_loss=0.2334 | ce=0.1860 | ent=0.1626 | center=0.3931 | val_loss=0.0559 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9502 | val_dqn_proxy_expanded5=0.8909

Epoch 041 | train_loss=0.2326 | ce=0.1854 | ent=0.1628 | center=0.3911 | val_loss=0.0575 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9198 | val_dqn_proxy_expanded5=0.8681

Epoch 042 | train_loss=0.2329 | ce=0.1859 | ent=0.1629 | center=0.3891 | val_loss=0.0567 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9308 | val_dqn_proxy_expanded5=0.8757

Epoch 043 | train_loss=0.2328 | ce=0.1859 | ent=0.1611 | center=0.3881 | val_loss=0.0573 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9301 | val_dqn_proxy_expanded5=0.8759

Epoch 044 | train_loss=0.2319 | ce=0.1850 | ent=0.1654 | center=0.3865 | val_loss=0.0560 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9489 | val_dqn_proxy_expanded5=0.8903
Early stopping at epoch 44 (best epoch: 29)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
31,ref_base_ent005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-43_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
23,ref_base_drop050_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-25_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
11,ref_base_ls002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
33,ref_base_ent010_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-46_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
15,ref_base_ls000_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-04_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
41,ref_pms_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-12_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,ref_base_ls000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-59_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
47,ref_pms_ent000_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-28_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
39,ref_base_lr2e4_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-07_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
8,ref_base_ls002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-47_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
53,ref_pms_drop040_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-49_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
12,ref_base_ls000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-56_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
51,ref_pms_ent002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-42_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
17,ref_base_drop040_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-07_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
29,ref_base_ent005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,ref_base_ls002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-49_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
37,ref_base_lr2e4_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-00_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
49,ref_pms_ent002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-35_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
43,ref_pms_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-19_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
45,ref_pms_ent000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-23_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
25,ref_base_ent002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-28_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
24,ref_base_ent002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-26_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
19,ref_base_drop040_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-11_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
32,ref_base_ent010_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-45_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
5,ref_base_ls005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,ref_base_ls005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-45_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
27,ref_base_ent002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
55,ref_pms_drop040_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-56_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
38,ref_base_lr2e4_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-04_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,ref_base_ls005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-42_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
54,ref_pms_drop040_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-54_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,ref_base_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
35,ref_base_ent010_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
21,ref_base_drop050_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-18_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
20,ref_base_drop050_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-14_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
42,ref_pms_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-16_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
28,ref_base_ent005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-35_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,ref_base_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-29_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
46,ref_pms_ent000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-25_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
22,ref_base_drop050_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-21_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
52,ref_pms_drop040_unkPA2_c16384_seed0,results_pa_confmanifold_refined/23-45_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
44,ref_pms_ent000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/23-22_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
48,ref_pms_ent002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/23-32_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
34,ref_base_ent010_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-52_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
36,ref_base_lr2e4_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-57_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,ref_base_ls005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-36_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
26,ref_base_ent002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-31_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
40,ref_pms_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/23-08_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
18,ref_base_drop040_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-09_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
30,ref_base_ent005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-41_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
50,ref_pms_ent002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-38_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
16,ref_base_drop040_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-06_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
10,ref_base_ls002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-53_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
14,ref_base_ls000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-02_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"

================================================================================
Running experiment 57/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "plateau",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0001,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": 1.0,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_pms_lr2e4",
  "lr": 0.0002,
  "label_smoothing": 0.05,
  "entropy_loss_weight": 0.05,
  "mlp_dropout": 0.5,
  "unknown_pas": [
    "PA2"
  ],
  "run_name": "ref_pms_lr2e4_unkPA2_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.8383 | ce=0.6678 | ent=0.7832 | center=1.3133 | val_loss=0.1560 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8770 | val_dqn_proxy_expanded5=0.8621

Epoch 002 | train_loss=0.4505 | ce=0.3022 | ent=0.3131 | center=1.3272 | val_loss=0.1151 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8454 | val_dqn_proxy_expanded5=0.8110

Epoch 003 | train_loss=0.4012 | ce=0.2714 | ent=0.2780 | center=1.1595 | val_loss=0.1084 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6648 | val_dqn_proxy_expanded5=0.7008

Epoch 004 | train_loss=0.3702 | ce=0.2511 | ent=0.2548 | center=1.0643 | val_loss=0.1016 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6547 | val_dqn_proxy_expanded5=0.7112

Epoch 005 | train_loss=0.3697 | ce=0.2571 | ent=0.2519 | center=1.0000 | val_loss=0.0891 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6707 | val_dqn_proxy_expanded5=0.7337

Epoch 006 | train_loss=0.3544 | ce=0.2481 | ent=0.2315 | center=0.9473 | val_loss=0.0899 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8568 | val_dqn_proxy_expanded5=0.8480

Epoch 007 | train_loss=0.3419 | ce=0.2413 | ent=0.2287 | center=0.8922 | val_loss=0.0801 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7269 | val_dqn_proxy_expanded5=0.7701

Epoch 008 | train_loss=0.3315 | ce=0.2356 | ent=0.2152 | center=0.8515 | val_loss=0.0738 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6823 | val_dqn_proxy_expanded5=0.7534

Epoch 009 | train_loss=0.3326 | ce=0.2395 | ent=0.2268 | center=0.8175 | val_loss=0.0607 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.5231 | val_dqn_proxy_expanded5=0.6745

Epoch 010 | train_loss=0.3172 | ce=0.2266 | ent=0.2200 | center=0.7954 | val_loss=0.0558 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8150 | val_dqn_proxy_expanded5=0.8519

Epoch 011 | train_loss=0.3127 | ce=0.2262 | ent=0.2080 | center=0.7602 | val_loss=0.0541 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7486 | val_dqn_proxy_expanded5=0.8134

Epoch 012 | train_loss=0.2925 | ce=0.2093 | ent=0.2012 | center=0.7316 | val_loss=0.0560 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7395 | val_dqn_proxy_expanded5=0.7971

Epoch 013 | train_loss=0.2826 | ce=0.2033 | ent=0.1903 | center=0.6980 | val_loss=0.0539 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6867 | val_dqn_proxy_expanded5=0.7557

Epoch 014 | train_loss=0.2815 | ce=0.2046 | ent=0.1916 | center=0.6733 | val_loss=0.0521 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6626 | val_dqn_proxy_expanded5=0.7296

Epoch 015 | train_loss=0.2755 | ce=0.2013 | ent=0.1851 | center=0.6501 | val_loss=0.0588 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9189 | val_dqn_proxy_expanded5=0.9213

Epoch 016 | train_loss=0.2718 | ce=0.2004 | ent=0.1867 | center=0.6209 | val_loss=0.0514 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8172 | val_dqn_proxy_expanded5=0.8518

Epoch 017 | train_loss=0.2754 | ce=0.2059 | ent=0.1845 | center=0.6036 | val_loss=0.0546 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6192 | val_dqn_proxy_expanded5=0.6838

Epoch 018 | train_loss=0.2763 | ce=0.2082 | ent=0.1878 | center=0.5864 | val_loss=0.0508 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7984 | val_dqn_proxy_expanded5=0.8381

Epoch 019 | train_loss=0.2660 | ce=0.2006 | ent=0.1810 | center=0.5638 | val_loss=0.0634 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7804 | val_dqn_proxy_expanded5=0.7859

Epoch 020 | train_loss=0.2693 | ce=0.2054 | ent=0.1827 | center=0.5481 | val_loss=0.0584 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.5527 | val_dqn_proxy_expanded5=0.5939

Epoch 021 | train_loss=0.2598 | ce=0.1985 | ent=0.1763 | center=0.5246 | val_loss=0.0577 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.5471 | val_dqn_proxy_expanded5=0.6331

Epoch 022 | train_loss=0.2615 | ce=0.2015 | ent=0.1801 | center=0.5093 | val_loss=0.0563 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8996 | val_dqn_proxy_expanded5=0.8826

Epoch 023 | train_loss=0.2583 | ce=0.2000 | ent=0.1764 | center=0.4950 | val_loss=0.0585 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8062 | val_dqn_proxy_expanded5=0.8060

Epoch 024 | train_loss=0.2518 | ce=0.1951 | ent=0.1786 | center=0.4772 | val_loss=0.0556 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7677 | val_dqn_proxy_expanded5=0.7614

Epoch 025 | train_loss=0.2540 | ce=0.1987 | ent=0.1756 | center=0.4657 | val_loss=0.0574 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.5723 | val_dqn_proxy_expanded5=0.6050

Epoch 026 | train_loss=0.2513 | ce=0.1970 | ent=0.1735 | center=0.4565 | val_loss=0.0535 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7816 | val_dqn_proxy_expanded5=0.7671

Epoch 027 | train_loss=0.2544 | ce=0.2007 | ent=0.1740 | center=0.4497 | val_loss=0.0568 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7832 | val_dqn_proxy_expanded5=0.7753

Epoch 028 | train_loss=0.2499 | ce=0.1972 | ent=0.1701 | center=0.4420 | val_loss=0.0582 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7381 | val_dqn_proxy_expanded5=0.7337

Epoch 029 | train_loss=0.2491 | ce=0.1965 | ent=0.1776 | center=0.4368 | val_loss=0.0569 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7412 | val_dqn_proxy_expanded5=0.7366

Epoch 030 | train_loss=0.2467 | ce=0.1953 | ent=0.1717 | center=0.4277 | val_loss=0.0625 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7543 | val_dqn_proxy_expanded5=0.7341
Early stopping at epoch 30 (best epoch: 15)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
31,ref_base_ent005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-43_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
23,ref_base_drop050_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-25_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
11,ref_base_ls002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
33,ref_base_ent010_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-46_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
15,ref_base_ls000_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-04_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
41,ref_pms_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-12_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,ref_base_ls000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-59_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
47,ref_pms_ent000_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-28_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
39,ref_base_lr2e4_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-07_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
8,ref_base_ls002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-47_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
53,ref_pms_drop040_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-49_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
12,ref_base_ls000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-56_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
51,ref_pms_ent002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-42_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
17,ref_base_drop040_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-07_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
29,ref_base_ent005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,ref_base_ls002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-49_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
37,ref_base_lr2e4_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-00_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
49,ref_pms_ent002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-35_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
43,ref_pms_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-19_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
45,ref_pms_ent000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-23_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
25,ref_base_ent002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-28_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
24,ref_base_ent002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-26_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
19,ref_base_drop040_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-11_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
32,ref_base_ent010_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-45_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
5,ref_base_ls005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
56,ref_pms_lr2e4_unkPA2_c16384_seed0,results_pa_confmanifold_refined/00-00_04-30-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,ref_base_ls005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-45_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
27,ref_base_ent002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
55,ref_pms_drop040_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-56_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
38,ref_base_lr2e4_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-04_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,ref_base_ls005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-42_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
54,ref_pms_drop040_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-54_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,ref_base_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
35,ref_base_ent010_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
21,ref_base_drop050_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-18_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
20,ref_base_drop050_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-14_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
42,ref_pms_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-16_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
28,ref_base_ent005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-35_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,ref_base_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-29_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
46,ref_pms_ent000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-25_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
22,ref_base_drop050_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-21_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
52,ref_pms_drop040_unkPA2_c16384_seed0,results_pa_confmanifold_refined/23-45_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
44,ref_pms_ent000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/23-22_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
48,ref_pms_ent002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/23-32_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
34,ref_base_ent010_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-52_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
36,ref_base_lr2e4_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-57_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,ref_base_ls005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-36_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
26,ref_base_ent002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-31_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
40,ref_pms_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/23-08_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
18,ref_base_drop040_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-09_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
30,ref_base_ent005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-41_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
50,ref_pms_ent002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-38_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
16,ref_base_drop040_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-06_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
10,ref_base_ls002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-53_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
14,ref_base_ls000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-02_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"

================================================================================
Running experiment 58/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "plateau",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0001,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": 1.0,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_pms_lr2e4",
  "lr": 0.0002,
  "label_smoothing": 0.05,
  "entropy_loss_weight": 0.05,
  "mlp_dropout": 0.5,
  "unknown_pas": [
    "PA3"
  ],
  "run_name": "ref_pms_lr2e4_unkPA3_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.8924 | ce=0.7321 | ent=0.8372 | center=1.1843 | val_loss=0.2113 | val_acc=0.9407 | val_macro_f1=0.9411 | val_dqn_proxy_softmax3=0.8815 | val_dqn_proxy_expanded5=0.8228

Epoch 002 | train_loss=0.5357 | ce=0.3772 | ent=0.4213 | center=1.3743 | val_loss=0.1642 | val_acc=0.9407 | val_macro_f1=0.9410 | val_dqn_proxy_softmax3=0.7964 | val_dqn_proxy_expanded5=0.7854

Epoch 003 | train_loss=0.4834 | ce=0.3463 | ent=0.3632 | center=1.1888 | val_loss=0.1876 | val_acc=0.9333 | val_macro_f1=0.9327 | val_dqn_proxy_softmax3=0.7772 | val_dqn_proxy_expanded5=0.7953

Epoch 004 | train_loss=0.4503 | ce=0.3236 | ent=0.3275 | center=1.1033 | val_loss=0.1087 | val_acc=0.9704 | val_macro_f1=0.9705 | val_dqn_proxy_softmax3=0.7505 | val_dqn_proxy_expanded5=0.7678

Epoch 005 | train_loss=0.4022 | ce=0.2832 | ent=0.2993 | center=1.0403 | val_loss=0.2012 | val_acc=0.9333 | val_macro_f1=0.9337 | val_dqn_proxy_softmax3=0.8924 | val_dqn_proxy_expanded5=0.8913

Epoch 006 | train_loss=0.3966 | ce=0.2855 | ent=0.2870 | center=0.9674 | val_loss=0.1305 | val_acc=0.9519 | val_macro_f1=0.9511 | val_dqn_proxy_softmax3=0.8626 | val_dqn_proxy_expanded5=0.8463

Epoch 007 | train_loss=0.3893 | ce=0.2843 | ent=0.2759 | center=0.9122 | val_loss=0.0989 | val_acc=0.9630 | val_macro_f1=0.9629 | val_dqn_proxy_softmax3=0.9169 | val_dqn_proxy_expanded5=0.8776

Epoch 008 | train_loss=0.3910 | ce=0.2903 | ent=0.2787 | center=0.8672 | val_loss=0.1352 | val_acc=0.9630 | val_macro_f1=0.9628 | val_dqn_proxy_softmax3=0.9585 | val_dqn_proxy_expanded5=0.9469

Epoch 009 | train_loss=0.3844 | ce=0.2878 | ent=0.2793 | center=0.8265 | val_loss=0.0802 | val_acc=0.9741 | val_macro_f1=0.9741 | val_dqn_proxy_softmax3=0.9534 | val_dqn_proxy_expanded5=0.9403

Epoch 010 | train_loss=0.3536 | ce=0.2612 | ent=0.2561 | center=0.7965 | val_loss=0.1082 | val_acc=0.9630 | val_macro_f1=0.9629 | val_dqn_proxy_softmax3=0.9346 | val_dqn_proxy_expanded5=0.9063

Epoch 011 | train_loss=0.3619 | ce=0.2730 | ent=0.2528 | center=0.7630 | val_loss=0.0824 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9611 | val_dqn_proxy_expanded5=0.9209

Epoch 012 | train_loss=0.3303 | ce=0.2453 | ent=0.2347 | center=0.7334 | val_loss=0.0612 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9509 | val_dqn_proxy_expanded5=0.9139

Epoch 013 | train_loss=0.3159 | ce=0.2349 | ent=0.2265 | center=0.6972 | val_loss=0.0668 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9591 | val_dqn_proxy_expanded5=0.9248

Epoch 014 | train_loss=0.2991 | ce=0.2218 | ent=0.2151 | center=0.6653 | val_loss=0.0754 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.9608 | val_dqn_proxy_expanded5=0.9093

Epoch 015 | train_loss=0.3071 | ce=0.2327 | ent=0.2152 | center=0.6368 | val_loss=0.0790 | val_acc=0.9741 | val_macro_f1=0.9741 | val_dqn_proxy_softmax3=0.9728 | val_dqn_proxy_expanded5=0.9359

Epoch 016 | train_loss=0.3015 | ce=0.2293 | ent=0.2143 | center=0.6154 | val_loss=0.1097 | val_acc=0.9630 | val_macro_f1=0.9628 | val_dqn_proxy_softmax3=0.8968 | val_dqn_proxy_expanded5=0.9043

Epoch 017 | train_loss=0.3037 | ce=0.2336 | ent=0.2155 | center=0.5934 | val_loss=0.1232 | val_acc=0.9704 | val_macro_f1=0.9703 | val_dqn_proxy_softmax3=0.8485 | val_dqn_proxy_expanded5=0.8277

Epoch 018 | train_loss=0.2907 | ce=0.2232 | ent=0.2098 | center=0.5708 | val_loss=0.0499 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9776 | val_dqn_proxy_expanded5=0.9482

Epoch 019 | train_loss=0.2968 | ce=0.2308 | ent=0.2149 | center=0.5527 | val_loss=0.0680 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9499 | val_dqn_proxy_expanded5=0.9034

Epoch 020 | train_loss=0.2833 | ce=0.2197 | ent=0.2032 | center=0.5339 | val_loss=0.0407 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9807 | val_dqn_proxy_expanded5=0.9246

Epoch 021 | train_loss=0.2787 | ce=0.2174 | ent=0.1984 | center=0.5145 | val_loss=0.1163 | val_acc=0.9704 | val_macro_f1=0.9703 | val_dqn_proxy_softmax3=0.9329 | val_dqn_proxy_expanded5=0.9022

Epoch 022 | train_loss=0.2766 | ce=0.2171 | ent=0.2052 | center=0.4929 | val_loss=0.0529 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9856 | val_dqn_proxy_expanded5=0.9336

Epoch 023 | train_loss=0.2647 | ce=0.2074 | ent=0.1945 | center=0.4752 | val_loss=0.0490 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.8973 | val_dqn_proxy_expanded5=0.8436

Epoch 024 | train_loss=0.2557 | ce=0.2004 | ent=0.1846 | center=0.4611 | val_loss=0.0637 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9764 | val_dqn_proxy_expanded5=0.9474

Epoch 025 | train_loss=0.2640 | ce=0.2099 | ent=0.1924 | center=0.4449 | val_loss=0.1230 | val_acc=0.9704 | val_macro_f1=0.9703 | val_dqn_proxy_softmax3=0.9576 | val_dqn_proxy_expanded5=0.9422

Epoch 026 | train_loss=0.2614 | ce=0.2093 | ent=0.1841 | center=0.4298 | val_loss=0.0444 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9754 | val_dqn_proxy_expanded5=0.9159

Epoch 027 | train_loss=0.2573 | ce=0.2066 | ent=0.1804 | center=0.4164 | val_loss=0.0471 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9730 | val_dqn_proxy_expanded5=0.9122

Epoch 028 | train_loss=0.2512 | ce=0.2011 | ent=0.1868 | center=0.4081 | val_loss=0.0374 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9801 | val_dqn_proxy_expanded5=0.9418

Epoch 029 | train_loss=0.2577 | ce=0.2083 | ent=0.1855 | center=0.4018 | val_loss=0.0489 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9770 | val_dqn_proxy_expanded5=0.9387

Epoch 030 | train_loss=0.2490 | ce=0.2008 | ent=0.1774 | center=0.3931 | val_loss=0.0407 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9821 | val_dqn_proxy_expanded5=0.9357

Epoch 031 | train_loss=0.2516 | ce=0.2035 | ent=0.1842 | center=0.3889 | val_loss=0.0435 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9821 | val_dqn_proxy_expanded5=0.9417

Epoch 032 | train_loss=0.2493 | ce=0.2022 | ent=0.1782 | center=0.3816 | val_loss=0.0360 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9856 | val_dqn_proxy_expanded5=0.9487

Epoch 033 | train_loss=0.2500 | ce=0.2033 | ent=0.1868 | center=0.3743 | val_loss=0.0849 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9625 | val_dqn_proxy_expanded5=0.9273

Epoch 034 | train_loss=0.2515 | ce=0.2054 | ent=0.1820 | center=0.3694 | val_loss=0.0517 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9736 | val_dqn_proxy_expanded5=0.9342

Epoch 035 | train_loss=0.2438 | ce=0.1981 | ent=0.1843 | center=0.3644 | val_loss=0.0392 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9808 | val_dqn_proxy_expanded5=0.9270

Epoch 036 | train_loss=0.2507 | ce=0.2060 | ent=0.1766 | center=0.3586 | val_loss=0.0371 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9838 | val_dqn_proxy_expanded5=0.9421

Epoch 037 | train_loss=0.2442 | ce=0.1998 | ent=0.1827 | center=0.3528 | val_loss=0.0432 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9870 | val_dqn_proxy_expanded5=0.9500

Epoch 038 | train_loss=0.2352 | ce=0.1921 | ent=0.1675 | center=0.3473 | val_loss=0.0364 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9874 | val_dqn_proxy_expanded5=0.9451

Epoch 039 | train_loss=0.2412 | ce=0.1978 | ent=0.1808 | center=0.3427 | val_loss=0.0403 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9894 | val_dqn_proxy_expanded5=0.9456

Epoch 040 | train_loss=0.2359 | ce=0.1935 | ent=0.1722 | center=0.3380 | val_loss=0.0342 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9945 | val_dqn_proxy_expanded5=0.9597

Epoch 041 | train_loss=0.2424 | ce=0.2003 | ent=0.1760 | center=0.3334 | val_loss=0.0458 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9826 | val_dqn_proxy_expanded5=0.9474

Epoch 042 | train_loss=0.2379 | ce=0.1962 | ent=0.1732 | center=0.3308 | val_loss=0.0319 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9896 | val_dqn_proxy_expanded5=0.9503

Epoch 043 | train_loss=0.2354 | ce=0.1940 | ent=0.1727 | center=0.3271 | val_loss=0.0440 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9789 | val_dqn_proxy_expanded5=0.9395

Epoch 044 | train_loss=0.2319 | ce=0.1906 | ent=0.1745 | center=0.3261 | val_loss=0.0342 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9910 | val_dqn_proxy_expanded5=0.9477

Epoch 045 | train_loss=0.2347 | ce=0.1941 | ent=0.1674 | center=0.3226 | val_loss=0.0347 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9844 | val_dqn_proxy_expanded5=0.9438

Epoch 046 | train_loss=0.2329 | ce=0.1922 | ent=0.1736 | center=0.3202 | val_loss=0.0323 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9941 | val_dqn_proxy_expanded5=0.9587

Epoch 047 | train_loss=0.2308 | ce=0.1907 | ent=0.1727 | center=0.3143 | val_loss=0.0343 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9939 | val_dqn_proxy_expanded5=0.9554

Epoch 048 | train_loss=0.2408 | ce=0.2006 | ent=0.1748 | center=0.3150 | val_loss=0.0376 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9895 | val_dqn_proxy_expanded5=0.9574

Epoch 049 | train_loss=0.2344 | ce=0.1948 | ent=0.1719 | center=0.3107 | val_loss=0.0337 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9950 | val_dqn_proxy_expanded5=0.9480

Epoch 050 | train_loss=0.2298 | ce=0.1903 | ent=0.1724 | center=0.3088 | val_loss=0.0381 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9839 | val_dqn_proxy_expanded5=0.9428

Epoch 051 | train_loss=0.2341 | ce=0.1945 | ent=0.1737 | center=0.3090 | val_loss=0.0313 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9986 | val_dqn_proxy_expanded5=0.9533

Epoch 052 | train_loss=0.2305 | ce=0.1914 | ent=0.1678 | center=0.3074 | val_loss=0.0351 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9833 | val_dqn_proxy_expanded5=0.9432

Epoch 053 | train_loss=0.2293 | ce=0.1901 | ent=0.1732 | center=0.3053 | val_loss=0.0326 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9952 | val_dqn_proxy_expanded5=0.9543

Epoch 054 | train_loss=0.2331 | ce=0.1941 | ent=0.1688 | center=0.3062 | val_loss=0.0308 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9952 | val_dqn_proxy_expanded5=0.9523

Epoch 055 | train_loss=0.2310 | ce=0.1920 | ent=0.1736 | center=0.3034 | val_loss=0.0338 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9938 | val_dqn_proxy_expanded5=0.9582

Epoch 056 | train_loss=0.2295 | ce=0.1907 | ent=0.1717 | center=0.3020 | val_loss=0.0357 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9845 | val_dqn_proxy_expanded5=0.9518

Epoch 057 | train_loss=0.2317 | ce=0.1932 | ent=0.1696 | center=0.2998 | val_loss=0.0337 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9934 | val_dqn_proxy_expanded5=0.9530

Epoch 058 | train_loss=0.2323 | ce=0.1940 | ent=0.1677 | center=0.2986 | val_loss=0.0317 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9969 | val_dqn_proxy_expanded5=0.9642

Epoch 059 | train_loss=0.2318 | ce=0.1934 | ent=0.1746 | center=0.2969 | val_loss=0.0323 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9977 | val_dqn_proxy_expanded5=0.9657

Epoch 060 | train_loss=0.2258 | ce=0.1876 | ent=0.1725 | center=0.2949 | val_loss=0.0337 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9854 | val_dqn_proxy_expanded5=0.9518

Epoch 061 | train_loss=0.2302 | ce=0.1923 | ent=0.1655 | center=0.2954 | val_loss=0.0322 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9959 | val_dqn_proxy_expanded5=0.9615

Epoch 062 | train_loss=0.2316 | ce=0.1935 | ent=0.1721 | center=0.2952 | val_loss=0.0328 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9953 | val_dqn_proxy_expanded5=0.9540

Epoch 063 | train_loss=0.2305 | ce=0.1925 | ent=0.1729 | center=0.2940 | val_loss=0.0355 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9855 | val_dqn_proxy_expanded5=0.9544

Epoch 064 | train_loss=0.2301 | ce=0.1925 | ent=0.1690 | center=0.2914 | val_loss=0.0403 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9858 | val_dqn_proxy_expanded5=0.9528

Epoch 065 | train_loss=0.2289 | ce=0.1912 | ent=0.1700 | center=0.2920 | val_loss=0.0350 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9917 | val_dqn_proxy_expanded5=0.9570

Epoch 066 | train_loss=0.2283 | ce=0.1906 | ent=0.1706 | center=0.2911 | val_loss=0.0307 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9936 | val_dqn_proxy_expanded5=0.9522
Early stopping at epoch 66 (best epoch: 51)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
31,ref_base_ent005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-43_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
23,ref_base_drop050_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-25_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
11,ref_base_ls002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
33,ref_base_ent010_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-46_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
15,ref_base_ls000_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-04_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
41,ref_pms_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-12_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,ref_base_ls000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-59_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
47,ref_pms_ent000_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-28_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
39,ref_base_lr2e4_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-07_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
8,ref_base_ls002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-47_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
57,ref_pms_lr2e4_unkPA3_c16384_seed0,results_pa_confmanifold_refined/00-02_04-30-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
53,ref_pms_drop040_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-49_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
12,ref_base_ls000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-56_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
51,ref_pms_ent002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-42_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
17,ref_base_drop040_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-07_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
29,ref_base_ent005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,ref_base_ls002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-49_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
37,ref_base_lr2e4_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-00_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
49,ref_pms_ent002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-35_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
43,ref_pms_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-19_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
45,ref_pms_ent000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-23_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
25,ref_base_ent002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-28_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
24,ref_base_ent002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-26_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
19,ref_base_drop040_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-11_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
32,ref_base_ent010_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-45_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
5,ref_base_ls005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
56,ref_pms_lr2e4_unkPA2_c16384_seed0,results_pa_confmanifold_refined/00-00_04-30-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,ref_base_ls005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-45_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
27,ref_base_ent002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
55,ref_pms_drop040_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-56_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
38,ref_base_lr2e4_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-04_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,ref_base_ls005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-42_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
54,ref_pms_drop040_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-54_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,ref_base_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
35,ref_base_ent010_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
21,ref_base_drop050_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-18_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
20,ref_base_drop050_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-14_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
42,ref_pms_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-16_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
28,ref_base_ent005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-35_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,ref_base_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-29_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
46,ref_pms_ent000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-25_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
22,ref_base_drop050_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-21_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
52,ref_pms_drop040_unkPA2_c16384_seed0,results_pa_confmanifold_refined/23-45_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
44,ref_pms_ent000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/23-22_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
48,ref_pms_ent002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/23-32_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
34,ref_base_ent010_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-52_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
36,ref_base_lr2e4_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-57_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,ref_base_ls005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-36_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
26,ref_base_ent002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-31_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
40,ref_pms_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/23-08_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
18,ref_base_drop040_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-09_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
30,ref_base_ent005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-41_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
50,ref_pms_ent002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-38_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
16,ref_base_drop040_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-06_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
10,ref_base_ls002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-53_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
14,ref_base_ls000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-02_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"

================================================================================
Running experiment 59/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "plateau",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0001,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": 1.0,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_pms_lr2e4",
  "lr": 0.0002,
  "label_smoothing": 0.05,
  "entropy_loss_weight": 0.05,
  "mlp_dropout": 0.5,
  "unknown_pas": [
    "PA4"
  ],
  "run_name": "ref_pms_lr2e4_unkPA4_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.8856 | ce=0.7170 | ent=0.8132 | center=1.2787 | val_loss=0.3399 | val_acc=0.9037 | val_macro_f1=0.9009 | val_dqn_proxy_softmax3=0.7131 | val_dqn_proxy_expanded5=0.6905

Epoch 002 | train_loss=0.5915 | ce=0.4294 | ent=0.4556 | center=1.3933 | val_loss=0.2845 | val_acc=0.8963 | val_macro_f1=0.8959 | val_dqn_proxy_softmax3=0.7353 | val_dqn_proxy_expanded5=0.6811

Epoch 003 | train_loss=0.5330 | ce=0.3924 | ent=0.3923 | center=1.2105 | val_loss=0.1878 | val_acc=0.9370 | val_macro_f1=0.9368 | val_dqn_proxy_softmax3=0.7568 | val_dqn_proxy_expanded5=0.7299

Epoch 004 | train_loss=0.4429 | ce=0.3121 | ent=0.3263 | center=1.1455 | val_loss=0.1466 | val_acc=0.9556 | val_macro_f1=0.9555 | val_dqn_proxy_softmax3=0.7438 | val_dqn_proxy_expanded5=0.7176

Epoch 005 | train_loss=0.4440 | ce=0.3215 | ent=0.3044 | center=1.0722 | val_loss=0.1434 | val_acc=0.9630 | val_macro_f1=0.9632 | val_dqn_proxy_softmax3=0.7434 | val_dqn_proxy_expanded5=0.7158

Epoch 006 | train_loss=0.3909 | ce=0.2773 | ent=0.2840 | center=0.9936 | val_loss=0.1180 | val_acc=0.9741 | val_macro_f1=0.9741 | val_dqn_proxy_softmax3=0.7593 | val_dqn_proxy_expanded5=0.7313

Epoch 007 | train_loss=0.4003 | ce=0.2925 | ent=0.2771 | center=0.9390 | val_loss=0.0926 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8350 | val_dqn_proxy_expanded5=0.7814

Epoch 008 | train_loss=0.3576 | ce=0.2559 | ent=0.2500 | center=0.8918 | val_loss=0.1299 | val_acc=0.9593 | val_macro_f1=0.9592 | val_dqn_proxy_softmax3=0.8803 | val_dqn_proxy_expanded5=0.8085

Epoch 009 | train_loss=0.3532 | ce=0.2557 | ent=0.2465 | center=0.8513 | val_loss=0.0739 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.9444 | val_dqn_proxy_expanded5=0.8673

Epoch 010 | train_loss=0.3351 | ce=0.2420 | ent=0.2370 | center=0.8123 | val_loss=0.0718 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9569 | val_dqn_proxy_expanded5=0.9144

Epoch 011 | train_loss=0.3411 | ce=0.2508 | ent=0.2379 | center=0.7845 | val_loss=0.0620 | val_acc=0.9815 | val_macro_f1=0.9813 | val_dqn_proxy_softmax3=0.9246 | val_dqn_proxy_expanded5=0.8507

Epoch 012 | train_loss=0.3193 | ce=0.2331 | ent=0.2248 | center=0.7497 | val_loss=0.0536 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9002 | val_dqn_proxy_expanded5=0.8245

Epoch 013 | train_loss=0.3055 | ce=0.2233 | ent=0.2168 | center=0.7141 | val_loss=0.0441 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9554 | val_dqn_proxy_expanded5=0.8751

Epoch 014 | train_loss=0.2965 | ce=0.2172 | ent=0.2145 | center=0.6851 | val_loss=0.0740 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9061 | val_dqn_proxy_expanded5=0.8265

Epoch 015 | train_loss=0.3072 | ce=0.2310 | ent=0.2096 | center=0.6579 | val_loss=0.0907 | val_acc=0.9704 | val_macro_f1=0.9703 | val_dqn_proxy_softmax3=0.8406 | val_dqn_proxy_expanded5=0.7868

Epoch 016 | train_loss=0.2972 | ce=0.2235 | ent=0.2077 | center=0.6334 | val_loss=0.0962 | val_acc=0.9704 | val_macro_f1=0.9703 | val_dqn_proxy_softmax3=0.8658 | val_dqn_proxy_expanded5=0.8062

Epoch 017 | train_loss=0.2936 | ce=0.2217 | ent=0.2053 | center=0.6157 | val_loss=0.0453 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.7767 | val_dqn_proxy_expanded5=0.7491

Epoch 018 | train_loss=0.2874 | ce=0.2182 | ent=0.2042 | center=0.5904 | val_loss=0.0508 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7927 | val_dqn_proxy_expanded5=0.7602

Epoch 019 | train_loss=0.2848 | ce=0.2181 | ent=0.1936 | center=0.5700 | val_loss=0.0630 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9566 | val_dqn_proxy_expanded5=0.8906

Epoch 020 | train_loss=0.2755 | ce=0.2104 | ent=0.1969 | center=0.5520 | val_loss=0.0427 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9321 | val_dqn_proxy_expanded5=0.8622

Epoch 021 | train_loss=0.2760 | ce=0.2123 | ent=0.1928 | center=0.5404 | val_loss=0.0493 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9528 | val_dqn_proxy_expanded5=0.8823

Epoch 022 | train_loss=0.2640 | ce=0.2018 | ent=0.1888 | center=0.5277 | val_loss=0.0415 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9534 | val_dqn_proxy_expanded5=0.8867

Epoch 023 | train_loss=0.2557 | ce=0.1946 | ent=0.1860 | center=0.5175 | val_loss=0.0592 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.7781 | val_dqn_proxy_expanded5=0.7522

Epoch 024 | train_loss=0.2700 | ce=0.2100 | ent=0.1815 | center=0.5093 | val_loss=0.0373 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.8106 | val_dqn_proxy_expanded5=0.7930

Epoch 025 | train_loss=0.2610 | ce=0.2013 | ent=0.1917 | center=0.5013 | val_loss=0.0457 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7717 | val_dqn_proxy_expanded5=0.7637
Early stopping at epoch 25 (best epoch: 10)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
31,ref_base_ent005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-43_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
23,ref_base_drop050_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-25_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
11,ref_base_ls002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
33,ref_base_ent010_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-46_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
15,ref_base_ls000_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-04_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
41,ref_pms_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-12_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,ref_base_ls000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-59_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
47,ref_pms_ent000_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-28_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
39,ref_base_lr2e4_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-07_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
8,ref_base_ls002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-47_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
57,ref_pms_lr2e4_unkPA3_c16384_seed0,results_pa_confmanifold_refined/00-02_04-30-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
53,ref_pms_drop040_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-49_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
12,ref_base_ls000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-56_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
51,ref_pms_ent002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-42_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
17,ref_base_drop040_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-07_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
29,ref_base_ent005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,ref_base_ls002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-49_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
37,ref_base_lr2e4_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-00_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
49,ref_pms_ent002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-35_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
43,ref_pms_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-19_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
45,ref_pms_ent000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-23_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
25,ref_base_ent002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-28_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
24,ref_base_ent002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-26_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
19,ref_base_drop040_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-11_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
32,ref_base_ent010_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-45_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
5,ref_base_ls005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
56,ref_pms_lr2e4_unkPA2_c16384_seed0,results_pa_confmanifold_refined/00-00_04-30-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,ref_base_ls005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-45_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
27,ref_base_ent002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
55,ref_pms_drop040_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-56_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
38,ref_base_lr2e4_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-04_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,ref_base_ls005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-42_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
54,ref_pms_drop040_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-54_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,ref_base_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
35,ref_base_ent010_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
21,ref_base_drop050_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-18_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
20,ref_base_drop050_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-14_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
42,ref_pms_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-16_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
28,ref_base_ent005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-35_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
58,ref_pms_lr2e4_unkPA4_c16384_seed0,results_pa_confmanifold_refined/00-08_04-30-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,ref_base_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-29_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
46,ref_pms_ent000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-25_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
22,ref_base_drop050_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-21_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
52,ref_pms_drop040_unkPA2_c16384_seed0,results_pa_confmanifold_refined/23-45_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
44,ref_pms_ent000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/23-22_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
48,ref_pms_ent002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/23-32_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
34,ref_base_ent010_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-52_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
36,ref_base_lr2e4_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-57_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,ref_base_ls005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-36_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
26,ref_base_ent002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-31_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
40,ref_pms_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/23-08_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
18,ref_base_drop040_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-09_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
30,ref_base_ent005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-41_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
50,ref_pms_ent002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-38_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
16,ref_base_drop040_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-06_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
10,ref_base_ls002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-53_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
14,ref_base_ls000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-02_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"

================================================================================
Running experiment 60/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "plateau",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0001,
  "lambda_center": 0.1,
  "class_weight_mode": null,
  "grad_clip_norm": 1.0,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_pms_lr2e4",
  "lr": 0.0002,
  "label_smoothing": 0.05,
  "entropy_loss_weight": 0.05,
  "mlp_dropout": 0.5,
  "unknown_pas": [
    "PA8"
  ],
  "run_name": "ref_pms_lr2e4_unkPA8_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.8052 | ce=0.6399 | ent=0.7433 | center=1.2813 | val_loss=0.1422 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9422 | val_dqn_proxy_expanded5=0.9354

Epoch 002 | train_loss=0.3801 | ce=0.2436 | ent=0.2739 | center=1.2278 | val_loss=0.1215 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9423 | val_dqn_proxy_expanded5=0.9394

Epoch 003 | train_loss=0.3532 | ce=0.2356 | ent=0.2447 | center=1.0540 | val_loss=0.1110 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9247 | val_dqn_proxy_expanded5=0.9306

Epoch 004 | train_loss=0.3476 | ce=0.2396 | ent=0.2364 | center=0.9617 | val_loss=0.0951 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9378 | val_dqn_proxy_expanded5=0.9218

Epoch 005 | train_loss=0.3292 | ce=0.2277 | ent=0.2261 | center=0.9021 | val_loss=0.1118 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9694 | val_dqn_proxy_expanded5=0.9623

Epoch 006 | train_loss=0.3243 | ce=0.2296 | ent=0.2120 | center=0.8411 | val_loss=0.0966 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9449 | val_dqn_proxy_expanded5=0.9329

Epoch 007 | train_loss=0.3116 | ce=0.2212 | ent=0.2150 | center=0.7969 | val_loss=0.0900 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9450 | val_dqn_proxy_expanded5=0.9357

Epoch 008 | train_loss=0.3016 | ce=0.2155 | ent=0.2029 | center=0.7601 | val_loss=0.0854 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9356 | val_dqn_proxy_expanded5=0.9272

Epoch 009 | train_loss=0.2973 | ce=0.2146 | ent=0.2050 | center=0.7247 | val_loss=0.0656 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9144 | val_dqn_proxy_expanded5=0.8901

Epoch 010 | train_loss=0.2801 | ce=0.2002 | ent=0.1913 | center=0.7035 | val_loss=0.0718 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9364 | val_dqn_proxy_expanded5=0.9231

Epoch 011 | train_loss=0.2721 | ce=0.1957 | ent=0.1915 | center=0.6684 | val_loss=0.0597 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8464 | val_dqn_proxy_expanded5=0.8363

Epoch 012 | train_loss=0.2698 | ce=0.1964 | ent=0.1843 | center=0.6423 | val_loss=0.0588 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9267 | val_dqn_proxy_expanded5=0.9170

Epoch 013 | train_loss=0.2616 | ce=0.1914 | ent=0.1792 | center=0.6127 | val_loss=0.0590 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8967 | val_dqn_proxy_expanded5=0.8950

Epoch 014 | train_loss=0.2601 | ce=0.1925 | ent=0.1777 | center=0.5865 | val_loss=0.0551 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9645 | val_dqn_proxy_expanded5=0.9411

Epoch 015 | train_loss=0.2566 | ce=0.1916 | ent=0.1750 | center=0.5630 | val_loss=0.0575 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9629 | val_dqn_proxy_expanded5=0.9457

Epoch 016 | train_loss=0.2549 | ce=0.1916 | ent=0.1775 | center=0.5438 | val_loss=0.0544 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9580 | val_dqn_proxy_expanded5=0.9271

Epoch 017 | train_loss=0.2515 | ce=0.1906 | ent=0.1735 | center=0.5220 | val_loss=0.0592 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9607 | val_dqn_proxy_expanded5=0.9356

Epoch 018 | train_loss=0.2637 | ce=0.2047 | ent=0.1750 | center=0.5019 | val_loss=0.0645 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9096 | val_dqn_proxy_expanded5=0.8890

Epoch 019 | train_loss=0.2509 | ce=0.1935 | ent=0.1714 | center=0.4882 | val_loss=0.0598 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8921 | val_dqn_proxy_expanded5=0.8925

Epoch 020 | train_loss=0.2451 | ce=0.1897 | ent=0.1687 | center=0.4690 | val_loss=0.0631 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9449 | val_dqn_proxy_expanded5=0.9337
Early stopping at epoch 20 (best epoch: 5)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
31,ref_base_ent005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-43_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
59,ref_pms_lr2e4_unkPA8_c16384_seed0,results_pa_confmanifold_refined/00-10_04-30-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
23,ref_base_drop050_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-25_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
11,ref_base_ls002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
33,ref_base_ent010_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-46_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
15,ref_base_ls000_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-04_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
41,ref_pms_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-12_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
13,ref_base_ls000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-59_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
47,ref_pms_ent000_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-28_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
39,ref_base_lr2e4_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-07_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
8,ref_base_ls002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-47_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
57,ref_pms_lr2e4_unkPA3_c16384_seed0,results_pa_confmanifold_refined/00-02_04-30-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
53,ref_pms_drop040_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-49_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
12,ref_base_ls000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-56_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
51,ref_pms_ent002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-42_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
17,ref_base_drop040_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-07_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
29,ref_base_ent005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
9,ref_base_ls002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-49_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
37,ref_base_lr2e4_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-00_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
49,ref_pms_ent002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-35_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
43,ref_pms_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-19_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
45,ref_pms_ent000_unkPA3_c16384_seed0,results_pa_confmanifold_refined/23-23_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
25,ref_base_ent002_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-28_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
24,ref_base_ent002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-26_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
19,ref_base_drop040_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-11_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
32,ref_base_ent010_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-45_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
5,ref_base_ls005_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-38_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
56,ref_pms_lr2e4_unkPA2_c16384_seed0,results_pa_confmanifold_refined/00-00_04-30-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
7,ref_base_ls005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-45_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
27,ref_base_ent002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
55,ref_pms_drop040_unkPA8_c16384_seed0,results_pa_confmanifold_refined/23-56_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
38,ref_base_lr2e4_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-04_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
6,ref_base_ls005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-42_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
54,ref_pms_drop040_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-54_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
3,ref_base_ctrl_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-33_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
35,ref_base_ent010_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
1,ref_base_ctrl_unkPA3_c16384_seed0,results_pa_confmanifold_refined/21-27_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
21,ref_base_drop050_unkPA3_c16384_seed0,results_pa_confmanifold_refined/22-18_04-29-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
20,ref_base_drop050_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-14_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
42,ref_pms_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-16_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
28,ref_base_ent005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-35_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
58,ref_pms_lr2e4_unkPA4_c16384_seed0,results_pa_confmanifold_refined/00-08_04-30-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
2,ref_base_ctrl_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-29_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
46,ref_pms_ent000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-25_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
22,ref_base_drop050_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-21_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
52,ref_pms_drop040_unkPA2_c16384_seed0,results_pa_confmanifold_refined/23-45_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
44,ref_pms_ent000_unkPA2_c16384_seed0,results_pa_confmanifold_refined/23-22_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
48,ref_pms_ent002_unkPA2_c16384_seed0,results_pa_confmanifold_refined/23-32_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
34,ref_base_ent010_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-52_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
36,ref_base_lr2e4_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-57_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
4,ref_base_ls005_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-36_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
26,ref_base_ent002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-31_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
40,ref_pms_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/23-08_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
18,ref_base_drop040_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-09_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
30,ref_base_ent005_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-41_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
50,ref_pms_ent002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-38_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
16,ref_base_drop040_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-06_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
10,ref_base_ls002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-53_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
14,ref_base_ls000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-02_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"

================================================================================
Running experiment 61/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "cosine",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0,
  "lambda_center": 0.0,
  "class_weight_mode": null,
  "grad_clip_norm": null,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_base_nocenter",
  "lr": 0.0005,
  "label_smoothing": 0.1,
  "entropy_loss_weight": 0.0,
  "mlp_dropout": 0.3,
  "unknown_pas": [
    "PA2"
  ],
  "run_name": "ref_base_nocenter_unkPA2_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.5570 | ce=0.5570 | ent=0.0000 | center=0.0000 | val_loss=0.1880 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.7454 | val_dqn_proxy_expanded5=0.7567

Epoch 002 | train_loss=0.3771 | ce=0.3771 | ent=0.0000 | center=0.0000 | val_loss=0.1357 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6549 | val_dqn_proxy_expanded5=0.6830

Epoch 003 | train_loss=0.3723 | ce=0.3723 | ent=0.0000 | center=0.0000 | val_loss=0.1372 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7451 | val_dqn_proxy_expanded5=0.7723

Epoch 004 | train_loss=0.3579 | ce=0.3579 | ent=0.0000 | center=0.0000 | val_loss=0.1618 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7602 | val_dqn_proxy_expanded5=0.7331

Epoch 005 | train_loss=0.3491 | ce=0.3491 | ent=0.0000 | center=0.0000 | val_loss=0.1036 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.6362 | val_dqn_proxy_expanded5=0.7219

Epoch 006 | train_loss=0.3348 | ce=0.3348 | ent=0.0000 | center=0.0000 | val_loss=0.0885 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.8782 | val_dqn_proxy_expanded5=0.8953

Epoch 007 | train_loss=0.3438 | ce=0.3438 | ent=0.0000 | center=0.0000 | val_loss=0.1096 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7472 | val_dqn_proxy_expanded5=0.7927

Epoch 008 | train_loss=0.3297 | ce=0.3297 | ent=0.0000 | center=0.0000 | val_loss=0.0760 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8391 | val_dqn_proxy_expanded5=0.8469

Epoch 009 | train_loss=0.3240 | ce=0.3240 | ent=0.0000 | center=0.0000 | val_loss=0.0855 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6348 | val_dqn_proxy_expanded5=0.7260

Epoch 010 | train_loss=0.3224 | ce=0.3224 | ent=0.0000 | center=0.0000 | val_loss=0.0947 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7677 | val_dqn_proxy_expanded5=0.8118

Epoch 011 | train_loss=0.3179 | ce=0.3179 | ent=0.0000 | center=0.0000 | val_loss=0.0976 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8226 | val_dqn_proxy_expanded5=0.8691

Epoch 012 | train_loss=0.3167 | ce=0.3167 | ent=0.0000 | center=0.0000 | val_loss=0.0929 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7468 | val_dqn_proxy_expanded5=0.8211

Epoch 013 | train_loss=0.3298 | ce=0.3298 | ent=0.0000 | center=0.0000 | val_loss=0.0966 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7173 | val_dqn_proxy_expanded5=0.7545

Epoch 014 | train_loss=0.3164 | ce=0.3164 | ent=0.0000 | center=0.0000 | val_loss=0.0980 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7548 | val_dqn_proxy_expanded5=0.8109

Epoch 015 | train_loss=0.3168 | ce=0.3168 | ent=0.0000 | center=0.0000 | val_loss=0.0762 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6501 | val_dqn_proxy_expanded5=0.7065

Epoch 016 | train_loss=0.3198 | ce=0.3198 | ent=0.0000 | center=0.0000 | val_loss=0.0968 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7197 | val_dqn_proxy_expanded5=0.7686

Epoch 017 | train_loss=0.3136 | ce=0.3136 | ent=0.0000 | center=0.0000 | val_loss=0.1009 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6666 | val_dqn_proxy_expanded5=0.6948

Epoch 018 | train_loss=0.3114 | ce=0.3114 | ent=0.0000 | center=0.0000 | val_loss=0.0966 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7390 | val_dqn_proxy_expanded5=0.7977

Epoch 019 | train_loss=0.3130 | ce=0.3130 | ent=0.0000 | center=0.0000 | val_loss=0.0917 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8865 | val_dqn_proxy_expanded5=0.9055

Epoch 020 | train_loss=0.3142 | ce=0.3142 | ent=0.0000 | center=0.0000 | val_loss=0.1075 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8132 | val_dqn_proxy_expanded5=0.8354

Epoch 021 | train_loss=0.3141 | ce=0.3141 | ent=0.0000 | center=0.0000 | val_loss=0.0798 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7463 | val_dqn_proxy_expanded5=0.7792

Epoch 022 | train_loss=0.3170 | ce=0.3170 | ent=0.0000 | center=0.0000 | val_loss=0.0851 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9346 | val_dqn_proxy_expanded5=0.9447

Epoch 023 | train_loss=0.3126 | ce=0.3126 | ent=0.0000 | center=0.0000 | val_loss=0.0835 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9408 | val_dqn_proxy_expanded5=0.9437

Epoch 024 | train_loss=0.3132 | ce=0.3132 | ent=0.0000 | center=0.0000 | val_loss=0.1064 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8400 | val_dqn_proxy_expanded5=0.8476

Epoch 025 | train_loss=0.3215 | ce=0.3215 | ent=0.0000 | center=0.0000 | val_loss=0.1005 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9739 | val_dqn_proxy_expanded5=0.9781

Epoch 026 | train_loss=0.3141 | ce=0.3141 | ent=0.0000 | center=0.0000 | val_loss=0.0996 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8629 | val_dqn_proxy_expanded5=0.8566

Epoch 027 | train_loss=0.3117 | ce=0.3117 | ent=0.0000 | center=0.0000 | val_loss=0.1075 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7097 | val_dqn_proxy_expanded5=0.7095

Epoch 028 | train_loss=0.3106 | ce=0.3106 | ent=0.0000 | center=0.0000 | val_loss=0.0930 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9068 | val_dqn_proxy_expanded5=0.8997

Epoch 029 | train_loss=0.3093 | ce=0.3093 | ent=0.0000 | center=0.0000 | val_loss=0.0876 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8175 | val_dqn_proxy_expanded5=0.8414

Epoch 030 | train_loss=0.3109 | ce=0.3109 | ent=0.0000 | center=0.0000 | val_loss=0.1956 | val_acc=0.9593 | val_macro_f1=0.9592 | val_dqn_proxy_softmax3=0.8715 | val_dqn_proxy_expanded5=0.8926

Epoch 031 | train_loss=0.3179 | ce=0.3179 | ent=0.0000 | center=0.0000 | val_loss=0.0914 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7758 | val_dqn_proxy_expanded5=0.7949

Epoch 032 | train_loss=0.3130 | ce=0.3130 | ent=0.0000 | center=0.0000 | val_loss=0.0905 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9411 | val_dqn_proxy_expanded5=0.9392

Epoch 033 | train_loss=0.3174 | ce=0.3174 | ent=0.0000 | center=0.0000 | val_loss=0.0788 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.5583 | val_dqn_proxy_expanded5=0.5896

Epoch 034 | train_loss=0.3126 | ce=0.3126 | ent=0.0000 | center=0.0000 | val_loss=0.1020 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8453 | val_dqn_proxy_expanded5=0.8724

Epoch 035 | train_loss=0.3103 | ce=0.3103 | ent=0.0000 | center=0.0000 | val_loss=0.1001 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7055 | val_dqn_proxy_expanded5=0.7348

Epoch 036 | train_loss=0.3124 | ce=0.3124 | ent=0.0000 | center=0.0000 | val_loss=0.0982 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7329 | val_dqn_proxy_expanded5=0.7737

Epoch 037 | train_loss=0.3111 | ce=0.3111 | ent=0.0000 | center=0.0000 | val_loss=0.0953 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7056 | val_dqn_proxy_expanded5=0.7333

Epoch 038 | train_loss=0.3102 | ce=0.3102 | ent=0.0000 | center=0.0000 | val_loss=0.0991 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7803 | val_dqn_proxy_expanded5=0.7971

Epoch 039 | train_loss=0.3106 | ce=0.3106 | ent=0.0000 | center=0.0000 | val_loss=0.1069 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7652 | val_dqn_proxy_expanded5=0.7842

Epoch 040 | train_loss=0.3113 | ce=0.3113 | ent=0.0000 | center=0.0000 | val_loss=0.0974 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.6633 | val_dqn_proxy_expanded5=0.7126
Early stopping at epoch 40 (best epoch: 25)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
60,ref_base_nocenter_unkPA2_c16384_seed0,results_pa_confmanifold_refined/00-12_04-30-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
31,ref_base_ent005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-43_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
59,ref_pms_lr2e4_unkPA8_c16384_seed0,results_pa_confmanifold_refined/00-10_04-30-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
23,ref_base_drop050_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-25_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
11,ref_base_ls002_unkPA8_c16384_seed0,results_pa_confmanifold_refined/21-54_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50,ref_pms_ent002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-38_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
16,ref_base_drop040_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-06_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
10,ref_base_ls002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-53_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
14,ref_base_ls000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-02_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"

================================================================================
Running experiment 62/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "cosine",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0,
  "lambda_center": 0.0,
  "class_weight_mode": null,
  "grad_clip_norm": null,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_base_nocenter",
  "lr": 0.0005,
  "label_smoothing": 0.1,
  "entropy_loss_weight": 0.0,
  "mlp_dropout": 0.3,
  "unknown_pas": [
    "PA3"
  ],
  "run_name": "ref_base_nocenter_unkPA3_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.6258 | ce=0.6258 | ent=0.0000 | center=0.0000 | val_loss=0.2410 | val_acc=0.9148 | val_macro_f1=0.9138 | val_dqn_proxy_softmax3=0.7711 | val_dqn_proxy_expanded5=0.7661

Epoch 002 | train_loss=0.4467 | ce=0.4467 | ent=0.0000 | center=0.0000 | val_loss=0.3615 | val_acc=0.8519 | val_macro_f1=0.8460 | val_dqn_proxy_softmax3=0.7985 | val_dqn_proxy_expanded5=0.7476

Epoch 003 | train_loss=0.4422 | ce=0.4422 | ent=0.0000 | center=0.0000 | val_loss=0.1559 | val_acc=0.9667 | val_macro_f1=0.9664 | val_dqn_proxy_softmax3=0.9032 | val_dqn_proxy_expanded5=0.8853

Epoch 004 | train_loss=0.3863 | ce=0.3863 | ent=0.0000 | center=0.0000 | val_loss=0.1873 | val_acc=0.9370 | val_macro_f1=0.9367 | val_dqn_proxy_softmax3=0.8225 | val_dqn_proxy_expanded5=0.8344

Epoch 005 | train_loss=0.3775 | ce=0.3775 | ent=0.0000 | center=0.0000 | val_loss=0.1298 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9204 | val_dqn_proxy_expanded5=0.8951

Epoch 006 | train_loss=0.3671 | ce=0.3671 | ent=0.0000 | center=0.0000 | val_loss=0.1031 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9303 | val_dqn_proxy_expanded5=0.9214

Epoch 007 | train_loss=0.3752 | ce=0.3752 | ent=0.0000 | center=0.0000 | val_loss=0.1542 | val_acc=0.9593 | val_macro_f1=0.9591 | val_dqn_proxy_softmax3=0.8521 | val_dqn_proxy_expanded5=0.8444

Epoch 008 | train_loss=0.3694 | ce=0.3694 | ent=0.0000 | center=0.0000 | val_loss=0.2062 | val_acc=0.9370 | val_macro_f1=0.9365 | val_dqn_proxy_softmax3=0.8732 | val_dqn_proxy_expanded5=0.8829

Epoch 009 | train_loss=0.3700 | ce=0.3700 | ent=0.0000 | center=0.0000 | val_loss=0.0986 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9467 | val_dqn_proxy_expanded5=0.9498

Epoch 010 | train_loss=0.3837 | ce=0.3837 | ent=0.0000 | center=0.0000 | val_loss=0.1306 | val_acc=0.9741 | val_macro_f1=0.9740 | val_dqn_proxy_softmax3=0.9262 | val_dqn_proxy_expanded5=0.9144

Epoch 011 | train_loss=0.3400 | ce=0.3400 | ent=0.0000 | center=0.0000 | val_loss=0.1020 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9770 | val_dqn_proxy_expanded5=0.9790

Epoch 012 | train_loss=0.3377 | ce=0.3377 | ent=0.0000 | center=0.0000 | val_loss=0.1209 | val_acc=0.9704 | val_macro_f1=0.9703 | val_dqn_proxy_softmax3=0.9517 | val_dqn_proxy_expanded5=0.9516

Epoch 013 | train_loss=0.3383 | ce=0.3383 | ent=0.0000 | center=0.0000 | val_loss=0.1017 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9807 | val_dqn_proxy_expanded5=0.9820

Epoch 014 | train_loss=0.3289 | ce=0.3289 | ent=0.0000 | center=0.0000 | val_loss=0.0874 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9629 | val_dqn_proxy_expanded5=0.9607

Epoch 015 | train_loss=0.3447 | ce=0.3447 | ent=0.0000 | center=0.0000 | val_loss=0.1086 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9500 | val_dqn_proxy_expanded5=0.9528

Epoch 016 | train_loss=0.3387 | ce=0.3387 | ent=0.0000 | center=0.0000 | val_loss=0.1066 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9262 | val_dqn_proxy_expanded5=0.9020

Epoch 017 | train_loss=0.3267 | ce=0.3267 | ent=0.0000 | center=0.0000 | val_loss=0.0942 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9795 | val_dqn_proxy_expanded5=0.9799

Epoch 018 | train_loss=0.3485 | ce=0.3485 | ent=0.0000 | center=0.0000 | val_loss=0.1121 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.9640 | val_dqn_proxy_expanded5=0.9663

Epoch 019 | train_loss=0.3385 | ce=0.3385 | ent=0.0000 | center=0.0000 | val_loss=0.0931 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9841 | val_dqn_proxy_expanded5=0.9856

Epoch 020 | train_loss=0.3261 | ce=0.3261 | ent=0.0000 | center=0.0000 | val_loss=0.1009 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9700 | val_dqn_proxy_expanded5=0.9629

Epoch 021 | train_loss=0.3376 | ce=0.3376 | ent=0.0000 | center=0.0000 | val_loss=0.0905 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9832 | val_dqn_proxy_expanded5=0.9712

Epoch 022 | train_loss=0.3256 | ce=0.3256 | ent=0.0000 | center=0.0000 | val_loss=0.1292 | val_acc=0.9630 | val_macro_f1=0.9629 | val_dqn_proxy_softmax3=0.9683 | val_dqn_proxy_expanded5=0.9709

Epoch 023 | train_loss=0.3319 | ce=0.3319 | ent=0.0000 | center=0.0000 | val_loss=0.1134 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.9426 | val_dqn_proxy_expanded5=0.9356

Epoch 024 | train_loss=0.3189 | ce=0.3189 | ent=0.0000 | center=0.0000 | val_loss=0.0753 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9768 | val_dqn_proxy_expanded5=0.9644

Epoch 025 | train_loss=0.3131 | ce=0.3131 | ent=0.0000 | center=0.0000 | val_loss=0.0792 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9727 | val_dqn_proxy_expanded5=0.9744

Epoch 026 | train_loss=0.3323 | ce=0.3323 | ent=0.0000 | center=0.0000 | val_loss=0.0983 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.8936 | val_dqn_proxy_expanded5=0.8982

Epoch 027 | train_loss=0.3378 | ce=0.3378 | ent=0.0000 | center=0.0000 | val_loss=0.0882 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9800 | val_dqn_proxy_expanded5=0.9623

Epoch 028 | train_loss=0.3193 | ce=0.3193 | ent=0.0000 | center=0.0000 | val_loss=0.0951 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9387 | val_dqn_proxy_expanded5=0.9516

Epoch 029 | train_loss=0.3367 | ce=0.3367 | ent=0.0000 | center=0.0000 | val_loss=0.0985 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.8480 | val_dqn_proxy_expanded5=0.8496

Epoch 030 | train_loss=0.3266 | ce=0.3266 | ent=0.0000 | center=0.0000 | val_loss=0.0756 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9793 | val_dqn_proxy_expanded5=0.9829

Epoch 031 | train_loss=0.3262 | ce=0.3262 | ent=0.0000 | center=0.0000 | val_loss=0.1103 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9633 | val_dqn_proxy_expanded5=0.9676

Epoch 032 | train_loss=0.3165 | ce=0.3165 | ent=0.0000 | center=0.0000 | val_loss=0.0961 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.9843 | val_dqn_proxy_expanded5=0.9749

Epoch 033 | train_loss=0.3274 | ce=0.3274 | ent=0.0000 | center=0.0000 | val_loss=0.0862 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9849 | val_dqn_proxy_expanded5=0.9687

Epoch 034 | train_loss=0.3314 | ce=0.3314 | ent=0.0000 | center=0.0000 | val_loss=0.1267 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9270 | val_dqn_proxy_expanded5=0.9158

Epoch 035 | train_loss=0.3272 | ce=0.3272 | ent=0.0000 | center=0.0000 | val_loss=0.1551 | val_acc=0.9741 | val_macro_f1=0.9740 | val_dqn_proxy_softmax3=0.9802 | val_dqn_proxy_expanded5=0.9735

Epoch 036 | train_loss=0.3273 | ce=0.3273 | ent=0.0000 | center=0.0000 | val_loss=0.0888 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9826 | val_dqn_proxy_expanded5=0.9484

Epoch 037 | train_loss=0.3321 | ce=0.3321 | ent=0.0000 | center=0.0000 | val_loss=0.0928 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9227 | val_dqn_proxy_expanded5=0.8955

Epoch 038 | train_loss=0.3288 | ce=0.3288 | ent=0.0000 | center=0.0000 | val_loss=0.1208 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9386 | val_dqn_proxy_expanded5=0.9400

Epoch 039 | train_loss=0.3244 | ce=0.3244 | ent=0.0000 | center=0.0000 | val_loss=0.0961 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9703 | val_dqn_proxy_expanded5=0.9737

Epoch 040 | train_loss=0.3170 | ce=0.3170 | ent=0.0000 | center=0.0000 | val_loss=0.1038 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9807 | val_dqn_proxy_expanded5=0.9703

Epoch 041 | train_loss=0.3259 | ce=0.3259 | ent=0.0000 | center=0.0000 | val_loss=0.0744 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9810 | val_dqn_proxy_expanded5=0.9566

Epoch 042 | train_loss=0.3175 | ce=0.3175 | ent=0.0000 | center=0.0000 | val_loss=0.0887 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9860 | val_dqn_proxy_expanded5=0.9649

Epoch 043 | train_loss=0.3155 | ce=0.3155 | ent=0.0000 | center=0.0000 | val_loss=0.0951 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9576 | val_dqn_proxy_expanded5=0.9460

Epoch 044 | train_loss=0.3409 | ce=0.3409 | ent=0.0000 | center=0.0000 | val_loss=0.0941 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.9858 | val_dqn_proxy_expanded5=0.9739

Epoch 045 | train_loss=0.3138 | ce=0.3138 | ent=0.0000 | center=0.0000 | val_loss=0.1054 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9789 | val_dqn_proxy_expanded5=0.9271

Epoch 046 | train_loss=0.3237 | ce=0.3237 | ent=0.0000 | center=0.0000 | val_loss=0.0944 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9650 | val_dqn_proxy_expanded5=0.9402

Epoch 047 | train_loss=0.3274 | ce=0.3274 | ent=0.0000 | center=0.0000 | val_loss=0.0951 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9634 | val_dqn_proxy_expanded5=0.9211

Epoch 048 | train_loss=0.3241 | ce=0.3241 | ent=0.0000 | center=0.0000 | val_loss=0.0904 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9550 | val_dqn_proxy_expanded5=0.9048

Epoch 049 | train_loss=0.3170 | ce=0.3170 | ent=0.0000 | center=0.0000 | val_loss=0.0812 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9775 | val_dqn_proxy_expanded5=0.9729

Epoch 050 | train_loss=0.3256 | ce=0.3256 | ent=0.0000 | center=0.0000 | val_loss=0.0829 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.9768 | val_dqn_proxy_expanded5=0.9722

Epoch 051 | train_loss=0.3159 | ce=0.3159 | ent=0.0000 | center=0.0000 | val_loss=0.1069 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.9731 | val_dqn_proxy_expanded5=0.9393

Epoch 052 | train_loss=0.3195 | ce=0.3195 | ent=0.0000 | center=0.0000 | val_loss=0.0989 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9837 | val_dqn_proxy_expanded5=0.9203

Epoch 053 | train_loss=0.3156 | ce=0.3156 | ent=0.0000 | center=0.0000 | val_loss=0.0948 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9405 | val_dqn_proxy_expanded5=0.8798

Epoch 054 | train_loss=0.3200 | ce=0.3200 | ent=0.0000 | center=0.0000 | val_loss=0.0971 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8729 | val_dqn_proxy_expanded5=0.8243

Epoch 055 | train_loss=0.3193 | ce=0.3193 | ent=0.0000 | center=0.0000 | val_loss=0.1690 | val_acc=0.9593 | val_macro_f1=0.9591 | val_dqn_proxy_softmax3=0.9156 | val_dqn_proxy_expanded5=0.8597

Epoch 056 | train_loss=0.3232 | ce=0.3232 | ent=0.0000 | center=0.0000 | val_loss=0.0884 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9698 | val_dqn_proxy_expanded5=0.9349

Epoch 057 | train_loss=0.3198 | ce=0.3198 | ent=0.0000 | center=0.0000 | val_loss=0.0707 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.9551 | val_dqn_proxy_expanded5=0.9163
Early stopping at epoch 57 (best epoch: 42)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
60,ref_base_nocenter_unkPA2_c16384_seed0,results_pa_confmanifold_refined/00-12_04-30-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
31,ref_base_ent005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-43_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
61,ref_base_nocenter_unkPA3_c16384_seed0,results_pa_confmanifold_refined/00-15_04-30-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
59,ref_pms_lr2e4_unkPA8_c16384_seed0,results_pa_confmanifold_refined/00-10_04-30-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
23,ref_base_drop050_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-25_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50,ref_pms_ent002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/23-38_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
16,ref_base_drop040_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-06_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
10,ref_base_ls002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-53_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
14,ref_base_ls000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-02_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"

================================================================================
Running experiment 63/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "cosine",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0,
  "lambda_center": 0.0,
  "class_weight_mode": null,
  "grad_clip_norm": null,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_base_nocenter",
  "lr": 0.0005,
  "label_smoothing": 0.1,
  "entropy_loss_weight": 0.0,
  "mlp_dropout": 0.3,
  "unknown_pas": [
    "PA4"
  ],
  "run_name": "ref_base_nocenter_unkPA4_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.6158 | ce=0.6158 | ent=0.0000 | center=0.0000 | val_loss=0.2528 | val_acc=0.9222 | val_macro_f1=0.9221 | val_dqn_proxy_softmax3=0.7022 | val_dqn_proxy_expanded5=0.6999

Epoch 002 | train_loss=0.4555 | ce=0.4555 | ent=0.0000 | center=0.0000 | val_loss=0.2143 | val_acc=0.9704 | val_macro_f1=0.9706 | val_dqn_proxy_softmax3=0.7671 | val_dqn_proxy_expanded5=0.7047

Epoch 003 | train_loss=0.4426 | ce=0.4426 | ent=0.0000 | center=0.0000 | val_loss=0.1855 | val_acc=0.9519 | val_macro_f1=0.9521 | val_dqn_proxy_softmax3=0.8220 | val_dqn_proxy_expanded5=0.7470

Epoch 004 | train_loss=0.4127 | ce=0.4127 | ent=0.0000 | center=0.0000 | val_loss=0.1071 | val_acc=0.9704 | val_macro_f1=0.9703 | val_dqn_proxy_softmax3=0.8728 | val_dqn_proxy_expanded5=0.7976

Epoch 005 | train_loss=0.3744 | ce=0.3744 | ent=0.0000 | center=0.0000 | val_loss=0.1438 | val_acc=0.9593 | val_macro_f1=0.9591 | val_dqn_proxy_softmax3=0.7220 | val_dqn_proxy_expanded5=0.6784

Epoch 006 | train_loss=0.3676 | ce=0.3676 | ent=0.0000 | center=0.0000 | val_loss=0.0942 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.6776 | val_dqn_proxy_expanded5=0.6655

Epoch 007 | train_loss=0.3716 | ce=0.3716 | ent=0.0000 | center=0.0000 | val_loss=0.0945 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.7391 | val_dqn_proxy_expanded5=0.6987

Epoch 008 | train_loss=0.3454 | ce=0.3454 | ent=0.0000 | center=0.0000 | val_loss=0.1558 | val_acc=0.9593 | val_macro_f1=0.9591 | val_dqn_proxy_softmax3=0.7435 | val_dqn_proxy_expanded5=0.6869

Epoch 009 | train_loss=0.3533 | ce=0.3533 | ent=0.0000 | center=0.0000 | val_loss=0.0931 | val_acc=0.9889 | val_macro_f1=0.9889 | val_dqn_proxy_softmax3=0.7698 | val_dqn_proxy_expanded5=0.7431

Epoch 010 | train_loss=0.3482 | ce=0.3482 | ent=0.0000 | center=0.0000 | val_loss=0.1164 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.7478 | val_dqn_proxy_expanded5=0.7252

Epoch 011 | train_loss=0.3280 | ce=0.3280 | ent=0.0000 | center=0.0000 | val_loss=0.0830 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.7686 | val_dqn_proxy_expanded5=0.7167

Epoch 012 | train_loss=0.3304 | ce=0.3304 | ent=0.0000 | center=0.0000 | val_loss=0.1000 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.7668 | val_dqn_proxy_expanded5=0.7113

Epoch 013 | train_loss=0.3377 | ce=0.3377 | ent=0.0000 | center=0.0000 | val_loss=0.1105 | val_acc=0.9778 | val_macro_f1=0.9778 | val_dqn_proxy_softmax3=0.7602 | val_dqn_proxy_expanded5=0.7053

Epoch 014 | train_loss=0.3494 | ce=0.3494 | ent=0.0000 | center=0.0000 | val_loss=0.0920 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7727 | val_dqn_proxy_expanded5=0.7149

Epoch 015 | train_loss=0.3455 | ce=0.3455 | ent=0.0000 | center=0.0000 | val_loss=0.0686 | val_acc=1.0000 | val_macro_f1=1.0000 | val_dqn_proxy_softmax3=0.7598 | val_dqn_proxy_expanded5=0.7067

Epoch 016 | train_loss=0.3323 | ce=0.3323 | ent=0.0000 | center=0.0000 | val_loss=0.1084 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.7744 | val_dqn_proxy_expanded5=0.7143

Epoch 017 | train_loss=0.3510 | ce=0.3510 | ent=0.0000 | center=0.0000 | val_loss=0.1006 | val_acc=0.9963 | val_macro_f1=0.9963 | val_dqn_proxy_softmax3=0.7949 | val_dqn_proxy_expanded5=0.7226

Epoch 018 | train_loss=0.3428 | ce=0.3428 | ent=0.0000 | center=0.0000 | val_loss=0.1008 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7427 | val_dqn_proxy_expanded5=0.6987

Epoch 019 | train_loss=0.3254 | ce=0.3254 | ent=0.0000 | center=0.0000 | val_loss=0.1061 | val_acc=0.9852 | val_macro_f1=0.9852 | val_dqn_proxy_softmax3=0.7530 | val_dqn_proxy_expanded5=0.7110
Early stopping at epoch 19 (best epoch: 4)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
60,ref_base_nocenter_unkPA2_c16384_seed0,results_pa_confmanifold_refined/00-12_04-30-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
31,ref_base_ent005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-43_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
61,ref_base_nocenter_unkPA3_c16384_seed0,results_pa_confmanifold_refined/00-15_04-30-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
59,ref_pms_lr2e4_unkPA8_c16384_seed0,results_pa_confmanifold_refined/00-10_04-30-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
23,ref_base_drop050_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-25_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
16,ref_base_drop040_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-06_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
10,ref_base_ls002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-53_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
14,ref_base_ls000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-02_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
62,ref_base_nocenter_unkPA4_c16384_seed0,results_pa_confmanifold_refined/00-19_04-30-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"

================================================================================
Running experiment 64/64
{
  "task": "pa",
  "split_mode": "open_pa",
  "normalize": true,
  "cache_len": 16384,
  "batch_size": 16,
  "seed": 0,
  "open_val_frac": 0.15,
  "build_balanced_val_open": true,
  "manifold_balance_seed": 0,
  "require_true_val_open": true,
  "allow_val_open_fallback": false,
  "confidence_temperature": 1.0,
  "early_stopping_mode": "open_conf",
  "model_selection_metric": "val_macro_f1",
  "open_conf_selection_metric": "dqn_proxy_softmax3",
  "scheduler_name": "cosine",
  "scheduler_factor": 0.5,
  "scheduler_patience": 5,
  "scheduler_min_lr": 1e-07,
  "epochs": 200,
  "early_stopping_patience": 15,
  "weight_decay": 0.0,
  "lambda_center": 0.0,
  "class_weight_mode": null,
  "grad_clip_norm": null,
  "save_root": "results_pa_confmanifold_refined",
  "tag": "ref_base_nocenter",
  "lr": 0.0005,
  "label_smoothing": 0.1,
  "entropy_loss_weight": 0.0,
  "mlp_dropout": 0.3,
  "unknown_pas": [
    "PA8"
  ],
  "run_name": "ref_base_nocenter_unkPA8_c16384_seed0"
}
================================================================================

Epoch 001 | train_loss=0.4868 | ce=0.4868 | ent=0.0000 | center=0.0000 | val_loss=0.1437 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9137 | val_dqn_proxy_expanded5=0.9210

Epoch 002 | train_loss=0.3554 | ce=0.3554 | ent=0.0000 | center=0.0000 | val_loss=0.1112 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8951 | val_dqn_proxy_expanded5=0.9083

Epoch 003 | train_loss=0.3396 | ce=0.3396 | ent=0.0000 | center=0.0000 | val_loss=0.1082 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9234 | val_dqn_proxy_expanded5=0.9323

Epoch 004 | train_loss=0.3382 | ce=0.3382 | ent=0.0000 | center=0.0000 | val_loss=0.1173 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.9725 | val_dqn_proxy_expanded5=0.9734

Epoch 005 | train_loss=0.3337 | ce=0.3337 | ent=0.0000 | center=0.0000 | val_loss=0.1217 | val_acc=0.9815 | val_macro_f1=0.9815 | val_dqn_proxy_softmax3=0.8843 | val_dqn_proxy_expanded5=0.8943

Epoch 006 | train_loss=0.3243 | ce=0.3243 | ent=0.0000 | center=0.0000 | val_loss=0.0950 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9048 | val_dqn_proxy_expanded5=0.9068

Epoch 007 | train_loss=0.3141 | ce=0.3141 | ent=0.0000 | center=0.0000 | val_loss=0.0945 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9170 | val_dqn_proxy_expanded5=0.9197

Epoch 008 | train_loss=0.3075 | ce=0.3075 | ent=0.0000 | center=0.0000 | val_loss=0.1091 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9278 | val_dqn_proxy_expanded5=0.9342

Epoch 009 | train_loss=0.3078 | ce=0.3078 | ent=0.0000 | center=0.0000 | val_loss=0.1073 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9082 | val_dqn_proxy_expanded5=0.9121

Epoch 010 | train_loss=0.3068 | ce=0.3068 | ent=0.0000 | center=0.0000 | val_loss=0.0833 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9537 | val_dqn_proxy_expanded5=0.9557

Epoch 011 | train_loss=0.3053 | ce=0.3053 | ent=0.0000 | center=0.0000 | val_loss=0.0854 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9304 | val_dqn_proxy_expanded5=0.9362

Epoch 012 | train_loss=0.3077 | ce=0.3077 | ent=0.0000 | center=0.0000 | val_loss=0.0900 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9817 | val_dqn_proxy_expanded5=0.9813

Epoch 013 | train_loss=0.3071 | ce=0.3071 | ent=0.0000 | center=0.0000 | val_loss=0.0891 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9001 | val_dqn_proxy_expanded5=0.9148

Epoch 014 | train_loss=0.3057 | ce=0.3057 | ent=0.0000 | center=0.0000 | val_loss=0.0979 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9275 | val_dqn_proxy_expanded5=0.9331

Epoch 015 | train_loss=0.3056 | ce=0.3056 | ent=0.0000 | center=0.0000 | val_loss=0.1064 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8507 | val_dqn_proxy_expanded5=0.8745

Epoch 016 | train_loss=0.3062 | ce=0.3062 | ent=0.0000 | center=0.0000 | val_loss=0.0869 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9416 | val_dqn_proxy_expanded5=0.9492

Epoch 017 | train_loss=0.3043 | ce=0.3043 | ent=0.0000 | center=0.0000 | val_loss=0.1042 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9210 | val_dqn_proxy_expanded5=0.9245

Epoch 018 | train_loss=0.3047 | ce=0.3047 | ent=0.0000 | center=0.0000 | val_loss=0.0931 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9316 | val_dqn_proxy_expanded5=0.9356

Epoch 019 | train_loss=0.3055 | ce=0.3055 | ent=0.0000 | center=0.0000 | val_loss=0.0890 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8696 | val_dqn_proxy_expanded5=0.8699

Epoch 020 | train_loss=0.3054 | ce=0.3054 | ent=0.0000 | center=0.0000 | val_loss=0.0924 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9176 | val_dqn_proxy_expanded5=0.9149

Epoch 021 | train_loss=0.3067 | ce=0.3067 | ent=0.0000 | center=0.0000 | val_loss=0.0797 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8872 | val_dqn_proxy_expanded5=0.8851

Epoch 022 | train_loss=0.3048 | ce=0.3048 | ent=0.0000 | center=0.0000 | val_loss=0.0996 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9468 | val_dqn_proxy_expanded5=0.9311

Epoch 023 | train_loss=0.3063 | ce=0.3063 | ent=0.0000 | center=0.0000 | val_loss=0.0993 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.8697 | val_dqn_proxy_expanded5=0.8519

Epoch 024 | train_loss=0.3046 | ce=0.3046 | ent=0.0000 | center=0.0000 | val_loss=0.0993 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9098 | val_dqn_proxy_expanded5=0.8735

Epoch 025 | train_loss=0.3038 | ce=0.3038 | ent=0.0000 | center=0.0000 | val_loss=0.0919 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9643 | val_dqn_proxy_expanded5=0.9380

Epoch 026 | train_loss=0.3096 | ce=0.3096 | ent=0.0000 | center=0.0000 | val_loss=0.0772 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9367 | val_dqn_proxy_expanded5=0.9135

Epoch 027 | train_loss=0.3592 | ce=0.3592 | ent=0.0000 | center=0.0000 | val_loss=0.1138 | val_acc=0.9926 | val_macro_f1=0.9926 | val_dqn_proxy_softmax3=0.9079 | val_dqn_proxy_expanded5=0.8883
Early stopping at epoch 27 (best epoch: 12)

,run_name,save_dir,task,split_mode,unknown_pas,known_pa_names,unknown_pa_names,open_label,known_label_map,num_classes,...,scheduler_name,early_stopping_mode,open_conf_selection_metric,epochs,seed,source_type,source_name,dataset_tag,noise_tag,available_checkpoints
60,ref_base_nocenter_unkPA2_c16384_seed0,results_pa_confmanifold_refined/00-12_04-30-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
31,ref_base_ent005_unkPA8_c16384_seed0,results_pa_confmanifold_refined/22-43_04-29-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
63,ref_base_nocenter_unkPA8_c16384_seed0,results_pa_confmanifold_refined/00-21_04-30-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
61,ref_base_nocenter_unkPA3_c16384_seed0,results_pa_confmanifold_refined/00-15_04-30-26...,pa,open_pa,[PA3],"[PA2, PA4, PA8]",[PA3],-1,"{0: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, epoch_50, final_model]"
59,ref_pms_lr2e4_unkPA8_c16384_seed0,results_pa_confmanifold_refined/00-10_04-30-26...,pa,open_pa,[PA8],"[PA2, PA3, PA4]",[PA8],-1,"{0: 0, 1: 1, 2: 2}",3,...,plateau,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,ref_base_ctrl_unkPA2_c16384_seed0,results_pa_confmanifold_refined/21-25_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, epoch_20, final_model]"
16,ref_base_drop040_unkPA2_c16384_seed0,results_pa_confmanifold_refined/22-06_04-29-26...,pa,open_pa,[PA2],"[PA3, PA4, PA8]",[PA2],-1,"{1: 0, 2: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
10,ref_base_ls002_unkPA4_c16384_seed0,results_pa_confmanifold_refined/21-53_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
14,ref_base_ls000_unkPA4_c16384_seed0,results_pa_confmanifold_refined/22-02_04-29-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"
62,ref_base_nocenter_unkPA4_c16384_seed0,results_pa_confmanifold_refined/00-19_04-30-26...,pa,open_pa,[PA4],"[PA2, PA3, PA8]",[PA4],-1,"{0: 0, 1: 1, 3: 2}",3,...,cosine,open_conf,dqn_proxy_softmax3,200,0,digital,pilot_noisy_torch,None,None,"[best_model, final_model]"